local CopeVestmentMaker = {}
local PRODUCTS = {
    linen_alb = { name = "Lnena alba", linenCost = 2, time = 2, cost = 25, sanctity = 4, description = "Preprosta lnena alba za duhovnike." },
    wool_chasuble = { name = "Volnena kazula", woolCost = 2, linenCost = 1, time = 4, cost = 80, sanctity = 8, prestige = 2, description = "Volnena kazula za mašo." },
    silk_stole = { name = "Svileni štol", silkCost = 2, time = 3, cost = 90, sanctity = 9, prestige = 3, happiness = 1, description = "Svileni štol z vezenim križem." },
    embroidered_cope = { name = "Vezena pluvial", silkCost = 3, threadCost = 2, time = 6, cost = 280, sanctity = 14, prestige = 8, happiness = 2, description = "Vezena pluvialna capa za slovesnosti." },
    gold_thread_cope = { name = "Zlatorobna pluvial", silkCost = 3, goldCost = 1, threadCost = 2, time = 9, cost = 620, sanctity = 18, prestige = 16, happiness = 4, description = "Pluvial z zlatimi nitmi za škofe." },
    royal_pontifical_vestment = { name = "Kraljevski pontifikalno oblačilo", silkCost = 5, goldCost = 2, silverCost = 1, jewelCost = 2, pearlCost = 1, threadCost = 3, time = 14, cost = 1800, sanctity = 30, prestige = 50, happiness = 10, description = "Veliko pontifikalno oblačilo z dragulji in biseri za nadškofa." },
}
local BUILDINGS = {
    workshop = { name = "Obelniška delavnica", cost = { gold = 280, wood = 120 }, upkeep = 7, qualityBonus = 5 },
    sewing_room = { name = "Šivalnica", cost = { gold = 850, wood = 220, stone = 200, silk = 6 }, upkeep = 20, qualityBonus = 18 },
    embroidery_room = { name = "Vezenilnica", cost = { gold = 1800, wood = 300, stone = 400, silver = 25, thread = 8 }, upkeep = 42, qualityBonus = 30 },
    royal_vestment_atelier = { name = "Kraljevski atelje oblačil", cost = { gold = 7000, wood = 600, stone = 800, gold = 50, silk = 20 }, upkeep = 130, qualityBonus = 55, prestigeBonus = 33 },
}
CopeVestmentMaker.linenStock = 14; CopeVestmentMaker.woolStock = 12; CopeVestmentMaker.silkStock = 12; CopeVestmentMaker.threadStock = 10; CopeVestmentMaker.goldStock = 6; CopeVestmentMaker.silverStock = 6; CopeVestmentMaker.jewelStock = 4; CopeVestmentMaker.pearlStock = 4
CopeVestmentMaker.productStock = {}; CopeVestmentMaker.buildings = {}; CopeVestmentMaker.maker = nil; CopeVestmentMaker.activeMaking = {}; CopeVestmentMaker.totalProducts = 0; CopeVestmentMaker.dayTimer = 0
function CopeVestmentMaker.init() CopeVestmentMaker.linenStock=14; CopeVestmentMaker.woolStock=12; CopeVestmentMaker.silkStock=12; CopeVestmentMaker.threadStock=10; CopeVestmentMaker.goldStock=6; CopeVestmentMaker.silverStock=6; CopeVestmentMaker.jewelStock=4; CopeVestmentMaker.pearlStock=4; CopeVestmentMaker.productStock={}; CopeVestmentMaker.buildings={}; CopeVestmentMaker.maker=nil; CopeVestmentMaker.activeMaking={}; CopeVestmentMaker.totalProducts=0; CopeVestmentMaker.dayTimer=0; print("[CopeVestmentMaker] Royal Cope & Vestment Maker System initialized (6 products, 4 buildings)") end
function CopeVestmentMaker.hireMaker(n,s) s=s or math.random(50,90); local c=480+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CopeVestmentMaker.maker={name=n or ("Obelničar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Obelničar najet: %s (spretnost: %d)",CopeVestmentMaker.maker.name,s),"success") end; return true end
function CopeVestmentMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CopeVestmentMaker.build(id) local ok,e=CopeVestmentMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CopeVestmentMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CopeVestmentMaker.getQualityBonus() local b=0; for _,bd in ipairs(CopeVestmentMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CopeVestmentMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.linenCost and CopeVestmentMaker.linenStock<(d.linenCost or 0) then return false,"Premalo lana" end; if d.woolCost and CopeVestmentMaker.woolStock<(d.woolCost or 0) then return false,"Premalo volne" end; if d.silkCost and CopeVestmentMaker.silkStock<(d.silkCost or 0) then return false,"Premalo svile" end; if d.threadCost and CopeVestmentMaker.threadStock<(d.threadCost or 0) then return false,"Premalo niti" end; if d.goldCost and CopeVestmentMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.silverCost and CopeVestmentMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.jewelCost and CopeVestmentMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CopeVestmentMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CopeVestmentMaker.buildings==0 then return false,"Potrebna delavnica" end; if not CopeVestmentMaker.maker then return false,"Potreben obelničar" end; return true end
function CopeVestmentMaker.make(pt,qty) qty=qty or 1; local ok,e=CopeVestmentMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.linenCost then CopeVestmentMaker.linenStock=CopeVestmentMaker.linenStock-d.linenCost*qty end; if d.woolCost then CopeVestmentMaker.woolStock=CopeVestmentMaker.woolStock-d.woolCost*qty end; if d.silkCost then CopeVestmentMaker.silkStock=CopeVestmentMaker.silkStock-d.silkCost*qty end; if d.threadCost then CopeVestmentMaker.threadStock=CopeVestmentMaker.threadStock-d.threadCost*qty end; if d.goldCost then CopeVestmentMaker.goldStock=CopeVestmentMaker.goldStock-d.goldCost*qty end; if d.silverCost then CopeVestmentMaker.silverStock=CopeVestmentMaker.silverStock-d.silverCost*qty end; if d.jewelCost then CopeVestmentMaker.jewelStock=CopeVestmentMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CopeVestmentMaker.pearlStock=CopeVestmentMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CopeVestmentMaker.maker then t=math.max(1,t-math.floor(CopeVestmentMaker.maker.skill/12)) end; table.insert(CopeVestmentMaker.activeMaking,{id="vestment_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,sanctity=d.sanctity or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CopeVestmentMaker.completeMaking(m) local q=1.0+(CopeVestmentMaker.getQualityBonus()/100); if CopeVestmentMaker.maker then q=q+(CopeVestmentMaker.maker.skill/180) end; q=math.min(2.0,q); CopeVestmentMaker.productStock[m.productType]=(CopeVestmentMaker.productStock[m.productType] or 0)+m.quantity; CopeVestmentMaker.totalProducts=CopeVestmentMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CopeVestmentMaker.maker then CopeVestmentMaker.maker.itemsMade=CopeVestmentMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then CopeVestmentMaker.maker.skill=math.min(100,CopeVestmentMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Oblačilo izdelano: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"vestment.completed",{productName=m.productName,sanctity=m.sanctity}) end end
function CopeVestmentMaker.update(dt) if not _G.state then return end; CopeVestmentMaker.dayTimer=CopeVestmentMaker.dayTimer+dt; if CopeVestmentMaker.dayTimer>=30 then CopeVestmentMaker.dayTimer=0; for i=#CopeVestmentMaker.activeMaking,1,-1 do local m=CopeVestmentMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CopeVestmentMaker.completeMaking(m); table.remove(CopeVestmentMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CopeVestmentMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CopeVestmentMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CopeVestmentMaker.getStats() return {linenStock=CopeVestmentMaker.linenStock,woolStock=CopeVestmentMaker.woolStock,silkStock=CopeVestmentMaker.silkStock,threadStock=CopeVestmentMaker.threadStock,goldStock=CopeVestmentMaker.goldStock,silverStock=CopeVestmentMaker.silverStock,jewelStock=CopeVestmentMaker.jewelStock,pearlStock=CopeVestmentMaker.pearlStock,productStock=CopeVestmentMaker.productStock,numBuildings=#CopeVestmentMaker.buildings,hasMaker=CopeVestmentMaker.maker~=nil,makerName=CopeVestmentMaker.maker and CopeVestmentMaker.maker.name or "—",makerSkill=CopeVestmentMaker.maker and CopeVestmentMaker.maker.skill or 0,activeMaking=#CopeVestmentMaker.activeMaking,totalProducts=CopeVestmentMaker.totalProducts} end
return CopeVestmentMaker
