local ArmorMaker = {}
local PRODUCTS = {
    leather_jerkin = { name = "Usnjeni jopič", leatherCost = 3, time = 2, cost = 40, defense = 5, durability = 20, description = "Usnjeni jopič za lokostrelce." },
    chain_hauberk = { name = "Verižna srajca", ironCost = 4, leatherCost = 1, time = 5, cost = 180, defense = 12, durability = 35, prestige = 2, description = "Verižna srajca za viteze." },
    steel_chainmail = { name = "Jeklena veriga", steelCost = 3, ironCost = 2, leatherCost = 1, time = 7, cost = 420, defense = 18, durability = 50, prestige = 5, happiness = 1, description = "Jeklena verižna srajca." },
    plate_armor = { name = "Ploščati oklep", steelCost = 4, ironCost = 2, leatherCost = 2, time = 10, cost = 950, defense = 26, durability = 65, prestige = 11, happiness = 2, description = "Ploščati oklep za težko konjenico." },
    silver_plate = { name = "Srebrni ploščati oklep", steelCost = 4, silverCost = 2, ironCost = 2, leatherCost = 2, time = 13, cost = 1900, defense = 32, durability = 75, prestige = 18, happiness = 4, description = "Srebrno okrašen oklep za plemiče." },
    royal_ceremonial_armor = { name = "Kraljevski slovesni oklep", steelCost = 5, goldCost = 3, silverCost = 2, jewelCost = 3, pearlCost = 1, leatherCost = 2, time = 18, cost = 3800, defense = 48, durability = 100, prestige = 70, happiness = 14, description = "Veliki kraljevski slovesni oklep z zlatim, draguljnim in bisernim okovjem za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Okleparska delavnica", cost = { gold = 320, wood = 130, stone = 100 }, upkeep = 8, qualityBonus = 5 },
    forge = { name = "Okleparska kovačija", cost = { gold = 1000, wood = 220, stone = 250, iron = 10 }, upkeep = 25, qualityBonus = 18 },
    finishing_room = { name = "Dokončevalnica", cost = { gold = 2200, wood = 300, stone = 500, silver = 30, steel = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_armor_atelier = { name = "Kraljevski atelje oklepov", cost = { gold = 9000, wood = 600, stone = 900, gold = 100, jewel = 25 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
ArmorMaker.leatherStock = 14; ArmorMaker.ironStock = 14; ArmorMaker.steelStock = 12; ArmorMaker.silverStock = 8; ArmorMaker.goldStock = 6; ArmorMaker.jewelStock = 6; ArmorMaker.pearlStock = 4
ArmorMaker.productStock = {}; ArmorMaker.buildings = {}; ArmorMaker.maker = nil; ArmorMaker.activeMaking = {}; ArmorMaker.totalProducts = 0; ArmorMaker.dayTimer = 0
function ArmorMaker.init() ArmorMaker.leatherStock=14; ArmorMaker.ironStock=14; ArmorMaker.steelStock=12; ArmorMaker.silverStock=8; ArmorMaker.goldStock=6; ArmorMaker.jewelStock=6; ArmorMaker.pearlStock=4; ArmorMaker.productStock={}; ArmorMaker.buildings={}; ArmorMaker.maker=nil; ArmorMaker.activeMaking={}; ArmorMaker.totalProducts=0; ArmorMaker.dayTimer=0; print("[ArmorMaker] Royal Armor Maker System initialized (6 products, 4 buildings)") end
function ArmorMaker.hireMaker(n,s) s=s or math.random(55,95); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ArmorMaker.maker={name=n or ("Oklepar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Oklepar najet: %s (spretnost: %d)",ArmorMaker.maker.name,s),"success") end; return true end
function ArmorMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ArmorMaker.build(id) local ok,e=ArmorMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ArmorMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ArmorMaker.getQualityBonus() local b=0; for _,bd in ipairs(ArmorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ArmorMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.leatherCost and ArmorMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.ironCost and ArmorMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and ArmorMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.silverCost and ArmorMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ArmorMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ArmorMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ArmorMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ArmorMaker.buildings==0 then return false,"Potrebna delavnica" end; if not ArmorMaker.maker then return false,"Potreben oklepar" end; return true end
function ArmorMaker.make(pt,qty) qty=qty or 1; local ok,e=ArmorMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.leatherCost then ArmorMaker.leatherStock=ArmorMaker.leatherStock-d.leatherCost*qty end; if d.ironCost then ArmorMaker.ironStock=ArmorMaker.ironStock-d.ironCost*qty end; if d.steelCost then ArmorMaker.steelStock=ArmorMaker.steelStock-d.steelCost*qty end; if d.silverCost then ArmorMaker.silverStock=ArmorMaker.silverStock-d.silverCost*qty end; if d.goldCost then ArmorMaker.goldStock=ArmorMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ArmorMaker.jewelStock=ArmorMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ArmorMaker.pearlStock=ArmorMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ArmorMaker.maker then t=math.max(1,t-math.floor(ArmorMaker.maker.skill/12)) end; table.insert(ArmorMaker.activeMaking,{id="armor_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,defense=d.defense or 0,durability=d.durability or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ArmorMaker.completeMaking(m) local q=1.0+(ArmorMaker.getQualityBonus()/100); if ArmorMaker.maker then q=q+(ArmorMaker.maker.skill/150) end; q=math.min(2.5,q); ArmorMaker.productStock[m.productType]=(ArmorMaker.productStock[m.productType] or 0)+m.quantity; ArmorMaker.totalProducts=ArmorMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ArmorMaker.maker then ArmorMaker.maker.itemsMade=ArmorMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ArmorMaker.maker.skill=math.min(100,ArmorMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Oklep izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"armor.completed",{productName=m.productName,defense=m.defense,durability=m.durability}) end end
function ArmorMaker.update(dt) if not _G.state then return end; ArmorMaker.dayTimer=ArmorMaker.dayTimer+dt; if ArmorMaker.dayTimer>=30 then ArmorMaker.dayTimer=0; for i=#ArmorMaker.activeMaking,1,-1 do local m=ArmorMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ArmorMaker.completeMaking(m); table.remove(ArmorMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ArmorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ArmorMaker.maker then tu=tu+18 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ArmorMaker.getStats() return {leatherStock=ArmorMaker.leatherStock,ironStock=ArmorMaker.ironStock,steelStock=ArmorMaker.steelStock,silverStock=ArmorMaker.silverStock,goldStock=ArmorMaker.goldStock,jewelStock=ArmorMaker.jewelStock,pearlStock=ArmorMaker.pearlStock,productStock=ArmorMaker.productStock,numBuildings=#ArmorMaker.buildings,hasMaker=ArmorMaker.maker~=nil,makerName=ArmorMaker.maker and ArmorMaker.maker.name or "—",makerSkill=ArmorMaker.maker and ArmorMaker.maker.skill or 0,activeMaking=#ArmorMaker.activeMaking,totalProducts=ArmorMaker.totalProducts} end
return ArmorMaker
