local LeechCollector = {}
local PRODUCTS = {
    common_leech = { name = "Navadna pijavka", pondWaterCost = 1, time = 1, cost = 8, healingPower = 30, description = "Navadna pijavka za puščanje krvi." },
    medicinal_leech = { name = "Medicinska pijavka", pondWaterCost = 1, herbCost = 1, time = 2, cost = 22, healingPower = 50, prestige = 1, description = "Medicinska pijavka za zdravljenje." },
    blood_leech = { name = "Krvna pijavka", pondWaterCost = 1, herbCost = 1, silverCost = 1, time = 4, cost = 60, healingPower = 65, prestige = 3, happiness = 1, description = "Krvna pijavka za medicinske postopke." },
    silver_jar_leech = { name = "Srebrno kozarčna pijavka", pondWaterCost = 1, silverCost = 1, herbCost = 1, time = 6, cost = 150, healingPower = 78, prestige = 7, happiness = 2, description = "Pijavka v srebrnem kozarcu za zdravnike." },
    silver_treated_leech = { name = "Srebrno obdelana pijavka", pondWaterCost = 1, silverCost = 1, goldCost = 1, herbCost = 1, time = 9, cost = 340, healingPower = 90, prestige = 13, happiness = 3, description = "Srebrno obdelana pijavka za plemiške zdravnike." },
    royal_grand_leech = { name = "Kraljevski veliki pijavka", pondWaterCost = 2, goldCost = 1, silverCost = 1, jewelCost = 1, herbCost = 2, time = 14, cost = 1200, healingPower = 100, prestige = 33, happiness = 7, description = "Velika kraljevska pijavka z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Pijavkarska postaja", cost = { gold = 220, wood = 120, stone = 150 }, upkeep = 5, qualityBonus = 5 },
    leech_pond = { name = "Pijavkarski ribnik", cost = { gold = 750, wood = 220, stone = 300, water = 10 }, upkeep = 18, qualityBonus = 18 },
    storage_house = { name = "Shranjevalnica", cost = { gold = 1900, wood = 300, stone = 500, silver = 25, herb = 8 }, upkeep = 48, qualityBonus = 30 },
    royal_leech_atelier = { name = "Kraljevski atelje pijavk", cost = { gold = 7800, wood = 500, stone = 900, gold = 60, jewel = 20 }, upkeep = 155, qualityBonus = 55, prestigeBonus = 40 },
}
LeechCollector.pondWaterStock = 22; LeechCollector.herbStock = 16; LeechCollector.silverStock = 8; LeechCollector.goldStock = 6; LeechCollector.jewelStock = 6
LeechCollector.productStock = {}; LeechCollector.buildings = {}; LeechCollector.maker = nil; LeechCollector.activeMaking = {}; LeechCollector.totalProducts = 0; LeechCollector.dayTimer = 0
function LeechCollector.init() LeechCollector.pondWaterStock=22; LeechCollector.herbStock=16; LeechCollector.silverStock=8; LeechCollector.goldStock=6; LeechCollector.jewelStock=6; LeechCollector.productStock={}; LeechCollector.buildings={}; LeechCollector.maker=nil; LeechCollector.activeMaking={}; LeechCollector.totalProducts=0; LeechCollector.dayTimer=0; print("[LeechCollector] Royal Leech Collector System initialized (6 products, 4 buildings)") end
function LeechCollector.hireMaker(n,s) s=s or math.random(45,85); local c=440+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LeechCollector.maker={name=n or ("Pijavkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pijavkar najet: %s (spretnost: %d)",LeechCollector.maker.name,s),"success") end; return true end
function LeechCollector.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LeechCollector.build(id) local ok,e=LeechCollector.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LeechCollector.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LeechCollector.getQualityBonus() local b=0; for _,bd in ipairs(LeechCollector.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LeechCollector.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.pondWaterCost and LeechCollector.pondWaterStock<(d.pondWaterCost or 0) then return false,"Premalo ribniške vode" end; if d.herbCost and LeechCollector.herbStock<(d.herbCost or 0) then return false,"Premalo zelišč" end; if d.silverCost and LeechCollector.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and LeechCollector.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and LeechCollector.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #LeechCollector.buildings==0 then return false,"Potrebna delavnica" end; if not LeechCollector.maker then return false,"Potreben pijavkar" end; return true end
function LeechCollector.make(pt,qty) qty=qty or 5; local ok,e=LeechCollector.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.pondWaterCost then LeechCollector.pondWaterStock=LeechCollector.pondWaterStock-d.pondWaterCost*qty end; if d.herbCost then LeechCollector.herbStock=LeechCollector.herbStock-d.herbCost*qty end; if d.silverCost then LeechCollector.silverStock=LeechCollector.silverStock-d.silverCost*qty end; if d.goldCost then LeechCollector.goldStock=LeechCollector.goldStock-d.goldCost*qty end; if d.jewelCost then LeechCollector.jewelStock=LeechCollector.jewelStock-d.jewelCost*qty end; local t=d.time; if LeechCollector.maker then t=math.max(1,t-math.floor(LeechCollector.maker.skill/12)) end; table.insert(LeechCollector.activeMaking,{id="leech_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,healingPower=d.healingPower or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LeechCollector.completeMaking(m) local q=1.0+(LeechCollector.getQualityBonus()/100); if LeechCollector.maker then q=q+(LeechCollector.maker.skill/180) end; q=math.min(2.0,q); LeechCollector.productStock[m.productType]=(LeechCollector.productStock[m.productType] or 0)+m.quantity; LeechCollector.totalProducts=LeechCollector.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LeechCollector.maker then LeechCollector.maker.itemsMade=LeechCollector.maker.itemsMade+m.quantity; if math.random()<0.20 then LeechCollector.maker.skill=math.min(100,LeechCollector.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pijavka pridelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"leech.completed",{productName=m.productName,healingPower=m.healingPower,happiness=m.happiness}) end end
function LeechCollector.update(dt) if not _G.state then return end; LeechCollector.dayTimer=LeechCollector.dayTimer+dt; if LeechCollector.dayTimer>=30 then LeechCollector.dayTimer=0; for i=#LeechCollector.activeMaking,1,-1 do local m=LeechCollector.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LeechCollector.completeMaking(m); table.remove(LeechCollector.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LeechCollector.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LeechCollector.maker then tu=tu+11 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LeechCollector.getStats() return {pondWaterStock=LeechCollector.pondWaterStock,herbStock=LeechCollector.herbStock,silverStock=LeechCollector.silverStock,goldStock=LeechCollector.goldStock,jewelStock=LeechCollector.jewelStock,productStock=LeechCollector.productStock,numBuildings=#LeechCollector.buildings,hasMaker=LeechCollector.maker~=nil,makerName=LeechCollector.maker and LeechCollector.maker.name or "—",makerSkill=LeechCollector.maker and LeechCollector.maker.skill or 0,activeMaking=#LeechCollector.activeMaking,totalProducts=LeechCollector.totalProducts} end
return LeechCollector
