local SignBoardMaker = {}
local PRODUCTS = {
    shop_board = { name = "Trgovska tabla", woodCost = 1, time = 1, cost = 6, visibility = 5, description = "Preprosta lesena tabla za trgovino." },
    inn_sign = { name = "Gostilniški napis", woodCost = 2, time = 2, cost = 16, visibility = 8, prestige = 1, description = "Okrasen napis za gostilno." },
    guild_sign = { name = "Cehovski znak", woodCost = 2, ironCost = 1, time = 3, cost = 38, visibility = 12, prestige = 3, description = "Cehovski znak z emblematom." },
    painted_sign = { name = "Poslikani napis", woodCost = 2, paintCost = 1, time = 4, cost = 80, visibility = 15, prestige = 5, description = "Bogato poslikani napis." },
    gilded_sign = { name = "Pozlačeni napis", woodCost = 2, goldCost = 1, paintCost = 1, time = 5, cost = 160, visibility = 20, prestige = 10, happiness = 1, description = "Z zlatom okrašen napis." },
    royal_heraldic_sign = { name = "Kraljevski heraldični napis", woodCost = 3, goldCost = 2, silverCost = 1, paintCost = 2, time = 8, cost = 420, visibility = 30, prestige = 22, happiness = 4, description = "Kraljevski napis z grbom in zlatimi detajli." },
}
local BUILDINGS = {
    workshop = { name = "Tablarska delavnica", cost = { gold = 180, wood = 110 }, upkeep = 4, qualityBonus = 5 },
    paint_room = { name = "Slikalnica", cost = { gold = 550, wood = 200, stone = 120 }, upkeep = 13, qualityBonus = 14 },
    gilding_room = { name = "Pozlatnica", cost = { gold = 1000, wood = 250, stone = 200, gold = 20 }, upkeep = 24, qualityBonus = 22 },
    royal_sign_atelier = { name = "Kraljevski atelje napisov", cost = { gold = 2900, wood = 400, stone = 450, gold = 30 }, upkeep = 58, qualityBonus = 36, prestigeBonus = 18 },
}
SignBoardMaker.woodStock = 24; SignBoardMaker.ironStock = 6; SignBoardMaker.paintStock = 8; SignBoardMaker.goldStock = 4; SignBoardMaker.silverStock = 4
SignBoardMaker.productStock = {}; SignBoardMaker.buildings = {}; SignBoardMaker.maker = nil; SignBoardMaker.activeMaking = {}; SignBoardMaker.totalProducts = 0; SignBoardMaker.dayTimer = 0
function SignBoardMaker.init() SignBoardMaker.woodStock=24; SignBoardMaker.ironStock=6; SignBoardMaker.paintStock=8; SignBoardMaker.goldStock=4; SignBoardMaker.silverStock=4; SignBoardMaker.productStock={}; SignBoardMaker.buildings={}; SignBoardMaker.maker=nil; SignBoardMaker.activeMaking={}; SignBoardMaker.totalProducts=0; SignBoardMaker.dayTimer=0; print("[SignBoardMaker] Royal Sign Board & Inn Sign System initialized (6 products, 4 buildings)") end
function SignBoardMaker.hireMaker(n,s) s=s or math.random(35,80); local c=240+s*5; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SignBoardMaker.maker={name=n or ("Tablar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tablar najet: %s (spretnost: %d)",SignBoardMaker.maker.name,s),"success") end; return true end
function SignBoardMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SignBoardMaker.build(id) local ok,e=SignBoardMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SignBoardMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SignBoardMaker.getQualityBonus() local b=0; for _,bd in ipairs(SignBoardMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SignBoardMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and SignBoardMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and SignBoardMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.paintCost and SignBoardMaker.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.goldCost and SignBoardMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.silverCost and SignBoardMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if #SignBoardMaker.buildings==0 then return false,"Potrebna delavnica" end; if not SignBoardMaker.maker then return false,"Potreben tablar" end; return true end
function SignBoardMaker.make(pt,qty) qty=qty or 5; local ok,e=SignBoardMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then SignBoardMaker.woodStock=SignBoardMaker.woodStock-d.woodCost*qty end; if d.ironCost then SignBoardMaker.ironStock=SignBoardMaker.ironStock-d.ironCost*qty end; if d.paintCost then SignBoardMaker.paintStock=SignBoardMaker.paintStock-d.paintCost*qty end; if d.goldCost then SignBoardMaker.goldStock=SignBoardMaker.goldStock-d.goldCost*qty end; if d.silverCost then SignBoardMaker.silverStock=SignBoardMaker.silverStock-d.silverCost*qty end; local t=d.time; if SignBoardMaker.maker then t=math.max(1,t-math.floor(SignBoardMaker.maker.skill/15)) end; table.insert(SignBoardMaker.activeMaking,{id="sign_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,visibility=d.visibility or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SignBoardMaker.completeMaking(m) local q=1.0+(SignBoardMaker.getQualityBonus()/100); if SignBoardMaker.maker then q=q+(SignBoardMaker.maker.skill/200) end; q=math.min(2.0,q); SignBoardMaker.productStock[m.productType]=(SignBoardMaker.productStock[m.productType] or 0)+m.quantity; SignBoardMaker.totalProducts=SignBoardMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SignBoardMaker.maker then SignBoardMaker.maker.itemsMade=SignBoardMaker.maker.itemsMade+m.quantity; if math.random()<0.15 then SignBoardMaker.maker.skill=math.min(100,SignBoardMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Napisni izdelani: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end end
function SignBoardMaker.update(dt) if not _G.state then return end; SignBoardMaker.dayTimer=SignBoardMaker.dayTimer+dt; if SignBoardMaker.dayTimer>=30 then SignBoardMaker.dayTimer=0; for i=#SignBoardMaker.activeMaking,1,-1 do local m=SignBoardMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SignBoardMaker.completeMaking(m); table.remove(SignBoardMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SignBoardMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SignBoardMaker.maker then tu=tu+8 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SignBoardMaker.getStats() return {woodStock=SignBoardMaker.woodStock,ironStock=SignBoardMaker.ironStock,paintStock=SignBoardMaker.paintStock,goldStock=SignBoardMaker.goldStock,silverStock=SignBoardMaker.silverStock,productStock=SignBoardMaker.productStock,numBuildings=#SignBoardMaker.buildings,hasMaker=SignBoardMaker.maker~=nil,makerName=SignBoardMaker.maker and SignBoardMaker.maker.name or "—",makerSkill=SignBoardMaker.maker and SignBoardMaker.maker.skill or 0,activeMaking=#SignBoardMaker.activeMaking,totalProducts=SignBoardMaker.totalProducts} end
return SignBoardMaker
