local HorseArmorMaker = {}
local PRODUCTS = {
    leather_barding = { name = "Usnjeni barding", leatherCost = 4, time = 4, cost = 120, defense = 8, durability = 25, description = "Usnjeni barding za konja." },
    padded_barding = { name = "Blazirani barding", leatherCost = 3, woolCost = 3, time = 6, cost = 280, defense = 14, durability = 35, prestige = 2, description = "Blazirani barding za boljšo zaščito." },
    chain_barding = { name = "Verižni barding", ironCost = 4, leatherCost = 2, time = 9, cost = 620, defense = 22, durability = 50, prestige = 6, happiness = 1, description = "Verižni barding za bojnega konja." },
    steel_plate_barding = { name = "Jekleni ploščati barding", steelCost = 4, ironCost = 2, leatherCost = 2, time = 12, cost = 1300, defense = 32, durability = 65, prestige = 12, happiness = 2, description = "Jekleni ploščati barding za težko konjenico." },
    silver_emblazoned_barding = { name = "Srebrno okrašen barding", steelCost = 4, silverCost = 2, leatherCost = 2, time = 15, cost = 2600, defense = 40, durability = 80, prestige = 22, happiness = 4, description = "Srebrno okrašen barding z grbom." },
    royal_ceremonial_barding = { name = "Kraljevski slovesni barding", steelCost = 5, goldCost = 3, silverCost = 2, jewelCost = 2, pearlCost = 1, leatherCost = 2, time = 20, cost = 5200, defense = 60, durability = 110, prestige = 80, happiness = 16, description = "Veliki kraljevski slovesni barding z zlatim, draguljnim in bisernim okovjem za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Bardingarska delavnica", cost = { gold = 320, wood = 130, stone = 100 }, upkeep = 8, qualityBonus = 5 },
    forge = { name = "Bardingarska kovačija", cost = { gold = 1000, wood = 220, stone = 250, iron = 10 }, upkeep = 25, qualityBonus = 18 },
    finishing_room = { name = "Dokončevalnica", cost = { gold = 2200, wood = 300, stone = 500, silver = 30, steel = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_barding_atelier = { name = "Kraljevski atelje bardingov", cost = { gold = 9000, wood = 600, stone = 900, gold = 100, jewel = 25 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
HorseArmorMaker.leatherStock = 14; HorseArmorMaker.woolStock = 10; HorseArmorMaker.ironStock = 12; HorseArmorMaker.steelStock = 10; HorseArmorMaker.silverStock = 8; HorseArmorMaker.goldStock = 6; HorseArmorMaker.jewelStock = 6; HorseArmorMaker.pearlStock = 4
HorseArmorMaker.productStock = {}; HorseArmorMaker.buildings = {}; HorseArmorMaker.maker = nil; HorseArmorMaker.activeMaking = {}; HorseArmorMaker.totalProducts = 0; HorseArmorMaker.dayTimer = 0
function HorseArmorMaker.init() HorseArmorMaker.leatherStock=14; HorseArmorMaker.woolStock=10; HorseArmorMaker.ironStock=12; HorseArmorMaker.steelStock=10; HorseArmorMaker.silverStock=8; HorseArmorMaker.goldStock=6; HorseArmorMaker.jewelStock=6; HorseArmorMaker.pearlStock=4; HorseArmorMaker.productStock={}; HorseArmorMaker.buildings={}; HorseArmorMaker.maker=nil; HorseArmorMaker.activeMaking={}; HorseArmorMaker.totalProducts=0; HorseArmorMaker.dayTimer=0; print("[HorseArmorMaker] Royal Horse Armor Maker System initialized (6 products, 4 buildings)") end
function HorseArmorMaker.hireMaker(n,s) s=s or math.random(55,95); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HorseArmorMaker.maker={name=n or ("Bardingar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Bardingar najet: %s (spretnost: %d)",HorseArmorMaker.maker.name,s),"success") end; return true end
function HorseArmorMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HorseArmorMaker.build(id) local ok,e=HorseArmorMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HorseArmorMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HorseArmorMaker.getQualityBonus() local b=0; for _,bd in ipairs(HorseArmorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HorseArmorMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.leatherCost and HorseArmorMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.woolCost and HorseArmorMaker.woolStock<(d.woolCost or 0) then return false,"Premalo volne" end; if d.ironCost and HorseArmorMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and HorseArmorMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.silverCost and HorseArmorMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HorseArmorMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HorseArmorMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HorseArmorMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HorseArmorMaker.buildings==0 then return false,"Potrebna delavnica" end; if not HorseArmorMaker.maker then return false,"Potreben bardingar" end; return true end
function HorseArmorMaker.make(pt,qty) qty=qty or 1; local ok,e=HorseArmorMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.leatherCost then HorseArmorMaker.leatherStock=HorseArmorMaker.leatherStock-d.leatherCost*qty end; if d.woolCost then HorseArmorMaker.woolStock=HorseArmorMaker.woolStock-d.woolCost*qty end; if d.ironCost then HorseArmorMaker.ironStock=HorseArmorMaker.ironStock-d.ironCost*qty end; if d.steelCost then HorseArmorMaker.steelStock=HorseArmorMaker.steelStock-d.steelCost*qty end; if d.silverCost then HorseArmorMaker.silverStock=HorseArmorMaker.silverStock-d.silverCost*qty end; if d.goldCost then HorseArmorMaker.goldStock=HorseArmorMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HorseArmorMaker.jewelStock=HorseArmorMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HorseArmorMaker.pearlStock=HorseArmorMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HorseArmorMaker.maker then t=math.max(1,t-math.floor(HorseArmorMaker.maker.skill/12)) end; table.insert(HorseArmorMaker.activeMaking,{id="barding_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,defense=d.defense or 0,durability=d.durability or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HorseArmorMaker.completeMaking(m) local q=1.0+(HorseArmorMaker.getQualityBonus()/100); if HorseArmorMaker.maker then q=q+(HorseArmorMaker.maker.skill/150) end; q=math.min(2.5,q); HorseArmorMaker.productStock[m.productType]=(HorseArmorMaker.productStock[m.productType] or 0)+m.quantity; HorseArmorMaker.totalProducts=HorseArmorMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HorseArmorMaker.maker then HorseArmorMaker.maker.itemsMade=HorseArmorMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then HorseArmorMaker.maker.skill=math.min(100,HorseArmorMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Barding izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"barding.completed",{productName=m.productName,defense=m.defense,durability=m.durability}) end end
function HorseArmorMaker.update(dt) if not _G.state then return end; HorseArmorMaker.dayTimer=HorseArmorMaker.dayTimer+dt; if HorseArmorMaker.dayTimer>=30 then HorseArmorMaker.dayTimer=0; for i=#HorseArmorMaker.activeMaking,1,-1 do local m=HorseArmorMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HorseArmorMaker.completeMaking(m); table.remove(HorseArmorMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HorseArmorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HorseArmorMaker.maker then tu=tu+18 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HorseArmorMaker.getStats() return {leatherStock=HorseArmorMaker.leatherStock,woolStock=HorseArmorMaker.woolStock,ironStock=HorseArmorMaker.ironStock,steelStock=HorseArmorMaker.steelStock,silverStock=HorseArmorMaker.silverStock,goldStock=HorseArmorMaker.goldStock,jewelStock=HorseArmorMaker.jewelStock,pearlStock=HorseArmorMaker.pearlStock,productStock=HorseArmorMaker.productStock,numBuildings=#HorseArmorMaker.buildings,hasMaker=HorseArmorMaker.maker~=nil,makerName=HorseArmorMaker.maker and HorseArmorMaker.maker.name or "—",makerSkill=HorseArmorMaker.maker and HorseArmorMaker.maker.skill or 0,activeMaking=#HorseArmorMaker.activeMaking,totalProducts=HorseArmorMaker.totalProducts} end
return HorseArmorMaker
