local HuntingFalconer = {}
local PRODUCTS = {
    hare_hunt = { name = "Lov na zajce", trainedFalconCost = 1, time = 2, cost = 25, yield = 35, happiness = 1, description = "Lov na zajce s sokolom." },
    pheasant_hunt = { name = "Lov na fazane", trainedFalconCost = 1, time = 3, cost = 45, yield = 50, prestige = 2, description = "Lov na fazane s sokolom." },
    heron_hunt = { name = "Lov na čaplje", trainedFalconCost = 1, silverCost = 1, time = 5, cost = 100, yield = 65, prestige = 5, happiness = 1, description = "Lov na čaplje za plemiče." },
    crane_hunt = { name = "Lov na žerjave", trainedFalconCost = 1, silverCost = 1, time = 7, cost = 220, yield = 75, prestige = 9, happiness = 2, description = "Lov na žerjave za visoke plemiče." },
    silver_jess_hunt = { name = "Srebrno remenski lov", trainedFalconCost = 1, silverCost = 1, time = 10, cost = 500, yield = 88, prestige = 16, happiness = 3, description = "Lov s srebrnimi remeni za kraljevski lov." },
    royal_grand_hunt = { name = "Kraljevski veliki lov", trainedFalconCost = 2, goldCost = 1, silverCost = 1, jewelCost = 1, time = 15, cost = 1600, yield = 100, prestige = 42, happiness = 9, description = "Veliki kraljevski lov z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Lovska postaja", cost = { gold = 260, wood = 130, stone = 200 }, upkeep = 6, qualityBonus = 5 },
    hunting_lodge = { name = "Lovska koča", cost = { gold = 900, wood = 280, stone = 400, leather = 10 }, upkeep = 22, qualityBonus = 18 },
    falconry_field = { name = "Sokolarsko polje", cost = { gold = 2300, wood = 350, stone = 600, silver = 25, meat = 8 }, upkeep = 58, qualityBonus = 30 },
    royal_hunting_atelier = { name = "Kraljevski atelje lova", cost = { gold = 9200, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 185, qualityBonus = 55, prestigeBonus = 40 },
}
HuntingFalconer.trainedFalconStock = 18; HuntingFalconer.silverStock = 8; HuntingFalconer.goldStock = 6; HuntingFalconer.jewelStock = 6
HuntingFalconer.productStock = {}; HuntingFalconer.buildings = {}; HuntingFalconer.maker = nil; HuntingFalconer.activeMaking = {}; HuntingFalconer.totalProducts = 0; HuntingFalconer.dayTimer = 0
function HuntingFalconer.init() HuntingFalconer.trainedFalconStock=18; HuntingFalconer.silverStock=8; HuntingFalconer.goldStock=6; HuntingFalconer.jewelStock=6; HuntingFalconer.productStock={}; HuntingFalconer.buildings={}; HuntingFalconer.maker=nil; HuntingFalconer.activeMaking={}; HuntingFalconer.totalProducts=0; HuntingFalconer.dayTimer=0; print("[HuntingFalconer] Royal Hunting Falconer System initialized (6 products, 4 buildings)") end
function HuntingFalconer.hireMaker(n,s) s=s or math.random(50,90); local c=520+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HuntingFalconer.maker={name=n or ("Lovsoki sokolar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lovsoki sokolar najet: %s (spretnost: %d)",HuntingFalconer.maker.name,s),"success") end; return true end
function HuntingFalconer.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HuntingFalconer.build(id) local ok,e=HuntingFalconer.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HuntingFalconer.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HuntingFalconer.getQualityBonus() local b=0; for _,bd in ipairs(HuntingFalconer.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HuntingFalconer.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.trainedFalconCost and HuntingFalconer.trainedFalconStock<(d.trainedFalconCost or 0) then return false,"Premalo udomačenih sokolov" end; if d.silverCost and HuntingFalconer.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HuntingFalconer.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HuntingFalconer.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #HuntingFalconer.buildings==0 then return false,"Potrebna delavnica" end; if not HuntingFalconer.maker then return false,"Potreben lovski sokolar" end; return true end
function HuntingFalconer.make(pt,qty) qty=qty or 1; local ok,e=HuntingFalconer.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.trainedFalconCost then HuntingFalconer.trainedFalconStock=HuntingFalconer.trainedFalconStock-d.trainedFalconCost*qty end; if d.silverCost then HuntingFalconer.silverStock=HuntingFalconer.silverStock-d.silverCost*qty end; if d.goldCost then HuntingFalconer.goldStock=HuntingFalconer.goldStock-d.goldCost*qty end; if d.jewelCost then HuntingFalconer.jewelStock=HuntingFalconer.jewelStock-d.jewelCost*qty end; local t=d.time; if HuntingFalconer.maker then t=math.max(1,t-math.floor(HuntingFalconer.maker.skill/12)) end; table.insert(HuntingFalconer.activeMaking,{id="huntfalcon_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,yield=d.yield or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HuntingFalconer.completeMaking(m) local q=1.0+(HuntingFalconer.getQualityBonus()/100); if HuntingFalconer.maker then q=q+(HuntingFalconer.maker.skill/150) end; q=math.min(2.5,q); HuntingFalconer.productStock[m.productType]=(HuntingFalconer.productStock[m.productType] or 0)+m.quantity; HuntingFalconer.totalProducts=HuntingFalconer.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HuntingFalconer.maker then HuntingFalconer.maker.itemsMade=HuntingFalconer.maker.itemsMade+m.quantity; if math.random()<0.25 then HuntingFalconer.maker.skill=math.min(100,HuntingFalconer.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lov zaključen: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"huntfalcon.completed",{productName=m.productName,yield=m.yield,prestige=m.prestige,happiness=m.happiness}) end end
function HuntingFalconer.update(dt) if not _G.state then return end; HuntingFalconer.dayTimer=HuntingFalconer.dayTimer+dt; if HuntingFalconer.dayTimer>=30 then HuntingFalconer.dayTimer=0; for i=#HuntingFalconer.activeMaking,1,-1 do local m=HuntingFalconer.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HuntingFalconer.completeMaking(m); table.remove(HuntingFalconer.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HuntingFalconer.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HuntingFalconer.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HuntingFalconer.getStats() return {trainedFalconStock=HuntingFalconer.trainedFalconStock,silverStock=HuntingFalconer.silverStock,goldStock=HuntingFalconer.goldStock,jewelStock=HuntingFalconer.jewelStock,productStock=HuntingFalconer.productStock,numBuildings=#HuntingFalconer.buildings,hasMaker=HuntingFalconer.maker~=nil,makerName=HuntingFalconer.maker and HuntingFalconer.maker.name or "—",makerSkill=HuntingFalconer.maker and HuntingFalconer.maker.skill or 0,activeMaking=#HuntingFalconer.activeMaking,totalProducts=HuntingFalconer.totalProducts} end
return HuntingFalconer
