local Fletcher = {}
local PRODUCTS = {
    bobkin_arrow = { name = "Bobkin puščica", woodCost = 1, featherCost = 1, time = 1, cost = 4, attack = 3, range = 25, description = "Bobkin puščica za prebadanje verižnega oklepa." },
    broadhead_arrow = { name = "Širokokljuna puščica", woodCost = 1, ironCost = 1, featherCost = 1, time = 2, cost = 10, attack = 5, range = 30, prestige = 1, description = "Širokokljuna puščica za lov." },
    bodkin_arrow = { name = "Bodkin puščica", woodCost = 1, steelCost = 1, featherCost = 1, time = 3, cost = 25, attack = 8, range = 35, prestige = 2, description = "Bodkin puščica za prebadanje ploščatega oklepa." },
    silver_tip_arrow = { name = "Srebrno kljuna puščica", woodCost = 1, silverCost = 1, featherCost = 1, time = 4, cost = 60, attack = 12, range = 40, prestige = 5, happiness = 1, description = "Srebrna puščica za slovesne namene." },
    gold_fletched_arrow = { name = "Zlatoroba puščica", woodCost = 1, goldCost = 1, silverCost = 1, featherCost = 1, time = 6, cost = 140, attack = 16, range = 45, prestige = 9, happiness = 2, description = "Puščica z zlatorobnim perjem za viteze." },
    royal_quiver_set = { name = "Kraljevski komplet tulec", woodCost = 2, goldCost = 1, silverCost = 1, jewelCost = 1, featherCost = 2, pearlCost = 1, time = 11, cost = 800, attack = 28, range = 60, prestige = 32, happiness = 7, description = "Veliki kraljevski komplet tulec z dragulji in biseri za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Puščičarska delavnica", cost = { gold = 250, wood = 130 }, upkeep = 6, qualityBonus = 5 },
    fletching_room = { name = "Peresnica", cost = { gold = 800, wood = 220, stone = 200, feather = 8 }, upkeep = 20, qualityBonus = 18 },
    forging_room = { name = "Kovašnica kljun", cost = { gold = 1800, wood = 280, stone = 400, silver = 25, steel = 8 }, upkeep = 42, qualityBonus = 30 },
    royal_fletcher_atelier = { name = "Kraljevski atelje puščic", cost = { gold = 7000, wood = 500, stone = 700, gold = 50, jewel = 20 }, upkeep = 130, qualityBonus = 55, prestigeBonus = 30 },
}
Fletcher.woodStock = 18; Fletcher.featherStock = 16; Fletcher.ironStock = 12; Fletcher.steelStock = 10; Fletcher.silverStock = 8; Fletcher.goldStock = 6; Fletcher.jewelStock = 6; Fletcher.pearlStock = 4
Fletcher.productStock = {}; Fletcher.buildings = {}; Fletcher.maker = nil; Fletcher.activeMaking = {}; Fletcher.totalProducts = 0; Fletcher.dayTimer = 0
function Fletcher.init() Fletcher.woodStock=18; Fletcher.featherStock=16; Fletcher.ironStock=12; Fletcher.steelStock=10; Fletcher.silverStock=8; Fletcher.goldStock=6; Fletcher.jewelStock=6; Fletcher.pearlStock=4; Fletcher.productStock={}; Fletcher.buildings={}; Fletcher.maker=nil; Fletcher.activeMaking={}; Fletcher.totalProducts=0; Fletcher.dayTimer=0; print("[Fletcher] Royal Fletcher System initialized (6 products, 4 buildings)") end
function Fletcher.hireMaker(n,s) s=s or math.random(50,90); local c=470+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; Fletcher.maker={name=n or ("Puščičar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Puščičar najet: %s (spretnost: %d)",Fletcher.maker.name,s),"success") end; return true end
function Fletcher.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function Fletcher.build(id) local ok,e=Fletcher.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(Fletcher.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function Fletcher.getQualityBonus() local b=0; for _,bd in ipairs(Fletcher.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function Fletcher.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and Fletcher.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.featherCost and Fletcher.featherStock<(d.featherCost or 0) then return false,"Premalo peres" end; if d.ironCost and Fletcher.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and Fletcher.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.silverCost and Fletcher.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and Fletcher.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and Fletcher.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and Fletcher.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #Fletcher.buildings==0 then return false,"Potrebna delavnica" end; if not Fletcher.maker then return false,"Potreben puščičar" end; return true end
function Fletcher.make(pt,qty) qty=qty or 20; local ok,e=Fletcher.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then Fletcher.woodStock=Fletcher.woodStock-d.woodCost*qty end; if d.featherCost then Fletcher.featherStock=Fletcher.featherStock-d.featherCost*qty end; if d.ironCost then Fletcher.ironStock=Fletcher.ironStock-d.ironCost*qty end; if d.steelCost then Fletcher.steelStock=Fletcher.steelStock-d.steelCost*qty end; if d.silverCost then Fletcher.silverStock=Fletcher.silverStock-d.silverCost*qty end; if d.goldCost then Fletcher.goldStock=Fletcher.goldStock-d.goldCost*qty end; if d.jewelCost then Fletcher.jewelStock=Fletcher.jewelStock-d.jewelCost*qty end; if d.pearlCost then Fletcher.pearlStock=Fletcher.pearlStock-d.pearlCost*qty end; local t=d.time; if Fletcher.maker then t=math.max(1,t-math.floor(Fletcher.maker.skill/12)) end; table.insert(Fletcher.activeMaking,{id="arrow_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,attack=d.attack or 0,range=d.range or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function Fletcher.completeMaking(m) local q=1.0+(Fletcher.getQualityBonus()/100); if Fletcher.maker then q=q+(Fletcher.maker.skill/180) end; q=math.min(2.0,q); Fletcher.productStock[m.productType]=(Fletcher.productStock[m.productType] or 0)+m.quantity; Fletcher.totalProducts=Fletcher.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if Fletcher.maker then Fletcher.maker.itemsMade=Fletcher.maker.itemsMade+m.quantity; if math.random()<0.20 then Fletcher.maker.skill=math.min(100,Fletcher.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Puščice izdelane: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"arrow.completed",{productName=m.productName,attack=m.attack,range=m.range}) end end
function Fletcher.update(dt) if not _G.state then return end; Fletcher.dayTimer=Fletcher.dayTimer+dt; if Fletcher.dayTimer>=30 then Fletcher.dayTimer=0; for i=#Fletcher.activeMaking,1,-1 do local m=Fletcher.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then Fletcher.completeMaking(m); table.remove(Fletcher.activeMaking,i) end end; local tu=0; for _,bd in ipairs(Fletcher.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if Fletcher.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function Fletcher.getStats() return {woodStock=Fletcher.woodStock,featherStock=Fletcher.featherStock,ironStock=Fletcher.ironStock,steelStock=Fletcher.steelStock,silverStock=Fletcher.silverStock,goldStock=Fletcher.goldStock,jewelStock=Fletcher.jewelStock,pearlStock=Fletcher.pearlStock,productStock=Fletcher.productStock,numBuildings=#Fletcher.buildings,hasMaker=Fletcher.maker~=nil,makerName=Fletcher.maker and Fletcher.maker.name or "—",makerSkill=Fletcher.maker and Fletcher.maker.skill or 0,activeMaking=#Fletcher.activeMaking,totalProducts=Fletcher.totalProducts} end
return Fletcher
