local PolearmMaker = {}
local PRODUCTS = {
    spear = { name = "Kopje", woodCost = 2, ironCost = 1, time = 2, cost = 25, attack = 8, durability = 25, description = "Preprosto kopje za pehoto." },
    pike = { name = "Pika", woodCost = 3, ironCost = 1, time = 4, cost = 70, attack = 12, durability = 30, prestige = 1, description = "Dolga pika za formacije." },
    halberd = { name = "Halberda", woodCost = 2, steelCost = 1, ironCost = 1, time = 5, cost = 180, attack = 18, durability = 40, prestige = 3, happiness = 1, description = "Halberda s sekiro in kavljem." },
    glaive = { name = "Glaive", woodCost = 2, steelCost = 1, time = 6, cost = 320, attack = 22, durability = 45, prestige = 6, happiness = 1, description = "Glaive z ukrivljenim rezom." },
    silver_polearm = { name = "Srebrna sulica", woodCost = 3, steelCost = 1, silverCost = 1, time = 8, cost = 680, attack = 28, durability = 55, prestige = 12, happiness = 2, description = "Srebrno okrašena sulica za slovesnost." },
    royal_ceremonial_polearm = { name = "Kraljevski slovesna sulica", woodCost = 4, steelCost = 2, goldCost = 2, silverCost = 1, jewelCost = 1, pearlCost = 1, time = 13, cost = 1900, attack = 42, durability = 80, prestige = 48, happiness = 10, description = "Velika kraljevska slovesna sulica z zlatim in bisernim okovjem." },
}
local BUILDINGS = {
    workshop = { name = "Suličarska delavnica", cost = { gold = 270, wood = 140 }, upkeep = 6, qualityBonus = 5 },
    forge = { name = "Suličarska kovačija", cost = { gold = 850, wood = 220, stone = 200, iron = 8 }, upkeep = 20, qualityBonus = 18 },
    finishing_room = { name = "Dokončevalnica", cost = { gold = 1800, wood = 280, stone = 400, silver = 25, steel = 8 }, upkeep = 42, qualityBonus = 30 },
    royal_polearm_atelier = { name = "Kraljevski atelje sulic", cost = { gold = 7000, wood = 500, stone = 700, gold = 50, jewel = 20 }, upkeep = 130, qualityBonus = 55, prestigeBonus = 30 },
}
PolearmMaker.woodStock = 16; PolearmMaker.ironStock = 12; PolearmMaker.steelStock = 10; PolearmMaker.silverStock = 6; PolearmMaker.goldStock = 6; PolearmMaker.jewelStock = 6; PolearmMaker.pearlStock = 4
PolearmMaker.productStock = {}; PolearmMaker.buildings = {}; PolearmMaker.maker = nil; PolearmMaker.activeMaking = {}; PolearmMaker.totalProducts = 0; PolearmMaker.dayTimer = 0
function PolearmMaker.init() PolearmMaker.woodStock=16; PolearmMaker.ironStock=12; PolearmMaker.steelStock=10; PolearmMaker.silverStock=6; PolearmMaker.goldStock=6; PolearmMaker.jewelStock=6; PolearmMaker.pearlStock=4; PolearmMaker.productStock={}; PolearmMaker.buildings={}; PolearmMaker.maker=nil; PolearmMaker.activeMaking={}; PolearmMaker.totalProducts=0; PolearmMaker.dayTimer=0; print("[PolearmMaker] Royal Polearm Maker System initialized (6 products, 4 buildings)") end
function PolearmMaker.hireMaker(n,s) s=s or math.random(50,90); local c=480+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PolearmMaker.maker={name=n or ("Suličar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Suličar najet: %s (spretnost: %d)",PolearmMaker.maker.name,s),"success") end; return true end
function PolearmMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PolearmMaker.build(id) local ok,e=PolearmMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PolearmMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PolearmMaker.getQualityBonus() local b=0; for _,bd in ipairs(PolearmMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PolearmMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and PolearmMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and PolearmMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and PolearmMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.silverCost and PolearmMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PolearmMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PolearmMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PolearmMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PolearmMaker.buildings==0 then return false,"Potrebna delavnica" end; if not PolearmMaker.maker then return false,"Potreben suličar" end; return true end
function PolearmMaker.make(pt,qty) qty=qty or 1; local ok,e=PolearmMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then PolearmMaker.woodStock=PolearmMaker.woodStock-d.woodCost*qty end; if d.ironCost then PolearmMaker.ironStock=PolearmMaker.ironStock-d.ironCost*qty end; if d.steelCost then PolearmMaker.steelStock=PolearmMaker.steelStock-d.steelCost*qty end; if d.silverCost then PolearmMaker.silverStock=PolearmMaker.silverStock-d.silverCost*qty end; if d.goldCost then PolearmMaker.goldStock=PolearmMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PolearmMaker.jewelStock=PolearmMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PolearmMaker.pearlStock=PolearmMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PolearmMaker.maker then t=math.max(1,t-math.floor(PolearmMaker.maker.skill/12)) end; table.insert(PolearmMaker.activeMaking,{id="polearm_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,attack=d.attack or 0,durability=d.durability or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PolearmMaker.completeMaking(m) local q=1.0+(PolearmMaker.getQualityBonus()/100); if PolearmMaker.maker then q=q+(PolearmMaker.maker.skill/180) end; q=math.min(2.0,q); PolearmMaker.productStock[m.productType]=(PolearmMaker.productStock[m.productType] or 0)+m.quantity; PolearmMaker.totalProducts=PolearmMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PolearmMaker.maker then PolearmMaker.maker.itemsMade=PolearmMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then PolearmMaker.maker.skill=math.min(100,PolearmMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sulica izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"polearm.completed",{productName=m.productName,attack=m.attack,durability=m.durability}) end end
function PolearmMaker.update(dt) if not _G.state then return end; PolearmMaker.dayTimer=PolearmMaker.dayTimer+dt; if PolearmMaker.dayTimer>=30 then PolearmMaker.dayTimer=0; for i=#PolearmMaker.activeMaking,1,-1 do local m=PolearmMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PolearmMaker.completeMaking(m); table.remove(PolearmMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PolearmMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PolearmMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PolearmMaker.getStats() return {woodStock=PolearmMaker.woodStock,ironStock=PolearmMaker.ironStock,steelStock=PolearmMaker.steelStock,silverStock=PolearmMaker.silverStock,goldStock=PolearmMaker.goldStock,jewelStock=PolearmMaker.jewelStock,pearlStock=PolearmMaker.pearlStock,productStock=PolearmMaker.productStock,numBuildings=#PolearmMaker.buildings,hasMaker=PolearmMaker.maker~=nil,makerName=PolearmMaker.maker and PolearmMaker.maker.name or "—",makerSkill=PolearmMaker.maker and PolearmMaker.maker.skill or 0,activeMaking=#PolearmMaker.activeMaking,totalProducts=PolearmMaker.totalProducts} end
return PolearmMaker
