local HelmetMaker = {}
local PRODUCTS = {
    iron_cap = { name = "Železna kapica", ironCost = 1, time = 1, cost = 18, defense = 4, durability = 18, description = "Preprosta železna kapica." },
    kettle_helmet = { name = "Lonec čelada", ironCost = 2, time = 2, cost = 50, defense = 7, durability = 25, prestige = 1, description = "Lonec čelada za pehoto." },
    nasal_helmet = { name = "Nosna čelada", steelCost = 1, ironCost = 1, time = 4, cost = 130, defense = 11, durability = 32, prestige = 3, description = "Čelada z nosno ščitnico." },
    great_helm = { name = "Velika čelada", steelCost = 2, ironCost = 1, time = 6, cost = 320, defense = 16, durability = 45, prestige = 6, happiness = 1, description = "Velika zaprta čelada za viteze." },
    silver_helm = { name = "Srebrna čelada", steelCost = 2, silverCost = 1, time = 8, cost = 700, defense = 22, durability = 55, prestige = 12, happiness = 2, description = "Srebrna čelada z reliefom." },
    royal_ceremonial_helm = { name = "Kraljevska slovesna čelada", steelCost = 3, goldCost = 2, silverCost = 1, jewelCost = 2, pearlCost = 1, time = 13, cost = 1900, defense = 35, durability = 80, prestige = 50, happiness = 10, description = "Velika kraljevska slovesna čelada z zlatim, draguljnim in bisernim okovjem." },
}
local BUILDINGS = {
    workshop = { name = "Čeladarska delavnica", cost = { gold = 280, wood = 110 }, upkeep = 7, qualityBonus = 5 },
    forge = { name = "Čeladarska kovačija", cost = { gold = 900, wood = 220, stone = 200, iron = 8 }, upkeep = 22, qualityBonus = 18 },
    polishing_room = { name = "Polirnica", cost = { gold = 1900, wood = 280, stone = 400, silver = 25, steel = 8 }, upkeep = 45, qualityBonus = 30 },
    royal_helmet_atelier = { name = "Kraljevski atelje čelad", cost = { gold = 7500, wood = 500, stone = 800, gold = 50, jewel = 20 }, upkeep = 140, qualityBonus = 55, prestigeBonus = 33 },
}
HelmetMaker.ironStock = 14; HelmetMaker.steelStock = 12; HelmetMaker.silverStock = 8; HelmetMaker.goldStock = 6; HelmetMaker.jewelStock = 6; HelmetMaker.pearlStock = 4
HelmetMaker.productStock = {}; HelmetMaker.buildings = {}; HelmetMaker.maker = nil; HelmetMaker.activeMaking = {}; HelmetMaker.totalProducts = 0; HelmetMaker.dayTimer = 0
function HelmetMaker.init() HelmetMaker.ironStock=14; HelmetMaker.steelStock=12; HelmetMaker.silverStock=8; HelmetMaker.goldStock=6; HelmetMaker.jewelStock=6; HelmetMaker.pearlStock=4; HelmetMaker.productStock={}; HelmetMaker.buildings={}; HelmetMaker.maker=nil; HelmetMaker.activeMaking={}; HelmetMaker.totalProducts=0; HelmetMaker.dayTimer=0; print("[HelmetMaker] Royal Helmet Maker System initialized (6 products, 4 buildings)") end
function HelmetMaker.hireMaker(n,s) s=s or math.random(50,90); local c=500+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HelmetMaker.maker={name=n or ("Čeladar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Čeladar najet: %s (spretnost: %d)",HelmetMaker.maker.name,s),"success") end; return true end
function HelmetMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HelmetMaker.build(id) local ok,e=HelmetMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HelmetMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HelmetMaker.getQualityBonus() local b=0; for _,bd in ipairs(HelmetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HelmetMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and HelmetMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and HelmetMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.silverCost and HelmetMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HelmetMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HelmetMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HelmetMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HelmetMaker.buildings==0 then return false,"Potrebna delavnica" end; if not HelmetMaker.maker then return false,"Potreben čeladar" end; return true end
function HelmetMaker.make(pt,qty) qty=qty or 1; local ok,e=HelmetMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then HelmetMaker.ironStock=HelmetMaker.ironStock-d.ironCost*qty end; if d.steelCost then HelmetMaker.steelStock=HelmetMaker.steelStock-d.steelCost*qty end; if d.silverCost then HelmetMaker.silverStock=HelmetMaker.silverStock-d.silverCost*qty end; if d.goldCost then HelmetMaker.goldStock=HelmetMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HelmetMaker.jewelStock=HelmetMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HelmetMaker.pearlStock=HelmetMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HelmetMaker.maker then t=math.max(1,t-math.floor(HelmetMaker.maker.skill/12)) end; table.insert(HelmetMaker.activeMaking,{id="helmet_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,defense=d.defense or 0,durability=d.durability or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HelmetMaker.completeMaking(m) local q=1.0+(HelmetMaker.getQualityBonus()/100); if HelmetMaker.maker then q=q+(HelmetMaker.maker.skill/180) end; q=math.min(2.0,q); HelmetMaker.productStock[m.productType]=(HelmetMaker.productStock[m.productType] or 0)+m.quantity; HelmetMaker.totalProducts=HelmetMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HelmetMaker.maker then HelmetMaker.maker.itemsMade=HelmetMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then HelmetMaker.maker.skill=math.min(100,HelmetMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Čelada izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"helmet.completed",{productName=m.productName,defense=m.defense,durability=m.durability}) end end
function HelmetMaker.update(dt) if not _G.state then return end; HelmetMaker.dayTimer=HelmetMaker.dayTimer+dt; if HelmetMaker.dayTimer>=30 then HelmetMaker.dayTimer=0; for i=#HelmetMaker.activeMaking,1,-1 do local m=HelmetMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HelmetMaker.completeMaking(m); table.remove(HelmetMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HelmetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HelmetMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HelmetMaker.getStats() return {ironStock=HelmetMaker.ironStock,steelStock=HelmetMaker.steelStock,silverStock=HelmetMaker.silverStock,goldStock=HelmetMaker.goldStock,jewelStock=HelmetMaker.jewelStock,pearlStock=HelmetMaker.pearlStock,productStock=HelmetMaker.productStock,numBuildings=#HelmetMaker.buildings,hasMaker=HelmetMaker.maker~=nil,makerName=HelmetMaker.maker and HelmetMaker.maker.name or "—",makerSkill=HelmetMaker.maker and HelmetMaker.maker.skill or 0,activeMaking=#HelmetMaker.activeMaking,totalProducts=HelmetMaker.totalProducts} end
return HelmetMaker
