local ThuribleMaker = {}
local PRODUCTS = {
    iron_thurible = { name = "Železno kadilo", ironCost = 2, time = 2, cost = 30, sanctity = 4, description = "Preprosto železno kadilo za vernike." },
    brass_thurible = { name = "Medeninasto kadilo", brassCost = 2, ironCost = 1, time = 4, cost = 90, sanctity = 7, prestige = 2, description = "Medeninasto kadilo z verigami." },
    silver_thurible = { name = "Srebrno kadilo", silverCost = 2, ironCost = 1, time = 6, cost = 240, sanctity = 11, prestige = 5, happiness = 1, description = "Srebrno kadilo z rezervo za kadilo." },
    gold_thurible = { name = "Zlato kadilo", goldCost = 1, silverCost = 1, ironCost = 1, time = 8, cost = 540, sanctity = 16, prestige = 12, happiness = 2, description = "Zlato kadilo za slovesne maše." },
    jewel_thurible = { name = "Draguljno kadilo", goldCost = 2, silverCost = 1, jewelCost = 2, ironCost = 1, time = 11, cost = 1150, sanctity = 21, prestige = 22, happiness = 5, description = "Kadilo z dragulji za katedralo." },
    royal_papal_thurible = { name = "Kraljevski papeško kadilo", goldCost = 3, silverCost = 2, jewelCost = 3, pearlCost = 1, ironCost = 2, time = 15, cost = 2700, sanctity = 33, prestige = 60, happiness = 12, description = "Veliko kraljevsko papeško kadilo z dragulji in biseri za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Kadilarska delavnica", cost = { gold = 280, wood = 120 }, upkeep = 7, qualityBonus = 5 },
    forge = { name = "Kadilarska kovačija", cost = { gold = 850, wood = 220, stone = 200, silver = 6 }, upkeep = 20, qualityBonus = 18 },
    chain_room = { name = "Verižna soba", cost = { gold = 1800, wood = 300, stone = 400, silver = 25, iron = 8 }, upkeep = 42, qualityBonus = 30 },
    royal_thurible_atelier = { name = "Kraljevski atelje kadił", cost = { gold = 7000, wood = 600, stone = 800, gold = 50, jewel = 20 }, upkeep = 130, qualityBonus = 55, prestigeBonus = 33 },
}
ThuribleMaker.ironStock = 14; ThuribleMaker.brassStock = 8; ThuribleMaker.silverStock = 8; ThuribleMaker.goldStock = 6; ThuribleMaker.jewelStock = 6; ThuribleMaker.pearlStock = 4
ThuribleMaker.productStock = {}; ThuribleMaker.buildings = {}; ThuribleMaker.maker = nil; ThuribleMaker.activeMaking = {}; ThuribleMaker.totalProducts = 0; ThuribleMaker.dayTimer = 0
function ThuribleMaker.init() ThuribleMaker.ironStock=14; ThuribleMaker.brassStock=8; ThuribleMaker.silverStock=8; ThuribleMaker.goldStock=6; ThuribleMaker.jewelStock=6; ThuribleMaker.pearlStock=4; ThuribleMaker.productStock={}; ThuribleMaker.buildings={}; ThuribleMaker.maker=nil; ThuribleMaker.activeMaking={}; ThuribleMaker.totalProducts=0; ThuribleMaker.dayTimer=0; print("[ThuribleMaker] Royal Thurible & Censer Maker System initialized (6 products, 4 buildings)") end
function ThuribleMaker.hireMaker(n,s) s=s or math.random(50,90); local c=490+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ThuribleMaker.maker={name=n or ("Kadilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kadilar najet: %s (spretnost: %d)",ThuribleMaker.maker.name,s),"success") end; return true end
function ThuribleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ThuribleMaker.build(id) local ok,e=ThuribleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ThuribleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ThuribleMaker.getQualityBonus() local b=0; for _,bd in ipairs(ThuribleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ThuribleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ThuribleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.brassCost and ThuribleMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and ThuribleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ThuribleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ThuribleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ThuribleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ThuribleMaker.buildings==0 then return false,"Potrebna delavnica" end; if not ThuribleMaker.maker then return false,"Potreben kadilar" end; return true end
function ThuribleMaker.make(pt,qty) qty=qty or 1; local ok,e=ThuribleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ThuribleMaker.ironStock=ThuribleMaker.ironStock-d.ironCost*qty end; if d.brassCost then ThuribleMaker.brassStock=ThuribleMaker.brassStock-d.brassCost*qty end; if d.silverCost then ThuribleMaker.silverStock=ThuribleMaker.silverStock-d.silverCost*qty end; if d.goldCost then ThuribleMaker.goldStock=ThuribleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ThuribleMaker.jewelStock=ThuribleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ThuribleMaker.pearlStock=ThuribleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ThuribleMaker.maker then t=math.max(1,t-math.floor(ThuribleMaker.maker.skill/12)) end; table.insert(ThuribleMaker.activeMaking,{id="thurible_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,sanctity=d.sanctity or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ThuribleMaker.completeMaking(m) local q=1.0+(ThuribleMaker.getQualityBonus()/100); if ThuribleMaker.maker then q=q+(ThuribleMaker.maker.skill/180) end; q=math.min(2.0,q); ThuribleMaker.productStock[m.productType]=(ThuribleMaker.productStock[m.productType] or 0)+m.quantity; ThuribleMaker.totalProducts=ThuribleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ThuribleMaker.maker then ThuribleMaker.maker.itemsMade=ThuribleMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then ThuribleMaker.maker.skill=math.min(100,ThuribleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kadilo izdelano: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"thurible.completed",{productName=m.productName,sanctity=m.sanctity}) end end
function ThuribleMaker.update(dt) if not _G.state then return end; ThuribleMaker.dayTimer=ThuribleMaker.dayTimer+dt; if ThuribleMaker.dayTimer>=30 then ThuribleMaker.dayTimer=0; for i=#ThuribleMaker.activeMaking,1,-1 do local m=ThuribleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ThuribleMaker.completeMaking(m); table.remove(ThuribleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ThuribleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ThuribleMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ThuribleMaker.getStats() return {ironStock=ThuribleMaker.ironStock,brassStock=ThuribleMaker.brassStock,silverStock=ThuribleMaker.silverStock,goldStock=ThuribleMaker.goldStock,jewelStock=ThuribleMaker.jewelStock,pearlStock=ThuribleMaker.pearlStock,productStock=ThuribleMaker.productStock,numBuildings=#ThuribleMaker.buildings,hasMaker=ThuribleMaker.maker~=nil,makerName=ThuribleMaker.maker and ThuribleMaker.maker.name or "—",makerSkill=ThuribleMaker.maker and ThuribleMaker.maker.skill or 0,activeMaking=#ThuribleMaker.activeMaking,totalProducts=ThuribleMaker.totalProducts} end
return ThuribleMaker
