local FalconBreeder = {}
local PRODUCTS = {
    peregrine_falcon = { name = "Selivski sokol", falconEggCost = 1, meatCost = 1, time = 4, cost = 45, yield = 40, prestige = 2, description = "Selivski sokol za lov." },
    goshawk = { name = "Kragulj", falconEggCost = 1, meatCost = 1, time = 4, cost = 50, yield = 45, prestige = 3, description = "Kragulj za gozdni lov." },
    saker_falcon = { name = "Stepska postarna", falconEggCost = 1, meatCost = 2, time = 6, cost = 110, yield = 55, prestige = 6, happiness = 1, description = "Stepska postarna za višje plemiče." },
    gyr_falcon = { name = "Polarni sokol", falconEggCost = 1, meatCost = 2, silverCost = 1, time = 9, cost = 280, yield = 70, prestige = 12, happiness = 2, description = "Polarni sokol za kraljevski lov." },
    silver_jessed_falcon = { name = "Srebrno remenski sokol", falconEggCost = 1, silverCost = 1, meatCost = 2, time = 12, cost = 600, yield = 85, prestige = 20, happiness = 4, description = "Sokol s srebrnimi remeni za visoke plemiče." },
    royal_grand_falcon = { name = "Kraljevski veliki sokol", falconEggCost = 2, goldCost = 1, silverCost = 1, jewelCost = 1, meatCost = 3, time = 18, cost = 1800, yield = 100, prestige = 50, happiness = 10, description = "Veliki kraljevski sokol z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Sokolarska postaja", cost = { gold = 280, wood = 130, stone = 200 }, upkeep = 7, qualityBonus = 5 },
    falcon_mews = { name = "Sokolarica", cost = { gold = 950, wood = 250, stone = 400, meat = 10 }, upkeep = 23, qualityBonus = 18 },
    training_ground = { name = "Trezensko polje", cost = { gold = 2400, wood = 350, stone = 600, silver = 30, leather = 8 }, upkeep = 60, qualityBonus = 30 },
    royal_falcon_atelier = { name = "Kraljevski atelje sokolarstva", cost = { gold = 9500, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 40 },
}
FalconBreeder.falconEggStock = 18; FalconBreeder.meatStock = 22; FalconBreeder.silverStock = 8; FalconBreeder.goldStock = 6; FalconBreeder.jewelStock = 6
FalconBreeder.productStock = {}; FalconBreeder.buildings = {}; FalconBreeder.maker = nil; FalconBreeder.activeMaking = {}; FalconBreeder.totalProducts = 0; FalconBreeder.dayTimer = 0
function FalconBreeder.init() FalconBreeder.falconEggStock=18; FalconBreeder.meatStock=22; FalconBreeder.silverStock=8; FalconBreeder.goldStock=6; FalconBreeder.jewelStock=6; FalconBreeder.productStock={}; FalconBreeder.buildings={}; FalconBreeder.maker=nil; FalconBreeder.activeMaking={}; FalconBreeder.totalProducts=0; FalconBreeder.dayTimer=0; print("[FalconBreeder] Royal Falcon Breeder System initialized (6 products, 4 buildings)") end
function FalconBreeder.hireMaker(n,s) s=s or math.random(50,90); local c=520+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; FalconBreeder.maker={name=n or ("Sokolar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sokolar najet: %s (spretnost: %d)",FalconBreeder.maker.name,s),"success") end; return true end
function FalconBreeder.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function FalconBreeder.build(id) local ok,e=FalconBreeder.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(FalconBreeder.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function FalconBreeder.getQualityBonus() local b=0; for _,bd in ipairs(FalconBreeder.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function FalconBreeder.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.falconEggCost and FalconBreeder.falconEggStock<(d.falconEggCost or 0) then return false,"Premalo sokolovih jajc" end; if d.meatCost and FalconBreeder.meatStock<(d.meatCost or 0) then return false,"Premalo mesa" end; if d.silverCost and FalconBreeder.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and FalconBreeder.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and FalconBreeder.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #FalconBreeder.buildings==0 then return false,"Potrebna delavnica" end; if not FalconBreeder.maker then return false,"Potreben sokolar" end; return true end
function FalconBreeder.make(pt,qty) qty=qty or 1; local ok,e=FalconBreeder.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.falconEggCost then FalconBreeder.falconEggStock=FalconBreeder.falconEggStock-d.falconEggCost*qty end; if d.meatCost then FalconBreeder.meatStock=FalconBreeder.meatStock-d.meatCost*qty end; if d.silverCost then FalconBreeder.silverStock=FalconBreeder.silverStock-d.silverCost*qty end; if d.goldCost then FalconBreeder.goldStock=FalconBreeder.goldStock-d.goldCost*qty end; if d.jewelCost then FalconBreeder.jewelStock=FalconBreeder.jewelStock-d.jewelCost*qty end; local t=d.time; if FalconBreeder.maker then t=math.max(1,t-math.floor(FalconBreeder.maker.skill/12)) end; table.insert(FalconBreeder.activeMaking,{id="falcon_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,yield=d.yield or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function FalconBreeder.completeMaking(m) local q=1.0+(FalconBreeder.getQualityBonus()/100); if FalconBreeder.maker then q=q+(FalconBreeder.maker.skill/150) end; q=math.min(2.5,q); FalconBreeder.productStock[m.productType]=(FalconBreeder.productStock[m.productType] or 0)+m.quantity; FalconBreeder.totalProducts=FalconBreeder.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if FalconBreeder.maker then FalconBreeder.maker.itemsMade=FalconBreeder.maker.itemsMade+m.quantity; if math.random()<0.25 then FalconBreeder.maker.skill=math.min(100,FalconBreeder.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sokol vzrejen: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"falcon.completed",{productName=m.productName,yield=m.yield,prestige=m.prestige,happiness=m.happiness}) end end
function FalconBreeder.update(dt) if not _G.state then return end; FalconBreeder.dayTimer=FalconBreeder.dayTimer+dt; if FalconBreeder.dayTimer>=30 then FalconBreeder.dayTimer=0; for i=#FalconBreeder.activeMaking,1,-1 do local m=FalconBreeder.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then FalconBreeder.completeMaking(m); table.remove(FalconBreeder.activeMaking,i) end end; local tu=0; for _,bd in ipairs(FalconBreeder.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if FalconBreeder.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function FalconBreeder.getStats() return {falconEggStock=FalconBreeder.falconEggStock,meatStock=FalconBreeder.meatStock,silverStock=FalconBreeder.silverStock,goldStock=FalconBreeder.goldStock,jewelStock=FalconBreeder.jewelStock,productStock=FalconBreeder.productStock,numBuildings=#FalconBreeder.buildings,hasMaker=FalconBreeder.maker~=nil,makerName=FalconBreeder.maker and FalconBreeder.maker.name or "—",makerSkill=FalconBreeder.maker and FalconBreeder.maker.skill or 0,activeMaking=#FalconBreeder.activeMaking,totalProducts=FalconBreeder.totalProducts} end
return FalconBreeder
