local AltarFrontalMaker = {}
local PRODUCTS = {
    linen_frontal = { name = "Lneni antependij", linenCost = 2, time = 2, cost = 20, sanctity = 3, description = "Preprost lneni antependij za oltar." },
    painted_frontal = { name = "Poslikani antependij", linenCost = 2, paintCost = 1, time = 4, cost = 70, sanctity = 6, prestige = 2, description = "Poslikani antependij z biblijskim prizorom." },
    embroidered_frontal = { name = "Vezeni antependij", linenCost = 2, silkCost = 1, threadCost = 1, time = 6, cost = 200, sanctity = 10, prestige = 5, happiness = 1, description = "Vezeni antependij za župnijske oltarje." },
    silk_frontal = { name = "Svileni antependij", silkCost = 3, goldCost = 1, threadCost = 1, time = 8, cost = 460, sanctity = 14, prestige = 11, happiness = 2, description = "Svileni antependij z zlatorobnim okrasjem." },
    jewel_frontal = { name = "Draguljni antependij", silkCost = 3, goldCost = 2, jewelCost = 1, threadCost = 2, time = 11, cost = 950, sanctity = 19, prestige = 22, happiness = 4, description = "Antependij z dragulji za katedralo." },
    royal_cathedral_frontal = { name = "Kraljevska katedralna antipendij", silkCost = 5, goldCost = 3, silverCost = 2, jewelCost = 3, pearlCost = 1, threadCost = 3, time = 15, cost = 2200, sanctity = 30, prestige = 55, happiness = 10, description = "Kraljevski antependij za katedralo z dragulji in biseri." },
}
local BUILDINGS = {
    workshop = { name = "Antependijarska delavnica", cost = { gold = 270, wood = 120 }, upkeep = 7, qualityBonus = 5 },
    painting_room = { name = "Slikalnica", cost = { gold = 850, wood = 220, stone = 200, paint = 6 }, upkeep = 20, qualityBonus = 18 },
    embroidery_room = { name = "Vezenilnica", cost = { gold = 1800, wood = 300, stone = 400, silver = 25, thread = 8 }, upkeep = 42, qualityBonus = 30 },
    royal_frontal_atelier = { name = "Kraljevski atelje antependijev", cost = { gold = 7000, wood = 600, stone = 800, gold = 50, silk = 20 }, upkeep = 130, qualityBonus = 55, prestigeBonus = 33 },
}
AltarFrontalMaker.linenStock = 14; AltarFrontalMaker.silkStock = 12; AltarFrontalMaker.paintStock = 10; AltarFrontalMaker.threadStock = 10; AltarFrontalMaker.goldStock = 6; AltarFrontalMaker.silverStock = 6; AltarFrontalMaker.jewelStock = 4; AltarFrontalMaker.pearlStock = 4
AltarFrontalMaker.productStock = {}; AltarFrontalMaker.buildings = {}; AltarFrontalMaker.maker = nil; AltarFrontalMaker.activeMaking = {}; AltarFrontalMaker.totalProducts = 0; AltarFrontalMaker.dayTimer = 0
function AltarFrontalMaker.init() AltarFrontalMaker.linenStock=14; AltarFrontalMaker.silkStock=12; AltarFrontalMaker.paintStock=10; AltarFrontalMaker.threadStock=10; AltarFrontalMaker.goldStock=6; AltarFrontalMaker.silverStock=6; AltarFrontalMaker.jewelStock=4; AltarFrontalMaker.pearlStock=4; AltarFrontalMaker.productStock={}; AltarFrontalMaker.buildings={}; AltarFrontalMaker.maker=nil; AltarFrontalMaker.activeMaking={}; AltarFrontalMaker.totalProducts=0; AltarFrontalMaker.dayTimer=0; print("[AltarFrontalMaker] Royal Altar Frontal Maker System initialized (6 products, 4 buildings)") end
function AltarFrontalMaker.hireMaker(n,s) s=s or math.random(50,90); local c=470+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; AltarFrontalMaker.maker={name=n or ("Antependijar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Antependijar najet: %s (spretnost: %d)",AltarFrontalMaker.maker.name,s),"success") end; return true end
function AltarFrontalMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function AltarFrontalMaker.build(id) local ok,e=AltarFrontalMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(AltarFrontalMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function AltarFrontalMaker.getQualityBonus() local b=0; for _,bd in ipairs(AltarFrontalMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function AltarFrontalMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.linenCost and AltarFrontalMaker.linenStock<(d.linenCost or 0) then return false,"Premalo lana" end; if d.silkCost and AltarFrontalMaker.silkStock<(d.silkCost or 0) then return false,"Premalo svile" end; if d.paintCost and AltarFrontalMaker.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.threadCost and AltarFrontalMaker.threadStock<(d.threadCost or 0) then return false,"Premalo niti" end; if d.goldCost and AltarFrontalMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.silverCost and AltarFrontalMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.jewelCost and AltarFrontalMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and AltarFrontalMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #AltarFrontalMaker.buildings==0 then return false,"Potrebna delavnica" end; if not AltarFrontalMaker.maker then return false,"Potreben antependijar" end; return true end
function AltarFrontalMaker.make(pt,qty) qty=qty or 1; local ok,e=AltarFrontalMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.linenCost then AltarFrontalMaker.linenStock=AltarFrontalMaker.linenStock-d.linenCost*qty end; if d.silkCost then AltarFrontalMaker.silkStock=AltarFrontalMaker.silkStock-d.silkCost*qty end; if d.paintCost then AltarFrontalMaker.paintStock=AltarFrontalMaker.paintStock-d.paintCost*qty end; if d.threadCost then AltarFrontalMaker.threadStock=AltarFrontalMaker.threadStock-d.threadCost*qty end; if d.goldCost then AltarFrontalMaker.goldStock=AltarFrontalMaker.goldStock-d.goldCost*qty end; if d.silverCost then AltarFrontalMaker.silverStock=AltarFrontalMaker.silverStock-d.silverCost*qty end; if d.jewelCost then AltarFrontalMaker.jewelStock=AltarFrontalMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then AltarFrontalMaker.pearlStock=AltarFrontalMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if AltarFrontalMaker.maker then t=math.max(1,t-math.floor(AltarFrontalMaker.maker.skill/12)) end; table.insert(AltarFrontalMaker.activeMaking,{id="frontal_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,sanctity=d.sanctity or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function AltarFrontalMaker.completeMaking(m) local q=1.0+(AltarFrontalMaker.getQualityBonus()/100); if AltarFrontalMaker.maker then q=q+(AltarFrontalMaker.maker.skill/180) end; q=math.min(2.0,q); AltarFrontalMaker.productStock[m.productType]=(AltarFrontalMaker.productStock[m.productType] or 0)+m.quantity; AltarFrontalMaker.totalProducts=AltarFrontalMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if AltarFrontalMaker.maker then AltarFrontalMaker.maker.itemsMade=AltarFrontalMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then AltarFrontalMaker.maker.skill=math.min(100,AltarFrontalMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Antependij izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"altarfrontal.completed",{productName=m.productName,sanctity=m.sanctity}) end end
function AltarFrontalMaker.update(dt) if not _G.state then return end; AltarFrontalMaker.dayTimer=AltarFrontalMaker.dayTimer+dt; if AltarFrontalMaker.dayTimer>=30 then AltarFrontalMaker.dayTimer=0; for i=#AltarFrontalMaker.activeMaking,1,-1 do local m=AltarFrontalMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then AltarFrontalMaker.completeMaking(m); table.remove(AltarFrontalMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(AltarFrontalMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if AltarFrontalMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function AltarFrontalMaker.getStats() return {linenStock=AltarFrontalMaker.linenStock,silkStock=AltarFrontalMaker.silkStock,paintStock=AltarFrontalMaker.paintStock,threadStock=AltarFrontalMaker.threadStock,goldStock=AltarFrontalMaker.goldStock,silverStock=AltarFrontalMaker.silverStock,jewelStock=AltarFrontalMaker.jewelStock,pearlStock=AltarFrontalMaker.pearlStock,productStock=AltarFrontalMaker.productStock,numBuildings=#AltarFrontalMaker.buildings,hasMaker=AltarFrontalMaker.maker~=nil,makerName=AltarFrontalMaker.maker and AltarFrontalMaker.maker.name or "—",makerSkill=AltarFrontalMaker.maker and AltarFrontalMaker.maker.skill or 0,activeMaking=#AltarFrontalMaker.activeMaking,totalProducts=AltarFrontalMaker.totalProducts} end
return AltarFrontalMaker
