local SoapMaker = {}
local PRODUCTS = {
    soap = { name = "Milo", fatCost = 2, ashCost = 1, time = 2, cost = 10, hygiene = 10, happiness = 1, description = "Preprosto milo." },
    scented_soap = { name = "Dišeče milo", fatCost = 2, ashCost = 1, herbCost = 2, time = 4, cost = 30, hygiene = 15, happiness = 5, aroma = 8, description = "Z eteričnimi olji." },
    lye = { name = "Lužina", ashCost = 3, waterCost = 1, time = 1, cost = 5, description = "Za milo in čiščenje." },
    washing_powder = { name = "Pralni prašek", ashCost = 2, fatCost = 1, time = 2, cost = 15, hygiene = 8, description = "Za pranje oblačil." },
    medicinal_soap = { name = "Zdravilno milo", fatCost = 2, ashCost = 1, herbCost = 3, time = 5, cost = 50, hygiene = 20, health = 5, description = "Z antiseptičnimi zelišči." },
    royal_soap = { name = "Kraljevsko milo", fatCost = 3, ashCost = 1, herbCost = 5, oilCost = 2, time = 7, cost = 100, hygiene = 25, happiness = 10, prestige = 5, aroma = 15, description = "Najboljše milo za kralja." },
}
local BUILDINGS = {
    workshop = { name = "Milarna", cost = { gold = 200, wood = 100 }, upkeep = 5, qualityBonus = 5 },
    soapery = { name = "Milarna", cost = { gold = 500, wood = 200, stone = 100 }, upkeep = 12, qualityBonus = 10 },
    ash_kiln = { name = "Pepelarna", cost = { gold = 300, wood = 150, stone = 50 }, upkeep = 8, ashProduction = 5 },
    royal_soapery = { name = "Kraljevska milarna", cost = { gold = 2500, wood = 400, stone = 500 }, upkeep = 50, qualityBonus = 30, prestigeBonus = 10 },
}
SoapMaker.fatStock = 15; SoapMaker.ashStock = 10; SoapMaker.herbStock = 8; SoapMaker.waterStock = 20; SoapMaker.oilStock = 5
SoapMaker.productStock = {}; SoapMaker.buildings = {}; SoapMaker.soapMaker = nil; SoapMaker.activeMaking = {}; SoapMaker.totalProducts = 0; SoapMaker.dayTimer = 0
function SoapMaker.init() SoapMaker.fatStock=15; SoapMaker.ashStock=10; SoapMaker.herbStock=8; SoapMaker.waterStock=20; SoapMaker.oilStock=5; SoapMaker.productStock={}; SoapMaker.buildings={}; SoapMaker.soapMaker=nil; SoapMaker.activeMaking={}; SoapMaker.totalProducts=0; SoapMaker.dayTimer=0; print("[SoapMaker] Royal Soap Maker & Cleansing System initialized (6 products, 4 buildings)") end
function SoapMaker.hireSoapMaker(n,s) s=s or math.random(35,75); local c=200+s*4; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SoapMaker.soapMaker={name=n or ("Milar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Milar najet: %s (spretnost: %d)",SoapMaker.soapMaker.name,s),"success") end; return true end
function SoapMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SoapMaker.build(id) local ok,e=SoapMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SoapMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SoapMaker.getQualityBonus() local b=0; for _,bd in ipairs(SoapMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SoapMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.fatCost and SoapMaker.fatStock<(d.fatCost or 0) then return false,"Premalo maščobe" end; if d.ashCost and SoapMaker.ashStock<(d.ashCost or 0) then return false,"Premalo pepela" end; if d.herbCost and SoapMaker.herbStock<(d.herbCost or 0) then return false,"Premalo zelišč" end; if d.waterCost and SoapMaker.waterStock<(d.waterCost or 0) then return false,"Premalo vode" end; if d.oilCost and SoapMaker.oilStock<(d.oilCost or 0) then return false,"Premalo olja" end; if #SoapMaker.buildings==0 then return false,"Potrebna milarna" end; if not SoapMaker.soapMaker then return false,"Potreben milar" end; return true end
function SoapMaker.make(pt) local ok,e=SoapMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.fatCost then SoapMaker.fatStock=SoapMaker.fatStock-d.fatCost end; if d.ashCost then SoapMaker.ashStock=SoapMaker.ashStock-d.ashCost end; if d.herbCost then SoapMaker.herbStock=SoapMaker.herbStock-d.herbCost end; if d.waterCost then SoapMaker.waterStock=SoapMaker.waterStock-d.waterCost end; if d.oilCost then SoapMaker.oilStock=SoapMaker.oilStock-d.oilCost end; local t=d.time; if SoapMaker.soapMaker then t=math.max(1,t-math.floor(SoapMaker.soapMaker.skill/15)) end; table.insert(SoapMaker.activeMaking,{id="soap_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost,hygiene=d.hygiene or 0,happiness=d.happiness or 0,health=d.health or 0,prestige=d.prestige or 0,aroma=d.aroma or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %s (%d dni)",d.name,t),"info") end; return true end
function SoapMaker.completeMaking(m) local q=1.0+(SoapMaker.getQualityBonus()/100); if SoapMaker.soapMaker then q=q+(SoapMaker.soapMaker.skill/200) end; q=math.min(2.0,q); SoapMaker.productStock[m.productType]=(SoapMaker.productStock[m.productType] or 0)+1; SoapMaker.totalProducts=SoapMaker.totalProducts+1; if _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness*q) end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if SoapMaker.soapMaker then SoapMaker.soapMaker.itemsMade=SoapMaker.soapMaker.itemsMade+1; if math.random()<0.15 then SoapMaker.soapMaker.skill=math.min(100,SoapMaker.soapMaker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Milo izdelano: %s (kakovost: %.1f)",m.productName,q),"success") end end
function SoapMaker.update(dt) if not _G.state then return end; SoapMaker.dayTimer=SoapMaker.dayTimer+dt; if SoapMaker.dayTimer>=30 then SoapMaker.dayTimer=0; for i=#SoapMaker.activeMaking,1,-1 do local m=SoapMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SoapMaker.completeMaking(m); table.remove(SoapMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SoapMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SoapMaker.soapMaker then tu=tu+6 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SoapMaker.getStats() return {fatStock=SoapMaker.fatStock,ashStock=SoapMaker.ashStock,herbStock=SoapMaker.herbStock,productStock=SoapMaker.productStock,numBuildings=#SoapMaker.buildings,hasSoapMaker=SoapMaker.soapMaker~=nil,soapMakerName=SoapMaker.soapMaker and SoapMaker.soapMaker.name or "—",soapMakerSkill=SoapMaker.soapMaker and SoapMaker.soapMaker.skill or 0,activeMaking=#SoapMaker.activeMaking,totalProducts=SoapMaker.totalProducts} end
return SoapMaker
