stages:
  - test

image: ubuntu

cache:
  key: ${CI_COMMIT_REF_SLUG}

run: 
  stage: test
  script:
    - echo "deb http://ppa.launchpad.net/bartbes/love-stable/ubuntu $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list
    - echo "deb-src http://ppa.launchpad.net/bartbes/love-stable/ubuntu $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list
    - apt-get update
    - apt-get install --assume-yes zip
    - zip -9 -r test.love .
    - apt-get install --assume-yes git
    - apt-get install --assume-yes libmodplug1
    - apt-get install --assume-yes libmpg123-0
    - apt-get install --assume-yes libogg0
    - apt-get install --assume-yes libopenal1
    - apt-get install --assume-yes libphysfs1
    - apt-get install --assume-yes libsdl2-2.0-0
    - apt-get install --assume-yes libluajit-5.1-2
    - apt-get install --assume-yes libtheora0
    - apt-get install --assume-yes libvorbisfile3
    - apt-get install --assume-yes libfreetype6
    - apt-get install --assume-yes love==11.3ppa1
    - cat /usr/bin/love test.love > testbuild
    - chmod a+x ./testbuild
    - apt-get install --assume-yes luarocks
    - luarocks install luacheck
    - luarocks install luacov
    - luarocks install luacov-console
    - luarocks install dkjson
    - luarocks install luasystem
    - luarocks install lua_cliargs
    - luarocks install say
    - luarocks install luassert
    - luarocks install lua-term
    - luarocks install penlight
    - luarocks install mediator_lua  
    - ls 
    - rm -r busted
    - rm -r libraries 
    - rm -r spec 
    - rm -r objects/object_quads.lua
    - RES=$(./testbuild --verbose --coverage --test) || { echo "$RES"; exit 1; }
    - luacov-console 
    - luacov-console -s && echo "$RES"   
    
