stages:
  - test


run: 
  stage: test
  script:
    - apt-get update
    - apt-get install --assume-yes zip
    - zip -9 -r test.love .
    - apt-get install --assume-yes libmodplug1
    - apt-get install --assume-yes libmpg123-0
    - apt-get install --assume-yes libogg0
    - apt-get install --assume-yes libopenal1
    - apt-get install --assume-yes libphysfs1
    - apt-get install --assume-yes libsdl2-2.0-0
    - apt-get install --assume-yes libluajit-5.1-2
    - apt-get install --assume-yes libtheora0
    - apt-get install --assume-yes libvorbisfile3
    - dpkg -i libraries/love/liblove0_0.10.2ppa1_amd64.deb
    - dpkg -i libraries/love/love_0.10.2ppa1_amd64.deb
    - cat /usr/bin/love test.love > testbuild
    - chmod a+x ./testbuild
    - apt-get install --assume-yes cmake
    - apt-get install --assume-yes luarocks
    - git clone https://github.com/torch/luajit-rocks.git
    - cd luajit-rocks
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/ljit
    - make install
    - ls
    - cd ..
    - cd ..
    - luarocks install luacheck
    - luarocks install luacov
    - luarocks install busted
    - luacheck --globals love --std max+busted *.lua spec
    - ./testbuild --test
    
