local InkMaker = {}
local PRODUCTS = {
    iron_gall = { name = "Železno galno črnilo", ironCost = 1, gallCost = 2, time = 3, cost = 20, quality = 15, description = "Standardno črnilo za dokumente." },
    lampblack = { name = "Čađno črnilo", sootCost = 2, oilCost = 1, time = 2, cost = 15, quality = 10, description = "Črnilo iz čađe." },
    red_ink = { name = "Rdeče črnilo", cinnabarCost = 1, gallCost = 1, time = 3, cost = 40, quality = 20, prestige = 3, description = "Za plemiške dokumente." },
    gold_ink = { name = "Zlato črnilo", goldCost = 1, gumCost = 1, time = 5, cost = 100, quality = 30, prestige = 10, description = "Zlati pigment za iluminacije." },
    invisible_ink = { name = "Nevidno črnilo", lemonCost = 2, time = 2, cost = 30, secrecy = 0.20, description = "Za tajne sporočila." },
    royal_ink = { name = "Kraljevsko črnilo", goldCost = 2, gallCost = 3, gumCost = 2, time = 7, cost = 200, quality = 40, prestige = 15, description = "Najboljše črnilo za kralja." },
}
local BUILDINGS = {
    workshop = { name = "Črnilnica", cost = { gold = 200, wood = 100 }, upkeep = 5, qualityBonus = 5 },
    ink_mill = { name = "Mlin za črnilo", cost = { gold = 500, wood = 200, stone = 100 }, upkeep = 12, qualityBonus = 10 },
    pigment_workshop = { name = "Pigmentna delavnica", cost = { gold = 1000, wood = 200, stone = 200, iron = 50 }, upkeep = 25, qualityBonus = 20 },
    royal_inkworks = { name = "Kraljevska črnilnica", cost = { gold = 3000, wood = 400, stone = 600 }, upkeep = 60, qualityBonus = 35, prestigeBonus = 15 },
}
InkMaker.ironStock = 8; InkMaker.gallStock = 10; InkMaker.sootStock = 8; InkMaker.oilStock = 5; InkMaker.cinnabarStock = 3; InkMaker.goldStock = 3; InkMaker.gumStock = 5; InkMaker.lemonStock = 5
InkMaker.productStock = {}; InkMaker.buildings = {}; InkMaker.inkMaker = nil; InkMaker.activeMaking = {}; InkMaker.totalProducts = 0; InkMaker.dayTimer = 0
function InkMaker.init() InkMaker.ironStock=8; InkMaker.gallStock=10; InkMaker.sootStock=8; InkMaker.oilStock=5; InkMaker.cinnabarStock=3; InkMaker.goldStock=3; InkMaker.gumStock=5; InkMaker.lemonStock=5; InkMaker.productStock={}; InkMaker.buildings={}; InkMaker.inkMaker=nil; InkMaker.activeMaking={}; InkMaker.totalProducts=0; InkMaker.dayTimer=0; print("[InkMaker] Royal Ink Maker & Writing Materials System initialized (6 products, 4 buildings)") end
function InkMaker.hireInkMaker(n,s) s=s or math.random(35,80); local c=250+s*5; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; InkMaker.inkMaker={name=n or ("Črnilkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Črnilkar najet: %s (spretnost: %d)",InkMaker.inkMaker.name,s),"success") end; return true end
function InkMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function InkMaker.build(id) local ok,e=InkMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(InkMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function InkMaker.getQualityBonus() local b=0; for _,bd in ipairs(InkMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function InkMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and InkMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.gallCost and InkMaker.gallStock<(d.gallCost or 0) then return false,"Premalo gall" end; if d.sootCost and InkMaker.sootStock<(d.sootCost or 0) then return false,"Premalo čađe" end; if d.oilCost and InkMaker.oilStock<(d.oilCost or 0) then return false,"Premalo olja" end; if d.cinnabarCost and InkMaker.cinnabarStock<(d.cinnabarCost or 0) then return false,"Premalo cinabarita" end; if d.goldCost and InkMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.gumCost and InkMaker.gumStock<(d.gumCost or 0) then return false,"Premalo gumije" end; if d.lemonCost and InkMaker.lemonStock<(d.lemonCost or 0) then return false,"Premalo limon" end; if #InkMaker.buildings==0 then return false,"Potrebna črnilnica" end; if not InkMaker.inkMaker then return false,"Potreben črnilkar" end; return true end
function InkMaker.make(pt) local ok,e=InkMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then InkMaker.ironStock=InkMaker.ironStock-d.ironCost end; if d.gallCost then InkMaker.gallStock=InkMaker.gallStock-d.gallCost end; if d.sootCost then InkMaker.sootStock=InkMaker.sootStock-d.sootCost end; if d.oilCost then InkMaker.oilStock=InkMaker.oilStock-d.oilCost end; if d.cinnabarCost then InkMaker.cinnabarStock=InkMaker.cinnabarStock-d.cinnabarCost end; if d.goldCost then InkMaker.goldStock=InkMaker.goldStock-d.goldCost end; if d.gumCost then InkMaker.gumStock=InkMaker.gumStock-d.gumCost end; if d.lemonCost then InkMaker.lemonStock=InkMaker.lemonStock-d.lemonCost end; local t=d.time; if InkMaker.inkMaker then t=math.max(1,t-math.floor(InkMaker.inkMaker.skill/15)) end; table.insert(InkMaker.activeMaking,{id="ink_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost,quality=d.quality or 0,prestige=d.prestige or 0,secrecy=d.secrecy or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %s (%d dni)",d.name,t),"info") end; return true end
function InkMaker.completeMaking(m) local q=1.0+(InkMaker.getQualityBonus()/100); if InkMaker.inkMaker then q=q+(InkMaker.inkMaker.skill/200) end; q=math.min(2.0,q); InkMaker.productStock[m.productType]=(InkMaker.productStock[m.productType] or 0)+1; InkMaker.totalProducts=InkMaker.totalProducts+1; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if InkMaker.inkMaker then InkMaker.inkMaker.itemsMade=InkMaker.inkMaker.itemsMade+1; if math.random()<0.15 then InkMaker.inkMaker.skill=math.min(100,InkMaker.inkMaker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Črnilo izdelano: %s (kakovost: %.1f)",m.productName,q),"success") end end
function InkMaker.update(dt) if not _G.state then return end; InkMaker.dayTimer=InkMaker.dayTimer+dt; if InkMaker.dayTimer>=30 then InkMaker.dayTimer=0; for i=#InkMaker.activeMaking,1,-1 do local m=InkMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then InkMaker.completeMaking(m); table.remove(InkMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(InkMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if InkMaker.inkMaker then tu=tu+8 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function InkMaker.getStats() return {ironStock=InkMaker.ironStock,gallStock=InkMaker.gallStock,goldStock=InkMaker.goldStock,productStock=InkMaker.productStock,numBuildings=#InkMaker.buildings,hasInkMaker=InkMaker.inkMaker~=nil,inkMakerName=InkMaker.inkMaker and InkMaker.inkMaker.name or "—",inkMakerSkill=InkMaker.inkMaker and InkMaker.inkMaker.skill or 0,activeMaking=#InkMaker.activeMaking,totalProducts=InkMaker.totalProducts} end
return InkMaker
