local Locksmith = {}
local PRODUCTS = {
    padlock = { name = "Viseči ključavnik", ironCost = 2, time = 2, cost = 30, securityLevel = 20, description = "Preprost ključavnik." },
    door_lock = { name = "Vratna ključavnica", ironCost = 4, time = 4, cost = 80, securityLevel = 40, description = "Vgrajena ključavnica." },
    chest_lock = { name = "Skladiščna ključavnica", ironCost = 3, time = 3, cost = 60, securityLevel = 50, description = "Za skrinje in trezorje." },
    combination = { name = "Kombinacijska ključavnica", ironCost = 6, time = 7, cost = 200, securityLevel = 70, description = "Brez ključa — s kodo." },
    magic_lock = { name = "Začarana ključavnica", ironCost = 5, goldCost = 2, time = 14, cost = 500, securityLevel = 90, prestige = 10, description = "Z magično zaščito." },
    key_set = { name = "Set ključev", ironCost = 1, time = 1, cost = 15, description = "Rezervni ključi." },
}
local BUILDINGS = {
    workshop = { name = "Ključavničarska delavnica", cost = { gold = 300, wood = 100, iron = 50 }, upkeep = 10, qualityBonus = 5 },
    forge = { name = "Ključavničarska kovašnica", cost = { gold = 1000, wood = 200, stone = 200, iron = 100 }, upkeep = 25, qualityBonus = 20 },
    security_vault = { name = "Varnostni trezor", cost = { gold = 3000, wood = 300, stone = 800, iron = 200 }, upkeep = 50, qualityBonus = 30, securityBonus = 20 },
    royal_locksmith = { name = "Kraljevski ključavničar", cost = { gold = 5000, wood = 400, stone = 1000, iron = 300 }, upkeep = 100, qualityBonus = 45, prestigeBonus = 15 },
}
Locksmith.ironStock = 10; Locksmith.goldStock = 5; Locksmith.productStock = {}; Locksmith.buildings = {}; Locksmith.locksmith = nil
Locksmith.activeMaking = {}; Locksmith.totalProducts = 0; Locksmith.dayTimer = 0
function Locksmith.init() Locksmith.ironStock=10; Locksmith.goldStock=5; Locksmith.productStock={}; Locksmith.buildings={}; Locksmith.locksmith=nil; Locksmith.activeMaking={}; Locksmith.totalProducts=0; Locksmith.dayTimer=0; print("[Locksmith] Royal Locksmith & Security System initialized (6 products, 4 buildings)") end
function Locksmith.hireLocksmith(n,s) s=s or math.random(40,85); local c=400+s*8; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; Locksmith.locksmith={name=n or ("Ključavničar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ključavničar najet: %s (spretnost: %d)",Locksmith.locksmith.name,s),"success") end; return true end
function Locksmith.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function Locksmith.build(id) local ok,e=Locksmith.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(Locksmith.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function Locksmith.getQualityBonus() local b=0; for _,bd in ipairs(Locksmith.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function Locksmith.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if Locksmith.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.goldCost and Locksmith.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if #Locksmith.buildings==0 then return false,"Potrebna delavnica" end; if not Locksmith.locksmith then return false,"Potreben ključavničar" end; return true end
function Locksmith.make(pt) local ok,e=Locksmith.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; Locksmith.ironStock=Locksmith.ironStock-(d.ironCost or 0); if d.goldCost then Locksmith.goldStock=Locksmith.goldStock-d.goldCost end; local t=d.time; if Locksmith.locksmith then t=math.max(1,t-math.floor(Locksmith.locksmith.skill/12)) end; table.insert(Locksmith.activeMaking,{id="lock_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost,securityLevel=d.securityLevel or 0,prestige=d.prestige or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %s (%d dni)",d.name,t),"info") end; return true end
function Locksmith.completeMaking(m) local q=1.0+(Locksmith.getQualityBonus()/100); if Locksmith.locksmith then q=q+(Locksmith.locksmith.skill/200) end; q=math.min(2.0,q); Locksmith.productStock[m.productType]=(Locksmith.productStock[m.productType] or 0)+1; Locksmith.totalProducts=Locksmith.totalProducts+1; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if Locksmith.locksmith then Locksmith.locksmith.itemsMade=Locksmith.locksmith.itemsMade+1; if math.random()<0.15 then Locksmith.locksmith.skill=math.min(100,Locksmith.locksmith.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ključavnica izdelana: %s (kakovost: %.1f)",m.productName,q),"success") end end
function Locksmith.update(dt) if not _G.state then return end; Locksmith.dayTimer=Locksmith.dayTimer+dt; if Locksmith.dayTimer>=30 then Locksmith.dayTimer=0; for i=#Locksmith.activeMaking,1,-1 do local m=Locksmith.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then Locksmith.completeMaking(m); table.remove(Locksmith.activeMaking,i) end end; local tu=0; for _,bd in ipairs(Locksmith.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if Locksmith.locksmith then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function Locksmith.getStats() return {ironStock=Locksmith.ironStock,goldStock=Locksmith.goldStock,productStock=Locksmith.productStock,numBuildings=#Locksmith.buildings,hasLocksmith=Locksmith.locksmith~=nil,locksmithName=Locksmith.locksmith and Locksmith.locksmith.name or "—",locksmithSkill=Locksmith.locksmith and Locksmith.locksmith.skill or 0,activeMaking=#Locksmith.activeMaking,totalProducts=Locksmith.totalProducts} end
return Locksmith
