local WaxModeler = {}
local PRODUCTS = {
    wax_model = { name = "Voščeni model", waxCost = 2, time = 2, cost = 15, description = "Model za livljenje." },
    seal_press = { name = "Pečatna stiska", woodCost = 2, metalCost = 2, time = 5, cost = 50, securityLevel = 20, description = "Stiska za pečatenje." },
    wax_figure = { name = "Voščena figura", waxCost = 5, paintCost = 1, time = 7, cost = 80, happiness = 3, prestige = 3, description = "Okrasna voščena figura." },
    death_mask = { name = "Posmrtna maska", waxCost = 8, plasterCost = 2, time = 5, cost = 150, prestige = 5, faith = 5, description = "Maska za pogreb." },
    wax_tableau = { name = "Voščena tabla", waxCost = 10, paintCost = 2, woodCost = 3, time = 14, cost = 300, happiness = 8, prestige = 12, description = "Scena iz voska." },
    royal_wax_effigy = { name = "Kraljevski voščeni dvojnik", waxCost = 15, goldCost = 1, paintCost = 3, silkCost = 2, time = 30, cost = 800, happiness = 15, prestige = 30, faith = 10, description = "Voščeni dvojnik kralja za ceremonialne namene." },
}
local BUILDINGS = {
    workshop = { name = "Voščarska delavnica", cost = { gold = 200, wood = 100 }, upkeep = 5, qualityBonus = 5 },
    modeling_studio = { name = "Modelirni atelje", cost = { gold = 800, wood = 200, stone = 200 }, upkeep = 20, qualityBonus = 20 },
    casting_prep = { name = "Livarska priprava", cost = { gold = 1200, wood = 200, stone = 300, wax = 50 }, upkeep = 25, qualityBonus = 15 },
    royal_waxworks = { name = "Kraljevska voščarna", cost = { gold = 3500, wood = 400, stone = 600, gold = 30 }, upkeep = 70, qualityBonus = 35, prestigeBonus = 20 },
}
WaxModeler.waxStock = 15; WaxModeler.woodStock = 10; WaxModeler.metalStock = 5; WaxModeler.paintStock = 3; WaxModeler.plasterStock = 5; WaxModeler.goldStock = 2; WaxModeler.silkStock = 2
WaxModeler.productStock = {}; WaxModeler.buildings = {}; WaxModeler.modeler = nil; WaxModeler.activeMaking = {}; WaxModeler.totalProducts = 0; WaxModeler.dayTimer = 0
function WaxModeler.init() WaxModeler.waxStock=15; WaxModeler.woodStock=10; WaxModeler.metalStock=5; WaxModeler.paintStock=3; WaxModeler.plasterStock=5; WaxModeler.goldStock=2; WaxModeler.silkStock=2; WaxModeler.productStock={}; WaxModeler.buildings={}; WaxModeler.modeler=nil; WaxModeler.activeMaking={}; WaxModeler.totalProducts=0; WaxModeler.dayTimer=0; print("[WaxModeler] Royal Wax Modeler & Seal Press System initialized (6 products, 4 buildings)") end
function WaxModeler.hireModeler(n,s) s=s or math.random(35,80); local c=250+s*5; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; WaxModeler.modeler={name=n or ("Voščar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Voščar najet: %s (spretnost: %d)",WaxModeler.modeler.name,s),"success") end; return true end
function WaxModeler.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function WaxModeler.build(id) local ok,e=WaxModeler.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(WaxModeler.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function WaxModeler.getQualityBonus() local b=0; for _,bd in ipairs(WaxModeler.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function WaxModeler.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.waxCost and WaxModeler.waxStock<(d.waxCost or 0) then return false,"Premalo voska" end; if d.woodCost and WaxModeler.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.metalCost and WaxModeler.metalStock<(d.metalCost or 0) then return false,"Premalo kovine" end; if d.paintCost and WaxModeler.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.plasterCost and WaxModeler.plasterStock<(d.plasterCost or 0) then return false,"Premalo mavca" end; if d.goldCost and WaxModeler.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.silkCost and WaxModeler.silkStock<(d.silkCost or 0) then return false,"Premalo svile" end; if #WaxModeler.buildings==0 then return false,"Potrebna delavnica" end; if not WaxModeler.modeler then return false,"Potreben voščar" end; return true end
function WaxModeler.make(pt) local ok,e=WaxModeler.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.waxCost then WaxModeler.waxStock=WaxModeler.waxStock-d.waxCost end; if d.woodCost then WaxModeler.woodStock=WaxModeler.woodStock-d.woodCost end; if d.metalCost then WaxModeler.metalStock=WaxModeler.metalStock-d.metalCost end; if d.paintCost then WaxModeler.paintStock=WaxModeler.paintStock-d.paintCost end; if d.plasterCost then WaxModeler.plasterStock=WaxModeler.plasterStock-d.plasterCost end; if d.goldCost then WaxModeler.goldStock=WaxModeler.goldStock-d.goldCost end; if d.silkCost then WaxModeler.silkStock=WaxModeler.silkStock-d.silkCost end; local t=d.time; if WaxModeler.modeler then t=math.max(1,t-math.floor(WaxModeler.modeler.skill/12)) end; table.insert(WaxModeler.activeMaking,{id="wax_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost,securityLevel=d.securityLevel or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,faith=d.faith or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Modeliranje: %s (%d dni)",d.name,t),"info") end; return true end
function WaxModeler.completeMaking(m) local q=1.0+(WaxModeler.getQualityBonus()/100); if WaxModeler.modeler then q=q+(WaxModeler.modeler.skill/200) end; q=math.min(2.5,q); WaxModeler.productStock[m.productType]=(WaxModeler.productStock[m.productType] or 0)+1; WaxModeler.totalProducts=WaxModeler.totalProducts+1; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if m.faith>0 and _G.Religion then pcall(_G.Religion.addFaith,m.faith) end; if WaxModeler.modeler then WaxModeler.modeler.itemsMade=WaxModeler.modeler.itemsMade+1; if math.random()<0.15 then WaxModeler.modeler.skill=math.min(100,WaxModeler.modeler.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Voščeni model izdelan: %s (kakovost: %.1f)",m.productName,q),"success") end end
function WaxModeler.update(dt) if not _G.state then return end; WaxModeler.dayTimer=WaxModeler.dayTimer+dt; if WaxModeler.dayTimer>=30 then WaxModeler.dayTimer=0; for i=#WaxModeler.activeMaking,1,-1 do local m=WaxModeler.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then WaxModeler.completeMaking(m); table.remove(WaxModeler.activeMaking,i) end end; local tu=0; for _,bd in ipairs(WaxModeler.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if WaxModeler.modeler then tu=tu+8 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function WaxModeler.getStats() return {waxStock=WaxModeler.waxStock,woodStock=WaxModeler.woodStock,paintStock=WaxModeler.paintStock,goldStock=WaxModeler.goldStock,productStock=WaxModeler.productStock,numBuildings=#WaxModeler.buildings,hasModeler=WaxModeler.modeler~=nil,modelerName=WaxModeler.modeler and WaxModeler.modeler.name or "—",modelerSkill=WaxModeler.modeler and WaxModeler.modeler.skill or 0,activeMaking=#WaxModeler.activeMaking,totalProducts=WaxModeler.totalProducts} end
return WaxModeler
