local RetortMaker = {}
local PRODUCTS = {
    simple_glass_retort = { name = "Preprosta steklena retorta", glassCost = 2, clayCost = 1, time = 4, cost = 45, science = 18, happiness = 1, description = "Preprosta steklena retorta za destilacijo." },
    bent_neck_retort = { name = "Upognjenovratna retorta", glassCost = 3, clayCost = 1, time = 6, cost = 130, science = 32, happiness = 1, prestige = 2, description = "Upognjenovratna retorta za trgovce." },
    silver_joint_retort = { name = "Srebrnospojna retorta", glassCost = 3, silverCost = 1, clayCost = 1, time = 9, cost = 320, science = 48, happiness = 2, prestige = 6, description = "Srebrnospojna retorta za plemiče." },
    gold_rim_retort = { name = "Zlatookrasna retorta", glassCost = 4, goldCost = 1, silverCost = 1, clayCost = 1, time = 13, cost = 760, science = 62, happiness = 3, prestige = 14, description = "Zlatookrasna retorta za visoke plemiče." },
    jewel_set_retort = { name = "Draguljasta retorta", glassCost = 4, goldCost = 2, silverCost = 1, clayCost = 1, jewelCost = 1, time = 17, cost = 1700, science = 78, happiness = 5, prestige = 27, description = "Retorta z draguljem za visoko plemstvo." },
    royal_grand_retort = { name = "Kraljevski veliki retorta", glassCost = 6, goldCost = 3, silverCost = 2, clayCost = 2, jewelCost = 2, pearlCost = 2, time = 24, cost = 3900, science = 92, happiness = 12, prestige = 58, description = "Velika kraljevska retorta z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    retort_workshop = { name = "Retortna delavnica", cost = { gold = 240, wood = 100, stone = 120, glass = 6 }, upkeep = 5, qualityBonus = 5 },
    distillation_loft = { name = "Destilacijska podstrešje", cost = { gold = 880, wood = 240, stone = 240, silver = 6, glass = 8 }, upkeep = 20, qualityBonus = 18 },
    master_glass_atelier = { name = "Mojstrski steklarski atelje", cost = { gold = 2500, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 58, qualityBonus = 30 },
    royal_retort_palace = { name = "Kraljevska retortna palača", cost = { gold = 10500, wood = 580, stone = 760, gold = 65, jewel = 16 }, upkeep = 210, qualityBonus = 55, prestigeBonus = 50 },
}
RetortMaker.glassStock = 18; RetortMaker.clayStock = 12; RetortMaker.silverStock = 6; RetortMaker.goldStock = 6; RetortMaker.jewelStock = 4; RetortMaker.pearlStock = 4
RetortMaker.productStock = {}; RetortMaker.buildings = {}; RetortMaker.maker = nil; RetortMaker.activeMaking = {}; RetortMaker.totalProducts = 0; RetortMaker.dayTimer = 0
function RetortMaker.init() RetortMaker.glassStock=18; RetortMaker.clayStock=12; RetortMaker.silverStock=6; RetortMaker.goldStock=6; RetortMaker.jewelStock=4; RetortMaker.pearlStock=4; RetortMaker.productStock={}; RetortMaker.buildings={}; RetortMaker.maker=nil; RetortMaker.activeMaking={}; RetortMaker.totalProducts=0; RetortMaker.dayTimer=0; print("[RetortMaker] Royal Retort Maker System initialized (6 products, 4 buildings)") end
function RetortMaker.hireMaker(n,s) s=s or math.random(55,90); local c=500+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; RetortMaker.maker={name=n or ("Retortar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Retortar najet: %s (spretnost: %d)",RetortMaker.maker.name,s),"success") end; return true end
function RetortMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function RetortMaker.build(id) local ok,e=RetortMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(RetortMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function RetortMaker.getQualityBonus() local b=0; for _,bd in ipairs(RetortMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function RetortMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.glassCost and RetortMaker.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.clayCost and RetortMaker.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.silverCost and RetortMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and RetortMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and RetortMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and RetortMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #RetortMaker.buildings==0 then return false,"Potrebna retortna delavnica" end; if not RetortMaker.maker then return false,"Potreben retortar" end; return true end
function RetortMaker.make(pt,qty) qty=qty or 1; local ok,e=RetortMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.glassCost then RetortMaker.glassStock=RetortMaker.glassStock-d.glassCost*qty end; if d.clayCost then RetortMaker.clayStock=RetortMaker.clayStock-d.clayCost*qty end; if d.silverCost then RetortMaker.silverStock=RetortMaker.silverStock-d.silverCost*qty end; if d.goldCost then RetortMaker.goldStock=RetortMaker.goldStock-d.goldCost*qty end; if d.jewelCost then RetortMaker.jewelStock=RetortMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then RetortMaker.pearlStock=RetortMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if RetortMaker.maker then t=math.max(1,t-math.floor(RetortMaker.maker.skill/13)) end; table.insert(RetortMaker.activeMaking,{id="retort_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function RetortMaker.completeMaking(m) local q=1.0+(RetortMaker.getQualityBonus()/100); if RetortMaker.maker then q=q+(RetortMaker.maker.skill/150) end; q=math.min(2.4,q); RetortMaker.productStock[m.productType]=(RetortMaker.productStock[m.productType] or 0)+m.quantity; RetortMaker.totalProducts=RetortMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if RetortMaker.maker then RetortMaker.maker.itemsMade=RetortMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then RetortMaker.maker.skill=math.min(100,RetortMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Retorta izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"retort.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function RetortMaker.update(dt) if not _G.state then return end; RetortMaker.dayTimer=RetortMaker.dayTimer+dt; if RetortMaker.dayTimer>=30 then RetortMaker.dayTimer=0; for i=#RetortMaker.activeMaking,1,-1 do local m=RetortMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then RetortMaker.completeMaking(m); table.remove(RetortMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(RetortMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if RetortMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function RetortMaker.getStats() return {glassStock=RetortMaker.glassStock,clayStock=RetortMaker.clayStock,silverStock=RetortMaker.silverStock,goldStock=RetortMaker.goldStock,jewelStock=RetortMaker.jewelStock,pearlStock=RetortMaker.pearlStock,productStock=RetortMaker.productStock,numBuildings=#RetortMaker.buildings,hasMaker=RetortMaker.maker~=nil,makerName=RetortMaker.maker and RetortMaker.maker.name or "—",makerSkill=RetortMaker.maker and RetortMaker.maker.skill or 0,activeMaking=#RetortMaker.activeMaking,totalProducts=RetortMaker.totalProducts} end
return RetortMaker
