local PouringLadleMaker = {}
local PRODUCTS = {
    iron_pouringladle = { name = "Železni livarska zajemalka", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni livarska zajemalka za livarje." },
    bronze_pouringladle = { name = "Bronast livarska zajemalka", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast livarska zajemalka za livarje." },
    silver_pouringladle = { name = "Srebrn livarska zajemalka", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn livarska zajemalka za livarje." },
    gilded_pouringladle = { name = "Pozlačen livarska zajemalka", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen livarska zajemalka za livarje." },
    jewel_set_pouringladle = { name = "Draguljast livarska zajemalka", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast livarska zajemalka za livarje." },
    royal_sovereign_pouringladle = { name = "Kraljevski suveren livarska zajemalka", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren livarska zajemalka z biseri za krono." },
}
local BUILDINGS = {
    pouringladle_workshop = { name = "Pouringladle delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    pouringladle_house = { name = "Pouringladle hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_pouringladle_atelier = { name = "Mojstrski pouringladle atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_pouringladle_palace = { name = "Suverena pouringladle palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
PouringLadleMaker.ironStock=18; PouringLadleMaker.bronzeStock=14; PouringLadleMaker.woodStock=10; PouringLadleMaker.leatherStock=8; PouringLadleMaker.silverStock=8; PouringLadleMaker.goldStock=6; PouringLadleMaker.jewelStock=4; PouringLadleMaker.pearlStock=4
PouringLadleMaker.productStock = {}; PouringLadleMaker.buildings = {}; PouringLadleMaker.maker = nil; PouringLadleMaker.activeMaking = {}; PouringLadleMaker.totalProducts = 0; PouringLadleMaker.dayTimer = 0
function PouringLadleMaker.init() PouringLadleMaker.ironStock=18; PouringLadleMaker.bronzeStock=14; PouringLadleMaker.woodStock=10; PouringLadleMaker.leatherStock=8; PouringLadleMaker.silverStock=8; PouringLadleMaker.goldStock=6; PouringLadleMaker.jewelStock=4; PouringLadleMaker.pearlStock=4; PouringLadleMaker.productStock={}; PouringLadleMaker.buildings={}; PouringLadleMaker.maker=nil; PouringLadleMaker.activeMaking={}; PouringLadleMaker.totalProducts=0; PouringLadleMaker.dayTimer=0; print("[PouringLadleMaker] Royal Pouring Ladle Maker System initialized (6 products, 4 buildings)") end
function PouringLadleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PouringLadleMaker.maker={name=n or ("Zajemalkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zajemalkar najet: %s (spretnost: %d)",PouringLadleMaker.maker.name,s),"success") end; return true end
function PouringLadleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PouringLadleMaker.build(id) local ok,e=PouringLadleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PouringLadleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PouringLadleMaker.getQualityBonus() local b=0; for _,bd in ipairs(PouringLadleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PouringLadleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PouringLadleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and PouringLadleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and PouringLadleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PouringLadleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PouringLadleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PouringLadleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PouringLadleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PouringLadleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PouringLadleMaker.buildings==0 then return false,"Potrebna zajemalna delavnica" end; if not PouringLadleMaker.maker then return false,"Potreben zajemalkar" end; return true end
function PouringLadleMaker.make(pt,qty) qty=qty or 1; local ok,e=PouringLadleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PouringLadleMaker.ironStock=PouringLadleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then PouringLadleMaker.bronzeStock=PouringLadleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then PouringLadleMaker.woodStock=PouringLadleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PouringLadleMaker.leatherStock=PouringLadleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then PouringLadleMaker.silverStock=PouringLadleMaker.silverStock-d.silverCost*qty end; if d.goldCost then PouringLadleMaker.goldStock=PouringLadleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PouringLadleMaker.jewelStock=PouringLadleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PouringLadleMaker.pearlStock=PouringLadleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PouringLadleMaker.maker then t=math.max(1,t-math.floor(PouringLadleMaker.maker.skill/13)) end; table.insert(PouringLadleMaker.activeMaking,{id="pouringladle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PouringLadleMaker.completeMaking(m) local q=1.0+(PouringLadleMaker.getQualityBonus()/100); if PouringLadleMaker.maker then q=q+(PouringLadleMaker.maker.skill/140) end; q=math.min(2.5,q); PouringLadleMaker.productStock[m.productType]=(PouringLadleMaker.productStock[m.productType] or 0)+m.quantity; PouringLadleMaker.totalProducts=PouringLadleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PouringLadleMaker.maker then PouringLadleMaker.maker.itemsMade=PouringLadleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PouringLadleMaker.maker.skill=math.min(100,PouringLadleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zajemalka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"pouringladle.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function PouringLadleMaker.update(dt) if not _G.state then return end; PouringLadleMaker.dayTimer=PouringLadleMaker.dayTimer+dt; if PouringLadleMaker.dayTimer>=30 then PouringLadleMaker.dayTimer=0; for i=#PouringLadleMaker.activeMaking,1,-1 do local m=PouringLadleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PouringLadleMaker.completeMaking(m); table.remove(PouringLadleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PouringLadleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PouringLadleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PouringLadleMaker.getStats() return {ironStock=PouringLadleMaker.ironStock,bronzeStock=PouringLadleMaker.bronzeStock,woodStock=PouringLadleMaker.woodStock,leatherStock=PouringLadleMaker.leatherStock,silverStock=PouringLadleMaker.silverStock,goldStock=PouringLadleMaker.goldStock,jewelStock=PouringLadleMaker.jewelStock,pearlStock=PouringLadleMaker.pearlStock,productStock=PouringLadleMaker.productStock,numBuildings=#PouringLadleMaker.buildings,hasMaker=PouringLadleMaker.maker~=nil,makerName=PouringLadleMaker.maker and PouringLadleMaker.maker.name or "—",makerSkill=PouringLadleMaker.maker and PouringLadleMaker.maker.skill or 0,activeMaking=#PouringLadleMaker.activeMaking,totalProducts=PouringLadleMaker.totalProducts} end
return PouringLadleMaker
