local MillDriveBeltMaker = {}
local PRODUCTS = {
    iron_milldrivebelt = { name = "Železni pogonski jermen za mline", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni pogonski jermen za mline za mlinarje." },
    bronze_milldrivebelt = { name = "Bronast pogonski jermen za mline", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast pogonski jermen za mline za mlinarje." },
    silver_milldrivebelt = { name = "Srebrn pogonski jermen za mline", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn pogonski jermen za mline za mlinarje." },
    gilded_milldrivebelt = { name = "Pozlačen pogonski jermen za mline", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen pogonski jermen za mline za mlinarje." },
    jewel_set_milldrivebelt = { name = "Draguljast pogonski jermen za mline", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast pogonski jermen za mline za mlinarje." },
    royal_sovereign_milldrivebelt = { name = "Kraljevski suveren pogonski jermen za mline", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren pogonski jermen za mline z biseri za krono." },
}
local BUILDINGS = {
    milldrivebelt_workshop = { name = "Milldrivebelt delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    milldrivebelt_house = { name = "Milldrivebelt hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_milldrivebelt_atelier = { name = "Mojstrski milldrivebelt atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_milldrivebelt_palace = { name = "Suverena milldrivebelt palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillDriveBeltMaker.ironStock=12; MillDriveBeltMaker.bronzeStock=10; MillDriveBeltMaker.woodStock=14; MillDriveBeltMaker.leatherStock=14; MillDriveBeltMaker.silverStock=8; MillDriveBeltMaker.goldStock=6; MillDriveBeltMaker.jewelStock=4; MillDriveBeltMaker.pearlStock=4
MillDriveBeltMaker.productStock = {}; MillDriveBeltMaker.buildings = {}; MillDriveBeltMaker.maker = nil; MillDriveBeltMaker.activeMaking = {}; MillDriveBeltMaker.totalProducts = 0; MillDriveBeltMaker.dayTimer = 0
function MillDriveBeltMaker.init() MillDriveBeltMaker.ironStock=12; MillDriveBeltMaker.bronzeStock=10; MillDriveBeltMaker.woodStock=14; MillDriveBeltMaker.leatherStock=14; MillDriveBeltMaker.silverStock=8; MillDriveBeltMaker.goldStock=6; MillDriveBeltMaker.jewelStock=4; MillDriveBeltMaker.pearlStock=4; MillDriveBeltMaker.productStock={}; MillDriveBeltMaker.buildings={}; MillDriveBeltMaker.maker=nil; MillDriveBeltMaker.activeMaking={}; MillDriveBeltMaker.totalProducts=0; MillDriveBeltMaker.dayTimer=0; print("[MillDriveBeltMaker] Royal Mill Drive Belt Maker System initialized (6 products, 4 buildings)") end
function MillDriveBeltMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillDriveBeltMaker.maker={name=n or ("Jermensar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Jermensar najet: %s (spretnost: %d)",MillDriveBeltMaker.maker.name,s),"success") end; return true end
function MillDriveBeltMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillDriveBeltMaker.build(id) local ok,e=MillDriveBeltMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillDriveBeltMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillDriveBeltMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillDriveBeltMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillDriveBeltMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillDriveBeltMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillDriveBeltMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillDriveBeltMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillDriveBeltMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillDriveBeltMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillDriveBeltMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillDriveBeltMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillDriveBeltMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillDriveBeltMaker.buildings==0 then return false,"Potrebna jermenska delavnica" end; if not MillDriveBeltMaker.maker then return false,"Potreben jermensar" end; return true end
function MillDriveBeltMaker.make(pt,qty) qty=qty or 1; local ok,e=MillDriveBeltMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillDriveBeltMaker.ironStock=MillDriveBeltMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillDriveBeltMaker.bronzeStock=MillDriveBeltMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillDriveBeltMaker.woodStock=MillDriveBeltMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillDriveBeltMaker.leatherStock=MillDriveBeltMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillDriveBeltMaker.silverStock=MillDriveBeltMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillDriveBeltMaker.goldStock=MillDriveBeltMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillDriveBeltMaker.jewelStock=MillDriveBeltMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillDriveBeltMaker.pearlStock=MillDriveBeltMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillDriveBeltMaker.maker then t=math.max(1,t-math.floor(MillDriveBeltMaker.maker.skill/13)) end; table.insert(MillDriveBeltMaker.activeMaking,{id="milldrivebelt_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillDriveBeltMaker.completeMaking(m) local q=1.0+(MillDriveBeltMaker.getQualityBonus()/100); if MillDriveBeltMaker.maker then q=q+(MillDriveBeltMaker.maker.skill/140) end; q=math.min(2.5,q); MillDriveBeltMaker.productStock[m.productType]=(MillDriveBeltMaker.productStock[m.productType] or 0)+m.quantity; MillDriveBeltMaker.totalProducts=MillDriveBeltMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillDriveBeltMaker.maker then MillDriveBeltMaker.maker.itemsMade=MillDriveBeltMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillDriveBeltMaker.maker.skill=math.min(100,MillDriveBeltMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Jermen izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"milldrivebelt.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillDriveBeltMaker.update(dt) if not _G.state then return end; MillDriveBeltMaker.dayTimer=MillDriveBeltMaker.dayTimer+dt; if MillDriveBeltMaker.dayTimer>=30 then MillDriveBeltMaker.dayTimer=0; for i=#MillDriveBeltMaker.activeMaking,1,-1 do local m=MillDriveBeltMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillDriveBeltMaker.completeMaking(m); table.remove(MillDriveBeltMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillDriveBeltMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillDriveBeltMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillDriveBeltMaker.getStats() return {ironStock=MillDriveBeltMaker.ironStock,bronzeStock=MillDriveBeltMaker.bronzeStock,woodStock=MillDriveBeltMaker.woodStock,leatherStock=MillDriveBeltMaker.leatherStock,silverStock=MillDriveBeltMaker.silverStock,goldStock=MillDriveBeltMaker.goldStock,jewelStock=MillDriveBeltMaker.jewelStock,pearlStock=MillDriveBeltMaker.pearlStock,productStock=MillDriveBeltMaker.productStock,numBuildings=#MillDriveBeltMaker.buildings,hasMaker=MillDriveBeltMaker.maker~=nil,makerName=MillDriveBeltMaker.maker and MillDriveBeltMaker.maker.name or "—",makerSkill=MillDriveBeltMaker.maker and MillDriveBeltMaker.maker.skill or 0,activeMaking=#MillDriveBeltMaker.activeMaking,totalProducts=MillDriveBeltMaker.totalProducts} end
return MillDriveBeltMaker
