local TheaterMaskMaker = {}
local PRODUCTS = {
    plain_papier_mask = { name = "Preprosta papirnata maska", woodCost = 1, paintCost = 1, time = 2, cost = 30, artistry = 18, happiness = 2, description = "Preprosta papirnata maska za gledališče." },
    painted_linen_mask = { name = "Poslikana lanena maska", woodCost = 1, linenCost = 1, paintCost = 2, time = 5, cost = 100, artistry = 35, happiness = 2, prestige = 2, description = "Poslikana lanena maska za trgovce." },
    leather_comedy_mask = { name = "Usnjena komedija maska", leatherCost = 2, linenCost = 1, paintCost = 2, time = 8, cost = 280, artistry = 50, happiness = 3, prestige = 6, description = "Usnjena komedija maska za plemiče." },
    silver_leaf_tragedy_mask = { name = "Srebrnolistna tragedija maska", leatherCost = 2, silverCost = 1, linenCost = 1, paintCost = 2, time = 12, cost = 680, artistry = 65, happiness = 4, prestige = 14, description = "Srebrnolistna tragedija maska za visoke plemiče." },
    gold_trimmed_heroic_mask = { name = "Zlatookrasni herojska maska", leatherCost = 2, goldCost = 1, silverCost = 1, linenCost = 1, paintCost = 2, jewelCost = 1, time = 16, cost = 1500, artistry = 78, happiness = 6, prestige = 27, description = "Herojska maska z zlato obrobo za visoko plemstvo." },
    royal_grand_ceremonial_mask = { name = "Kraljevski veliki slovesnostna maska", leatherCost = 3, goldCost = 2, silverCost = 2, linenCost = 1, paintCost = 2, jewelCost = 2, pearlCost = 2, time = 23, cost = 3500, artistry = 92, happiness = 12, prestige = 58, description = "Velika kraljevska slovesnostna maska z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    mask_workshop = { name = "Maskarska delavnica", cost = { gold = 220, wood = 100, stone = 100, paint = 6, leather = 6 }, upkeep = 5, qualityBonus = 5 },
    mask_loft = { name = "Maskarska podstrešje", cost = { gold = 800, wood = 240, stone = 220, silver = 6, linen = 6 }, upkeep = 18, qualityBonus = 18 },
    master_mask_atelier = { name = "Mojstrski maskarski atelje", cost = { gold = 2300, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 52, qualityBonus = 30 },
    royal_mask_palace = { name = "Kraljevska maskarska palača", cost = { gold = 9500, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 50 },
}
TheaterMaskMaker.woodStock = 12; TheaterMaskMaker.linenStock = 12; TheaterMaskMaker.leatherStock = 12; TheaterMaskMaker.paintStock = 14; TheaterMaskMaker.silverStock = 6; TheaterMaskMaker.goldStock = 6; TheaterMaskMaker.jewelStock = 4; TheaterMaskMaker.pearlStock = 4
TheaterMaskMaker.productStock = {}; TheaterMaskMaker.buildings = {}; TheaterMaskMaker.maker = nil; TheaterMaskMaker.activeMaking = {}; TheaterMaskMaker.totalProducts = 0; TheaterMaskMaker.dayTimer = 0
function TheaterMaskMaker.init() TheaterMaskMaker.woodStock=12; TheaterMaskMaker.linenStock=12; TheaterMaskMaker.leatherStock=12; TheaterMaskMaker.paintStock=14; TheaterMaskMaker.silverStock=6; TheaterMaskMaker.goldStock=6; TheaterMaskMaker.jewelStock=4; TheaterMaskMaker.pearlStock=4; TheaterMaskMaker.productStock={}; TheaterMaskMaker.buildings={}; TheaterMaskMaker.maker=nil; TheaterMaskMaker.activeMaking={}; TheaterMaskMaker.totalProducts=0; TheaterMaskMaker.dayTimer=0; print("[TheaterMaskMaker] Royal Theater Mask Maker System initialized (6 products, 4 buildings)") end
function TheaterMaskMaker.hireMaker(n,s) s=s or math.random(55,90); local c=480+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TheaterMaskMaker.maker={name=n or ("Maskar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Maskar najet: %s (spretnost: %d)",TheaterMaskMaker.maker.name,s),"success") end; return true end
function TheaterMaskMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TheaterMaskMaker.build(id) local ok,e=TheaterMaskMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TheaterMaskMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TheaterMaskMaker.getQualityBonus() local b=0; for _,bd in ipairs(TheaterMaskMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TheaterMaskMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and TheaterMaskMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.linenCost and TheaterMaskMaker.linenStock<(d.linenCost or 0) then return false,"Premalo lanu" end; if d.leatherCost and TheaterMaskMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.paintCost and TheaterMaskMaker.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.silverCost and TheaterMaskMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and TheaterMaskMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and TheaterMaskMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and TheaterMaskMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #TheaterMaskMaker.buildings==0 then return false,"Potrebna maskarska delavnica" end; if not TheaterMaskMaker.maker then return false,"Potreben maskar" end; return true end
function TheaterMaskMaker.make(pt,qty) qty=qty or 1; local ok,e=TheaterMaskMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then TheaterMaskMaker.woodStock=TheaterMaskMaker.woodStock-d.woodCost*qty end; if d.linenCost then TheaterMaskMaker.linenStock=TheaterMaskMaker.linenStock-d.linenCost*qty end; if d.leatherCost then TheaterMaskMaker.leatherStock=TheaterMaskMaker.leatherStock-d.leatherCost*qty end; if d.paintCost then TheaterMaskMaker.paintStock=TheaterMaskMaker.paintStock-d.paintCost*qty end; if d.silverCost then TheaterMaskMaker.silverStock=TheaterMaskMaker.silverStock-d.silverCost*qty end; if d.goldCost then TheaterMaskMaker.goldStock=TheaterMaskMaker.goldStock-d.goldCost*qty end; if d.jewelCost then TheaterMaskMaker.jewelStock=TheaterMaskMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then TheaterMaskMaker.pearlStock=TheaterMaskMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if TheaterMaskMaker.maker then t=math.max(1,t-math.floor(TheaterMaskMaker.maker.skill/13)) end; table.insert(TheaterMaskMaker.activeMaking,{id="theatermask_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,artistry=d.artistry or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TheaterMaskMaker.completeMaking(m) local q=1.0+(TheaterMaskMaker.getQualityBonus()/100); if TheaterMaskMaker.maker then q=q+(TheaterMaskMaker.maker.skill/150) end; q=math.min(2.4,q); TheaterMaskMaker.productStock[m.productType]=(TheaterMaskMaker.productStock[m.productType] or 0)+m.quantity; TheaterMaskMaker.totalProducts=TheaterMaskMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if TheaterMaskMaker.maker then TheaterMaskMaker.maker.itemsMade=TheaterMaskMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then TheaterMaskMaker.maker.skill=math.min(100,TheaterMaskMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Maska izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"theatermask.completed",{productName=m.productName,artistry=m.artistry,prestige=m.prestige,happiness=m.happiness}) end end
function TheaterMaskMaker.update(dt) if not _G.state then return end; TheaterMaskMaker.dayTimer=TheaterMaskMaker.dayTimer+dt; if TheaterMaskMaker.dayTimer>=30 then TheaterMaskMaker.dayTimer=0; for i=#TheaterMaskMaker.activeMaking,1,-1 do local m=TheaterMaskMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TheaterMaskMaker.completeMaking(m); table.remove(TheaterMaskMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TheaterMaskMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TheaterMaskMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TheaterMaskMaker.getStats() return {woodStock=TheaterMaskMaker.woodStock,linenStock=TheaterMaskMaker.linenStock,leatherStock=TheaterMaskMaker.leatherStock,paintStock=TheaterMaskMaker.paintStock,silverStock=TheaterMaskMaker.silverStock,goldStock=TheaterMaskMaker.goldStock,jewelStock=TheaterMaskMaker.jewelStock,pearlStock=TheaterMaskMaker.pearlStock,productStock=TheaterMaskMaker.productStock,numBuildings=#TheaterMaskMaker.buildings,hasMaker=TheaterMaskMaker.maker~=nil,makerName=TheaterMaskMaker.maker and TheaterMaskMaker.maker.name or "—",makerSkill=TheaterMaskMaker.maker and TheaterMaskMaker.maker.skill or 0,activeMaking=#TheaterMaskMaker.activeMaking,totalProducts=TheaterMaskMaker.totalProducts} end
return TheaterMaskMaker
