local PendulumRodMaker = {}
local PRODUCTS = {
    iron_pendulumrod = { name = "Železni nihajna palica", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni nihajna palica za ure." },
    bronze_pendulumrod = { name = "Bronast nihajna palica", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast nihajna palica za ure." },
    silver_pendulumrod = { name = "Srebrn nihajna palica", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn nihajna palica za ure." },
    gilded_pendulumrod = { name = "Pozlačen nihajna palica", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen nihajna palica za ure." },
    jewel_set_pendulumrod = { name = "Draguljast nihajna palica", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast nihajna palica za ure." },
    royal_sovereign_pendulumrod = { name = "Kraljevski suveren nihajna palica", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren nihajna palica z biseri za krono." },
}
local BUILDINGS = {
    pendulumrod_workshop = { name = "Pendulumrod delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    pendulumrod_house = { name = "Pendulumrod hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_pendulumrod_atelier = { name = "Mojstrski pendulumrod atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_pendulumrod_palace = { name = "Suverena pendulumrod palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
PendulumRodMaker.ironStock = 14; PendulumRodMaker.bronzeStock = 12; PendulumRodMaker.woodStock = 14; PendulumRodMaker.leatherStock = 8; PendulumRodMaker.silverStock = 8; PendulumRodMaker.goldStock = 6; PendulumRodMaker.jewelStock = 4; PendulumRodMaker.pearlStock = 4
PendulumRodMaker.productStock = {}; PendulumRodMaker.buildings = {}; PendulumRodMaker.maker = nil; PendulumRodMaker.activeMaking = {}; PendulumRodMaker.totalProducts = 0; PendulumRodMaker.dayTimer = 0
function PendulumRodMaker.init() PendulumRodMaker.ironStock=14; PendulumRodMaker.bronzeStock=12; PendulumRodMaker.woodStock=14; PendulumRodMaker.leatherStock=8; PendulumRodMaker.silverStock=8; PendulumRodMaker.goldStock=6; PendulumRodMaker.jewelStock=4; PendulumRodMaker.pearlStock=4; PendulumRodMaker.productStock={}; PendulumRodMaker.buildings={}; PendulumRodMaker.maker=nil; PendulumRodMaker.activeMaking={}; PendulumRodMaker.totalProducts=0; PendulumRodMaker.dayTimer=0; print("[PendulumRodMaker] Royal Pendulum Rod Maker System initialized (6 products, 4 buildings)") end
function PendulumRodMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PendulumRodMaker.maker={name=n or ("Nihajec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Nihajec najet: %s (spretnost: %d)",PendulumRodMaker.maker.name,s),"success") end; return true end
function PendulumRodMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PendulumRodMaker.build(id) local ok,e=PendulumRodMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PendulumRodMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PendulumRodMaker.getQualityBonus() local b=0; for _,bd in ipairs(PendulumRodMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PendulumRodMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PendulumRodMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and PendulumRodMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and PendulumRodMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PendulumRodMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PendulumRodMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PendulumRodMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PendulumRodMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PendulumRodMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PendulumRodMaker.buildings==0 then return false,"Potrebna nihajna delavnica" end; if not PendulumRodMaker.maker then return false,"Potreben nihajec" end; return true end
function PendulumRodMaker.make(pt,qty) qty=qty or 1; local ok,e=PendulumRodMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PendulumRodMaker.ironStock=PendulumRodMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then PendulumRodMaker.bronzeStock=PendulumRodMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then PendulumRodMaker.woodStock=PendulumRodMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PendulumRodMaker.leatherStock=PendulumRodMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then PendulumRodMaker.silverStock=PendulumRodMaker.silverStock-d.silverCost*qty end; if d.goldCost then PendulumRodMaker.goldStock=PendulumRodMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PendulumRodMaker.jewelStock=PendulumRodMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PendulumRodMaker.pearlStock=PendulumRodMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PendulumRodMaker.maker then t=math.max(1,t-math.floor(PendulumRodMaker.maker.skill/13)) end; table.insert(PendulumRodMaker.activeMaking,{id="pendulumrod_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PendulumRodMaker.completeMaking(m) local q=1.0+(PendulumRodMaker.getQualityBonus()/100); if PendulumRodMaker.maker then q=q+(PendulumRodMaker.maker.skill/140) end; q=math.min(2.5,q); PendulumRodMaker.productStock[m.productType]=(PendulumRodMaker.productStock[m.productType] or 0)+m.quantity; PendulumRodMaker.totalProducts=PendulumRodMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PendulumRodMaker.maker then PendulumRodMaker.maker.itemsMade=PendulumRodMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PendulumRodMaker.maker.skill=math.min(100,PendulumRodMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Palica izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"pendulumrod.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function PendulumRodMaker.update(dt) if not _G.state then return end; PendulumRodMaker.dayTimer=PendulumRodMaker.dayTimer+dt; if PendulumRodMaker.dayTimer>=30 then PendulumRodMaker.dayTimer=0; for i=#PendulumRodMaker.activeMaking,1,-1 do local m=PendulumRodMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PendulumRodMaker.completeMaking(m); table.remove(PendulumRodMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PendulumRodMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PendulumRodMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PendulumRodMaker.getStats() return {ironStock=PendulumRodMaker.ironStock,bronzeStock=PendulumRodMaker.bronzeStock,woodStock=PendulumRodMaker.woodStock,leatherStock=PendulumRodMaker.leatherStock,silverStock=PendulumRodMaker.silverStock,goldStock=PendulumRodMaker.goldStock,jewelStock=PendulumRodMaker.jewelStock,pearlStock=PendulumRodMaker.pearlStock,productStock=PendulumRodMaker.productStock,numBuildings=#PendulumRodMaker.buildings,hasMaker=PendulumRodMaker.maker~=nil,makerName=PendulumRodMaker.maker and PendulumRodMaker.maker.name or "—",makerSkill=PendulumRodMaker.maker and PendulumRodMaker.maker.skill or 0,activeMaking=#PendulumRodMaker.activeMaking,totalProducts=PendulumRodMaker.totalProducts} end
return PendulumRodMaker
