local HookMaker = {}
local PRODUCTS = {
    simple_iron_hook = { name = "Preprost železen kljuk", ironCost = 2, time = 2, cost = 40, happiness = 1, description = "Preprost železen kljuk za obešanje." },
    brass_hook = { name = "Medeninast kljuk", brassCost = 2, ironCost = 1, time = 4, cost = 110, happiness = 1, prestige = 2, description = "Medeninast kljuk za trgovce." },
    silver_hook = { name = "Srebrn kljuk", silverCost = 2, brassCost = 1, ironCost = 1, time = 7, cost = 280, happiness = 2, prestige = 6, description = "Srebrn kljuk za plemiče." },
    gold_trimmed_hook = { name = "Zlatookrasni kljuk", goldCost = 1, silverCost = 1, brassCost = 1, ironCost = 1, time = 10, cost = 680, happiness = 3, prestige = 14, description = "Zlatookrasni kljuk za visoke plemiče." },
    jewel_set_hook = { name = "Draguljasta kljuk", goldCost = 1, silverCost = 1, brassCost = 1, ironCost = 1, jewelCost = 1, time = 14, cost = 1500, happiness = 5, prestige = 27, description = "Kljuk z draguljem za visoko plemstvo." },
    royal_grand_hook = { name = "Kraljevski veliki kljuk", goldCost = 2, silverCost = 2, brassCost = 1, ironCost = 1, jewelCost = 2, pearlCost = 2, time = 21, cost = 3500, happiness = 12, prestige = 58, description = "Veliki kraljevski kljuk z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    hook_workshop = { name = "Kljukarska delavnica", cost = { gold = 240, wood = 100, stone = 120, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    metalwork_loft = { name = "Kovinska podstrešje", cost = { gold = 880, wood = 240, stone = 240, silver = 6, brass = 6 }, upkeep = 20, qualityBonus = 18 },
    master_hook_atelier = { name = "Mojstrski kljukarski atelje", cost = { gold = 2500, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 58, qualityBonus = 30 },
    royal_metalwork_palace = { name = "Kraljevska kovinska palača", cost = { gold = 10500, wood = 580, stone = 760, gold = 65, jewel = 16 }, upkeep = 210, qualityBonus = 55, prestigeBonus = 50 },
}
HookMaker.ironStock = 14; HookMaker.brassStock = 12; HookMaker.silverStock = 8; HookMaker.goldStock = 6; HookMaker.jewelStock = 4; HookMaker.pearlStock = 4
HookMaker.productStock = {}; HookMaker.buildings = {}; HookMaker.maker = nil; HookMaker.activeMaking = {}; HookMaker.totalProducts = 0; HookMaker.dayTimer = 0
function HookMaker.init() HookMaker.ironStock=14; HookMaker.brassStock=12; HookMaker.silverStock=8; HookMaker.goldStock=6; HookMaker.jewelStock=4; HookMaker.pearlStock=4; HookMaker.productStock={}; HookMaker.buildings={}; HookMaker.maker=nil; HookMaker.activeMaking={}; HookMaker.totalProducts=0; HookMaker.dayTimer=0; print("[HookMaker] Royal Hook Maker System initialized (6 products, 4 buildings)") end
function HookMaker.hireMaker(n,s) s=s or math.random(55,90); local c=500+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HookMaker.maker={name=n or ("Kljukar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kljukar najet: %s (spretnost: %d)",HookMaker.maker.name,s),"success") end; return true end
function HookMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HookMaker.build(id) local ok,e=HookMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HookMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HookMaker.getQualityBonus() local b=0; for _,bd in ipairs(HookMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HookMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and HookMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.brassCost and HookMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and HookMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HookMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HookMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HookMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HookMaker.buildings==0 then return false,"Potrebna kljukarska delavnica" end; if not HookMaker.maker then return false,"Potreben kljukar" end; return true end
function HookMaker.make(pt,qty) qty=qty or 1; local ok,e=HookMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then HookMaker.ironStock=HookMaker.ironStock-d.ironCost*qty end; if d.brassCost then HookMaker.brassStock=HookMaker.brassStock-d.brassCost*qty end; if d.silverCost then HookMaker.silverStock=HookMaker.silverStock-d.silverCost*qty end; if d.goldCost then HookMaker.goldStock=HookMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HookMaker.jewelStock=HookMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HookMaker.pearlStock=HookMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HookMaker.maker then t=math.max(1,t-math.floor(HookMaker.maker.skill/14)) end; table.insert(HookMaker.activeMaking,{id="hook_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HookMaker.completeMaking(m) local q=1.0+(HookMaker.getQualityBonus()/100); if HookMaker.maker then q=q+(HookMaker.maker.skill/140) end; q=math.min(2.5,q); HookMaker.productStock[m.productType]=(HookMaker.productStock[m.productType] or 0)+m.quantity; HookMaker.totalProducts=HookMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HookMaker.maker then HookMaker.maker.itemsMade=HookMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then HookMaker.maker.skill=math.min(100,HookMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kljuk izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"hook.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function HookMaker.update(dt) if not _G.state then return end; HookMaker.dayTimer=HookMaker.dayTimer+dt; if HookMaker.dayTimer>=30 then HookMaker.dayTimer=0; for i=#HookMaker.activeMaking,1,-1 do local m=HookMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HookMaker.completeMaking(m); table.remove(HookMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HookMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HookMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HookMaker.getStats() return {ironStock=HookMaker.ironStock,brassStock=HookMaker.brassStock,silverStock=HookMaker.silverStock,goldStock=HookMaker.goldStock,jewelStock=HookMaker.jewelStock,pearlStock=HookMaker.pearlStock,productStock=HookMaker.productStock,numBuildings=#HookMaker.buildings,hasMaker=HookMaker.maker~=nil,makerName=HookMaker.maker and HookMaker.maker.name or "—",makerSkill=HookMaker.maker and HookMaker.maker.skill or 0,activeMaking=#HookMaker.activeMaking,totalProducts=HookMaker.totalProducts} end
return HookMaker
