local GrainHopperLevelSensorMaker = {}
local PRODUCTS = {
    iron_grainhopperlevelsensor = { name = "Železni senzor nivoja žita", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni senzor nivoja žita za mlinarje." },
    bronze_grainhopperlevelsensor = { name = "Bronast senzor nivoja žita", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast senzor nivoja žita za mlinarje." },
    silver_grainhopperlevelsensor = { name = "Srebrn senzor nivoja žita", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn senzor nivoja žita za mlinarje." },
    gilded_grainhopperlevelsensor = { name = "Pozlačen senzor nivoja žita", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen senzor nivoja žita za mlinarje." },
    jewel_set_grainhopperlevelsensor = { name = "Draguljast senzor nivoja žita", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast senzor nivoja žita za mlinarje." },
    royal_sovereign_grainhopperlevelsensor = { name = "Kraljevski suveren senzor nivoja žita", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren senzor nivoja žita z biseri za krono." },
}
local BUILDINGS = {
    grainhopperlevelsensor_workshop = { name = "Grainhopperlevelsensor delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    grainhopperlevelsensor_house = { name = "Grainhopperlevelsensor hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_grainhopperlevelsensor_atelier = { name = "Mojstrski grainhopperlevelsensor atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_grainhopperlevelsensor_palace = { name = "Suverena grainhopperlevelsensor palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GrainHopperLevelSensorMaker.ironStock=14; GrainHopperLevelSensorMaker.bronzeStock=12; GrainHopperLevelSensorMaker.woodStock=12; GrainHopperLevelSensorMaker.leatherStock=8; GrainHopperLevelSensorMaker.silverStock=8; GrainHopperLevelSensorMaker.goldStock=6; GrainHopperLevelSensorMaker.jewelStock=4; GrainHopperLevelSensorMaker.pearlStock=4
GrainHopperLevelSensorMaker.productStock = {}; GrainHopperLevelSensorMaker.buildings = {}; GrainHopperLevelSensorMaker.maker = nil; GrainHopperLevelSensorMaker.activeMaking = {}; GrainHopperLevelSensorMaker.totalProducts = 0; GrainHopperLevelSensorMaker.dayTimer = 0
function GrainHopperLevelSensorMaker.init() GrainHopperLevelSensorMaker.ironStock=14; GrainHopperLevelSensorMaker.bronzeStock=12; GrainHopperLevelSensorMaker.woodStock=12; GrainHopperLevelSensorMaker.leatherStock=8; GrainHopperLevelSensorMaker.silverStock=8; GrainHopperLevelSensorMaker.goldStock=6; GrainHopperLevelSensorMaker.jewelStock=4; GrainHopperLevelSensorMaker.pearlStock=4; GrainHopperLevelSensorMaker.productStock={}; GrainHopperLevelSensorMaker.buildings={}; GrainHopperLevelSensorMaker.maker=nil; GrainHopperLevelSensorMaker.activeMaking={}; GrainHopperLevelSensorMaker.totalProducts=0; GrainHopperLevelSensorMaker.dayTimer=0; print("[GrainHopperLevelSensorMaker] Royal Grain Hopper Level Sensor Maker System initialized (6 products, 4 buildings)") end
function GrainHopperLevelSensorMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GrainHopperLevelSensorMaker.maker={name=n or ("Senzornik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Senzornik najet: %s (spretnost: %d)",GrainHopperLevelSensorMaker.maker.name,s),"success") end; return true end
function GrainHopperLevelSensorMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GrainHopperLevelSensorMaker.build(id) local ok,e=GrainHopperLevelSensorMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GrainHopperLevelSensorMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GrainHopperLevelSensorMaker.getQualityBonus() local b=0; for _,bd in ipairs(GrainHopperLevelSensorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GrainHopperLevelSensorMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GrainHopperLevelSensorMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GrainHopperLevelSensorMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GrainHopperLevelSensorMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GrainHopperLevelSensorMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GrainHopperLevelSensorMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GrainHopperLevelSensorMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GrainHopperLevelSensorMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GrainHopperLevelSensorMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GrainHopperLevelSensorMaker.buildings==0 then return false,"Potrebna senzorska delavnica" end; if not GrainHopperLevelSensorMaker.maker then return false,"Potreben senzornik" end; return true end
function GrainHopperLevelSensorMaker.make(pt,qty) qty=qty or 1; local ok,e=GrainHopperLevelSensorMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GrainHopperLevelSensorMaker.ironStock=GrainHopperLevelSensorMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GrainHopperLevelSensorMaker.bronzeStock=GrainHopperLevelSensorMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GrainHopperLevelSensorMaker.woodStock=GrainHopperLevelSensorMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GrainHopperLevelSensorMaker.leatherStock=GrainHopperLevelSensorMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GrainHopperLevelSensorMaker.silverStock=GrainHopperLevelSensorMaker.silverStock-d.silverCost*qty end; if d.goldCost then GrainHopperLevelSensorMaker.goldStock=GrainHopperLevelSensorMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GrainHopperLevelSensorMaker.jewelStock=GrainHopperLevelSensorMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GrainHopperLevelSensorMaker.pearlStock=GrainHopperLevelSensorMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GrainHopperLevelSensorMaker.maker then t=math.max(1,t-math.floor(GrainHopperLevelSensorMaker.maker.skill/13)) end; table.insert(GrainHopperLevelSensorMaker.activeMaking,{id="grainhopperlevelsensor_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GrainHopperLevelSensorMaker.completeMaking(m) local q=1.0+(GrainHopperLevelSensorMaker.getQualityBonus()/100); if GrainHopperLevelSensorMaker.maker then q=q+(GrainHopperLevelSensorMaker.maker.skill/140) end; q=math.min(2.5,q); GrainHopperLevelSensorMaker.productStock[m.productType]=(GrainHopperLevelSensorMaker.productStock[m.productType] or 0)+m.quantity; GrainHopperLevelSensorMaker.totalProducts=GrainHopperLevelSensorMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GrainHopperLevelSensorMaker.maker then GrainHopperLevelSensorMaker.maker.itemsMade=GrainHopperLevelSensorMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GrainHopperLevelSensorMaker.maker.skill=math.min(100,GrainHopperLevelSensorMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Senzor izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"grainhopperlevelsensor.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GrainHopperLevelSensorMaker.update(dt) if not _G.state then return end; GrainHopperLevelSensorMaker.dayTimer=GrainHopperLevelSensorMaker.dayTimer+dt; if GrainHopperLevelSensorMaker.dayTimer>=30 then GrainHopperLevelSensorMaker.dayTimer=0; for i=#GrainHopperLevelSensorMaker.activeMaking,1,-1 do local m=GrainHopperLevelSensorMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GrainHopperLevelSensorMaker.completeMaking(m); table.remove(GrainHopperLevelSensorMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GrainHopperLevelSensorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GrainHopperLevelSensorMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GrainHopperLevelSensorMaker.getStats() return {ironStock=GrainHopperLevelSensorMaker.ironStock,bronzeStock=GrainHopperLevelSensorMaker.bronzeStock,woodStock=GrainHopperLevelSensorMaker.woodStock,leatherStock=GrainHopperLevelSensorMaker.leatherStock,silverStock=GrainHopperLevelSensorMaker.silverStock,goldStock=GrainHopperLevelSensorMaker.goldStock,jewelStock=GrainHopperLevelSensorMaker.jewelStock,pearlStock=GrainHopperLevelSensorMaker.pearlStock,productStock=GrainHopperLevelSensorMaker.productStock,numBuildings=#GrainHopperLevelSensorMaker.buildings,hasMaker=GrainHopperLevelSensorMaker.maker~=nil,makerName=GrainHopperLevelSensorMaker.maker and GrainHopperLevelSensorMaker.maker.name or "—",makerSkill=GrainHopperLevelSensorMaker.maker and GrainHopperLevelSensorMaker.maker.skill or 0,activeMaking=#GrainHopperLevelSensorMaker.activeMaking,totalProducts=GrainHopperLevelSensorMaker.totalProducts} end
return GrainHopperLevelSensorMaker
