local CoreVarnishBrushMaker = {}
local PRODUCTS = {
    iron_corevarnishbrush = { name = "Železni čopič za lak jedrc", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni čopič za lak jedrc za livarje." },
    bronze_corevarnishbrush = { name = "Bronast čopič za lak jedrc", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast čopič za lak jedrc za livarje." },
    silver_corevarnishbrush = { name = "Srebrn čopič za lak jedrc", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn čopič za lak jedrc za livarje." },
    gilded_corevarnishbrush = { name = "Pozlačen čopič za lak jedrc", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen čopič za lak jedrc za livarje." },
    jewel_set_corevarnishbrush = { name = "Draguljast čopič za lak jedrc", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast čopič za lak jedrc za livarje." },
    royal_sovereign_corevarnishbrush = { name = "Kraljevski suveren čopič za lak jedrc", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren čopič za lak jedrc z biseri za krono." },
}
local BUILDINGS = {
    corevarnishbrush_workshop = { name = "Corevarnishbrush delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    corevarnishbrush_house = { name = "Corevarnishbrush hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_corevarnishbrush_atelier = { name = "Mojstrski corevarnishbrush atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_corevarnishbrush_palace = { name = "Suverena corevarnishbrush palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
CoreVarnishBrushMaker.ironStock=10; CoreVarnishBrushMaker.bronzeStock=8; CoreVarnishBrushMaker.woodStock=14; CoreVarnishBrushMaker.leatherStock=14; CoreVarnishBrushMaker.silverStock=8; CoreVarnishBrushMaker.goldStock=6; CoreVarnishBrushMaker.jewelStock=4; CoreVarnishBrushMaker.pearlStock=4
CoreVarnishBrushMaker.productStock = {}; CoreVarnishBrushMaker.buildings = {}; CoreVarnishBrushMaker.maker = nil; CoreVarnishBrushMaker.activeMaking = {}; CoreVarnishBrushMaker.totalProducts = 0; CoreVarnishBrushMaker.dayTimer = 0
function CoreVarnishBrushMaker.init() CoreVarnishBrushMaker.ironStock=10; CoreVarnishBrushMaker.bronzeStock=8; CoreVarnishBrushMaker.woodStock=14; CoreVarnishBrushMaker.leatherStock=14; CoreVarnishBrushMaker.silverStock=8; CoreVarnishBrushMaker.goldStock=6; CoreVarnishBrushMaker.jewelStock=4; CoreVarnishBrushMaker.pearlStock=4; CoreVarnishBrushMaker.productStock={}; CoreVarnishBrushMaker.buildings={}; CoreVarnishBrushMaker.maker=nil; CoreVarnishBrushMaker.activeMaking={}; CoreVarnishBrushMaker.totalProducts=0; CoreVarnishBrushMaker.dayTimer=0; print("[CoreVarnishBrushMaker] Royal Core Varnish Brush Maker System initialized (6 products, 4 buildings)") end
function CoreVarnishBrushMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CoreVarnishBrushMaker.maker={name=n or ("Čopičar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Čopičar najet: %s (spretnost: %d)",CoreVarnishBrushMaker.maker.name,s),"success") end; return true end
function CoreVarnishBrushMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CoreVarnishBrushMaker.build(id) local ok,e=CoreVarnishBrushMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CoreVarnishBrushMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CoreVarnishBrushMaker.getQualityBonus() local b=0; for _,bd in ipairs(CoreVarnishBrushMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CoreVarnishBrushMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CoreVarnishBrushMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CoreVarnishBrushMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CoreVarnishBrushMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CoreVarnishBrushMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CoreVarnishBrushMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CoreVarnishBrushMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CoreVarnishBrushMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CoreVarnishBrushMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CoreVarnishBrushMaker.buildings==0 then return false,"Potrebna čopična delavnica" end; if not CoreVarnishBrushMaker.maker then return false,"Potreben copicar" end; return true end
function CoreVarnishBrushMaker.make(pt,qty) qty=qty or 1; local ok,e=CoreVarnishBrushMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CoreVarnishBrushMaker.ironStock=CoreVarnishBrushMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CoreVarnishBrushMaker.bronzeStock=CoreVarnishBrushMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CoreVarnishBrushMaker.woodStock=CoreVarnishBrushMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CoreVarnishBrushMaker.leatherStock=CoreVarnishBrushMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CoreVarnishBrushMaker.silverStock=CoreVarnishBrushMaker.silverStock-d.silverCost*qty end; if d.goldCost then CoreVarnishBrushMaker.goldStock=CoreVarnishBrushMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CoreVarnishBrushMaker.jewelStock=CoreVarnishBrushMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CoreVarnishBrushMaker.pearlStock=CoreVarnishBrushMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CoreVarnishBrushMaker.maker then t=math.max(1,t-math.floor(CoreVarnishBrushMaker.maker.skill/13)) end; table.insert(CoreVarnishBrushMaker.activeMaking,{id="corevarnishbrush_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CoreVarnishBrushMaker.completeMaking(m) local q=1.0+(CoreVarnishBrushMaker.getQualityBonus()/100); if CoreVarnishBrushMaker.maker then q=q+(CoreVarnishBrushMaker.maker.skill/140) end; q=math.min(2.5,q); CoreVarnishBrushMaker.productStock[m.productType]=(CoreVarnishBrushMaker.productStock[m.productType] or 0)+m.quantity; CoreVarnishBrushMaker.totalProducts=CoreVarnishBrushMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CoreVarnishBrushMaker.maker then CoreVarnishBrushMaker.maker.itemsMade=CoreVarnishBrushMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CoreVarnishBrushMaker.maker.skill=math.min(100,CoreVarnishBrushMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Čopič izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"corevarnishbrush.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CoreVarnishBrushMaker.update(dt) if not _G.state then return end; CoreVarnishBrushMaker.dayTimer=CoreVarnishBrushMaker.dayTimer+dt; if CoreVarnishBrushMaker.dayTimer>=30 then CoreVarnishBrushMaker.dayTimer=0; for i=#CoreVarnishBrushMaker.activeMaking,1,-1 do local m=CoreVarnishBrushMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CoreVarnishBrushMaker.completeMaking(m); table.remove(CoreVarnishBrushMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CoreVarnishBrushMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CoreVarnishBrushMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CoreVarnishBrushMaker.getStats() return {ironStock=CoreVarnishBrushMaker.ironStock,bronzeStock=CoreVarnishBrushMaker.bronzeStock,woodStock=CoreVarnishBrushMaker.woodStock,leatherStock=CoreVarnishBrushMaker.leatherStock,silverStock=CoreVarnishBrushMaker.silverStock,goldStock=CoreVarnishBrushMaker.goldStock,jewelStock=CoreVarnishBrushMaker.jewelStock,pearlStock=CoreVarnishBrushMaker.pearlStock,productStock=CoreVarnishBrushMaker.productStock,numBuildings=#CoreVarnishBrushMaker.buildings,hasMaker=CoreVarnishBrushMaker.maker~=nil,makerName=CoreVarnishBrushMaker.maker and CoreVarnishBrushMaker.maker.name or "—",makerSkill=CoreVarnishBrushMaker.maker and CoreVarnishBrushMaker.maker.skill or 0,activeMaking=#CoreVarnishBrushMaker.activeMaking,totalProducts=CoreVarnishBrushMaker.totalProducts} end
return CoreVarnishBrushMaker
