local WashstandMaker = {}
local PRODUCTS = {
    iron_washstand = { name = "Železni umivalni mizic", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni umivalni mizic za kopališča." },
    bronze_washstand = { name = "Bronast umivalni mizic", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast umivalni mizic za kopališča." },
    silver_washstand = { name = "Srebrn umivalni mizic", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn umivalni mizic za kopališča." },
    gilded_washstand = { name = "Pozlačen umivalni mizic", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen umivalni mizic za kopališča." },
    jewel_set_washstand = { name = "Draguljast umivalni mizic", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast umivalni mizic za kopališča." },
    royal_sovereign_washstand = { name = "Kraljevski suveren umivalni mizic", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren umivalni mizic z biseri za krono." },
}
local BUILDINGS = {
    washstand_workshop = { name = "Washstand delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    washstand_house = { name = "Washstand hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_washstand_atelier = { name = "Mojstrski washstand atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_washstand_palace = { name = "Suverena washstand palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
WashstandMaker.ironStock = 14; WashstandMaker.bronzeStock = 12; WashstandMaker.woodStock = 16; WashstandMaker.leatherStock = 10; WashstandMaker.silverStock = 8; WashstandMaker.goldStock = 6; WashstandMaker.jewelStock = 4; WashstandMaker.pearlStock = 4
WashstandMaker.productStock = {}; WashstandMaker.buildings = {}; WashstandMaker.maker = nil; WashstandMaker.activeMaking = {}; WashstandMaker.totalProducts = 0; WashstandMaker.dayTimer = 0
function WashstandMaker.init() WashstandMaker.ironStock=14; WashstandMaker.bronzeStock=12; WashstandMaker.woodStock=16; WashstandMaker.leatherStock=10; WashstandMaker.silverStock=8; WashstandMaker.goldStock=6; WashstandMaker.jewelStock=4; WashstandMaker.pearlStock=4; WashstandMaker.productStock={}; WashstandMaker.buildings={}; WashstandMaker.maker=nil; WashstandMaker.activeMaking={}; WashstandMaker.totalProducts=0; WashstandMaker.dayTimer=0; print("[WashstandMaker] Royal Washstand Maker System initialized (6 products, 4 buildings)") end
function WashstandMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; WashstandMaker.maker={name=n or ("Umivalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Umivalnik najet: %s (spretnost: %d)",WashstandMaker.maker.name,s),"success") end; return true end
function WashstandMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function WashstandMaker.build(id) local ok,e=WashstandMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(WashstandMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function WashstandMaker.getQualityBonus() local b=0; for _,bd in ipairs(WashstandMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function WashstandMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and WashstandMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and WashstandMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and WashstandMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and WashstandMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and WashstandMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and WashstandMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and WashstandMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and WashstandMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #WashstandMaker.buildings==0 then return false,"Potrebna umivalna delavnica" end; if not WashstandMaker.maker then return false,"Potreben umivalnik" end; return true end
function WashstandMaker.make(pt,qty) qty=qty or 1; local ok,e=WashstandMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then WashstandMaker.ironStock=WashstandMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then WashstandMaker.bronzeStock=WashstandMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then WashstandMaker.woodStock=WashstandMaker.woodStock-d.woodCost*qty end; if d.leatherCost then WashstandMaker.leatherStock=WashstandMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then WashstandMaker.silverStock=WashstandMaker.silverStock-d.silverCost*qty end; if d.goldCost then WashstandMaker.goldStock=WashstandMaker.goldStock-d.goldCost*qty end; if d.jewelCost then WashstandMaker.jewelStock=WashstandMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then WashstandMaker.pearlStock=WashstandMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if WashstandMaker.maker then t=math.max(1,t-math.floor(WashstandMaker.maker.skill/13)) end; table.insert(WashstandMaker.activeMaking,{id="washstand_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function WashstandMaker.completeMaking(m) local q=1.0+(WashstandMaker.getQualityBonus()/100); if WashstandMaker.maker then q=q+(WashstandMaker.maker.skill/140) end; q=math.min(2.5,q); WashstandMaker.productStock[m.productType]=(WashstandMaker.productStock[m.productType] or 0)+m.quantity; WashstandMaker.totalProducts=WashstandMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if WashstandMaker.maker then WashstandMaker.maker.itemsMade=WashstandMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then WashstandMaker.maker.skill=math.min(100,WashstandMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Umivalnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"washstand.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function WashstandMaker.update(dt) if not _G.state then return end; WashstandMaker.dayTimer=WashstandMaker.dayTimer+dt; if WashstandMaker.dayTimer>=30 then WashstandMaker.dayTimer=0; for i=#WashstandMaker.activeMaking,1,-1 do local m=WashstandMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then WashstandMaker.completeMaking(m); table.remove(WashstandMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(WashstandMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if WashstandMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function WashstandMaker.getStats() return {ironStock=WashstandMaker.ironStock,bronzeStock=WashstandMaker.bronzeStock,woodStock=WashstandMaker.woodStock,leatherStock=WashstandMaker.leatherStock,silverStock=WashstandMaker.silverStock,goldStock=WashstandMaker.goldStock,jewelStock=WashstandMaker.jewelStock,pearlStock=WashstandMaker.pearlStock,productStock=WashstandMaker.productStock,numBuildings=#WashstandMaker.buildings,hasMaker=WashstandMaker.maker~=nil,makerName=WashstandMaker.maker and WashstandMaker.maker.name or "—",makerSkill=WashstandMaker.maker and WashstandMaker.maker.skill or 0,activeMaking=#WashstandMaker.activeMaking,totalProducts=WashstandMaker.totalProducts} end
return WashstandMaker
