local MillstoneGrooveReframerMaker = {}
local PRODUCTS = {
    iron_millstonegroovereframer = { name = "Železni obnavljalec utorov mlinskih kamnov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni obnavljalec utorov mlinskih kamnov za mlinarje." },
    bronze_millstonegroovereframer = { name = "Bronast obnavljalec utorov mlinskih kamnov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast obnavljalec utorov mlinskih kamnov za mlinarje." },
    silver_millstonegroovereframer = { name = "Srebrn obnavljalec utorov mlinskih kamnov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn obnavljalec utorov mlinskih kamnov za mlinarje." },
    gilded_millstonegroovereframer = { name = "Pozlačen obnavljalec utorov mlinskih kamnov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen obnavljalec utorov mlinskih kamnov za mlinarje." },
    jewel_set_millstonegroovereframer = { name = "Draguljast obnavljalec utorov mlinskih kamnov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast obnavljalec utorov mlinskih kamnov za mlinarje." },
    royal_sovereign_millstonegroovereframer = { name = "Kraljevski suveren obnavljalec utorov mlinskih kamnov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren obnavljalec utorov mlinskih kamnov z biseri za krono." },
}
local BUILDINGS = {
    millstonegroovereframer_workshop = { name = "Millstonegroovereframer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    millstonegroovereframer_house = { name = "Millstonegroovereframer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_millstonegroovereframer_atelier = { name = "Mojstrski millstonegroovereframer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_millstonegroovereframer_palace = { name = "Suverena millstonegroovereframer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillstoneGrooveReframerMaker.ironStock=18; MillstoneGrooveReframerMaker.bronzeStock=14; MillstoneGrooveReframerMaker.woodStock=10; MillstoneGrooveReframerMaker.leatherStock=8; MillstoneGrooveReframerMaker.silverStock=8; MillstoneGrooveReframerMaker.goldStock=6; MillstoneGrooveReframerMaker.jewelStock=4; MillstoneGrooveReframerMaker.pearlStock=4
MillstoneGrooveReframerMaker.productStock = {}; MillstoneGrooveReframerMaker.buildings = {}; MillstoneGrooveReframerMaker.maker = nil; MillstoneGrooveReframerMaker.activeMaking = {}; MillstoneGrooveReframerMaker.totalProducts = 0; MillstoneGrooveReframerMaker.dayTimer = 0
function MillstoneGrooveReframerMaker.init() MillstoneGrooveReframerMaker.ironStock=18; MillstoneGrooveReframerMaker.bronzeStock=14; MillstoneGrooveReframerMaker.woodStock=10; MillstoneGrooveReframerMaker.leatherStock=8; MillstoneGrooveReframerMaker.silverStock=8; MillstoneGrooveReframerMaker.goldStock=6; MillstoneGrooveReframerMaker.jewelStock=4; MillstoneGrooveReframerMaker.pearlStock=4; MillstoneGrooveReframerMaker.productStock={}; MillstoneGrooveReframerMaker.buildings={}; MillstoneGrooveReframerMaker.maker=nil; MillstoneGrooveReframerMaker.activeMaking={}; MillstoneGrooveReframerMaker.totalProducts=0; MillstoneGrooveReframerMaker.dayTimer=0; print("[MillstoneGrooveReframerMaker] Royal Millstone Groove Reframer Maker System initialized (6 products, 4 buildings)") end
function MillstoneGrooveReframerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillstoneGrooveReframerMaker.maker={name=n or ("Utorovalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Utorovalec najet: %s (spretnost: %d)",MillstoneGrooveReframerMaker.maker.name,s),"success") end; return true end
function MillstoneGrooveReframerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillstoneGrooveReframerMaker.build(id) local ok,e=MillstoneGrooveReframerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillstoneGrooveReframerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillstoneGrooveReframerMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillstoneGrooveReframerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillstoneGrooveReframerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillstoneGrooveReframerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillstoneGrooveReframerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillstoneGrooveReframerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillstoneGrooveReframerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillstoneGrooveReframerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillstoneGrooveReframerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillstoneGrooveReframerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillstoneGrooveReframerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillstoneGrooveReframerMaker.buildings==0 then return false,"Potrebna utorovalna delavnica" end; if not MillstoneGrooveReframerMaker.maker then return false,"Potreben utorovalec" end; return true end
function MillstoneGrooveReframerMaker.make(pt,qty) qty=qty or 1; local ok,e=MillstoneGrooveReframerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillstoneGrooveReframerMaker.ironStock=MillstoneGrooveReframerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillstoneGrooveReframerMaker.bronzeStock=MillstoneGrooveReframerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillstoneGrooveReframerMaker.woodStock=MillstoneGrooveReframerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillstoneGrooveReframerMaker.leatherStock=MillstoneGrooveReframerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillstoneGrooveReframerMaker.silverStock=MillstoneGrooveReframerMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillstoneGrooveReframerMaker.goldStock=MillstoneGrooveReframerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillstoneGrooveReframerMaker.jewelStock=MillstoneGrooveReframerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillstoneGrooveReframerMaker.pearlStock=MillstoneGrooveReframerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillstoneGrooveReframerMaker.maker then t=math.max(1,t-math.floor(MillstoneGrooveReframerMaker.maker.skill/13)) end; table.insert(MillstoneGrooveReframerMaker.activeMaking,{id="millstonegroovereframer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillstoneGrooveReframerMaker.completeMaking(m) local q=1.0+(MillstoneGrooveReframerMaker.getQualityBonus()/100); if MillstoneGrooveReframerMaker.maker then q=q+(MillstoneGrooveReframerMaker.maker.skill/140) end; q=math.min(2.5,q); MillstoneGrooveReframerMaker.productStock[m.productType]=(MillstoneGrooveReframerMaker.productStock[m.productType] or 0)+m.quantity; MillstoneGrooveReframerMaker.totalProducts=MillstoneGrooveReframerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillstoneGrooveReframerMaker.maker then MillstoneGrooveReframerMaker.maker.itemsMade=MillstoneGrooveReframerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillstoneGrooveReframerMaker.maker.skill=math.min(100,MillstoneGrooveReframerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Utorovalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millstonegroovereframer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillstoneGrooveReframerMaker.update(dt) if not _G.state then return end; MillstoneGrooveReframerMaker.dayTimer=MillstoneGrooveReframerMaker.dayTimer+dt; if MillstoneGrooveReframerMaker.dayTimer>=30 then MillstoneGrooveReframerMaker.dayTimer=0; for i=#MillstoneGrooveReframerMaker.activeMaking,1,-1 do local m=MillstoneGrooveReframerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillstoneGrooveReframerMaker.completeMaking(m); table.remove(MillstoneGrooveReframerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillstoneGrooveReframerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillstoneGrooveReframerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillstoneGrooveReframerMaker.getStats() return {ironStock=MillstoneGrooveReframerMaker.ironStock,bronzeStock=MillstoneGrooveReframerMaker.bronzeStock,woodStock=MillstoneGrooveReframerMaker.woodStock,leatherStock=MillstoneGrooveReframerMaker.leatherStock,silverStock=MillstoneGrooveReframerMaker.silverStock,goldStock=MillstoneGrooveReframerMaker.goldStock,jewelStock=MillstoneGrooveReframerMaker.jewelStock,pearlStock=MillstoneGrooveReframerMaker.pearlStock,productStock=MillstoneGrooveReframerMaker.productStock,numBuildings=#MillstoneGrooveReframerMaker.buildings,hasMaker=MillstoneGrooveReframerMaker.maker~=nil,makerName=MillstoneGrooveReframerMaker.maker and MillstoneGrooveReframerMaker.maker.name or "—",makerSkill=MillstoneGrooveReframerMaker.maker and MillstoneGrooveReframerMaker.maker.skill or 0,activeMaking=#MillstoneGrooveReframerMaker.activeMaking,totalProducts=MillstoneGrooveReframerMaker.totalProducts} end
return MillstoneGrooveReframerMaker
