local SprueCutterMaker = {}
local PRODUCTS = {
    iron_spruecutter = { name = "Železni rezalec vtokov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni rezalec vtokov za livarje." },
    bronze_spruecutter = { name = "Bronast rezalec vtokov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast rezalec vtokov za livarje." },
    silver_spruecutter = { name = "Srebrn rezalec vtokov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn rezalec vtokov za livarje." },
    gilded_spruecutter = { name = "Pozlačen rezalec vtokov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen rezalec vtokov za livarje." },
    jewel_set_spruecutter = { name = "Draguljast rezalec vtokov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast rezalec vtokov za livarje." },
    royal_sovereign_spruecutter = { name = "Kraljevski suveren rezalec vtokov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren rezalec vtokov z biseri za krono." },
}
local BUILDINGS = {
    spruecutter_workshop = { name = "Spruecutter delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    spruecutter_house = { name = "Spruecutter hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_spruecutter_atelier = { name = "Mojstrski spruecutter atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_spruecutter_palace = { name = "Suverena spruecutter palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SprueCutterMaker.ironStock=18; SprueCutterMaker.bronzeStock=14; SprueCutterMaker.woodStock=10; SprueCutterMaker.leatherStock=8; SprueCutterMaker.silverStock=8; SprueCutterMaker.goldStock=6; SprueCutterMaker.jewelStock=4; SprueCutterMaker.pearlStock=4
SprueCutterMaker.productStock = {}; SprueCutterMaker.buildings = {}; SprueCutterMaker.maker = nil; SprueCutterMaker.activeMaking = {}; SprueCutterMaker.totalProducts = 0; SprueCutterMaker.dayTimer = 0
function SprueCutterMaker.init() SprueCutterMaker.ironStock=18; SprueCutterMaker.bronzeStock=14; SprueCutterMaker.woodStock=10; SprueCutterMaker.leatherStock=8; SprueCutterMaker.silverStock=8; SprueCutterMaker.goldStock=6; SprueCutterMaker.jewelStock=4; SprueCutterMaker.pearlStock=4; SprueCutterMaker.productStock={}; SprueCutterMaker.buildings={}; SprueCutterMaker.maker=nil; SprueCutterMaker.activeMaking={}; SprueCutterMaker.totalProducts=0; SprueCutterMaker.dayTimer=0; print("[SprueCutterMaker] Royal Sprue Cutter Maker System initialized (6 products, 4 buildings)") end
function SprueCutterMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SprueCutterMaker.maker={name=n or ("Vtokorezar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vtokorezar najet: %s (spretnost: %d)",SprueCutterMaker.maker.name,s),"success") end; return true end
function SprueCutterMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SprueCutterMaker.build(id) local ok,e=SprueCutterMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SprueCutterMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SprueCutterMaker.getQualityBonus() local b=0; for _,bd in ipairs(SprueCutterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SprueCutterMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SprueCutterMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SprueCutterMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SprueCutterMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SprueCutterMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SprueCutterMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SprueCutterMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SprueCutterMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SprueCutterMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SprueCutterMaker.buildings==0 then return false,"Potrebna vtokorezna delavnica" end; if not SprueCutterMaker.maker then return false,"Potreben vtokorezar" end; return true end
function SprueCutterMaker.make(pt,qty) qty=qty or 1; local ok,e=SprueCutterMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SprueCutterMaker.ironStock=SprueCutterMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SprueCutterMaker.bronzeStock=SprueCutterMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SprueCutterMaker.woodStock=SprueCutterMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SprueCutterMaker.leatherStock=SprueCutterMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SprueCutterMaker.silverStock=SprueCutterMaker.silverStock-d.silverCost*qty end; if d.goldCost then SprueCutterMaker.goldStock=SprueCutterMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SprueCutterMaker.jewelStock=SprueCutterMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SprueCutterMaker.pearlStock=SprueCutterMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SprueCutterMaker.maker then t=math.max(1,t-math.floor(SprueCutterMaker.maker.skill/13)) end; table.insert(SprueCutterMaker.activeMaking,{id="spruecutter_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SprueCutterMaker.completeMaking(m) local q=1.0+(SprueCutterMaker.getQualityBonus()/100); if SprueCutterMaker.maker then q=q+(SprueCutterMaker.maker.skill/140) end; q=math.min(2.5,q); SprueCutterMaker.productStock[m.productType]=(SprueCutterMaker.productStock[m.productType] or 0)+m.quantity; SprueCutterMaker.totalProducts=SprueCutterMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SprueCutterMaker.maker then SprueCutterMaker.maker.itemsMade=SprueCutterMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SprueCutterMaker.maker.skill=math.min(100,SprueCutterMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vtokorez izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"spruecutter.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SprueCutterMaker.update(dt) if not _G.state then return end; SprueCutterMaker.dayTimer=SprueCutterMaker.dayTimer+dt; if SprueCutterMaker.dayTimer>=30 then SprueCutterMaker.dayTimer=0; for i=#SprueCutterMaker.activeMaking,1,-1 do local m=SprueCutterMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SprueCutterMaker.completeMaking(m); table.remove(SprueCutterMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SprueCutterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SprueCutterMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SprueCutterMaker.getStats() return {ironStock=SprueCutterMaker.ironStock,bronzeStock=SprueCutterMaker.bronzeStock,woodStock=SprueCutterMaker.woodStock,leatherStock=SprueCutterMaker.leatherStock,silverStock=SprueCutterMaker.silverStock,goldStock=SprueCutterMaker.goldStock,jewelStock=SprueCutterMaker.jewelStock,pearlStock=SprueCutterMaker.pearlStock,productStock=SprueCutterMaker.productStock,numBuildings=#SprueCutterMaker.buildings,hasMaker=SprueCutterMaker.maker~=nil,makerName=SprueCutterMaker.maker and SprueCutterMaker.maker.name or "—",makerSkill=SprueCutterMaker.maker and SprueCutterMaker.maker.skill or 0,activeMaking=#SprueCutterMaker.activeMaking,totalProducts=SprueCutterMaker.totalProducts} end
return SprueCutterMaker
