local PickleCurer = {}
local PRODUCTS = {
    pickled_cucumber = { name = "Kumarica v kisom", cucumberCost = 2, vinegarCost = 1, saltCost = 1, time = 2, cost = 12, flavorStrength = 25, happiness = 1, description = "Kumarica v kisom za vsakdanjo rabo." },
    pickled_cabbage = { name = "Kislo zelje", cabbageCost = 2, saltCost = 1, spiceCost = 1, time = 3, cost = 30, flavorStrength = 40, happiness = 2, prestige = 1, description = "Kislo zelje za zimske jedi." },
    pickled_onion = { name = "Kislo čebula", onionCost = 2, vinegarCost = 1, spiceCost = 1, time = 4, cost = 65, flavorStrength = 55, happiness = 3, prestige = 2, description = "Kislo čebula z začimbami." },
    spiced_pickled_vegetables = { name = "Začinjene kisle zelenjava", cucumberCost = 2, cabbageCost = 1, onionCost = 1, vinegarCost = 1, spiceCost = 2, time = 6, cost = 150, flavorStrength = 70, happiness = 4, prestige = 5, description = "Mešana kisla zelenjava z redkimi začimbami." },
    silver_jar_pickles = { name = "Srebrno kozarec kisle", cucumberCost = 3, cabbageCost = 1, onionCost = 1, vinegarCost = 1, silverCost = 1, spiceCost = 2, time = 9, cost = 380, flavorStrength = 85, happiness = 6, prestige = 11, description = "Kisle zelenjava v srebrnem kozarcu za plemiče." },
    royal_grand_pickles = { name = "Kraljevski veliki kisle", cucumberCost = 5, cabbageCost = 3, onionCost = 2, goldCost = 1, silverCost = 1, jewelCost = 1, vinegarCost = 2, spiceCost = 3, time = 14, cost = 1300, flavorStrength = 100, happiness = 13, prestige = 33, description = "Velike kraljevske kisle zelenjava z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Kisarska delavnica", cost = { gold = 260, wood = 130, stone = 200 }, upkeep = 6, qualityBonus = 5 },
    brining_vat = { name = "Slanica kadi", cost = { gold = 850, wood = 250, stone = 350, salt = 10 }, upkeep = 20, qualityBonus = 18 },
    storage_cellar = { name = "Shramba", cost = { gold = 2100, wood = 350, stone = 600, silver = 30, vinegar = 10 }, upkeep = 52, qualityBonus = 30 },
    royal_pickle_atelier = { name = "Kraljevski atelje kislin", cost = { gold = 8500, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 170, qualityBonus = 55, prestigeBonus = 40 },
}
PickleCurer.cucumberStock = 22; PickleCurer.cabbageStock = 18; PickleCurer.onionStock = 16; PickleCurer.vinegarStock = 14; PickleCurer.saltStock = 14; PickleCurer.spiceStock = 12; PickleCurer.silverStock = 8; PickleCurer.goldStock = 6; PickleCurer.jewelStock = 6
PickleCurer.productStock = {}; PickleCurer.buildings = {}; PickleCurer.maker = nil; PickleCurer.activeMaking = {}; PickleCurer.totalProducts = 0; PickleCurer.dayTimer = 0
function PickleCurer.init() PickleCurer.cucumberStock=22; PickleCurer.cabbageStock=18; PickleCurer.onionStock=16; PickleCurer.vinegarStock=14; PickleCurer.saltStock=14; PickleCurer.spiceStock=12; PickleCurer.silverStock=8; PickleCurer.goldStock=6; PickleCurer.jewelStock=6; PickleCurer.productStock={}; PickleCurer.buildings={}; PickleCurer.maker=nil; PickleCurer.activeMaking={}; PickleCurer.totalProducts=0; PickleCurer.dayTimer=0; print("[PickleCurer] Royal Pickle Curer System initialized (6 products, 4 buildings)") end
function PickleCurer.hireMaker(n,s) s=s or math.random(50,90); local c=480+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PickleCurer.maker={name=n or ("Kisar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kisar najet: %s (spretnost: %d)",PickleCurer.maker.name,s),"success") end; return true end
function PickleCurer.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PickleCurer.build(id) local ok,e=PickleCurer.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PickleCurer.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PickleCurer.getQualityBonus() local b=0; for _,bd in ipairs(PickleCurer.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PickleCurer.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.cucumberCost and PickleCurer.cucumberStock<(d.cucumberCost or 0) then return false,"Premalo kumarič" end; if d.cabbageCost and PickleCurer.cabbageStock<(d.cabbageCost or 0) then return false,"Premalo zelja" end; if d.onionCost and PickleCurer.onionStock<(d.onionCost or 0) then return false,"Premalo čebule" end; if d.vinegarCost and PickleCurer.vinegarStock<(d.vinegarCost or 0) then return false,"Premalo kisa" end; if d.saltCost and PickleCurer.saltStock<(d.saltCost or 0) then return false,"Premalo soli" end; if d.spiceCost and PickleCurer.spiceStock<(d.spiceCost or 0) then return false,"Premalo začimb" end; if d.silverCost and PickleCurer.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PickleCurer.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PickleCurer.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #PickleCurer.buildings==0 then return false,"Potrebna delavnica" end; if not PickleCurer.maker then return false,"Potreben kisar" end; return true end
function PickleCurer.make(pt,qty) qty=qty or 5; local ok,e=PickleCurer.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.cucumberCost then PickleCurer.cucumberStock=PickleCurer.cucumberStock-d.cucumberCost*qty end; if d.cabbageCost then PickleCurer.cabbageStock=PickleCurer.cabbageStock-d.cabbageCost*qty end; if d.onionCost then PickleCurer.onionStock=PickleCurer.onionStock-d.onionCost*qty end; if d.vinegarCost then PickleCurer.vinegarStock=PickleCurer.vinegarStock-d.vinegarCost*qty end; if d.saltCost then PickleCurer.saltStock=PickleCurer.saltStock-d.saltCost*qty end; if d.spiceCost then PickleCurer.spiceStock=PickleCurer.spiceStock-d.spiceCost*qty end; if d.silverCost then PickleCurer.silverStock=PickleCurer.silverStock-d.silverCost*qty end; if d.goldCost then PickleCurer.goldStock=PickleCurer.goldStock-d.goldCost*qty end; if d.jewelCost then PickleCurer.jewelStock=PickleCurer.jewelStock-d.jewelCost*qty end; local t=d.time; if PickleCurer.maker then t=math.max(1,t-math.floor(PickleCurer.maker.skill/12)) end; table.insert(PickleCurer.activeMaking,{id="pickle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,flavorStrength=d.flavorStrength or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PickleCurer.completeMaking(m) local q=1.0+(PickleCurer.getQualityBonus()/100); if PickleCurer.maker then q=q+(PickleCurer.maker.skill/180) end; q=math.min(2.0,q); PickleCurer.productStock[m.productType]=(PickleCurer.productStock[m.productType] or 0)+m.quantity; PickleCurer.totalProducts=PickleCurer.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PickleCurer.maker then PickleCurer.maker.itemsMade=PickleCurer.maker.itemsMade+m.quantity; if math.random()<0.20 then PickleCurer.maker.skill=math.min(100,PickleCurer.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kisle izdelane: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"pickle.completed",{productName=m.productName,flavorStrength=m.flavorStrength,happiness=m.happiness}) end end
function PickleCurer.update(dt) if not _G.state then return end; PickleCurer.dayTimer=PickleCurer.dayTimer+dt; if PickleCurer.dayTimer>=30 then PickleCurer.dayTimer=0; for i=#PickleCurer.activeMaking,1,-1 do local m=PickleCurer.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PickleCurer.completeMaking(m); table.remove(PickleCurer.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PickleCurer.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PickleCurer.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PickleCurer.getStats() return {cucumberStock=PickleCurer.cucumberStock,cabbageStock=PickleCurer.cabbageStock,onionStock=PickleCurer.onionStock,vinegarStock=PickleCurer.vinegarStock,saltStock=PickleCurer.saltStock,spiceStock=PickleCurer.spiceStock,silverStock=PickleCurer.silverStock,goldStock=PickleCurer.goldStock,jewelStock=PickleCurer.jewelStock,productStock=PickleCurer.productStock,numBuildings=#PickleCurer.buildings,hasMaker=PickleCurer.maker~=nil,makerName=PickleCurer.maker and PickleCurer.maker.name or "—",makerSkill=PickleCurer.maker and PickleCurer.maker.skill or 0,activeMaking=#PickleCurer.activeMaking,totalProducts=PickleCurer.totalProducts} end
return PickleCurer
