local GardenSecateursMaker = {}
local PRODUCTS = {
    iron_gardensecateurs = { name = "Železni vrtni škarjici", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni vrtni škarjici za vrtnarje." },
    bronze_gardensecateurs = { name = "Bronast vrtni škarjici", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast vrtni škarjici za vrtnarje." },
    silver_gardensecateurs = { name = "Srebrn vrtni škarjici", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn vrtni škarjici za vrtnarje." },
    gilded_gardensecateurs = { name = "Pozlačen vrtni škarjici", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen vrtni škarjici za vrtnarje." },
    jewel_set_gardensecateurs = { name = "Draguljast vrtni škarjici", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast vrtni škarjici za vrtnarje." },
    royal_sovereign_gardensecateurs = { name = "Kraljevski suveren vrtni škarjici", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren vrtni škarjici z biseri za krono." },
}
local BUILDINGS = {
    gardensecateurs_workshop = { name = "Gardensecateurs delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardensecateurs_house = { name = "Gardensecateurs hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardensecateurs_atelier = { name = "Mojstrski gardensecateurs atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardensecateurs_palace = { name = "Suverena gardensecateurs palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenSecateursMaker.ironStock=18; GardenSecateursMaker.bronzeStock=14; GardenSecateursMaker.woodStock=10; GardenSecateursMaker.leatherStock=8; GardenSecateursMaker.silverStock=8; GardenSecateursMaker.goldStock=6; GardenSecateursMaker.jewelStock=4; GardenSecateursMaker.pearlStock=4
GardenSecateursMaker.productStock = {}; GardenSecateursMaker.buildings = {}; GardenSecateursMaker.maker = nil; GardenSecateursMaker.activeMaking = {}; GardenSecateursMaker.totalProducts = 0; GardenSecateursMaker.dayTimer = 0
function GardenSecateursMaker.init() GardenSecateursMaker.ironStock=18; GardenSecateursMaker.bronzeStock=14; GardenSecateursMaker.woodStock=10; GardenSecateursMaker.leatherStock=8; GardenSecateursMaker.silverStock=8; GardenSecateursMaker.goldStock=6; GardenSecateursMaker.jewelStock=4; GardenSecateursMaker.pearlStock=4; GardenSecateursMaker.productStock={}; GardenSecateursMaker.buildings={}; GardenSecateursMaker.maker=nil; GardenSecateursMaker.activeMaking={}; GardenSecateursMaker.totalProducts=0; GardenSecateursMaker.dayTimer=0; print("[GardenSecateursMaker] Royal Garden Secateurs Maker System initialized (6 products, 4 buildings)") end
function GardenSecateursMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenSecateursMaker.maker={name=n or ("Škarjičar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Škarjičar najet: %s (spretnost: %d)",GardenSecateursMaker.maker.name,s),"success") end; return true end
function GardenSecateursMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenSecateursMaker.build(id) local ok,e=GardenSecateursMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenSecateursMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenSecateursMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenSecateursMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenSecateursMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenSecateursMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenSecateursMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenSecateursMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenSecateursMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenSecateursMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenSecateursMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenSecateursMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenSecateursMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenSecateursMaker.buildings==0 then return false,"Potrebna škarjična delavnica" end; if not GardenSecateursMaker.maker then return false,"Potreben škarjičar" end; return true end
function GardenSecateursMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenSecateursMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenSecateursMaker.ironStock=GardenSecateursMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenSecateursMaker.bronzeStock=GardenSecateursMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenSecateursMaker.woodStock=GardenSecateursMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenSecateursMaker.leatherStock=GardenSecateursMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenSecateursMaker.silverStock=GardenSecateursMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenSecateursMaker.goldStock=GardenSecateursMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenSecateursMaker.jewelStock=GardenSecateursMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenSecateursMaker.pearlStock=GardenSecateursMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenSecateursMaker.maker then t=math.max(1,t-math.floor(GardenSecateursMaker.maker.skill/13)) end; table.insert(GardenSecateursMaker.activeMaking,{id="gardensecateurs_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenSecateursMaker.completeMaking(m) local q=1.0+(GardenSecateursMaker.getQualityBonus()/100); if GardenSecateursMaker.maker then q=q+(GardenSecateursMaker.maker.skill/140) end; q=math.min(2.5,q); GardenSecateursMaker.productStock[m.productType]=(GardenSecateursMaker.productStock[m.productType] or 0)+m.quantity; GardenSecateursMaker.totalProducts=GardenSecateursMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenSecateursMaker.maker then GardenSecateursMaker.maker.itemsMade=GardenSecateursMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenSecateursMaker.maker.skill=math.min(100,GardenSecateursMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Škarjice izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardensecateurs.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenSecateursMaker.update(dt) if not _G.state then return end; GardenSecateursMaker.dayTimer=GardenSecateursMaker.dayTimer+dt; if GardenSecateursMaker.dayTimer>=30 then GardenSecateursMaker.dayTimer=0; for i=#GardenSecateursMaker.activeMaking,1,-1 do local m=GardenSecateursMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenSecateursMaker.completeMaking(m); table.remove(GardenSecateursMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenSecateursMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenSecateursMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenSecateursMaker.getStats() return {ironStock=GardenSecateursMaker.ironStock,bronzeStock=GardenSecateursMaker.bronzeStock,woodStock=GardenSecateursMaker.woodStock,leatherStock=GardenSecateursMaker.leatherStock,silverStock=GardenSecateursMaker.silverStock,goldStock=GardenSecateursMaker.goldStock,jewelStock=GardenSecateursMaker.jewelStock,pearlStock=GardenSecateursMaker.pearlStock,productStock=GardenSecateursMaker.productStock,numBuildings=#GardenSecateursMaker.buildings,hasMaker=GardenSecateursMaker.maker~=nil,makerName=GardenSecateursMaker.maker and GardenSecateursMaker.maker.name or "—",makerSkill=GardenSecateursMaker.maker and GardenSecateursMaker.maker.skill or 0,activeMaking=#GardenSecateursMaker.activeMaking,totalProducts=GardenSecateursMaker.totalProducts} end
return GardenSecateursMaker
