local CoreDryingRackMaker = {}
local PRODUCTS = {
    iron_coredryingrack = { name = "Železni stojala za sušenje jedrc", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni stojala za sušenje jedrc za livarje." },
    bronze_coredryingrack = { name = "Bronast stojala za sušenje jedrc", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast stojala za sušenje jedrc za livarje." },
    silver_coredryingrack = { name = "Srebrn stojala za sušenje jedrc", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn stojala za sušenje jedrc za livarje." },
    gilded_coredryingrack = { name = "Pozlačen stojala za sušenje jedrc", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen stojala za sušenje jedrc za livarje." },
    jewel_set_coredryingrack = { name = "Draguljast stojala za sušenje jedrc", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast stojala za sušenje jedrc za livarje." },
    royal_sovereign_coredryingrack = { name = "Kraljevski suveren stojala za sušenje jedrc", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren stojala za sušenje jedrc z biseri za krono." },
}
local BUILDINGS = {
    coredryingrack_workshop = { name = "Coredryingrack delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    coredryingrack_house = { name = "Coredryingrack hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_coredryingrack_atelier = { name = "Mojstrski coredryingrack atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_coredryingrack_palace = { name = "Suverena coredryingrack palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
CoreDryingRackMaker.ironStock=14; CoreDryingRackMaker.bronzeStock=12; CoreDryingRackMaker.woodStock=14; CoreDryingRackMaker.leatherStock=8; CoreDryingRackMaker.silverStock=8; CoreDryingRackMaker.goldStock=6; CoreDryingRackMaker.jewelStock=4; CoreDryingRackMaker.pearlStock=4
CoreDryingRackMaker.productStock = {}; CoreDryingRackMaker.buildings = {}; CoreDryingRackMaker.maker = nil; CoreDryingRackMaker.activeMaking = {}; CoreDryingRackMaker.totalProducts = 0; CoreDryingRackMaker.dayTimer = 0
function CoreDryingRackMaker.init() CoreDryingRackMaker.ironStock=14; CoreDryingRackMaker.bronzeStock=12; CoreDryingRackMaker.woodStock=14; CoreDryingRackMaker.leatherStock=8; CoreDryingRackMaker.silverStock=8; CoreDryingRackMaker.goldStock=6; CoreDryingRackMaker.jewelStock=4; CoreDryingRackMaker.pearlStock=4; CoreDryingRackMaker.productStock={}; CoreDryingRackMaker.buildings={}; CoreDryingRackMaker.maker=nil; CoreDryingRackMaker.activeMaking={}; CoreDryingRackMaker.totalProducts=0; CoreDryingRackMaker.dayTimer=0; print("[CoreDryingRackMaker] Royal Core Drying Rack Maker System initialized (6 products, 4 buildings)") end
function CoreDryingRackMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CoreDryingRackMaker.maker={name=n or ("Stojalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stojalnik najet: %s (spretnost: %d)",CoreDryingRackMaker.maker.name,s),"success") end; return true end
function CoreDryingRackMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CoreDryingRackMaker.build(id) local ok,e=CoreDryingRackMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CoreDryingRackMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CoreDryingRackMaker.getQualityBonus() local b=0; for _,bd in ipairs(CoreDryingRackMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CoreDryingRackMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CoreDryingRackMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CoreDryingRackMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CoreDryingRackMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CoreDryingRackMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CoreDryingRackMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CoreDryingRackMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CoreDryingRackMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CoreDryingRackMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CoreDryingRackMaker.buildings==0 then return false,"Potrebna stojalna delavnica" end; if not CoreDryingRackMaker.maker then return false,"Potreben stojalnik" end; return true end
function CoreDryingRackMaker.make(pt,qty) qty=qty or 1; local ok,e=CoreDryingRackMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CoreDryingRackMaker.ironStock=CoreDryingRackMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CoreDryingRackMaker.bronzeStock=CoreDryingRackMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CoreDryingRackMaker.woodStock=CoreDryingRackMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CoreDryingRackMaker.leatherStock=CoreDryingRackMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CoreDryingRackMaker.silverStock=CoreDryingRackMaker.silverStock-d.silverCost*qty end; if d.goldCost then CoreDryingRackMaker.goldStock=CoreDryingRackMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CoreDryingRackMaker.jewelStock=CoreDryingRackMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CoreDryingRackMaker.pearlStock=CoreDryingRackMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CoreDryingRackMaker.maker then t=math.max(1,t-math.floor(CoreDryingRackMaker.maker.skill/13)) end; table.insert(CoreDryingRackMaker.activeMaking,{id="coredryingrack_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CoreDryingRackMaker.completeMaking(m) local q=1.0+(CoreDryingRackMaker.getQualityBonus()/100); if CoreDryingRackMaker.maker then q=q+(CoreDryingRackMaker.maker.skill/140) end; q=math.min(2.5,q); CoreDryingRackMaker.productStock[m.productType]=(CoreDryingRackMaker.productStock[m.productType] or 0)+m.quantity; CoreDryingRackMaker.totalProducts=CoreDryingRackMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CoreDryingRackMaker.maker then CoreDryingRackMaker.maker.itemsMade=CoreDryingRackMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CoreDryingRackMaker.maker.skill=math.min(100,CoreDryingRackMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stojalo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"coredryingrack.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CoreDryingRackMaker.update(dt) if not _G.state then return end; CoreDryingRackMaker.dayTimer=CoreDryingRackMaker.dayTimer+dt; if CoreDryingRackMaker.dayTimer>=30 then CoreDryingRackMaker.dayTimer=0; for i=#CoreDryingRackMaker.activeMaking,1,-1 do local m=CoreDryingRackMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CoreDryingRackMaker.completeMaking(m); table.remove(CoreDryingRackMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CoreDryingRackMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CoreDryingRackMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CoreDryingRackMaker.getStats() return {ironStock=CoreDryingRackMaker.ironStock,bronzeStock=CoreDryingRackMaker.bronzeStock,woodStock=CoreDryingRackMaker.woodStock,leatherStock=CoreDryingRackMaker.leatherStock,silverStock=CoreDryingRackMaker.silverStock,goldStock=CoreDryingRackMaker.goldStock,jewelStock=CoreDryingRackMaker.jewelStock,pearlStock=CoreDryingRackMaker.pearlStock,productStock=CoreDryingRackMaker.productStock,numBuildings=#CoreDryingRackMaker.buildings,hasMaker=CoreDryingRackMaker.maker~=nil,makerName=CoreDryingRackMaker.maker and CoreDryingRackMaker.maker.name or "—",makerSkill=CoreDryingRackMaker.maker and CoreDryingRackMaker.maker.skill or 0,activeMaking=#CoreDryingRackMaker.activeMaking,totalProducts=CoreDryingRackMaker.totalProducts} end
return CoreDryingRackMaker
