local PritchelHoleMaker = {}
local PRODUCTS = {
    iron_pritchelhole = { name = "Železni luknja za konice", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni luknja za konice za kovace." },
    bronze_pritchelhole = { name = "Bronast luknja za konice", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast luknja za konice za kovace." },
    silver_pritchelhole = { name = "Srebrn luknja za konice", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn luknja za konice za kovace." },
    gilded_pritchelhole = { name = "Pozlačen luknja za konice", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen luknja za konice za kovace." },
    jewel_set_pritchelhole = { name = "Draguljast luknja za konice", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast luknja za konice za kovace." },
    royal_sovereign_pritchelhole = { name = "Kraljevski suveren luknja za konice", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren luknja za konice z biseri za krono." },
}
local BUILDINGS = {
    pritchelhole_workshop = { name = "Pritchelhole delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    pritchelhole_house = { name = "Pritchelhole hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_pritchelhole_atelier = { name = "Mojstrski pritchelhole atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_pritchelhole_palace = { name = "Suverena pritchelhole palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
PritchelHoleMaker.ironStock=18; PritchelHoleMaker.bronzeStock=14; PritchelHoleMaker.woodStock=10; PritchelHoleMaker.leatherStock=8; PritchelHoleMaker.silverStock=8; PritchelHoleMaker.goldStock=6; PritchelHoleMaker.jewelStock=4; PritchelHoleMaker.pearlStock=4
PritchelHoleMaker.productStock = {}; PritchelHoleMaker.buildings = {}; PritchelHoleMaker.maker = nil; PritchelHoleMaker.activeMaking = {}; PritchelHoleMaker.totalProducts = 0; PritchelHoleMaker.dayTimer = 0
function PritchelHoleMaker.init() PritchelHoleMaker.ironStock=18; PritchelHoleMaker.bronzeStock=14; PritchelHoleMaker.woodStock=10; PritchelHoleMaker.leatherStock=8; PritchelHoleMaker.silverStock=8; PritchelHoleMaker.goldStock=6; PritchelHoleMaker.jewelStock=4; PritchelHoleMaker.pearlStock=4; PritchelHoleMaker.productStock={}; PritchelHoleMaker.buildings={}; PritchelHoleMaker.maker=nil; PritchelHoleMaker.activeMaking={}; PritchelHoleMaker.totalProducts=0; PritchelHoleMaker.dayTimer=0; print("[PritchelHoleMaker] Royal Pritchel Hole Maker System initialized (6 products, 4 buildings)") end
function PritchelHoleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PritchelHoleMaker.maker={name=n or ("Koničar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Koničar najet: %s (spretnost: %d)",PritchelHoleMaker.maker.name,s),"success") end; return true end
function PritchelHoleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PritchelHoleMaker.build(id) local ok,e=PritchelHoleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PritchelHoleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PritchelHoleMaker.getQualityBonus() local b=0; for _,bd in ipairs(PritchelHoleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PritchelHoleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PritchelHoleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and PritchelHoleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and PritchelHoleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PritchelHoleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PritchelHoleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PritchelHoleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PritchelHoleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PritchelHoleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PritchelHoleMaker.buildings==0 then return false,"Potrebna konična delavnica" end; if not PritchelHoleMaker.maker then return false,"Potreben koničar" end; return true end
function PritchelHoleMaker.make(pt,qty) qty=qty or 1; local ok,e=PritchelHoleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PritchelHoleMaker.ironStock=PritchelHoleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then PritchelHoleMaker.bronzeStock=PritchelHoleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then PritchelHoleMaker.woodStock=PritchelHoleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PritchelHoleMaker.leatherStock=PritchelHoleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then PritchelHoleMaker.silverStock=PritchelHoleMaker.silverStock-d.silverCost*qty end; if d.goldCost then PritchelHoleMaker.goldStock=PritchelHoleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PritchelHoleMaker.jewelStock=PritchelHoleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PritchelHoleMaker.pearlStock=PritchelHoleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PritchelHoleMaker.maker then t=math.max(1,t-math.floor(PritchelHoleMaker.maker.skill/13)) end; table.insert(PritchelHoleMaker.activeMaking,{id="pritchelhole_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PritchelHoleMaker.completeMaking(m) local q=1.0+(PritchelHoleMaker.getQualityBonus()/100); if PritchelHoleMaker.maker then q=q+(PritchelHoleMaker.maker.skill/140) end; q=math.min(2.5,q); PritchelHoleMaker.productStock[m.productType]=(PritchelHoleMaker.productStock[m.productType] or 0)+m.quantity; PritchelHoleMaker.totalProducts=PritchelHoleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PritchelHoleMaker.maker then PritchelHoleMaker.maker.itemsMade=PritchelHoleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PritchelHoleMaker.maker.skill=math.min(100,PritchelHoleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Konica izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"pritchelhole.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function PritchelHoleMaker.update(dt) if not _G.state then return end; PritchelHoleMaker.dayTimer=PritchelHoleMaker.dayTimer+dt; if PritchelHoleMaker.dayTimer>=30 then PritchelHoleMaker.dayTimer=0; for i=#PritchelHoleMaker.activeMaking,1,-1 do local m=PritchelHoleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PritchelHoleMaker.completeMaking(m); table.remove(PritchelHoleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PritchelHoleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PritchelHoleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PritchelHoleMaker.getStats() return {ironStock=PritchelHoleMaker.ironStock,bronzeStock=PritchelHoleMaker.bronzeStock,woodStock=PritchelHoleMaker.woodStock,leatherStock=PritchelHoleMaker.leatherStock,silverStock=PritchelHoleMaker.silverStock,goldStock=PritchelHoleMaker.goldStock,jewelStock=PritchelHoleMaker.jewelStock,pearlStock=PritchelHoleMaker.pearlStock,productStock=PritchelHoleMaker.productStock,numBuildings=#PritchelHoleMaker.buildings,hasMaker=PritchelHoleMaker.maker~=nil,makerName=PritchelHoleMaker.maker and PritchelHoleMaker.maker.name or "—",makerSkill=PritchelHoleMaker.maker and PritchelHoleMaker.maker.skill or 0,activeMaking=#PritchelHoleMaker.activeMaking,totalProducts=PritchelHoleMaker.totalProducts} end
return PritchelHoleMaker
