local WoolStapler = {}
local PRODUCTS = {
    raw_fleece = { name = "Surova runa", fleeceCost = 2, time = 1, cost = 12, quality = 30, description = "Surova runa za predelavo." },
    scoured_wool = { name = "Prana volna", fleeceCost = 3, waterCost = 1, soapCost = 1, time = 3, cost = 32, quality = 50, prestige = 1, description = "Prana volna brez umazanije." },
    carded_wool = { name = "Česana volna", fleeceCost = 3, waterCost = 1, soapCost = 1, time = 4, cost = 75, quality = 65, prestige = 2, happiness = 1, description = "Česana volna za predenje." },
    combed_wool = { name = "Glavčana volna", fleeceCost = 4, waterCost = 1, soapCost = 1, oilCost = 1, time = 6, cost = 180, quality = 80, prestige = 5, happiness = 2, description = "Glavčana volna za fine tkanine." },
    silver_spun_wool = { name = "Srebrno predena volna", fleeceCost = 5, silverCost = 1, waterCost = 1, soapCost = 1, oilCost = 1, time = 9, cost = 420, quality = 92, prestige = 11, happiness = 3, description = "Volna s srebrno primesjo za plemiče." },
    royal_grand_wool = { name = "Kraljevski veliki volna", fleeceCost = 8, goldCost = 1, silverCost = 1, jewelCost = 1, waterCost = 2, soapCost = 2, oilCost = 1, time = 14, cost = 1400, quality = 100, prestige = 35, happiness = 8, description = "Velika kraljevska volna z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Volnarska delavnica", cost = { gold = 260, wood = 130 }, upkeep = 6, qualityBonus = 5 },
    scouring_house = { name = "Pralnica", cost = { gold = 850, wood = 250, stone = 350, water = 10 }, upkeep = 20, qualityBonus = 18 },
    carding_room = { name = "Česalnica", cost = { gold = 2100, wood = 350, stone = 600, silver = 30, fleece = 8 }, upkeep = 52, qualityBonus = 30 },
    royal_wool_atelier = { name = "Kraljevski atelje volne", cost = { gold = 8500, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 170, qualityBonus = 55, prestigeBonus = 40 },
}
WoolStapler.fleeceStock = 22; WoolStapler.waterStock = 18; WoolStapler.soapStock = 14; WoolStapler.oilStock = 12; WoolStapler.silverStock = 8; WoolStapler.goldStock = 6; WoolStapler.jewelStock = 6
WoolStapler.productStock = {}; WoolStapler.buildings = {}; WoolStapler.maker = nil; WoolStapler.activeMaking = {}; WoolStapler.totalProducts = 0; WoolStapler.dayTimer = 0
function WoolStapler.init() WoolStapler.fleeceStock=22; WoolStapler.waterStock=18; WoolStapler.soapStock=14; WoolStapler.oilStock=12; WoolStapler.silverStock=8; WoolStapler.goldStock=6; WoolStapler.jewelStock=6; WoolStapler.productStock={}; WoolStapler.buildings={}; WoolStapler.maker=nil; WoolStapler.activeMaking={}; WoolStapler.totalProducts=0; WoolStapler.dayTimer=0; print("[WoolStapler] Royal Wool Stapler System initialized (6 products, 4 buildings)") end
function WoolStapler.hireMaker(n,s) s=s or math.random(50,90); local c=480+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; WoolStapler.maker={name=n or ("Volnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Volnar najet: %s (spretnost: %d)",WoolStapler.maker.name,s),"success") end; return true end
function WoolStapler.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function WoolStapler.build(id) local ok,e=WoolStapler.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(WoolStapler.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function WoolStapler.getQualityBonus() local b=0; for _,bd in ipairs(WoolStapler.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function WoolStapler.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.fleeceCost and WoolStapler.fleeceStock<(d.fleeceCost or 0) then return false,"Premalo runa" end; if d.waterCost and WoolStapler.waterStock<(d.waterCost or 0) then return false,"Premalo vode" end; if d.soapCost and WoolStapler.soapStock<(d.soapCost or 0) then return false,"Premalo mila" end; if d.oilCost and WoolStapler.oilStock<(d.oilCost or 0) then return false,"Premalo olja" end; if d.silverCost and WoolStapler.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and WoolStapler.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and WoolStapler.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #WoolStapler.buildings==0 then return false,"Potrebna delavnica" end; if not WoolStapler.maker then return false,"Potreben volnar" end; return true end
function WoolStapler.make(pt,qty) qty=qty or 5; local ok,e=WoolStapler.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.fleeceCost then WoolStapler.fleeceStock=WoolStapler.fleeceStock-d.fleeceCost*qty end; if d.waterCost then WoolStapler.waterStock=WoolStapler.waterStock-d.waterCost*qty end; if d.soapCost then WoolStapler.soapStock=WoolStapler.soapStock-d.soapCost*qty end; if d.oilCost then WoolStapler.oilStock=WoolStapler.oilStock-d.oilCost*qty end; if d.silverCost then WoolStapler.silverStock=WoolStapler.silverStock-d.silverCost*qty end; if d.goldCost then WoolStapler.goldStock=WoolStapler.goldStock-d.goldCost*qty end; if d.jewelCost then WoolStapler.jewelStock=WoolStapler.jewelStock-d.jewelCost*qty end; local t=d.time; if WoolStapler.maker then t=math.max(1,t-math.floor(WoolStapler.maker.skill/12)) end; table.insert(WoolStapler.activeMaking,{id="wool_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,quality=d.quality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function WoolStapler.completeMaking(m) local q=1.0+(WoolStapler.getQualityBonus()/100); if WoolStapler.maker then q=q+(WoolStapler.maker.skill/180) end; q=math.min(2.0,q); WoolStapler.productStock[m.productType]=(WoolStapler.productStock[m.productType] or 0)+m.quantity; WoolStapler.totalProducts=WoolStapler.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if WoolStapler.maker then WoolStapler.maker.itemsMade=WoolStapler.maker.itemsMade+m.quantity; if math.random()<0.20 then WoolStapler.maker.skill=math.min(100,WoolStapler.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Volna izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"wool.completed",{productName=m.productName,quality=m.quality}) end end
function WoolStapler.update(dt) if not _G.state then return end; WoolStapler.dayTimer=WoolStapler.dayTimer+dt; if WoolStapler.dayTimer>=30 then WoolStapler.dayTimer=0; for i=#WoolStapler.activeMaking,1,-1 do local m=WoolStapler.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then WoolStapler.completeMaking(m); table.remove(WoolStapler.activeMaking,i) end end; local tu=0; for _,bd in ipairs(WoolStapler.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if WoolStapler.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function WoolStapler.getStats() return {fleeceStock=WoolStapler.fleeceStock,waterStock=WoolStapler.waterStock,soapStock=WoolStapler.soapStock,oilStock=WoolStapler.oilStock,silverStock=WoolStapler.silverStock,goldStock=WoolStapler.goldStock,jewelStock=WoolStapler.jewelStock,productStock=WoolStapler.productStock,numBuildings=#WoolStapler.buildings,hasMaker=WoolStapler.maker~=nil,makerName=WoolStapler.maker and WoolStapler.maker.name or "—",makerSkill=WoolStapler.maker and WoolStapler.maker.skill or 0,activeMaking=#WoolStapler.activeMaking,totalProducts=WoolStapler.totalProducts} end
return WoolStapler
