local OrderInsignia = {}
local PRODUCTS = {
    bronze_order_badge = { name = "Bronast redni znak", bronzeCost = 1, ironCost = 1, time = 5, cost = 130, prestige = 4, happiness = 1, description = "Bronast znak za nižje redove." },
    silver_knight_insignia = { name = "Srebrni viteški insignij", silverCost = 1, ironCost = 1, time = 7, cost = 330, prestige = 9, happiness = 2, description = "Srebrni viteški znak za red seniorjev." },
    gilded_commander_badge = { name = "Pozlačeni poveljniški znak", goldCost = 1, silverCost = 1, time = 11, cost = 770, prestige = 17, happiness = 3, description = "Pozlačeni znak poveljnika reda." },
    jewel_set_grand_cross = { name = "Draguljasti veliki križ", goldCost = 2, silverCost = 1, jewelCost = 1, time = 15, cost = 1750, prestige = 30, happiness = 4, description = "Veliki križ z draguljem za visoke plemiče." },
    collar_chain_insignia = { name = "Verižni ovratniški insignij", goldCost = 2, silverCost = 2, jewelCost = 1, time = 19, cost = 3800, prestige = 50, happiness = 6, description = "Verižni ovratnik za kraljevske redove." },
    royal_sovereign_insignia = { name = "Kraljevski suvereni insignij", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, time = 26, cost = 8400, prestige = 88, happiness = 12, description = "Suvereni znak z biseri za krono." },
}
local BUILDINGS = {
    insignia_workshop = { name = "Insignijska delavnica", cost = { gold = 320, wood = 140, stone = 120, iron = 6 }, upkeep = 6, qualityBonus = 5 },
    chivalric_hall = { name = "Viteška dvorana reda", cost = { gold = 1100, wood = 280, stone = 240, silver = 6, iron = 6 }, upkeep = 25, qualityBonus = 18 },
    master_insignia_atelier = { name = "Mojstrski insignijski atelje", cost = { gold = 2900, wood = 360, stone = 480, silver = 32, gold = 6 }, upkeep = 70, qualityBonus = 30 },
    sovereign_orders_palace = { name = "Suverena palača redov", cost = { gold = 12500, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 250, qualityBonus = 55, prestigeBonus = 50 },
}
OrderInsignia.bronzeStock = 12; OrderInsignia.ironStock = 10; OrderInsignia.silverStock = 8; OrderInsignia.goldStock = 6; OrderInsignia.jewelStock = 4; OrderInsignia.pearlStock = 4
OrderInsignia.productStock = {}; OrderInsignia.buildings = {}; OrderInsignia.maker = nil; OrderInsignia.activeMaking = {}; OrderInsignia.totalProducts = 0; OrderInsignia.dayTimer = 0
function OrderInsignia.init() OrderInsignia.bronzeStock=12; OrderInsignia.ironStock=10; OrderInsignia.silverStock=8; OrderInsignia.goldStock=6; OrderInsignia.jewelStock=4; OrderInsignia.pearlStock=4; OrderInsignia.productStock={}; OrderInsignia.buildings={}; OrderInsignia.maker=nil; OrderInsignia.activeMaking={}; OrderInsignia.totalProducts=0; OrderInsignia.dayTimer=0; print("[OrderInsignia] Royal Order Insignia System initialized (6 products, 4 buildings)") end
function OrderInsignia.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; OrderInsignia.maker={name=n or ("Insignijar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Insignijar najet: %s (spretnost: %d)",OrderInsignia.maker.name,s),"success") end; return true end
function OrderInsignia.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function OrderInsignia.build(id) local ok,e=OrderInsignia.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(OrderInsignia.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function OrderInsignia.getQualityBonus() local b=0; for _,bd in ipairs(OrderInsignia.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function OrderInsignia.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.bronzeCost and OrderInsignia.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.ironCost and OrderInsignia.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.silverCost and OrderInsignia.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and OrderInsignia.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and OrderInsignia.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and OrderInsignia.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #OrderInsignia.buildings==0 then return false,"Potrebna insignijska delavnica" end; if not OrderInsignia.maker then return false,"Potreben insignijar" end; return true end
function OrderInsignia.make(pt,qty) qty=qty or 1; local ok,e=OrderInsignia.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.bronzeCost then OrderInsignia.bronzeStock=OrderInsignia.bronzeStock-d.bronzeCost*qty end; if d.ironCost then OrderInsignia.ironStock=OrderInsignia.ironStock-d.ironCost*qty end; if d.silverCost then OrderInsignia.silverStock=OrderInsignia.silverStock-d.silverCost*qty end; if d.goldCost then OrderInsignia.goldStock=OrderInsignia.goldStock-d.goldCost*qty end; if d.jewelCost then OrderInsignia.jewelStock=OrderInsignia.jewelStock-d.jewelCost*qty end; if d.pearlCost then OrderInsignia.pearlStock=OrderInsignia.pearlStock-d.pearlCost*qty end; local t=d.time; if OrderInsignia.maker then t=math.max(1,t-math.floor(OrderInsignia.maker.skill/13)) end; table.insert(OrderInsignia.activeMaking,{id="insignia_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function OrderInsignia.completeMaking(m) local q=1.0+(OrderInsignia.getQualityBonus()/100); if OrderInsignia.maker then q=q+(OrderInsignia.maker.skill/140) end; q=math.min(2.5,q); OrderInsignia.productStock[m.productType]=(OrderInsignia.productStock[m.productType] or 0)+m.quantity; OrderInsignia.totalProducts=OrderInsignia.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if OrderInsignia.maker then OrderInsignia.maker.itemsMade=OrderInsignia.maker.itemsMade+m.quantity; if math.random()<0.25 then OrderInsignia.maker.skill=math.min(100,OrderInsignia.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Insignij izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"insignia.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function OrderInsignia.update(dt) if not _G.state then return end; OrderInsignia.dayTimer=OrderInsignia.dayTimer+dt; if OrderInsignia.dayTimer>=30 then OrderInsignia.dayTimer=0; for i=#OrderInsignia.activeMaking,1,-1 do local m=OrderInsignia.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then OrderInsignia.completeMaking(m); table.remove(OrderInsignia.activeMaking,i) end end; local tu=0; for _,bd in ipairs(OrderInsignia.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if OrderInsignia.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function OrderInsignia.getStats() return {bronzeStock=OrderInsignia.bronzeStock,ironStock=OrderInsignia.ironStock,silverStock=OrderInsignia.silverStock,goldStock=OrderInsignia.goldStock,jewelStock=OrderInsignia.jewelStock,pearlStock=OrderInsignia.pearlStock,productStock=OrderInsignia.productStock,numBuildings=#OrderInsignia.buildings,hasMaker=OrderInsignia.maker~=nil,makerName=OrderInsignia.maker and OrderInsignia.maker.name or "—",makerSkill=OrderInsignia.maker and OrderInsignia.maker.skill or 0,activeMaking=#OrderInsignia.activeMaking,totalProducts=OrderInsignia.totalProducts} end
return OrderInsignia
