local BookCoverBoardCornerMiterMaker = {}
local PRODUCTS = {
    iron_bookcoverboardcornermiter = { name = "Železni koti za vezave naslovnic", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni koti za vezave naslovnic za knjigoveze." },
    bronze_bookcoverboardcornermiter = { name = "Bronast koti za vezave naslovnic", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast koti za vezave naslovnic za knjigoveze." },
    silver_bookcoverboardcornermiter = { name = "Srebrn koti za vezave naslovnic", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn koti za vezave naslovnic za knjigoveze." },
    gilded_bookcoverboardcornermiter = { name = "Pozlačen koti za vezave naslovnic", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen koti za vezave naslovnic za knjigoveze." },
    jewel_set_bookcoverboardcornermiter = { name = "Draguljast koti za vezave naslovnic", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast koti za vezave naslovnic za knjigoveze." },
    royal_sovereign_bookcoverboardcornermiter = { name = "Kraljevski suveren koti za vezave naslovnic", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren koti za vezave naslovnic z biseri za krono." },
}
local BUILDINGS = {
    bookcoverboardcornermiter_workshop = { name = "Bookcoverboardcornermiter delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookcoverboardcornermiter_house = { name = "Bookcoverboardcornermiter hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookcoverboardcornermiter_atelier = { name = "Mojstrski bookcoverboardcornermiter atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookcoverboardcornermiter_palace = { name = "Suverena bookcoverboardcornermiter palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookCoverBoardCornerMiterMaker.ironStock=18; BookCoverBoardCornerMiterMaker.bronzeStock=14; BookCoverBoardCornerMiterMaker.woodStock=10; BookCoverBoardCornerMiterMaker.leatherStock=8; BookCoverBoardCornerMiterMaker.silverStock=8; BookCoverBoardCornerMiterMaker.goldStock=6; BookCoverBoardCornerMiterMaker.jewelStock=4; BookCoverBoardCornerMiterMaker.pearlStock=4
BookCoverBoardCornerMiterMaker.productStock = {}; BookCoverBoardCornerMiterMaker.buildings = {}; BookCoverBoardCornerMiterMaker.maker = nil; BookCoverBoardCornerMiterMaker.activeMaking = {}; BookCoverBoardCornerMiterMaker.totalProducts = 0; BookCoverBoardCornerMiterMaker.dayTimer = 0
function BookCoverBoardCornerMiterMaker.init() BookCoverBoardCornerMiterMaker.ironStock=18; BookCoverBoardCornerMiterMaker.bronzeStock=14; BookCoverBoardCornerMiterMaker.woodStock=10; BookCoverBoardCornerMiterMaker.leatherStock=8; BookCoverBoardCornerMiterMaker.silverStock=8; BookCoverBoardCornerMiterMaker.goldStock=6; BookCoverBoardCornerMiterMaker.jewelStock=4; BookCoverBoardCornerMiterMaker.pearlStock=4; BookCoverBoardCornerMiterMaker.productStock={}; BookCoverBoardCornerMiterMaker.buildings={}; BookCoverBoardCornerMiterMaker.maker=nil; BookCoverBoardCornerMiterMaker.activeMaking={}; BookCoverBoardCornerMiterMaker.totalProducts=0; BookCoverBoardCornerMiterMaker.dayTimer=0; print("[BookCoverBoardCornerMiterMaker] Royal Book Cover Board Corner Miter Maker System initialized (6 products, 4 buildings)") end
function BookCoverBoardCornerMiterMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookCoverBoardCornerMiterMaker.maker={name=n or ("Kotnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kotnik najet: %s (spretnost: %d)",BookCoverBoardCornerMiterMaker.maker.name,s),"success") end; return true end
function BookCoverBoardCornerMiterMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookCoverBoardCornerMiterMaker.build(id) local ok,e=BookCoverBoardCornerMiterMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookCoverBoardCornerMiterMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookCoverBoardCornerMiterMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookCoverBoardCornerMiterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookCoverBoardCornerMiterMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookCoverBoardCornerMiterMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookCoverBoardCornerMiterMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookCoverBoardCornerMiterMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookCoverBoardCornerMiterMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookCoverBoardCornerMiterMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookCoverBoardCornerMiterMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookCoverBoardCornerMiterMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookCoverBoardCornerMiterMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookCoverBoardCornerMiterMaker.buildings==0 then return false,"Potrebna kotna delavnica" end; if not BookCoverBoardCornerMiterMaker.maker then return false,"Potreben kotnik" end; return true end
function BookCoverBoardCornerMiterMaker.make(pt,qty) qty=qty or 1; local ok,e=BookCoverBoardCornerMiterMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookCoverBoardCornerMiterMaker.ironStock=BookCoverBoardCornerMiterMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookCoverBoardCornerMiterMaker.bronzeStock=BookCoverBoardCornerMiterMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookCoverBoardCornerMiterMaker.woodStock=BookCoverBoardCornerMiterMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookCoverBoardCornerMiterMaker.leatherStock=BookCoverBoardCornerMiterMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookCoverBoardCornerMiterMaker.silverStock=BookCoverBoardCornerMiterMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookCoverBoardCornerMiterMaker.goldStock=BookCoverBoardCornerMiterMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookCoverBoardCornerMiterMaker.jewelStock=BookCoverBoardCornerMiterMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookCoverBoardCornerMiterMaker.pearlStock=BookCoverBoardCornerMiterMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookCoverBoardCornerMiterMaker.maker then t=math.max(1,t-math.floor(BookCoverBoardCornerMiterMaker.maker.skill/13)) end; table.insert(BookCoverBoardCornerMiterMaker.activeMaking,{id="bookcoverboardcornermiter_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookCoverBoardCornerMiterMaker.completeMaking(m) local q=1.0+(BookCoverBoardCornerMiterMaker.getQualityBonus()/100); if BookCoverBoardCornerMiterMaker.maker then q=q+(BookCoverBoardCornerMiterMaker.maker.skill/140) end; q=math.min(2.5,q); BookCoverBoardCornerMiterMaker.productStock[m.productType]=(BookCoverBoardCornerMiterMaker.productStock[m.productType] or 0)+m.quantity; BookCoverBoardCornerMiterMaker.totalProducts=BookCoverBoardCornerMiterMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookCoverBoardCornerMiterMaker.maker then BookCoverBoardCornerMiterMaker.maker.itemsMade=BookCoverBoardCornerMiterMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookCoverBoardCornerMiterMaker.maker.skill=math.min(100,BookCoverBoardCornerMiterMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kot izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookcoverboardcornermiter.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookCoverBoardCornerMiterMaker.update(dt) if not _G.state then return end; BookCoverBoardCornerMiterMaker.dayTimer=BookCoverBoardCornerMiterMaker.dayTimer+dt; if BookCoverBoardCornerMiterMaker.dayTimer>=30 then BookCoverBoardCornerMiterMaker.dayTimer=0; for i=#BookCoverBoardCornerMiterMaker.activeMaking,1,-1 do local m=BookCoverBoardCornerMiterMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookCoverBoardCornerMiterMaker.completeMaking(m); table.remove(BookCoverBoardCornerMiterMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookCoverBoardCornerMiterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookCoverBoardCornerMiterMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookCoverBoardCornerMiterMaker.getStats() return {ironStock=BookCoverBoardCornerMiterMaker.ironStock,bronzeStock=BookCoverBoardCornerMiterMaker.bronzeStock,woodStock=BookCoverBoardCornerMiterMaker.woodStock,leatherStock=BookCoverBoardCornerMiterMaker.leatherStock,silverStock=BookCoverBoardCornerMiterMaker.silverStock,goldStock=BookCoverBoardCornerMiterMaker.goldStock,jewelStock=BookCoverBoardCornerMiterMaker.jewelStock,pearlStock=BookCoverBoardCornerMiterMaker.pearlStock,productStock=BookCoverBoardCornerMiterMaker.productStock,numBuildings=#BookCoverBoardCornerMiterMaker.buildings,hasMaker=BookCoverBoardCornerMiterMaker.maker~=nil,makerName=BookCoverBoardCornerMiterMaker.maker and BookCoverBoardCornerMiterMaker.maker.name or "—",makerSkill=BookCoverBoardCornerMiterMaker.maker and BookCoverBoardCornerMiterMaker.maker.skill or 0,activeMaking=#BookCoverBoardCornerMiterMaker.activeMaking,totalProducts=BookCoverBoardCornerMiterMaker.totalProducts} end
return BookCoverBoardCornerMiterMaker
