local MoldCoatingBrushMaker = {}
local PRODUCTS = {
    iron_moldcoatingbrush = { name = "Železni čopič za premaze kalupov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni čopič za premaze kalupov za livarje." },
    bronze_moldcoatingbrush = { name = "Bronast čopič za premaze kalupov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast čopič za premaze kalupov za livarje." },
    silver_moldcoatingbrush = { name = "Srebrn čopič za premaze kalupov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn čopič za premaze kalupov za livarje." },
    gilded_moldcoatingbrush = { name = "Pozlačen čopič za premaze kalupov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen čopič za premaze kalupov za livarje." },
    jewel_set_moldcoatingbrush = { name = "Draguljast čopič za premaze kalupov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast čopič za premaze kalupov za livarje." },
    royal_sovereign_moldcoatingbrush = { name = "Kraljevski suveren čopič za premaze kalupov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren čopič za premaze kalupov z biseri za krono." },
}
local BUILDINGS = {
    moldcoatingbrush_workshop = { name = "Moldcoatingbrush delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    moldcoatingbrush_house = { name = "Moldcoatingbrush hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_moldcoatingbrush_atelier = { name = "Mojstrski moldcoatingbrush atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_moldcoatingbrush_palace = { name = "Suverena moldcoatingbrush palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MoldCoatingBrushMaker.ironStock=12; MoldCoatingBrushMaker.bronzeStock=10; MoldCoatingBrushMaker.woodStock=14; MoldCoatingBrushMaker.leatherStock=12; MoldCoatingBrushMaker.silverStock=8; MoldCoatingBrushMaker.goldStock=6; MoldCoatingBrushMaker.jewelStock=4; MoldCoatingBrushMaker.pearlStock=4
MoldCoatingBrushMaker.productStock = {}; MoldCoatingBrushMaker.buildings = {}; MoldCoatingBrushMaker.maker = nil; MoldCoatingBrushMaker.activeMaking = {}; MoldCoatingBrushMaker.totalProducts = 0; MoldCoatingBrushMaker.dayTimer = 0
function MoldCoatingBrushMaker.init() MoldCoatingBrushMaker.ironStock=12; MoldCoatingBrushMaker.bronzeStock=10; MoldCoatingBrushMaker.woodStock=14; MoldCoatingBrushMaker.leatherStock=12; MoldCoatingBrushMaker.silverStock=8; MoldCoatingBrushMaker.goldStock=6; MoldCoatingBrushMaker.jewelStock=4; MoldCoatingBrushMaker.pearlStock=4; MoldCoatingBrushMaker.productStock={}; MoldCoatingBrushMaker.buildings={}; MoldCoatingBrushMaker.maker=nil; MoldCoatingBrushMaker.activeMaking={}; MoldCoatingBrushMaker.totalProducts=0; MoldCoatingBrushMaker.dayTimer=0; print("[MoldCoatingBrushMaker] Royal Mold Coating Brush Maker System initialized (6 products, 4 buildings)") end
function MoldCoatingBrushMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MoldCoatingBrushMaker.maker={name=n or ("Čopičar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Čopičar najet: %s (spretnost: %d)",MoldCoatingBrushMaker.maker.name,s),"success") end; return true end
function MoldCoatingBrushMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MoldCoatingBrushMaker.build(id) local ok,e=MoldCoatingBrushMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MoldCoatingBrushMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MoldCoatingBrushMaker.getQualityBonus() local b=0; for _,bd in ipairs(MoldCoatingBrushMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MoldCoatingBrushMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MoldCoatingBrushMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MoldCoatingBrushMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MoldCoatingBrushMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MoldCoatingBrushMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MoldCoatingBrushMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MoldCoatingBrushMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MoldCoatingBrushMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MoldCoatingBrushMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MoldCoatingBrushMaker.buildings==0 then return false,"Potrebna čopična delavnica" end; if not MoldCoatingBrushMaker.maker then return false,"Potreben čopičar" end; return true end
function MoldCoatingBrushMaker.make(pt,qty) qty=qty or 1; local ok,e=MoldCoatingBrushMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MoldCoatingBrushMaker.ironStock=MoldCoatingBrushMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MoldCoatingBrushMaker.bronzeStock=MoldCoatingBrushMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MoldCoatingBrushMaker.woodStock=MoldCoatingBrushMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MoldCoatingBrushMaker.leatherStock=MoldCoatingBrushMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MoldCoatingBrushMaker.silverStock=MoldCoatingBrushMaker.silverStock-d.silverCost*qty end; if d.goldCost then MoldCoatingBrushMaker.goldStock=MoldCoatingBrushMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MoldCoatingBrushMaker.jewelStock=MoldCoatingBrushMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MoldCoatingBrushMaker.pearlStock=MoldCoatingBrushMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MoldCoatingBrushMaker.maker then t=math.max(1,t-math.floor(MoldCoatingBrushMaker.maker.skill/13)) end; table.insert(MoldCoatingBrushMaker.activeMaking,{id="moldcoatingbrush_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MoldCoatingBrushMaker.completeMaking(m) local q=1.0+(MoldCoatingBrushMaker.getQualityBonus()/100); if MoldCoatingBrushMaker.maker then q=q+(MoldCoatingBrushMaker.maker.skill/140) end; q=math.min(2.5,q); MoldCoatingBrushMaker.productStock[m.productType]=(MoldCoatingBrushMaker.productStock[m.productType] or 0)+m.quantity; MoldCoatingBrushMaker.totalProducts=MoldCoatingBrushMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MoldCoatingBrushMaker.maker then MoldCoatingBrushMaker.maker.itemsMade=MoldCoatingBrushMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MoldCoatingBrushMaker.maker.skill=math.min(100,MoldCoatingBrushMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Čopič izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"moldcoatingbrush.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MoldCoatingBrushMaker.update(dt) if not _G.state then return end; MoldCoatingBrushMaker.dayTimer=MoldCoatingBrushMaker.dayTimer+dt; if MoldCoatingBrushMaker.dayTimer>=30 then MoldCoatingBrushMaker.dayTimer=0; for i=#MoldCoatingBrushMaker.activeMaking,1,-1 do local m=MoldCoatingBrushMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MoldCoatingBrushMaker.completeMaking(m); table.remove(MoldCoatingBrushMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MoldCoatingBrushMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MoldCoatingBrushMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MoldCoatingBrushMaker.getStats() return {ironStock=MoldCoatingBrushMaker.ironStock,bronzeStock=MoldCoatingBrushMaker.bronzeStock,woodStock=MoldCoatingBrushMaker.woodStock,leatherStock=MoldCoatingBrushMaker.leatherStock,silverStock=MoldCoatingBrushMaker.silverStock,goldStock=MoldCoatingBrushMaker.goldStock,jewelStock=MoldCoatingBrushMaker.jewelStock,pearlStock=MoldCoatingBrushMaker.pearlStock,productStock=MoldCoatingBrushMaker.productStock,numBuildings=#MoldCoatingBrushMaker.buildings,hasMaker=MoldCoatingBrushMaker.maker~=nil,makerName=MoldCoatingBrushMaker.maker and MoldCoatingBrushMaker.maker.name or "—",makerSkill=MoldCoatingBrushMaker.maker and MoldCoatingBrushMaker.maker.skill or 0,activeMaking=#MoldCoatingBrushMaker.activeMaking,totalProducts=MoldCoatingBrushMaker.totalProducts} end
return MoldCoatingBrushMaker
