local DrillPressMaker = {}
local PRODUCTS = {
    simple_wood_drill = { name = "Preprost leseni vrtalni stroj", woodCost = 4, ironCost = 2, time = 5, cost = 180, science = 20, happiness = 1, description = "Preprost leseni vrtalni stroj za vrtanje." },
    iron_reinforced_drill = { name = "Železnookrepljen vrtalni stroj", woodCost = 3, ironCost = 3, brassCost = 1, time = 8, cost = 440, science = 32, happiness = 2, prestige = 2, description = "Železnookrepljen vrtalni stroj za trgovce." },
    silver_chuck_drill = { name = "Srebrnospojni vrtalni stroj", woodCost = 3, ironCost = 2, silverCost = 1, brassCost = 1, time = 12, cost = 1000, science = 48, happiness = 2, prestige = 6, description = "Srebrnospojni vrtalni stroj za plemiče." },
    gold_trimmed_drill = { name = "Zlatookrasni vrtalni stroj", woodCost = 3, ironCost = 2, goldCost = 1, silverCost = 1, brassCost = 1, time = 16, cost = 2300, science = 62, happiness = 3, prestige = 14, description = "Zlatookrasni vrtalni stroj za visoke plemiče." },
    jewel_set_drill = { name = "Draguljasta vrtalni stroj", woodCost = 3, ironCost = 2, goldCost = 1, silverCost = 1, brassCost = 1, jewelCost = 1, time = 20, cost = 4800, science = 78, happiness = 5, prestige = 27, description = "Vrtalni stroj z draguljem za visoko plemstvo." },
    royal_grand_drill = { name = "Kraljevski veliki vrtalni stroj", woodCost = 5, ironCost = 3, goldCost = 2, silverCost = 2, brassCost = 1, jewelCost = 2, pearlCost = 2, time = 27, cost = 10000, science = 95, happiness = 12, prestige = 58, description = "Veliki kraljevski vrtalni stroj z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    drill_workshop = { name = "Vrtna delavnica", cost = { gold = 300, wood = 160, stone = 140, iron = 6 }, upkeep = 7, qualityBonus = 5 },
    machinery_loft = { name = "Strojna podstrešje", cost = { gold = 1100, wood = 320, stone = 280, silver = 6, brass = 6 }, upkeep = 26, qualityBonus = 18 },
    master_machinist_atelier = { name = "Mojstrski strojniški atelje", cost = { gold = 2800, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_machinery_palace = { name = "Kraljevska strojna palača", cost = { gold = 12000, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
DrillPressMaker.woodStock = 20; DrillPressMaker.ironStock = 14; DrillPressMaker.brassStock = 10; DrillPressMaker.silverStock = 6; DrillPressMaker.goldStock = 6; DrillPressMaker.jewelStock = 4; DrillPressMaker.pearlStock = 4
DrillPressMaker.productStock = {}; DrillPressMaker.buildings = {}; DrillPressMaker.maker = nil; DrillPressMaker.activeMaking = {}; DrillPressMaker.totalProducts = 0; DrillPressMaker.dayTimer = 0
function DrillPressMaker.init() DrillPressMaker.woodStock=20; DrillPressMaker.ironStock=14; DrillPressMaker.brassStock=10; DrillPressMaker.silverStock=6; DrillPressMaker.goldStock=6; DrillPressMaker.jewelStock=4; DrillPressMaker.pearlStock=4; DrillPressMaker.productStock={}; DrillPressMaker.buildings={}; DrillPressMaker.maker=nil; DrillPressMaker.activeMaking={}; DrillPressMaker.totalProducts=0; DrillPressMaker.dayTimer=0; print("[DrillPressMaker] Royal Drill Press Maker System initialized (6 products, 4 buildings)") end
function DrillPressMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; DrillPressMaker.maker={name=n or ("Vrtnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrtnar najet: %s (spretnost: %d)",DrillPressMaker.maker.name,s),"success") end; return true end
function DrillPressMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function DrillPressMaker.build(id) local ok,e=DrillPressMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(DrillPressMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function DrillPressMaker.getQualityBonus() local b=0; for _,bd in ipairs(DrillPressMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function DrillPressMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and DrillPressMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and DrillPressMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.brassCost and DrillPressMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and DrillPressMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and DrillPressMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and DrillPressMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and DrillPressMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #DrillPressMaker.buildings==0 then return false,"Potrebna vrtna delavnica" end; if not DrillPressMaker.maker then return false,"Potreben vrtnar" end; return true end
function DrillPressMaker.make(pt,qty) qty=qty or 1; local ok,e=DrillPressMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then DrillPressMaker.woodStock=DrillPressMaker.woodStock-d.woodCost*qty end; if d.ironCost then DrillPressMaker.ironStock=DrillPressMaker.ironStock-d.ironCost*qty end; if d.brassCost then DrillPressMaker.brassStock=DrillPressMaker.brassStock-d.brassCost*qty end; if d.silverCost then DrillPressMaker.silverStock=DrillPressMaker.silverStock-d.silverCost*qty end; if d.goldCost then DrillPressMaker.goldStock=DrillPressMaker.goldStock-d.goldCost*qty end; if d.jewelCost then DrillPressMaker.jewelStock=DrillPressMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then DrillPressMaker.pearlStock=DrillPressMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if DrillPressMaker.maker then t=math.max(1,t-math.floor(DrillPressMaker.maker.skill/12)) end; table.insert(DrillPressMaker.activeMaking,{id="drill_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function DrillPressMaker.completeMaking(m) local q=1.0+(DrillPressMaker.getQualityBonus()/100); if DrillPressMaker.maker then q=q+(DrillPressMaker.maker.skill/140) end; q=math.min(2.5,q); DrillPressMaker.productStock[m.productType]=(DrillPressMaker.productStock[m.productType] or 0)+m.quantity; DrillPressMaker.totalProducts=DrillPressMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if DrillPressMaker.maker then DrillPressMaker.maker.itemsMade=DrillPressMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then DrillPressMaker.maker.skill=math.min(100,DrillPressMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrtalni stroj izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"drill.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function DrillPressMaker.update(dt) if not _G.state then return end; DrillPressMaker.dayTimer=DrillPressMaker.dayTimer+dt; if DrillPressMaker.dayTimer>=30 then DrillPressMaker.dayTimer=0; for i=#DrillPressMaker.activeMaking,1,-1 do local m=DrillPressMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then DrillPressMaker.completeMaking(m); table.remove(DrillPressMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(DrillPressMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if DrillPressMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function DrillPressMaker.getStats() return {woodStock=DrillPressMaker.woodStock,ironStock=DrillPressMaker.ironStock,brassStock=DrillPressMaker.brassStock,silverStock=DrillPressMaker.silverStock,goldStock=DrillPressMaker.goldStock,jewelStock=DrillPressMaker.jewelStock,pearlStock=DrillPressMaker.pearlStock,productStock=DrillPressMaker.productStock,numBuildings=#DrillPressMaker.buildings,hasMaker=DrillPressMaker.maker~=nil,makerName=DrillPressMaker.maker and DrillPressMaker.maker.name or "—",makerSkill=DrillPressMaker.maker and DrillPressMaker.maker.skill or 0,activeMaking=#DrillPressMaker.activeMaking,totalProducts=DrillPressMaker.totalProducts} end
return DrillPressMaker
