local CastingLadlePreheatStandMaker = {}
local PRODUCTS = {
    iron_castingladlepreheatstand = { name = "Železni stojalo za predgrevanje", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni stojalo za predgrevanje za livarje." },
    bronze_castingladlepreheatstand = { name = "Bronast stojalo za predgrevanje", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast stojalo za predgrevanje za livarje." },
    silver_castingladlepreheatstand = { name = "Srebrn stojalo za predgrevanje", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn stojalo za predgrevanje za livarje." },
    gilded_castingladlepreheatstand = { name = "Pozlačen stojalo za predgrevanje", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen stojalo za predgrevanje za livarje." },
    jewel_set_castingladlepreheatstand = { name = "Draguljast stojalo za predgrevanje", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast stojalo za predgrevanje za livarje." },
    royal_sovereign_castingladlepreheatstand = { name = "Kraljevski suveren stojalo za predgrevanje", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren stojalo za predgrevanje z biseri za krono." },
}
local BUILDINGS = {
    castingladlepreheatstand_workshop = { name = "Castingladlepreheatstand delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    castingladlepreheatstand_house = { name = "Castingladlepreheatstand hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_castingladlepreheatstand_atelier = { name = "Mojstrski castingladlepreheatstand atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_castingladlepreheatstand_palace = { name = "Suverena castingladlepreheatstand palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
CastingLadlePreheatStandMaker.ironStock=14; CastingLadlePreheatStandMaker.bronzeStock=12; CastingLadlePreheatStandMaker.woodStock=14; CastingLadlePreheatStandMaker.leatherStock=8; CastingLadlePreheatStandMaker.silverStock=8; CastingLadlePreheatStandMaker.goldStock=6; CastingLadlePreheatStandMaker.jewelStock=4; CastingLadlePreheatStandMaker.pearlStock=4
CastingLadlePreheatStandMaker.productStock = {}; CastingLadlePreheatStandMaker.buildings = {}; CastingLadlePreheatStandMaker.maker = nil; CastingLadlePreheatStandMaker.activeMaking = {}; CastingLadlePreheatStandMaker.totalProducts = 0; CastingLadlePreheatStandMaker.dayTimer = 0
function CastingLadlePreheatStandMaker.init() CastingLadlePreheatStandMaker.ironStock=14; CastingLadlePreheatStandMaker.bronzeStock=12; CastingLadlePreheatStandMaker.woodStock=14; CastingLadlePreheatStandMaker.leatherStock=8; CastingLadlePreheatStandMaker.silverStock=8; CastingLadlePreheatStandMaker.goldStock=6; CastingLadlePreheatStandMaker.jewelStock=4; CastingLadlePreheatStandMaker.pearlStock=4; CastingLadlePreheatStandMaker.productStock={}; CastingLadlePreheatStandMaker.buildings={}; CastingLadlePreheatStandMaker.maker=nil; CastingLadlePreheatStandMaker.activeMaking={}; CastingLadlePreheatStandMaker.totalProducts=0; CastingLadlePreheatStandMaker.dayTimer=0; print("[CastingLadlePreheatStandMaker] Royal Casting Ladle Preheat Stand Maker System initialized (6 products, 4 buildings)") end
function CastingLadlePreheatStandMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CastingLadlePreheatStandMaker.maker={name=n or ("Stojalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stojalnik najet: %s (spretnost: %d)",CastingLadlePreheatStandMaker.maker.name,s),"success") end; return true end
function CastingLadlePreheatStandMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CastingLadlePreheatStandMaker.build(id) local ok,e=CastingLadlePreheatStandMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CastingLadlePreheatStandMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CastingLadlePreheatStandMaker.getQualityBonus() local b=0; for _,bd in ipairs(CastingLadlePreheatStandMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CastingLadlePreheatStandMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CastingLadlePreheatStandMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CastingLadlePreheatStandMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CastingLadlePreheatStandMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CastingLadlePreheatStandMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CastingLadlePreheatStandMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CastingLadlePreheatStandMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CastingLadlePreheatStandMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CastingLadlePreheatStandMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CastingLadlePreheatStandMaker.buildings==0 then return false,"Potrebna stojalna delavnica" end; if not CastingLadlePreheatStandMaker.maker then return false,"Potreben stojalnik" end; return true end
function CastingLadlePreheatStandMaker.make(pt,qty) qty=qty or 1; local ok,e=CastingLadlePreheatStandMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CastingLadlePreheatStandMaker.ironStock=CastingLadlePreheatStandMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CastingLadlePreheatStandMaker.bronzeStock=CastingLadlePreheatStandMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CastingLadlePreheatStandMaker.woodStock=CastingLadlePreheatStandMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CastingLadlePreheatStandMaker.leatherStock=CastingLadlePreheatStandMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CastingLadlePreheatStandMaker.silverStock=CastingLadlePreheatStandMaker.silverStock-d.silverCost*qty end; if d.goldCost then CastingLadlePreheatStandMaker.goldStock=CastingLadlePreheatStandMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CastingLadlePreheatStandMaker.jewelStock=CastingLadlePreheatStandMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CastingLadlePreheatStandMaker.pearlStock=CastingLadlePreheatStandMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CastingLadlePreheatStandMaker.maker then t=math.max(1,t-math.floor(CastingLadlePreheatStandMaker.maker.skill/13)) end; table.insert(CastingLadlePreheatStandMaker.activeMaking,{id="castingladlepreheatstand_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CastingLadlePreheatStandMaker.completeMaking(m) local q=1.0+(CastingLadlePreheatStandMaker.getQualityBonus()/100); if CastingLadlePreheatStandMaker.maker then q=q+(CastingLadlePreheatStandMaker.maker.skill/140) end; q=math.min(2.5,q); CastingLadlePreheatStandMaker.productStock[m.productType]=(CastingLadlePreheatStandMaker.productStock[m.productType] or 0)+m.quantity; CastingLadlePreheatStandMaker.totalProducts=CastingLadlePreheatStandMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CastingLadlePreheatStandMaker.maker then CastingLadlePreheatStandMaker.maker.itemsMade=CastingLadlePreheatStandMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CastingLadlePreheatStandMaker.maker.skill=math.min(100,CastingLadlePreheatStandMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stojalo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"castingladlepreheatstand.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CastingLadlePreheatStandMaker.update(dt) if not _G.state then return end; CastingLadlePreheatStandMaker.dayTimer=CastingLadlePreheatStandMaker.dayTimer+dt; if CastingLadlePreheatStandMaker.dayTimer>=30 then CastingLadlePreheatStandMaker.dayTimer=0; for i=#CastingLadlePreheatStandMaker.activeMaking,1,-1 do local m=CastingLadlePreheatStandMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CastingLadlePreheatStandMaker.completeMaking(m); table.remove(CastingLadlePreheatStandMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CastingLadlePreheatStandMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CastingLadlePreheatStandMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CastingLadlePreheatStandMaker.getStats() return {ironStock=CastingLadlePreheatStandMaker.ironStock,bronzeStock=CastingLadlePreheatStandMaker.bronzeStock,woodStock=CastingLadlePreheatStandMaker.woodStock,leatherStock=CastingLadlePreheatStandMaker.leatherStock,silverStock=CastingLadlePreheatStandMaker.silverStock,goldStock=CastingLadlePreheatStandMaker.goldStock,jewelStock=CastingLadlePreheatStandMaker.jewelStock,pearlStock=CastingLadlePreheatStandMaker.pearlStock,productStock=CastingLadlePreheatStandMaker.productStock,numBuildings=#CastingLadlePreheatStandMaker.buildings,hasMaker=CastingLadlePreheatStandMaker.maker~=nil,makerName=CastingLadlePreheatStandMaker.maker and CastingLadlePreheatStandMaker.maker.name or "—",makerSkill=CastingLadlePreheatStandMaker.maker and CastingLadlePreheatStandMaker.maker.skill or 0,activeMaking=#CastingLadlePreheatStandMaker.activeMaking,totalProducts=CastingLadlePreheatStandMaker.totalProducts} end
return CastingLadlePreheatStandMaker
