local FishSmoker = {}
local PRODUCTS = {
    smoked_herring = { name = "Prekajena sled", fishCost = 2, saltCost = 1, fuelCost = 1, time = 2, cost = 15, flavorStrength = 30, happiness = 1, description = "Prekajena sled za kmete." },
    smoked_trout = { name = "Prekajena postrv", fishCost = 3, saltCost = 1, spiceCost = 1, fuelCost = 1, time = 4, cost = 45, flavorStrength = 45, happiness = 2, prestige = 1, description = "Prekajena postrv z nežnim okusom." },
    smoked_salmon = { name = "Prekajen losos", fishCost = 4, saltCost = 1, spiceCost = 1, fuelCost = 1, time = 6, cost = 110, flavorStrength = 60, happiness = 3, prestige = 3, description = "Prekajen losos za plemiče." },
    spiced_smoked_fish = { name = "Začinjeno prekajena riba", fishCost = 4, saltCost = 1, spiceCost = 2, fuelCost = 1, time = 8, cost = 240, flavorStrength = 75, happiness = 4, prestige = 6, description = "Začinjena prekajena riba z redkimi začimbami." },
    silver_platter_fish = { name = "Srebrno pladenj riba", fishCost = 5, silverCost = 1, saltCost = 1, spiceCost = 2, fuelCost = 1, time = 11, cost = 520, flavorStrength = 90, happiness = 6, prestige = 12, description = "Prekajena riba na srebrnem pladnju za visoke plemiče." },
    royal_grand_smoked_fish = { name = "Kraljevski veliki prekajena riba", fishCost = 8, goldCost = 1, silverCost = 1, jewelCost = 1, saltCost = 2, spiceCost = 3, fuelCost = 2, time = 16, cost = 1500, flavorStrength = 100, happiness = 13, prestige = 35, description = "Velika kraljevska prekajena riba z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Ribja kadilnica", cost = { gold = 280, wood = 140, stone = 200 }, upkeep = 7, qualityBonus = 5 },
    smokehouse = { name = "Kadilnica", cost = { gold = 900, wood = 280, stone = 400, fish = 10 }, upkeep = 22, qualityBonus = 18 },
    brining_room = { name = "Slanica", cost = { gold = 2200, wood = 350, stone = 600, silver = 30, salt = 10 }, upkeep = 55, qualityBonus = 30 },
    royal_fish_atelier = { name = "Kraljevski atelje prekajenih rib", cost = { gold = 9000, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
FishSmoker.fishStock = 22; FishSmoker.saltStock = 14; FishSmoker.spiceStock = 12; FishSmoker.fuelStock = 14; FishSmoker.silverStock = 8; FishSmoker.goldStock = 6; FishSmoker.jewelStock = 6
FishSmoker.productStock = {}; FishSmoker.buildings = {}; FishSmoker.maker = nil; FishSmoker.activeMaking = {}; FishSmoker.totalProducts = 0; FishSmoker.dayTimer = 0
function FishSmoker.init() FishSmoker.fishStock=22; FishSmoker.saltStock=14; FishSmoker.spiceStock=12; FishSmoker.fuelStock=14; FishSmoker.silverStock=8; FishSmoker.goldStock=6; FishSmoker.jewelStock=6; FishSmoker.productStock={}; FishSmoker.buildings={}; FishSmoker.maker=nil; FishSmoker.activeMaking={}; FishSmoker.totalProducts=0; FishSmoker.dayTimer=0; print("[FishSmoker] Royal Fish Smoker System initialized (6 products, 4 buildings)") end
function FishSmoker.hireMaker(n,s) s=s or math.random(50,90); local c=500+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; FishSmoker.maker={name=n or ("Ribji kadilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ribji kadilar najet: %s (spretnost: %d)",FishSmoker.maker.name,s),"success") end; return true end
function FishSmoker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function FishSmoker.build(id) local ok,e=FishSmoker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(FishSmoker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function FishSmoker.getQualityBonus() local b=0; for _,bd in ipairs(FishSmoker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function FishSmoker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.fishCost and FishSmoker.fishStock<(d.fishCost or 0) then return false,"Premalo rib" end; if d.saltCost and FishSmoker.saltStock<(d.saltCost or 0) then return false,"Premalo soli" end; if d.spiceCost and FishSmoker.spiceStock<(d.spiceCost or 0) then return false,"Premalo začimb" end; if d.fuelCost and FishSmoker.fuelStock<(d.fuelCost or 0) then return false,"Premalo goriva" end; if d.silverCost and FishSmoker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and FishSmoker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and FishSmoker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #FishSmoker.buildings==0 then return false,"Potrebna delavnica" end; if not FishSmoker.maker then return false,"Potreben ribji kadilar" end; return true end
function FishSmoker.make(pt,qty) qty=qty or 5; local ok,e=FishSmoker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.fishCost then FishSmoker.fishStock=FishSmoker.fishStock-d.fishCost*qty end; if d.saltCost then FishSmoker.saltStock=FishSmoker.saltStock-d.saltCost*qty end; if d.spiceCost then FishSmoker.spiceStock=FishSmoker.spiceStock-d.spiceCost*qty end; if d.fuelCost then FishSmoker.fuelStock=FishSmoker.fuelStock-d.fuelCost*qty end; if d.silverCost then FishSmoker.silverStock=FishSmoker.silverStock-d.silverCost*qty end; if d.goldCost then FishSmoker.goldStock=FishSmoker.goldStock-d.goldCost*qty end; if d.jewelCost then FishSmoker.jewelStock=FishSmoker.jewelStock-d.jewelCost*qty end; local t=d.time; if FishSmoker.maker then t=math.max(1,t-math.floor(FishSmoker.maker.skill/12)) end; table.insert(FishSmoker.activeMaking,{id="fishsmoke_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,flavorStrength=d.flavorStrength or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function FishSmoker.completeMaking(m) local q=1.0+(FishSmoker.getQualityBonus()/100); if FishSmoker.maker then q=q+(FishSmoker.maker.skill/180) end; q=math.min(2.0,q); FishSmoker.productStock[m.productType]=(FishSmoker.productStock[m.productType] or 0)+m.quantity; FishSmoker.totalProducts=FishSmoker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if FishSmoker.maker then FishSmoker.maker.itemsMade=FishSmoker.maker.itemsMade+m.quantity; if math.random()<0.20 then FishSmoker.maker.skill=math.min(100,FishSmoker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Prekajena riba izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"fishsmoke.completed",{productName=m.productName,flavorStrength=m.flavorStrength,happiness=m.happiness}) end end
function FishSmoker.update(dt) if not _G.state then return end; FishSmoker.dayTimer=FishSmoker.dayTimer+dt; if FishSmoker.dayTimer>=30 then FishSmoker.dayTimer=0; for i=#FishSmoker.activeMaking,1,-1 do local m=FishSmoker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then FishSmoker.completeMaking(m); table.remove(FishSmoker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(FishSmoker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if FishSmoker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function FishSmoker.getStats() return {fishStock=FishSmoker.fishStock,saltStock=FishSmoker.saltStock,spiceStock=FishSmoker.spiceStock,fuelStock=FishSmoker.fuelStock,silverStock=FishSmoker.silverStock,goldStock=FishSmoker.goldStock,jewelStock=FishSmoker.jewelStock,productStock=FishSmoker.productStock,numBuildings=#FishSmoker.buildings,hasMaker=FishSmoker.maker~=nil,makerName=FishSmoker.maker and FishSmoker.maker.name or "—",makerSkill=FishSmoker.maker and FishSmoker.maker.skill or 0,activeMaking=#FishSmoker.activeMaking,totalProducts=FishSmoker.totalProducts} end
return FishSmoker
