local PlantRootPrunerMaker = {}
local PRODUCTS = {
    iron_plantrootpruner = { name = "Železni škarje za korenine", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni škarje za korenine za vrtnarje." },
    bronze_plantrootpruner = { name = "Bronast škarje za korenine", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast škarje za korenine za vrtnarje." },
    silver_plantrootpruner = { name = "Srebrn škarje za korenine", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn škarje za korenine za vrtnarje." },
    gilded_plantrootpruner = { name = "Pozlačen škarje za korenine", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen škarje za korenine za vrtnarje." },
    jewel_set_plantrootpruner = { name = "Draguljast škarje za korenine", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast škarje za korenine za vrtnarje." },
    royal_sovereign_plantrootpruner = { name = "Kraljevski suveren škarje za korenine", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren škarje za korenine z biseri za krono." },
}
local BUILDINGS = {
    plantrootpruner_workshop = { name = "Plantrootpruner delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    plantrootpruner_house = { name = "Plantrootpruner hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_plantrootpruner_atelier = { name = "Mojstrski plantrootpruner atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_plantrootpruner_palace = { name = "Suverena plantrootpruner palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
PlantRootPrunerMaker.ironStock=18; PlantRootPrunerMaker.bronzeStock=14; PlantRootPrunerMaker.woodStock=10; PlantRootPrunerMaker.leatherStock=8; PlantRootPrunerMaker.silverStock=8; PlantRootPrunerMaker.goldStock=6; PlantRootPrunerMaker.jewelStock=4; PlantRootPrunerMaker.pearlStock=4
PlantRootPrunerMaker.productStock = {}; PlantRootPrunerMaker.buildings = {}; PlantRootPrunerMaker.maker = nil; PlantRootPrunerMaker.activeMaking = {}; PlantRootPrunerMaker.totalProducts = 0; PlantRootPrunerMaker.dayTimer = 0
function PlantRootPrunerMaker.init() PlantRootPrunerMaker.ironStock=18; PlantRootPrunerMaker.bronzeStock=14; PlantRootPrunerMaker.woodStock=10; PlantRootPrunerMaker.leatherStock=8; PlantRootPrunerMaker.silverStock=8; PlantRootPrunerMaker.goldStock=6; PlantRootPrunerMaker.jewelStock=4; PlantRootPrunerMaker.pearlStock=4; PlantRootPrunerMaker.productStock={}; PlantRootPrunerMaker.buildings={}; PlantRootPrunerMaker.maker=nil; PlantRootPrunerMaker.activeMaking={}; PlantRootPrunerMaker.totalProducts=0; PlantRootPrunerMaker.dayTimer=0; print("[PlantRootPrunerMaker] Royal Plant Root Pruner Maker System initialized (6 products, 4 buildings)") end
function PlantRootPrunerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PlantRootPrunerMaker.maker={name=n or ("Koreninar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Koreninar najet: %s (spretnost: %d)",PlantRootPrunerMaker.maker.name,s),"success") end; return true end
function PlantRootPrunerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PlantRootPrunerMaker.build(id) local ok,e=PlantRootPrunerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PlantRootPrunerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PlantRootPrunerMaker.getQualityBonus() local b=0; for _,bd in ipairs(PlantRootPrunerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PlantRootPrunerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PlantRootPrunerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and PlantRootPrunerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and PlantRootPrunerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PlantRootPrunerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PlantRootPrunerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PlantRootPrunerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PlantRootPrunerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PlantRootPrunerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PlantRootPrunerMaker.buildings==0 then return false,"Potrebna koreninska delavnica" end; if not PlantRootPrunerMaker.maker then return false,"Potreben koreninar" end; return true end
function PlantRootPrunerMaker.make(pt,qty) qty=qty or 1; local ok,e=PlantRootPrunerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PlantRootPrunerMaker.ironStock=PlantRootPrunerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then PlantRootPrunerMaker.bronzeStock=PlantRootPrunerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then PlantRootPrunerMaker.woodStock=PlantRootPrunerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PlantRootPrunerMaker.leatherStock=PlantRootPrunerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then PlantRootPrunerMaker.silverStock=PlantRootPrunerMaker.silverStock-d.silverCost*qty end; if d.goldCost then PlantRootPrunerMaker.goldStock=PlantRootPrunerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PlantRootPrunerMaker.jewelStock=PlantRootPrunerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PlantRootPrunerMaker.pearlStock=PlantRootPrunerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PlantRootPrunerMaker.maker then t=math.max(1,t-math.floor(PlantRootPrunerMaker.maker.skill/13)) end; table.insert(PlantRootPrunerMaker.activeMaking,{id="plantrootpruner_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PlantRootPrunerMaker.completeMaking(m) local q=1.0+(PlantRootPrunerMaker.getQualityBonus()/100); if PlantRootPrunerMaker.maker then q=q+(PlantRootPrunerMaker.maker.skill/140) end; q=math.min(2.5,q); PlantRootPrunerMaker.productStock[m.productType]=(PlantRootPrunerMaker.productStock[m.productType] or 0)+m.quantity; PlantRootPrunerMaker.totalProducts=PlantRootPrunerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PlantRootPrunerMaker.maker then PlantRootPrunerMaker.maker.itemsMade=PlantRootPrunerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PlantRootPrunerMaker.maker.skill=math.min(100,PlantRootPrunerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Škarje izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"plantrootpruner.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function PlantRootPrunerMaker.update(dt) if not _G.state then return end; PlantRootPrunerMaker.dayTimer=PlantRootPrunerMaker.dayTimer+dt; if PlantRootPrunerMaker.dayTimer>=30 then PlantRootPrunerMaker.dayTimer=0; for i=#PlantRootPrunerMaker.activeMaking,1,-1 do local m=PlantRootPrunerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PlantRootPrunerMaker.completeMaking(m); table.remove(PlantRootPrunerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PlantRootPrunerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PlantRootPrunerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PlantRootPrunerMaker.getStats() return {ironStock=PlantRootPrunerMaker.ironStock,bronzeStock=PlantRootPrunerMaker.bronzeStock,woodStock=PlantRootPrunerMaker.woodStock,leatherStock=PlantRootPrunerMaker.leatherStock,silverStock=PlantRootPrunerMaker.silverStock,goldStock=PlantRootPrunerMaker.goldStock,jewelStock=PlantRootPrunerMaker.jewelStock,pearlStock=PlantRootPrunerMaker.pearlStock,productStock=PlantRootPrunerMaker.productStock,numBuildings=#PlantRootPrunerMaker.buildings,hasMaker=PlantRootPrunerMaker.maker~=nil,makerName=PlantRootPrunerMaker.maker and PlantRootPrunerMaker.maker.name or "—",makerSkill=PlantRootPrunerMaker.maker and PlantRootPrunerMaker.maker.skill or 0,activeMaking=#PlantRootPrunerMaker.activeMaking,totalProducts=PlantRootPrunerMaker.totalProducts} end
return PlantRootPrunerMaker
