local GlazeSieveMaker = {}
local PRODUCTS = {
    iron_glaze_sieve = { name = "Železno sito za glazure", ironCost = 2, woodCost = 3, leatherCost = 1, time = 4, cost = 140, prestige = 3, happiness = 2, description = "Železno sito za sejanje glazur." },
    bronze_glaze_sieve = { name = "Bronasto sito za glazure", bronzeCost = 2, ironCost = 1, woodCost = 3, leatherCost = 1, time = 6, cost = 340, prestige = 5, happiness = 3, description = "Bronasto sito za fine glazure." },
    silver_glaze_sieve = { name = "Srebrno sito za glazure", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 3, leatherCost = 1, time = 10, cost = 830, prestige = 10, happiness = 4, description = "Srebrno sito za plemiške glazure." },
    gilded_glaze_sieve = { name = "Pozlačeno sito za glazure", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 14, cost = 1800, prestige = 19, happiness = 5, description = "Pozlačeno sito za dvorne glazure." },
    jewel_set_glaze_sieve = { name = "Draguljasto sito za glazure", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 18, cost = 3900, prestige = 35, happiness = 7, description = "Draguljasto sito za kraljevske glazure." },
    royal_sovereign_glaze_sieve = { name = "Kraljevski suvereno sito za glazure", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 4, leatherCost = 1, time = 25, cost = 8400, prestige = 67, happiness = 13, description = "Suvereno sito z biseri za krono." },
}
local BUILDINGS = {
    glazesieve_workshop = { name = "Sitna delavnica", cost = { gold = 300, wood = 180, stone = 125, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    glazesieve_house = { name = "Sitna hiša", cost = { gold = 1110, wood = 360, stone = 255, silver = 6, iron = 6 }, upkeep = 23, qualityBonus = 18 },
    master_glazesieve_atelier = { name = "Mojstrski sitni atelje", cost = { gold = 2850, wood = 420, stone = 495, silver = 32, gold = 6 }, upkeep = 67, qualityBonus = 30 },
    sovereign_glazesieve_palace = { name = "Suverena sitna palača", cost = { gold = 12400, wood = 640, stone = 800, gold = 79, jewel = 18 }, upkeep = 245, qualityBonus = 55, prestigeBonus = 50 },
}
GlazeSieveMaker.ironStock = 12; GlazeSieveMaker.bronzeStock = 10; GlazeSieveMaker.woodStock = 16; GlazeSieveMaker.leatherStock = 10; GlazeSieveMaker.silverStock = 8; GlazeSieveMaker.goldStock = 6; GlazeSieveMaker.jewelStock = 4; GlazeSieveMaker.pearlStock = 4
GlazeSieveMaker.productStock = {}; GlazeSieveMaker.buildings = {}; GlazeSieveMaker.maker = nil; GlazeSieveMaker.activeMaking = {}; GlazeSieveMaker.totalProducts = 0; GlazeSieveMaker.dayTimer = 0
function GlazeSieveMaker.init() GlazeSieveMaker.ironStock=12; GlazeSieveMaker.bronzeStock=10; GlazeSieveMaker.woodStock=16; GlazeSieveMaker.leatherStock=10; GlazeSieveMaker.silverStock=8; GlazeSieveMaker.goldStock=6; GlazeSieveMaker.jewelStock=4; GlazeSieveMaker.pearlStock=4; GlazeSieveMaker.productStock={}; GlazeSieveMaker.buildings={}; GlazeSieveMaker.maker=nil; GlazeSieveMaker.activeMaking={}; GlazeSieveMaker.totalProducts=0; GlazeSieveMaker.dayTimer=0; print("[GlazeSieveMaker] Royal Glaze Sieve Maker System initialized (6 products, 4 buildings)") end
function GlazeSieveMaker.hireMaker(n,s) s=s or math.random(55,90); local c=565+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlazeSieveMaker.maker={name=n or ("Sitar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sitar najet: %s (spretnost: %d)",GlazeSieveMaker.maker.name,s),"success") end; return true end
function GlazeSieveMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlazeSieveMaker.build(id) local ok,e=GlazeSieveMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlazeSieveMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlazeSieveMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlazeSieveMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlazeSieveMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlazeSieveMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlazeSieveMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlazeSieveMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlazeSieveMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlazeSieveMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlazeSieveMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlazeSieveMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlazeSieveMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlazeSieveMaker.buildings==0 then return false,"Potrebna sitna delavnica" end; if not GlazeSieveMaker.maker then return false,"Potreben sitar" end; return true end
function GlazeSieveMaker.make(pt,qty) qty=qty or 1; local ok,e=GlazeSieveMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlazeSieveMaker.ironStock=GlazeSieveMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlazeSieveMaker.bronzeStock=GlazeSieveMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlazeSieveMaker.woodStock=GlazeSieveMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlazeSieveMaker.leatherStock=GlazeSieveMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlazeSieveMaker.silverStock=GlazeSieveMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlazeSieveMaker.goldStock=GlazeSieveMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlazeSieveMaker.jewelStock=GlazeSieveMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlazeSieveMaker.pearlStock=GlazeSieveMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlazeSieveMaker.maker then t=math.max(1,t-math.floor(GlazeSieveMaker.maker.skill/13)) end; table.insert(GlazeSieveMaker.activeMaking,{id="glazesieve_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlazeSieveMaker.completeMaking(m) local q=1.0+(GlazeSieveMaker.getQualityBonus()/100); if GlazeSieveMaker.maker then q=q+(GlazeSieveMaker.maker.skill/140) end; q=math.min(2.5,q); GlazeSieveMaker.productStock[m.productType]=(GlazeSieveMaker.productStock[m.productType] or 0)+m.quantity; GlazeSieveMaker.totalProducts=GlazeSieveMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlazeSieveMaker.maker then GlazeSieveMaker.maker.itemsMade=GlazeSieveMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlazeSieveMaker.maker.skill=math.min(100,GlazeSieveMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sito izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glazesieve.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlazeSieveMaker.update(dt) if not _G.state then return end; GlazeSieveMaker.dayTimer=GlazeSieveMaker.dayTimer+dt; if GlazeSieveMaker.dayTimer>=30 then GlazeSieveMaker.dayTimer=0; for i=#GlazeSieveMaker.activeMaking,1,-1 do local m=GlazeSieveMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlazeSieveMaker.completeMaking(m); table.remove(GlazeSieveMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlazeSieveMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlazeSieveMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlazeSieveMaker.getStats() return {ironStock=GlazeSieveMaker.ironStock,bronzeStock=GlazeSieveMaker.bronzeStock,woodStock=GlazeSieveMaker.woodStock,leatherStock=GlazeSieveMaker.leatherStock,silverStock=GlazeSieveMaker.silverStock,goldStock=GlazeSieveMaker.goldStock,jewelStock=GlazeSieveMaker.jewelStock,pearlStock=GlazeSieveMaker.pearlStock,productStock=GlazeSieveMaker.productStock,numBuildings=#GlazeSieveMaker.buildings,hasMaker=GlazeSieveMaker.maker~=nil,makerName=GlazeSieveMaker.maker and GlazeSieveMaker.maker.name or "—",makerSkill=GlazeSieveMaker.maker and GlazeSieveMaker.maker.skill or 0,activeMaking=#GlazeSieveMaker.activeMaking,totalProducts=GlazeSieveMaker.totalProducts} end
return GlazeSieveMaker
