local EscapementLeverMaker = {}
local PRODUCTS = {
    iron_escapementlever = { name = "Železni uhopna ročica", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni uhopna ročica za ure." },
    bronze_escapementlever = { name = "Bronast uhopna ročica", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast uhopna ročica za ure." },
    silver_escapementlever = { name = "Srebrn uhopna ročica", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn uhopna ročica za ure." },
    gilded_escapementlever = { name = "Pozlačen uhopna ročica", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen uhopna ročica za ure." },
    jewel_set_escapementlever = { name = "Draguljast uhopna ročica", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast uhopna ročica za ure." },
    royal_sovereign_escapementlever = { name = "Kraljevski suveren uhopna ročica", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren uhopna ročica z biseri za krono." },
}
local BUILDINGS = {
    escapementlever_workshop = { name = "Escapementlever delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    escapementlever_house = { name = "Escapementlever hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_escapementlever_atelier = { name = "Mojstrski escapementlever atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_escapementlever_palace = { name = "Suverena escapementlever palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
EscapementLeverMaker.ironStock = 18; EscapementLeverMaker.bronzeStock = 14; EscapementLeverMaker.woodStock = 10; EscapementLeverMaker.leatherStock = 8; EscapementLeverMaker.silverStock = 8; EscapementLeverMaker.goldStock = 6; EscapementLeverMaker.jewelStock = 4; EscapementLeverMaker.pearlStock = 4
EscapementLeverMaker.productStock = {}; EscapementLeverMaker.buildings = {}; EscapementLeverMaker.maker = nil; EscapementLeverMaker.activeMaking = {}; EscapementLeverMaker.totalProducts = 0; EscapementLeverMaker.dayTimer = 0
function EscapementLeverMaker.init() EscapementLeverMaker.ironStock=18; EscapementLeverMaker.bronzeStock=14; EscapementLeverMaker.woodStock=10; EscapementLeverMaker.leatherStock=8; EscapementLeverMaker.silverStock=8; EscapementLeverMaker.goldStock=6; EscapementLeverMaker.jewelStock=4; EscapementLeverMaker.pearlStock=4; EscapementLeverMaker.productStock={}; EscapementLeverMaker.buildings={}; EscapementLeverMaker.maker=nil; EscapementLeverMaker.activeMaking={}; EscapementLeverMaker.totalProducts=0; EscapementLeverMaker.dayTimer=0; print("[EscapementLeverMaker] Royal Escapement Lever Maker System initialized (6 products, 4 buildings)") end
function EscapementLeverMaker.hireMaker(n,s) s=s or math.random(55,90); local c=590+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; EscapementLeverMaker.maker={name=n or ("Uhopar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Uhopar najet: %s (spretnost: %d)",EscapementLeverMaker.maker.name,s),"success") end; return true end
function EscapementLeverMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function EscapementLeverMaker.build(id) local ok,e=EscapementLeverMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(EscapementLeverMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function EscapementLeverMaker.getQualityBonus() local b=0; for _,bd in ipairs(EscapementLeverMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function EscapementLeverMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and EscapementLeverMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and EscapementLeverMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and EscapementLeverMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and EscapementLeverMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and EscapementLeverMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and EscapementLeverMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and EscapementLeverMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and EscapementLeverMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #EscapementLeverMaker.buildings==0 then return false,"Potrebna uhopna delavnica" end; if not EscapementLeverMaker.maker then return false,"Potreben uhopar" end; return true end
function EscapementLeverMaker.make(pt,qty) qty=qty or 1; local ok,e=EscapementLeverMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then EscapementLeverMaker.ironStock=EscapementLeverMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then EscapementLeverMaker.bronzeStock=EscapementLeverMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then EscapementLeverMaker.woodStock=EscapementLeverMaker.woodStock-d.woodCost*qty end; if d.leatherCost then EscapementLeverMaker.leatherStock=EscapementLeverMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then EscapementLeverMaker.silverStock=EscapementLeverMaker.silverStock-d.silverCost*qty end; if d.goldCost then EscapementLeverMaker.goldStock=EscapementLeverMaker.goldStock-d.goldCost*qty end; if d.jewelCost then EscapementLeverMaker.jewelStock=EscapementLeverMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then EscapementLeverMaker.pearlStock=EscapementLeverMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if EscapementLeverMaker.maker then t=math.max(1,t-math.floor(EscapementLeverMaker.maker.skill/13)) end; table.insert(EscapementLeverMaker.activeMaking,{id="escapementlever_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function EscapementLeverMaker.completeMaking(m) local q=1.0+(EscapementLeverMaker.getQualityBonus()/100); if EscapementLeverMaker.maker then q=q+(EscapementLeverMaker.maker.skill/140) end; q=math.min(2.5,q); EscapementLeverMaker.productStock[m.productType]=(EscapementLeverMaker.productStock[m.productType] or 0)+m.quantity; EscapementLeverMaker.totalProducts=EscapementLeverMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if EscapementLeverMaker.maker then EscapementLeverMaker.maker.itemsMade=EscapementLeverMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then EscapementLeverMaker.maker.skill=math.min(100,EscapementLeverMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rocica izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"escapementlever.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function EscapementLeverMaker.update(dt) if not _G.state then return end; EscapementLeverMaker.dayTimer=EscapementLeverMaker.dayTimer+dt; if EscapementLeverMaker.dayTimer>=30 then EscapementLeverMaker.dayTimer=0; for i=#EscapementLeverMaker.activeMaking,1,-1 do local m=EscapementLeverMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then EscapementLeverMaker.completeMaking(m); table.remove(EscapementLeverMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(EscapementLeverMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if EscapementLeverMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function EscapementLeverMaker.getStats() return {ironStock=EscapementLeverMaker.ironStock,bronzeStock=EscapementLeverMaker.bronzeStock,woodStock=EscapementLeverMaker.woodStock,leatherStock=EscapementLeverMaker.leatherStock,silverStock=EscapementLeverMaker.silverStock,goldStock=EscapementLeverMaker.goldStock,jewelStock=EscapementLeverMaker.jewelStock,pearlStock=EscapementLeverMaker.pearlStock,productStock=EscapementLeverMaker.productStock,numBuildings=#EscapementLeverMaker.buildings,hasMaker=EscapementLeverMaker.maker~=nil,makerName=EscapementLeverMaker.maker and EscapementLeverMaker.maker.name or "—",makerSkill=EscapementLeverMaker.maker and EscapementLeverMaker.maker.skill or 0,activeMaking=#EscapementLeverMaker.activeMaking,totalProducts=EscapementLeverMaker.totalProducts} end
return EscapementLeverMaker
