local StitchingAwlMaker = {}
local PRODUCTS = {
    iron_stitching_awl = { name = "Železno šivalno šilo", ironCost = 5, woodCost = 1, leatherCost = 1, time = 5, cost = 175, prestige = 4, happiness = 2, description = "Železno šivalno šilo za vbijanje lukenj v usnje." },
    bronze_stitching_awl = { name = "Bronasto šivalno šilo", bronzeCost = 5, ironCost = 1, woodCost = 1, leatherCost = 1, time = 7, cost = 425, prestige = 6, happiness = 3, description = "Bronasto šivalno šilo za fino vbijanje." },
    silver_stitching_awl = { name = "Srebrno šivalno šilo", silverCost = 5, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 11, cost = 1025, prestige = 11, happiness = 4, description = "Srebrno šivalno šilo za plemiške knjigoveže." },
    gilded_stitching_awl = { name = "Pozlačeno šivalno šilo", goldCost = 1, silverCost = 5, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 15, cost = 2200, prestige = 20, happiness = 5, description = "Pozlačeno šivalno šilo za dvorne knjigoveže." },
    jewel_set_stitching_awl = { name = "Draguljasto šivalno šilo", goldCost = 2, silverCost = 5, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 19, cost = 4750, prestige = 36, happiness = 7, description = "Draguljasto šivalno šilo za kraljevske knjigoveže." },
    royal_sovereign_stitching_awl = { name = "Kraljevski suvereno šivalno šilo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 26, cost = 10200, prestige = 68, happiness = 13, description = "Suvereno šivalno šilo z biseri za krono." },
}
local BUILDINGS = {
    stitchingawl_workshop = { name = "Šilna delavnica", cost = { gold = 355, wood = 175, stone = 140, iron = 10 }, upkeep = 7, qualityBonus = 5 },
    stitchingawl_house = { name = "Šilna hiša", cost = { gold = 1255, wood = 360, stone = 280, silver = 8, iron = 8 }, upkeep = 26, qualityBonus = 18 },
    master_stitchingawl_atelier = { name = "Mojstrski šilni atelje", cost = { gold = 3140, wood = 420, stone = 535, silver = 37, gold = 7 }, upkeep = 74, qualityBonus = 30 },
    sovereign_stitchingawl_palace = { name = "Suverena šilna palača", cost = { gold = 13300, wood = 650, stone = 845, gold = 85, jewel = 19 }, upkeep = 260, qualityBonus = 55, prestigeBonus = 50 },
}
StitchingAwlMaker.ironStock = 18; StitchingAwlMaker.bronzeStock = 14; StitchingAwlMaker.woodStock = 10; StitchingAwlMaker.leatherStock = 10; StitchingAwlMaker.silverStock = 8; StitchingAwlMaker.goldStock = 6; StitchingAwlMaker.jewelStock = 4; StitchingAwlMaker.pearlStock = 4
StitchingAwlMaker.productStock = {}; StitchingAwlMaker.buildings = {}; StitchingAwlMaker.maker = nil; StitchingAwlMaker.activeMaking = {}; StitchingAwlMaker.totalProducts = 0; StitchingAwlMaker.dayTimer = 0
function StitchingAwlMaker.init() StitchingAwlMaker.ironStock=18; StitchingAwlMaker.bronzeStock=14; StitchingAwlMaker.woodStock=10; StitchingAwlMaker.leatherStock=10; StitchingAwlMaker.silverStock=8; StitchingAwlMaker.goldStock=6; StitchingAwlMaker.jewelStock=4; StitchingAwlMaker.pearlStock=4; StitchingAwlMaker.productStock={}; StitchingAwlMaker.buildings={}; StitchingAwlMaker.maker=nil; StitchingAwlMaker.activeMaking={}; StitchingAwlMaker.totalProducts=0; StitchingAwlMaker.dayTimer=0; print("[StitchingAwlMaker] Royal Stitching Awl Maker System initialized (6 products, 4 buildings)") end
function StitchingAwlMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; StitchingAwlMaker.maker={name=n or ("Šilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Šilar najet: %s (spretnost: %d)",StitchingAwlMaker.maker.name,s),"success") end; return true end
function StitchingAwlMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function StitchingAwlMaker.build(id) local ok,e=StitchingAwlMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(StitchingAwlMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function StitchingAwlMaker.getQualityBonus() local b=0; for _,bd in ipairs(StitchingAwlMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function StitchingAwlMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and StitchingAwlMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and StitchingAwlMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and StitchingAwlMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and StitchingAwlMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and StitchingAwlMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and StitchingAwlMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and StitchingAwlMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and StitchingAwlMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #StitchingAwlMaker.buildings==0 then return false,"Potrebna šilna delavnica" end; if not StitchingAwlMaker.maker then return false,"Potreben šilar" end; return true end
function StitchingAwlMaker.make(pt,qty) qty=qty or 1; local ok,e=StitchingAwlMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then StitchingAwlMaker.ironStock=StitchingAwlMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then StitchingAwlMaker.bronzeStock=StitchingAwlMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then StitchingAwlMaker.woodStock=StitchingAwlMaker.woodStock-d.woodCost*qty end; if d.leatherCost then StitchingAwlMaker.leatherStock=StitchingAwlMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then StitchingAwlMaker.silverStock=StitchingAwlMaker.silverStock-d.silverCost*qty end; if d.goldCost then StitchingAwlMaker.goldStock=StitchingAwlMaker.goldStock-d.goldCost*qty end; if d.jewelCost then StitchingAwlMaker.jewelStock=StitchingAwlMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then StitchingAwlMaker.pearlStock=StitchingAwlMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if StitchingAwlMaker.maker then t=math.max(1,t-math.floor(StitchingAwlMaker.maker.skill/13)) end; table.insert(StitchingAwlMaker.activeMaking,{id="stitchingawl_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function StitchingAwlMaker.completeMaking(m) local q=1.0+(StitchingAwlMaker.getQualityBonus()/100); if StitchingAwlMaker.maker then q=q+(StitchingAwlMaker.maker.skill/140) end; q=math.min(2.5,q); StitchingAwlMaker.productStock[m.productType]=(StitchingAwlMaker.productStock[m.productType] or 0)+m.quantity; StitchingAwlMaker.totalProducts=StitchingAwlMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if StitchingAwlMaker.maker then StitchingAwlMaker.maker.itemsMade=StitchingAwlMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then StitchingAwlMaker.maker.skill=math.min(100,StitchingAwlMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Šilo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"stitchingawl.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function StitchingAwlMaker.update(dt) if not _G.state then return end; StitchingAwlMaker.dayTimer=StitchingAwlMaker.dayTimer+dt; if StitchingAwlMaker.dayTimer>=30 then StitchingAwlMaker.dayTimer=0; for i=#StitchingAwlMaker.activeMaking,1,-1 do local m=StitchingAwlMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then StitchingAwlMaker.completeMaking(m); table.remove(StitchingAwlMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(StitchingAwlMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if StitchingAwlMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function StitchingAwlMaker.getStats() return {ironStock=StitchingAwlMaker.ironStock,bronzeStock=StitchingAwlMaker.bronzeStock,woodStock=StitchingAwlMaker.woodStock,leatherStock=StitchingAwlMaker.leatherStock,silverStock=StitchingAwlMaker.silverStock,goldStock=StitchingAwlMaker.goldStock,jewelStock=StitchingAwlMaker.jewelStock,pearlStock=StitchingAwlMaker.pearlStock,productStock=StitchingAwlMaker.productStock,numBuildings=#StitchingAwlMaker.buildings,hasMaker=StitchingAwlMaker.maker~=nil,makerName=StitchingAwlMaker.maker and StitchingAwlMaker.maker.name or "—",makerSkill=StitchingAwlMaker.maker and StitchingAwlMaker.maker.skill or 0,activeMaking=#StitchingAwlMaker.activeMaking,totalProducts=StitchingAwlMaker.totalProducts} end
return StitchingAwlMaker
