local TwineMaker = {}
local PRODUCTS = {
    iron_twine = { name = "Železni špigelj", ironCost = 1, woodCost = 1, leatherCost = 3, time = 4, cost = 130, prestige = 3, happiness = 2, description = "Železni špigelj za pakiranje." },
    bronze_twine = { name = "Bronast špigelj", bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 3, time = 6, cost = 320, prestige = 5, happiness = 3, description = "Bronast špigelj za vezanje." },
    silver_twine = { name = "Srebrni špigelj", silverCost = 1, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 3, time = 10, cost = 780, prestige = 10, happiness = 4, description = "Srebrni špigelj za plemiške potrebe." },
    gilded_twine = { name = "Pozlačeni špigelj", goldCost = 1, silverCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 3, time = 14, cost = 1700, prestige = 19, happiness = 5, description = "Pozlačeni špigelj za dvorne potrebe." },
    jewel_set_twine = { name = "Draguljasti špigelj", goldCost = 2, silverCost = 1, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 3, time = 18, cost = 3700, prestige = 35, happiness = 7, description = "Draguljasti špigelj za kraljeve potrebe." },
    royal_sovereign_twine = { name = "Kraljevski suvereni špigelj", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 4, time = 25, cost = 8000, prestige = 67, happiness = 13, description = "Suvereni špigelj z biseri za krono." },
}
local BUILDINGS = {
    twine_workshop = { name = "Špigeljna delavnica", cost = { gold = 290, wood = 175, stone = 120, iron = 5 }, upkeep = 5, qualityBonus = 5 },
    twine_house = { name = "Špigeljna hiša", cost = { gold = 1080, wood = 350, stone = 250, silver = 6, iron = 6 }, upkeep = 23, qualityBonus = 18 },
    master_twine_atelier = { name = "Mojstrski špigeljni atelje", cost = { gold = 2850, wood = 410, stone = 490, silver = 32, gold = 6 }, upkeep = 67, qualityBonus = 30 },
    sovereign_twine_palace = { name = "Suverena špigeljna palača", cost = { gold = 12400, wood = 640, stone = 800, gold = 79, jewel = 18 }, upkeep = 245, qualityBonus = 55, prestigeBonus = 50 },
}
TwineMaker.ironStock = 8; TwineMaker.bronzeStock = 6; TwineMaker.woodStock = 14; TwineMaker.leatherStock = 16; TwineMaker.silverStock = 8; TwineMaker.goldStock = 6; TwineMaker.jewelStock = 4; TwineMaker.pearlStock = 4
TwineMaker.productStock = {}; TwineMaker.buildings = {}; TwineMaker.maker = nil; TwineMaker.activeMaking = {}; TwineMaker.totalProducts = 0; TwineMaker.dayTimer = 0
function TwineMaker.init() TwineMaker.ironStock=8; TwineMaker.bronzeStock=6; TwineMaker.woodStock=14; TwineMaker.leatherStock=16; TwineMaker.silverStock=8; TwineMaker.goldStock=6; TwineMaker.jewelStock=4; TwineMaker.pearlStock=4; TwineMaker.productStock={}; TwineMaker.buildings={}; TwineMaker.maker=nil; TwineMaker.activeMaking={}; TwineMaker.totalProducts=0; TwineMaker.dayTimer=0; print("[TwineMaker] Royal Twine Maker System initialized (6 products, 4 buildings)") end
function TwineMaker.hireMaker(n,s) s=s or math.random(55,90); local c=560+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TwineMaker.maker={name=n or ("Špigeljar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Špigeljar najet: %s (spretnost: %d)",TwineMaker.maker.name,s),"success") end; return true end
function TwineMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TwineMaker.build(id) local ok,e=TwineMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TwineMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TwineMaker.getQualityBonus() local b=0; for _,bd in ipairs(TwineMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TwineMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and TwineMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and TwineMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and TwineMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and TwineMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and TwineMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and TwineMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and TwineMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and TwineMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #TwineMaker.buildings==0 then return false,"Potrebna špigeljna delavnica" end; if not TwineMaker.maker then return false,"Potreben špigeljar" end; return true end
function TwineMaker.make(pt,qty) qty=qty or 1; local ok,e=TwineMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then TwineMaker.ironStock=TwineMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then TwineMaker.bronzeStock=TwineMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then TwineMaker.woodStock=TwineMaker.woodStock-d.woodCost*qty end; if d.leatherCost then TwineMaker.leatherStock=TwineMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then TwineMaker.silverStock=TwineMaker.silverStock-d.silverCost*qty end; if d.goldCost then TwineMaker.goldStock=TwineMaker.goldStock-d.goldCost*qty end; if d.jewelCost then TwineMaker.jewelStock=TwineMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then TwineMaker.pearlStock=TwineMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if TwineMaker.maker then t=math.max(1,t-math.floor(TwineMaker.maker.skill/13)) end; table.insert(TwineMaker.activeMaking,{id="twine_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TwineMaker.completeMaking(m) local q=1.0+(TwineMaker.getQualityBonus()/100); if TwineMaker.maker then q=q+(TwineMaker.maker.skill/140) end; q=math.min(2.5,q); TwineMaker.productStock[m.productType]=(TwineMaker.productStock[m.productType] or 0)+m.quantity; TwineMaker.totalProducts=TwineMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if TwineMaker.maker then TwineMaker.maker.itemsMade=TwineMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then TwineMaker.maker.skill=math.min(100,TwineMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Špigelj izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"twine.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function TwineMaker.update(dt) if not _G.state then return end; TwineMaker.dayTimer=TwineMaker.dayTimer+dt; if TwineMaker.dayTimer>=30 then TwineMaker.dayTimer=0; for i=#TwineMaker.activeMaking,1,-1 do local m=TwineMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TwineMaker.completeMaking(m); table.remove(TwineMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TwineMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TwineMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TwineMaker.getStats() return {ironStock=TwineMaker.ironStock,bronzeStock=TwineMaker.bronzeStock,woodStock=TwineMaker.woodStock,leatherStock=TwineMaker.leatherStock,silverStock=TwineMaker.silverStock,goldStock=TwineMaker.goldStock,jewelStock=TwineMaker.jewelStock,pearlStock=TwineMaker.pearlStock,productStock=TwineMaker.productStock,numBuildings=#TwineMaker.buildings,hasMaker=TwineMaker.maker~=nil,makerName=TwineMaker.maker and TwineMaker.maker.name or "—",makerSkill=TwineMaker.maker and TwineMaker.maker.skill or 0,activeMaking=#TwineMaker.activeMaking,totalProducts=TwineMaker.totalProducts} end
return TwineMaker
