local SandMullerMaker = {}
local PRODUCTS = {
    iron_sandmuller = { name = "Železni mešalec livarskega peska", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni mešalec livarskega peska za livarje." },
    bronze_sandmuller = { name = "Bronast mešalec livarskega peska", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast mešalec livarskega peska za livarje." },
    silver_sandmuller = { name = "Srebrn mešalec livarskega peska", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn mešalec livarskega peska za livarje." },
    gilded_sandmuller = { name = "Pozlačen mešalec livarskega peska", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen mešalec livarskega peska za livarje." },
    jewel_set_sandmuller = { name = "Draguljast mešalec livarskega peska", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast mešalec livarskega peska za livarje." },
    royal_sovereign_sandmuller = { name = "Kraljevski suveren mešalec livarskega peska", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren mešalec livarskega peska z biseri za krono." },
}
local BUILDINGS = {
    sandmuller_workshop = { name = "Sandmuller delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    sandmuller_house = { name = "Sandmuller hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_sandmuller_atelier = { name = "Mojstrski sandmuller atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_sandmuller_palace = { name = "Suverena sandmuller palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SandMullerMaker.ironStock=18; SandMullerMaker.bronzeStock=14; SandMullerMaker.woodStock=10; SandMullerMaker.leatherStock=8; SandMullerMaker.silverStock=8; SandMullerMaker.goldStock=6; SandMullerMaker.jewelStock=4; SandMullerMaker.pearlStock=4
SandMullerMaker.productStock = {}; SandMullerMaker.buildings = {}; SandMullerMaker.maker = nil; SandMullerMaker.activeMaking = {}; SandMullerMaker.totalProducts = 0; SandMullerMaker.dayTimer = 0
function SandMullerMaker.init() SandMullerMaker.ironStock=18; SandMullerMaker.bronzeStock=14; SandMullerMaker.woodStock=10; SandMullerMaker.leatherStock=8; SandMullerMaker.silverStock=8; SandMullerMaker.goldStock=6; SandMullerMaker.jewelStock=4; SandMullerMaker.pearlStock=4; SandMullerMaker.productStock={}; SandMullerMaker.buildings={}; SandMullerMaker.maker=nil; SandMullerMaker.activeMaking={}; SandMullerMaker.totalProducts=0; SandMullerMaker.dayTimer=0; print("[SandMullerMaker] Royal Sand Muller Maker System initialized (6 products, 4 buildings)") end
function SandMullerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SandMullerMaker.maker={name=n or ("Mešač "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mešač najet: %s (spretnost: %d)",SandMullerMaker.maker.name,s),"success") end; return true end
function SandMullerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SandMullerMaker.build(id) local ok,e=SandMullerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SandMullerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SandMullerMaker.getQualityBonus() local b=0; for _,bd in ipairs(SandMullerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SandMullerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SandMullerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SandMullerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SandMullerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SandMullerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SandMullerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SandMullerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SandMullerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SandMullerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SandMullerMaker.buildings==0 then return false,"Potrebna mešalna delavnica" end; if not SandMullerMaker.maker then return false,"Potreben mešač" end; return true end
function SandMullerMaker.make(pt,qty) qty=qty or 1; local ok,e=SandMullerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SandMullerMaker.ironStock=SandMullerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SandMullerMaker.bronzeStock=SandMullerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SandMullerMaker.woodStock=SandMullerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SandMullerMaker.leatherStock=SandMullerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SandMullerMaker.silverStock=SandMullerMaker.silverStock-d.silverCost*qty end; if d.goldCost then SandMullerMaker.goldStock=SandMullerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SandMullerMaker.jewelStock=SandMullerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SandMullerMaker.pearlStock=SandMullerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SandMullerMaker.maker then t=math.max(1,t-math.floor(SandMullerMaker.maker.skill/13)) end; table.insert(SandMullerMaker.activeMaking,{id="sandmuller_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SandMullerMaker.completeMaking(m) local q=1.0+(SandMullerMaker.getQualityBonus()/100); if SandMullerMaker.maker then q=q+(SandMullerMaker.maker.skill/140) end; q=math.min(2.5,q); SandMullerMaker.productStock[m.productType]=(SandMullerMaker.productStock[m.productType] or 0)+m.quantity; SandMullerMaker.totalProducts=SandMullerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SandMullerMaker.maker then SandMullerMaker.maker.itemsMade=SandMullerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SandMullerMaker.maker.skill=math.min(100,SandMullerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mešač izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sandmuller.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SandMullerMaker.update(dt) if not _G.state then return end; SandMullerMaker.dayTimer=SandMullerMaker.dayTimer+dt; if SandMullerMaker.dayTimer>=30 then SandMullerMaker.dayTimer=0; for i=#SandMullerMaker.activeMaking,1,-1 do local m=SandMullerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SandMullerMaker.completeMaking(m); table.remove(SandMullerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SandMullerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SandMullerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SandMullerMaker.getStats() return {ironStock=SandMullerMaker.ironStock,bronzeStock=SandMullerMaker.bronzeStock,woodStock=SandMullerMaker.woodStock,leatherStock=SandMullerMaker.leatherStock,silverStock=SandMullerMaker.silverStock,goldStock=SandMullerMaker.goldStock,jewelStock=SandMullerMaker.jewelStock,pearlStock=SandMullerMaker.pearlStock,productStock=SandMullerMaker.productStock,numBuildings=#SandMullerMaker.buildings,hasMaker=SandMullerMaker.maker~=nil,makerName=SandMullerMaker.maker and SandMullerMaker.maker.name or "—",makerSkill=SandMullerMaker.maker and SandMullerMaker.maker.skill or 0,activeMaking=#SandMullerMaker.activeMaking,totalProducts=SandMullerMaker.totalProducts} end
return SandMullerMaker
