local MicroscopeMaker = {}
local PRODUCTS = {
    brass_microscope = { name = "Medeninast mikroskop", brassCost = 2, glassCost = 2, time = 6, cost = 110, magnification = 40, prestige = 5, description = "Medeninast mikroskop za zdravnike." },
    silver_microscope = { name = "Srebrn mikroskop", silverCost = 2, glassCost = 2, brassCost = 1, time = 8, cost = 280, magnification = 60, prestige = 10, happiness = 1, description = "Srebrn mikroskop za učenjake." },
    engraved_microscope = { name = "Vgraviran mikroskop", silverCost = 2, goldCost = 1, glassCost = 2, brassCost = 1, time = 11, cost = 620, magnification = 78, prestige = 16, happiness = 2, description = "Vgraviran mikroskop za zdravnike." },
    silver_stage_microscope = { name = "Srebrnomizni mikroskop", silverCost = 2, goldCost = 1, glassCost = 2, brassCost = 1, time = 14, cost = 1200, magnification = 88, prestige = 24, happiness = 4, description = "Mikroskop s srebrnim mmizom za plemiče." },
    gold_stage_microscope = { name = "Zlatomizni mikroskop", goldCost = 2, silverCost = 1, glassCost = 2, jewelCost = 1, time = 18, cost = 2400, magnification = 95, prestige = 36, happiness = 7, description = "Mikroskop z zlatim mizom za visoke plemiče." },
    royal_grand_microscope = { name = "Kraljevski veliki mikroskop", goldCost = 3, silverCost = 2, jewelCost = 2, pearlCost = 1, glassCost = 2, time = 24, cost = 4800, magnification = 100, prestige = 65, happiness = 14, description = "Veliki kraljevski mikroskop z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Mikroskopska delavnica", cost = { gold = 380, wood = 140, stone = 300 }, upkeep = 10, qualityBonus = 5 },
    lens_grinding_room = { name = "Lečna brusilnica", cost = { gold = 1300, wood = 300, stone = 600, glass = 8 }, upkeep = 32, qualityBonus = 18 },
    calibration_room = { name = "Kalibrirnica", cost = { gold = 3000, wood = 400, stone = 900, silver = 50, steel = 8 }, upkeep = 75, qualityBonus = 30 },
    royal_microscope_atelier = { name = "Kraljevski atelje mikroskopov", cost = { gold = 13000, wood = 700, stone = 1300, gold = 80, jewel = 25 }, upkeep = 260, qualityBonus = 55, prestigeBonus = 55 },
}
MicroscopeMaker.brassStock = 14; MicroscopeMaker.glassStock = 14; MicroscopeMaker.silverStock = 8; MicroscopeMaker.goldStock = 6; MicroscopeMaker.jewelStock = 6; MicroscopeMaker.pearlStock = 4
MicroscopeMaker.productStock = {}; MicroscopeMaker.buildings = {}; MicroscopeMaker.maker = nil; MicroscopeMaker.activeMaking = {}; MicroscopeMaker.totalProducts = 0; MicroscopeMaker.dayTimer = 0
function MicroscopeMaker.init() MicroscopeMaker.brassStock=14; MicroscopeMaker.glassStock=14; MicroscopeMaker.silverStock=8; MicroscopeMaker.goldStock=6; MicroscopeMaker.jewelStock=6; MicroscopeMaker.pearlStock=4; MicroscopeMaker.productStock={}; MicroscopeMaker.buildings={}; MicroscopeMaker.maker=nil; MicroscopeMaker.activeMaking={}; MicroscopeMaker.totalProducts=0; MicroscopeMaker.dayTimer=0; print("[MicroscopeMaker] Royal Microscope Maker System initialized (6 products, 4 buildings)") end
function MicroscopeMaker.hireMaker(n,s) s=s or math.random(55,90); local c=620+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MicroscopeMaker.maker={name=n or ("Mikroskopar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mikroskopar najet: %s (spretnost: %d)",MicroscopeMaker.maker.name,s),"success") end; return true end
function MicroscopeMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MicroscopeMaker.build(id) local ok,e=MicroscopeMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MicroscopeMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MicroscopeMaker.getQualityBonus() local b=0; for _,bd in ipairs(MicroscopeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MicroscopeMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.brassCost and MicroscopeMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.glassCost and MicroscopeMaker.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.silverCost and MicroscopeMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MicroscopeMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MicroscopeMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MicroscopeMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MicroscopeMaker.buildings==0 then return false,"Potrebna delavnica" end; if not MicroscopeMaker.maker then return false,"Potreben mikroskopar" end; return true end
function MicroscopeMaker.make(pt,qty) qty=qty or 1; local ok,e=MicroscopeMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.brassCost then MicroscopeMaker.brassStock=MicroscopeMaker.brassStock-d.brassCost*qty end; if d.glassCost then MicroscopeMaker.glassStock=MicroscopeMaker.glassStock-d.glassCost*qty end; if d.silverCost then MicroscopeMaker.silverStock=MicroscopeMaker.silverStock-d.silverCost*qty end; if d.goldCost then MicroscopeMaker.goldStock=MicroscopeMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MicroscopeMaker.jewelStock=MicroscopeMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MicroscopeMaker.pearlStock=MicroscopeMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MicroscopeMaker.maker then t=math.max(1,t-math.floor(MicroscopeMaker.maker.skill/12)) end; table.insert(MicroscopeMaker.activeMaking,{id="microscope_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,magnification=d.magnification or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MicroscopeMaker.completeMaking(m) local q=1.0+(MicroscopeMaker.getQualityBonus()/100); if MicroscopeMaker.maker then q=q+(MicroscopeMaker.maker.skill/150) end; q=math.min(2.5,q); MicroscopeMaker.productStock[m.productType]=(MicroscopeMaker.productStock[m.productType] or 0)+m.quantity; MicroscopeMaker.totalProducts=MicroscopeMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MicroscopeMaker.maker then MicroscopeMaker.maker.itemsMade=MicroscopeMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MicroscopeMaker.maker.skill=math.min(100,MicroscopeMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mikroskop izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"microscope.completed",{productName=m.productName,magnification=m.magnification,prestige=m.prestige,happiness=m.happiness}) end end
function MicroscopeMaker.update(dt) if not _G.state then return end; MicroscopeMaker.dayTimer=MicroscopeMaker.dayTimer+dt; if MicroscopeMaker.dayTimer>=30 then MicroscopeMaker.dayTimer=0; for i=#MicroscopeMaker.activeMaking,1,-1 do local m=MicroscopeMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MicroscopeMaker.completeMaking(m); table.remove(MicroscopeMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MicroscopeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MicroscopeMaker.maker then tu=tu+22 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MicroscopeMaker.getStats() return {brassStock=MicroscopeMaker.brassStock,glassStock=MicroscopeMaker.glassStock,silverStock=MicroscopeMaker.silverStock,goldStock=MicroscopeMaker.goldStock,jewelStock=MicroscopeMaker.jewelStock,pearlStock=MicroscopeMaker.pearlStock,productStock=MicroscopeMaker.productStock,numBuildings=#MicroscopeMaker.buildings,hasMaker=MicroscopeMaker.maker~=nil,makerName=MicroscopeMaker.maker and MicroscopeMaker.maker.name or "—",makerSkill=MicroscopeMaker.maker and MicroscopeMaker.maker.skill or 0,activeMaking=#MicroscopeMaker.activeMaking,totalProducts=MicroscopeMaker.totalProducts} end
return MicroscopeMaker
