local CofferMaker = {}
local PRODUCTS = {
    pine_lockbox = { name = "Borova skrinjica", woodCost = 1, ironCost = 1, time = 1, cost = 8, capacity = 50, description = "Preprosta borova skrinjica z železnim okovjem." },
    oak_coffer = { name = "Hrastova skrinja", woodCost = 2, ironCost = 1, time = 2, cost = 22, capacity = 100, prestige = 1, description = "Hrastova skrinja z okovjem za shranjevanje." },
    ironbound_chest = { name = "Železno okovana skrinja", woodCost = 2, ironCost = 2, time = 3, cost = 55, capacity = 200, prestige = 2, description = "Trda skrinja z obilnim železnim okovjem." },
    cedar_wardrobe = { name = "Cedrova omara", woodCost = 3, time = 4, cost = 110, capacity = 350, prestige = 5, description = "Cedrova omara proti moljem za kraljevske halje." },
    silver_trimmed_coffer = { name = "Srebrno obrobljena skrinja", woodCost = 3, silverCost = 1, ironCost = 1, time = 5, cost = 200, capacity = 500, prestige = 9, happiness = 1, description = "Srebrno obrobljena skrinja z dragocenim videzom." },
    royal_treasure_coffer = { name = "Kraljevski zakladniški zaboj", woodCost = 5, goldCost = 2, silverCost = 2, ironCost = 2, jewelCost = 1, time = 8, cost = 600, capacity = 1000, prestige = 25, happiness = 5, description = "Veliki zakladniški zaboj z zlatimi in srebrnimi okraski ter dragulji." },
}
local BUILDINGS = {
    workshop = { name = "Skrinjarska delavnica", cost = { gold = 200, wood = 120 }, upkeep = 5, qualityBonus = 5 },
    carpentry = { name = "Mizarski atelje", cost = { gold = 650, wood = 250, stone = 120 }, upkeep = 16, qualityBonus = 15 },
    iron_works = { name = "Železarna", cost = { gold = 1100, wood = 250, stone = 250, iron = 25 }, upkeep = 26, qualityBonus = 22 },
    royal_coffer_atelier = { name = "Kraljevski atelje skrinj", cost = { gold = 3500, wood = 500, stone = 500, gold = 30 }, upkeep = 65, qualityBonus = 38, prestigeBonus = 18 },
}
CofferMaker.woodStock = 26; CofferMaker.ironStock = 12; CofferMaker.silverStock = 4; CofferMaker.goldStock = 3; CofferMaker.jewelStock = 3
CofferMaker.productStock = {}; CofferMaker.buildings = {}; CofferMaker.maker = nil; CofferMaker.activeMaking = {}; CofferMaker.totalProducts = 0; CofferMaker.dayTimer = 0
function CofferMaker.init() CofferMaker.woodStock=26; CofferMaker.ironStock=12; CofferMaker.silverStock=4; CofferMaker.goldStock=3; CofferMaker.jewelStock=3; CofferMaker.productStock={}; CofferMaker.buildings={}; CofferMaker.maker=nil; CofferMaker.activeMaking={}; CofferMaker.totalProducts=0; CofferMaker.dayTimer=0; print("[CofferMaker] Royal Coffer & Lockbox System initialized (6 products, 4 buildings)") end
function CofferMaker.hireMaker(n,s) s=s or math.random(35,80); local c=260+s*5; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CofferMaker.maker={name=n or ("Skrinjar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Skrinjar najet: %s (spretnost: %d)",CofferMaker.maker.name,s),"success") end; return true end
function CofferMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CofferMaker.build(id) local ok,e=CofferMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CofferMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CofferMaker.getQualityBonus() local b=0; for _,bd in ipairs(CofferMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CofferMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and CofferMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and CofferMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.silverCost and CofferMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CofferMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CofferMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #CofferMaker.buildings==0 then return false,"Potrebna delavnica" end; if not CofferMaker.maker then return false,"Potreben skrinjar" end; return true end
function CofferMaker.make(pt,qty) qty=qty or 5; local ok,e=CofferMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then CofferMaker.woodStock=CofferMaker.woodStock-d.woodCost*qty end; if d.ironCost then CofferMaker.ironStock=CofferMaker.ironStock-d.ironCost*qty end; if d.silverCost then CofferMaker.silverStock=CofferMaker.silverStock-d.silverCost*qty end; if d.goldCost then CofferMaker.goldStock=CofferMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CofferMaker.jewelStock=CofferMaker.jewelStock-d.jewelCost*qty end; local t=d.time; if CofferMaker.maker then t=math.max(1,t-math.floor(CofferMaker.maker.skill/15)) end; table.insert(CofferMaker.activeMaking,{id="coffer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,capacity=d.capacity or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CofferMaker.completeMaking(m) local q=1.0+(CofferMaker.getQualityBonus()/100); if CofferMaker.maker then q=q+(CofferMaker.maker.skill/200) end; q=math.min(2.0,q); CofferMaker.productStock[m.productType]=(CofferMaker.productStock[m.productType] or 0)+m.quantity; CofferMaker.totalProducts=CofferMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CofferMaker.maker then CofferMaker.maker.itemsMade=CofferMaker.maker.itemsMade+m.quantity; if math.random()<0.15 then CofferMaker.maker.skill=math.min(100,CofferMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Skrinje izdelane: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end end
function CofferMaker.update(dt) if not _G.state then return end; CofferMaker.dayTimer=CofferMaker.dayTimer+dt; if CofferMaker.dayTimer>=30 then CofferMaker.dayTimer=0; for i=#CofferMaker.activeMaking,1,-1 do local m=CofferMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CofferMaker.completeMaking(m); table.remove(CofferMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CofferMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CofferMaker.maker then tu=tu+8 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CofferMaker.getStats() return {woodStock=CofferMaker.woodStock,ironStock=CofferMaker.ironStock,silverStock=CofferMaker.silverStock,goldStock=CofferMaker.goldStock,jewelStock=CofferMaker.jewelStock,productStock=CofferMaker.productStock,numBuildings=#CofferMaker.buildings,hasMaker=CofferMaker.maker~=nil,makerName=CofferMaker.maker and CofferMaker.maker.name or "—",makerSkill=CofferMaker.maker and CofferMaker.maker.skill or 0,activeMaking=#CofferMaker.activeMaking,totalProducts=CofferMaker.totalProducts} end
return CofferMaker
