local PlateCuirassSmith = {}
local PRODUCTS = {
    simple_iron_cuirass = { name = "Preprost železni oklep", ironCost = 5, leatherCost = 1, time = 7, cost = 280, defense = 38, happiness = 1, description = "Preprost železni oklep za vojake." },
    steel_breastplate = { name = "Jekleni prsni oklep", ironCost = 4, steelCost = 3, leatherCost = 1, time = 10, cost = 680, defense = 52, happiness = 2, prestige = 4, description = "Jekleni prsni oklep za viteze." },
    silver_embossed_cuirass = { name = "Srebrnoizbočeni oklep", ironCost = 4, steelCost = 2, silverCost = 2, leatherCost = 1, time = 13, cost = 1400, defense = 64, happiness = 2, prestige = 10, description = "Srebrnoizbočeni oklep za plemiške viteze." },
    gold_trimmed_cuirass = { name = "Zlatookrasni oklep", ironCost = 4, steelCost = 2, goldCost = 2, silverCost = 1, leatherCost = 1, time = 17, cost = 3000, defense = 76, happiness = 3, prestige = 22, description = "Zlatookrasni oklep za visoke plemiče." }
    , jewel_set_cuirass = { name = "Draguljasta oklep", ironCost = 4, steelCost = 2, goldCost = 2, silverCost = 1, leatherCost = 1, jewelCost = 1, time = 21, cost = 6000, defense = 86, happiness = 5, prestige = 38, description = "Oklep z draguljem za visoko plemstvo." },
    royal_grand_cuirass = { name = "Kraljevski veliki oklep", ironCost = 6, steelCost = 3, goldCost = 3, silverCost = 2, leatherCost = 1, jewelCost = 2, pearlCost = 2, time = 28, cost = 11000, defense = 98, happiness = 12, prestige = 68, description = "Veliki kraljevski oklep z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    cuirass_workshop = { name = "Oklepna delavnica", cost = { gold = 320, wood = 120, stone = 160, iron = 8 }, upkeep = 7, qualityBonus = 5 },
    plate_loft = { name = "Ploščna podstrešje", cost = { gold = 1200, wood = 280, stone = 360, steel = 6, leather = 6 }, upkeep = 28, qualityBonus = 18 },
    master_platesmith_atelier = { name = "Mojstrski ploščarski atelje", cost = { gold = 3200, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 75, qualityBonus = 30 },
    royal_plate_palace = { name = "Kraljevska oklepna palača", cost = { gold = 13500, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 270, qualityBonus = 55, prestigeBonus = 50 },
}
PlateCuirassSmith.ironStock = 20; PlateCuirassSmith.steelStock = 14; PlateCuirassSmith.leatherStock = 10; PlateCuirassSmith.silverStock = 8; PlateCuirassSmith.goldStock = 6; PlateCuirassSmith.jewelStock = 4; PlateCuirassSmith.pearlStock = 4
PlateCuirassSmith.productStock = {}; PlateCuirassSmith.buildings = {}; PlateCuirassSmith.maker = nil; PlateCuirassSmith.activeMaking = {}; PlateCuirassSmith.totalProducts = 0; PlateCuirassSmith.dayTimer = 0
function PlateCuirassSmith.init() PlateCuirassSmith.ironStock=20; PlateCuirassSmith.steelStock=14; PlateCuirassSmith.leatherStock=10; PlateCuirassSmith.silverStock=8; PlateCuirassSmith.goldStock=6; PlateCuirassSmith.jewelStock=4; PlateCuirassSmith.pearlStock=4; PlateCuirassSmith.productStock={}; PlateCuirassSmith.buildings={}; PlateCuirassSmith.maker=nil; PlateCuirassSmith.activeMaking={}; PlateCuirassSmith.totalProducts=0; PlateCuirassSmith.dayTimer=0; print("[PlateCuirassSmith] Royal Plate Cuirass Smith System initialized (6 products, 4 buildings)") end
function PlateCuirassSmith.hireMaker(n,s) s=s or math.random(55,90); local c=620+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PlateCuirassSmith.maker={name=n or ("Oklepar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Oklepar najet: %s (spretnost: %d)",PlateCuirassSmith.maker.name,s),"success") end; return true end
function PlateCuirassSmith.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PlateCuirassSmith.build(id) local ok,e=PlateCuirassSmith.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PlateCuirassSmith.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PlateCuirassSmith.getQualityBonus() local b=0; for _,bd in ipairs(PlateCuirassSmith.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PlateCuirassSmith.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PlateCuirassSmith.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and PlateCuirassSmith.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.leatherCost and PlateCuirassSmith.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PlateCuirassSmith.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PlateCuirassSmith.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PlateCuirassSmith.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PlateCuirassSmith.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PlateCuirassSmith.buildings==0 then return false,"Potrebna oklepna delavnica" end; if not PlateCuirassSmith.maker then return false,"Potreben oklepar" end; return true end
function PlateCuirassSmith.make(pt,qty) qty=qty or 1; local ok,e=PlateCuirassSmith.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PlateCuirassSmith.ironStock=PlateCuirassSmith.ironStock-d.ironCost*qty end; if d.steelCost then PlateCuirassSmith.steelStock=PlateCuirassSmith.steelStock-d.steelCost*qty end; if d.leatherCost then PlateCuirassSmith.leatherStock=PlateCuirassSmith.leatherStock-d.leatherCost*qty end; if d.silverCost then PlateCuirassSmith.silverStock=PlateCuirassSmith.silverStock-d.silverCost*qty end; if d.goldCost then PlateCuirassSmith.goldStock=PlateCuirassSmith.goldStock-d.goldCost*qty end; if d.jewelCost then PlateCuirassSmith.jewelStock=PlateCuirassSmith.jewelStock-d.jewelCost*qty end; if d.pearlCost then PlateCuirassSmith.pearlStock=PlateCuirassSmith.pearlStock-d.pearlCost*qty end; local t=d.time; if PlateCuirassSmith.maker then t=math.max(1,t-math.floor(PlateCuirassSmith.maker.skill/12)) end; table.insert(PlateCuirassSmith.activeMaking,{id="cuirass_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,defense=d.defense or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PlateCuirassSmith.completeMaking(m) local q=1.0+(PlateCuirassSmith.getQualityBonus()/100); if PlateCuirassSmith.maker then q=q+(PlateCuirassSmith.maker.skill/140) end; q=math.min(2.5,q); PlateCuirassSmith.productStock[m.productType]=(PlateCuirassSmith.productStock[m.productType] or 0)+m.quantity; PlateCuirassSmith.totalProducts=PlateCuirassSmith.totalProducts+m.quantity; if m.defense>0 and _G.state then _G.state.defense=(_G.state.defense or 0)+m.defense end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PlateCuirassSmith.maker then PlateCuirassSmith.maker.itemsMade=PlateCuirassSmith.maker.itemsMade+m.quantity; if math.random()<0.25 then PlateCuirassSmith.maker.skill=math.min(100,PlateCuirassSmith.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Oklep izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"cuirass.completed",{productName=m.productName,defense=m.defense,prestige=m.prestige,happiness=m.happiness}) end end
function PlateCuirassSmith.update(dt) if not _G.state then return end; PlateCuirassSmith.dayTimer=PlateCuirassSmith.dayTimer+dt; if PlateCuirassSmith.dayTimer>=30 then PlateCuirassSmith.dayTimer=0; for i=#PlateCuirassSmith.activeMaking,1,-1 do local m=PlateCuirassSmith.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PlateCuirassSmith.completeMaking(m); table.remove(PlateCuirassSmith.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PlateCuirassSmith.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PlateCuirassSmith.maker then tu=tu+17 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PlateCuirassSmith.getStats() return {ironStock=PlateCuirassSmith.ironStock,steelStock=PlateCuirassSmith.steelStock,leatherStock=PlateCuirassSmith.leatherStock,silverStock=PlateCuirassSmith.silverStock,goldStock=PlateCuirassSmith.goldStock,jewelStock=PlateCuirassSmith.jewelStock,pearlStock=PlateCuirassSmith.pearlStock,productStock=PlateCuirassSmith.productStock,numBuildings=#PlateCuirassSmith.buildings,hasMaker=PlateCuirassSmith.maker~=nil,makerName=PlateCuirassSmith.maker and PlateCuirassSmith.maker.name or "—",makerSkill=PlateCuirassSmith.maker and PlateCuirassSmith.maker.skill or 0,activeMaking=#PlateCuirassSmith.activeMaking,totalProducts=PlateCuirassSmith.totalProducts} end
return PlateCuirassSmith
