local ConfectionOvenMaker = {}
local PRODUCTS = {
    simple_brick_confection_oven = { name = "Preprosta opečna peč za sladice", brickCost = 3, ironCost = 1, time = 5, cost = 180, food = 12, happiness = 1, description = "Preprosta opečna peč za peko sladic." }
    , iron_reinforced_oven = { name = "Železnookrepljena peč", brickCost = 2, ironCost = 2, steelCost = 1, time = 8, cost = 440, food = 20, happiness = 2, prestige = 2, description = "Železnookrepljena peč za trgovce." },
    silver_trimmed_oven = { name = "Srebrnoobrobljena peč", brickCost = 2, ironCost = 2, silverCost = 1, steelCost = 1, time = 12, cost = 1000, food = 32, happiness = 2, prestige = 6, description = "Srebrnoobrobljena peč za plemiče." },
    gold_trimmed_oven = { name = "Zlatookrasna peč", brickCost = 2, ironCost = 2, goldCost = 1, silverCost = 1, steelCost = 1, time = 16, cost = 2300, food = 45, happiness = 3, prestige = 14, description = "Zlatookrasna peč za visoke plemiče." },
    jewel_set_oven = { name = "Draguljasta peč", brickCost = 2, ironCost = 2, goldCost = 1, silverCost = 1, steelCost = 1, jewelCost = 1, time = 20, cost = 4800, food = 60, happiness = 5, prestige = 27, description = "Peč z draguljem za visoko plemstvo." },
    royal_grand_confection_oven = { name = "Kraljevski veliki peč za sladice", brickCost = 3, ironCost = 3, goldCost = 2, silverCost = 2, steelCost = 1, jewelCost = 2, pearlCost = 2, time = 27, cost = 10000, food = 80, happiness = 12, prestige = 58, description = "Veliki kraljevski peč za sladice z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    oven_workshop = { name = "Pečna delavnica", cost = { gold = 300, wood = 140, stone = 160, iron = 6 }, upkeep = 7, qualityBonus = 5 },
    bakery_loft = { name = "Pekovska podstrešje", cost = { gold = 1100, wood = 280, stone = 320, silver = 6, steel = 4 }, upkeep = 26, qualityBonus = 18 },
    master_baker_atelier = { name = "Mojstrski pekovski atelje", cost = { gold = 2800, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_bakery_palace = { name = "Kraljevska pekovska palača", cost = { gold = 12000, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
ConfectionOvenMaker.brickStock = 18; ConfectionOvenMaker.ironStock = 14; ConfectionOvenMaker.steelStock = 8; ConfectionOvenMaker.silverStock = 6; ConfectionOvenMaker.goldStock = 6; ConfectionOvenMaker.jewelStock = 4; ConfectionOvenMaker.pearlStock = 4
ConfectionOvenMaker.productStock = {}; ConfectionOvenMaker.buildings = {}; ConfectionOvenMaker.maker = nil; ConfectionOvenMaker.activeMaking = {}; ConfectionOvenMaker.totalProducts = 0; ConfectionOvenMaker.dayTimer = 0
function ConfectionOvenMaker.init() ConfectionOvenMaker.brickStock=18; ConfectionOvenMaker.ironStock=14; ConfectionOvenMaker.steelStock=8; ConfectionOvenMaker.silverStock=6; ConfectionOvenMaker.goldStock=6; ConfectionOvenMaker.jewelStock=4; ConfectionOvenMaker.pearlStock=4; ConfectionOvenMaker.productStock={}; ConfectionOvenMaker.buildings={}; ConfectionOvenMaker.maker=nil; ConfectionOvenMaker.activeMaking={}; ConfectionOvenMaker.totalProducts=0; ConfectionOvenMaker.dayTimer=0; print("[ConfectionOvenMaker] Royal Confection Oven Maker System initialized (6 products, 4 buildings)") end
function ConfectionOvenMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ConfectionOvenMaker.maker={name=n or ("Pečar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pečar najet: %s (spretnost: %d)",ConfectionOvenMaker.maker.name,s),"success") end; return true end
function ConfectionOvenMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ConfectionOvenMaker.build(id) local ok,e=ConfectionOvenMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ConfectionOvenMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ConfectionOvenMaker.getQualityBonus() local b=0; for _,bd in ipairs(ConfectionOvenMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ConfectionOvenMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.brickCost and ConfectionOvenMaker.brickStock<(d.brickCost or 0) then return false,"Premalo opek" end; if d.ironCost and ConfectionOvenMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and ConfectionOvenMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.silverCost and ConfectionOvenMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ConfectionOvenMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ConfectionOvenMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ConfectionOvenMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ConfectionOvenMaker.buildings==0 then return false,"Potrebna pečna delavnica" end; if not ConfectionOvenMaker.maker then return false,"Potreben pečar" end; return true end
function ConfectionOvenMaker.make(pt,qty) qty=qty or 1; local ok,e=ConfectionOvenMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.brickCost then ConfectionOvenMaker.brickStock=ConfectionOvenMaker.brickStock-d.brickCost*qty end; if d.ironCost then ConfectionOvenMaker.ironStock=ConfectionOvenMaker.ironStock-d.ironCost*qty end; if d.steelCost then ConfectionOvenMaker.steelStock=ConfectionOvenMaker.steelStock-d.steelCost*qty end; if d.silverCost then ConfectionOvenMaker.silverStock=ConfectionOvenMaker.silverStock-d.silverCost*qty end; if d.goldCost then ConfectionOvenMaker.goldStock=ConfectionOvenMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ConfectionOvenMaker.jewelStock=ConfectionOvenMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ConfectionOvenMaker.pearlStock=ConfectionOvenMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ConfectionOvenMaker.maker then t=math.max(1,t-math.floor(ConfectionOvenMaker.maker.skill/12)) end; table.insert(ConfectionOvenMaker.activeMaking,{id="confectionoven_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=d.food or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ConfectionOvenMaker.completeMaking(m) local q=1.0+(ConfectionOvenMaker.getQualityBonus()/100); if ConfectionOvenMaker.maker then q=q+(ConfectionOvenMaker.maker.skill/140) end; q=math.min(2.5,q); ConfectionOvenMaker.productStock[m.productType]=(ConfectionOvenMaker.productStock[m.productType] or 0)+m.quantity; ConfectionOvenMaker.totalProducts=ConfectionOvenMaker.totalProducts+m.quantity; if m.food>0 and _G.state then _G.state.food=(_G.state.food or 0)+m.food end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ConfectionOvenMaker.maker then ConfectionOvenMaker.maker.itemsMade=ConfectionOvenMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ConfectionOvenMaker.maker.skill=math.min(100,ConfectionOvenMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Peč izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"confectionoven.completed",{productName=m.productName,food=m.food,prestige=m.prestige,happiness=m.happiness}) end end
function ConfectionOvenMaker.update(dt) if not _G.state then return end; ConfectionOvenMaker.dayTimer=ConfectionOvenMaker.dayTimer+dt; if ConfectionOvenMaker.dayTimer>=30 then ConfectionOvenMaker.dayTimer=0; for i=#ConfectionOvenMaker.activeMaking,1,-1 do local m=ConfectionOvenMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ConfectionOvenMaker.completeMaking(m); table.remove(ConfectionOvenMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ConfectionOvenMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ConfectionOvenMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ConfectionOvenMaker.getStats() return {brickStock=ConfectionOvenMaker.brickStock,ironStock=ConfectionOvenMaker.ironStock,steelStock=ConfectionOvenMaker.steelStock,silverStock=ConfectionOvenMaker.silverStock,goldStock=ConfectionOvenMaker.goldStock,jewelStock=ConfectionOvenMaker.jewelStock,pearlStock=ConfectionOvenMaker.pearlStock,productStock=ConfectionOvenMaker.productStock,numBuildings=#ConfectionOvenMaker.buildings,hasMaker=ConfectionOvenMaker.maker~=nil,makerName=ConfectionOvenMaker.maker and ConfectionOvenMaker.maker.name or "—",makerSkill=ConfectionOvenMaker.maker and ConfectionOvenMaker.maker.skill or 0,activeMaking=#ConfectionOvenMaker.activeMaking,totalProducts=ConfectionOvenMaker.totalProducts} end
return ConfectionOvenMaker
