local IceCutter = {}
local PRODUCTS = {
    lake_ice = { name = "Jezerski led", sawCost = 1, time = 2, cost = 12, purity = 60, description = "Jezerski led za hlajenje." },
    river_ice = { name = "Rečni led", sawCost = 1, time = 2, cost = 16, purity = 70, prestige = 1, description = "Rečni led za skladiščenje." },
    glacier_ice = { name = "Ledniški led", sawCost = 1, ropeCost = 1, time = 4, cost = 45, purity = 85, prestige = 3, happiness = 1, description = "Ledniški led za kraljevske shrambe." },
    silver_dust_ice = { name = "Srebrno prašni led", sawCost = 1, silverCost = 1, ropeCost = 1, time = 7, cost = 120, purity = 92, prestige = 7, happiness = 2, description = "Led s srebrnim prahom za plemiče." },
    silver_box_ice = { name = "Srebrno zabojni led", sawCost = 1, silverCost = 1, ropeCost = 1, time = 10, cost = 280, purity = 96, prestige = 12, happiness = 3, description = "Led v srebrnem zabojniku za visoke plemiče." },
    royal_grand_ice = { name = "Kraljevski veliki led", sawCost = 2, goldCost = 1, silverCost = 1, jewelCost = 1, ropeCost = 1, time = 15, cost = 1100, purity = 100, prestige = 30, happiness = 7, description = "Veliki kraljevski led z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Ledarska postaja", cost = { gold = 220, wood = 120, stone = 200 }, upkeep = 5, qualityBonus = 5 },
    ice_house = { name = "Ledarna", cost = { gold = 850, wood = 280, stone = 500, saw = 8 }, upkeep = 21, qualityBonus = 18 },
    cold_storage = { name = "Hladilnica", cost = { gold = 2200, wood = 350, stone = 700, silver = 25, rope = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_ice_atelier = { name = "Kraljevski atelje ledu", cost = { gold = 8800, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 175, qualityBonus = 55, prestigeBonus = 40 },
}
IceCutter.sawStock = 18; IceCutter.ropeStock = 14; IceCutter.silverStock = 8; IceCutter.goldStock = 6; IceCutter.jewelStock = 6
IceCutter.productStock = {}; IceCutter.buildings = {}; IceCutter.maker = nil; IceCutter.activeMaking = {}; IceCutter.totalProducts = 0; IceCutter.dayTimer = 0
function IceCutter.init() IceCutter.sawStock=18; IceCutter.ropeStock=14; IceCutter.silverStock=8; IceCutter.goldStock=6; IceCutter.jewelStock=6; IceCutter.productStock={}; IceCutter.buildings={}; IceCutter.maker=nil; IceCutter.activeMaking={}; IceCutter.totalProducts=0; IceCutter.dayTimer=0; print("[IceCutter] Royal Ice Cutter System initialized (6 products, 4 buildings)") end
function IceCutter.hireMaker(n,s) s=s or math.random(45,85); local c=460+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; IceCutter.maker={name=n or ("Ledar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ledar najet: %s (spretnost: %d)",IceCutter.maker.name,s),"success") end; return true end
function IceCutter.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function IceCutter.build(id) local ok,e=IceCutter.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(IceCutter.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function IceCutter.getQualityBonus() local b=0; for _,bd in ipairs(IceCutter.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function IceCutter.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.sawCost and IceCutter.sawStock<(d.sawCost or 0) then return false,"Premalo žag" end; if d.ropeCost and IceCutter.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.silverCost and IceCutter.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and IceCutter.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and IceCutter.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #IceCutter.buildings==0 then return false,"Potrebna delavnica" end; if not IceCutter.maker then return false,"Potreben ledar" end; return true end
function IceCutter.make(pt,qty) qty=qty or 5; local ok,e=IceCutter.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.sawCost then IceCutter.sawStock=IceCutter.sawStock-d.sawCost*qty end; if d.ropeCost then IceCutter.ropeStock=IceCutter.ropeStock-d.ropeCost*qty end; if d.silverCost then IceCutter.silverStock=IceCutter.silverStock-d.silverCost*qty end; if d.goldCost then IceCutter.goldStock=IceCutter.goldStock-d.goldCost*qty end; if d.jewelCost then IceCutter.jewelStock=IceCutter.jewelStock-d.jewelCost*qty end; local t=d.time; if IceCutter.maker then t=math.max(1,t-math.floor(IceCutter.maker.skill/12)) end; table.insert(IceCutter.activeMaking,{id="ice_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,purity=d.purity or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function IceCutter.completeMaking(m) local q=1.0+(IceCutter.getQualityBonus()/100); if IceCutter.maker then q=q+(IceCutter.maker.skill/180) end; q=math.min(2.0,q); IceCutter.productStock[m.productType]=(IceCutter.productStock[m.productType] or 0)+m.quantity; IceCutter.totalProducts=IceCutter.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if IceCutter.maker then IceCutter.maker.itemsMade=IceCutter.maker.itemsMade+m.quantity; if math.random()<0.20 then IceCutter.maker.skill=math.min(100,IceCutter.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Led pridelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"ice.completed",{productName=m.productName,purity=m.purity}) end end
function IceCutter.update(dt) if not _G.state then return end; IceCutter.dayTimer=IceCutter.dayTimer+dt; if IceCutter.dayTimer>=30 then IceCutter.dayTimer=0; for i=#IceCutter.activeMaking,1,-1 do local m=IceCutter.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then IceCutter.completeMaking(m); table.remove(IceCutter.activeMaking,i) end end; local tu=0; for _,bd in ipairs(IceCutter.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if IceCutter.maker then tu=tu+12 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function IceCutter.getStats() return {sawStock=IceCutter.sawStock,ropeStock=IceCutter.ropeStock,silverStock=IceCutter.silverStock,goldStock=IceCutter.goldStock,jewelStock=IceCutter.jewelStock,productStock=IceCutter.productStock,numBuildings=#IceCutter.buildings,hasMaker=IceCutter.maker~=nil,makerName=IceCutter.maker and IceCutter.maker.name or "—",makerSkill=IceCutter.maker and IceCutter.maker.skill or 0,activeMaking=#IceCutter.activeMaking,totalProducts=IceCutter.totalProducts} end
return IceCutter
