local GlassEngravingWheelRestMaker = {}
local PRODUCTS = {
    iron_glassengravingwheelrest = { name = "Železni počivališča za rezbarska kolesa", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni počivališča za rezbarska kolesa za steklarje." },
    bronze_glassengravingwheelrest = { name = "Bronast počivališča za rezbarska kolesa", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast počivališča za rezbarska kolesa za steklarje." },
    silver_glassengravingwheelrest = { name = "Srebrn počivališča za rezbarska kolesa", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn počivališča za rezbarska kolesa za steklarje." },
    gilded_glassengravingwheelrest = { name = "Pozlačen počivališča za rezbarska kolesa", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen počivališča za rezbarska kolesa za steklarje." },
    jewel_set_glassengravingwheelrest = { name = "Draguljast počivališča za rezbarska kolesa", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast počivališča za rezbarska kolesa za steklarje." },
    royal_sovereign_glassengravingwheelrest = { name = "Kraljevski suveren počivališča za rezbarska kolesa", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren počivališča za rezbarska kolesa z biseri za krono." },
}
local BUILDINGS = {
    glassengravingwheelrest_workshop = { name = "Glassengravingwheelrest delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glassengravingwheelrest_house = { name = "Glassengravingwheelrest hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glassengravingwheelrest_atelier = { name = "Mojstrski glassengravingwheelrest atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glassengravingwheelrest_palace = { name = "Suverena glassengravingwheelrest palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassEngravingWheelRestMaker.ironStock=14; GlassEngravingWheelRestMaker.bronzeStock=12; GlassEngravingWheelRestMaker.woodStock=14; GlassEngravingWheelRestMaker.leatherStock=8; GlassEngravingWheelRestMaker.silverStock=8; GlassEngravingWheelRestMaker.goldStock=6; GlassEngravingWheelRestMaker.jewelStock=4; GlassEngravingWheelRestMaker.pearlStock=4
GlassEngravingWheelRestMaker.productStock = {}; GlassEngravingWheelRestMaker.buildings = {}; GlassEngravingWheelRestMaker.maker = nil; GlassEngravingWheelRestMaker.activeMaking = {}; GlassEngravingWheelRestMaker.totalProducts = 0; GlassEngravingWheelRestMaker.dayTimer = 0
function GlassEngravingWheelRestMaker.init() GlassEngravingWheelRestMaker.ironStock=14; GlassEngravingWheelRestMaker.bronzeStock=12; GlassEngravingWheelRestMaker.woodStock=14; GlassEngravingWheelRestMaker.leatherStock=8; GlassEngravingWheelRestMaker.silverStock=8; GlassEngravingWheelRestMaker.goldStock=6; GlassEngravingWheelRestMaker.jewelStock=4; GlassEngravingWheelRestMaker.pearlStock=4; GlassEngravingWheelRestMaker.productStock={}; GlassEngravingWheelRestMaker.buildings={}; GlassEngravingWheelRestMaker.maker=nil; GlassEngravingWheelRestMaker.activeMaking={}; GlassEngravingWheelRestMaker.totalProducts=0; GlassEngravingWheelRestMaker.dayTimer=0; print("[GlassEngravingWheelRestMaker] Royal Glass Engraving Wheel Rest Maker System initialized (6 products, 4 buildings)") end
function GlassEngravingWheelRestMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassEngravingWheelRestMaker.maker={name=n or ("Počivalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Počivalnik najet: %s (spretnost: %d)",GlassEngravingWheelRestMaker.maker.name,s),"success") end; return true end
function GlassEngravingWheelRestMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassEngravingWheelRestMaker.build(id) local ok,e=GlassEngravingWheelRestMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassEngravingWheelRestMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassEngravingWheelRestMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassEngravingWheelRestMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassEngravingWheelRestMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassEngravingWheelRestMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassEngravingWheelRestMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassEngravingWheelRestMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassEngravingWheelRestMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassEngravingWheelRestMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassEngravingWheelRestMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassEngravingWheelRestMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassEngravingWheelRestMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassEngravingWheelRestMaker.buildings==0 then return false,"Potrebna pocivalna delavnica" end; if not GlassEngravingWheelRestMaker.maker then return false,"Potreben pocivalnik" end; return true end
function GlassEngravingWheelRestMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassEngravingWheelRestMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassEngravingWheelRestMaker.ironStock=GlassEngravingWheelRestMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassEngravingWheelRestMaker.bronzeStock=GlassEngravingWheelRestMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassEngravingWheelRestMaker.woodStock=GlassEngravingWheelRestMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassEngravingWheelRestMaker.leatherStock=GlassEngravingWheelRestMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassEngravingWheelRestMaker.silverStock=GlassEngravingWheelRestMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassEngravingWheelRestMaker.goldStock=GlassEngravingWheelRestMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassEngravingWheelRestMaker.jewelStock=GlassEngravingWheelRestMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassEngravingWheelRestMaker.pearlStock=GlassEngravingWheelRestMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassEngravingWheelRestMaker.maker then t=math.max(1,t-math.floor(GlassEngravingWheelRestMaker.maker.skill/13)) end; table.insert(GlassEngravingWheelRestMaker.activeMaking,{id="glassengravingwheelrest_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassEngravingWheelRestMaker.completeMaking(m) local q=1.0+(GlassEngravingWheelRestMaker.getQualityBonus()/100); if GlassEngravingWheelRestMaker.maker then q=q+(GlassEngravingWheelRestMaker.maker.skill/140) end; q=math.min(2.5,q); GlassEngravingWheelRestMaker.productStock[m.productType]=(GlassEngravingWheelRestMaker.productStock[m.productType] or 0)+m.quantity; GlassEngravingWheelRestMaker.totalProducts=GlassEngravingWheelRestMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassEngravingWheelRestMaker.maker then GlassEngravingWheelRestMaker.maker.itemsMade=GlassEngravingWheelRestMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassEngravingWheelRestMaker.maker.skill=math.min(100,GlassEngravingWheelRestMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Počivališče izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glassengravingwheelrest.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassEngravingWheelRestMaker.update(dt) if not _G.state then return end; GlassEngravingWheelRestMaker.dayTimer=GlassEngravingWheelRestMaker.dayTimer+dt; if GlassEngravingWheelRestMaker.dayTimer>=30 then GlassEngravingWheelRestMaker.dayTimer=0; for i=#GlassEngravingWheelRestMaker.activeMaking,1,-1 do local m=GlassEngravingWheelRestMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassEngravingWheelRestMaker.completeMaking(m); table.remove(GlassEngravingWheelRestMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassEngravingWheelRestMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassEngravingWheelRestMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassEngravingWheelRestMaker.getStats() return {ironStock=GlassEngravingWheelRestMaker.ironStock,bronzeStock=GlassEngravingWheelRestMaker.bronzeStock,woodStock=GlassEngravingWheelRestMaker.woodStock,leatherStock=GlassEngravingWheelRestMaker.leatherStock,silverStock=GlassEngravingWheelRestMaker.silverStock,goldStock=GlassEngravingWheelRestMaker.goldStock,jewelStock=GlassEngravingWheelRestMaker.jewelStock,pearlStock=GlassEngravingWheelRestMaker.pearlStock,productStock=GlassEngravingWheelRestMaker.productStock,numBuildings=#GlassEngravingWheelRestMaker.buildings,hasMaker=GlassEngravingWheelRestMaker.maker~=nil,makerName=GlassEngravingWheelRestMaker.maker and GlassEngravingWheelRestMaker.maker.name or "—",makerSkill=GlassEngravingWheelRestMaker.maker and GlassEngravingWheelRestMaker.maker.skill or 0,activeMaking=#GlassEngravingWheelRestMaker.activeMaking,totalProducts=GlassEngravingWheelRestMaker.totalProducts} end
return GlassEngravingWheelRestMaker
