local BakingSheetMaker = {}
local PRODUCTS = {
    simple_iron_baking_sheet = { name = "Preprosta železna pekač", ironCost = 2, clayCost = 1, time = 3, cost = 80, culinary = 18, happiness = 1, description = "Preprosta železna pekač za peko." }
    , tin_coated_baking_sheet = { name = "Kositrnoobložena pekač", ironCost = 2, tinCost = 1, clayCost = 1, time = 5, cost = 220, culinary = 32, happiness = 1, prestige = 2, description = "Kositrnoobložena pekač za trgovce." },
    silver_rim_baking_sheet = { name = "Srebrnorobna pekač", ironCost = 2, tinCost = 1, silverCost = 1, clayCost = 1, time = 8, cost = 540, culinary = 48, happiness = 2, prestige = 6, description = "Srebrnorobna pekač za plemiče." },
    gold_trimmed_baking_sheet = { name = "Zlatookrasna pekač", ironCost = 2, tinCost = 1, goldCost = 1, silverCost = 1, clayCost = 1, time = 12, cost = 1300, culinary = 62, happiness = 3, prestige = 14, description = "Zlatookrasna pekač za visoke plemiče." },
    jewel_set_baking_sheet = { name = "Draguljasta pekač", ironCost = 2, tinCost = 1, goldCost = 1, silverCost = 1, clayCost = 1, jewelCost = 1, time = 16, cost = 2900, culinary = 78, happiness = 5, prestige = 27, description = "Pekač z draguljem za visoko plemstvo." },
    royal_grand_baking_sheet = { name = "Kraljevski veliki pekač", ironCost = 3, tinCost = 1, goldCost = 2, silverCost = 2, clayCost = 1, jewelCost = 2, pearlCost = 2, time = 23, cost = 6200, culinary = 95, happiness = 12, prestige = 58, description = "Veliki kraljevski pekač z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    baking_sheet_workshop = { name = "Pekačna delavnica", cost = { gold = 260, wood = 120, stone = 120, iron = 6, clay = 6 }, upkeep = 6, qualityBonus = 5 },
    bakeware_loft = { name = "Pekovska podstrešje", cost = { gold = 950, wood = 240, stone = 240, silver = 6, tin = 6 }, upkeep = 22, qualityBonus = 18 },
    master_bakeware_atelier = { name = "Mojstrski pekavski atelje", cost = { gold = 2700, wood = 360, stone = 480, silver = 32, gold = 6 }, upkeep = 62, qualityBonus = 30 },
    royal_bakeware_palace = { name = "Kraljevska pekavska palača", cost = { gold = 11500, wood = 580, stone = 760, gold = 75, jewel = 18 }, upkeep = 230, qualityBonus = 55, prestigeBonus = 50 },
}
BakingSheetMaker.ironStock = 14; BakingSheetMaker.clayStock = 10; BakingSheetMaker.tinStock = 10; BakingSheetMaker.silverStock = 6; BakingSheetMaker.goldStock = 6; BakingSheetMaker.jewelStock = 4; BakingSheetMaker.pearlStock = 4
BakingSheetMaker.productStock = {}; BakingSheetMaker.buildings = {}; BakingSheetMaker.maker = nil; BakingSheetMaker.activeMaking = {}; BakingSheetMaker.totalProducts = 0; BakingSheetMaker.dayTimer = 0
function BakingSheetMaker.init() BakingSheetMaker.ironStock=14; BakingSheetMaker.clayStock=10; BakingSheetMaker.tinStock=10; BakingSheetMaker.silverStock=6; BakingSheetMaker.goldStock=6; BakingSheetMaker.jewelStock=4; BakingSheetMaker.pearlStock=4; BakingSheetMaker.productStock={}; BakingSheetMaker.buildings={}; BakingSheetMaker.maker=nil; BakingSheetMaker.activeMaking={}; BakingSheetMaker.totalProducts=0; BakingSheetMaker.dayTimer=0; print("[BakingSheetMaker] Royal Baking Sheet Maker System initialized (6 products, 4 buildings)") end
function BakingSheetMaker.hireMaker(n,s) s=s or math.random(55,90); local c=520+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BakingSheetMaker.maker={name=n or ("Pekačar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pekačar najet: %s (spretnost: %d)",BakingSheetMaker.maker.name,s),"success") end; return true end
function BakingSheetMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BakingSheetMaker.build(id) local ok,e=BakingSheetMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BakingSheetMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BakingSheetMaker.getQualityBonus() local b=0; for _,bd in ipairs(BakingSheetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BakingSheetMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BakingSheetMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.clayCost and BakingSheetMaker.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.tinCost and BakingSheetMaker.tinStock<(d.tinCost or 0) then return false,"Premalo kositra" end; if d.silverCost and BakingSheetMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BakingSheetMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BakingSheetMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BakingSheetMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BakingSheetMaker.buildings==0 then return false,"Potrebna pekačna delavnica" end; if not BakingSheetMaker.maker then return false,"Potreben pekačar" end; return true end
function BakingSheetMaker.make(pt,qty) qty=qty or 1; local ok,e=BakingSheetMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BakingSheetMaker.ironStock=BakingSheetMaker.ironStock-d.ironCost*qty end; if d.clayCost then BakingSheetMaker.clayStock=BakingSheetMaker.clayStock-d.clayCost*qty end; if d.tinCost then BakingSheetMaker.tinStock=BakingSheetMaker.tinStock-d.tinCost*qty end; if d.silverCost then BakingSheetMaker.silverStock=BakingSheetMaker.silverStock-d.silverCost*qty end; if d.goldCost then BakingSheetMaker.goldStock=BakingSheetMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BakingSheetMaker.jewelStock=BakingSheetMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BakingSheetMaker.pearlStock=BakingSheetMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BakingSheetMaker.maker then t=math.max(1,t-math.floor(BakingSheetMaker.maker.skill/13)) end; table.insert(BakingSheetMaker.activeMaking,{id="bakingsheet_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,culinary=d.culinary or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BakingSheetMaker.completeMaking(m) local q=1.0+(BakingSheetMaker.getQualityBonus()/100); if BakingSheetMaker.maker then q=q+(BakingSheetMaker.maker.skill/140) end; q=math.min(2.5,q); BakingSheetMaker.productStock[m.productType]=(BakingSheetMaker.productStock[m.productType] or 0)+m.quantity; BakingSheetMaker.totalProducts=BakingSheetMaker.totalProducts+m.quantity; if m.culinary>0 and _G.state then _G.state.culinary=(_G.state.culinary or 0)+m.culinary end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BakingSheetMaker.maker then BakingSheetMaker.maker.itemsMade=BakingSheetMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BakingSheetMaker.maker.skill=math.min(100,BakingSheetMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pekač izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bakingsheet.completed",{productName=m.productName,culinary=m.culinary,prestige=m.prestige,happiness=m.happiness}) end end
function BakingSheetMaker.update(dt) if not _G.state then return end; BakingSheetMaker.dayTimer=BakingSheetMaker.dayTimer+dt; if BakingSheetMaker.dayTimer>=30 then BakingSheetMaker.dayTimer=0; for i=#BakingSheetMaker.activeMaking,1,-1 do local m=BakingSheetMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BakingSheetMaker.completeMaking(m); table.remove(BakingSheetMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BakingSheetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BakingSheetMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BakingSheetMaker.getStats() return {ironStock=BakingSheetMaker.ironStock,clayStock=BakingSheetMaker.clayStock,tinStock=BakingSheetMaker.tinStock,silverStock=BakingSheetMaker.silverStock,goldStock=BakingSheetMaker.goldStock,jewelStock=BakingSheetMaker.jewelStock,pearlStock=BakingSheetMaker.pearlStock,productStock=BakingSheetMaker.productStock,numBuildings=#BakingSheetMaker.buildings,hasMaker=BakingSheetMaker.maker~=nil,makerName=BakingSheetMaker.maker and BakingSheetMaker.maker.name or "—",makerSkill=BakingSheetMaker.maker and BakingSheetMaker.maker.skill or 0,activeMaking=#BakingSheetMaker.activeMaking,totalProducts=BakingSheetMaker.totalProducts} end
return BakingSheetMaker
