local MoldDryingOvenMaker = {}
local PRODUCTS = {
    iron_molddryingoven = { name = "Železni sušilna peč za kalupe", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni sušilna peč za kalupe za livarje." },
    bronze_molddryingoven = { name = "Bronast sušilna peč za kalupe", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast sušilna peč za kalupe za livarje." },
    silver_molddryingoven = { name = "Srebrn sušilna peč za kalupe", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn sušilna peč za kalupe za livarje." },
    gilded_molddryingoven = { name = "Pozlačen sušilna peč za kalupe", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen sušilna peč za kalupe za livarje." },
    jewel_set_molddryingoven = { name = "Draguljast sušilna peč za kalupe", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast sušilna peč za kalupe za livarje." },
    royal_sovereign_molddryingoven = { name = "Kraljevski suveren sušilna peč za kalupe", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren sušilna peč za kalupe z biseri za krono." },
}
local BUILDINGS = {
    molddryingoven_workshop = { name = "Molddryingoven delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    molddryingoven_house = { name = "Molddryingoven hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_molddryingoven_atelier = { name = "Mojstrski molddryingoven atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_molddryingoven_palace = { name = "Suverena molddryingoven palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MoldDryingOvenMaker.ironStock=18; MoldDryingOvenMaker.bronzeStock=14; MoldDryingOvenMaker.woodStock=10; MoldDryingOvenMaker.leatherStock=8; MoldDryingOvenMaker.silverStock=8; MoldDryingOvenMaker.goldStock=6; MoldDryingOvenMaker.jewelStock=4; MoldDryingOvenMaker.pearlStock=4
MoldDryingOvenMaker.productStock = {}; MoldDryingOvenMaker.buildings = {}; MoldDryingOvenMaker.maker = nil; MoldDryingOvenMaker.activeMaking = {}; MoldDryingOvenMaker.totalProducts = 0; MoldDryingOvenMaker.dayTimer = 0
function MoldDryingOvenMaker.init() MoldDryingOvenMaker.ironStock=18; MoldDryingOvenMaker.bronzeStock=14; MoldDryingOvenMaker.woodStock=10; MoldDryingOvenMaker.leatherStock=8; MoldDryingOvenMaker.silverStock=8; MoldDryingOvenMaker.goldStock=6; MoldDryingOvenMaker.jewelStock=4; MoldDryingOvenMaker.pearlStock=4; MoldDryingOvenMaker.productStock={}; MoldDryingOvenMaker.buildings={}; MoldDryingOvenMaker.maker=nil; MoldDryingOvenMaker.activeMaking={}; MoldDryingOvenMaker.totalProducts=0; MoldDryingOvenMaker.dayTimer=0; print("[MoldDryingOvenMaker] Royal Mold Drying Oven Maker System initialized (6 products, 4 buildings)") end
function MoldDryingOvenMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MoldDryingOvenMaker.maker={name=n or ("Sušar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sušar najet: %s (spretnost: %d)",MoldDryingOvenMaker.maker.name,s),"success") end; return true end
function MoldDryingOvenMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MoldDryingOvenMaker.build(id) local ok,e=MoldDryingOvenMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MoldDryingOvenMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MoldDryingOvenMaker.getQualityBonus() local b=0; for _,bd in ipairs(MoldDryingOvenMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MoldDryingOvenMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MoldDryingOvenMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MoldDryingOvenMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MoldDryingOvenMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MoldDryingOvenMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MoldDryingOvenMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MoldDryingOvenMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MoldDryingOvenMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MoldDryingOvenMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MoldDryingOvenMaker.buildings==0 then return false,"Potrebna sušilna delavnica" end; if not MoldDryingOvenMaker.maker then return false,"Potreben sušar" end; return true end
function MoldDryingOvenMaker.make(pt,qty) qty=qty or 1; local ok,e=MoldDryingOvenMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MoldDryingOvenMaker.ironStock=MoldDryingOvenMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MoldDryingOvenMaker.bronzeStock=MoldDryingOvenMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MoldDryingOvenMaker.woodStock=MoldDryingOvenMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MoldDryingOvenMaker.leatherStock=MoldDryingOvenMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MoldDryingOvenMaker.silverStock=MoldDryingOvenMaker.silverStock-d.silverCost*qty end; if d.goldCost then MoldDryingOvenMaker.goldStock=MoldDryingOvenMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MoldDryingOvenMaker.jewelStock=MoldDryingOvenMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MoldDryingOvenMaker.pearlStock=MoldDryingOvenMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MoldDryingOvenMaker.maker then t=math.max(1,t-math.floor(MoldDryingOvenMaker.maker.skill/13)) end; table.insert(MoldDryingOvenMaker.activeMaking,{id="molddryingoven_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MoldDryingOvenMaker.completeMaking(m) local q=1.0+(MoldDryingOvenMaker.getQualityBonus()/100); if MoldDryingOvenMaker.maker then q=q+(MoldDryingOvenMaker.maker.skill/140) end; q=math.min(2.5,q); MoldDryingOvenMaker.productStock[m.productType]=(MoldDryingOvenMaker.productStock[m.productType] or 0)+m.quantity; MoldDryingOvenMaker.totalProducts=MoldDryingOvenMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MoldDryingOvenMaker.maker then MoldDryingOvenMaker.maker.itemsMade=MoldDryingOvenMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MoldDryingOvenMaker.maker.skill=math.min(100,MoldDryingOvenMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sušilnica izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"molddryingoven.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MoldDryingOvenMaker.update(dt) if not _G.state then return end; MoldDryingOvenMaker.dayTimer=MoldDryingOvenMaker.dayTimer+dt; if MoldDryingOvenMaker.dayTimer>=30 then MoldDryingOvenMaker.dayTimer=0; for i=#MoldDryingOvenMaker.activeMaking,1,-1 do local m=MoldDryingOvenMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MoldDryingOvenMaker.completeMaking(m); table.remove(MoldDryingOvenMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MoldDryingOvenMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MoldDryingOvenMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MoldDryingOvenMaker.getStats() return {ironStock=MoldDryingOvenMaker.ironStock,bronzeStock=MoldDryingOvenMaker.bronzeStock,woodStock=MoldDryingOvenMaker.woodStock,leatherStock=MoldDryingOvenMaker.leatherStock,silverStock=MoldDryingOvenMaker.silverStock,goldStock=MoldDryingOvenMaker.goldStock,jewelStock=MoldDryingOvenMaker.jewelStock,pearlStock=MoldDryingOvenMaker.pearlStock,productStock=MoldDryingOvenMaker.productStock,numBuildings=#MoldDryingOvenMaker.buildings,hasMaker=MoldDryingOvenMaker.maker~=nil,makerName=MoldDryingOvenMaker.maker and MoldDryingOvenMaker.maker.name or "—",makerSkill=MoldDryingOvenMaker.maker and MoldDryingOvenMaker.maker.skill or 0,activeMaking=#MoldDryingOvenMaker.activeMaking,totalProducts=MoldDryingOvenMaker.totalProducts} end
return MoldDryingOvenMaker
