local PanFluteMaker = {}
local PRODUCTS = {
    simple_reed_panflute = { name = "Preprosta trstna panova flavta", woodCost = 1, time = 2, cost = 25, music = 18, happiness = 1, description = "Preprosta trstna panova flavta za pastirje." },
    wooden_bound_panflute = { name = "Lesenovezana panova flavta", woodCost = 2, leatherCost = 1, time = 4, cost = 70, music = 32, happiness = 2, prestige = 1, description = "Lesenovezana panova flavta za trgovce." },
    boxwood_consort_panflute = { name = "Pušpanova panova flavta", woodCost = 3, leatherCost = 1, ropeCost = 1, time = 7, cost = 200, music = 48, happiness = 2, prestige = 4, description = "Pušpanova panova flavta za plemiče." },
    silver_bound_panflute = { name = "Srebrnovezana panova flavta", woodCost = 3, silverCost = 1, leatherCost = 1, time = 10, cost = 540, music = 62, happiness = 3, prestige = 12, description = "Srebrnovezana panova flavta za visoke plemiče." },
    gold_trimmed_panflute = { name = "Zlatookrasna panova flavta", woodCost = 3, goldCost = 1, silverCost = 1, leatherCost = 1, jewelCost = 1, time = 14, cost = 1300, music = 78, happiness = 5, prestige = 25, description = "Zlatookrasna panova flavta z draguljem za visoko plemstvo." },
    royal_grand_panflute = { name = "Kraljevski veliki panova flavta", woodCost = 5, goldCost = 2, silverCost = 2, leatherCost = 1, jewelCost = 2, pearlCost = 2, time = 21, cost = 3300, music = 92, happiness = 11, prestige = 56, description = "Velika kraljevska panova flavta z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    panflute_workshop = { name = "Panova delavnica", cost = { gold = 200, wood = 120, stone = 80, leather = 6 }, upkeep = 4, qualityBonus = 5 },
    wind_loft = { name = "Pihalna podstrešje", cost = { gold = 780, wood = 240, stone = 220, silver = 6, leather = 8 }, upkeep = 18, qualityBonus = 18 },
    master_wind_atelier = { name = "Mojstrski pihalni atelje", cost = { gold = 2300, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 52, qualityBonus = 30 },
    royal_panflute_palace = { name = "Kraljevska panova palača", cost = { gold = 9500, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 50 },
}
PanFluteMaker.woodStock = 18; PanFluteMaker.leatherStock = 10; PanFluteMaker.ropeStock = 8; PanFluteMaker.silverStock = 6; PanFluteMaker.goldStock = 6; PanFluteMaker.jewelStock = 4; PanFluteMaker.pearlStock = 4
PanFluteMaker.productStock = {}; PanFluteMaker.buildings = {}; PanFluteMaker.maker = nil; PanFluteMaker.activeMaking = {}; PanFluteMaker.totalProducts = 0; PanFluteMaker.dayTimer = 0
function PanFluteMaker.init() PanFluteMaker.woodStock=18; PanFluteMaker.leatherStock=10; PanFluteMaker.ropeStock=8; PanFluteMaker.silverStock=6; PanFluteMaker.goldStock=6; PanFluteMaker.jewelStock=4; PanFluteMaker.pearlStock=4; PanFluteMaker.productStock={}; PanFluteMaker.buildings={}; PanFluteMaker.maker=nil; PanFluteMaker.activeMaking={}; PanFluteMaker.totalProducts=0; PanFluteMaker.dayTimer=0; print("[PanFluteMaker] Royal Pan Flute Maker System initialized (6 products, 4 buildings)") end
function PanFluteMaker.hireMaker(n,s) s=s or math.random(55,90); local c=460+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PanFluteMaker.maker={name=n or ("Panovar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Panovar najet: %s (spretnost: %d)",PanFluteMaker.maker.name,s),"success") end; return true end
function PanFluteMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PanFluteMaker.build(id) local ok,e=PanFluteMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PanFluteMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PanFluteMaker.getQualityBonus() local b=0; for _,bd in ipairs(PanFluteMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PanFluteMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and PanFluteMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PanFluteMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.ropeCost and PanFluteMaker.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.silverCost and PanFluteMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PanFluteMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PanFluteMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PanFluteMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PanFluteMaker.buildings==0 then return false,"Potrebna panova delavnica" end; if not PanFluteMaker.maker then return false,"Potreben panovar" end; return true end
function PanFluteMaker.make(pt,qty) qty=qty or 1; local ok,e=PanFluteMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then PanFluteMaker.woodStock=PanFluteMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PanFluteMaker.leatherStock=PanFluteMaker.leatherStock-d.leatherCost*qty end; if d.ropeCost then PanFluteMaker.ropeStock=PanFluteMaker.ropeStock-d.ropeCost*qty end; if d.silverCost then PanFluteMaker.silverStock=PanFluteMaker.silverStock-d.silverCost*qty end; if d.goldCost then PanFluteMaker.goldStock=PanFluteMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PanFluteMaker.jewelStock=PanFluteMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PanFluteMaker.pearlStock=PanFluteMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PanFluteMaker.maker then t=math.max(1,t-math.floor(PanFluteMaker.maker.skill/13)) end; table.insert(PanFluteMaker.activeMaking,{id="panflute_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,music=d.music or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PanFluteMaker.completeMaking(m) local q=1.0+(PanFluteMaker.getQualityBonus()/100); if PanFluteMaker.maker then q=q+(PanFluteMaker.maker.skill/150) end; q=math.min(2.4,q); PanFluteMaker.productStock[m.productType]=(PanFluteMaker.productStock[m.productType] or 0)+m.quantity; PanFluteMaker.totalProducts=PanFluteMaker.totalProducts+m.quantity; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if PanFluteMaker.maker then PanFluteMaker.maker.itemsMade=PanFluteMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PanFluteMaker.maker.skill=math.min(100,PanFluteMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Panova flavta izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"panflute.completed",{productName=m.productName,music=m.music,prestige=m.prestige,happiness=m.happiness}) end end
function PanFluteMaker.update(dt) if not _G.state then return end; PanFluteMaker.dayTimer=PanFluteMaker.dayTimer+dt; if PanFluteMaker.dayTimer>=30 then PanFluteMaker.dayTimer=0; for i=#PanFluteMaker.activeMaking,1,-1 do local m=PanFluteMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PanFluteMaker.completeMaking(m); table.remove(PanFluteMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PanFluteMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PanFluteMaker.maker then tu=tu+12 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PanFluteMaker.getStats() return {woodStock=PanFluteMaker.woodStock,leatherStock=PanFluteMaker.leatherStock,ropeStock=PanFluteMaker.ropeStock,silverStock=PanFluteMaker.silverStock,goldStock=PanFluteMaker.goldStock,jewelStock=PanFluteMaker.jewelStock,pearlStock=PanFluteMaker.pearlStock,productStock=PanFluteMaker.productStock,numBuildings=#PanFluteMaker.buildings,hasMaker=PanFluteMaker.maker~=nil,makerName=PanFluteMaker.maker and PanFluteMaker.maker.name or "—",makerSkill=PanFluteMaker.maker and PanFluteMaker.maker.skill or 0,activeMaking=#PanFluteMaker.activeMaking,totalProducts=PanFluteMaker.totalProducts} end
return PanFluteMaker
