local GlassAnnealingOvenDoorWheelMaker = {}
local PRODUCTS = {
    iron_glassannealingovendoorwheel = { name = "Železni kolesa za vrata ohlajevalne peči", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni kolesa za vrata ohlajevalne peči za steklarje." },
    bronze_glassannealingovendoorwheel = { name = "Bronast kolesa za vrata ohlajevalne peči", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast kolesa za vrata ohlajevalne peči za steklarje." },
    silver_glassannealingovendoorwheel = { name = "Srebrn kolesa za vrata ohlajevalne peči", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn kolesa za vrata ohlajevalne peči za steklarje." },
    gilded_glassannealingovendoorwheel = { name = "Pozlačen kolesa za vrata ohlajevalne peči", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen kolesa za vrata ohlajevalne peči za steklarje." },
    jewel_set_glassannealingovendoorwheel = { name = "Draguljast kolesa za vrata ohlajevalne peči", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast kolesa za vrata ohlajevalne peči za steklarje." },
    royal_sovereign_glassannealingovendoorwheel = { name = "Kraljevski suveren kolesa za vrata ohlajevalne peči", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren kolesa za vrata ohlajevalne peči z biseri za krono." },
}
local BUILDINGS = {
    glassannealingovendoorwheel_workshop = { name = "Glassannealingovendoorwheel delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glassannealingovendoorwheel_house = { name = "Glassannealingovendoorwheel hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glassannealingovendoorwheel_atelier = { name = "Mojstrski glassannealingovendoorwheel atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glassannealingovendoorwheel_palace = { name = "Suverena glassannealingovendoorwheel palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassAnnealingOvenDoorWheelMaker.ironStock=16; GlassAnnealingOvenDoorWheelMaker.bronzeStock=12; GlassAnnealingOvenDoorWheelMaker.woodStock=12; GlassAnnealingOvenDoorWheelMaker.leatherStock=8; GlassAnnealingOvenDoorWheelMaker.silverStock=8; GlassAnnealingOvenDoorWheelMaker.goldStock=6; GlassAnnealingOvenDoorWheelMaker.jewelStock=4; GlassAnnealingOvenDoorWheelMaker.pearlStock=4
GlassAnnealingOvenDoorWheelMaker.productStock = {}; GlassAnnealingOvenDoorWheelMaker.buildings = {}; GlassAnnealingOvenDoorWheelMaker.maker = nil; GlassAnnealingOvenDoorWheelMaker.activeMaking = {}; GlassAnnealingOvenDoorWheelMaker.totalProducts = 0; GlassAnnealingOvenDoorWheelMaker.dayTimer = 0
function GlassAnnealingOvenDoorWheelMaker.init() GlassAnnealingOvenDoorWheelMaker.ironStock=16; GlassAnnealingOvenDoorWheelMaker.bronzeStock=12; GlassAnnealingOvenDoorWheelMaker.woodStock=12; GlassAnnealingOvenDoorWheelMaker.leatherStock=8; GlassAnnealingOvenDoorWheelMaker.silverStock=8; GlassAnnealingOvenDoorWheelMaker.goldStock=6; GlassAnnealingOvenDoorWheelMaker.jewelStock=4; GlassAnnealingOvenDoorWheelMaker.pearlStock=4; GlassAnnealingOvenDoorWheelMaker.productStock={}; GlassAnnealingOvenDoorWheelMaker.buildings={}; GlassAnnealingOvenDoorWheelMaker.maker=nil; GlassAnnealingOvenDoorWheelMaker.activeMaking={}; GlassAnnealingOvenDoorWheelMaker.totalProducts=0; GlassAnnealingOvenDoorWheelMaker.dayTimer=0; print("[GlassAnnealingOvenDoorWheelMaker] Royal Glass Annealing Oven Door Wheel Maker System initialized (6 products, 4 buildings)") end
function GlassAnnealingOvenDoorWheelMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassAnnealingOvenDoorWheelMaker.maker={name=n or ("Kolar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kolar najet: %s (spretnost: %d)",GlassAnnealingOvenDoorWheelMaker.maker.name,s),"success") end; return true end
function GlassAnnealingOvenDoorWheelMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassAnnealingOvenDoorWheelMaker.build(id) local ok,e=GlassAnnealingOvenDoorWheelMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassAnnealingOvenDoorWheelMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassAnnealingOvenDoorWheelMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassAnnealingOvenDoorWheelMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassAnnealingOvenDoorWheelMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassAnnealingOvenDoorWheelMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassAnnealingOvenDoorWheelMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassAnnealingOvenDoorWheelMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassAnnealingOvenDoorWheelMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassAnnealingOvenDoorWheelMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassAnnealingOvenDoorWheelMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassAnnealingOvenDoorWheelMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassAnnealingOvenDoorWheelMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassAnnealingOvenDoorWheelMaker.buildings==0 then return false,"Potrebna kolska delavnica" end; if not GlassAnnealingOvenDoorWheelMaker.maker then return false,"Potreben kolar" end; return true end
function GlassAnnealingOvenDoorWheelMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassAnnealingOvenDoorWheelMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassAnnealingOvenDoorWheelMaker.ironStock=GlassAnnealingOvenDoorWheelMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassAnnealingOvenDoorWheelMaker.bronzeStock=GlassAnnealingOvenDoorWheelMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassAnnealingOvenDoorWheelMaker.woodStock=GlassAnnealingOvenDoorWheelMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassAnnealingOvenDoorWheelMaker.leatherStock=GlassAnnealingOvenDoorWheelMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassAnnealingOvenDoorWheelMaker.silverStock=GlassAnnealingOvenDoorWheelMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassAnnealingOvenDoorWheelMaker.goldStock=GlassAnnealingOvenDoorWheelMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassAnnealingOvenDoorWheelMaker.jewelStock=GlassAnnealingOvenDoorWheelMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassAnnealingOvenDoorWheelMaker.pearlStock=GlassAnnealingOvenDoorWheelMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassAnnealingOvenDoorWheelMaker.maker then t=math.max(1,t-math.floor(GlassAnnealingOvenDoorWheelMaker.maker.skill/13)) end; table.insert(GlassAnnealingOvenDoorWheelMaker.activeMaking,{id="glassannealingovendoorwheel_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassAnnealingOvenDoorWheelMaker.completeMaking(m) local q=1.0+(GlassAnnealingOvenDoorWheelMaker.getQualityBonus()/100); if GlassAnnealingOvenDoorWheelMaker.maker then q=q+(GlassAnnealingOvenDoorWheelMaker.maker.skill/140) end; q=math.min(2.5,q); GlassAnnealingOvenDoorWheelMaker.productStock[m.productType]=(GlassAnnealingOvenDoorWheelMaker.productStock[m.productType] or 0)+m.quantity; GlassAnnealingOvenDoorWheelMaker.totalProducts=GlassAnnealingOvenDoorWheelMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassAnnealingOvenDoorWheelMaker.maker then GlassAnnealingOvenDoorWheelMaker.maker.itemsMade=GlassAnnealingOvenDoorWheelMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassAnnealingOvenDoorWheelMaker.maker.skill=math.min(100,GlassAnnealingOvenDoorWheelMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kolo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glassannealingovendoorwheel.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassAnnealingOvenDoorWheelMaker.update(dt) if not _G.state then return end; GlassAnnealingOvenDoorWheelMaker.dayTimer=GlassAnnealingOvenDoorWheelMaker.dayTimer+dt; if GlassAnnealingOvenDoorWheelMaker.dayTimer>=30 then GlassAnnealingOvenDoorWheelMaker.dayTimer=0; for i=#GlassAnnealingOvenDoorWheelMaker.activeMaking,1,-1 do local m=GlassAnnealingOvenDoorWheelMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassAnnealingOvenDoorWheelMaker.completeMaking(m); table.remove(GlassAnnealingOvenDoorWheelMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassAnnealingOvenDoorWheelMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassAnnealingOvenDoorWheelMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassAnnealingOvenDoorWheelMaker.getStats() return {ironStock=GlassAnnealingOvenDoorWheelMaker.ironStock,bronzeStock=GlassAnnealingOvenDoorWheelMaker.bronzeStock,woodStock=GlassAnnealingOvenDoorWheelMaker.woodStock,leatherStock=GlassAnnealingOvenDoorWheelMaker.leatherStock,silverStock=GlassAnnealingOvenDoorWheelMaker.silverStock,goldStock=GlassAnnealingOvenDoorWheelMaker.goldStock,jewelStock=GlassAnnealingOvenDoorWheelMaker.jewelStock,pearlStock=GlassAnnealingOvenDoorWheelMaker.pearlStock,productStock=GlassAnnealingOvenDoorWheelMaker.productStock,numBuildings=#GlassAnnealingOvenDoorWheelMaker.buildings,hasMaker=GlassAnnealingOvenDoorWheelMaker.maker~=nil,makerName=GlassAnnealingOvenDoorWheelMaker.maker and GlassAnnealingOvenDoorWheelMaker.maker.name or "—",makerSkill=GlassAnnealingOvenDoorWheelMaker.maker and GlassAnnealingOvenDoorWheelMaker.maker.skill or 0,activeMaking=#GlassAnnealingOvenDoorWheelMaker.activeMaking,totalProducts=GlassAnnealingOvenDoorWheelMaker.totalProducts} end
return GlassAnnealingOvenDoorWheelMaker
