local GardenLeafGrabberMaker = {}
local PRODUCTS = {
    iron_gardenleafgrabber = { name = "Železni grablje za liste", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni grablje za liste za vrtnarje." },
    bronze_gardenleafgrabber = { name = "Bronast grablje za liste", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast grablje za liste za vrtnarje." },
    silver_gardenleafgrabber = { name = "Srebrn grablje za liste", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn grablje za liste za vrtnarje." },
    gilded_gardenleafgrabber = { name = "Pozlačen grablje za liste", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen grablje za liste za vrtnarje." },
    jewel_set_gardenleafgrabber = { name = "Draguljast grablje za liste", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast grablje za liste za vrtnarje." },
    royal_sovereign_gardenleafgrabber = { name = "Kraljevski suveren grablje za liste", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren grablje za liste z biseri za krono." },
}
local BUILDINGS = {
    gardenleafgrabber_workshop = { name = "Gardenleafgrabber delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardenleafgrabber_house = { name = "Gardenleafgrabber hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardenleafgrabber_atelier = { name = "Mojstrski gardenleafgrabber atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardenleafgrabber_palace = { name = "Suverena gardenleafgrabber palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenLeafGrabberMaker.ironStock=12; GardenLeafGrabberMaker.bronzeStock=10; GardenLeafGrabberMaker.woodStock=16; GardenLeafGrabberMaker.leatherStock=10; GardenLeafGrabberMaker.silverStock=8; GardenLeafGrabberMaker.goldStock=6; GardenLeafGrabberMaker.jewelStock=4; GardenLeafGrabberMaker.pearlStock=4
GardenLeafGrabberMaker.productStock = {}; GardenLeafGrabberMaker.buildings = {}; GardenLeafGrabberMaker.maker = nil; GardenLeafGrabberMaker.activeMaking = {}; GardenLeafGrabberMaker.totalProducts = 0; GardenLeafGrabberMaker.dayTimer = 0
function GardenLeafGrabberMaker.init() GardenLeafGrabberMaker.ironStock=12; GardenLeafGrabberMaker.bronzeStock=10; GardenLeafGrabberMaker.woodStock=16; GardenLeafGrabberMaker.leatherStock=10; GardenLeafGrabberMaker.silverStock=8; GardenLeafGrabberMaker.goldStock=6; GardenLeafGrabberMaker.jewelStock=4; GardenLeafGrabberMaker.pearlStock=4; GardenLeafGrabberMaker.productStock={}; GardenLeafGrabberMaker.buildings={}; GardenLeafGrabberMaker.maker=nil; GardenLeafGrabberMaker.activeMaking={}; GardenLeafGrabberMaker.totalProducts=0; GardenLeafGrabberMaker.dayTimer=0; print("[GardenLeafGrabberMaker] Royal Garden Leaf Grabber Maker System initialized (6 products, 4 buildings)") end
function GardenLeafGrabberMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenLeafGrabberMaker.maker={name=n or ("Listar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Listar najet: %s (spretnost: %d)",GardenLeafGrabberMaker.maker.name,s),"success") end; return true end
function GardenLeafGrabberMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenLeafGrabberMaker.build(id) local ok,e=GardenLeafGrabberMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenLeafGrabberMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenLeafGrabberMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenLeafGrabberMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenLeafGrabberMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenLeafGrabberMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenLeafGrabberMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenLeafGrabberMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenLeafGrabberMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenLeafGrabberMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenLeafGrabberMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenLeafGrabberMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenLeafGrabberMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenLeafGrabberMaker.buildings==0 then return false,"Potrebna listna delavnica" end; if not GardenLeafGrabberMaker.maker then return false,"Potreben listar" end; return true end
function GardenLeafGrabberMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenLeafGrabberMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenLeafGrabberMaker.ironStock=GardenLeafGrabberMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenLeafGrabberMaker.bronzeStock=GardenLeafGrabberMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenLeafGrabberMaker.woodStock=GardenLeafGrabberMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenLeafGrabberMaker.leatherStock=GardenLeafGrabberMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenLeafGrabberMaker.silverStock=GardenLeafGrabberMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenLeafGrabberMaker.goldStock=GardenLeafGrabberMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenLeafGrabberMaker.jewelStock=GardenLeafGrabberMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenLeafGrabberMaker.pearlStock=GardenLeafGrabberMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenLeafGrabberMaker.maker then t=math.max(1,t-math.floor(GardenLeafGrabberMaker.maker.skill/13)) end; table.insert(GardenLeafGrabberMaker.activeMaking,{id="gardenleafgrabber_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenLeafGrabberMaker.completeMaking(m) local q=1.0+(GardenLeafGrabberMaker.getQualityBonus()/100); if GardenLeafGrabberMaker.maker then q=q+(GardenLeafGrabberMaker.maker.skill/140) end; q=math.min(2.5,q); GardenLeafGrabberMaker.productStock[m.productType]=(GardenLeafGrabberMaker.productStock[m.productType] or 0)+m.quantity; GardenLeafGrabberMaker.totalProducts=GardenLeafGrabberMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenLeafGrabberMaker.maker then GardenLeafGrabberMaker.maker.itemsMade=GardenLeafGrabberMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenLeafGrabberMaker.maker.skill=math.min(100,GardenLeafGrabberMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Grabilec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardenleafgrabber.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenLeafGrabberMaker.update(dt) if not _G.state then return end; GardenLeafGrabberMaker.dayTimer=GardenLeafGrabberMaker.dayTimer+dt; if GardenLeafGrabberMaker.dayTimer>=30 then GardenLeafGrabberMaker.dayTimer=0; for i=#GardenLeafGrabberMaker.activeMaking,1,-1 do local m=GardenLeafGrabberMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenLeafGrabberMaker.completeMaking(m); table.remove(GardenLeafGrabberMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenLeafGrabberMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenLeafGrabberMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenLeafGrabberMaker.getStats() return {ironStock=GardenLeafGrabberMaker.ironStock,bronzeStock=GardenLeafGrabberMaker.bronzeStock,woodStock=GardenLeafGrabberMaker.woodStock,leatherStock=GardenLeafGrabberMaker.leatherStock,silverStock=GardenLeafGrabberMaker.silverStock,goldStock=GardenLeafGrabberMaker.goldStock,jewelStock=GardenLeafGrabberMaker.jewelStock,pearlStock=GardenLeafGrabberMaker.pearlStock,productStock=GardenLeafGrabberMaker.productStock,numBuildings=#GardenLeafGrabberMaker.buildings,hasMaker=GardenLeafGrabberMaker.maker~=nil,makerName=GardenLeafGrabberMaker.maker and GardenLeafGrabberMaker.maker.name or "—",makerSkill=GardenLeafGrabberMaker.maker and GardenLeafGrabberMaker.maker.skill or 0,activeMaking=#GardenLeafGrabberMaker.activeMaking,totalProducts=GardenLeafGrabberMaker.totalProducts} end
return GardenLeafGrabberMaker
