local SandReclaimerMaker = {}
local PRODUCTS = {
    iron_sandreclaimer = { name = "Železni obnavljalec livarskega peska", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni obnavljalec livarskega peska za livarje." },
    bronze_sandreclaimer = { name = "Bronast obnavljalec livarskega peska", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast obnavljalec livarskega peska za livarje." },
    silver_sandreclaimer = { name = "Srebrn obnavljalec livarskega peska", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn obnavljalec livarskega peska za livarje." },
    gilded_sandreclaimer = { name = "Pozlačen obnavljalec livarskega peska", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen obnavljalec livarskega peska za livarje." },
    jewel_set_sandreclaimer = { name = "Draguljast obnavljalec livarskega peska", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast obnavljalec livarskega peska za livarje." },
    royal_sovereign_sandreclaimer = { name = "Kraljevski suveren obnavljalec livarskega peska", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren obnavljalec livarskega peska z biseri za krono." },
}
local BUILDINGS = {
    sandreclaimer_workshop = { name = "Sandreclaimer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    sandreclaimer_house = { name = "Sandreclaimer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_sandreclaimer_atelier = { name = "Mojstrski sandreclaimer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_sandreclaimer_palace = { name = "Suverena sandreclaimer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SandReclaimerMaker.ironStock=18; SandReclaimerMaker.bronzeStock=14; SandReclaimerMaker.woodStock=10; SandReclaimerMaker.leatherStock=8; SandReclaimerMaker.silverStock=8; SandReclaimerMaker.goldStock=6; SandReclaimerMaker.jewelStock=4; SandReclaimerMaker.pearlStock=4
SandReclaimerMaker.productStock = {}; SandReclaimerMaker.buildings = {}; SandReclaimerMaker.maker = nil; SandReclaimerMaker.activeMaking = {}; SandReclaimerMaker.totalProducts = 0; SandReclaimerMaker.dayTimer = 0
function SandReclaimerMaker.init() SandReclaimerMaker.ironStock=18; SandReclaimerMaker.bronzeStock=14; SandReclaimerMaker.woodStock=10; SandReclaimerMaker.leatherStock=8; SandReclaimerMaker.silverStock=8; SandReclaimerMaker.goldStock=6; SandReclaimerMaker.jewelStock=4; SandReclaimerMaker.pearlStock=4; SandReclaimerMaker.productStock={}; SandReclaimerMaker.buildings={}; SandReclaimerMaker.maker=nil; SandReclaimerMaker.activeMaking={}; SandReclaimerMaker.totalProducts=0; SandReclaimerMaker.dayTimer=0; print("[SandReclaimerMaker] Royal Sand Reclaimer Maker System initialized (6 products, 4 buildings)") end
function SandReclaimerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SandReclaimerMaker.maker={name=n or ("Obnavljalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Obnavljalec najet: %s (spretnost: %d)",SandReclaimerMaker.maker.name,s),"success") end; return true end
function SandReclaimerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SandReclaimerMaker.build(id) local ok,e=SandReclaimerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SandReclaimerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SandReclaimerMaker.getQualityBonus() local b=0; for _,bd in ipairs(SandReclaimerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SandReclaimerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SandReclaimerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SandReclaimerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SandReclaimerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SandReclaimerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SandReclaimerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SandReclaimerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SandReclaimerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SandReclaimerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SandReclaimerMaker.buildings==0 then return false,"Potrebna obnavljalna delavnica" end; if not SandReclaimerMaker.maker then return false,"Potreben obnavljalec" end; return true end
function SandReclaimerMaker.make(pt,qty) qty=qty or 1; local ok,e=SandReclaimerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SandReclaimerMaker.ironStock=SandReclaimerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SandReclaimerMaker.bronzeStock=SandReclaimerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SandReclaimerMaker.woodStock=SandReclaimerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SandReclaimerMaker.leatherStock=SandReclaimerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SandReclaimerMaker.silverStock=SandReclaimerMaker.silverStock-d.silverCost*qty end; if d.goldCost then SandReclaimerMaker.goldStock=SandReclaimerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SandReclaimerMaker.jewelStock=SandReclaimerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SandReclaimerMaker.pearlStock=SandReclaimerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SandReclaimerMaker.maker then t=math.max(1,t-math.floor(SandReclaimerMaker.maker.skill/13)) end; table.insert(SandReclaimerMaker.activeMaking,{id="sandreclaimer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SandReclaimerMaker.completeMaking(m) local q=1.0+(SandReclaimerMaker.getQualityBonus()/100); if SandReclaimerMaker.maker then q=q+(SandReclaimerMaker.maker.skill/140) end; q=math.min(2.5,q); SandReclaimerMaker.productStock[m.productType]=(SandReclaimerMaker.productStock[m.productType] or 0)+m.quantity; SandReclaimerMaker.totalProducts=SandReclaimerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SandReclaimerMaker.maker then SandReclaimerMaker.maker.itemsMade=SandReclaimerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SandReclaimerMaker.maker.skill=math.min(100,SandReclaimerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Obnovilec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sandreclaimer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SandReclaimerMaker.update(dt) if not _G.state then return end; SandReclaimerMaker.dayTimer=SandReclaimerMaker.dayTimer+dt; if SandReclaimerMaker.dayTimer>=30 then SandReclaimerMaker.dayTimer=0; for i=#SandReclaimerMaker.activeMaking,1,-1 do local m=SandReclaimerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SandReclaimerMaker.completeMaking(m); table.remove(SandReclaimerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SandReclaimerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SandReclaimerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SandReclaimerMaker.getStats() return {ironStock=SandReclaimerMaker.ironStock,bronzeStock=SandReclaimerMaker.bronzeStock,woodStock=SandReclaimerMaker.woodStock,leatherStock=SandReclaimerMaker.leatherStock,silverStock=SandReclaimerMaker.silverStock,goldStock=SandReclaimerMaker.goldStock,jewelStock=SandReclaimerMaker.jewelStock,pearlStock=SandReclaimerMaker.pearlStock,productStock=SandReclaimerMaker.productStock,numBuildings=#SandReclaimerMaker.buildings,hasMaker=SandReclaimerMaker.maker~=nil,makerName=SandReclaimerMaker.maker and SandReclaimerMaker.maker.name or "—",makerSkill=SandReclaimerMaker.maker and SandReclaimerMaker.maker.skill or 0,activeMaking=#SandReclaimerMaker.activeMaking,totalProducts=SandReclaimerMaker.totalProducts} end
return SandReclaimerMaker
