local BookMarkTasselMaker = {}
local PRODUCTS = {
    iron_bookmarktassel = { name = "Železni lok za zaznamke", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni lok za zaznamke za knjigoveze." },
    bronze_bookmarktassel = { name = "Bronast lok za zaznamke", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast lok za zaznamke za knjigoveze." },
    silver_bookmarktassel = { name = "Srebrn lok za zaznamke", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn lok za zaznamke za knjigoveze." },
    gilded_bookmarktassel = { name = "Pozlačen lok za zaznamke", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen lok za zaznamke za knjigoveze." },
    jewel_set_bookmarktassel = { name = "Draguljast lok za zaznamke", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast lok za zaznamke za knjigoveze." },
    royal_sovereign_bookmarktassel = { name = "Kraljevski suveren lok za zaznamke", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren lok za zaznamke z biseri za krono." },
}
local BUILDINGS = {
    bookmarktassel_workshop = { name = "Bookmarktassel delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookmarktassel_house = { name = "Bookmarktassel hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookmarktassel_atelier = { name = "Mojstrski bookmarktassel atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookmarktassel_palace = { name = "Suverena bookmarktassel palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookMarkTasselMaker.ironStock=10; BookMarkTasselMaker.bronzeStock=8; BookMarkTasselMaker.woodStock=14; BookMarkTasselMaker.leatherStock=14; BookMarkTasselMaker.silverStock=8; BookMarkTasselMaker.goldStock=6; BookMarkTasselMaker.jewelStock=4; BookMarkTasselMaker.pearlStock=4
BookMarkTasselMaker.productStock = {}; BookMarkTasselMaker.buildings = {}; BookMarkTasselMaker.maker = nil; BookMarkTasselMaker.activeMaking = {}; BookMarkTasselMaker.totalProducts = 0; BookMarkTasselMaker.dayTimer = 0
function BookMarkTasselMaker.init() BookMarkTasselMaker.ironStock=10; BookMarkTasselMaker.bronzeStock=8; BookMarkTasselMaker.woodStock=14; BookMarkTasselMaker.leatherStock=14; BookMarkTasselMaker.silverStock=8; BookMarkTasselMaker.goldStock=6; BookMarkTasselMaker.jewelStock=4; BookMarkTasselMaker.pearlStock=4; BookMarkTasselMaker.productStock={}; BookMarkTasselMaker.buildings={}; BookMarkTasselMaker.maker=nil; BookMarkTasselMaker.activeMaking={}; BookMarkTasselMaker.totalProducts=0; BookMarkTasselMaker.dayTimer=0; print("[BookMarkTasselMaker] Royal Book Mark Tassel Maker System initialized (6 products, 4 buildings)") end
function BookMarkTasselMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookMarkTasselMaker.maker={name=n or ("Lokčar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lokčar najet: %s (spretnost: %d)",BookMarkTasselMaker.maker.name,s),"success") end; return true end
function BookMarkTasselMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookMarkTasselMaker.build(id) local ok,e=BookMarkTasselMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookMarkTasselMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookMarkTasselMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookMarkTasselMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookMarkTasselMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookMarkTasselMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookMarkTasselMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookMarkTasselMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookMarkTasselMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookMarkTasselMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookMarkTasselMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookMarkTasselMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookMarkTasselMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookMarkTasselMaker.buildings==0 then return false,"Potrebna lokčna delavnica" end; if not BookMarkTasselMaker.maker then return false,"Potreben lokčar" end; return true end
function BookMarkTasselMaker.make(pt,qty) qty=qty or 1; local ok,e=BookMarkTasselMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookMarkTasselMaker.ironStock=BookMarkTasselMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookMarkTasselMaker.bronzeStock=BookMarkTasselMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookMarkTasselMaker.woodStock=BookMarkTasselMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookMarkTasselMaker.leatherStock=BookMarkTasselMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookMarkTasselMaker.silverStock=BookMarkTasselMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookMarkTasselMaker.goldStock=BookMarkTasselMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookMarkTasselMaker.jewelStock=BookMarkTasselMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookMarkTasselMaker.pearlStock=BookMarkTasselMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookMarkTasselMaker.maker then t=math.max(1,t-math.floor(BookMarkTasselMaker.maker.skill/13)) end; table.insert(BookMarkTasselMaker.activeMaking,{id="bookmarktassel_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookMarkTasselMaker.completeMaking(m) local q=1.0+(BookMarkTasselMaker.getQualityBonus()/100); if BookMarkTasselMaker.maker then q=q+(BookMarkTasselMaker.maker.skill/140) end; q=math.min(2.5,q); BookMarkTasselMaker.productStock[m.productType]=(BookMarkTasselMaker.productStock[m.productType] or 0)+m.quantity; BookMarkTasselMaker.totalProducts=BookMarkTasselMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookMarkTasselMaker.maker then BookMarkTasselMaker.maker.itemsMade=BookMarkTasselMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookMarkTasselMaker.maker.skill=math.min(100,BookMarkTasselMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lok izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookmarktassel.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookMarkTasselMaker.update(dt) if not _G.state then return end; BookMarkTasselMaker.dayTimer=BookMarkTasselMaker.dayTimer+dt; if BookMarkTasselMaker.dayTimer>=30 then BookMarkTasselMaker.dayTimer=0; for i=#BookMarkTasselMaker.activeMaking,1,-1 do local m=BookMarkTasselMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookMarkTasselMaker.completeMaking(m); table.remove(BookMarkTasselMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookMarkTasselMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookMarkTasselMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookMarkTasselMaker.getStats() return {ironStock=BookMarkTasselMaker.ironStock,bronzeStock=BookMarkTasselMaker.bronzeStock,woodStock=BookMarkTasselMaker.woodStock,leatherStock=BookMarkTasselMaker.leatherStock,silverStock=BookMarkTasselMaker.silverStock,goldStock=BookMarkTasselMaker.goldStock,jewelStock=BookMarkTasselMaker.jewelStock,pearlStock=BookMarkTasselMaker.pearlStock,productStock=BookMarkTasselMaker.productStock,numBuildings=#BookMarkTasselMaker.buildings,hasMaker=BookMarkTasselMaker.maker~=nil,makerName=BookMarkTasselMaker.maker and BookMarkTasselMaker.maker.name or "—",makerSkill=BookMarkTasselMaker.maker and BookMarkTasselMaker.maker.skill or 0,activeMaking=#BookMarkTasselMaker.activeMaking,totalProducts=BookMarkTasselMaker.totalProducts} end
return BookMarkTasselMaker
