local GlassGloryHoleMaker = {}
local PRODUCTS = {
    iron_glassgloryhole = { name = "Železni ognjena komora za oblikovanje", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni ognjena komora za oblikovanje za steklarje." },
    bronze_glassgloryhole = { name = "Bronast ognjena komora za oblikovanje", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast ognjena komora za oblikovanje za steklarje." },
    silver_glassgloryhole = { name = "Srebrn ognjena komora za oblikovanje", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn ognjena komora za oblikovanje za steklarje." },
    gilded_glassgloryhole = { name = "Pozlačen ognjena komora za oblikovanje", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen ognjena komora za oblikovanje za steklarje." },
    jewel_set_glassgloryhole = { name = "Draguljast ognjena komora za oblikovanje", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast ognjena komora za oblikovanje za steklarje." },
    royal_sovereign_glassgloryhole = { name = "Kraljevski suveren ognjena komora za oblikovanje", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren ognjena komora za oblikovanje z biseri za krono." },
}
local BUILDINGS = {
    glassgloryhole_workshop = { name = "Glassgloryhole delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glassgloryhole_house = { name = "Glassgloryhole hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glassgloryhole_atelier = { name = "Mojstrski glassgloryhole atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glassgloryhole_palace = { name = "Suverena glassgloryhole palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassGloryHoleMaker.ironStock = 16; GlassGloryHoleMaker.bronzeStock = 14; GlassGloryHoleMaker.woodStock = 10; GlassGloryHoleMaker.leatherStock = 8; GlassGloryHoleMaker.silverStock = 8; GlassGloryHoleMaker.goldStock = 6; GlassGloryHoleMaker.jewelStock = 4; GlassGloryHoleMaker.pearlStock = 4
GlassGloryHoleMaker.productStock = {}; GlassGloryHoleMaker.buildings = {}; GlassGloryHoleMaker.maker = nil; GlassGloryHoleMaker.activeMaking = {}; GlassGloryHoleMaker.totalProducts = 0; GlassGloryHoleMaker.dayTimer = 0
function GlassGloryHoleMaker.init() GlassGloryHoleMaker.ironStock=16; GlassGloryHoleMaker.bronzeStock=14; GlassGloryHoleMaker.woodStock=10; GlassGloryHoleMaker.leatherStock=8; GlassGloryHoleMaker.silverStock=8; GlassGloryHoleMaker.goldStock=6; GlassGloryHoleMaker.jewelStock=4; GlassGloryHoleMaker.pearlStock=4; GlassGloryHoleMaker.productStock={}; GlassGloryHoleMaker.buildings={}; GlassGloryHoleMaker.maker=nil; GlassGloryHoleMaker.activeMaking={}; GlassGloryHoleMaker.totalProducts=0; GlassGloryHoleMaker.dayTimer=0; print("[GlassGloryHoleMaker] Royal Glass Glory Hole Maker System initialized (6 products, 4 buildings)") end
function GlassGloryHoleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassGloryHoleMaker.maker={name=n or ("Komorec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Komorec najet: %s (spretnost: %d)",GlassGloryHoleMaker.maker.name,s),"success") end; return true end
function GlassGloryHoleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassGloryHoleMaker.build(id) local ok,e=GlassGloryHoleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassGloryHoleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassGloryHoleMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassGloryHoleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassGloryHoleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassGloryHoleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassGloryHoleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassGloryHoleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassGloryHoleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassGloryHoleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassGloryHoleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassGloryHoleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassGloryHoleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassGloryHoleMaker.buildings==0 then return false,"Potrebna komorna delavnica" end; if not GlassGloryHoleMaker.maker then return false,"Potreben komorec" end; return true end
function GlassGloryHoleMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassGloryHoleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassGloryHoleMaker.ironStock=GlassGloryHoleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassGloryHoleMaker.bronzeStock=GlassGloryHoleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassGloryHoleMaker.woodStock=GlassGloryHoleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassGloryHoleMaker.leatherStock=GlassGloryHoleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassGloryHoleMaker.silverStock=GlassGloryHoleMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassGloryHoleMaker.goldStock=GlassGloryHoleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassGloryHoleMaker.jewelStock=GlassGloryHoleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassGloryHoleMaker.pearlStock=GlassGloryHoleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassGloryHoleMaker.maker then t=math.max(1,t-math.floor(GlassGloryHoleMaker.maker.skill/13)) end; table.insert(GlassGloryHoleMaker.activeMaking,{id="${MAKER_LOWER}_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassGloryHoleMaker.completeMaking(m) local q=1.0+(GlassGloryHoleMaker.getQualityBonus()/100); if GlassGloryHoleMaker.maker then q=q+(GlassGloryHoleMaker.maker.skill/140) end; q=math.min(2.5,q); GlassGloryHoleMaker.productStock[m.productType]=(GlassGloryHoleMaker.productStock[m.productType] or 0)+m.quantity; GlassGloryHoleMaker.totalProducts=GlassGloryHoleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassGloryHoleMaker.maker then GlassGloryHoleMaker.maker.itemsMade=GlassGloryHoleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassGloryHoleMaker.maker.skill=math.min(100,GlassGloryHoleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Komora izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"${MAKER_LOWER}.completed",{productName=m.productName,prestige=m.prestige,happiness:m.happiness}) end end
function GlassGloryHoleMaker.update(dt) if not _G.state then return end; GlassGloryHoleMaker.dayTimer=GlassGloryHoleMaker.dayTimer+dt; if GlassGloryHoleMaker.dayTimer>=30 then GlassGloryHoleMaker.dayTimer=0; for i=#GlassGloryHoleMaker.activeMaking,1,-1 do local m=GlassGloryHoleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassGloryHoleMaker.completeMaking(m); table.remove(GlassGloryHoleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassGloryHoleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassGloryHoleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassGloryHoleMaker.getStats() return {ironStock=GlassGloryHoleMaker.ironStock,bronzeStock=GlassGloryHoleMaker.bronzeStock,woodStock=GlassGloryHoleMaker.woodStock,leatherStock=GlassGloryHoleMaker.leatherStock,silverStock=GlassGloryHoleMaker.silverStock,goldStock=GlassGloryHoleMaker.goldStock,jewelStock=GlassGloryHoleMaker.jewelStock,pearlStock=GlassGloryHoleMaker.pearlStock,productStock=GlassGloryHoleMaker.productStock,numBuildings=#GlassGloryHoleMaker.buildings,hasMaker=GlassGloryHoleMaker.maker~=nil,makerName=GlassGloryHoleMaker.maker and GlassGloryHoleMaker.maker.name or "—",makerSkill=GlassGloryHoleMaker.maker and GlassGloryHoleMaker.maker.skill or 0,activeMaking=#GlassGloryHoleMaker.activeMaking,totalProducts=GlassGloryHoleMaker.totalProducts} end
return GlassGloryHoleMaker
