local ApothecaryVialMaker = {}
local PRODUCTS = {
    iron_vial = { name = "Železna viala", ironCost = 1, woodCost = 1, leatherCost = 1, time = 4, cost = 125, prestige = 2, happiness = 1, description = "Železna viala za shranjevanje zdravil." },
    bronze_vial = { name = "Bronasta viala", bronzeCost = 2, ironCost = 1, woodCost = 1, leatherCost = 1, time = 6, cost = 310, prestige = 4, happiness = 2, description = "Bronasta viala za apoteko." },
    silver_vial = { name = "Srebrna viala", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 10, cost = 760, prestige = 9, happiness = 3, description = "Srebrna viala za plemiške lekarne." },
    gilded_vial = { name = "Pozlačena viala", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 14, cost = 1700, prestige = 17, happiness = 4, description = "Pozlačena viala za dvorno lekarno." },
    jewel_set_vial = { name = "Draguljasta viala", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 18, cost = 3650, prestige = 32, happiness = 6, description = "Draguljasta viala za kraljevo lekarno." },
    royal_sovereign_vial = { name = "Kraljevski suverena viala", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 25, cost = 8000, prestige = 63, happiness = 12, description = "Suverena viala z biseri za krono." },
}
local BUILDINGS = {
    vial_workshop = { name = "Vialna delavnica", cost = { gold = 310, wood = 165, stone = 125, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    vial_house = { name = "Vialna hiša", cost = { gold = 1150, wood = 345, stone = 255, silver = 7, iron = 7 }, upkeep = 24, qualityBonus = 18 },
    master_vial_atelier = { name = "Mojstrski vialni atelje", cost = { gold = 2920, wood = 405, stone = 505, silver = 33, gold = 7 }, upkeep = 68, qualityBonus = 30 },
    sovereign_vial_palace = { name = "Suverena vialna palača", cost = { gold = 12650, wood = 615, stone = 815, gold = 81, jewel = 18 }, upkeep = 248, qualityBonus = 55, prestigeBonus = 50 },
}
ApothecaryVialMaker.ironStock = 12; ApothecaryVialMaker.bronzeStock = 10; ApothecaryVialMaker.woodStock = 14; ApothecaryVialMaker.leatherStock = 10; ApothecaryVialMaker.silverStock = 8; ApothecaryVialMaker.goldStock = 6; ApothecaryVialMaker.jewelStock = 4; ApothecaryVialMaker.pearlStock = 4
ApothecaryVialMaker.productStock = {}; ApothecaryVialMaker.buildings = {}; ApothecaryVialMaker.maker = nil; ApothecaryVialMaker.activeMaking = {}; ApothecaryVialMaker.totalProducts = 0; ApothecaryVialMaker.dayTimer = 0
function ApothecaryVialMaker.init() ApothecaryVialMaker.ironStock=12; ApothecaryVialMaker.bronzeStock=10; ApothecaryVialMaker.woodStock=14; ApothecaryVialMaker.leatherStock=10; ApothecaryVialMaker.silverStock=8; ApothecaryVialMaker.goldStock=6; ApothecaryVialMaker.jewelStock=4; ApothecaryVialMaker.pearlStock=4; ApothecaryVialMaker.productStock={}; ApothecaryVialMaker.buildings={}; ApothecaryVialMaker.maker=nil; ApothecaryVialMaker.activeMaking={}; ApothecaryVialMaker.totalProducts=0; ApothecaryVialMaker.dayTimer=0; print("[ApothecaryVialMaker] Royal Apothecary Vial Maker System initialized (6 products, 4 buildings)") end
function ApothecaryVialMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ApothecaryVialMaker.maker={name=n or ("Vialar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vialar najet: %s (spretnost: %d)",ApothecaryVialMaker.maker.name,s),"success") end; return true end
function ApothecaryVialMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ApothecaryVialMaker.build(id) local ok,e=ApothecaryVialMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ApothecaryVialMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ApothecaryVialMaker.getQualityBonus() local b=0; for _,bd in ipairs(ApothecaryVialMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ApothecaryVialMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ApothecaryVialMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and ApothecaryVialMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ApothecaryVialMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ApothecaryVialMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ApothecaryVialMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ApothecaryVialMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ApothecaryVialMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ApothecaryVialMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ApothecaryVialMaker.buildings==0 then return false,"Potrebna vialna delavnica" end; if not ApothecaryVialMaker.maker then return false,"Potreben vialar" end; return true end
function ApothecaryVialMaker.make(pt,qty) qty=qty or 1; local ok,e=ApothecaryVialMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ApothecaryVialMaker.ironStock=ApothecaryVialMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ApothecaryVialMaker.bronzeStock=ApothecaryVialMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ApothecaryVialMaker.woodStock=ApothecaryVialMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ApothecaryVialMaker.leatherStock=ApothecaryVialMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ApothecaryVialMaker.silverStock=ApothecaryVialMaker.silverStock-d.silverCost*qty end; if d.goldCost then ApothecaryVialMaker.goldStock=ApothecaryVialMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ApothecaryVialMaker.jewelStock=ApothecaryVialMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ApothecaryVialMaker.pearlStock=ApothecaryVialMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ApothecaryVialMaker.maker then t=math.max(1,t-math.floor(ApothecaryVialMaker.maker.skill/13)) end; table.insert(ApothecaryVialMaker.activeMaking,{id="vial_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ApothecaryVialMaker.completeMaking(m) local q=1.0+(ApothecaryVialMaker.getQualityBonus()/100); if ApothecaryVialMaker.maker then q=q+(ApothecaryVialMaker.maker.skill/140) end; q=math.min(2.5,q); ApothecaryVialMaker.productStock[m.productType]=(ApothecaryVialMaker.productStock[m.productType] or 0)+m.quantity; ApothecaryVialMaker.totalProducts=ApothecaryVialMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ApothecaryVialMaker.maker then ApothecaryVialMaker.maker.itemsMade=ApothecaryVialMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ApothecaryVialMaker.maker.skill=math.min(100,ApothecaryVialMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Viala izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"vial.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ApothecaryVialMaker.update(dt) if not _G.state then return end; ApothecaryVialMaker.dayTimer=ApothecaryVialMaker.dayTimer+dt; if ApothecaryVialMaker.dayTimer>=30 then ApothecaryVialMaker.dayTimer=0; for i=#ApothecaryVialMaker.activeMaking,1,-1 do local m=ApothecaryVialMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ApothecaryVialMaker.completeMaking(m); table.remove(ApothecaryVialMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ApothecaryVialMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ApothecaryVialMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ApothecaryVialMaker.getStats() return {ironStock=ApothecaryVialMaker.ironStock,bronzeStock=ApothecaryVialMaker.bronzeStock,woodStock=ApothecaryVialMaker.woodStock,leatherStock=ApothecaryVialMaker.leatherStock,silverStock=ApothecaryVialMaker.silverStock,goldStock=ApothecaryVialMaker.goldStock,jewelStock=ApothecaryVialMaker.jewelStock,pearlStock=ApothecaryVialMaker.pearlStock,productStock=ApothecaryVialMaker.productStock,numBuildings=#ApothecaryVialMaker.buildings,hasMaker=ApothecaryVialMaker.maker~=nil,makerName=ApothecaryVialMaker.maker and ApothecaryVialMaker.maker.name or "—",makerSkill=ApothecaryVialMaker.maker and ApothecaryVialMaker.maker.skill or 0,activeMaking=#ApothecaryVialMaker.activeMaking,totalProducts=ApothecaryVialMaker.totalProducts} end
return ApothecaryVialMaker
