local LatrineBuilder = {}
local PRODUCTS = {
    simple_wood_latrine = { name = "Preprost leseni stranišče", woodCost = 3, stoneCost = 1, time = 3, cost = 80, health = 6, happiness = 1, description = "Preprost leseni stranišče za higiene." },
    stone_pit_latrine = { name = "Kamnit jamski stranišče", stoneCost = 3, woodCost = 2, time = 5, cost = 200, health = 10, happiness = 1, prestige = 1, description = "Kamnit jamski stranišče za trgovce." },
    brick_privy = { name = "Opečna privatna stranišče", brickCost = 3, stoneCost = 2, woodCost = 2, time = 8, cost = 480, health = 16, happiness = 2, prestige = 3, description = "Opečna privatna stranišče za plemiče." },
    marble_privy = { name = "Marmornata privatna stranišče", marbleCost = 2, brickCost = 2, stoneCost = 2, woodCost = 2, time = 12, cost = 1100, health = 22, happiness = 3, prestige = 8, description = "Marmornata privatna stranišče za visoke plemiče." },
    silver_fitted_privy = { name = "Srebrnoopremljena stranišče", marbleCost = 2, silverCost = 1, brickCost = 2, stoneCost = 2, woodCost = 2, time = 16, cost = 2500, health = 30, happiness = 5, prestige = 16, description = "Srebrnoopremljena stranišče za visoko plemstvo." },
    royal_grand_privy = { name = "Kraljevski veliki stranišče", marbleCost = 3, goldCost = 1, silverCost = 1, brickCost = 2, stoneCost = 2, woodCost = 2, jewelCost = 1, pearlCost = 1, time = 23, cost = 5500, health = 45, happiness = 12, prestige = 40, description = "Veliki kraljevski stranišče z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    latrine_workshop = { name = "Straniščna delavnica", cost = { gold = 240, wood = 140, stone = 140, brick = 4 }, upkeep = 5, qualityBonus = 5 },
    sanitation_loft = { name = "Sanitarna podstrešje", cost = { gold = 880, wood = 280, stone = 280, silver = 6, marble = 4 }, upkeep = 20, qualityBonus = 18 },
    master_latrine_atelier = { name = "Mojstrski sanitarni atelje", cost = { gold = 2500, wood = 380, stone = 520, silver = 30, gold = 6 }, upkeep = 58, qualityBonus = 30 },
    royal_sanitation_palace = { name = "Kraljevska sanitarna palača", cost = { gold = 10500, wood = 580, stone = 800, gold = 65, jewel = 16 }, upkeep = 210, qualityBonus = 55, prestigeBonus = 50 },
}
LatrineBuilder.woodStock = 18; LatrineBuilder.stoneStock = 16; LatrineBuilder.brickStock = 14; LatrineBuilder.marbleStock = 8; LatrineBuilder.silverStock = 6; LatrineBuilder.goldStock = 6; LatrineBuilder.jewelStock = 4; LatrineBuilder.pearlStock = 4
LatrineBuilder.productStock = {}; LatrineBuilder.buildings = {}; LatrineBuilder.maker = nil; LatrineBuilder.activeMaking = {}; LatrineBuilder.totalProducts = 0; LatrineBuilder.dayTimer = 0
function LatrineBuilder.init() LatrineBuilder.woodStock=18; LatrineBuilder.stoneStock=16; LatrineBuilder.brickStock=14; LatrineBuilder.marbleStock=8; LatrineBuilder.silverStock=6; LatrineBuilder.goldStock=6; LatrineBuilder.jewelStock=4; LatrineBuilder.pearlStock=4; LatrineBuilder.productStock={}; LatrineBuilder.buildings={}; LatrineBuilder.maker=nil; LatrineBuilder.activeMaking={}; LatrineBuilder.totalProducts=0; LatrineBuilder.dayTimer=0; print("[LatrineBuilder] Royal Latrine Builder System initialized (6 products, 4 buildings)") end
function LatrineBuilder.hireMaker(n,s) s=s or math.random(55,90); local c=520+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LatrineBuilder.maker={name=n or ("Sanitar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sanitar najet: %s (spretnost: %d)",LatrineBuilder.maker.name,s),"success") end; return true end
function LatrineBuilder.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LatrineBuilder.build(id) local ok,e=LatrineBuilder.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LatrineBuilder.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LatrineBuilder.getQualityBonus() local b=0; for _,bd in ipairs(LatrineBuilder.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LatrineBuilder.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and LatrineBuilder.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.stoneCost and LatrineBuilder.stoneStock<(d.stoneCost or 0) then return false,"Premalo kamna" end; if d.brickCost and LatrineBuilder.brickStock<(d.brickCost or 0) then return false,"Premalo opek" end; if d.marbleCost and LatrineBuilder.marbleStock<(d.marbleCost or 0) then return false,"Premalo marmorja" end; if d.silverCost and LatrineBuilder.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and LatrineBuilder.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and LatrineBuilder.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and LatrineBuilder.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #LatrineBuilder.buildings==0 then return false,"Potrebna straniščna delavnica" end; if not LatrineBuilder.maker then return false,"Potreben sanitar" end; return true end
function LatrineBuilder.make(pt,qty) qty=qty or 1; local ok,e=LatrineBuilder.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then LatrineBuilder.woodStock=LatrineBuilder.woodStock-d.woodCost*qty end; if d.stoneCost then LatrineBuilder.stoneStock=LatrineBuilder.stoneStock-d.stoneCost*qty end; if d.brickCost then LatrineBuilder.brickStock=LatrineBuilder.brickStock-d.brickCost*qty end; if d.marbleCost then LatrineBuilder.marbleStock=LatrineBuilder.marbleStock-d.marbleCost*qty end; if d.silverCost then LatrineBuilder.silverStock=LatrineBuilder.silverStock-d.silverCost*qty end; if d.goldCost then LatrineBuilder.goldStock=LatrineBuilder.goldStock-d.goldCost*qty end; if d.jewelCost then LatrineBuilder.jewelStock=LatrineBuilder.jewelStock-d.jewelCost*qty end; if d.pearlCost then LatrineBuilder.pearlStock=LatrineBuilder.pearlStock-d.pearlCost*qty end; local t=d.time; if LatrineBuilder.maker then t=math.max(1,t-math.floor(LatrineBuilder.maker.skill/13)) end; table.insert(LatrineBuilder.activeMaking,{id="latrine_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,health=d.health or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gradnja: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LatrineBuilder.completeMaking(m) local q=1.0+(LatrineBuilder.getQualityBonus()/100); if LatrineBuilder.maker then q=q+(LatrineBuilder.maker.skill/140) end; q=math.min(2.5,q); LatrineBuilder.productStock[m.productType]=(LatrineBuilder.productStock[m.productType] or 0)+m.quantity; LatrineBuilder.totalProducts=LatrineBuilder.totalProducts+m.quantity; if m.health>0 and _G.state then _G.state.health=(_G.state.health or 0)+m.health end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LatrineBuilder.maker then LatrineBuilder.maker.itemsMade=LatrineBuilder.maker.itemsMade+m.quantity; if math.random()<0.25 then LatrineBuilder.maker.skill=math.min(100,LatrineBuilder.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stranišče izdelano: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"latrine.completed",{productName=m.productName,health=m.health,prestige=m.prestige,happiness=m.happiness}) end end
function LatrineBuilder.update(dt) if not _G.state then return end; LatrineBuilder.dayTimer=LatrineBuilder.dayTimer+dt; if LatrineBuilder.dayTimer>=30 then LatrineBuilder.dayTimer=0; for i=#LatrineBuilder.activeMaking,1,-1 do local m=LatrineBuilder.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LatrineBuilder.completeMaking(m); table.remove(LatrineBuilder.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LatrineBuilder.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LatrineBuilder.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LatrineBuilder.getStats() return {woodStock=LatrineBuilder.woodStock,stoneStock=LatrineBuilder.stoneStock,brickStock=LatrineBuilder.brickStock,marbleStock=LatrineBuilder.marbleStock,silverStock=LatrineBuilder.silverStock,goldStock=LatrineBuilder.goldStock,jewelStock=LatrineBuilder.jewelStock,pearlStock=LatrineBuilder.pearlStock,productStock=LatrineBuilder.productStock,numBuildings=#LatrineBuilder.buildings,hasMaker=LatrineBuilder.maker~=nil,makerName=LatrineBuilder.maker and LatrineBuilder.maker.name or "—",makerSkill=LatrineBuilder.maker and LatrineBuilder.maker.skill or 0,activeMaking=#LatrineBuilder.activeMaking,totalProducts=LatrineBuilder.totalProducts} end
return LatrineBuilder
