local ChimeHammerMaker = {}
local PRODUCTS = {
    iron_chimehammer = { name = "Železni kladivce za zvonove", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni kladivce za zvonove za ure." },
    bronze_chimehammer = { name = "Bronast kladivce za zvonove", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast kladivce za zvonove za ure." },
    silver_chimehammer = { name = "Srebrn kladivce za zvonove", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn kladivce za zvonove za ure." },
    gilded_chimehammer = { name = "Pozlačen kladivce za zvonove", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen kladivce za zvonove za ure." },
    jewel_set_chimehammer = { name = "Draguljast kladivce za zvonove", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast kladivce za zvonove za ure." },
    royal_sovereign_chimehammer = { name = "Kraljevski suveren kladivce za zvonove", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren kladivce za zvonove z biseri za krono." },
}
local BUILDINGS = {
    chimehammer_workshop = { name = "Chimehammer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    chimehammer_house = { name = "Chimehammer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_chimehammer_atelier = { name = "Mojstrski chimehammer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_chimehammer_palace = { name = "Suverena chimehammer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
ChimeHammerMaker.ironStock = 16; ChimeHammerMaker.bronzeStock = 14; ChimeHammerMaker.woodStock = 10; ChimeHammerMaker.leatherStock = 10; ChimeHammerMaker.silverStock = 8; ChimeHammerMaker.goldStock = 6; ChimeHammerMaker.jewelStock = 4; ChimeHammerMaker.pearlStock = 4
ChimeHammerMaker.productStock = {}; ChimeHammerMaker.buildings = {}; ChimeHammerMaker.maker = nil; ChimeHammerMaker.activeMaking = {}; ChimeHammerMaker.totalProducts = 0; ChimeHammerMaker.dayTimer = 0
function ChimeHammerMaker.init() ChimeHammerMaker.ironStock=16; ChimeHammerMaker.bronzeStock=14; ChimeHammerMaker.woodStock=10; ChimeHammerMaker.leatherStock=10; ChimeHammerMaker.silverStock=8; ChimeHammerMaker.goldStock=6; ChimeHammerMaker.jewelStock=4; ChimeHammerMaker.pearlStock=4; ChimeHammerMaker.productStock={}; ChimeHammerMaker.buildings={}; ChimeHammerMaker.maker=nil; ChimeHammerMaker.activeMaking={}; ChimeHammerMaker.totalProducts=0; ChimeHammerMaker.dayTimer=0; print("[ChimeHammerMaker] Royal Chime Hammer Maker System initialized (6 products, 4 buildings)") end
function ChimeHammerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ChimeHammerMaker.maker={name=n or ("Zvonar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zvonar najet: %s (spretnost: %d)",ChimeHammerMaker.maker.name,s),"success") end; return true end
function ChimeHammerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ChimeHammerMaker.build(id) local ok,e=ChimeHammerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ChimeHammerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ChimeHammerMaker.getQualityBonus() local b=0; for _,bd in ipairs(ChimeHammerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ChimeHammerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ChimeHammerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and ChimeHammerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ChimeHammerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ChimeHammerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ChimeHammerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ChimeHammerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ChimeHammerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ChimeHammerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ChimeHammerMaker.buildings==0 then return false,"Potrebna zvončna delavnica" end; if not ChimeHammerMaker.maker then return false,"Potreben zvonar" end; return true end
function ChimeHammerMaker.make(pt,qty) qty=qty or 1; local ok,e=ChimeHammerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ChimeHammerMaker.ironStock=ChimeHammerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ChimeHammerMaker.bronzeStock=ChimeHammerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ChimeHammerMaker.woodStock=ChimeHammerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ChimeHammerMaker.leatherStock=ChimeHammerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ChimeHammerMaker.silverStock=ChimeHammerMaker.silverStock-d.silverCost*qty end; if d.goldCost then ChimeHammerMaker.goldStock=ChimeHammerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ChimeHammerMaker.jewelStock=ChimeHammerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ChimeHammerMaker.pearlStock=ChimeHammerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ChimeHammerMaker.maker then t=math.max(1,t-math.floor(ChimeHammerMaker.maker.skill/13)) end; table.insert(ChimeHammerMaker.activeMaking,{id="chimehammer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ChimeHammerMaker.completeMaking(m) local q=1.0+(ChimeHammerMaker.getQualityBonus()/100); if ChimeHammerMaker.maker then q=q+(ChimeHammerMaker.maker.skill/140) end; q=math.min(2.5,q); ChimeHammerMaker.productStock[m.productType]=(ChimeHammerMaker.productStock[m.productType] or 0)+m.quantity; ChimeHammerMaker.totalProducts=ChimeHammerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ChimeHammerMaker.maker then ChimeHammerMaker.maker.itemsMade=ChimeHammerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ChimeHammerMaker.maker.skill=math.min(100,ChimeHammerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kladivce izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"chimehammer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ChimeHammerMaker.update(dt) if not _G.state then return end; ChimeHammerMaker.dayTimer=ChimeHammerMaker.dayTimer+dt; if ChimeHammerMaker.dayTimer>=30 then ChimeHammerMaker.dayTimer=0; for i=#ChimeHammerMaker.activeMaking,1,-1 do local m=ChimeHammerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ChimeHammerMaker.completeMaking(m); table.remove(ChimeHammerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ChimeHammerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ChimeHammerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ChimeHammerMaker.getStats() return {ironStock=ChimeHammerMaker.ironStock,bronzeStock=ChimeHammerMaker.bronzeStock,woodStock=ChimeHammerMaker.woodStock,leatherStock=ChimeHammerMaker.leatherStock,silverStock=ChimeHammerMaker.silverStock,goldStock=ChimeHammerMaker.goldStock,jewelStock=ChimeHammerMaker.jewelStock,pearlStock=ChimeHammerMaker.pearlStock,productStock=ChimeHammerMaker.productStock,numBuildings=#ChimeHammerMaker.buildings,hasMaker=ChimeHammerMaker.maker~=nil,makerName=ChimeHammerMaker.maker and ChimeHammerMaker.maker.name or "—",makerSkill=ChimeHammerMaker.maker and ChimeHammerMaker.maker.skill or 0,activeMaking=#ChimeHammerMaker.activeMaking,totalProducts=ChimeHammerMaker.totalProducts} end
return ChimeHammerMaker
