local MillstoneEyeReamerMaker = {}
local PRODUCTS = {
    iron_millstoneeyereamer = { name = "Železni razširjevalci očes mlinskih kamnov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni razširjevalci očes mlinskih kamnov za mlinarje." },
    bronze_millstoneeyereamer = { name = "Bronast razširjevalci očes mlinskih kamnov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast razširjevalci očes mlinskih kamnov za mlinarje." },
    silver_millstoneeyereamer = { name = "Srebrn razširjevalci očes mlinskih kamnov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn razširjevalci očes mlinskih kamnov za mlinarje." },
    gilded_millstoneeyereamer = { name = "Pozlačen razširjevalci očes mlinskih kamnov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen razširjevalci očes mlinskih kamnov za mlinarje." },
    jewel_set_millstoneeyereamer = { name = "Draguljast razširjevalci očes mlinskih kamnov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast razširjevalci očes mlinskih kamnov za mlinarje." },
    royal_sovereign_millstoneeyereamer = { name = "Kraljevski suveren razširjevalci očes mlinskih kamnov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren razširjevalci očes mlinskih kamnov z biseri za krono." },
}
local BUILDINGS = {
    millstoneeyereamer_workshop = { name = "Millstoneeyereamer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    millstoneeyereamer_house = { name = "Millstoneeyereamer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_millstoneeyereamer_atelier = { name = "Mojstrski millstoneeyereamer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_millstoneeyereamer_palace = { name = "Suverena millstoneeyereamer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillstoneEyeReamerMaker.ironStock=18; MillstoneEyeReamerMaker.bronzeStock=14; MillstoneEyeReamerMaker.woodStock=10; MillstoneEyeReamerMaker.leatherStock=8; MillstoneEyeReamerMaker.silverStock=8; MillstoneEyeReamerMaker.goldStock=6; MillstoneEyeReamerMaker.jewelStock=4; MillstoneEyeReamerMaker.pearlStock=4
MillstoneEyeReamerMaker.productStock = {}; MillstoneEyeReamerMaker.buildings = {}; MillstoneEyeReamerMaker.maker = nil; MillstoneEyeReamerMaker.activeMaking = {}; MillstoneEyeReamerMaker.totalProducts = 0; MillstoneEyeReamerMaker.dayTimer = 0
function MillstoneEyeReamerMaker.init() MillstoneEyeReamerMaker.ironStock=18; MillstoneEyeReamerMaker.bronzeStock=14; MillstoneEyeReamerMaker.woodStock=10; MillstoneEyeReamerMaker.leatherStock=8; MillstoneEyeReamerMaker.silverStock=8; MillstoneEyeReamerMaker.goldStock=6; MillstoneEyeReamerMaker.jewelStock=4; MillstoneEyeReamerMaker.pearlStock=4; MillstoneEyeReamerMaker.productStock={}; MillstoneEyeReamerMaker.buildings={}; MillstoneEyeReamerMaker.maker=nil; MillstoneEyeReamerMaker.activeMaking={}; MillstoneEyeReamerMaker.totalProducts=0; MillstoneEyeReamerMaker.dayTimer=0; print("[MillstoneEyeReamerMaker] Royal Millstone Eye Reamer Maker System initialized (6 products, 4 buildings)") end
function MillstoneEyeReamerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillstoneEyeReamerMaker.maker={name=n or ("Razširjevalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Razširjevalec najet: %s (spretnost: %d)",MillstoneEyeReamerMaker.maker.name,s),"success") end; return true end
function MillstoneEyeReamerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillstoneEyeReamerMaker.build(id) local ok,e=MillstoneEyeReamerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillstoneEyeReamerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillstoneEyeReamerMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillstoneEyeReamerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillstoneEyeReamerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillstoneEyeReamerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillstoneEyeReamerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillstoneEyeReamerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillstoneEyeReamerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillstoneEyeReamerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillstoneEyeReamerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillstoneEyeReamerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillstoneEyeReamerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillstoneEyeReamerMaker.buildings==0 then return false,"Potrebna razširjevalna delavnica" end; if not MillstoneEyeReamerMaker.maker then return false,"Potreben razsirjevalec" end; return true end
function MillstoneEyeReamerMaker.make(pt,qty) qty=qty or 1; local ok,e=MillstoneEyeReamerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillstoneEyeReamerMaker.ironStock=MillstoneEyeReamerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillstoneEyeReamerMaker.bronzeStock=MillstoneEyeReamerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillstoneEyeReamerMaker.woodStock=MillstoneEyeReamerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillstoneEyeReamerMaker.leatherStock=MillstoneEyeReamerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillstoneEyeReamerMaker.silverStock=MillstoneEyeReamerMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillstoneEyeReamerMaker.goldStock=MillstoneEyeReamerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillstoneEyeReamerMaker.jewelStock=MillstoneEyeReamerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillstoneEyeReamerMaker.pearlStock=MillstoneEyeReamerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillstoneEyeReamerMaker.maker then t=math.max(1,t-math.floor(MillstoneEyeReamerMaker.maker.skill/13)) end; table.insert(MillstoneEyeReamerMaker.activeMaking,{id="millstoneeyereamer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillstoneEyeReamerMaker.completeMaking(m) local q=1.0+(MillstoneEyeReamerMaker.getQualityBonus()/100); if MillstoneEyeReamerMaker.maker then q=q+(MillstoneEyeReamerMaker.maker.skill/140) end; q=math.min(2.5,q); MillstoneEyeReamerMaker.productStock[m.productType]=(MillstoneEyeReamerMaker.productStock[m.productType] or 0)+m.quantity; MillstoneEyeReamerMaker.totalProducts=MillstoneEyeReamerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillstoneEyeReamerMaker.maker then MillstoneEyeReamerMaker.maker.itemsMade=MillstoneEyeReamerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillstoneEyeReamerMaker.maker.skill=math.min(100,MillstoneEyeReamerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Razširjevalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millstoneeyereamer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillstoneEyeReamerMaker.update(dt) if not _G.state then return end; MillstoneEyeReamerMaker.dayTimer=MillstoneEyeReamerMaker.dayTimer+dt; if MillstoneEyeReamerMaker.dayTimer>=30 then MillstoneEyeReamerMaker.dayTimer=0; for i=#MillstoneEyeReamerMaker.activeMaking,1,-1 do local m=MillstoneEyeReamerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillstoneEyeReamerMaker.completeMaking(m); table.remove(MillstoneEyeReamerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillstoneEyeReamerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillstoneEyeReamerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillstoneEyeReamerMaker.getStats() return {ironStock=MillstoneEyeReamerMaker.ironStock,bronzeStock=MillstoneEyeReamerMaker.bronzeStock,woodStock=MillstoneEyeReamerMaker.woodStock,leatherStock=MillstoneEyeReamerMaker.leatherStock,silverStock=MillstoneEyeReamerMaker.silverStock,goldStock=MillstoneEyeReamerMaker.goldStock,jewelStock=MillstoneEyeReamerMaker.jewelStock,pearlStock=MillstoneEyeReamerMaker.pearlStock,productStock=MillstoneEyeReamerMaker.productStock,numBuildings=#MillstoneEyeReamerMaker.buildings,hasMaker=MillstoneEyeReamerMaker.maker~=nil,makerName=MillstoneEyeReamerMaker.maker and MillstoneEyeReamerMaker.maker.name or "—",makerSkill=MillstoneEyeReamerMaker.maker and MillstoneEyeReamerMaker.maker.skill or 0,activeMaking=#MillstoneEyeReamerMaker.activeMaking,totalProducts=MillstoneEyeReamerMaker.totalProducts} end
return MillstoneEyeReamerMaker
