local SilkReeler = {}
local PRODUCTS = {
    raw_silk = { name = "Surova svila", cocoonCost = 3, waterCost = 1, time = 2, cost = 25, quality = 30, happiness = 1, description = "Surova svila iz bub." },
    reeled_silk = { name = "Ovitki svila", cocoonCost = 4, waterCost = 1, time = 4, cost = 65, quality = 50, prestige = 2, happiness = 2, description = "Ovitki svila za predenje." },
    thrown_silk = { name = "Trda svila", cocoonCost = 4, waterCost = 1, oilCost = 1, time = 6, cost = 150, quality = 65, prestige = 4, happiness = 2, description = "Trda svila za močne tkanine." },
    spun_silk = { name = "Predena svila", cocoonCost = 5, waterCost = 1, oilCost = 1, time = 8, cost = 320, quality = 80, prestige = 7, happiness = 3, description = "Predena svila za fine halje." },
    silver_thread_silk = { name = "Srebrno nitna svila", cocoonCost = 6, silverCost = 1, waterCost = 1, oilCost = 1, time = 11, cost = 700, quality = 92, prestige = 13, happiness = 4, description = "Svila s srebrnimi nitmi za plemiče." },
    royal_grand_silk = { name = "Kraljevski veliki svila", cocoonCost = 10, goldCost = 1, silverCost = 1, jewelCost = 1, waterCost = 2, oilCost = 1, time = 16, cost = 1800, quality = 100, prestige = 38, happiness = 9, description = "Velika kraljevska svila z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Svilarska delavnica", cost = { gold = 320, wood = 140, stone = 200 }, upkeep = 8, qualityBonus = 5 },
    reeling_house = { name = "Ovijalnica", cost = { gold = 1000, wood = 280, stone = 400, cocoon = 10 }, upkeep = 25, qualityBonus = 18 },
    throwing_room = { name = "Trdilnica", cost = { gold = 2400, wood = 350, stone = 700, silver = 30, water = 10 }, upkeep = 60, qualityBonus = 30 },
    royal_silk_atelier = { name = "Kraljevski atelje svile", cost = { gold = 9500, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 40 },
}
SilkReeler.cocoonStock = 22; SilkReeler.waterStock = 18; SilkReeler.oilStock = 12; SilkReeler.silverStock = 8; SilkReeler.goldStock = 6; SilkReeler.jewelStock = 6
SilkReeler.productStock = {}; SilkReeler.buildings = {}; SilkReeler.maker = nil; SilkReeler.activeMaking = {}; SilkReeler.totalProducts = 0; SilkReeler.dayTimer = 0
function SilkReeler.init() SilkReeler.cocoonStock=22; SilkReeler.waterStock=18; SilkReeler.oilStock=12; SilkReeler.silverStock=8; SilkReeler.goldStock=6; SilkReeler.jewelStock=6; SilkReeler.productStock={}; SilkReeler.buildings={}; SilkReeler.maker=nil; SilkReeler.activeMaking={}; SilkReeler.totalProducts=0; SilkReeler.dayTimer=0; print("[SilkReeler] Royal Silk Reeler System initialized (6 products, 4 buildings)") end
function SilkReeler.hireMaker(n,s) s=s or math.random(50,90); local c=540+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SilkReeler.maker={name=n or ("Svilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Svilar najet: %s (spretnost: %d)",SilkReeler.maker.name,s),"success") end; return true end
function SilkReeler.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SilkReeler.build(id) local ok,e=SilkReeler.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SilkReeler.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SilkReeler.getQualityBonus() local b=0; for _,bd in ipairs(SilkReeler.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SilkReeler.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.cocoonCost and SilkReeler.cocoonStock<(d.cocoonCost or 0) then return false,"Premalo bub" end; if d.waterCost and SilkReeler.waterStock<(d.waterCost or 0) then return false,"Premalo vode" end; if d.oilCost and SilkReeler.oilStock<(d.oilCost or 0) then return false,"Premalo olja" end; if d.silverCost and SilkReeler.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SilkReeler.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SilkReeler.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #SilkReeler.buildings==0 then return false,"Potrebna delavnica" end; if not SilkReeler.maker then return false,"Potreben svilar" end; return true end
function SilkReeler.make(pt,qty) qty=qty or 5; local ok,e=SilkReeler.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.cocoonCost then SilkReeler.cocoonStock=SilkReeler.cocoonStock-d.cocoonCost*qty end; if d.waterCost then SilkReeler.waterStock=SilkReeler.waterStock-d.waterCost*qty end; if d.oilCost then SilkReeler.oilStock=SilkReeler.oilStock-d.oilCost*qty end; if d.silverCost then SilkReeler.silverStock=SilkReeler.silverStock-d.silverCost*qty end; if d.goldCost then SilkReeler.goldStock=SilkReeler.goldStock-d.goldCost*qty end; if d.jewelCost then SilkReeler.jewelStock=SilkReeler.jewelStock-d.jewelCost*qty end; local t=d.time; if SilkReeler.maker then t=math.max(1,t-math.floor(SilkReeler.maker.skill/12)) end; table.insert(SilkReeler.activeMaking,{id="silk_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,quality=d.quality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SilkReeler.completeMaking(m) local q=1.0+(SilkReeler.getQualityBonus()/100); if SilkReeler.maker then q=q+(SilkReeler.maker.skill/180) end; q=math.min(2.0,q); SilkReeler.productStock[m.productType]=(SilkReeler.productStock[m.productType] or 0)+m.quantity; SilkReeler.totalProducts=SilkReeler.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SilkReeler.maker then SilkReeler.maker.itemsMade=SilkReeler.maker.itemsMade+m.quantity; if math.random()<0.20 then SilkReeler.maker.skill=math.min(100,SilkReeler.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Svila izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"silk.completed",{productName=m.productName,quality=m.quality,happiness=m.happiness}) end end
function SilkReeler.update(dt) if not _G.state then return end; SilkReeler.dayTimer=SilkReeler.dayTimer+dt; if SilkReeler.dayTimer>=30 then SilkReeler.dayTimer=0; for i=#SilkReeler.activeMaking,1,-1 do local m=SilkReeler.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SilkReeler.completeMaking(m); table.remove(SilkReeler.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SilkReeler.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SilkReeler.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SilkReeler.getStats() return {cocoonStock=SilkReeler.cocoonStock,waterStock=SilkReeler.waterStock,oilStock=SilkReeler.oilStock,silverStock=SilkReeler.silverStock,goldStock=SilkReeler.goldStock,jewelStock=SilkReeler.jewelStock,productStock=SilkReeler.productStock,numBuildings=#SilkReeler.buildings,hasMaker=SilkReeler.maker~=nil,makerName=SilkReeler.maker and SilkReeler.maker.name or "—",makerSkill=SilkReeler.maker and SilkReeler.maker.skill or 0,activeMaking=#SilkReeler.activeMaking,totalProducts=SilkReeler.totalProducts} end
return SilkReeler
