local BickHornAnvilMaker = {}
local PRODUCTS = {
    iron_bickhornanvil = { name = "Železni rogasto nakovalo", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni rogasto nakovalo za kovace." },
    bronze_bickhornanvil = { name = "Bronast rogasto nakovalo", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast rogasto nakovalo za kovace." },
    silver_bickhornanvil = { name = "Srebrn rogasto nakovalo", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn rogasto nakovalo za kovace." },
    gilded_bickhornanvil = { name = "Pozlačen rogasto nakovalo", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen rogasto nakovalo za kovace." },
    jewel_set_bickhornanvil = { name = "Draguljast rogasto nakovalo", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast rogasto nakovalo za kovace." },
    royal_sovereign_bickhornanvil = { name = "Kraljevski suveren rogasto nakovalo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren rogasto nakovalo z biseri za krono." },
}
local BUILDINGS = {
    bickhornanvil_workshop = { name = "Bickhornanvil delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bickhornanvil_house = { name = "Bickhornanvil hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bickhornanvil_atelier = { name = "Mojstrski bickhornanvil atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bickhornanvil_palace = { name = "Suverena bickhornanvil palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BickHornAnvilMaker.ironStock=18; BickHornAnvilMaker.bronzeStock=14; BickHornAnvilMaker.woodStock=10; BickHornAnvilMaker.leatherStock=8; BickHornAnvilMaker.silverStock=8; BickHornAnvilMaker.goldStock=6; BickHornAnvilMaker.jewelStock=4; BickHornAnvilMaker.pearlStock=4
BickHornAnvilMaker.productStock = {}; BickHornAnvilMaker.buildings = {}; BickHornAnvilMaker.maker = nil; BickHornAnvilMaker.activeMaking = {}; BickHornAnvilMaker.totalProducts = 0; BickHornAnvilMaker.dayTimer = 0
function BickHornAnvilMaker.init() BickHornAnvilMaker.ironStock=18; BickHornAnvilMaker.bronzeStock=14; BickHornAnvilMaker.woodStock=10; BickHornAnvilMaker.leatherStock=8; BickHornAnvilMaker.silverStock=8; BickHornAnvilMaker.goldStock=6; BickHornAnvilMaker.jewelStock=4; BickHornAnvilMaker.pearlStock=4; BickHornAnvilMaker.productStock={}; BickHornAnvilMaker.buildings={}; BickHornAnvilMaker.maker=nil; BickHornAnvilMaker.activeMaking={}; BickHornAnvilMaker.totalProducts=0; BickHornAnvilMaker.dayTimer=0; print("[BickHornAnvilMaker] Royal Bick Horn Anvil Maker System initialized (6 products, 4 buildings)") end
function BickHornAnvilMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BickHornAnvilMaker.maker={name=n or ("Rogar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rogar najet: %s (spretnost: %d)",BickHornAnvilMaker.maker.name,s),"success") end; return true end
function BickHornAnvilMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BickHornAnvilMaker.build(id) local ok,e=BickHornAnvilMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BickHornAnvilMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BickHornAnvilMaker.getQualityBonus() local b=0; for _,bd in ipairs(BickHornAnvilMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BickHornAnvilMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BickHornAnvilMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BickHornAnvilMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BickHornAnvilMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BickHornAnvilMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BickHornAnvilMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BickHornAnvilMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BickHornAnvilMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BickHornAnvilMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BickHornAnvilMaker.buildings==0 then return false,"Potrebna rogna delavnica" end; if not BickHornAnvilMaker.maker then return false,"Potreben rogar" end; return true end
function BickHornAnvilMaker.make(pt,qty) qty=qty or 1; local ok,e=BickHornAnvilMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BickHornAnvilMaker.ironStock=BickHornAnvilMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BickHornAnvilMaker.bronzeStock=BickHornAnvilMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BickHornAnvilMaker.woodStock=BickHornAnvilMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BickHornAnvilMaker.leatherStock=BickHornAnvilMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BickHornAnvilMaker.silverStock=BickHornAnvilMaker.silverStock-d.silverCost*qty end; if d.goldCost then BickHornAnvilMaker.goldStock=BickHornAnvilMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BickHornAnvilMaker.jewelStock=BickHornAnvilMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BickHornAnvilMaker.pearlStock=BickHornAnvilMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BickHornAnvilMaker.maker then t=math.max(1,t-math.floor(BickHornAnvilMaker.maker.skill/13)) end; table.insert(BickHornAnvilMaker.activeMaking,{id="bickhornanvil_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BickHornAnvilMaker.completeMaking(m) local q=1.0+(BickHornAnvilMaker.getQualityBonus()/100); if BickHornAnvilMaker.maker then q=q+(BickHornAnvilMaker.maker.skill/140) end; q=math.min(2.5,q); BickHornAnvilMaker.productStock[m.productType]=(BickHornAnvilMaker.productStock[m.productType] or 0)+m.quantity; BickHornAnvilMaker.totalProducts=BickHornAnvilMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BickHornAnvilMaker.maker then BickHornAnvilMaker.maker.itemsMade=BickHornAnvilMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BickHornAnvilMaker.maker.skill=math.min(100,BickHornAnvilMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rog izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bickhornanvil.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BickHornAnvilMaker.update(dt) if not _G.state then return end; BickHornAnvilMaker.dayTimer=BickHornAnvilMaker.dayTimer+dt; if BickHornAnvilMaker.dayTimer>=30 then BickHornAnvilMaker.dayTimer=0; for i=#BickHornAnvilMaker.activeMaking,1,-1 do local m=BickHornAnvilMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BickHornAnvilMaker.completeMaking(m); table.remove(BickHornAnvilMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BickHornAnvilMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BickHornAnvilMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BickHornAnvilMaker.getStats() return {ironStock=BickHornAnvilMaker.ironStock,bronzeStock=BickHornAnvilMaker.bronzeStock,woodStock=BickHornAnvilMaker.woodStock,leatherStock=BickHornAnvilMaker.leatherStock,silverStock=BickHornAnvilMaker.silverStock,goldStock=BickHornAnvilMaker.goldStock,jewelStock=BickHornAnvilMaker.jewelStock,pearlStock=BickHornAnvilMaker.pearlStock,productStock=BickHornAnvilMaker.productStock,numBuildings=#BickHornAnvilMaker.buildings,hasMaker=BickHornAnvilMaker.maker~=nil,makerName=BickHornAnvilMaker.maker and BickHornAnvilMaker.maker.name or "—",makerSkill=BickHornAnvilMaker.maker and BickHornAnvilMaker.maker.skill or 0,activeMaking=#BickHornAnvilMaker.activeMaking,totalProducts=BickHornAnvilMaker.totalProducts} end
return BickHornAnvilMaker
