local CarillonMaker = {}
local PRODUCTS = {
    bronze_hand_carillon = { name = "Bronasti ročni kariljon", bronzeCost = 2, ironCost = 1, woodCost = 2, time = 6, cost = 220, happiness = 2, prestige = 3, description = "Bronasti ročni kariljon za kapelo." },
    iron_tower_carillon = { name = "Železni stolpni kariljon", bronzeCost = 2, ironCost = 3, woodCost = 2, time = 9, cost = 540, happiness = 3, prestige = 7, description = "Stolpni kariljon z železnimi zvonovi." },
    silver_tuned_carillon = { name = "Srebrno uglašen kariljon", bronzeCost = 2, silverCost = 2, ironCost = 2, woodCost = 2, time = 13, cost = 1300, happiness = 4, prestige = 14, description = "Srebrno uglašen kariljon za katedralo." },
    gilded_ceremonial_carillon = { name = "Pozlačeni slavnostni kariljon", bronzeCost = 2, goldCost = 1, silverCost = 2, ironCost = 2, woodCost = 2, time = 17, cost = 2800, happiness = 5, prestige = 25, description = "Pozlačeni slavnostni kariljon za plemstvo." },
    jewel_set_royal_carillon = { name = "Draguljasta kraljevski kariljon", bronzeCost = 3, goldCost = 2, silverCost = 2, jewelCost = 1, ironCost = 2, woodCost = 2, time = 21, cost = 5800, happiness = 7, prestige = 44, description = "Draguljasti kariljon za kraljevo kapelo." },
    sovereign_grand_carillon = { name = "Suvereni veliki kariljon", bronzeCost = 4, goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, ironCost = 2, woodCost = 3, time = 28, cost = 12000, happiness = 13, prestige = 82, description = "Veliki suvereni kariljon z biseri za krono." },
}
local BUILDINGS = {
    carillon_workshop = { name = "Kariljonska delavnica", cost = { gold = 380, wood = 180, stone = 140, iron = 8 }, upkeep = 7, qualityBonus = 5 },
    bell_foundry_annex = { name = "Zvonolivarski priključek", cost = { gold = 1300, wood = 360, stone = 280, silver = 8, iron = 8 }, upkeep = 28, qualityBonus = 18 },
    master_carillon_atelier = { name = "Mojstrski kariljonski atelje", cost = { gold = 3200, wood = 420, stone = 540, silver = 38, gold = 8 }, upkeep = 75, qualityBonus = 30 },
    sovereign_campanile_palace = { name = "Suverena kampanilna palača", cost = { gold = 14000, wood = 700, stone = 900, gold = 90, jewel = 20 }, upkeep = 260, qualityBonus = 55, prestigeBonus = 50 },
}
CarillonMaker.bronzeStock = 14; CarillonMaker.ironStock = 10; CarillonMaker.woodStock = 14; CarillonMaker.silverStock = 8; CarillonMaker.goldStock = 6; CarillonMaker.jewelStock = 4; CarillonMaker.pearlStock = 4
CarillonMaker.productStock = {}; CarillonMaker.buildings = {}; CarillonMaker.maker = nil; CarillonMaker.activeMaking = {}; CarillonMaker.totalProducts = 0; CarillonMaker.dayTimer = 0
function CarillonMaker.init() CarillonMaker.bronzeStock=14; CarillonMaker.ironStock=10; CarillonMaker.woodStock=14; CarillonMaker.silverStock=8; CarillonMaker.goldStock=6; CarillonMaker.jewelStock=4; CarillonMaker.pearlStock=4; CarillonMaker.productStock={}; CarillonMaker.buildings={}; CarillonMaker.maker=nil; CarillonMaker.activeMaking={}; CarillonMaker.totalProducts=0; CarillonMaker.dayTimer=0; print("[CarillonMaker] Royal Carillon Maker System initialized (6 products, 4 buildings)") end
function CarillonMaker.hireMaker(n,s) s=s or math.random(55,90); local c=620+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CarillonMaker.maker={name=n or ("Kariljonar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kariljonar najet: %s (spretnost: %d)",CarillonMaker.maker.name,s),"success") end; return true end
function CarillonMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CarillonMaker.build(id) local ok,e=CarillonMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CarillonMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CarillonMaker.getQualityBonus() local b=0; for _,bd in ipairs(CarillonMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CarillonMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.bronzeCost and CarillonMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.ironCost and CarillonMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.woodCost and CarillonMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.silverCost and CarillonMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CarillonMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CarillonMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CarillonMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CarillonMaker.buildings==0 then return false,"Potrebna kariljonska delavnica" end; if not CarillonMaker.maker then return false,"Potreben kariljonar" end; return true end
function CarillonMaker.make(pt,qty) qty=qty or 1; local ok,e=CarillonMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.bronzeCost then CarillonMaker.bronzeStock=CarillonMaker.bronzeStock-d.bronzeCost*qty end; if d.ironCost then CarillonMaker.ironStock=CarillonMaker.ironStock-d.ironCost*qty end; if d.woodCost then CarillonMaker.woodStock=CarillonMaker.woodStock-d.woodCost*qty end; if d.silverCost then CarillonMaker.silverStock=CarillonMaker.silverStock-d.silverCost*qty end; if d.goldCost then CarillonMaker.goldStock=CarillonMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CarillonMaker.jewelStock=CarillonMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CarillonMaker.pearlStock=CarillonMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CarillonMaker.maker then t=math.max(1,t-math.floor(CarillonMaker.maker.skill/13)) end; table.insert(CarillonMaker.activeMaking,{id="carillon_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CarillonMaker.completeMaking(m) local q=1.0+(CarillonMaker.getQualityBonus()/100); if CarillonMaker.maker then q=q+(CarillonMaker.maker.skill/140) end; q=math.min(2.5,q); CarillonMaker.productStock[m.productType]=(CarillonMaker.productStock[m.productType] or 0)+m.quantity; CarillonMaker.totalProducts=CarillonMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CarillonMaker.maker then CarillonMaker.maker.itemsMade=CarillonMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CarillonMaker.maker.skill=math.min(100,CarillonMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kariljon izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"carillon.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CarillonMaker.update(dt) if not _G.state then return end; CarillonMaker.dayTimer=CarillonMaker.dayTimer+dt; if CarillonMaker.dayTimer>=30 then CarillonMaker.dayTimer=0; for i=#CarillonMaker.activeMaking,1,-1 do local m=CarillonMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CarillonMaker.completeMaking(m); table.remove(CarillonMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CarillonMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CarillonMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CarillonMaker.getStats() return {bronzeStock=CarillonMaker.bronzeStock,ironStock=CarillonMaker.ironStock,woodStock=CarillonMaker.woodStock,silverStock=CarillonMaker.silverStock,goldStock=CarillonMaker.goldStock,jewelStock=CarillonMaker.jewelStock,pearlStock=CarillonMaker.pearlStock,productStock=CarillonMaker.productStock,numBuildings=#CarillonMaker.buildings,hasMaker=CarillonMaker.maker~=nil,makerName=CarillonMaker.maker and CarillonMaker.maker.name or "—",makerSkill=CarillonMaker.maker and CarillonMaker.maker.skill or 0,activeMaking=#CarillonMaker.activeMaking,totalProducts=CarillonMaker.totalProducts} end
return CarillonMaker
