local HandbellMaker = {}
local PRODUCTS = {
    plain_bronze_handbell = { name = "Preprosta bronasta ročna zvončnica", bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 4, cost = 110, happiness = 1, prestige = 1, description = "Preprosta ročna zvončnica za službe." },
    brass_choir_handbell = { name = "Medeninasta zborovska zvončnica", brassCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 280, happiness = 2, prestige = 4, description = "Zborovska zvončnica za procesije." },
    silver_tuned_handbell = { name = "Srebrno uglašena zvončnica", silverCost = 1, brassCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 10, cost = 720, happiness = 3, prestige = 9, description = "Srebrno uglašena zvončnica za plemiče." },
    gilded_ceremonial_handbell = { name = "Pozlačena slavnostna zvončnica", goldCost = 1, silverCost = 1, brassCost = 1, woodCost = 2, leatherCost = 1, time = 14, cost = 1700, happiness = 4, prestige = 18, description = "Pozlačena slavnostna zvončnica za dvor." },
    jewel_set_royal_handbell = { name = "Draguljasta kraljevska zvončnica", goldCost = 1, silverCost = 1, jewelCost = 1, brassCost = 1, woodCost = 2, leatherCost = 1, time = 18, cost = 3700, happiness = 6, prestige = 33, description = "Draguljasta zvončnica za krono." },
    sovereign_peal_handbell = { name = "Suvereni zvončničenje zvonec", goldCost = 2, silverCost = 2, jewelCost = 2, pearlCost = 2, brassCost = 1, woodCost = 3, leatherCost = 1, time = 25, cost = 8000, happiness = 12, prestige = 64, description = "Suvereni zvonec z biseri za kronanje." },
}
local BUILDINGS = {
    handbell_workshop = { name = "Zvončničarska delavnica", cost = { gold = 300, wood = 160, stone = 100, leather = 4 }, upkeep = 5, qualityBonus = 5 },
    bell_ring_guild = { name = "Zvončničarski ceh", cost = { gold = 1100, wood = 320, stone = 220, silver = 6, leather = 6 }, upkeep = 23, qualityBonus = 18 },
    master_handbell_atelier = { name = "Mojstrski zvončničarski atelje", cost = { gold = 2900, wood = 380, stone = 460, silver = 32, gold = 6 }, upkeep = 67, qualityBonus = 30 },
    sovereign_campanology_palace = { name = "Suverena kampanološka palača", cost = { gold = 12500, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 245, qualityBonus = 55, prestigeBonus = 50 },
}
HandbellMaker.bronzeStock = 12; HandbellMaker.brassStock = 10; HandbellMaker.woodStock = 14; HandbellMaker.leatherStock = 10; HandbellMaker.silverStock = 8; HandbellMaker.goldStock = 6; HandbellMaker.jewelStock = 4; HandbellMaker.pearlStock = 4
HandbellMaker.productStock = {}; HandbellMaker.buildings = {}; HandbellMaker.maker = nil; HandbellMaker.activeMaking = {}; HandbellMaker.totalProducts = 0; HandbellMaker.dayTimer = 0
function HandbellMaker.init() HandbellMaker.bronzeStock=12; HandbellMaker.brassStock=10; HandbellMaker.woodStock=14; HandbellMaker.leatherStock=10; HandbellMaker.silverStock=8; HandbellMaker.goldStock=6; HandbellMaker.jewelStock=4; HandbellMaker.pearlStock=4; HandbellMaker.productStock={}; HandbellMaker.buildings={}; HandbellMaker.maker=nil; HandbellMaker.activeMaking={}; HandbellMaker.totalProducts=0; HandbellMaker.dayTimer=0; print("[HandbellMaker] Royal Handbell Maker System initialized (6 products, 4 buildings)") end
function HandbellMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HandbellMaker.maker={name=n or ("Zvončničar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zvončničar najet: %s (spretnost: %d)",HandbellMaker.maker.name,s),"success") end; return true end
function HandbellMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HandbellMaker.build(id) local ok,e=HandbellMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HandbellMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HandbellMaker.getQualityBonus() local b=0; for _,bd in ipairs(HandbellMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HandbellMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.bronzeCost and HandbellMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.brassCost and HandbellMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.woodCost and HandbellMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and HandbellMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and HandbellMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HandbellMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HandbellMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HandbellMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HandbellMaker.buildings==0 then return false,"Potrebna zvončničarska delavnica" end; if not HandbellMaker.maker then return false,"Potreben zvončničar" end; return true end
function HandbellMaker.make(pt,qty) qty=qty or 1; local ok,e=HandbellMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.bronzeCost then HandbellMaker.bronzeStock=HandbellMaker.bronzeStock-d.bronzeCost*qty end; if d.brassCost then HandbellMaker.brassStock=HandbellMaker.brassStock-d.brassCost*qty end; if d.woodCost then HandbellMaker.woodStock=HandbellMaker.woodStock-d.woodCost*qty end; if d.leatherCost then HandbellMaker.leatherStock=HandbellMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then HandbellMaker.silverStock=HandbellMaker.silverStock-d.silverCost*qty end; if d.goldCost then HandbellMaker.goldStock=HandbellMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HandbellMaker.jewelStock=HandbellMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HandbellMaker.pearlStock=HandbellMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HandbellMaker.maker then t=math.max(1,t-math.floor(HandbellMaker.maker.skill/13)) end; table.insert(HandbellMaker.activeMaking,{id="handbell_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HandbellMaker.completeMaking(m) local q=1.0+(HandbellMaker.getQualityBonus()/100); if HandbellMaker.maker then q=q+(HandbellMaker.maker.skill/140) end; q=math.min(2.5,q); HandbellMaker.productStock[m.productType]=(HandbellMaker.productStock[m.productType] or 0)+m.quantity; HandbellMaker.totalProducts=HandbellMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HandbellMaker.maker then HandbellMaker.maker.itemsMade=HandbellMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then HandbellMaker.maker.skill=math.min(100,HandbellMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zvončnica izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"handbell.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function HandbellMaker.update(dt) if not _G.state then return end; HandbellMaker.dayTimer=HandbellMaker.dayTimer+dt; if HandbellMaker.dayTimer>=30 then HandbellMaker.dayTimer=0; for i=#HandbellMaker.activeMaking,1,-1 do local m=HandbellMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HandbellMaker.completeMaking(m); table.remove(HandbellMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HandbellMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HandbellMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HandbellMaker.getStats() return {bronzeStock=HandbellMaker.bronzeStock,brassStock=HandbellMaker.brassStock,woodStock=HandbellMaker.woodStock,leatherStock=HandbellMaker.leatherStock,silverStock=HandbellMaker.silverStock,goldStock=HandbellMaker.goldStock,jewelStock=HandbellMaker.jewelStock,pearlStock=HandbellMaker.pearlStock,productStock=HandbellMaker.productStock,numBuildings=#HandbellMaker.buildings,hasMaker=HandbellMaker.maker~=nil,makerName=HandbellMaker.maker and HandbellMaker.maker.name or "—",makerSkill=HandbellMaker.maker and HandbellMaker.maker.skill or 0,activeMaking=#HandbellMaker.activeMaking,totalProducts=HandbellMaker.totalProducts} end
return HandbellMaker
