local DyeVatMaker = {}
local PRODUCTS = {
    simple_clay_dye_vat = { name = "Preprosta glinena barvilska kad", clayCost = 3, woodCost = 1, time = 4, cost = 60, science = 18, happiness = 1, description = "Preprosta glinena barvilska kad za barvanje." },
    iron_rimmed_dye_vat = { name = "Železnorobna barvilska kad", clayCost = 3, ironCost = 1, woodCost = 1, time = 6, cost = 160, science = 32, happiness = 1, prestige = 2, description = "Železnorobna barvilska kad za trgovce." },
    silver_trimmed_dye_vat = { name = "Srebrnoobrobljena barvilska kad", clayCost = 3, silverCost = 1, ironCost = 1, woodCost = 1, time = 9, cost = 400, science = 48, happiness = 2, prestige = 6, description = "Srebrnoobrobljena barvilska kad za plemiče." },
    gold_trimmed_dye_vat = { name = "Zlatookrasna barvilska kad", clayCost = 3, goldCost = 1, silverCost = 1, ironCost = 1, woodCost = 1, time = 13, cost = 950, science = 62, happiness = 3, prestige = 14, description = "Zlatookrasna barvilska kad za visoke plemiče." },
    jewel_set_dye_vat = { name = "Draguljasta barvilska kad", clayCost = 3, goldCost = 1, silverCost = 1, ironCost = 1, woodCost = 1, jewelCost = 1, time = 17, cost = 2100, science = 78, happiness = 5, prestige = 27, description = "Barvilska kad z draguljem za visoko plemstvo." },
    royal_grand_dye_vat = { name = "Kraljevski veliki barvilska kad", clayCost = 4, goldCost = 2, silverCost = 2, ironCost = 1, woodCost = 1, jewelCost = 2, pearlCost = 2, time = 24, cost = 4500, science = 92, happiness = 12, prestige = 58, description = "Velika kraljevska barvilska kad z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    dye_vat_workshop = { name = "Barvilska kadna delavnica", cost = { gold = 260, wood = 120, stone = 120, clay = 6 }, upkeep = 6, qualityBonus = 5 },
    textile_loft = { name = "Tekstilna podstrešje", cost = { gold = 950, wood = 280, stone = 240, silver = 6, iron = 6 }, upkeep = 22, qualityBonus = 18 },
    master_vat_atelier = { name = "Mojstrski barvilski atelje", cost = { gold = 2700, wood = 380, stone = 480, silver = 32, gold = 6 }, upkeep = 62, qualityBonus = 30 },
    royal_textile_palace = { name = "Kraljevska tekstilna palača", cost = { gold = 11500, wood = 580, stone = 760, gold = 75, jewel = 18 }, upkeep = 230, qualityBonus = 55, prestigeBonus = 50 },
}
DyeVatMaker.clayStock = 14; DyeVatMaker.woodStock = 10; DyeVatMaker.ironStock = 10; DyeVatMaker.silverStock = 6; DyeVatMaker.goldStock = 6; DyeVatMaker.jewelStock = 4; DyeVatMaker.pearlStock = 4
DyeVatMaker.productStock = {}; DyeVatMaker.buildings = {}; DyeVatMaker.maker = nil; DyeVatMaker.activeMaking = {}; DyeVatMaker.totalProducts = 0; DyeVatMaker.dayTimer = 0
function DyeVatMaker.init() DyeVatMaker.clayStock=14; DyeVatMaker.woodStock=10; DyeVatMaker.ironStock=10; DyeVatMaker.silverStock=6; DyeVatMaker.goldStock=6; DyeVatMaker.jewelStock=4; DyeVatMaker.pearlStock=4; DyeVatMaker.productStock={}; DyeVatMaker.buildings={}; DyeVatMaker.maker=nil; DyeVatMaker.activeMaking={}; DyeVatMaker.totalProducts=0; DyeVatMaker.dayTimer=0; print("[DyeVatMaker] Royal Dye Vat Maker System initialized (6 products, 4 buildings)") end
function DyeVatMaker.hireMaker(n,s) s=s or math.random(55,90); local c=540+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; DyeVatMaker.maker={name=n or ("Barvilski kadar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Barvilski kadar najet: %s (spretnost: %d)",DyeVatMaker.maker.name,s),"success") end; return true end
function DyeVatMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function DyeVatMaker.build(id) local ok,e=DyeVatMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(DyeVatMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function DyeVatMaker.getQualityBonus() local b=0; for _,bd in ipairs(DyeVatMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function DyeVatMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.clayCost and DyeVatMaker.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.woodCost and DyeVatMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and DyeVatMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.silverCost and DyeVatMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and DyeVatMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and DyeVatMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and DyeVatMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #DyeVatMaker.buildings==0 then return false,"Potrebna barvilska kadna delavnica" end; if not DyeVatMaker.maker then return false,"Potreben barvilski kadar" end; return true end
function DyeVatMaker.make(pt,qty) qty=qty or 1; local ok,e=DyeVatMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.clayCost then DyeVatMaker.clayStock=DyeVatMaker.clayStock-d.clayCost*qty end; if d.woodCost then DyeVatMaker.woodStock=DyeVatMaker.woodStock-d.woodCost*qty end; if d.ironCost then DyeVatMaker.ironStock=DyeVatMaker.ironStock-d.ironCost*qty end; if d.silverCost then DyeVatMaker.silverStock=DyeVatMaker.silverStock-d.silverCost*qty end; if d.goldCost then DyeVatMaker.goldStock=DyeVatMaker.goldStock-d.goldCost*qty end; if d.jewelCost then DyeVatMaker.jewelStock=DyeVatMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then DyeVatMaker.pearlStock=DyeVatMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if DyeVatMaker.maker then t=math.max(1,t-math.floor(DyeVatMaker.maker.skill/13)) end; table.insert(DyeVatMaker.activeMaking,{id="dyevat_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function DyeVatMaker.completeMaking(m) local q=1.0+(DyeVatMaker.getQualityBonus()/100); if DyeVatMaker.maker then q=q+(DyeVatMaker.maker.skill/140) end; q=math.min(2.5,q); DyeVatMaker.productStock[m.productType]=(DyeVatMaker.productStock[m.productType] or 0)+m.quantity; DyeVatMaker.totalProducts=DyeVatMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if DyeVatMaker.maker then DyeVatMaker.maker.itemsMade=DyeVatMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then DyeVatMaker.maker.skill=math.min(100,DyeVatMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Barvilska kad izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"dyevat.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function DyeVatMaker.update(dt) if not _G.state then return end; DyeVatMaker.dayTimer=DyeVatMaker.dayTimer+dt; if DyeVatMaker.dayTimer>=30 then DyeVatMaker.dayTimer=0; for i=#DyeVatMaker.activeMaking,1,-1 do local m=DyeVatMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then DyeVatMaker.completeMaking(m); table.remove(DyeVatMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(DyeVatMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if DyeVatMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function DyeVatMaker.getStats() return {clayStock=DyeVatMaker.clayStock,woodStock=DyeVatMaker.woodStock,ironStock=DyeVatMaker.ironStock,silverStock=DyeVatMaker.silverStock,goldStock=DyeVatMaker.goldStock,jewelStock=DyeVatMaker.jewelStock,pearlStock=DyeVatMaker.pearlStock,productStock=DyeVatMaker.productStock,numBuildings=#DyeVatMaker.buildings,hasMaker=DyeVatMaker.maker~=nil,makerName=DyeVatMaker.maker and DyeVatMaker.maker.name or "—",makerSkill=DyeVatMaker.maker and DyeVatMaker.maker.skill or 0,activeMaking=#DyeVatMaker.activeMaking,totalProducts=DyeVatMaker.totalProducts} end
return DyeVatMaker
