local ClayExtruderMaker = {}
local PRODUCTS = {
    iron_clay_extruder = { name = "Železni ekstruder za glino", ironCost = 4, woodCost = 2, leatherCost = 1, time = 5, cost = 170, prestige = 4, happiness = 2, description = "Železni ekstruder za oblikovanje gline." },
    bronze_clay_extruder = { name = "Bronast ekstruder za glino", bronzeCost = 4, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 410, prestige = 6, happiness = 3, description = "Bronast ekstruder za enakomerne oblike." },
    silver_clay_extruder = { name = "Srebrni ekstruder za glino", silverCost = 4, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 990, prestige = 11, happiness = 4, description = "Srebrni ekstruder za plemiške lončarje." },
    gilded_clay_extruder = { name = "Pozlačeni ekstruder za glino", goldCost = 1, silverCost = 4, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 2130, prestige = 20, happiness = 5, description = "Pozlačeni ekstruder za dvorne lončarje." },
    jewel_set_clay_extruder = { name = "Draguljasti ekstruder za glino", goldCost = 2, silverCost = 4, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4600, prestige = 36, happiness = 7, description = "Draguljasti ekstruder za kraljevske lončarje." },
    royal_sovereign_clay_extruder = { name = "Kraljevski suvereni ekstruder za glino", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 9800, prestige = 69, happiness = 13, description = "Suvereni ekstruder z biseri za krono." },
}
local BUILDINGS = {
    clayextruder_workshop = { name = "Ekstruderska delavnica", cost = { gold = 350, wood = 185, stone = 135, iron = 9 }, upkeep = 6, qualityBonus = 5 },
    clayextruder_house = { name = "Ekstruderska hiša", cost = { gold = 1240, wood = 370, stone = 275, silver = 7, iron = 8 }, upkeep = 26, qualityBonus = 18 },
    master_clayextruder_atelier = { name = "Mojstrski ekstruderski atelje", cost = { gold = 3100, wood = 430, stone = 525, silver = 36, gold = 7 }, upkeep = 73, qualityBonus = 30 },
    sovereign_clayextruder_palace = { name = "Suverena ekstruderska palača", cost = { gold = 13200, wood = 650, stone = 835, gold = 85, jewel = 19 }, upkeep = 258, qualityBonus = 55, prestigeBonus = 50 },
}
ClayExtruderMaker.ironStock = 16; ClayExtruderMaker.bronzeStock = 12; ClayExtruderMaker.woodStock = 14; ClayExtruderMaker.leatherStock = 10; ClayExtruderMaker.silverStock = 8; ClayExtruderMaker.goldStock = 6; ClayExtruderMaker.jewelStock = 4; ClayExtruderMaker.pearlStock = 4
ClayExtruderMaker.productStock = {}; ClayExtruderMaker.buildings = {}; ClayExtruderMaker.maker = nil; ClayExtruderMaker.activeMaking = {}; ClayExtruderMaker.totalProducts = 0; ClayExtruderMaker.dayTimer = 0
function ClayExtruderMaker.init() ClayExtruderMaker.ironStock=16; ClayExtruderMaker.bronzeStock=12; ClayExtruderMaker.woodStock=14; ClayExtruderMaker.leatherStock=10; ClayExtruderMaker.silverStock=8; ClayExtruderMaker.goldStock=6; ClayExtruderMaker.jewelStock=4; ClayExtruderMaker.pearlStock=4; ClayExtruderMaker.productStock={}; ClayExtruderMaker.buildings={}; ClayExtruderMaker.maker=nil; ClayExtruderMaker.activeMaking={}; ClayExtruderMaker.totalProducts=0; ClayExtruderMaker.dayTimer=0; print("[ClayExtruderMaker] Royal Clay Extruder Maker System initialized (6 products, 4 buildings)") end
function ClayExtruderMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ClayExtruderMaker.maker={name=n or ("Ekstruderar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ekstruderar najet: %s (spretnost: %d)",ClayExtruderMaker.maker.name,s),"success") end; return true end
function ClayExtruderMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ClayExtruderMaker.build(id) local ok,e=ClayExtruderMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ClayExtruderMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ClayExtruderMaker.getQualityBonus() local b=0; for _,bd in ipairs(ClayExtruderMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ClayExtruderMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ClayExtruderMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and ClayExtruderMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ClayExtruderMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ClayExtruderMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ClayExtruderMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ClayExtruderMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ClayExtruderMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ClayExtruderMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ClayExtruderMaker.buildings==0 then return false,"Potrebna ekstruderska delavnica" end; if not ClayExtruderMaker.maker then return false,"Potreben ekstruderar" end; return true end
function ClayExtruderMaker.make(pt,qty) qty=qty or 1; local ok,e=ClayExtruderMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ClayExtruderMaker.ironStock=ClayExtruderMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ClayExtruderMaker.bronzeStock=ClayExtruderMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ClayExtruderMaker.woodStock=ClayExtruderMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ClayExtruderMaker.leatherStock=ClayExtruderMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ClayExtruderMaker.silverStock=ClayExtruderMaker.silverStock-d.silverCost*qty end; if d.goldCost then ClayExtruderMaker.goldStock=ClayExtruderMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ClayExtruderMaker.jewelStock=ClayExtruderMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ClayExtruderMaker.pearlStock=ClayExtruderMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ClayExtruderMaker.maker then t=math.max(1,t-math.floor(ClayExtruderMaker.maker.skill/13)) end; table.insert(ClayExtruderMaker.activeMaking,{id="clayextruder_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ClayExtruderMaker.completeMaking(m) local q=1.0+(ClayExtruderMaker.getQualityBonus()/100); if ClayExtruderMaker.maker then q=q+(ClayExtruderMaker.maker.skill/140) end; q=math.min(2.5,q); ClayExtruderMaker.productStock[m.productType]=(ClayExtruderMaker.productStock[m.productType] or 0)+m.quantity; ClayExtruderMaker.totalProducts=ClayExtruderMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ClayExtruderMaker.maker then ClayExtruderMaker.maker.itemsMade=ClayExtruderMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ClayExtruderMaker.maker.skill=math.min(100,ClayExtruderMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ekstruder izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"clayextruder.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ClayExtruderMaker.update(dt) if not _G.state then return end; ClayExtruderMaker.dayTimer=ClayExtruderMaker.dayTimer+dt; if ClayExtruderMaker.dayTimer>=30 then ClayExtruderMaker.dayTimer=0; for i=#ClayExtruderMaker.activeMaking,1,-1 do local m=ClayExtruderMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ClayExtruderMaker.completeMaking(m); table.remove(ClayExtruderMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ClayExtruderMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ClayExtruderMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ClayExtruderMaker.getStats() return {ironStock=ClayExtruderMaker.ironStock,bronzeStock=ClayExtruderMaker.bronzeStock,woodStock=ClayExtruderMaker.woodStock,leatherStock=ClayExtruderMaker.leatherStock,silverStock=ClayExtruderMaker.silverStock,goldStock=ClayExtruderMaker.goldStock,jewelStock=ClayExtruderMaker.jewelStock,pearlStock=ClayExtruderMaker.pearlStock,productStock=ClayExtruderMaker.productStock,numBuildings=#ClayExtruderMaker.buildings,hasMaker=ClayExtruderMaker.maker~=nil,makerName=ClayExtruderMaker.maker and ClayExtruderMaker.maker.name or "—",makerSkill=ClayExtruderMaker.maker and ClayExtruderMaker.maker.skill or 0,activeMaking=#ClayExtruderMaker.activeMaking,totalProducts=ClayExtruderMaker.totalProducts} end
return ClayExtruderMaker
