local BookCoverPasteRollerMaker = {}
local PRODUCTS = {
    iron_bookcoverpasteroller = { name = "Železni valj za pasto naslovnic", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni valj za pasto naslovnic za knjigoveze." },
    bronze_bookcoverpasteroller = { name = "Bronast valj za pasto naslovnic", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast valj za pasto naslovnic za knjigoveze." },
    silver_bookcoverpasteroller = { name = "Srebrn valj za pasto naslovnic", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn valj za pasto naslovnic za knjigoveze." },
    gilded_bookcoverpasteroller = { name = "Pozlačen valj za pasto naslovnic", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen valj za pasto naslovnic za knjigoveze." },
    jewel_set_bookcoverpasteroller = { name = "Draguljast valj za pasto naslovnic", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast valj za pasto naslovnic za knjigoveze." },
    royal_sovereign_bookcoverpasteroller = { name = "Kraljevski suveren valj za pasto naslovnic", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren valj za pasto naslovnic z biseri za krono." },
}
local BUILDINGS = {
    bookcoverpasteroller_workshop = { name = "Bookcoverpasteroller delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookcoverpasteroller_house = { name = "Bookcoverpasteroller hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookcoverpasteroller_atelier = { name = "Mojstrski bookcoverpasteroller atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookcoverpasteroller_palace = { name = "Suverena bookcoverpasteroller palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookCoverPasteRollerMaker.ironStock=14; BookCoverPasteRollerMaker.bronzeStock=12; BookCoverPasteRollerMaker.woodStock=14; BookCoverPasteRollerMaker.leatherStock=8; BookCoverPasteRollerMaker.silverStock=8; BookCoverPasteRollerMaker.goldStock=6; BookCoverPasteRollerMaker.jewelStock=4; BookCoverPasteRollerMaker.pearlStock=4
BookCoverPasteRollerMaker.productStock = {}; BookCoverPasteRollerMaker.buildings = {}; BookCoverPasteRollerMaker.maker = nil; BookCoverPasteRollerMaker.activeMaking = {}; BookCoverPasteRollerMaker.totalProducts = 0; BookCoverPasteRollerMaker.dayTimer = 0
function BookCoverPasteRollerMaker.init() BookCoverPasteRollerMaker.ironStock=14; BookCoverPasteRollerMaker.bronzeStock=12; BookCoverPasteRollerMaker.woodStock=14; BookCoverPasteRollerMaker.leatherStock=8; BookCoverPasteRollerMaker.silverStock=8; BookCoverPasteRollerMaker.goldStock=6; BookCoverPasteRollerMaker.jewelStock=4; BookCoverPasteRollerMaker.pearlStock=4; BookCoverPasteRollerMaker.productStock={}; BookCoverPasteRollerMaker.buildings={}; BookCoverPasteRollerMaker.maker=nil; BookCoverPasteRollerMaker.activeMaking={}; BookCoverPasteRollerMaker.totalProducts=0; BookCoverPasteRollerMaker.dayTimer=0; print("[BookCoverPasteRollerMaker] Royal Book Cover Paste Roller Maker System initialized (6 products, 4 buildings)") end
function BookCoverPasteRollerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookCoverPasteRollerMaker.maker={name=n or ("Valjar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Valjar najet: %s (spretnost: %d)",BookCoverPasteRollerMaker.maker.name,s),"success") end; return true end
function BookCoverPasteRollerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookCoverPasteRollerMaker.build(id) local ok,e=BookCoverPasteRollerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookCoverPasteRollerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookCoverPasteRollerMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookCoverPasteRollerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookCoverPasteRollerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookCoverPasteRollerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookCoverPasteRollerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookCoverPasteRollerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookCoverPasteRollerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookCoverPasteRollerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookCoverPasteRollerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookCoverPasteRollerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookCoverPasteRollerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookCoverPasteRollerMaker.buildings==0 then return false,"Potrebna valjarna delavnica" end; if not BookCoverPasteRollerMaker.maker then return false,"Potreben valjar" end; return true end
function BookCoverPasteRollerMaker.make(pt,qty) qty=qty or 1; local ok,e=BookCoverPasteRollerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookCoverPasteRollerMaker.ironStock=BookCoverPasteRollerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookCoverPasteRollerMaker.bronzeStock=BookCoverPasteRollerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookCoverPasteRollerMaker.woodStock=BookCoverPasteRollerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookCoverPasteRollerMaker.leatherStock=BookCoverPasteRollerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookCoverPasteRollerMaker.silverStock=BookCoverPasteRollerMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookCoverPasteRollerMaker.goldStock=BookCoverPasteRollerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookCoverPasteRollerMaker.jewelStock=BookCoverPasteRollerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookCoverPasteRollerMaker.pearlStock=BookCoverPasteRollerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookCoverPasteRollerMaker.maker then t=math.max(1,t-math.floor(BookCoverPasteRollerMaker.maker.skill/13)) end; table.insert(BookCoverPasteRollerMaker.activeMaking,{id="bookcoverpasteroller_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookCoverPasteRollerMaker.completeMaking(m) local q=1.0+(BookCoverPasteRollerMaker.getQualityBonus()/100); if BookCoverPasteRollerMaker.maker then q=q+(BookCoverPasteRollerMaker.maker.skill/140) end; q=math.min(2.5,q); BookCoverPasteRollerMaker.productStock[m.productType]=(BookCoverPasteRollerMaker.productStock[m.productType] or 0)+m.quantity; BookCoverPasteRollerMaker.totalProducts=BookCoverPasteRollerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookCoverPasteRollerMaker.maker then BookCoverPasteRollerMaker.maker.itemsMade=BookCoverPasteRollerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookCoverPasteRollerMaker.maker.skill=math.min(100,BookCoverPasteRollerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Valj izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookcoverpasteroller.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookCoverPasteRollerMaker.update(dt) if not _G.state then return end; BookCoverPasteRollerMaker.dayTimer=BookCoverPasteRollerMaker.dayTimer+dt; if BookCoverPasteRollerMaker.dayTimer>=30 then BookCoverPasteRollerMaker.dayTimer=0; for i=#BookCoverPasteRollerMaker.activeMaking,1,-1 do local m=BookCoverPasteRollerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookCoverPasteRollerMaker.completeMaking(m); table.remove(BookCoverPasteRollerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookCoverPasteRollerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookCoverPasteRollerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookCoverPasteRollerMaker.getStats() return {ironStock=BookCoverPasteRollerMaker.ironStock,bronzeStock=BookCoverPasteRollerMaker.bronzeStock,woodStock=BookCoverPasteRollerMaker.woodStock,leatherStock=BookCoverPasteRollerMaker.leatherStock,silverStock=BookCoverPasteRollerMaker.silverStock,goldStock=BookCoverPasteRollerMaker.goldStock,jewelStock=BookCoverPasteRollerMaker.jewelStock,pearlStock=BookCoverPasteRollerMaker.pearlStock,productStock=BookCoverPasteRollerMaker.productStock,numBuildings=#BookCoverPasteRollerMaker.buildings,hasMaker=BookCoverPasteRollerMaker.maker~=nil,makerName=BookCoverPasteRollerMaker.maker and BookCoverPasteRollerMaker.maker.name or "—",makerSkill=BookCoverPasteRollerMaker.maker and BookCoverPasteRollerMaker.maker.skill or 0,activeMaking=#BookCoverPasteRollerMaker.activeMaking,totalProducts=BookCoverPasteRollerMaker.totalProducts} end
return BookCoverPasteRollerMaker
