local FishScalerMaker = {}
local PRODUCTS = {
    iron_fishscaler = { name = "Železni luskalec za ribe", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni luskalec za ribe za ribištvo." },
    bronze_fishscaler = { name = "Bronast luskalec za ribe", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast luskalec za ribe za ribištvo." },
    silver_fishscaler = { name = "Srebrn luskalec za ribe", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn luskalec za ribe za ribištvo." },
    gilded_fishscaler = { name = "Pozlačen luskalec za ribe", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen luskalec za ribe za ribištvo." },
    jewel_set_fishscaler = { name = "Draguljast luskalec za ribe", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast luskalec za ribe za ribištvo." },
    royal_sovereign_fishscaler = { name = "Kraljevski suveren luskalec za ribe", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren luskalec za ribe z biseri za krono." },
}
local BUILDINGS = {
    fishscaler_workshop = { name = "Fishscaler delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    fishscaler_house = { name = "Fishscaler hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_fishscaler_atelier = { name = "Mojstrski fishscaler atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_fishscaler_palace = { name = "Suverena fishscaler palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
FishScalerMaker.ironStock = 16; FishScalerMaker.bronzeStock = 14; FishScalerMaker.woodStock = 10; FishScalerMaker.leatherStock = 8; FishScalerMaker.silverStock = 8; FishScalerMaker.goldStock = 6; FishScalerMaker.jewelStock = 4; FishScalerMaker.pearlStock = 4
FishScalerMaker.productStock = {}; FishScalerMaker.buildings = {}; FishScalerMaker.maker = nil; FishScalerMaker.activeMaking = {}; FishScalerMaker.totalProducts = 0; FishScalerMaker.dayTimer = 0
function FishScalerMaker.init() FishScalerMaker.ironStock=16; FishScalerMaker.bronzeStock=14; FishScalerMaker.woodStock=10; FishScalerMaker.leatherStock=8; FishScalerMaker.silverStock=8; FishScalerMaker.goldStock=6; FishScalerMaker.jewelStock=4; FishScalerMaker.pearlStock=4; FishScalerMaker.productStock={}; FishScalerMaker.buildings={}; FishScalerMaker.maker=nil; FishScalerMaker.activeMaking={}; FishScalerMaker.totalProducts=0; FishScalerMaker.dayTimer=0; print("[FishScalerMaker] Royal Fish Scaler Maker System initialized (6 products, 4 buildings)") end
function FishScalerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; FishScalerMaker.maker={name=n or ("Luskar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Luskar najet: %s (spretnost: %d)",FishScalerMaker.maker.name,s),"success") end; return true end
function FishScalerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function FishScalerMaker.build(id) local ok,e=FishScalerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(FishScalerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function FishScalerMaker.getQualityBonus() local b=0; for _,bd in ipairs(FishScalerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function FishScalerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and FishScalerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and FishScalerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and FishScalerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and FishScalerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and FishScalerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and FishScalerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and FishScalerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and FishScalerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #FishScalerMaker.buildings==0 then return false,"Potrebna luskarska delavnica" end; if not FishScalerMaker.maker then return false,"Potreben luskar" end; return true end
function FishScalerMaker.make(pt,qty) qty=qty or 1; local ok,e=FishScalerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then FishScalerMaker.ironStock=FishScalerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then FishScalerMaker.bronzeStock=FishScalerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then FishScalerMaker.woodStock=FishScalerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then FishScalerMaker.leatherStock=FishScalerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then FishScalerMaker.silverStock=FishScalerMaker.silverStock-d.silverCost*qty end; if d.goldCost then FishScalerMaker.goldStock=FishScalerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then FishScalerMaker.jewelStock=FishScalerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then FishScalerMaker.pearlStock=FishScalerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if FishScalerMaker.maker then t=math.max(1,t-math.floor(FishScalerMaker.maker.skill/13)) end; table.insert(FishScalerMaker.activeMaking,{id="fishscaler_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function FishScalerMaker.completeMaking(m) local q=1.0+(FishScalerMaker.getQualityBonus()/100); if FishScalerMaker.maker then q=q+(FishScalerMaker.maker.skill/140) end; q=math.min(2.5,q); FishScalerMaker.productStock[m.productType]=(FishScalerMaker.productStock[m.productType] or 0)+m.quantity; FishScalerMaker.totalProducts=FishScalerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if FishScalerMaker.maker then FishScalerMaker.maker.itemsMade=FishScalerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then FishScalerMaker.maker.skill=math.min(100,FishScalerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Luskar izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"fishscaler.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function FishScalerMaker.update(dt) if not _G.state then return end; FishScalerMaker.dayTimer=FishScalerMaker.dayTimer+dt; if FishScalerMaker.dayTimer>=30 then FishScalerMaker.dayTimer=0; for i=#FishScalerMaker.activeMaking,1,-1 do local m=FishScalerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then FishScalerMaker.completeMaking(m); table.remove(FishScalerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(FishScalerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if FishScalerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function FishScalerMaker.getStats() return {ironStock=FishScalerMaker.ironStock,bronzeStock=FishScalerMaker.bronzeStock,woodStock=FishScalerMaker.woodStock,leatherStock=FishScalerMaker.leatherStock,silverStock=FishScalerMaker.silverStock,goldStock=FishScalerMaker.goldStock,jewelStock=FishScalerMaker.jewelStock,pearlStock=FishScalerMaker.pearlStock,productStock=FishScalerMaker.productStock,numBuildings=#FishScalerMaker.buildings,hasMaker=FishScalerMaker.maker~=nil,makerName=FishScalerMaker.maker and FishScalerMaker.maker.name or "—",makerSkill=FishScalerMaker.maker and FishScalerMaker.maker.skill or 0,activeMaking=#FishScalerMaker.activeMaking,totalProducts=FishScalerMaker.totalProducts} end
return FishScalerMaker
