local GlassEngravingCopperWheelMaker = {}
local PRODUCTS = {
    iron_glassengravingcopperwheel = { name = "Železni bakreno rezbarsko kolo", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni bakreno rezbarsko kolo za steklarje." },
    bronze_glassengravingcopperwheel = { name = "Bronast bakreno rezbarsko kolo", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast bakreno rezbarsko kolo za steklarje." },
    silver_glassengravingcopperwheel = { name = "Srebrn bakreno rezbarsko kolo", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn bakreno rezbarsko kolo za steklarje." },
    gilded_glassengravingcopperwheel = { name = "Pozlačen bakreno rezbarsko kolo", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen bakreno rezbarsko kolo za steklarje." },
    jewel_set_glassengravingcopperwheel = { name = "Draguljast bakreno rezbarsko kolo", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast bakreno rezbarsko kolo za steklarje." },
    royal_sovereign_glassengravingcopperwheel = { name = "Kraljevski suveren bakreno rezbarsko kolo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren bakreno rezbarsko kolo z biseri za krono." },
}
local BUILDINGS = {
    glassengravingcopperwheel_workshop = { name = "Glassengravingcopperwheel delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glassengravingcopperwheel_house = { name = "Glassengravingcopperwheel hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glassengravingcopperwheel_atelier = { name = "Mojstrski glassengravingcopperwheel atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glassengravingcopperwheel_palace = { name = "Suverena glassengravingcopperwheel palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassEngravingCopperWheelMaker.ironStock=14; GlassEngravingCopperWheelMaker.bronzeStock=14; GlassEngravingCopperWheelMaker.woodStock=12; GlassEngravingCopperWheelMaker.leatherStock=8; GlassEngravingCopperWheelMaker.silverStock=8; GlassEngravingCopperWheelMaker.goldStock=6; GlassEngravingCopperWheelMaker.jewelStock=4; GlassEngravingCopperWheelMaker.pearlStock=4
GlassEngravingCopperWheelMaker.productStock = {}; GlassEngravingCopperWheelMaker.buildings = {}; GlassEngravingCopperWheelMaker.maker = nil; GlassEngravingCopperWheelMaker.activeMaking = {}; GlassEngravingCopperWheelMaker.totalProducts = 0; GlassEngravingCopperWheelMaker.dayTimer = 0
function GlassEngravingCopperWheelMaker.init() GlassEngravingCopperWheelMaker.ironStock=14; GlassEngravingCopperWheelMaker.bronzeStock=14; GlassEngravingCopperWheelMaker.woodStock=12; GlassEngravingCopperWheelMaker.leatherStock=8; GlassEngravingCopperWheelMaker.silverStock=8; GlassEngravingCopperWheelMaker.goldStock=6; GlassEngravingCopperWheelMaker.jewelStock=4; GlassEngravingCopperWheelMaker.pearlStock=4; GlassEngravingCopperWheelMaker.productStock={}; GlassEngravingCopperWheelMaker.buildings={}; GlassEngravingCopperWheelMaker.maker=nil; GlassEngravingCopperWheelMaker.activeMaking={}; GlassEngravingCopperWheelMaker.totalProducts=0; GlassEngravingCopperWheelMaker.dayTimer=0; print("[GlassEngravingCopperWheelMaker] Royal Glass Engraving Copper Wheel Maker System initialized (6 products, 4 buildings)") end
function GlassEngravingCopperWheelMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassEngravingCopperWheelMaker.maker={name=n or ("Bakrenik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Bakrenik najet: %s (spretnost: %d)",GlassEngravingCopperWheelMaker.maker.name,s),"success") end; return true end
function GlassEngravingCopperWheelMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassEngravingCopperWheelMaker.build(id) local ok,e=GlassEngravingCopperWheelMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassEngravingCopperWheelMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassEngravingCopperWheelMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassEngravingCopperWheelMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassEngravingCopperWheelMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassEngravingCopperWheelMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassEngravingCopperWheelMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassEngravingCopperWheelMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassEngravingCopperWheelMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassEngravingCopperWheelMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassEngravingCopperWheelMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassEngravingCopperWheelMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassEngravingCopperWheelMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassEngravingCopperWheelMaker.buildings==0 then return false,"Potrebna bakrena delavnica" end; if not GlassEngravingCopperWheelMaker.maker then return false,"Potreben bakrenik" end; return true end
function GlassEngravingCopperWheelMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassEngravingCopperWheelMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassEngravingCopperWheelMaker.ironStock=GlassEngravingCopperWheelMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassEngravingCopperWheelMaker.bronzeStock=GlassEngravingCopperWheelMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassEngravingCopperWheelMaker.woodStock=GlassEngravingCopperWheelMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassEngravingCopperWheelMaker.leatherStock=GlassEngravingCopperWheelMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassEngravingCopperWheelMaker.silverStock=GlassEngravingCopperWheelMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassEngravingCopperWheelMaker.goldStock=GlassEngravingCopperWheelMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassEngravingCopperWheelMaker.jewelStock=GlassEngravingCopperWheelMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassEngravingCopperWheelMaker.pearlStock=GlassEngravingCopperWheelMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassEngravingCopperWheelMaker.maker then t=math.max(1,t-math.floor(GlassEngravingCopperWheelMaker.maker.skill/13)) end; table.insert(GlassEngravingCopperWheelMaker.activeMaking,{id="glassengravingcopperwheel_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassEngravingCopperWheelMaker.completeMaking(m) local q=1.0+(GlassEngravingCopperWheelMaker.getQualityBonus()/100); if GlassEngravingCopperWheelMaker.maker then q=q+(GlassEngravingCopperWheelMaker.maker.skill/140) end; q=math.min(2.5,q); GlassEngravingCopperWheelMaker.productStock[m.productType]=(GlassEngravingCopperWheelMaker.productStock[m.productType] or 0)+m.quantity; GlassEngravingCopperWheelMaker.totalProducts=GlassEngravingCopperWheelMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassEngravingCopperWheelMaker.maker then GlassEngravingCopperWheelMaker.maker.itemsMade=GlassEngravingCopperWheelMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassEngravingCopperWheelMaker.maker.skill=math.min(100,GlassEngravingCopperWheelMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kolo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glassengravingcopperwheel.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassEngravingCopperWheelMaker.update(dt) if not _G.state then return end; GlassEngravingCopperWheelMaker.dayTimer=GlassEngravingCopperWheelMaker.dayTimer+dt; if GlassEngravingCopperWheelMaker.dayTimer>=30 then GlassEngravingCopperWheelMaker.dayTimer=0; for i=#GlassEngravingCopperWheelMaker.activeMaking,1,-1 do local m=GlassEngravingCopperWheelMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassEngravingCopperWheelMaker.completeMaking(m); table.remove(GlassEngravingCopperWheelMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassEngravingCopperWheelMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassEngravingCopperWheelMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassEngravingCopperWheelMaker.getStats() return {ironStock=GlassEngravingCopperWheelMaker.ironStock,bronzeStock=GlassEngravingCopperWheelMaker.bronzeStock,woodStock=GlassEngravingCopperWheelMaker.woodStock,leatherStock=GlassEngravingCopperWheelMaker.leatherStock,silverStock=GlassEngravingCopperWheelMaker.silverStock,goldStock=GlassEngravingCopperWheelMaker.goldStock,jewelStock=GlassEngravingCopperWheelMaker.jewelStock,pearlStock=GlassEngravingCopperWheelMaker.pearlStock,productStock=GlassEngravingCopperWheelMaker.productStock,numBuildings=#GlassEngravingCopperWheelMaker.buildings,hasMaker=GlassEngravingCopperWheelMaker.maker~=nil,makerName=GlassEngravingCopperWheelMaker.maker and GlassEngravingCopperWheelMaker.maker.name or "—",makerSkill=GlassEngravingCopperWheelMaker.maker and GlassEngravingCopperWheelMaker.maker.skill or 0,activeMaking=#GlassEngravingCopperWheelMaker.activeMaking,totalProducts=GlassEngravingCopperWheelMaker.totalProducts} end
return GlassEngravingCopperWheelMaker
