local GardenMulchForkMaker = {}
local PRODUCTS = {
    iron_gardenmulchfork = { name = "Železni vilice za zastirko", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni vilice za zastirko za vrtnarje." },
    bronze_gardenmulchfork = { name = "Bronast vilice za zastirko", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast vilice za zastirko za vrtnarje." },
    silver_gardenmulchfork = { name = "Srebrn vilice za zastirko", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn vilice za zastirko za vrtnarje." },
    gilded_gardenmulchfork = { name = "Pozlačen vilice za zastirko", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen vilice za zastirko za vrtnarje." },
    jewel_set_gardenmulchfork = { name = "Draguljast vilice za zastirko", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast vilice za zastirko za vrtnarje." },
    royal_sovereign_gardenmulchfork = { name = "Kraljevski suveren vilice za zastirko", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren vilice za zastirko z biseri za krono." },
}
local BUILDINGS = {
    gardenmulchfork_workshop = { name = "Gardenmulchfork delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardenmulchfork_house = { name = "Gardenmulchfork hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardenmulchfork_atelier = { name = "Mojstrski gardenmulchfork atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardenmulchfork_palace = { name = "Suverena gardenmulchfork palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenMulchForkMaker.ironStock=18; GardenMulchForkMaker.bronzeStock=14; GardenMulchForkMaker.woodStock=10; GardenMulchForkMaker.leatherStock=8; GardenMulchForkMaker.silverStock=8; GardenMulchForkMaker.goldStock=6; GardenMulchForkMaker.jewelStock=4; GardenMulchForkMaker.pearlStock=4
GardenMulchForkMaker.productStock = {}; GardenMulchForkMaker.buildings = {}; GardenMulchForkMaker.maker = nil; GardenMulchForkMaker.activeMaking = {}; GardenMulchForkMaker.totalProducts = 0; GardenMulchForkMaker.dayTimer = 0
function GardenMulchForkMaker.init() GardenMulchForkMaker.ironStock=18; GardenMulchForkMaker.bronzeStock=14; GardenMulchForkMaker.woodStock=10; GardenMulchForkMaker.leatherStock=8; GardenMulchForkMaker.silverStock=8; GardenMulchForkMaker.goldStock=6; GardenMulchForkMaker.jewelStock=4; GardenMulchForkMaker.pearlStock=4; GardenMulchForkMaker.productStock={}; GardenMulchForkMaker.buildings={}; GardenMulchForkMaker.maker=nil; GardenMulchForkMaker.activeMaking={}; GardenMulchForkMaker.totalProducts=0; GardenMulchForkMaker.dayTimer=0; print("[GardenMulchForkMaker] Royal Garden Mulch Fork Maker System initialized (6 products, 4 buildings)") end
function GardenMulchForkMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenMulchForkMaker.maker={name=n or ("Viliar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Viliar najet: %s (spretnost: %d)",GardenMulchForkMaker.maker.name,s),"success") end; return true end
function GardenMulchForkMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenMulchForkMaker.build(id) local ok,e=GardenMulchForkMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenMulchForkMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenMulchForkMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenMulchForkMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenMulchForkMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenMulchForkMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenMulchForkMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenMulchForkMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenMulchForkMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenMulchForkMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenMulchForkMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenMulchForkMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenMulchForkMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenMulchForkMaker.buildings==0 then return false,"Potrebna vilična delavnica" end; if not GardenMulchForkMaker.maker then return false,"Potreben viliar" end; return true end
function GardenMulchForkMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenMulchForkMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenMulchForkMaker.ironStock=GardenMulchForkMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenMulchForkMaker.bronzeStock=GardenMulchForkMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenMulchForkMaker.woodStock=GardenMulchForkMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenMulchForkMaker.leatherStock=GardenMulchForkMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenMulchForkMaker.silverStock=GardenMulchForkMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenMulchForkMaker.goldStock=GardenMulchForkMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenMulchForkMaker.jewelStock=GardenMulchForkMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenMulchForkMaker.pearlStock=GardenMulchForkMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenMulchForkMaker.maker then t=math.max(1,t-math.floor(GardenMulchForkMaker.maker.skill/13)) end; table.insert(GardenMulchForkMaker.activeMaking,{id="gardenmulchfork_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenMulchForkMaker.completeMaking(m) local q=1.0+(GardenMulchForkMaker.getQualityBonus()/100); if GardenMulchForkMaker.maker then q=q+(GardenMulchForkMaker.maker.skill/140) end; q=math.min(2.5,q); GardenMulchForkMaker.productStock[m.productType]=(GardenMulchForkMaker.productStock[m.productType] or 0)+m.quantity; GardenMulchForkMaker.totalProducts=GardenMulchForkMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenMulchForkMaker.maker then GardenMulchForkMaker.maker.itemsMade=GardenMulchForkMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenMulchForkMaker.maker.skill=math.min(100,GardenMulchForkMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vilice izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardenmulchfork.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenMulchForkMaker.update(dt) if not _G.state then return end; GardenMulchForkMaker.dayTimer=GardenMulchForkMaker.dayTimer+dt; if GardenMulchForkMaker.dayTimer>=30 then GardenMulchForkMaker.dayTimer=0; for i=#GardenMulchForkMaker.activeMaking,1,-1 do local m=GardenMulchForkMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenMulchForkMaker.completeMaking(m); table.remove(GardenMulchForkMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenMulchForkMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenMulchForkMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenMulchForkMaker.getStats() return {ironStock=GardenMulchForkMaker.ironStock,bronzeStock=GardenMulchForkMaker.bronzeStock,woodStock=GardenMulchForkMaker.woodStock,leatherStock=GardenMulchForkMaker.leatherStock,silverStock=GardenMulchForkMaker.silverStock,goldStock=GardenMulchForkMaker.goldStock,jewelStock=GardenMulchForkMaker.jewelStock,pearlStock=GardenMulchForkMaker.pearlStock,productStock=GardenMulchForkMaker.productStock,numBuildings=#GardenMulchForkMaker.buildings,hasMaker=GardenMulchForkMaker.maker~=nil,makerName=GardenMulchForkMaker.maker and GardenMulchForkMaker.maker.name or "—",makerSkill=GardenMulchForkMaker.maker and GardenMulchForkMaker.maker.skill or 0,activeMaking=#GardenMulchForkMaker.activeMaking,totalProducts=GardenMulchForkMaker.totalProducts} end
return GardenMulchForkMaker
