local AnvilHornPolisherMaker = {}
local PRODUCTS = {
    iron_anvilhornpolisher = { name = "Železni poliralec za rog nakovala", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni poliralec za rog nakovala za kovace." },
    bronze_anvilhornpolisher = { name = "Bronast poliralec za rog nakovala", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast poliralec za rog nakovala za kovace." },
    silver_anvilhornpolisher = { name = "Srebrn poliralec za rog nakovala", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn poliralec za rog nakovala za kovace." },
    gilded_anvilhornpolisher = { name = "Pozlačen poliralec za rog nakovala", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen poliralec za rog nakovala za kovace." },
    jewel_set_anvilhornpolisher = { name = "Draguljast poliralec za rog nakovala", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast poliralec za rog nakovala za kovace." },
    royal_sovereign_anvilhornpolisher = { name = "Kraljevski suveren poliralec za rog nakovala", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren poliralec za rog nakovala z biseri za krono." },
}
local BUILDINGS = {
    anvilhornpolisher_workshop = { name = "Anvilhornpolisher delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    anvilhornpolisher_house = { name = "Anvilhornpolisher hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_anvilhornpolisher_atelier = { name = "Mojstrski anvilhornpolisher atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_anvilhornpolisher_palace = { name = "Suverena anvilhornpolisher palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
AnvilHornPolisherMaker.ironStock=14; AnvilHornPolisherMaker.bronzeStock=12; AnvilHornPolisherMaker.woodStock=14; AnvilHornPolisherMaker.leatherStock=8; AnvilHornPolisherMaker.silverStock=8; AnvilHornPolisherMaker.goldStock=6; AnvilHornPolisherMaker.jewelStock=4; AnvilHornPolisherMaker.pearlStock=4
AnvilHornPolisherMaker.productStock = {}; AnvilHornPolisherMaker.buildings = {}; AnvilHornPolisherMaker.maker = nil; AnvilHornPolisherMaker.activeMaking = {}; AnvilHornPolisherMaker.totalProducts = 0; AnvilHornPolisherMaker.dayTimer = 0
function AnvilHornPolisherMaker.init() AnvilHornPolisherMaker.ironStock=14; AnvilHornPolisherMaker.bronzeStock=12; AnvilHornPolisherMaker.woodStock=14; AnvilHornPolisherMaker.leatherStock=8; AnvilHornPolisherMaker.silverStock=8; AnvilHornPolisherMaker.goldStock=6; AnvilHornPolisherMaker.jewelStock=4; AnvilHornPolisherMaker.pearlStock=4; AnvilHornPolisherMaker.productStock={}; AnvilHornPolisherMaker.buildings={}; AnvilHornPolisherMaker.maker=nil; AnvilHornPolisherMaker.activeMaking={}; AnvilHornPolisherMaker.totalProducts=0; AnvilHornPolisherMaker.dayTimer=0; print("[AnvilHornPolisherMaker] Royal Anvil Horn Polisher Maker System initialized (6 products, 4 buildings)") end
function AnvilHornPolisherMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; AnvilHornPolisherMaker.maker={name=n or ("Polirar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Polirar najet: %s (spretnost: %d)",AnvilHornPolisherMaker.maker.name,s),"success") end; return true end
function AnvilHornPolisherMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function AnvilHornPolisherMaker.build(id) local ok,e=AnvilHornPolisherMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(AnvilHornPolisherMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function AnvilHornPolisherMaker.getQualityBonus() local b=0; for _,bd in ipairs(AnvilHornPolisherMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function AnvilHornPolisherMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and AnvilHornPolisherMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and AnvilHornPolisherMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and AnvilHornPolisherMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and AnvilHornPolisherMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and AnvilHornPolisherMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and AnvilHornPolisherMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and AnvilHornPolisherMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and AnvilHornPolisherMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #AnvilHornPolisherMaker.buildings==0 then return false,"Potrebna polirna delavnica" end; if not AnvilHornPolisherMaker.maker then return false,"Potreben polirar" end; return true end
function AnvilHornPolisherMaker.make(pt,qty) qty=qty or 1; local ok,e=AnvilHornPolisherMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then AnvilHornPolisherMaker.ironStock=AnvilHornPolisherMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then AnvilHornPolisherMaker.bronzeStock=AnvilHornPolisherMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then AnvilHornPolisherMaker.woodStock=AnvilHornPolisherMaker.woodStock-d.woodCost*qty end; if d.leatherCost then AnvilHornPolisherMaker.leatherStock=AnvilHornPolisherMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then AnvilHornPolisherMaker.silverStock=AnvilHornPolisherMaker.silverStock-d.silverCost*qty end; if d.goldCost then AnvilHornPolisherMaker.goldStock=AnvilHornPolisherMaker.goldStock-d.goldCost*qty end; if d.jewelCost then AnvilHornPolisherMaker.jewelStock=AnvilHornPolisherMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then AnvilHornPolisherMaker.pearlStock=AnvilHornPolisherMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if AnvilHornPolisherMaker.maker then t=math.max(1,t-math.floor(AnvilHornPolisherMaker.maker.skill/13)) end; table.insert(AnvilHornPolisherMaker.activeMaking,{id="anvilhornpolisher_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function AnvilHornPolisherMaker.completeMaking(m) local q=1.0+(AnvilHornPolisherMaker.getQualityBonus()/100); if AnvilHornPolisherMaker.maker then q=q+(AnvilHornPolisherMaker.maker.skill/140) end; q=math.min(2.5,q); AnvilHornPolisherMaker.productStock[m.productType]=(AnvilHornPolisherMaker.productStock[m.productType] or 0)+m.quantity; AnvilHornPolisherMaker.totalProducts=AnvilHornPolisherMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if AnvilHornPolisherMaker.maker then AnvilHornPolisherMaker.maker.itemsMade=AnvilHornPolisherMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then AnvilHornPolisherMaker.maker.skill=math.min(100,AnvilHornPolisherMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Polirec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"anvilhornpolisher.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function AnvilHornPolisherMaker.update(dt) if not _G.state then return end; AnvilHornPolisherMaker.dayTimer=AnvilHornPolisherMaker.dayTimer+dt; if AnvilHornPolisherMaker.dayTimer>=30 then AnvilHornPolisherMaker.dayTimer=0; for i=#AnvilHornPolisherMaker.activeMaking,1,-1 do local m=AnvilHornPolisherMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then AnvilHornPolisherMaker.completeMaking(m); table.remove(AnvilHornPolisherMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(AnvilHornPolisherMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if AnvilHornPolisherMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function AnvilHornPolisherMaker.getStats() return {ironStock=AnvilHornPolisherMaker.ironStock,bronzeStock=AnvilHornPolisherMaker.bronzeStock,woodStock=AnvilHornPolisherMaker.woodStock,leatherStock=AnvilHornPolisherMaker.leatherStock,silverStock=AnvilHornPolisherMaker.silverStock,goldStock=AnvilHornPolisherMaker.goldStock,jewelStock=AnvilHornPolisherMaker.jewelStock,pearlStock=AnvilHornPolisherMaker.pearlStock,productStock=AnvilHornPolisherMaker.productStock,numBuildings=#AnvilHornPolisherMaker.buildings,hasMaker=AnvilHornPolisherMaker.maker~=nil,makerName=AnvilHornPolisherMaker.maker and AnvilHornPolisherMaker.maker.name or "—",makerSkill=AnvilHornPolisherMaker.maker and AnvilHornPolisherMaker.maker.skill or 0,activeMaking=#AnvilHornPolisherMaker.activeMaking,totalProducts=AnvilHornPolisherMaker.totalProducts} end
return AnvilHornPolisherMaker
