local CorePrintBoxMaker = {}
local PRODUCTS = {
    iron_coreprintbox = { name = "Železni skatla za odtise jedrc", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni skatla za odtise jedrc za livarje." },
    bronze_coreprintbox = { name = "Bronast skatla za odtise jedrc", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast skatla za odtise jedrc za livarje." },
    silver_coreprintbox = { name = "Srebrn skatla za odtise jedrc", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn skatla za odtise jedrc za livarje." },
    gilded_coreprintbox = { name = "Pozlačen skatla za odtise jedrc", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen skatla za odtise jedrc za livarje." },
    jewel_set_coreprintbox = { name = "Draguljast skatla za odtise jedrc", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast skatla za odtise jedrc za livarje." },
    royal_sovereign_coreprintbox = { name = "Kraljevski suveren skatla za odtise jedrc", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren skatla za odtise jedrc z biseri za krono." },
}
local BUILDINGS = {
    coreprintbox_workshop = { name = "Coreprintbox delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    coreprintbox_house = { name = "Coreprintbox hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_coreprintbox_atelier = { name = "Mojstrski coreprintbox atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_coreprintbox_palace = { name = "Suverena coreprintbox palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
CorePrintBoxMaker.ironStock=12; CorePrintBoxMaker.bronzeStock=10; CorePrintBoxMaker.woodStock=16; CorePrintBoxMaker.leatherStock=10; CorePrintBoxMaker.silverStock=8; CorePrintBoxMaker.goldStock=6; CorePrintBoxMaker.jewelStock=4; CorePrintBoxMaker.pearlStock=4
CorePrintBoxMaker.productStock = {}; CorePrintBoxMaker.buildings = {}; CorePrintBoxMaker.maker = nil; CorePrintBoxMaker.activeMaking = {}; CorePrintBoxMaker.totalProducts = 0; CorePrintBoxMaker.dayTimer = 0
function CorePrintBoxMaker.init() CorePrintBoxMaker.ironStock=12; CorePrintBoxMaker.bronzeStock=10; CorePrintBoxMaker.woodStock=16; CorePrintBoxMaker.leatherStock=10; CorePrintBoxMaker.silverStock=8; CorePrintBoxMaker.goldStock=6; CorePrintBoxMaker.jewelStock=4; CorePrintBoxMaker.pearlStock=4; CorePrintBoxMaker.productStock={}; CorePrintBoxMaker.buildings={}; CorePrintBoxMaker.maker=nil; CorePrintBoxMaker.activeMaking={}; CorePrintBoxMaker.totalProducts=0; CorePrintBoxMaker.dayTimer=0; print("[CorePrintBoxMaker] Royal Core Print Box Maker System initialized (6 products, 4 buildings)") end
function CorePrintBoxMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CorePrintBoxMaker.maker={name=n or ("Škatlar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Škatlar najet: %s (spretnost: %d)",CorePrintBoxMaker.maker.name,s),"success") end; return true end
function CorePrintBoxMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CorePrintBoxMaker.build(id) local ok,e=CorePrintBoxMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CorePrintBoxMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CorePrintBoxMaker.getQualityBonus() local b=0; for _,bd in ipairs(CorePrintBoxMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CorePrintBoxMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CorePrintBoxMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CorePrintBoxMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CorePrintBoxMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CorePrintBoxMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CorePrintBoxMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CorePrintBoxMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CorePrintBoxMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CorePrintBoxMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CorePrintBoxMaker.buildings==0 then return false,"Potrebna skatelna delavnica" end; if not CorePrintBoxMaker.maker then return false,"Potreben skatlar" end; return true end
function CorePrintBoxMaker.make(pt,qty) qty=qty or 1; local ok,e=CorePrintBoxMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CorePrintBoxMaker.ironStock=CorePrintBoxMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CorePrintBoxMaker.bronzeStock=CorePrintBoxMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CorePrintBoxMaker.woodStock=CorePrintBoxMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CorePrintBoxMaker.leatherStock=CorePrintBoxMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CorePrintBoxMaker.silverStock=CorePrintBoxMaker.silverStock-d.silverCost*qty end; if d.goldCost then CorePrintBoxMaker.goldStock=CorePrintBoxMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CorePrintBoxMaker.jewelStock=CorePrintBoxMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CorePrintBoxMaker.pearlStock=CorePrintBoxMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CorePrintBoxMaker.maker then t=math.max(1,t-math.floor(CorePrintBoxMaker.maker.skill/13)) end; table.insert(CorePrintBoxMaker.activeMaking,{id="coreprintbox_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CorePrintBoxMaker.completeMaking(m) local q=1.0+(CorePrintBoxMaker.getQualityBonus()/100); if CorePrintBoxMaker.maker then q=q+(CorePrintBoxMaker.maker.skill/140) end; q=math.min(2.5,q); CorePrintBoxMaker.productStock[m.productType]=(CorePrintBoxMaker.productStock[m.productType] or 0)+m.quantity; CorePrintBoxMaker.totalProducts=CorePrintBoxMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CorePrintBoxMaker.maker then CorePrintBoxMaker.maker.itemsMade=CorePrintBoxMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CorePrintBoxMaker.maker.skill=math.min(100,CorePrintBoxMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Škatla izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"coreprintbox.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CorePrintBoxMaker.update(dt) if not _G.state then return end; CorePrintBoxMaker.dayTimer=CorePrintBoxMaker.dayTimer+dt; if CorePrintBoxMaker.dayTimer>=30 then CorePrintBoxMaker.dayTimer=0; for i=#CorePrintBoxMaker.activeMaking,1,-1 do local m=CorePrintBoxMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CorePrintBoxMaker.completeMaking(m); table.remove(CorePrintBoxMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CorePrintBoxMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CorePrintBoxMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CorePrintBoxMaker.getStats() return {ironStock=CorePrintBoxMaker.ironStock,bronzeStock=CorePrintBoxMaker.bronzeStock,woodStock=CorePrintBoxMaker.woodStock,leatherStock=CorePrintBoxMaker.leatherStock,silverStock=CorePrintBoxMaker.silverStock,goldStock=CorePrintBoxMaker.goldStock,jewelStock=CorePrintBoxMaker.jewelStock,pearlStock=CorePrintBoxMaker.pearlStock,productStock=CorePrintBoxMaker.productStock,numBuildings=#CorePrintBoxMaker.buildings,hasMaker=CorePrintBoxMaker.maker~=nil,makerName=CorePrintBoxMaker.maker and CorePrintBoxMaker.maker.name or "—",makerSkill=CorePrintBoxMaker.maker and CorePrintBoxMaker.maker.skill or 0,activeMaking=#CorePrintBoxMaker.activeMaking,totalProducts=CorePrintBoxMaker.totalProducts} end
return CorePrintBoxMaker
