local DollHouseMaker = {}
local PRODUCTS = {
    simple_dollhouse = { name = "Preprosta lutkna hiša", woodCost = 3, paintCost = 1, time = 3, cost = 35, artistry = 40, happiness = 3, description = "Preprosta lutkna hiša za otroke." },
    painted_dollhouse = { name = "Poslikana lutkna hiša", woodCost = 3, paintCost = 2, fabricCost = 1, time = 5, cost = 80, artistry = 55, prestige = 2, happiness = 4, description = "Poslikana lutkna hiša z notranjostjo." },
    furnished_dollhouse = { name = "Pohištena lutkna hiša", woodCost = 4, paintCost = 2, fabricCost = 1, silkCost = 1, time = 7, cost = 180, artistry = 70, prestige = 5, happiness = 5, description = "Pohištena lutkna hiša z mini pohištvom." },
    silver_trim_dollhouse = { name = "Srebrno obrobljena lutkna hiša", woodCost = 4, silverCost = 1, paintCost = 2, silkCost = 1, fabricCost = 1, time = 10, cost = 420, artistry = 82, prestige = 10, happiness = 6, description = "Lutkna hiša s srebrnim okovjem za plemiče." },
    gold_inlaid_dollhouse = { name = "Zlatointarzirana lutkna hiša", woodCost = 5, goldCost = 1, silverCost = 1, jewelCost = 1, silkCost = 1, paintCost = 2, fabricCost = 1, time = 13, cost = 900, artistry = 92, prestige = 18, happiness = 8, description = "Zlatointarzirana lutkna hiša za visoke plemiče." },
    royal_grand_dollhouse = { name = "Kraljevski veliki lutkna hiša", woodCost = 8, goldCost = 2, silverCost = 1, jewelCost = 1, pearlCost = 1, silkCost = 2, paintCost = 3, fabricCost = 2, time = 18, cost = 2200, artistry = 100, prestige = 45, happiness = 14, description = "Velika kraljevska lutkna hiša z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Lutknarska delavnica", cost = { gold = 280, wood = 140, stone = 200 }, upkeep = 7, qualityBonus = 5 },
    furnishing_room = { name = "Pohištilnica", cost = { gold = 900, wood = 250, stone = 400, fabric = 8 }, upkeep = 22, qualityBonus = 18 },
    decorating_room = { name = "Okrasovalnica", cost = { gold = 2200, wood = 350, stone = 600, silver = 25, silk = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_dollhouse_atelier = { name = "Kraljevski atelje lutknih hiš", cost = { gold = 9000, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
DollHouseMaker.woodStock = 22; DollHouseMaker.paintStock = 12; DollHouseMaker.fabricStock = 10; DollHouseMaker.silkStock = 8; DollHouseMaker.silverStock = 8; DollHouseMaker.goldStock = 6; DollHouseMaker.jewelStock = 6; DollHouseMaker.pearlStock = 4
DollHouseMaker.productStock = {}; DollHouseMaker.buildings = {}; DollHouseMaker.maker = nil; DollHouseMaker.activeMaking = {}; DollHouseMaker.totalProducts = 0; DollHouseMaker.dayTimer = 0
function DollHouseMaker.init() DollHouseMaker.woodStock=22; DollHouseMaker.paintStock=12; DollHouseMaker.fabricStock=10; DollHouseMaker.silkStock=8; DollHouseMaker.silverStock=8; DollHouseMaker.goldStock=6; DollHouseMaker.jewelStock=6; DollHouseMaker.pearlStock=4; DollHouseMaker.productStock={}; DollHouseMaker.buildings={}; DollHouseMaker.maker=nil; DollHouseMaker.activeMaking={}; DollHouseMaker.totalProducts=0; DollHouseMaker.dayTimer=0; print("[DollHouseMaker] Royal Doll House Maker System initialized (6 products, 4 buildings)") end
function DollHouseMaker.hireMaker(n,s) s=s or math.random(50,90); local c=520+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; DollHouseMaker.maker={name=n or ("Lutknar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lutknar najet: %s (spretnost: %d)",DollHouseMaker.maker.name,s),"success") end; return true end
function DollHouseMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function DollHouseMaker.build(id) local ok,e=DollHouseMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(DollHouseMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function DollHouseMaker.getQualityBonus() local b=0; for _,bd in ipairs(DollHouseMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function DollHouseMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and DollHouseMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.paintCost and DollHouseMaker.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.fabricCost and DollHouseMaker.fabricStock<(d.fabricCost or 0) then return false,"Premalo tkanine" end; if d.silkCost and DollHouseMaker.silkStock<(d.silkCost or 0) then return false,"Premalo svile" end; if d.silverCost and DollHouseMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and DollHouseMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and DollHouseMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and DollHouseMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #DollHouseMaker.buildings==0 then return false,"Potrebna delavnica" end; if not DollHouseMaker.maker then return false,"Potreben lutknar" end; return true end
function DollHouseMaker.make(pt,qty) qty=qty or 1; local ok,e=DollHouseMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then DollHouseMaker.woodStock=DollHouseMaker.woodStock-d.woodCost*qty end; if d.paintCost then DollHouseMaker.paintStock=DollHouseMaker.paintStock-d.paintCost*qty end; if d.fabricCost then DollHouseMaker.fabricStock=DollHouseMaker.fabricStock-d.fabricCost*qty end; if d.silkCost then DollHouseMaker.silkStock=DollHouseMaker.silkStock-d.silkCost*qty end; if d.silverCost then DollHouseMaker.silverStock=DollHouseMaker.silverStock-d.silverCost*qty end; if d.goldCost then DollHouseMaker.goldStock=DollHouseMaker.goldStock-d.goldCost*qty end; if d.jewelCost then DollHouseMaker.jewelStock=DollHouseMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then DollHouseMaker.pearlStock=DollHouseMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if DollHouseMaker.maker then t=math.max(1,t-math.floor(DollHouseMaker.maker.skill/12)) end; table.insert(DollHouseMaker.activeMaking,{id="dollhouse_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,artistry=d.artistry or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function DollHouseMaker.completeMaking(m) local q=1.0+(DollHouseMaker.getQualityBonus()/100); if DollHouseMaker.maker then q=q+(DollHouseMaker.maker.skill/180) end; q=math.min(2.0,q); DollHouseMaker.productStock[m.productType]=(DollHouseMaker.productStock[m.productType] or 0)+m.quantity; DollHouseMaker.totalProducts=DollHouseMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if DollHouseMaker.maker then DollHouseMaker.maker.itemsMade=DollHouseMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then DollHouseMaker.maker.skill=math.min(100,DollHouseMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lutkna hiša izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"dollhouse.completed",{productName=m.productName,artistry=m.artistry,prestige=m.prestige,happiness=m.happiness}) end end
function DollHouseMaker.update(dt) if not _G.state then return end; DollHouseMaker.dayTimer=DollHouseMaker.dayTimer+dt; if DollHouseMaker.dayTimer>=30 then DollHouseMaker.dayTimer=0; for i=#DollHouseMaker.activeMaking,1,-1 do local m=DollHouseMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then DollHouseMaker.completeMaking(m); table.remove(DollHouseMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(DollHouseMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if DollHouseMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function DollHouseMaker.getStats() return {woodStock=DollHouseMaker.woodStock,paintStock=DollHouseMaker.paintStock,fabricStock=DollHouseMaker.fabricStock,silkStock=DollHouseMaker.silkStock,silverStock=DollHouseMaker.silverStock,goldStock=DollHouseMaker.goldStock,jewelStock=DollHouseMaker.jewelStock,pearlStock=DollHouseMaker.pearlStock,productStock=DollHouseMaker.productStock,numBuildings=#DollHouseMaker.buildings,hasMaker=DollHouseMaker.maker~=nil,makerName=DollHouseMaker.maker and DollHouseMaker.maker.name or "—",makerSkill=DollHouseMaker.maker and DollHouseMaker.maker.skill or 0,activeMaking=#DollHouseMaker.activeMaking,totalProducts=DollHouseMaker.totalProducts} end
return DollHouseMaker
