local CupolaTuyereMaker = {}
local PRODUCTS = {
    iron_cupolatuyere = { name = "Železni šoba za kupole", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni šoba za kupole za kovace." },
    bronze_cupolatuyere = { name = "Bronast šoba za kupole", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast šoba za kupole za kovace." },
    silver_cupolatuyere = { name = "Srebrn šoba za kupole", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn šoba za kupole za kovace." },
    gilded_cupolatuyere = { name = "Pozlačen šoba za kupole", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen šoba za kupole za kovace." },
    jewel_set_cupolatuyere = { name = "Draguljast šoba za kupole", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast šoba za kupole za kovace." },
    royal_sovereign_cupolatuyere = { name = "Kraljevski suveren šoba za kupole", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren šoba za kupole z biseri za krono." },
}
local BUILDINGS = {
    cupolatuyere_workshop = { name = "Cupolatuyere delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    cupolatuyere_house = { name = "Cupolatuyere hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_cupolatuyere_atelier = { name = "Mojstrski cupolatuyere atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_cupolatuyere_palace = { name = "Suverena cupolatuyere palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
CupolaTuyereMaker.ironStock=18; CupolaTuyereMaker.bronzeStock=14; CupolaTuyereMaker.woodStock=10; CupolaTuyereMaker.leatherStock=8; CupolaTuyereMaker.silverStock=8; CupolaTuyereMaker.goldStock=6; CupolaTuyereMaker.jewelStock=4; CupolaTuyereMaker.pearlStock=4
CupolaTuyereMaker.productStock = {}; CupolaTuyereMaker.buildings = {}; CupolaTuyereMaker.maker = nil; CupolaTuyereMaker.activeMaking = {}; CupolaTuyereMaker.totalProducts = 0; CupolaTuyereMaker.dayTimer = 0
function CupolaTuyereMaker.init() CupolaTuyereMaker.ironStock=18; CupolaTuyereMaker.bronzeStock=14; CupolaTuyereMaker.woodStock=10; CupolaTuyereMaker.leatherStock=8; CupolaTuyereMaker.silverStock=8; CupolaTuyereMaker.goldStock=6; CupolaTuyereMaker.jewelStock=4; CupolaTuyereMaker.pearlStock=4; CupolaTuyereMaker.productStock={}; CupolaTuyereMaker.buildings={}; CupolaTuyereMaker.maker=nil; CupolaTuyereMaker.activeMaking={}; CupolaTuyereMaker.totalProducts=0; CupolaTuyereMaker.dayTimer=0; print("[CupolaTuyereMaker] Royal Cupola Tuyere Maker System initialized (6 products, 4 buildings)") end
function CupolaTuyereMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CupolaTuyereMaker.maker={name=n or ("Šobnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Šobnik najet: %s (spretnost: %d)",CupolaTuyereMaker.maker.name,s),"success") end; return true end
function CupolaTuyereMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CupolaTuyereMaker.build(id) local ok,e=CupolaTuyereMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CupolaTuyereMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CupolaTuyereMaker.getQualityBonus() local b=0; for _,bd in ipairs(CupolaTuyereMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CupolaTuyereMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CupolaTuyereMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CupolaTuyereMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CupolaTuyereMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CupolaTuyereMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CupolaTuyereMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CupolaTuyereMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CupolaTuyereMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CupolaTuyereMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CupolaTuyereMaker.buildings==0 then return false,"Potrebna šobniška delavnica" end; if not CupolaTuyereMaker.maker then return false,"Potreben šobnik" end; return true end
function CupolaTuyereMaker.make(pt,qty) qty=qty or 1; local ok,e=CupolaTuyereMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CupolaTuyereMaker.ironStock=CupolaTuyereMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CupolaTuyereMaker.bronzeStock=CupolaTuyereMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CupolaTuyereMaker.woodStock=CupolaTuyereMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CupolaTuyereMaker.leatherStock=CupolaTuyereMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CupolaTuyereMaker.silverStock=CupolaTuyereMaker.silverStock-d.silverCost*qty end; if d.goldCost then CupolaTuyereMaker.goldStock=CupolaTuyereMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CupolaTuyereMaker.jewelStock=CupolaTuyereMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CupolaTuyereMaker.pearlStock=CupolaTuyereMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CupolaTuyereMaker.maker then t=math.max(1,t-math.floor(CupolaTuyereMaker.maker.skill/13)) end; table.insert(CupolaTuyereMaker.activeMaking,{id="cupolatuyere_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CupolaTuyereMaker.completeMaking(m) local q=1.0+(CupolaTuyereMaker.getQualityBonus()/100); if CupolaTuyereMaker.maker then q=q+(CupolaTuyereMaker.maker.skill/140) end; q=math.min(2.5,q); CupolaTuyereMaker.productStock[m.productType]=(CupolaTuyereMaker.productStock[m.productType] or 0)+m.quantity; CupolaTuyereMaker.totalProducts=CupolaTuyereMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CupolaTuyereMaker.maker then CupolaTuyereMaker.maker.itemsMade=CupolaTuyereMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CupolaTuyereMaker.maker.skill=math.min(100,CupolaTuyereMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Šoba izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"cupolatuyere.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CupolaTuyereMaker.update(dt) if not _G.state then return end; CupolaTuyereMaker.dayTimer=CupolaTuyereMaker.dayTimer+dt; if CupolaTuyereMaker.dayTimer>=30 then CupolaTuyereMaker.dayTimer=0; for i=#CupolaTuyereMaker.activeMaking,1,-1 do local m=CupolaTuyereMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CupolaTuyereMaker.completeMaking(m); table.remove(CupolaTuyereMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CupolaTuyereMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CupolaTuyereMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CupolaTuyereMaker.getStats() return {ironStock=CupolaTuyereMaker.ironStock,bronzeStock=CupolaTuyereMaker.bronzeStock,woodStock=CupolaTuyereMaker.woodStock,leatherStock=CupolaTuyereMaker.leatherStock,silverStock=CupolaTuyereMaker.silverStock,goldStock=CupolaTuyereMaker.goldStock,jewelStock=CupolaTuyereMaker.jewelStock,pearlStock=CupolaTuyereMaker.pearlStock,productStock=CupolaTuyereMaker.productStock,numBuildings=#CupolaTuyereMaker.buildings,hasMaker=CupolaTuyereMaker.maker~=nil,makerName=CupolaTuyereMaker.maker and CupolaTuyereMaker.maker.name or "—",makerSkill=CupolaTuyereMaker.maker and CupolaTuyereMaker.maker.skill or 0,activeMaking=#CupolaTuyereMaker.activeMaking,totalProducts=CupolaTuyereMaker.totalProducts} end
return CupolaTuyereMaker
