local BridleMaker = {}
local PRODUCTS = {
    iron_bridle = { name = "Železna uzda", ironCost = 2, woodCost = 1, leatherCost = 3, time = 5, cost = 175, prestige = 3, happiness = 2, description = "Železna uzda za osnovno vodenje konja." },
    bronze_bridle = { name = "Bronasta uzda", bronzeCost = 2, ironCost = 1, woodCost = 1, leatherCost = 3, time = 7, cost = 430, prestige = 5, happiness = 3, description = "Bronasta uzda za lahko konjenico." },
    silver_bridle = { name = "Srebrna uzda", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 3, time = 11, cost = 1050, prestige = 10, happiness = 4, description = "Srebrna uzda za plemiške konje." },
    gilded_bridle = { name = "Pozlačena uzda", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 1, leatherCost = 3, time = 15, cost = 2300, prestige = 19, happiness = 5, description = "Pozlačena uzda za dvorne konje." },
    jewel_set_bridle = { name = "Draguljasta uzda", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 3, time = 19, cost = 4900, prestige = 35, happiness = 7, description = "Draguljasta uzda za kraljeve konje." },
    royal_sovereign_bridle = { name = "Kraljevski suverena uzda", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 4, time = 26, cost = 10500, prestige = 68, happiness = 13, description = "Suverena uzda z biseri za krono." },
}
local BUILDINGS = {
    bridle_workshop = { name = "Uzdarska delavnica", cost = { gold = 340, wood = 175, stone = 135, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bridle_house = { name = "Uzdarska hiša", cost = { gold = 1220, wood = 350, stone = 270, silver = 7, iron = 7 }, upkeep = 26, qualityBonus = 18 },
    master_bridle_atelier = { name = "Mojstrski uzdarski atelje", cost = { gold = 3050, wood = 410, stone = 525, silver = 36, gold = 7 }, upkeep = 72, qualityBonus = 30 },
    sovereign_bridle_palace = { name = "Suverena uzdarska palača", cost = { gold = 13100, wood = 630, stone = 835, gold = 84, jewel = 19 }, upkeep = 257, qualityBonus = 55, prestigeBonus = 50 },
}
BridleMaker.ironStock = 12; BridleMaker.bronzeStock = 10; BridleMaker.woodStock = 14; BridleMaker.leatherStock = 14; BridleMaker.silverStock = 8; BridleMaker.goldStock = 6; BridleMaker.jewelStock = 4; BridleMaker.pearlStock = 4
BridleMaker.productStock = {}; BridleMaker.buildings = {}; BridleMaker.maker = nil; BridleMaker.activeMaking = {}; BridleMaker.totalProducts = 0; BridleMaker.dayTimer = 0
function BridleMaker.init() BridleMaker.ironStock=12; BridleMaker.bronzeStock=10; BridleMaker.woodStock=14; BridleMaker.leatherStock=14; BridleMaker.silverStock=8; BridleMaker.goldStock=6; BridleMaker.jewelStock=4; BridleMaker.pearlStock=4; BridleMaker.productStock={}; BridleMaker.buildings={}; BridleMaker.maker=nil; BridleMaker.activeMaking={}; BridleMaker.totalProducts=0; BridleMaker.dayTimer=0; print("[BridleMaker] Royal Bridle Maker System initialized (6 products, 4 buildings)") end
function BridleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BridleMaker.maker={name=n or ("Uzdar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Uzdar najet: %s (spretnost: %d)",BridleMaker.maker.name,s),"success") end; return true end
function BridleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BridleMaker.build(id) local ok,e=BridleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BridleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BridleMaker.getQualityBonus() local b=0; for _,bd in ipairs(BridleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BridleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BridleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BridleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BridleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BridleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BridleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BridleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BridleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BridleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BridleMaker.buildings==0 then return false,"Potrebna uzdarska delavnica" end; if not BridleMaker.maker then return false,"Potreben uzdar" end; return true end
function BridleMaker.make(pt,qty) qty=qty or 1; local ok,e=BridleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BridleMaker.ironStock=BridleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BridleMaker.bronzeStock=BridleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BridleMaker.woodStock=BridleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BridleMaker.leatherStock=BridleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BridleMaker.silverStock=BridleMaker.silverStock-d.silverCost*qty end; if d.goldCost then BridleMaker.goldStock=BridleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BridleMaker.jewelStock=BridleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BridleMaker.pearlStock=BridleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BridleMaker.maker then t=math.max(1,t-math.floor(BridleMaker.maker.skill/13)) end; table.insert(BridleMaker.activeMaking,{id="bridle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BridleMaker.completeMaking(m) local q=1.0+(BridleMaker.getQualityBonus()/100); if BridleMaker.maker then q=q+(BridleMaker.maker.skill/140) end; q=math.min(2.5,q); BridleMaker.productStock[m.productType]=(BridleMaker.productStock[m.productType] or 0)+m.quantity; BridleMaker.totalProducts=BridleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BridleMaker.maker then BridleMaker.maker.itemsMade=BridleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BridleMaker.maker.skill=math.min(100,BridleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Uzda izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bridle.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BridleMaker.update(dt) if not _G.state then return end; BridleMaker.dayTimer=BridleMaker.dayTimer+dt; if BridleMaker.dayTimer>=30 then BridleMaker.dayTimer=0; for i=#BridleMaker.activeMaking,1,-1 do local m=BridleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BridleMaker.completeMaking(m); table.remove(BridleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BridleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BridleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BridleMaker.getStats() return {ironStock=BridleMaker.ironStock,bronzeStock=BridleMaker.bronzeStock,woodStock=BridleMaker.woodStock,leatherStock=BridleMaker.leatherStock,silverStock=BridleMaker.silverStock,goldStock=BridleMaker.goldStock,jewelStock=BridleMaker.jewelStock,pearlStock=BridleMaker.pearlStock,productStock=BridleMaker.productStock,numBuildings=#BridleMaker.buildings,hasMaker=BridleMaker.maker~=nil,makerName=BridleMaker.maker and BridleMaker.maker.name or "—",makerSkill=BridleMaker.maker and BridleMaker.maker.skill or 0,activeMaking=#BridleMaker.activeMaking,totalProducts=BridleMaker.totalProducts} end
return BridleMaker
