local BindingCordMaker = {}
local PRODUCTS = {
    iron_binding_cord = { name = "Železna vezalna vrvica", ironCost = 1, woodCost = 2, leatherCost = 3, time = 5, cost = 155, prestige = 4, happiness = 2, description = "Železna vezalna vrvica za vezavo knjig." },
    bronze_binding_cord = { name = "Bronasta vezalna vrvica", bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 3, time = 7, cost = 375, prestige = 6, happiness = 3, description = "Bronasta vezalna vrvica za trdno vezavo." },
    silver_binding_cord = { name = "Srebrna vezalna vrvica", silverCost = 1, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 3, time = 11, cost = 910, prestige = 11, happiness = 4, description = "Srebrna vezalna vrvica za plemiške knjigoveže." },
    gilded_binding_cord = { name = "Pozlačena vezalna vrvica", goldCost = 1, silverCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 3, time = 15, cost = 1960, prestige = 20, happiness = 5, description = "Pozlačena vezalna vrvica za dvorne knjigoveže." },
    jewel_set_binding_cord = { name = "Draguljasta vezalna vrvica", goldCost = 2, silverCost = 1, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 3, time = 19, cost = 4250, prestige = 36, happiness = 7, description = "Draguljasta vezalna vrvica za kraljevske knjigoveže." },
    royal_sovereign_binding_cord = { name = "Kraljevski suverena vezalna vrvica", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 4, time = 26, cost = 9100, prestige = 68, happiness = 13, description = "Suverena vezalna vrvica z biseri za krono." },
}
local BUILDINGS = {
    bindingcord_workshop = { name = "Vezalna delavnica", cost = { gold = 320, wood = 180, stone = 130, iron = 6 }, upkeep = 6, qualityBonus = 5 },
    bindingcord_house = { name = "Vezalna hiša", cost = { gold = 1185, wood = 365, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bindingcord_atelier = { name = "Mojstrski vezalni atelje", cost = { gold = 2980, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bindingcord_palace = { name = "Suverena vezalna palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BindingCordMaker.ironStock = 10; BindingCordMaker.bronzeStock = 8; BindingCordMaker.woodStock = 14; BindingCordMaker.leatherStock = 16; BindingCordMaker.silverStock = 8; BindingCordMaker.goldStock = 6; BindingCordMaker.jewelStock = 4; BindingCordMaker.pearlStock = 4
BindingCordMaker.productStock = {}; BindingCordMaker.buildings = {}; BindingCordMaker.maker = nil; BindingCordMaker.activeMaking = {}; BindingCordMaker.totalProducts = 0; BindingCordMaker.dayTimer = 0
function BindingCordMaker.init() BindingCordMaker.ironStock=10; BindingCordMaker.bronzeStock=8; BindingCordMaker.woodStock=14; BindingCordMaker.leatherStock=16; BindingCordMaker.silverStock=8; BindingCordMaker.goldStock=6; BindingCordMaker.jewelStock=4; BindingCordMaker.pearlStock=4; BindingCordMaker.productStock={}; BindingCordMaker.buildings={}; BindingCordMaker.maker=nil; BindingCordMaker.activeMaking={}; BindingCordMaker.totalProducts=0; BindingCordMaker.dayTimer=0; print("[BindingCordMaker] Royal Binding Cord Maker System initialized (6 products, 4 buildings)") end
function BindingCordMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BindingCordMaker.maker={name=n or ("Vezar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vezar najet: %s (spretnost: %d)",BindingCordMaker.maker.name,s),"success") end; return true end
function BindingCordMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BindingCordMaker.build(id) local ok,e=BindingCordMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BindingCordMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BindingCordMaker.getQualityBonus() local b=0; for _,bd in ipairs(BindingCordMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BindingCordMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BindingCordMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BindingCordMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BindingCordMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BindingCordMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BindingCordMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BindingCordMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BindingCordMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BindingCordMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BindingCordMaker.buildings==0 then return false,"Potrebna vezalna delavnica" end; if not BindingCordMaker.maker then return false,"Potreben vezar" end; return true end
function BindingCordMaker.make(pt,qty) qty=qty or 1; local ok,e=BindingCordMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BindingCordMaker.ironStock=BindingCordMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BindingCordMaker.bronzeStock=BindingCordMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BindingCordMaker.woodStock=BindingCordMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BindingCordMaker.leatherStock=BindingCordMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BindingCordMaker.silverStock=BindingCordMaker.silverStock-d.silverCost*qty end; if d.goldCost then BindingCordMaker.goldStock=BindingCordMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BindingCordMaker.jewelStock=BindingCordMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BindingCordMaker.pearlStock=BindingCordMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BindingCordMaker.maker then t=math.max(1,t-math.floor(BindingCordMaker.maker.skill/13)) end; table.insert(BindingCordMaker.activeMaking,{id="bindingcord_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BindingCordMaker.completeMaking(m) local q=1.0+(BindingCordMaker.getQualityBonus()/100); if BindingCordMaker.maker then q=q+(BindingCordMaker.maker.skill/140) end; q=math.min(2.5,q); BindingCordMaker.productStock[m.productType]=(BindingCordMaker.productStock[m.productType] or 0)+m.quantity; BindingCordMaker.totalProducts=BindingCordMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BindingCordMaker.maker then BindingCordMaker.maker.itemsMade=BindingCordMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BindingCordMaker.maker.skill=math.min(100,BindingCordMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrvica izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bindingcord.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BindingCordMaker.update(dt) if not _G.state then return end; BindingCordMaker.dayTimer=BindingCordMaker.dayTimer+dt; if BindingCordMaker.dayTimer>=30 then BindingCordMaker.dayTimer=0; for i=#BindingCordMaker.activeMaking,1,-1 do local m=BindingCordMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BindingCordMaker.completeMaking(m); table.remove(BindingCordMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BindingCordMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BindingCordMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BindingCordMaker.getStats() return {ironStock=BindingCordMaker.ironStock,bronzeStock=BindingCordMaker.bronzeStock,woodStock=BindingCordMaker.woodStock,leatherStock=BindingCordMaker.leatherStock,silverStock=BindingCordMaker.silverStock,goldStock=BindingCordMaker.goldStock,jewelStock=BindingCordMaker.jewelStock,pearlStock=BindingCordMaker.pearlStock,productStock=BindingCordMaker.productStock,numBuildings=#BindingCordMaker.buildings,hasMaker=BindingCordMaker.maker~=nil,makerName=BindingCordMaker.maker and BindingCordMaker.maker.name or "—",makerSkill=BindingCordMaker.maker and BindingCordMaker.maker.skill or 0,activeMaking=#BindingCordMaker.activeMaking,totalProducts=BindingCordMaker.totalProducts} end
return BindingCordMaker
