local GardenClocheMaker = {}
local PRODUCTS = {
    iron_gardencloche = { name = "Železni stekleni pokrov za rastline", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni stekleni pokrov za rastline za vrtnarje." },
    bronze_gardencloche = { name = "Bronast stekleni pokrov za rastline", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast stekleni pokrov za rastline za vrtnarje." },
    silver_gardencloche = { name = "Srebrn stekleni pokrov za rastline", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn stekleni pokrov za rastline za vrtnarje." },
    gilded_gardencloche = { name = "Pozlačen stekleni pokrov za rastline", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen stekleni pokrov za rastline za vrtnarje." },
    jewel_set_gardencloche = { name = "Draguljast stekleni pokrov za rastline", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast stekleni pokrov za rastline za vrtnarje." },
    royal_sovereign_gardencloche = { name = "Kraljevski suveren stekleni pokrov za rastline", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren stekleni pokrov za rastline z biseri za krono." },
}
local BUILDINGS = {
    gardencloche_workshop = { name = "Gardencloche delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardencloche_house = { name = "Gardencloche hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardencloche_atelier = { name = "Mojstrski gardencloche atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardencloche_palace = { name = "Suverena gardencloche palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenClocheMaker.ironStock=12; GardenClocheMaker.bronzeStock=10; GardenClocheMaker.woodStock=14; GardenClocheMaker.leatherStock=10; GardenClocheMaker.silverStock=8; GardenClocheMaker.goldStock=6; GardenClocheMaker.jewelStock=4; GardenClocheMaker.pearlStock=4
GardenClocheMaker.productStock = {}; GardenClocheMaker.buildings = {}; GardenClocheMaker.maker = nil; GardenClocheMaker.activeMaking = {}; GardenClocheMaker.totalProducts = 0; GardenClocheMaker.dayTimer = 0
function GardenClocheMaker.init() GardenClocheMaker.ironStock=12; GardenClocheMaker.bronzeStock=10; GardenClocheMaker.woodStock=14; GardenClocheMaker.leatherStock=10; GardenClocheMaker.silverStock=8; GardenClocheMaker.goldStock=6; GardenClocheMaker.jewelStock=4; GardenClocheMaker.pearlStock=4; GardenClocheMaker.productStock={}; GardenClocheMaker.buildings={}; GardenClocheMaker.maker=nil; GardenClocheMaker.activeMaking={}; GardenClocheMaker.totalProducts=0; GardenClocheMaker.dayTimer=0; print("[GardenClocheMaker] Royal Garden Cloche Maker System initialized (6 products, 4 buildings)") end
function GardenClocheMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenClocheMaker.maker={name=n or ("Pokrovnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pokrovnik najet: %s (spretnost: %d)",GardenClocheMaker.maker.name,s),"success") end; return true end
function GardenClocheMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenClocheMaker.build(id) local ok,e=GardenClocheMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenClocheMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenClocheMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenClocheMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenClocheMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenClocheMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenClocheMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenClocheMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenClocheMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenClocheMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenClocheMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenClocheMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenClocheMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenClocheMaker.buildings==0 then return false,"Potrebna pokrovna delavnica" end; if not GardenClocheMaker.maker then return false,"Potreben pokrovnik" end; return true end
function GardenClocheMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenClocheMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenClocheMaker.ironStock=GardenClocheMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenClocheMaker.bronzeStock=GardenClocheMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenClocheMaker.woodStock=GardenClocheMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenClocheMaker.leatherStock=GardenClocheMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenClocheMaker.silverStock=GardenClocheMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenClocheMaker.goldStock=GardenClocheMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenClocheMaker.jewelStock=GardenClocheMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenClocheMaker.pearlStock=GardenClocheMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenClocheMaker.maker then t=math.max(1,t-math.floor(GardenClocheMaker.maker.skill/13)) end; table.insert(GardenClocheMaker.activeMaking,{id="gardencloche_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenClocheMaker.completeMaking(m) local q=1.0+(GardenClocheMaker.getQualityBonus()/100); if GardenClocheMaker.maker then q=q+(GardenClocheMaker.maker.skill/140) end; q=math.min(2.5,q); GardenClocheMaker.productStock[m.productType]=(GardenClocheMaker.productStock[m.productType] or 0)+m.quantity; GardenClocheMaker.totalProducts=GardenClocheMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenClocheMaker.maker then GardenClocheMaker.maker.itemsMade=GardenClocheMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenClocheMaker.maker.skill=math.min(100,GardenClocheMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pokrov izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardencloche.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenClocheMaker.update(dt) if not _G.state then return end; GardenClocheMaker.dayTimer=GardenClocheMaker.dayTimer+dt; if GardenClocheMaker.dayTimer>=30 then GardenClocheMaker.dayTimer=0; for i=#GardenClocheMaker.activeMaking,1,-1 do local m=GardenClocheMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenClocheMaker.completeMaking(m); table.remove(GardenClocheMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenClocheMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenClocheMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenClocheMaker.getStats() return {ironStock=GardenClocheMaker.ironStock,bronzeStock=GardenClocheMaker.bronzeStock,woodStock=GardenClocheMaker.woodStock,leatherStock=GardenClocheMaker.leatherStock,silverStock=GardenClocheMaker.silverStock,goldStock=GardenClocheMaker.goldStock,jewelStock=GardenClocheMaker.jewelStock,pearlStock=GardenClocheMaker.pearlStock,productStock=GardenClocheMaker.productStock,numBuildings=#GardenClocheMaker.buildings,hasMaker=GardenClocheMaker.maker~=nil,makerName=GardenClocheMaker.maker and GardenClocheMaker.maker.name or "—",makerSkill=GardenClocheMaker.maker and GardenClocheMaker.maker.skill or 0,activeMaking=#GardenClocheMaker.activeMaking,totalProducts=GardenClocheMaker.totalProducts} end
return GardenClocheMaker
