local LeatherSplitterMaker = {}
local PRODUCTS = {
    iron_leathersplitter = { name = "Železni cepalec usnja", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni cepalec usnja za usnjarje." },
    bronze_leathersplitter = { name = "Bronast cepalec usnja", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast cepalec usnja za usnjarje." },
    silver_leathersplitter = { name = "Srebrn cepalec usnja", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn cepalec usnja za usnjarje." },
    gilded_leathersplitter = { name = "Pozlačen cepalec usnja", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen cepalec usnja za usnjarje." },
    jewel_set_leathersplitter = { name = "Draguljast cepalec usnja", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast cepalec usnja za usnjarje." },
    royal_sovereign_leathersplitter = { name = "Kraljevski suveren cepalec usnja", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren cepalec usnja z biseri za krono." },
}
local BUILDINGS = {
    leathersplitter_workshop = { name = "Leathersplitter delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    leathersplitter_house = { name = "Leathersplitter hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_leathersplitter_atelier = { name = "Mojstrski leathersplitter atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_leathersplitter_palace = { name = "Suverena leathersplitter palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
LeatherSplitterMaker.ironStock = 18; LeatherSplitterMaker.bronzeStock = 14; LeatherSplitterMaker.woodStock = 8; LeatherSplitterMaker.leatherStock = 10; LeatherSplitterMaker.silverStock = 8; LeatherSplitterMaker.goldStock = 6; LeatherSplitterMaker.jewelStock = 4; LeatherSplitterMaker.pearlStock = 4
LeatherSplitterMaker.productStock = {}; LeatherSplitterMaker.buildings = {}; LeatherSplitterMaker.maker = nil; LeatherSplitterMaker.activeMaking = {}; LeatherSplitterMaker.totalProducts = 0; LeatherSplitterMaker.dayTimer = 0
function LeatherSplitterMaker.init() LeatherSplitterMaker.ironStock=18; LeatherSplitterMaker.bronzeStock=14; LeatherSplitterMaker.woodStock=8; LeatherSplitterMaker.leatherStock=10; LeatherSplitterMaker.silverStock=8; LeatherSplitterMaker.goldStock=6; LeatherSplitterMaker.jewelStock=4; LeatherSplitterMaker.pearlStock=4; LeatherSplitterMaker.productStock={}; LeatherSplitterMaker.buildings={}; LeatherSplitterMaker.maker=nil; LeatherSplitterMaker.activeMaking={}; LeatherSplitterMaker.totalProducts=0; LeatherSplitterMaker.dayTimer=0; print("[LeatherSplitterMaker] Royal Leather Splitter Maker System initialized (6 products, 4 buildings)") end
function LeatherSplitterMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LeatherSplitterMaker.maker={name=n or ("Cepalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Cepalec najet: %s (spretnost: %d)",LeatherSplitterMaker.maker.name,s),"success") end; return true end
function LeatherSplitterMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LeatherSplitterMaker.build(id) local ok,e=LeatherSplitterMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LeatherSplitterMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LeatherSplitterMaker.getQualityBonus() local b=0; for _,bd in ipairs(LeatherSplitterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LeatherSplitterMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and LeatherSplitterMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and LeatherSplitterMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and LeatherSplitterMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and LeatherSplitterMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and LeatherSplitterMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and LeatherSplitterMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and LeatherSplitterMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and LeatherSplitterMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #LeatherSplitterMaker.buildings==0 then return false,"Potrebna cepalna delavnica" end; if not LeatherSplitterMaker.maker then return false,"Potreben cepalec" end; return true end
function LeatherSplitterMaker.make(pt,qty) qty=qty or 1; local ok,e=LeatherSplitterMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then LeatherSplitterMaker.ironStock=LeatherSplitterMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then LeatherSplitterMaker.bronzeStock=LeatherSplitterMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then LeatherSplitterMaker.woodStock=LeatherSplitterMaker.woodStock-d.woodCost*qty end; if d.leatherCost then LeatherSplitterMaker.leatherStock=LeatherSplitterMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then LeatherSplitterMaker.silverStock=LeatherSplitterMaker.silverStock-d.silverCost*qty end; if d.goldCost then LeatherSplitterMaker.goldStock=LeatherSplitterMaker.goldStock-d.goldCost*qty end; if d.jewelCost then LeatherSplitterMaker.jewelStock=LeatherSplitterMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then LeatherSplitterMaker.pearlStock=LeatherSplitterMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if LeatherSplitterMaker.maker then t=math.max(1,t-math.floor(LeatherSplitterMaker.maker.skill/13)) end; table.insert(LeatherSplitterMaker.activeMaking,{id="${MAKER_LOWER}_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LeatherSplitterMaker.completeMaking(m) local q=1.0+(LeatherSplitterMaker.getQualityBonus()/100); if LeatherSplitterMaker.maker then q=q+(LeatherSplitterMaker.maker.skill/140) end; q=math.min(2.5,q); LeatherSplitterMaker.productStock[m.productType]=(LeatherSplitterMaker.productStock[m.productType] or 0)+m.quantity; LeatherSplitterMaker.totalProducts=LeatherSplitterMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LeatherSplitterMaker.maker then LeatherSplitterMaker.maker.itemsMade=LeatherSplitterMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then LeatherSplitterMaker.maker.skill=math.min(100,LeatherSplitterMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Cepalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"${MAKER_LOWER}.completed",{productName=m.productName,prestige=m.prestige,happiness:m.happiness}) end end
function LeatherSplitterMaker.update(dt) if not _G.state then return end; LeatherSplitterMaker.dayTimer=LeatherSplitterMaker.dayTimer+dt; if LeatherSplitterMaker.dayTimer>=30 then LeatherSplitterMaker.dayTimer=0; for i=#LeatherSplitterMaker.activeMaking,1,-1 do local m=LeatherSplitterMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LeatherSplitterMaker.completeMaking(m); table.remove(LeatherSplitterMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LeatherSplitterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LeatherSplitterMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LeatherSplitterMaker.getStats() return {ironStock=LeatherSplitterMaker.ironStock,bronzeStock=LeatherSplitterMaker.bronzeStock,woodStock=LeatherSplitterMaker.woodStock,leatherStock=LeatherSplitterMaker.leatherStock,silverStock=LeatherSplitterMaker.silverStock,goldStock=LeatherSplitterMaker.goldStock,jewelStock=LeatherSplitterMaker.jewelStock,pearlStock=LeatherSplitterMaker.pearlStock,productStock=LeatherSplitterMaker.productStock,numBuildings=#LeatherSplitterMaker.buildings,hasMaker=LeatherSplitterMaker.maker~=nil,makerName=LeatherSplitterMaker.maker and LeatherSplitterMaker.maker.name or "—",makerSkill=LeatherSplitterMaker.maker and LeatherSplitterMaker.maker.skill or 0,activeMaking=#LeatherSplitterMaker.activeMaking,totalProducts=LeatherSplitterMaker.totalProducts} end
return LeatherSplitterMaker
