local ManuscriptIlluminator = {}
local PRODUCTS = {
    simple_painted_initial = { name = "Preprost poslikan začetnik", parchmentCost = 1, paintCost = 2, time = 4, cost = 60, happiness = 1, description = "Preprost poslikan začetnik za listine." },
    gilded_border_illumination = { name = "Pozlačeni robni ornament", parchmentCost = 2, paintCost = 2, goldCost = 1, time = 7, cost = 180, happiness = 2, prestige = 3, description = "Pozlačeni robni ornament za plemiške listine." },
    silver_filigree_illumination = { name = "Srebrnofiligranska iluminacija", parchmentCost = 2, paintCost = 3, silverCost = 1, goldCost = 1, time = 10, cost = 460, happiness = 3, prestige = 9, description = "Srebrnofiligranska iluminacija za visoke plemiče." },
    gold_leaf_miniature = { name = "Zlatolistna miniatúra", parchmentCost = 3, paintCost = 3, goldCost = 2, silverCost = 1, time = 14, cost = 1100, happiness = 4, prestige = 20, description = "Zlatolistna miniatúra za visoko plemstvo." },
    jewel_inlaid_illumination = { name = "Draguljarska iluminacija", parchmentCost = 3, paintCost = 4, goldCost = 2, silverCost = 1, jewelCost = 1, time = 18, cost = 2300, happiness = 6, prestige = 32, description = "Iluminacija z draguljem za visoko plemstvo." },
    royal_grand_illumination = { name = "Kraljevski velika iluminacija", parchmentCost = 5, paintCost = 5, goldCost = 3, silverCost = 2, jewelCost = 2, pearlCost = 2, time = 25, cost = 4600, happiness = 13, prestige = 62, description = "Velika kraljevska iluminacija z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    illuminator_cell = { name = "Iluminatorjeva celica", cost = { gold = 260, wood = 100, stone = 100, paint = 6, parchment = 6 }, upkeep = 6, qualityBonus = 5 },
    scriptorium_hall = { name = "Skriptorijska dvorana", cost = { gold = 900, wood = 260, stone = 280, silver = 12, paint = 10 }, upkeep = 22, qualityBonus = 18 },
    gilding_atelier = { name = "Pozlatorski atelje", cost = { gold = 2400, wood = 380, stone = 520, gold = 8, silver = 30 }, upkeep = 55, qualityBonus = 30 },
    royal_illuminations_palace = { name = "Kraljevska iluminacijska palača", cost = { gold = 9800, wood = 600, stone = 760, gold = 65, jewel = 16 }, upkeep = 195, qualityBonus = 55, prestigeBonus = 50 },
}
ManuscriptIlluminator.parchmentStock = 14; ManuscriptIlluminator.paintStock = 16; ManuscriptIlluminator.silverStock = 8; ManuscriptIlluminator.goldStock = 8; ManuscriptIlluminator.jewelStock = 4; ManuscriptIlluminator.pearlStock = 4
ManuscriptIlluminator.productStock = {}; ManuscriptIlluminator.buildings = {}; ManuscriptIlluminator.maker = nil; ManuscriptIlluminator.activeMaking = {}; ManuscriptIlluminator.totalProducts = 0; ManuscriptIlluminator.dayTimer = 0
function ManuscriptIlluminator.init() ManuscriptIlluminator.parchmentStock=14; ManuscriptIlluminator.paintStock=16; ManuscriptIlluminator.silverStock=8; ManuscriptIlluminator.goldStock=8; ManuscriptIlluminator.jewelStock=4; ManuscriptIlluminator.pearlStock=4; ManuscriptIlluminator.productStock={}; ManuscriptIlluminator.buildings={}; ManuscriptIlluminator.maker=nil; ManuscriptIlluminator.activeMaking={}; ManuscriptIlluminator.totalProducts=0; ManuscriptIlluminator.dayTimer=0; print("[ManuscriptIlluminator] Royal Manuscript Illuminator System initialized (6 products, 4 buildings)") end
function ManuscriptIlluminator.hireMaker(n,s) s=s or math.random(55,90); local c=560+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ManuscriptIlluminator.maker={name=n or ("Iluminator "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Iluminator najet: %s (spretnost: %d)",ManuscriptIlluminator.maker.name,s),"success") end; return true end
function ManuscriptIlluminator.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ManuscriptIlluminator.build(id) local ok,e=ManuscriptIlluminator.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ManuscriptIlluminator.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ManuscriptIlluminator.getQualityBonus() local b=0; for _,bd in ipairs(ManuscriptIlluminator.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ManuscriptIlluminator.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.parchmentCost and ManuscriptIlluminator.parchmentStock<(d.parchmentCost or 0) then return false,"Premalo pergamenta" end; if d.paintCost and ManuscriptIlluminator.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.silverCost and ManuscriptIlluminator.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ManuscriptIlluminator.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ManuscriptIlluminator.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ManuscriptIlluminator.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ManuscriptIlluminator.buildings==0 then return false,"Potrebna iluminatorjeva celica" end; if not ManuscriptIlluminator.maker then return false,"Potreben iluminator" end; return true end
function ManuscriptIlluminator.make(pt,qty) qty=qty or 1; local ok,e=ManuscriptIlluminator.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.parchmentCost then ManuscriptIlluminator.parchmentStock=ManuscriptIlluminator.parchmentStock-d.parchmentCost*qty end; if d.paintCost then ManuscriptIlluminator.paintStock=ManuscriptIlluminator.paintStock-d.paintCost*qty end; if d.silverCost then ManuscriptIlluminator.silverStock=ManuscriptIlluminator.silverStock-d.silverCost*qty end; if d.goldCost then ManuscriptIlluminator.goldStock=ManuscriptIlluminator.goldStock-d.goldCost*qty end; if d.jewelCost then ManuscriptIlluminator.jewelStock=ManuscriptIlluminator.jewelStock-d.jewelCost*qty end; if d.pearlCost then ManuscriptIlluminator.pearlStock=ManuscriptIlluminator.pearlStock-d.pearlCost*qty end; local t=d.time; if ManuscriptIlluminator.maker then t=math.max(1,t-math.floor(ManuscriptIlluminator.maker.skill/13)) end; table.insert(ManuscriptIlluminator.activeMaking,{id="illumination_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Poslikava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ManuscriptIlluminator.completeMaking(m) local q=1.0+(ManuscriptIlluminator.getQualityBonus()/100); if ManuscriptIlluminator.maker then q=q+(ManuscriptIlluminator.maker.skill/150) end; q=math.min(2.4,q); ManuscriptIlluminator.productStock[m.productType]=(ManuscriptIlluminator.productStock[m.productType] or 0)+m.quantity; ManuscriptIlluminator.totalProducts=ManuscriptIlluminator.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ManuscriptIlluminator.maker then ManuscriptIlluminator.maker.itemsMade=ManuscriptIlluminator.maker.itemsMade+m.quantity; if math.random()<0.25 then ManuscriptIlluminator.maker.skill=math.min(100,ManuscriptIlluminator.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Iluminacija končana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"illumination.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ManuscriptIlluminator.update(dt) if not _G.state then return end; ManuscriptIlluminator.dayTimer=ManuscriptIlluminator.dayTimer+dt; if ManuscriptIlluminator.dayTimer>=30 then ManuscriptIlluminator.dayTimer=0; for i=#ManuscriptIlluminator.activeMaking,1,-1 do local m=ManuscriptIlluminator.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ManuscriptIlluminator.completeMaking(m); table.remove(ManuscriptIlluminator.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ManuscriptIlluminator.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ManuscriptIlluminator.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ManuscriptIlluminator.getStats() return {parchmentStock=ManuscriptIlluminator.parchmentStock,paintStock=ManuscriptIlluminator.paintStock,silverStock=ManuscriptIlluminator.silverStock,goldStock=ManuscriptIlluminator.goldStock,jewelStock=ManuscriptIlluminator.jewelStock,pearlStock=ManuscriptIlluminator.pearlStock,productStock=ManuscriptIlluminator.productStock,numBuildings=#ManuscriptIlluminator.buildings,hasMaker=ManuscriptIlluminator.maker~=nil,makerName=ManuscriptIlluminator.maker and ManuscriptIlluminator.maker.name or "—",makerSkill=ManuscriptIlluminator.maker and ManuscriptIlluminator.maker.skill or 0,activeMaking=#ManuscriptIlluminator.activeMaking,totalProducts=ManuscriptIlluminator.totalProducts} end
return ManuscriptIlluminator
