local TrellisMaker = {}
local PRODUCTS = {
    iron_trellis = { name = "Železni loška rešetka za rastline", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni loška rešetka za rastline za vrtnarje." },
    bronze_trellis = { name = "Bronast loška rešetka za rastline", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast loška rešetka za rastline za vrtnarje." },
    silver_trellis = { name = "Srebrn loška rešetka za rastline", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn loška rešetka za rastline za vrtnarje." },
    gilded_trellis = { name = "Pozlačen loška rešetka za rastline", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen loška rešetka za rastline za vrtnarje." },
    jewel_set_trellis = { name = "Draguljast loška rešetka za rastline", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast loška rešetka za rastline za vrtnarje." },
    royal_sovereign_trellis = { name = "Kraljevski suveren loška rešetka za rastline", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren loška rešetka za rastline z biseri za krono." },
}
local BUILDINGS = {
    trellis_workshop = { name = "Trellis delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    trellis_house = { name = "Trellis hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_trellis_atelier = { name = "Mojstrski trellis atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_trellis_palace = { name = "Suverena trellis palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
TrellisMaker.ironStock=12; TrellisMaker.bronzeStock=10; TrellisMaker.woodStock=18; TrellisMaker.leatherStock=8; TrellisMaker.silverStock=8; TrellisMaker.goldStock=6; TrellisMaker.jewelStock=4; TrellisMaker.pearlStock=4
TrellisMaker.productStock = {}; TrellisMaker.buildings = {}; TrellisMaker.maker = nil; TrellisMaker.activeMaking = {}; TrellisMaker.totalProducts = 0; TrellisMaker.dayTimer = 0
function TrellisMaker.init() TrellisMaker.ironStock=12; TrellisMaker.bronzeStock=10; TrellisMaker.woodStock=18; TrellisMaker.leatherStock=8; TrellisMaker.silverStock=8; TrellisMaker.goldStock=6; TrellisMaker.jewelStock=4; TrellisMaker.pearlStock=4; TrellisMaker.productStock={}; TrellisMaker.buildings={}; TrellisMaker.maker=nil; TrellisMaker.activeMaking={}; TrellisMaker.totalProducts=0; TrellisMaker.dayTimer=0; print("[TrellisMaker] Royal Trellis Maker System initialized (6 products, 4 buildings)") end
function TrellisMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TrellisMaker.maker={name=n or ("Rešetkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rešetkar najet: %s (spretnost: %d)",TrellisMaker.maker.name,s),"success") end; return true end
function TrellisMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TrellisMaker.build(id) local ok,e=TrellisMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TrellisMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TrellisMaker.getQualityBonus() local b=0; for _,bd in ipairs(TrellisMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TrellisMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and TrellisMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and TrellisMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and TrellisMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and TrellisMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and TrellisMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and TrellisMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and TrellisMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and TrellisMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #TrellisMaker.buildings==0 then return false,"Potrebna rešetkarska delavnica" end; if not TrellisMaker.maker then return false,"Potreben rešetkar" end; return true end
function TrellisMaker.make(pt,qty) qty=qty or 1; local ok,e=TrellisMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then TrellisMaker.ironStock=TrellisMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then TrellisMaker.bronzeStock=TrellisMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then TrellisMaker.woodStock=TrellisMaker.woodStock-d.woodCost*qty end; if d.leatherCost then TrellisMaker.leatherStock=TrellisMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then TrellisMaker.silverStock=TrellisMaker.silverStock-d.silverCost*qty end; if d.goldCost then TrellisMaker.goldStock=TrellisMaker.goldStock-d.goldCost*qty end; if d.jewelCost then TrellisMaker.jewelStock=TrellisMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then TrellisMaker.pearlStock=TrellisMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if TrellisMaker.maker then t=math.max(1,t-math.floor(TrellisMaker.maker.skill/13)) end; table.insert(TrellisMaker.activeMaking,{id="trellis_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TrellisMaker.completeMaking(m) local q=1.0+(TrellisMaker.getQualityBonus()/100); if TrellisMaker.maker then q=q+(TrellisMaker.maker.skill/140) end; q=math.min(2.5,q); TrellisMaker.productStock[m.productType]=(TrellisMaker.productStock[m.productType] or 0)+m.quantity; TrellisMaker.totalProducts=TrellisMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if TrellisMaker.maker then TrellisMaker.maker.itemsMade=TrellisMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then TrellisMaker.maker.skill=math.min(100,TrellisMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rešetka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"trellis.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function TrellisMaker.update(dt) if not _G.state then return end; TrellisMaker.dayTimer=TrellisMaker.dayTimer+dt; if TrellisMaker.dayTimer>=30 then TrellisMaker.dayTimer=0; for i=#TrellisMaker.activeMaking,1,-1 do local m=TrellisMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TrellisMaker.completeMaking(m); table.remove(TrellisMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TrellisMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TrellisMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TrellisMaker.getStats() return {ironStock=TrellisMaker.ironStock,bronzeStock=TrellisMaker.bronzeStock,woodStock=TrellisMaker.woodStock,leatherStock=TrellisMaker.leatherStock,silverStock=TrellisMaker.silverStock,goldStock=TrellisMaker.goldStock,jewelStock=TrellisMaker.jewelStock,pearlStock=TrellisMaker.pearlStock,productStock=TrellisMaker.productStock,numBuildings=#TrellisMaker.buildings,hasMaker=TrellisMaker.maker~=nil,makerName=TrellisMaker.maker and TrellisMaker.maker.name or "—",makerSkill=TrellisMaker.maker and TrellisMaker.maker.skill or 0,activeMaking=#TrellisMaker.activeMaking,totalProducts=TrellisMaker.totalProducts} end
return TrellisMaker
