local HurdyGurdyMaker = {}
local PRODUCTS = {
    simple_hurdy = { name = "Preprosta_vrtavka", woodCost = 3, gutCost = 3, time = 3, cost = 60, soundQuality = 10, prestige = 2, description = "Preprosta vrtavka z ročico." },
    diatonic_hurdy = { name = "Diatonska vrtavka", woodCost = 4, gutCost = 4, time = 5, cost = 180, soundQuality = 14, prestige = 4, description = "Diatonska vrtavka z eno melodijo." },
    chromatic_hurdy = { name = "Kromatska vrtavka", woodCost = 4, gutCost = 6, brassCost = 1, time = 7, cost = 420, soundQuality = 18, prestige = 8, happiness = 1, description = "Kromatska vrtavka z medeninastimi tipkami." },
    two_bridge_hurdy = { name = "Dvonosilčna vrtavka", woodCost = 5, gutCost = 8, brassCost = 1, time = 9, cost = 900, soundQuality = 22, prestige = 13, happiness = 2, description = "Vrtavka z dvema nosilcema za polifonijo." },
    silver_hurdy = { name = "Srebrna vrtavka", woodCost = 5, silverCost = 1, gutCost = 8, time = 12, cost = 1700, soundQuality = 28, prestige = 20, happiness = 4, description = "Srebrna vrtavka za plemiške dvorane." },
    royal_lute_hurdy = { name = "Kraljevska lutnjarska vrtavka", woodCost = 6, goldCost = 2, silverCost = 1, gutCost = 10, pearlCost = 1, time = 16, cost = 2600, soundQuality = 40, prestige = 52, happiness = 11, description = "Velika kraljevska vrtavka z zlatim okovjem in biseri." },
}
local BUILDINGS = {
    workshop = { name = "Vrtilna delavnica", cost = { gold = 280, wood = 140 }, upkeep = 7, qualityBonus = 5 },
    wheel_room = { name = "Kolesna soba", cost = { gold = 850, wood = 240, stone = 200, gut = 8 }, upkeep = 20, qualityBonus = 18 },
    key_room = { name = "Tipkarska soba", cost = { gold = 1800, wood = 300, stone = 400, silver = 25, brass = 8 }, upkeep = 42, qualityBonus = 30 },
    royal_hurdy_atelier = { name = "Kraljevski atelje vrtavk", cost = { gold = 7000, wood = 600, stone = 800, gold = 50, silver = 30 }, upkeep = 130, qualityBonus = 55, prestigeBonus = 33 },
}
HurdyGurdyMaker.woodStock = 18; HurdyGurdyMaker.gutStock = 14; HurdyGurdyMaker.brassStock = 8; HurdyGurdyMaker.silverStock = 6; HurdyGurdyMaker.goldStock = 6; HurdyGurdyMaker.pearlStock = 4
HurdyGurdyMaker.productStock = {}; HurdyGurdyMaker.buildings = {}; HurdyGurdyMaker.maker = nil; HurdyGurdyMaker.activeMaking = {}; HurdyGurdyMaker.totalProducts = 0; HurdyGurdyMaker.dayTimer = 0
function HurdyGurdyMaker.init() HurdyGurdyMaker.woodStock=18; HurdyGurdyMaker.gutStock=14; HurdyGurdyMaker.brassStock=8; HurdyGurdyMaker.silverStock=6; HurdyGurdyMaker.goldStock=6; HurdyGurdyMaker.pearlStock=4; HurdyGurdyMaker.productStock={}; HurdyGurdyMaker.buildings={}; HurdyGurdyMaker.maker=nil; HurdyGurdyMaker.activeMaking={}; HurdyGurdyMaker.totalProducts=0; HurdyGurdyMaker.dayTimer=0; print("[HurdyGurdyMaker] Royal Hurdy-Gurdy Maker System initialized (6 products, 4 buildings)") end
function HurdyGurdyMaker.hireMaker(n,s) s=s or math.random(50,90); local c=490+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HurdyGurdyMaker.maker={name=n or ("Vrtilkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrtilkar najet: %s (spretnost: %d)",HurdyGurdyMaker.maker.name,s),"success") end; return true end
function HurdyGurdyMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HurdyGurdyMaker.build(id) local ok,e=HurdyGurdyMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HurdyGurdyMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HurdyGurdyMaker.getQualityBonus() local b=0; for _,bd in ipairs(HurdyGurdyMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HurdyGurdyMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and HurdyGurdyMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.gutCost and HurdyGurdyMaker.gutStock<(d.gutCost or 0) then return false,"Premalo črevesja" end; if d.brassCost and HurdyGurdyMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and HurdyGurdyMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HurdyGurdyMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.pearlCost and HurdyGurdyMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HurdyGurdyMaker.buildings==0 then return false,"Potrebna delavnica" end; if not HurdyGurdyMaker.maker then return false,"Potreben vrtilkar" end; return true end
function HurdyGurdyMaker.make(pt,qty) qty=qty or 1; local ok,e=HurdyGurdyMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then HurdyGurdyMaker.woodStock=HurdyGurdyMaker.woodStock-d.woodCost*qty end; if d.gutCost then HurdyGurdyMaker.gutStock=HurdyGurdyMaker.gutStock-d.gutCost*qty end; if d.brassCost then HurdyGurdyMaker.brassStock=HurdyGurdyMaker.brassStock-d.brassCost*qty end; if d.silverCost then HurdyGurdyMaker.silverStock=HurdyGurdyMaker.silverStock-d.silverCost*qty end; if d.goldCost then HurdyGurdyMaker.goldStock=HurdyGurdyMaker.goldStock-d.goldCost*qty end; if d.pearlCost then HurdyGurdyMaker.pearlStock=HurdyGurdyMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HurdyGurdyMaker.maker then t=math.max(1,t-math.floor(HurdyGurdyMaker.maker.skill/12)) end; table.insert(HurdyGurdyMaker.activeMaking,{id="hurdy_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,soundQuality=d.soundQuality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HurdyGurdyMaker.completeMaking(m) local q=1.0+(HurdyGurdyMaker.getQualityBonus()/100); if HurdyGurdyMaker.maker then q=q+(HurdyGurdyMaker.maker.skill/180) end; q=math.min(2.0,q); HurdyGurdyMaker.productStock[m.productType]=(HurdyGurdyMaker.productStock[m.productType] or 0)+m.quantity; HurdyGurdyMaker.totalProducts=HurdyGurdyMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HurdyGurdyMaker.maker then HurdyGurdyMaker.maker.itemsMade=HurdyGurdyMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then HurdyGurdyMaker.maker.skill=math.min(100,HurdyGurdyMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrtavka izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"hurdygurdy.completed",{productName=m.productName,soundQuality=m.soundQuality}) end end
function HurdyGurdyMaker.update(dt) if not _G.state then return end; HurdyGurdyMaker.dayTimer=HurdyGurdyMaker.dayTimer+dt; if HurdyGurdyMaker.dayTimer>=30 then HurdyGurdyMaker.dayTimer=0; for i=#HurdyGurdyMaker.activeMaking,1,-1 do local m=HurdyGurdyMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HurdyGurdyMaker.completeMaking(m); table.remove(HurdyGurdyMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HurdyGurdyMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HurdyGurdyMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HurdyGurdyMaker.getStats() return {woodStock=HurdyGurdyMaker.woodStock,gutStock=HurdyGurdyMaker.gutStock,brassStock=HurdyGurdyMaker.brassStock,silverStock=HurdyGurdyMaker.silverStock,goldStock=HurdyGurdyMaker.goldStock,pearlStock=HurdyGurdyMaker.pearlStock,productStock=HurdyGurdyMaker.productStock,numBuildings=#HurdyGurdyMaker.buildings,hasMaker=HurdyGurdyMaker.maker~=nil,makerName=HurdyGurdyMaker.maker and HurdyGurdyMaker.maker.name or "—",makerSkill=HurdyGurdyMaker.maker and HurdyGurdyMaker.maker.skill or 0,activeMaking=#HurdyGurdyMaker.activeMaking,totalProducts=HurdyGurdyMaker.totalProducts} end
return HurdyGurdyMaker
