local CompostAeratorMaker = {}
local PRODUCTS = {
    iron_compostaerator = { name = "Železni zračnik za kompost", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni zračnik za kompost za vrtove." },
    bronze_compostaerator = { name = "Bronast zračnik za kompost", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast zračnik za kompost za vrtove." },
    silver_compostaerator = { name = "Srebrn zračnik za kompost", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn zračnik za kompost za vrtove." },
    gilded_compostaerator = { name = "Pozlačen zračnik za kompost", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen zračnik za kompost za vrtove." },
    jewel_set_compostaerator = { name = "Draguljast zračnik za kompost", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast zračnik za kompost za vrtove." },
    royal_sovereign_compostaerator = { name = "Kraljevski suveren zračnik za kompost", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren zračnik za kompost z biseri za krono." },
}
local BUILDINGS = {
    compostaerator_workshop = { name = "Compostaerator delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    compostaerator_house = { name = "Compostaerator hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_compostaerator_atelier = { name = "Mojstrski compostaerator atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_compostaerator_palace = { name = "Suverena compostaerator palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
CompostAeratorMaker.ironStock = 16; CompostAeratorMaker.bronzeStock = 14; CompostAeratorMaker.woodStock = 10; CompostAeratorMaker.leatherStock = 8; CompostAeratorMaker.silverStock = 8; CompostAeratorMaker.goldStock = 6; CompostAeratorMaker.jewelStock = 4; CompostAeratorMaker.pearlStock = 4
CompostAeratorMaker.productStock = {}; CompostAeratorMaker.buildings = {}; CompostAeratorMaker.maker = nil; CompostAeratorMaker.activeMaking = {}; CompostAeratorMaker.totalProducts = 0; CompostAeratorMaker.dayTimer = 0
function CompostAeratorMaker.init() CompostAeratorMaker.ironStock=16; CompostAeratorMaker.bronzeStock=14; CompostAeratorMaker.woodStock=10; CompostAeratorMaker.leatherStock=8; CompostAeratorMaker.silverStock=8; CompostAeratorMaker.goldStock=6; CompostAeratorMaker.jewelStock=4; CompostAeratorMaker.pearlStock=4; CompostAeratorMaker.productStock={}; CompostAeratorMaker.buildings={}; CompostAeratorMaker.maker=nil; CompostAeratorMaker.activeMaking={}; CompostAeratorMaker.totalProducts=0; CompostAeratorMaker.dayTimer=0; print("[CompostAeratorMaker] Royal Compost Aerator Maker System initialized (6 products, 4 buildings)") end
function CompostAeratorMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CompostAeratorMaker.maker={name=n or ("Zračnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zračnik najet: %s (spretnost: %d)",CompostAeratorMaker.maker.name,s),"success") end; return true end
function CompostAeratorMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CompostAeratorMaker.build(id) local ok,e=CompostAeratorMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CompostAeratorMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CompostAeratorMaker.getQualityBonus() local b=0; for _,bd in ipairs(CompostAeratorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CompostAeratorMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CompostAeratorMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CompostAeratorMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CompostAeratorMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CompostAeratorMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CompostAeratorMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CompostAeratorMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CompostAeratorMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CompostAeratorMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CompostAeratorMaker.buildings==0 then return false,"Potrebna zračna delavnica" end; if not CompostAeratorMaker.maker then return false,"Potreben zracnik" end; return true end
function CompostAeratorMaker.make(pt,qty) qty=qty or 1; local ok,e=CompostAeratorMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CompostAeratorMaker.ironStock=CompostAeratorMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CompostAeratorMaker.bronzeStock=CompostAeratorMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CompostAeratorMaker.woodStock=CompostAeratorMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CompostAeratorMaker.leatherStock=CompostAeratorMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CompostAeratorMaker.silverStock=CompostAeratorMaker.silverStock-d.silverCost*qty end; if d.goldCost then CompostAeratorMaker.goldStock=CompostAeratorMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CompostAeratorMaker.jewelStock=CompostAeratorMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CompostAeratorMaker.pearlStock=CompostAeratorMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CompostAeratorMaker.maker then t=math.max(1,t-math.floor(CompostAeratorMaker.maker.skill/13)) end; table.insert(CompostAeratorMaker.activeMaking,{id="compostaerator_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CompostAeratorMaker.completeMaking(m) local q=1.0+(CompostAeratorMaker.getQualityBonus()/100); if CompostAeratorMaker.maker then q=q+(CompostAeratorMaker.maker.skill/140) end; q=math.min(2.5,q); CompostAeratorMaker.productStock[m.productType]=(CompostAeratorMaker.productStock[m.productType] or 0)+m.quantity; CompostAeratorMaker.totalProducts=CompostAeratorMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CompostAeratorMaker.maker then CompostAeratorMaker.maker.itemsMade=CompostAeratorMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CompostAeratorMaker.maker.skill=math.min(100,CompostAeratorMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zračnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"compostaerator.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CompostAeratorMaker.update(dt) if not _G.state then return end; CompostAeratorMaker.dayTimer=CompostAeratorMaker.dayTimer+dt; if CompostAeratorMaker.dayTimer>=30 then CompostAeratorMaker.dayTimer=0; for i=#CompostAeratorMaker.activeMaking,1,-1 do local m=CompostAeratorMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CompostAeratorMaker.completeMaking(m); table.remove(CompostAeratorMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CompostAeratorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CompostAeratorMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CompostAeratorMaker.getStats() return {ironStock=CompostAeratorMaker.ironStock,bronzeStock=CompostAeratorMaker.bronzeStock,woodStock=CompostAeratorMaker.woodStock,leatherStock=CompostAeratorMaker.leatherStock,silverStock=CompostAeratorMaker.silverStock,goldStock=CompostAeratorMaker.goldStock,jewelStock=CompostAeratorMaker.jewelStock,pearlStock=CompostAeratorMaker.pearlStock,productStock=CompostAeratorMaker.productStock,numBuildings=#CompostAeratorMaker.buildings,hasMaker=CompostAeratorMaker.maker~=nil,makerName=CompostAeratorMaker.maker and CompostAeratorMaker.maker.name or "—",makerSkill=CompostAeratorMaker.maker and CompostAeratorMaker.maker.skill or 0,activeMaking=#CompostAeratorMaker.activeMaking,totalProducts=CompostAeratorMaker.totalProducts} end
return CompostAeratorMaker
