local GlassLehrBeltMaker = {}
local PRODUCTS = {
    iron_glasslehrbelt = { name = "Železni trak za ohlajevalne peči", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni trak za ohlajevalne peči za steklarje." },
    bronze_glasslehrbelt = { name = "Bronast trak za ohlajevalne peči", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast trak za ohlajevalne peči za steklarje." },
    silver_glasslehrbelt = { name = "Srebrn trak za ohlajevalne peči", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn trak za ohlajevalne peči za steklarje." },
    gilded_glasslehrbelt = { name = "Pozlačen trak za ohlajevalne peči", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen trak za ohlajevalne peči za steklarje." },
    jewel_set_glasslehrbelt = { name = "Draguljast trak za ohlajevalne peči", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast trak za ohlajevalne peči za steklarje." },
    royal_sovereign_glasslehrbelt = { name = "Kraljevski suveren trak za ohlajevalne peči", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren trak za ohlajevalne peči z biseri za krono." },
}
local BUILDINGS = {
    glasslehrbelt_workshop = { name = "Glasslehrbelt delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glasslehrbelt_house = { name = "Glasslehrbelt hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glasslehrbelt_atelier = { name = "Mojstrski glasslehrbelt atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glasslehrbelt_palace = { name = "Suverena glasslehrbelt palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassLehrBeltMaker.ironStock=14; GlassLehrBeltMaker.bronzeStock=12; GlassLehrBeltMaker.woodStock=14; GlassLehrBeltMaker.leatherStock=10; GlassLehrBeltMaker.silverStock=8; GlassLehrBeltMaker.goldStock=6; GlassLehrBeltMaker.jewelStock=4; GlassLehrBeltMaker.pearlStock=4
GlassLehrBeltMaker.productStock = {}; GlassLehrBeltMaker.buildings = {}; GlassLehrBeltMaker.maker = nil; GlassLehrBeltMaker.activeMaking = {}; GlassLehrBeltMaker.totalProducts = 0; GlassLehrBeltMaker.dayTimer = 0
function GlassLehrBeltMaker.init() GlassLehrBeltMaker.ironStock=14; GlassLehrBeltMaker.bronzeStock=12; GlassLehrBeltMaker.woodStock=14; GlassLehrBeltMaker.leatherStock=10; GlassLehrBeltMaker.silverStock=8; GlassLehrBeltMaker.goldStock=6; GlassLehrBeltMaker.jewelStock=4; GlassLehrBeltMaker.pearlStock=4; GlassLehrBeltMaker.productStock={}; GlassLehrBeltMaker.buildings={}; GlassLehrBeltMaker.maker=nil; GlassLehrBeltMaker.activeMaking={}; GlassLehrBeltMaker.totalProducts=0; GlassLehrBeltMaker.dayTimer=0; print("[GlassLehrBeltMaker] Royal Glass Lehr Belt Maker System initialized (6 products, 4 buildings)") end
function GlassLehrBeltMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassLehrBeltMaker.maker={name=n or ("Tračar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tračar najet: %s (spretnost: %d)",GlassLehrBeltMaker.maker.name,s),"success") end; return true end
function GlassLehrBeltMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassLehrBeltMaker.build(id) local ok,e=GlassLehrBeltMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassLehrBeltMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassLehrBeltMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassLehrBeltMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassLehrBeltMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassLehrBeltMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassLehrBeltMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassLehrBeltMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassLehrBeltMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassLehrBeltMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassLehrBeltMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassLehrBeltMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassLehrBeltMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassLehrBeltMaker.buildings==0 then return false,"Potrebna tračna delavnica" end; if not GlassLehrBeltMaker.maker then return false,"Potreben tračar" end; return true end
function GlassLehrBeltMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassLehrBeltMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassLehrBeltMaker.ironStock=GlassLehrBeltMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassLehrBeltMaker.bronzeStock=GlassLehrBeltMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassLehrBeltMaker.woodStock=GlassLehrBeltMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassLehrBeltMaker.leatherStock=GlassLehrBeltMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassLehrBeltMaker.silverStock=GlassLehrBeltMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassLehrBeltMaker.goldStock=GlassLehrBeltMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassLehrBeltMaker.jewelStock=GlassLehrBeltMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassLehrBeltMaker.pearlStock=GlassLehrBeltMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassLehrBeltMaker.maker then t=math.max(1,t-math.floor(GlassLehrBeltMaker.maker.skill/13)) end; table.insert(GlassLehrBeltMaker.activeMaking,{id="glasslehrbelt_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassLehrBeltMaker.completeMaking(m) local q=1.0+(GlassLehrBeltMaker.getQualityBonus()/100); if GlassLehrBeltMaker.maker then q=q+(GlassLehrBeltMaker.maker.skill/140) end; q=math.min(2.5,q); GlassLehrBeltMaker.productStock[m.productType]=(GlassLehrBeltMaker.productStock[m.productType] or 0)+m.quantity; GlassLehrBeltMaker.totalProducts=GlassLehrBeltMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassLehrBeltMaker.maker then GlassLehrBeltMaker.maker.itemsMade=GlassLehrBeltMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassLehrBeltMaker.maker.skill=math.min(100,GlassLehrBeltMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Traček izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glasslehrbelt.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassLehrBeltMaker.update(dt) if not _G.state then return end; GlassLehrBeltMaker.dayTimer=GlassLehrBeltMaker.dayTimer+dt; if GlassLehrBeltMaker.dayTimer>=30 then GlassLehrBeltMaker.dayTimer=0; for i=#GlassLehrBeltMaker.activeMaking,1,-1 do local m=GlassLehrBeltMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassLehrBeltMaker.completeMaking(m); table.remove(GlassLehrBeltMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassLehrBeltMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassLehrBeltMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassLehrBeltMaker.getStats() return {ironStock=GlassLehrBeltMaker.ironStock,bronzeStock=GlassLehrBeltMaker.bronzeStock,woodStock=GlassLehrBeltMaker.woodStock,leatherStock=GlassLehrBeltMaker.leatherStock,silverStock=GlassLehrBeltMaker.silverStock,goldStock=GlassLehrBeltMaker.goldStock,jewelStock=GlassLehrBeltMaker.jewelStock,pearlStock=GlassLehrBeltMaker.pearlStock,productStock=GlassLehrBeltMaker.productStock,numBuildings=#GlassLehrBeltMaker.buildings,hasMaker=GlassLehrBeltMaker.maker~=nil,makerName=GlassLehrBeltMaker.maker and GlassLehrBeltMaker.maker.name or "—",makerSkill=GlassLehrBeltMaker.maker and GlassLehrBeltMaker.maker.skill or 0,activeMaking=#GlassLehrBeltMaker.activeMaking,totalProducts=GlassLehrBeltMaker.totalProducts} end
return GlassLehrBeltMaker
