local PerfumeBottleMaker = {}
local PRODUCTS = {
    iron_perfumebottle = { name = "Železni steklenička za parfum", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni steklenička za parfum za glasbila." },
    bronze_perfumebottle = { name = "Bronast steklenička za parfum", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast steklenička za parfum za fino glasbo." },
    silver_perfumebottle = { name = "Srebrn steklenička za parfum", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn steklenička za parfum za plemiške glasbenike." },
    gilded_perfumebottle = { name = "Pozlačen steklenička za parfum", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen steklenička za parfum za dvorne glasbenike." },
    jewel_set_perfumebottle = { name = "Draguljast steklenička za parfum", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast steklenička za parfum za kraljevske glasbenike." },
    royal_sovereign_perfumebottle = { name = "Kraljevski suveren steklenička za parfum", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren steklenička za parfum z biseri za krono." },
}
local BUILDINGS = {
    perfumebottle_workshop = { name = "Perfumebottle delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    perfumebottle_house = { name = "Perfumebottle hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_perfumebottle_atelier = { name = "Mojstrski perfumebottle atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_perfumebottle_palace = { name = "Suverena perfumebottle palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
PerfumeBottleMaker.ironStock = 12; PerfumeBottleMaker.bronzeStock = 10; PerfumeBottleMaker.woodStock = 14; PerfumeBottleMaker.leatherStock = 12; PerfumeBottleMaker.silverStock = 8; PerfumeBottleMaker.goldStock = 6; PerfumeBottleMaker.jewelStock = 4; PerfumeBottleMaker.pearlStock = 4
PerfumeBottleMaker.productStock = {}; PerfumeBottleMaker.buildings = {}; PerfumeBottleMaker.maker = nil; PerfumeBottleMaker.activeMaking = {}; PerfumeBottleMaker.totalProducts = 0; PerfumeBottleMaker.dayTimer = 0
function PerfumeBottleMaker.init() PerfumeBottleMaker.ironStock=12; PerfumeBottleMaker.bronzeStock=10; PerfumeBottleMaker.woodStock=14; PerfumeBottleMaker.leatherStock=12; PerfumeBottleMaker.silverStock=8; PerfumeBottleMaker.goldStock=6; PerfumeBottleMaker.jewelStock=4; PerfumeBottleMaker.pearlStock=4; PerfumeBottleMaker.productStock={}; PerfumeBottleMaker.buildings={}; PerfumeBottleMaker.maker=nil; PerfumeBottleMaker.activeMaking={}; PerfumeBottleMaker.totalProducts=0; PerfumeBottleMaker.dayTimer=0; print("[PerfumeBottleMaker] Royal Perfume Bottle Maker System initialized (6 products, 4 buildings)") end
function PerfumeBottleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PerfumeBottleMaker.maker={name=n or ("Stekleničar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stekleničar najet: %s (spretnost: %d)",PerfumeBottleMaker.maker.name,s),"success") end; return true end
function PerfumeBottleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PerfumeBottleMaker.build(id) local ok,e=PerfumeBottleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PerfumeBottleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PerfumeBottleMaker.getQualityBonus() local b=0; for _,bd in ipairs(PerfumeBottleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PerfumeBottleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PerfumeBottleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and PerfumeBottleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and PerfumeBottleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PerfumeBottleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PerfumeBottleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PerfumeBottleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PerfumeBottleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PerfumeBottleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PerfumeBottleMaker.buildings==0 then return false,"Potrebna steklenična delavnica" end; if not PerfumeBottleMaker.maker then return false,"Potreben steklenicar" end; return true end
function PerfumeBottleMaker.make(pt,qty) qty=qty or 1; local ok,e=PerfumeBottleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PerfumeBottleMaker.ironStock=PerfumeBottleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then PerfumeBottleMaker.bronzeStock=PerfumeBottleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then PerfumeBottleMaker.woodStock=PerfumeBottleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PerfumeBottleMaker.leatherStock=PerfumeBottleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then PerfumeBottleMaker.silverStock=PerfumeBottleMaker.silverStock-d.silverCost*qty end; if d.goldCost then PerfumeBottleMaker.goldStock=PerfumeBottleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PerfumeBottleMaker.jewelStock=PerfumeBottleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PerfumeBottleMaker.pearlStock=PerfumeBottleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PerfumeBottleMaker.maker then t=math.max(1,t-math.floor(PerfumeBottleMaker.maker.skill/13)) end; table.insert(PerfumeBottleMaker.activeMaking,{id="perfumebottle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PerfumeBottleMaker.completeMaking(m) local q=1.0+(PerfumeBottleMaker.getQualityBonus()/100); if PerfumeBottleMaker.maker then q=q+(PerfumeBottleMaker.maker.skill/140) end; q=math.min(2.5,q); PerfumeBottleMaker.productStock[m.productType]=(PerfumeBottleMaker.productStock[m.productType] or 0)+m.quantity; PerfumeBottleMaker.totalProducts=PerfumeBottleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PerfumeBottleMaker.maker then PerfumeBottleMaker.maker.itemsMade=PerfumeBottleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PerfumeBottleMaker.maker.skill=math.min(100,PerfumeBottleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Steklenička izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"perfumebottle.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function PerfumeBottleMaker.update(dt) if not _G.state then return end; PerfumeBottleMaker.dayTimer=PerfumeBottleMaker.dayTimer+dt; if PerfumeBottleMaker.dayTimer>=30 then PerfumeBottleMaker.dayTimer=0; for i=#PerfumeBottleMaker.activeMaking,1,-1 do local m=PerfumeBottleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PerfumeBottleMaker.completeMaking(m); table.remove(PerfumeBottleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PerfumeBottleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PerfumeBottleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PerfumeBottleMaker.getStats() return {ironStock=PerfumeBottleMaker.ironStock,bronzeStock=PerfumeBottleMaker.bronzeStock,woodStock=PerfumeBottleMaker.woodStock,leatherStock=PerfumeBottleMaker.leatherStock,silverStock=PerfumeBottleMaker.silverStock,goldStock=PerfumeBottleMaker.goldStock,jewelStock=PerfumeBottleMaker.jewelStock,pearlStock=PerfumeBottleMaker.pearlStock,productStock=PerfumeBottleMaker.productStock,numBuildings=#PerfumeBottleMaker.buildings,hasMaker=PerfumeBottleMaker.maker~=nil,makerName=PerfumeBottleMaker.maker and PerfumeBottleMaker.maker.name or "—",makerSkill=PerfumeBottleMaker.maker and PerfumeBottleMaker.maker.skill or 0,activeMaking=#PerfumeBottleMaker.activeMaking,totalProducts=PerfumeBottleMaker.totalProducts} end
return PerfumeBottleMaker
