local TrumpetMaker = {}
local PRODUCTS = {
    simple_bronze_trumpet = { name = "Preprosta bronasta trobenta", bronzeCost = 2, woodCost = 1, time = 4, cost = 50, music = 20, happiness = 2, description = "Preprosta bronasta trobenta za godbe." },
    brass_herald_trumpet = { name = "Medeninasta glasniška trobenta", brassCost = 2, bronzeCost = 1, woodCost = 1, time = 6, cost = 130, music = 35, happiness = 2, prestige = 2, description = "Medeninasta glasniška trobenta za trgovce." },
    silver_band_trumpet = { name = "Srebrna godbeniška trobenta", silverCost = 2, brassCost = 1, bronzeCost = 1, woodCost = 1, time = 10, cost = 320, music = 50, happiness = 3, prestige = 6, description = "Srebrna godbeniška trobenta za plemiče." },
    silver_with_banner_trumpet = { name = "Srebrna pasovna trobenta", silverCost = 2, brassCost = 1, silkCost = 1, woodCost = 1, time = 13, cost = 760, music = 65, happiness = 4, prestige = 14, description = "Srebrna trobenta s pasom za visoke plemiče." },
    gold_trimmed_fanfare_trumpet = { name = "Zlatookrasna fanfarna trobenta", goldCost = 2, silverCost = 1, brassCost = 1, silkCost = 1, woodCost = 1, jewelCost = 1, time = 17, cost = 1700, music = 80, happiness = 6, prestige = 27, description = "Zlatookrasna fanfarna trobenta z draguljem za visoko plemstvo." },
    royal_grand_trumpet = { name = "Kraljevski veliki trobenti", goldCost = 3, silverCost = 2, brassCost = 1, bronzeCost = 1, silkCost = 2, jewelCost = 2, pearlCost = 2, time = 24, cost = 3900, music = 95, happiness = 12, prestige = 58, description = "Veliki kraljevski trobenti z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    trumpet_workshop = { name = "Trobentna delavnica", cost = { gold = 240, wood = 100, stone = 100, bronze = 6 }, upkeep = 5, qualityBonus = 5 },
    brass_foundry = { name = "Medeninasta livarna", cost = { gold = 880, wood = 240, stone = 240, brass = 8, silver = 6 }, upkeep = 20, qualityBonus = 18 },
    master_trumpet_atelier = { name = "Mojstrski trobetni atelje", cost = { gold = 2400, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 55, qualityBonus = 30 },
    royal_trumpet_palace = { name = "Kraljevska trobentna palača", cost = { gold = 9800, wood = 580, stone = 760, gold = 60, jewel = 16 }, upkeep = 195, qualityBonus = 55, prestigeBonus = 50 },
}
TrumpetMaker.bronzeStock = 14; TrumpetMaker.brassStock = 14; TrumpetMaker.woodStock = 10; TrumpetMaker.silverStock = 6; TrumpetMaker.goldStock = 6; TrumpetMaker.silkStock = 6; TrumpetMaker.jewelStock = 4; TrumpetMaker.pearlStock = 4
TrumpetMaker.productStock = {}; TrumpetMaker.buildings = {}; TrumpetMaker.maker = nil; TrumpetMaker.activeMaking = {}; TrumpetMaker.totalProducts = 0; TrumpetMaker.dayTimer = 0
function TrumpetMaker.init() TrumpetMaker.bronzeStock=14; TrumpetMaker.brassStock=14; TrumpetMaker.woodStock=10; TrumpetMaker.silverStock=6; TrumpetMaker.goldStock=6; TrumpetMaker.silkStock=6; TrumpetMaker.jewelStock=4; TrumpetMaker.pearlStock=4; TrumpetMaker.productStock={}; TrumpetMaker.buildings={}; TrumpetMaker.maker=nil; TrumpetMaker.activeMaking={}; TrumpetMaker.totalProducts=0; TrumpetMaker.dayTimer=0; print("[TrumpetMaker] Royal Trumpet Maker System initialized (6 products, 4 buildings)") end
function TrumpetMaker.hireMaker(n,s) s=s or math.random(55,90); local c=500+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TrumpetMaker.maker={name=n or ("Trobentar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Trobentar najet: %s (spretnost: %d)",TrumpetMaker.maker.name,s),"success") end; return true end
function TrumpetMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TrumpetMaker.build(id) local ok,e=TrumpetMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TrumpetMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TrumpetMaker.getQualityBonus() local b=0; for _,bd in ipairs(TrumpetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TrumpetMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.bronzeCost and TrumpetMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.brassCost and TrumpetMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.woodCost and TrumpetMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.silverCost and TrumpetMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and TrumpetMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.silkCost and TrumpetMaker.silkStock<(d.silkCost or 0) then return false,"Premalo svile" end; if d.jewelCost and TrumpetMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and TrumpetMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #TrumpetMaker.buildings==0 then return false,"Potrebna trobentna delavnica" end; if not TrumpetMaker.maker then return false,"Potreben trobetar" end; return true end
function TrumpetMaker.make(pt,qty) qty=qty or 1; local ok,e=TrumpetMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.bronzeCost then TrumpetMaker.bronzeStock=TrumpetMaker.bronzeStock-d.bronzeCost*qty end; if d.brassCost then TrumpetMaker.brassStock=TrumpetMaker.brassStock-d.brassCost*qty end; if d.woodCost then TrumpetMaker.woodStock=TrumpetMaker.woodStock-d.woodCost*qty end; if d.silverCost then TrumpetMaker.silverStock=TrumpetMaker.silverStock-d.silverCost*qty end; if d.goldCost then TrumpetMaker.goldStock=TrumpetMaker.goldStock-d.goldCost*qty end; if d.silkCost then TrumpetMaker.silkStock=TrumpetMaker.silkStock-d.silkCost*qty end; if d.jewelCost then TrumpetMaker.jewelStock=TrumpetMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then TrumpetMaker.pearlStock=TrumpetMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if TrumpetMaker.maker then t=math.max(1,t-math.floor(TrumpetMaker.maker.skill/13)) end; table.insert(TrumpetMaker.activeMaking,{id="trumpet_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,music=d.music or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TrumpetMaker.completeMaking(m) local q=1.0+(TrumpetMaker.getQualityBonus()/100); if TrumpetMaker.maker then q=q+(TrumpetMaker.maker.skill/150) end; q=math.min(2.4,q); TrumpetMaker.productStock[m.productType]=(TrumpetMaker.productStock[m.productType] or 0)+m.quantity; TrumpetMaker.totalProducts=TrumpetMaker.totalProducts+m.quantity; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if TrumpetMaker.maker then TrumpetMaker.maker.itemsMade=TrumpetMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then TrumpetMaker.maker.skill=math.min(100,TrumpetMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Trobenta izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"trumpet.completed",{productName=m.productName,music=m.music,prestige=m.prestige,happiness=m.happiness}) end end
function TrumpetMaker.update(dt) if not _G.state then return end; TrumpetMaker.dayTimer=TrumpetMaker.dayTimer+dt; if TrumpetMaker.dayTimer>=30 then TrumpetMaker.dayTimer=0; for i=#TrumpetMaker.activeMaking,1,-1 do local m=TrumpetMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TrumpetMaker.completeMaking(m); table.remove(TrumpetMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TrumpetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TrumpetMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TrumpetMaker.getStats() return {bronzeStock=TrumpetMaker.bronzeStock,brassStock=TrumpetMaker.brassStock,woodStock=TrumpetMaker.woodStock,silverStock=TrumpetMaker.silverStock,goldStock=TrumpetMaker.goldStock,silkStock=TrumpetMaker.silkStock,jewelStock=TrumpetMaker.jewelStock,pearlStock=TrumpetMaker.pearlStock,productStock=TrumpetMaker.productStock,numBuildings=#TrumpetMaker.buildings,hasMaker=TrumpetMaker.maker~=nil,makerName=TrumpetMaker.maker and TrumpetMaker.maker.name or "—",makerSkill=TrumpetMaker.maker and TrumpetMaker.maker.skill or 0,activeMaking=#TrumpetMaker.activeMaking,totalProducts=TrumpetMaker.totalProducts} end
return TrumpetMaker
