local BookSpineCreaserMaker = {}
local PRODUCTS = {
    iron_bookspinecreaser = { name = "Železni gubalec hrbtov knjig", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni gubalec hrbtov knjig za knjigoveze." },
    bronze_bookspinecreaser = { name = "Bronast gubalec hrbtov knjig", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast gubalec hrbtov knjig za knjigoveze." },
    silver_bookspinecreaser = { name = "Srebrn gubalec hrbtov knjig", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn gubalec hrbtov knjig za knjigoveze." },
    gilded_bookspinecreaser = { name = "Pozlačen gubalec hrbtov knjig", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen gubalec hrbtov knjig za knjigoveze." },
    jewel_set_bookspinecreaser = { name = "Draguljast gubalec hrbtov knjig", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast gubalec hrbtov knjig za knjigoveze." },
    royal_sovereign_bookspinecreaser = { name = "Kraljevski suveren gubalec hrbtov knjig", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren gubalec hrbtov knjig z biseri za krono." },
}
local BUILDINGS = {
    bookspinecreaser_workshop = { name = "Bookspinecreaser delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookspinecreaser_house = { name = "Bookspinecreaser hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookspinecreaser_atelier = { name = "Mojstrski bookspinecreaser atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookspinecreaser_palace = { name = "Suverena bookspinecreaser palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookSpineCreaserMaker.ironStock=14; BookSpineCreaserMaker.bronzeStock=12; BookSpineCreaserMaker.woodStock=14; BookSpineCreaserMaker.leatherStock=8; BookSpineCreaserMaker.silverStock=8; BookSpineCreaserMaker.goldStock=6; BookSpineCreaserMaker.jewelStock=4; BookSpineCreaserMaker.pearlStock=4
BookSpineCreaserMaker.productStock = {}; BookSpineCreaserMaker.buildings = {}; BookSpineCreaserMaker.maker = nil; BookSpineCreaserMaker.activeMaking = {}; BookSpineCreaserMaker.totalProducts = 0; BookSpineCreaserMaker.dayTimer = 0
function BookSpineCreaserMaker.init() BookSpineCreaserMaker.ironStock=14; BookSpineCreaserMaker.bronzeStock=12; BookSpineCreaserMaker.woodStock=14; BookSpineCreaserMaker.leatherStock=8; BookSpineCreaserMaker.silverStock=8; BookSpineCreaserMaker.goldStock=6; BookSpineCreaserMaker.jewelStock=4; BookSpineCreaserMaker.pearlStock=4; BookSpineCreaserMaker.productStock={}; BookSpineCreaserMaker.buildings={}; BookSpineCreaserMaker.maker=nil; BookSpineCreaserMaker.activeMaking={}; BookSpineCreaserMaker.totalProducts=0; BookSpineCreaserMaker.dayTimer=0; print("[BookSpineCreaserMaker] Royal Book Spine Creaser Maker System initialized (6 products, 4 buildings)") end
function BookSpineCreaserMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookSpineCreaserMaker.maker={name=n or ("Hrbtogubalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Hrbtogubalec najet: %s (spretnost: %d)",BookSpineCreaserMaker.maker.name,s),"success") end; return true end
function BookSpineCreaserMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookSpineCreaserMaker.build(id) local ok,e=BookSpineCreaserMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookSpineCreaserMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookSpineCreaserMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookSpineCreaserMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookSpineCreaserMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookSpineCreaserMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookSpineCreaserMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookSpineCreaserMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookSpineCreaserMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookSpineCreaserMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookSpineCreaserMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookSpineCreaserMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookSpineCreaserMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookSpineCreaserMaker.buildings==0 then return false,"Potrebna hrbtogubalna delavnica" end; if not BookSpineCreaserMaker.maker then return false,"Potreben hrbtogubalec" end; return true end
function BookSpineCreaserMaker.make(pt,qty) qty=qty or 1; local ok,e=BookSpineCreaserMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookSpineCreaserMaker.ironStock=BookSpineCreaserMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookSpineCreaserMaker.bronzeStock=BookSpineCreaserMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookSpineCreaserMaker.woodStock=BookSpineCreaserMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookSpineCreaserMaker.leatherStock=BookSpineCreaserMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookSpineCreaserMaker.silverStock=BookSpineCreaserMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookSpineCreaserMaker.goldStock=BookSpineCreaserMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookSpineCreaserMaker.jewelStock=BookSpineCreaserMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookSpineCreaserMaker.pearlStock=BookSpineCreaserMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookSpineCreaserMaker.maker then t=math.max(1,t-math.floor(BookSpineCreaserMaker.maker.skill/13)) end; table.insert(BookSpineCreaserMaker.activeMaking,{id="bookspinecreaser_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookSpineCreaserMaker.completeMaking(m) local q=1.0+(BookSpineCreaserMaker.getQualityBonus()/100); if BookSpineCreaserMaker.maker then q=q+(BookSpineCreaserMaker.maker.skill/140) end; q=math.min(2.5,q); BookSpineCreaserMaker.productStock[m.productType]=(BookSpineCreaserMaker.productStock[m.productType] or 0)+m.quantity; BookSpineCreaserMaker.totalProducts=BookSpineCreaserMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookSpineCreaserMaker.maker then BookSpineCreaserMaker.maker.itemsMade=BookSpineCreaserMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookSpineCreaserMaker.maker.skill=math.min(100,BookSpineCreaserMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Hrbtogubalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookspinecreaser.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookSpineCreaserMaker.update(dt) if not _G.state then return end; BookSpineCreaserMaker.dayTimer=BookSpineCreaserMaker.dayTimer+dt; if BookSpineCreaserMaker.dayTimer>=30 then BookSpineCreaserMaker.dayTimer=0; for i=#BookSpineCreaserMaker.activeMaking,1,-1 do local m=BookSpineCreaserMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookSpineCreaserMaker.completeMaking(m); table.remove(BookSpineCreaserMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookSpineCreaserMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookSpineCreaserMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookSpineCreaserMaker.getStats() return {ironStock=BookSpineCreaserMaker.ironStock,bronzeStock=BookSpineCreaserMaker.bronzeStock,woodStock=BookSpineCreaserMaker.woodStock,leatherStock=BookSpineCreaserMaker.leatherStock,silverStock=BookSpineCreaserMaker.silverStock,goldStock=BookSpineCreaserMaker.goldStock,jewelStock=BookSpineCreaserMaker.jewelStock,pearlStock=BookSpineCreaserMaker.pearlStock,productStock=BookSpineCreaserMaker.productStock,numBuildings=#BookSpineCreaserMaker.buildings,hasMaker=BookSpineCreaserMaker.maker~=nil,makerName=BookSpineCreaserMaker.maker and BookSpineCreaserMaker.maker.name or "—",makerSkill=BookSpineCreaserMaker.maker and BookSpineCreaserMaker.maker.skill or 0,activeMaking=#BookSpineCreaserMaker.activeMaking,totalProducts=BookSpineCreaserMaker.totalProducts} end
return BookSpineCreaserMaker
