local LoomFrameMaker = {}
local PRODUCTS = {
    simple_wood_loom_frame = { name = "Preprost lesen statveni okvir", woodCost = 5, ropeCost = 2, time = 6, cost = 150, science = 20, happiness = 1, description = "Preprost lesen statveni okvir za tkanje." },
    iron_reinforced_loom = { name = "Železnookrepljena statve", woodCost = 4, ironCost = 2, ropeCost = 2, time = 9, cost = 380, science = 35, happiness = 2, prestige = 2, description = "Železnookrepljena statve za trgovce." },
    silver_trimmed_loom = { name = "Srebrnoobrobljene statve", woodCost = 4, silverCost = 1, ironCost = 2, ropeCost = 2, time = 12, cost = 880, science = 50, happiness = 2, prestige = 6, description = "Srebrnoobrobljene statve za plemiče." },
    gold_trimmed_loom = { name = "Zlatookrasne statve", woodCost = 4, goldCost = 1, silverCost = 1, ironCost = 2, ropeCost = 2, time = 16, cost = 2000, science = 65, happiness = 3, prestige = 14, description = "Zlatookrasne statve za visoke plemiče." },
    jewel_set_loom = { name = "Draguljasta statve", woodCost = 4, goldCost = 1, silverCost = 1, ironCost = 2, ropeCost = 2, jewelCost = 1, time = 20, cost = 4400, science = 80, happiness = 5, prestige = 27, description = "Statve z draguljem za visoko plemstvo." },
    royal_grand_loom = { name = "Kraljevski velike statve", woodCost = 6, goldCost = 2, silverCost = 2, ironCost = 2, ropeCost = 2, jewelCost = 2, pearlCost = 2, time = 27, cost = 9500, science = 95, happiness = 12, prestige = 58, description = "Velike kraljevske statve z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    loom_workshop = { name = "Statvena delavnica", cost = { gold = 300, wood = 180, stone = 120, rope = 6 }, upkeep = 6, qualityBonus = 5 },
    textile_loft = { name = "Tekstilna podstrešje", cost = { gold = 1100, wood = 320, stone = 240, silver = 6, iron = 6 }, upkeep = 25, qualityBonus = 18 },
    master_loom_atelier = { name = "Mojstrski statveni atelje", cost = { gold = 2900, wood = 380, stone = 480, silver = 32, gold = 6 }, upkeep = 68, qualityBonus = 30 },
    royal_textile_palace = { name = "Kraljevska tekstilna palača", cost = { gold = 12500, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 250, qualityBonus = 55, prestigeBonus = 50 },
}
LoomFrameMaker.woodStock = 22; LoomFrameMaker.ironStock = 12; LoomFrameMaker.ropeStock = 10; LoomFrameMaker.silverStock = 6; LoomFrameMaker.goldStock = 6; LoomFrameMaker.jewelStock = 4; LoomFrameMaker.pearlStock = 4
LoomFrameMaker.productStock = {}; LoomFrameMaker.buildings = {}; LoomFrameMaker.maker = nil; LoomFrameMaker.activeMaking = {}; LoomFrameMaker.totalProducts = 0; LoomFrameMaker.dayTimer = 0
function LoomFrameMaker.init() LoomFrameMaker.woodStock=22; LoomFrameMaker.ironStock=12; LoomFrameMaker.ropeStock=10; LoomFrameMaker.silverStock=6; LoomFrameMaker.goldStock=6; LoomFrameMaker.jewelStock=4; LoomFrameMaker.pearlStock=4; LoomFrameMaker.productStock={}; LoomFrameMaker.buildings={}; LoomFrameMaker.maker=nil; LoomFrameMaker.activeMaking={}; LoomFrameMaker.totalProducts=0; LoomFrameMaker.dayTimer=0; print("[LoomFrameMaker] Royal Loom Frame Maker System initialized (6 products, 4 buildings)") end
function LoomFrameMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LoomFrameMaker.maker={name=n or ("Statvar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Statvar najet: %s (spretnost: %d)",LoomFrameMaker.maker.name,s),"success") end; return true end
function LoomFrameMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LoomFrameMaker.build(id) local ok,e=LoomFrameMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LoomFrameMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LoomFrameMaker.getQualityBonus() local b=0; for _,bd in ipairs(LoomFrameMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LoomFrameMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and LoomFrameMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and LoomFrameMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.ropeCost and LoomFrameMaker.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.silverCost and LoomFrameMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and LoomFrameMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and LoomFrameMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and LoomFrameMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #LoomFrameMaker.buildings==0 then return false,"Potrebna statvena delavnica" end; if not LoomFrameMaker.maker then return false,"Potreben statvar" end; return true end
function LoomFrameMaker.make(pt,qty) qty=qty or 1; local ok,e=LoomFrameMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then LoomFrameMaker.woodStock=LoomFrameMaker.woodStock-d.woodCost*qty end; if d.ironCost then LoomFrameMaker.ironStock=LoomFrameMaker.ironStock-d.ironCost*qty end; if d.ropeCost then LoomFrameMaker.ropeStock=LoomFrameMaker.ropeStock-d.ropeCost*qty end; if d.silverCost then LoomFrameMaker.silverStock=LoomFrameMaker.silverStock-d.silverCost*qty end; if d.goldCost then LoomFrameMaker.goldStock=LoomFrameMaker.goldStock-d.goldCost*qty end; if d.jewelCost then LoomFrameMaker.jewelStock=LoomFrameMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then LoomFrameMaker.pearlStock=LoomFrameMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if LoomFrameMaker.maker then t=math.max(1,t-math.floor(LoomFrameMaker.maker.skill/12)) end; table.insert(LoomFrameMaker.activeMaking,{id="loomframe_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LoomFrameMaker.completeMaking(m) local q=1.0+(LoomFrameMaker.getQualityBonus()/100); if LoomFrameMaker.maker then q=q+(LoomFrameMaker.maker.skill/140) end; q=math.min(2.5,q); LoomFrameMaker.productStock[m.productType]=(LoomFrameMaker.productStock[m.productType] or 0)+m.quantity; LoomFrameMaker.totalProducts=LoomFrameMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LoomFrameMaker.maker then LoomFrameMaker.maker.itemsMade=LoomFrameMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then LoomFrameMaker.maker.skill=math.min(100,LoomFrameMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Statve izdelane: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"loomframe.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function LoomFrameMaker.update(dt) if not _G.state then return end; LoomFrameMaker.dayTimer=LoomFrameMaker.dayTimer+dt; if LoomFrameMaker.dayTimer>=30 then LoomFrameMaker.dayTimer=0; for i=#LoomFrameMaker.activeMaking,1,-1 do local m=LoomFrameMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LoomFrameMaker.completeMaking(m); table.remove(LoomFrameMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LoomFrameMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LoomFrameMaker.maker then tu=tu+16 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LoomFrameMaker.getStats() return {woodStock=LoomFrameMaker.woodStock,ironStock=LoomFrameMaker.ironStock,ropeStock=LoomFrameMaker.ropeStock,silverStock=LoomFrameMaker.silverStock,goldStock=LoomFrameMaker.goldStock,jewelStock=LoomFrameMaker.jewelStock,pearlStock=LoomFrameMaker.pearlStock,productStock=LoomFrameMaker.productStock,numBuildings=#LoomFrameMaker.buildings,hasMaker=LoomFrameMaker.maker~=nil,makerName=LoomFrameMaker.maker and LoomFrameMaker.maker.name or "—",makerSkill=LoomFrameMaker.maker and LoomFrameMaker.maker.skill or 0,activeMaking=#LoomFrameMaker.activeMaking,totalProducts=LoomFrameMaker.totalProducts} end
return LoomFrameMaker
