local StringMaker = {}
local PRODUCTS = {
    lute_string = { name = "Lutnja struna", gutCost = 1, time = 1, cost = 5, soundQuality = 10, description = "Struna za lutnjo." },
    harp_string = { name = "Harfna struna", gutCost = 2, time = 2, cost = 15, soundQuality = 15, description = "Struna za harfo." },
    violin_string = { name = "Violinska struna", gutCost = 2, silverCost = 1, time = 3, cost = 30, soundQuality = 20, prestige = 2, description = "Srebrno navita struna." },
    silver_string = { name = "Srebrna struna", silverCost = 2, gutCost = 1, time = 4, cost = 50, soundQuality = 25, prestige = 5, description = "Visokokakovostna srebrna struna." },
    gold_string = { name = "Zlata struna", goldCost = 1, gutCost = 1, time = 5, cost = 100, soundQuality = 30, prestige = 10, happiness = 2, description = "Zlata struna za kraljeve instrumente." },
    royal_string_set = { name = "Kraljevski set strun", goldCost = 2, silverCost = 2, gutCost = 3, time = 7, cost = 300, soundQuality = 40, prestige = 20, happiness = 5, description = "Komplet strun za kraljevske orgle." },
}
local BUILDINGS = {
    workshop = { name = "Strunarska delavnica", cost = { gold = 200, wood = 100 }, upkeep = 5, qualityBonus = 5 },
    drawing_room = { name = "Vlečilnica", cost = { gold = 600, wood = 200, stone = 100 }, upkeep = 15, qualityBonus = 15 },
    metal_winding = { name = "Kovinska navitnica", cost = { gold = 1000, wood = 200, stone = 200, silver = 30 }, upkeep = 25, qualityBonus = 20 },
    royal_stringery = { name = "Kraljevska strunarna", cost = { gold = 3000, wood = 400, stone = 500, gold = 30 }, upkeep = 60, qualityBonus = 35, prestigeBonus = 15 },
}
StringMaker.gutStock = 15; StringMaker.silverStock = 5; StringMaker.goldStock = 3
StringMaker.productStock = {}; StringMaker.buildings = {}; StringMaker.maker = nil; StringMaker.activeMaking = {}; StringMaker.totalProducts = 0; StringMaker.dayTimer = 0
function StringMaker.init() StringMaker.gutStock=15; StringMaker.silverStock=5; StringMaker.goldStock=3; StringMaker.productStock={}; StringMaker.buildings={}; StringMaker.maker=nil; StringMaker.activeMaking={}; StringMaker.totalProducts=0; StringMaker.dayTimer=0; print("[StringMaker] Royal Musical String Maker System initialized (6 products, 4 buildings)") end
function StringMaker.hireMaker(n,s) s=s or math.random(35,80); local c=250+s*5; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; StringMaker.maker={name=n or ("Strunar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Strunar najet: %s (spretnost: %d)",StringMaker.maker.name,s),"success") end; return true end
function StringMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function StringMaker.build(id) local ok,e=StringMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(StringMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function StringMaker.getQualityBonus() local b=0; for _,bd in ipairs(StringMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function StringMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.gutCost and StringMaker.gutStock<(d.gutCost or 0) then return false,"Premalo črevesja" end; if d.silverCost and StringMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and StringMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if #StringMaker.buildings==0 then return false,"Potrebna delavnica" end; if not StringMaker.maker then return false,"Potreben strunar" end; return true end
function StringMaker.make(pt,qty) qty=qty or 5; local ok,e=StringMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.gutCost then StringMaker.gutStock=StringMaker.gutStock-d.gutCost*qty end; if d.silverCost then StringMaker.silverStock=StringMaker.silverStock-d.silverCost*qty end; if d.goldCost then StringMaker.goldStock=StringMaker.goldStock-d.goldCost*qty end; local t=d.time; if StringMaker.maker then t=math.max(1,t-math.floor(StringMaker.maker.skill/15)) end; table.insert(StringMaker.activeMaking,{id="string_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,soundQuality=d.soundQuality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function StringMaker.completeMaking(m) local q=1.0+(StringMaker.getQualityBonus()/100); if StringMaker.maker then q=q+(StringMaker.maker.skill/200) end; q=math.min(2.0,q); StringMaker.productStock[m.productType]=(StringMaker.productStock[m.productType] or 0)+m.quantity; StringMaker.totalProducts=StringMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if StringMaker.maker then StringMaker.maker.itemsMade=StringMaker.maker.itemsMade+m.quantity; if math.random()<0.15 then StringMaker.maker.skill=math.min(100,StringMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Strune izdelane: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end end
function StringMaker.update(dt) if not _G.state then return end; StringMaker.dayTimer=StringMaker.dayTimer+dt; if StringMaker.dayTimer>=30 then StringMaker.dayTimer=0; for i=#StringMaker.activeMaking,1,-1 do local m=StringMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then StringMaker.completeMaking(m); table.remove(StringMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(StringMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if StringMaker.maker then tu=tu+8 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function StringMaker.getStats() return {gutStock=StringMaker.gutStock,silverStock=StringMaker.silverStock,goldStock=StringMaker.goldStock,productStock=StringMaker.productStock,numBuildings=#StringMaker.buildings,hasMaker=StringMaker.maker~=nil,makerName=StringMaker.maker and StringMaker.maker.name or "—",makerSkill=StringMaker.maker and StringMaker.maker.skill or 0,activeMaking=#StringMaker.activeMaking,totalProducts=StringMaker.totalProducts} end
return StringMaker
