local ParchmentMaker = {}
local PRODUCTS = {
    sheep_parchment = { name = "Ovčji pergament", hideCost = 1, limeCost = 1, waterCost = 1, time = 3, cost = 20, quality = 50, description = "Ovčji pergament za dokumente." },
    goat_parchment = { name = "Kozji pergament", hideCost = 1, limeCost = 1, waterCost = 1, time = 4, cost = 35, quality = 60, prestige = 1, description = "Kozji pergament za fine dokumente." },
    vellum = { name = "Velum", calfHideCost = 1, limeCost = 1, waterCost = 1, time = 6, cost = 85, quality = 75, prestige = 4, happiness = 1, description = "Velum iz teletje kože za dragocne dokumente." },
    silver_scraped_vellum = { name = "Srebrno ostrgani velum", calfHideCost = 1, silverCost = 1, limeCost = 1, waterCost = 1, time = 9, cost = 220, quality = 88, prestige = 10, happiness = 2, description = "Srebrno ostrgani velum za plemiče." },
    silver_trimmed_vellum = { name = "Srebrno obrobljeni velum", calfHideCost = 1, silverCost = 1, goldCost = 1, limeCost = 1, waterCost = 1, time = 12, cost = 500, quality = 94, prestige = 18, happiness = 3, description = "Srebrno obrobljeni velum za visoke plemiče." },
    royal_grand_vellum = { name = "Kraljevski veliki velum", calfHideCost = 2, goldCost = 1, silverCost = 1, jewelCost = 1, limeCost = 2, waterCost = 2, time = 17, cost = 1600, quality = 100, prestige = 40, happiness = 8, description = "Veliki kraljevski velum z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Pergamentna postaja", cost = { gold = 280, wood = 130, stone = 250 }, upkeep = 7, qualityBonus = 5 },
    parchment_house = { name = "Pergamentnica", cost = { gold = 950, wood = 250, stone = 450, lime = 8 }, upkeep = 23, qualityBonus = 18 },
    scraping_room = { name = "Strgalnica", cost = { gold = 2300, wood = 350, stone = 700, silver = 30, steel = 8 }, upkeep = 58, qualityBonus = 30 },
    royal_parchment_atelier = { name = "Kraljevski atelje pergamenta", cost = { gold = 9200, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 185, qualityBonus = 55, prestigeBonus = 40 },
}
ParchmentMaker.hideStock = 20; ParchmentMaker.calfHideStock = 14; ParchmentMaker.limeStock = 14; ParchmentMaker.waterStock = 18; ParchmentMaker.silverStock = 8; ParchmentMaker.goldStock = 6; ParchmentMaker.jewelStock = 6
ParchmentMaker.productStock = {}; ParchmentMaker.buildings = {}; ParchmentMaker.maker = nil; ParchmentMaker.activeMaking = {}; ParchmentMaker.totalProducts = 0; ParchmentMaker.dayTimer = 0
function ParchmentMaker.init() ParchmentMaker.hideStock=20; ParchmentMaker.calfHideStock=14; ParchmentMaker.limeStock=14; ParchmentMaker.waterStock=18; ParchmentMaker.silverStock=8; ParchmentMaker.goldStock=6; ParchmentMaker.jewelStock=6; ParchmentMaker.productStock={}; ParchmentMaker.buildings={}; ParchmentMaker.maker=nil; ParchmentMaker.activeMaking={}; ParchmentMaker.totalProducts=0; ParchmentMaker.dayTimer=0; print("[ParchmentMaker] Royal Parchment Maker System initialized (6 products, 4 buildings)") end
function ParchmentMaker.hireMaker(n,s) s=s or math.random(50,90); local c=520+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ParchmentMaker.maker={name=n or ("Pergamentar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pergamentar najet: %s (spretnost: %d)",ParchmentMaker.maker.name,s),"success") end; return true end
function ParchmentMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ParchmentMaker.build(id) local ok,e=ParchmentMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ParchmentMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ParchmentMaker.getQualityBonus() local b=0; for _,bd in ipairs(ParchmentMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ParchmentMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.hideCost and ParchmentMaker.hideStock<(d.hideCost or 0) then return false,"Premalo kož" end; if d.calfHideCost and ParchmentMaker.calfHideStock<(d.calfHideCost or 0) then return false,"Premalo teletjih kož" end; if d.limeCost and ParchmentMaker.limeStock<(d.limeCost or 0) then return false,"Premalo apna" end; if d.waterCost and ParchmentMaker.waterStock<(d.waterCost or 0) then return false,"Premalo vode" end; if d.silverCost and ParchmentMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ParchmentMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ParchmentMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #ParchmentMaker.buildings==0 then return false,"Potrebna delavnica" end; if not ParchmentMaker.maker then return false,"Potreben pergamentar" end; return true end
function ParchmentMaker.make(pt,qty) qty=qty or 5; local ok,e=ParchmentMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.hideCost then ParchmentMaker.hideStock=ParchmentMaker.hideStock-d.hideCost*qty end; if d.calfHideCost then ParchmentMaker.calfHideStock=ParchmentMaker.calfHideStock-d.calfHideCost*qty end; if d.limeCost then ParchmentMaker.limeStock=ParchmentMaker.limeStock-d.limeCost*qty end; if d.waterCost then ParchmentMaker.waterStock=ParchmentMaker.waterStock-d.waterCost*qty end; if d.silverCost then ParchmentMaker.silverStock=ParchmentMaker.silverStock-d.silverCost*qty end; if d.goldCost then ParchmentMaker.goldStock=ParchmentMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ParchmentMaker.jewelStock=ParchmentMaker.jewelStock-d.jewelCost*qty end; local t=d.time; if ParchmentMaker.maker then t=math.max(1,t-math.floor(ParchmentMaker.maker.skill/12)) end; table.insert(ParchmentMaker.activeMaking,{id="parchment_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,quality=d.quality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ParchmentMaker.completeMaking(m) local q=1.0+(ParchmentMaker.getQualityBonus()/100); if ParchmentMaker.maker then q=q+(ParchmentMaker.maker.skill/180) end; q=math.min(2.0,q); ParchmentMaker.productStock[m.productType]=(ParchmentMaker.productStock[m.productType] or 0)+m.quantity; ParchmentMaker.totalProducts=ParchmentMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ParchmentMaker.maker then ParchmentMaker.maker.itemsMade=ParchmentMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then ParchmentMaker.maker.skill=math.min(100,ParchmentMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pergament izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"parchment.completed",{productName=m.productName,quality=m.quality}) end end
function ParchmentMaker.update(dt) if not _G.state then return end; ParchmentMaker.dayTimer=ParchmentMaker.dayTimer+dt; if ParchmentMaker.dayTimer>=30 then ParchmentMaker.dayTimer=0; for i=#ParchmentMaker.activeMaking,1,-1 do local m=ParchmentMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ParchmentMaker.completeMaking(m); table.remove(ParchmentMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ParchmentMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ParchmentMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ParchmentMaker.getStats() return {hideStock=ParchmentMaker.hideStock,calfHideStock=ParchmentMaker.calfHideStock,limeStock=ParchmentMaker.limeStock,waterStock=ParchmentMaker.waterStock,silverStock=ParchmentMaker.silverStock,goldStock=ParchmentMaker.goldStock,jewelStock=ParchmentMaker.jewelStock,productStock=ParchmentMaker.productStock,numBuildings=#ParchmentMaker.buildings,hasMaker=ParchmentMaker.maker~=nil,makerName=ParchmentMaker.maker and ParchmentMaker.maker.name or "—",makerSkill=ParchmentMaker.maker and ParchmentMaker.maker.skill or 0,activeMaking=#ParchmentMaker.activeMaking,totalProducts=ParchmentMaker.totalProducts} end
return ParchmentMaker
