local SlackTubLidMaker = {}
local PRODUCTS = {
    iron_slacktublid = { name = "Železni pokrov za kalilno kad", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni pokrov za kalilno kad za kovace." },
    bronze_slacktublid = { name = "Bronast pokrov za kalilno kad", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast pokrov za kalilno kad za kovace." },
    silver_slacktublid = { name = "Srebrn pokrov za kalilno kad", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn pokrov za kalilno kad za kovace." },
    gilded_slacktublid = { name = "Pozlačen pokrov za kalilno kad", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen pokrov za kalilno kad za kovace." },
    jewel_set_slacktublid = { name = "Draguljast pokrov za kalilno kad", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast pokrov za kalilno kad za kovace." },
    royal_sovereign_slacktublid = { name = "Kraljevski suveren pokrov za kalilno kad", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren pokrov za kalilno kad z biseri za krono." },
}
local BUILDINGS = {
    slacktublid_workshop = { name = "Slacktublid delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    slacktublid_house = { name = "Slacktublid hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_slacktublid_atelier = { name = "Mojstrski slacktublid atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_slacktublid_palace = { name = "Suverena slacktublid palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SlackTubLidMaker.ironStock=14; SlackTubLidMaker.bronzeStock=12; SlackTubLidMaker.woodStock=14; SlackTubLidMaker.leatherStock=8; SlackTubLidMaker.silverStock=8; SlackTubLidMaker.goldStock=6; SlackTubLidMaker.jewelStock=4; SlackTubLidMaker.pearlStock=4
SlackTubLidMaker.productStock = {}; SlackTubLidMaker.buildings = {}; SlackTubLidMaker.maker = nil; SlackTubLidMaker.activeMaking = {}; SlackTubLidMaker.totalProducts = 0; SlackTubLidMaker.dayTimer = 0
function SlackTubLidMaker.init() SlackTubLidMaker.ironStock=14; SlackTubLidMaker.bronzeStock=12; SlackTubLidMaker.woodStock=14; SlackTubLidMaker.leatherStock=8; SlackTubLidMaker.silverStock=8; SlackTubLidMaker.goldStock=6; SlackTubLidMaker.jewelStock=4; SlackTubLidMaker.pearlStock=4; SlackTubLidMaker.productStock={}; SlackTubLidMaker.buildings={}; SlackTubLidMaker.maker=nil; SlackTubLidMaker.activeMaking={}; SlackTubLidMaker.totalProducts=0; SlackTubLidMaker.dayTimer=0; print("[SlackTubLidMaker] Royal Slack Tub Lid Maker System initialized (6 products, 4 buildings)") end
function SlackTubLidMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SlackTubLidMaker.maker={name=n or ("Pokrovnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pokrovnik najet: %s (spretnost: %d)",SlackTubLidMaker.maker.name,s),"success") end; return true end
function SlackTubLidMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SlackTubLidMaker.build(id) local ok,e=SlackTubLidMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SlackTubLidMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SlackTubLidMaker.getQualityBonus() local b=0; for _,bd in ipairs(SlackTubLidMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SlackTubLidMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SlackTubLidMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SlackTubLidMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SlackTubLidMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SlackTubLidMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SlackTubLidMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SlackTubLidMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SlackTubLidMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SlackTubLidMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SlackTubLidMaker.buildings==0 then return false,"Potrebna pokrovna delavnica" end; if not SlackTubLidMaker.maker then return false,"Potreben pokrovnik" end; return true end
function SlackTubLidMaker.make(pt,qty) qty=qty or 1; local ok,e=SlackTubLidMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SlackTubLidMaker.ironStock=SlackTubLidMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SlackTubLidMaker.bronzeStock=SlackTubLidMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SlackTubLidMaker.woodStock=SlackTubLidMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SlackTubLidMaker.leatherStock=SlackTubLidMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SlackTubLidMaker.silverStock=SlackTubLidMaker.silverStock-d.silverCost*qty end; if d.goldCost then SlackTubLidMaker.goldStock=SlackTubLidMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SlackTubLidMaker.jewelStock=SlackTubLidMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SlackTubLidMaker.pearlStock=SlackTubLidMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SlackTubLidMaker.maker then t=math.max(1,t-math.floor(SlackTubLidMaker.maker.skill/13)) end; table.insert(SlackTubLidMaker.activeMaking,{id="slacktublid_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SlackTubLidMaker.completeMaking(m) local q=1.0+(SlackTubLidMaker.getQualityBonus()/100); if SlackTubLidMaker.maker then q=q+(SlackTubLidMaker.maker.skill/140) end; q=math.min(2.5,q); SlackTubLidMaker.productStock[m.productType]=(SlackTubLidMaker.productStock[m.productType] or 0)+m.quantity; SlackTubLidMaker.totalProducts=SlackTubLidMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SlackTubLidMaker.maker then SlackTubLidMaker.maker.itemsMade=SlackTubLidMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SlackTubLidMaker.maker.skill=math.min(100,SlackTubLidMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pokrov izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"slacktublid.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SlackTubLidMaker.update(dt) if not _G.state then return end; SlackTubLidMaker.dayTimer=SlackTubLidMaker.dayTimer+dt; if SlackTubLidMaker.dayTimer>=30 then SlackTubLidMaker.dayTimer=0; for i=#SlackTubLidMaker.activeMaking,1,-1 do local m=SlackTubLidMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SlackTubLidMaker.completeMaking(m); table.remove(SlackTubLidMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SlackTubLidMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SlackTubLidMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SlackTubLidMaker.getStats() return {ironStock=SlackTubLidMaker.ironStock,bronzeStock=SlackTubLidMaker.bronzeStock,woodStock=SlackTubLidMaker.woodStock,leatherStock=SlackTubLidMaker.leatherStock,silverStock=SlackTubLidMaker.silverStock,goldStock=SlackTubLidMaker.goldStock,jewelStock=SlackTubLidMaker.jewelStock,pearlStock=SlackTubLidMaker.pearlStock,productStock=SlackTubLidMaker.productStock,numBuildings=#SlackTubLidMaker.buildings,hasMaker=SlackTubLidMaker.maker~=nil,makerName=SlackTubLidMaker.maker and SlackTubLidMaker.maker.name or "—",makerSkill=SlackTubLidMaker.maker and SlackTubLidMaker.maker.skill or 0,activeMaking=#SlackTubLidMaker.activeMaking,totalProducts=SlackTubLidMaker.totalProducts} end
return SlackTubLidMaker
