local JigsawPuzzleMaker = {}
local PRODUCTS = {
    wood_puzzle = { name = "Leseni sestavljenka", woodCost = 2, paintCost = 1, time = 2, cost = 20, artistry = 40, happiness = 2, description = "Leseni sestavljenka za otroke." },
    painted_puzzle = { name = "Poslikana sestavljenka", woodCost = 2, paintCost = 2, time = 4, cost = 50, artistry = 55, prestige = 2, happiness = 3, description = "Poslikana sestavljenka z motivi." },
    veneer_puzzle = { name = "Furnirna sestavljenka", woodCost = 3, veneerCost = 1, paintCost = 1, time = 6, cost = 120, artistry = 70, prestige = 5, happiness = 4, description = "Furnirna sestavljenka z lepimi vzorci." },
    silver_trim_puzzle = { name = "Srebrno obrobljena sestavljenka", woodCost = 3, silverCost = 1, veneerCost = 1, paintCost = 1, time = 9, cost = 280, artistry = 82, prestige = 10, happiness = 5, description = "Sestavljenka s srebrnim okovjem za plemiče." },
    gold_inlaid_puzzle = { name = "Zlatointarzirana sestavljenka", woodCost = 3, goldCost = 1, silverCost = 1, veneerCost = 1, jewelCost = 1, paintCost = 1, time = 12, cost = 600, artistry = 92, prestige = 18, happiness = 7, description = "Zlatointarzirana sestavljenka za visoke plemiče." },
    royal_grand_puzzle = { name = "Kraljevski veliki sestavljenka", woodCost = 5, goldCost = 2, silverCost = 1, jewelCost = 1, pearlCost = 1, veneerCost = 1, paintCost = 2, time = 17, cost = 1600, artistry = 100, prestige = 40, happiness = 12, description = "Velika kraljevska sestavljenka z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Sestavljenkarska delavnica", cost = { gold = 260, wood = 130, stone = 200 }, upkeep = 6, qualityBonus = 5 },
    cutting_room = { name = "Rezalnica", cost = { gold = 850, wood = 220, stone = 400, wood2 = 8 }, upkeep = 21, qualityBonus = 18 },
    painting_room = { name = "Slikalnica", cost = { gold = 2200, wood = 350, stone = 600, silver = 25, paint = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_puzzle_atelier = { name = "Kraljevski atelje sestavljenk", cost = { gold = 9000, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
JigsawPuzzleMaker.woodStock = 18; JigsawPuzzleMaker.veneerStock = 10; JigsawPuzzleMaker.paintStock = 12; JigsawPuzzleMaker.silverStock = 8; JigsawPuzzleMaker.goldStock = 6; JigsawPuzzleMaker.jewelStock = 6; JigsawPuzzleMaker.pearlStock = 4
JigsawPuzzleMaker.productStock = {}; JigsawPuzzleMaker.buildings = {}; JigsawPuzzleMaker.maker = nil; JigsawPuzzleMaker.activeMaking = {}; JigsawPuzzleMaker.totalProducts = 0; JigsawPuzzleMaker.dayTimer = 0
function JigsawPuzzleMaker.init() JigsawPuzzleMaker.woodStock=18; JigsawPuzzleMaker.veneerStock=10; JigsawPuzzleMaker.paintStock=12; JigsawPuzzleMaker.silverStock=8; JigsawPuzzleMaker.goldStock=6; JigsawPuzzleMaker.jewelStock=6; JigsawPuzzleMaker.pearlStock=4; JigsawPuzzleMaker.productStock={}; JigsawPuzzleMaker.buildings={}; JigsawPuzzleMaker.maker=nil; JigsawPuzzleMaker.activeMaking={}; JigsawPuzzleMaker.totalProducts=0; JigsawPuzzleMaker.dayTimer=0; print("[JigsawPuzzleMaker] Royal Jigsaw Puzzle Maker System initialized (6 products, 4 buildings)") end
function JigsawPuzzleMaker.hireMaker(n,s) s=s or math.random(50,90); local c=500+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; JigsawPuzzleMaker.maker={name=n or ("Sestavljenkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sestavljenkar najet: %s (spretnost: %d)",JigsawPuzzleMaker.maker.name,s),"success") end; return true end
function JigsawPuzzleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function JigsawPuzzleMaker.build(id) local ok,e=JigsawPuzzleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(JigsawPuzzleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function JigsawPuzzleMaker.getQualityBonus() local b=0; for _,bd in ipairs(JigsawPuzzleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function JigsawPuzzleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and JigsawPuzzleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.veneerCost and JigsawPuzzleMaker.veneerStock<(d.veneerCost or 0) then return false,"Premalo furnirja" end; if d.paintCost and JigsawPuzzleMaker.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.silverCost and JigsawPuzzleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and JigsawPuzzleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and JigsawPuzzleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and JigsawPuzzleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #JigsawPuzzleMaker.buildings==0 then return false,"Potrebna delavnica" end; if not JigsawPuzzleMaker.maker then return false,"Potreben sestavljenkar" end; return true end
function JigsawPuzzleMaker.make(pt,qty) qty=qty or 1; local ok,e=JigsawPuzzleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then JigsawPuzzleMaker.woodStock=JigsawPuzzleMaker.woodStock-d.woodCost*qty end; if d.veneerCost then JigsawPuzzleMaker.veneerStock=JigsawPuzzleMaker.veneerStock-d.veneerCost*qty end; if d.paintCost then JigsawPuzzleMaker.paintStock=JigsawPuzzleMaker.paintStock-d.paintCost*qty end; if d.silverCost then JigsawPuzzleMaker.silverStock=JigsawPuzzleMaker.silverStock-d.silverCost*qty end; if d.goldCost then JigsawPuzzleMaker.goldStock=JigsawPuzzleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then JigsawPuzzleMaker.jewelStock=JigsawPuzzleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then JigsawPuzzleMaker.pearlStock=JigsawPuzzleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if JigsawPuzzleMaker.maker then t=math.max(1,t-math.floor(JigsawPuzzleMaker.maker.skill/12)) end; table.insert(JigsawPuzzleMaker.activeMaking,{id="puzzle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,artistry=d.artistry or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function JigsawPuzzleMaker.completeMaking(m) local q=1.0+(JigsawPuzzleMaker.getQualityBonus()/100); if JigsawPuzzleMaker.maker then q=q+(JigsawPuzzleMaker.maker.skill/180) end; q=math.min(2.0,q); JigsawPuzzleMaker.productStock[m.productType]=(JigsawPuzzleMaker.productStock[m.productType] or 0)+m.quantity; JigsawPuzzleMaker.totalProducts=JigsawPuzzleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if JigsawPuzzleMaker.maker then JigsawPuzzleMaker.maker.itemsMade=JigsawPuzzleMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then JigsawPuzzleMaker.maker.skill=math.min(100,JigsawPuzzleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sestavljenka izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"puzzle.completed",{productName=m.productName,artistry=m.artistry,prestige=m.prestige,happiness=m.happiness}) end end
function JigsawPuzzleMaker.update(dt) if not _G.state then return end; JigsawPuzzleMaker.dayTimer=JigsawPuzzleMaker.dayTimer+dt; if JigsawPuzzleMaker.dayTimer>=30 then JigsawPuzzleMaker.dayTimer=0; for i=#JigsawPuzzleMaker.activeMaking,1,-1 do local m=JigsawPuzzleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then JigsawPuzzleMaker.completeMaking(m); table.remove(JigsawPuzzleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(JigsawPuzzleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if JigsawPuzzleMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function JigsawPuzzleMaker.getStats() return {woodStock=JigsawPuzzleMaker.woodStock,veneerStock=JigsawPuzzleMaker.veneerStock,paintStock=JigsawPuzzleMaker.paintStock,silverStock=JigsawPuzzleMaker.silverStock,goldStock=JigsawPuzzleMaker.goldStock,jewelStock=JigsawPuzzleMaker.jewelStock,pearlStock=JigsawPuzzleMaker.pearlStock,productStock=JigsawPuzzleMaker.productStock,numBuildings=#JigsawPuzzleMaker.buildings,hasMaker=JigsawPuzzleMaker.maker~=nil,makerName=JigsawPuzzleMaker.maker and JigsawPuzzleMaker.maker.name or "—",makerSkill=JigsawPuzzleMaker.maker and JigsawPuzzleMaker.maker.skill or 0,activeMaking=#JigsawPuzzleMaker.activeMaking,totalProducts=JigsawPuzzleMaker.totalProducts} end
return JigsawPuzzleMaker
