local SaltPanWorker = {}
local PRODUCTS = {
    bay_salt = { name = "Solinska sol", seawaterCost = 2, fuelCost = 1, time = 3, cost = 14, purity = 50, description = "Solinska sol iz izhlapene morske vode." },
    flake_salt = { name = "Pahuljasta sol", seawaterCost = 3, fuelCost = 1, time = 5, cost = 38, purity = 70, prestige = 1, description = "Pahuljasta sol z nežnim okusom." },
    fleur_de_sel = { name = "Solni cvet", seawaterCost = 3, silverCost = 1, fuelCost = 1, time = 7, cost = 90, purity = 85, prestige = 4, happiness = 1, description = "Solni cvet za fine jedi." },
    silver_crystal_salt = { name = "Srebrno kristalna sol", seawaterCost = 4, silverCost = 1, fuelCost = 1, time = 10, cost = 220, purity = 92, prestige = 9, happiness = 2, description = "Srebrno kristalna sol za plemiče." },
    silver_pan_salt = { name = "Srebrno solinska sol", seawaterCost = 4, silverCost = 1, fuelCost = 1, time = 13, cost = 480, purity = 96, prestige = 15, happiness = 3, description = "Sol iz srebrnih solin za visoke plemiče." },
    royal_grand_salt = { name = "Kraljevski veliki sol", seawaterCost = 6, goldCost = 1, silverCost = 1, jewelCost = 1, fuelCost = 2, time = 18, cost = 1500, purity = 100, prestige = 35, happiness = 8, description = "Velika kraljevska sol z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Solinarska postaja", cost = { gold = 250, wood = 120, stone = 250 }, upkeep = 6, qualityBonus = 5 },
    salt_pan = { name = "Solina", cost = { gold = 900, wood = 250, stone = 500, seawater = 10 }, upkeep = 22, qualityBonus = 18 },
    crystallization_yard = { name = "Kristalizacijsko dvorišče", cost = { gold = 2300, wood = 350, stone = 700, silver = 30, fuel = 8 }, upkeep = 58, qualityBonus = 30 },
    royal_salt_pan_atelier = { name = "Kraljevski atelje solin", cost = { gold = 9200, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 185, qualityBonus = 55, prestigeBonus = 40 },
}
SaltPanWorker.seawaterStock = 24; SaltPanWorker.fuelStock = 18; SaltPanWorker.silverStock = 8; SaltPanWorker.goldStock = 6; SaltPanWorker.jewelStock = 6
SaltPanWorker.productStock = {}; SaltPanWorker.buildings = {}; SaltPanWorker.maker = nil; SaltPanWorker.activeMaking = {}; SaltPanWorker.totalProducts = 0; SaltPanWorker.dayTimer = 0
function SaltPanWorker.init() SaltPanWorker.seawaterStock=24; SaltPanWorker.fuelStock=18; SaltPanWorker.silverStock=8; SaltPanWorker.goldStock=6; SaltPanWorker.jewelStock=6; SaltPanWorker.productStock={}; SaltPanWorker.buildings={}; SaltPanWorker.maker=nil; SaltPanWorker.activeMaking={}; SaltPanWorker.totalProducts=0; SaltPanWorker.dayTimer=0; print("[SaltPanWorker] Royal Salt Pan Worker System initialized (6 products, 4 buildings)") end
function SaltPanWorker.hireMaker(n,s) s=s or math.random(45,85); local c=500+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SaltPanWorker.maker={name=n or ("Solinar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Solinar najet: %s (spretnost: %d)",SaltPanWorker.maker.name,s),"success") end; return true end
function SaltPanWorker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SaltPanWorker.build(id) local ok,e=SaltPanWorker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SaltPanWorker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SaltPanWorker.getQualityBonus() local b=0; for _,bd in ipairs(SaltPanWorker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SaltPanWorker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.seawaterCost and SaltPanWorker.seawaterStock<(d.seawaterCost or 0) then return false,"Premalo morske vode" end; if d.fuelCost and SaltPanWorker.fuelStock<(d.fuelCost or 0) then return false,"Premalo goriva" end; if d.silverCost and SaltPanWorker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SaltPanWorker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SaltPanWorker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #SaltPanWorker.buildings==0 then return false,"Potrebna delavnica" end; if not SaltPanWorker.maker then return false,"Potreben solinar" end; return true end
function SaltPanWorker.make(pt,qty) qty=qty or 10; local ok,e=SaltPanWorker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.seawaterCost then SaltPanWorker.seawaterStock=SaltPanWorker.seawaterStock-d.seawaterCost*qty end; if d.fuelCost then SaltPanWorker.fuelStock=SaltPanWorker.fuelStock-d.fuelCost*qty end; if d.silverCost then SaltPanWorker.silverStock=SaltPanWorker.silverStock-d.silverCost*qty end; if d.goldCost then SaltPanWorker.goldStock=SaltPanWorker.goldStock-d.goldCost*qty end; if d.jewelCost then SaltPanWorker.jewelStock=SaltPanWorker.jewelStock-d.jewelCost*qty end; local t=d.time; if SaltPanWorker.maker then t=math.max(1,t-math.floor(SaltPanWorker.maker.skill/12)) end; table.insert(SaltPanWorker.activeMaking,{id="saltpan_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,purity=d.purity or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SaltPanWorker.completeMaking(m) local q=1.0+(SaltPanWorker.getQualityBonus()/100); if SaltPanWorker.maker then q=q+(SaltPanWorker.maker.skill/180) end; q=math.min(2.0,q); SaltPanWorker.productStock[m.productType]=(SaltPanWorker.productStock[m.productType] or 0)+m.quantity; SaltPanWorker.totalProducts=SaltPanWorker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SaltPanWorker.maker then SaltPanWorker.maker.itemsMade=SaltPanWorker.maker.itemsMade+m.quantity; if math.random()<0.20 then SaltPanWorker.maker.skill=math.min(100,SaltPanWorker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sol pridelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"saltpan.completed",{productName=m.productName,purity=m.purity}) end end
function SaltPanWorker.update(dt) if not _G.state then return end; SaltPanWorker.dayTimer=SaltPanWorker.dayTimer+dt; if SaltPanWorker.dayTimer>=30 then SaltPanWorker.dayTimer=0; for i=#SaltPanWorker.activeMaking,1,-1 do local m=SaltPanWorker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SaltPanWorker.completeMaking(m); table.remove(SaltPanWorker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SaltPanWorker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SaltPanWorker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SaltPanWorker.getStats() return {seawaterStock=SaltPanWorker.seawaterStock,fuelStock=SaltPanWorker.fuelStock,silverStock=SaltPanWorker.silverStock,goldStock=SaltPanWorker.goldStock,jewelStock=SaltPanWorker.jewelStock,productStock=SaltPanWorker.productStock,numBuildings=#SaltPanWorker.buildings,hasMaker=SaltPanWorker.maker~=nil,makerName=SaltPanWorker.maker and SaltPanWorker.maker.name or "—",makerSkill=SaltPanWorker.maker and SaltPanWorker.maker.skill or 0,activeMaking=#SaltPanWorker.activeMaking,totalProducts=SaltPanWorker.totalProducts} end
return SaltPanWorker
