local AstrolabeRingMaker = {}
local PRODUCTS = {
    iron_astrolabering = { name = "Železni astrolabni obroč", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni astrolabni obroč za astrolabe." },
    bronze_astrolabering = { name = "Bronast astrolabni obroč", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast astrolabni obroč za astrolabe." },
    silver_astrolabering = { name = "Srebrn astrolabni obroč", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn astrolabni obroč za astrolabe." },
    gilded_astrolabering = { name = "Pozlačen astrolabni obroč", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen astrolabni obroč za astrolabe." },
    jewel_set_astrolabering = { name = "Draguljast astrolabni obroč", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast astrolabni obroč za astrolabe." },
    royal_sovereign_astrolabering = { name = "Kraljevski suveren astrolabni obroč", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren astrolabni obroč z biseri za krono." },
}
local BUILDINGS = {
    astrolabering_workshop = { name = "Astrolabering delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    astrolabering_house = { name = "Astrolabering hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_astrolabering_atelier = { name = "Mojstrski astrolabering atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_astrolabering_palace = { name = "Suverena astrolabering palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
AstrolabeRingMaker.ironStock = 14; AstrolabeRingMaker.bronzeStock = 12; AstrolabeRingMaker.woodStock = 14; AstrolabeRingMaker.leatherStock = 8; AstrolabeRingMaker.silverStock = 10; AstrolabeRingMaker.goldStock = 6; AstrolabeRingMaker.jewelStock = 4; AstrolabeRingMaker.pearlStock = 4
AstrolabeRingMaker.productStock = {}; AstrolabeRingMaker.buildings = {}; AstrolabeRingMaker.maker = nil; AstrolabeRingMaker.activeMaking = {}; AstrolabeRingMaker.totalProducts = 0; AstrolabeRingMaker.dayTimer = 0
function AstrolabeRingMaker.init() AstrolabeRingMaker.ironStock=14; AstrolabeRingMaker.bronzeStock=12; AstrolabeRingMaker.woodStock=14; AstrolabeRingMaker.leatherStock=8; AstrolabeRingMaker.silverStock=10; AstrolabeRingMaker.goldStock=6; AstrolabeRingMaker.jewelStock=4; AstrolabeRingMaker.pearlStock=4; AstrolabeRingMaker.productStock={}; AstrolabeRingMaker.buildings={}; AstrolabeRingMaker.maker=nil; AstrolabeRingMaker.activeMaking={}; AstrolabeRingMaker.totalProducts=0; AstrolabeRingMaker.dayTimer=0; print("[AstrolabeRingMaker] Royal Astrolabe Ring Maker System initialized (6 products, 4 buildings)") end
function AstrolabeRingMaker.hireMaker(n,s) s=s or math.random(55,90); local c=595+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; AstrolabeRingMaker.maker={name=n or ("Krožar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Krožar najet: %s (spretnost: %d)",AstrolabeRingMaker.maker.name,s),"success") end; return true end
function AstrolabeRingMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function AstrolabeRingMaker.build(id) local ok,e=AstrolabeRingMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(AstrolabeRingMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function AstrolabeRingMaker.getQualityBonus() local b=0; for _,bd in ipairs(AstrolabeRingMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function AstrolabeRingMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and AstrolabeRingMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and AstrolabeRingMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and AstrolabeRingMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and AstrolabeRingMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and AstrolabeRingMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and AstrolabeRingMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and AstrolabeRingMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and AstrolabeRingMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #AstrolabeRingMaker.buildings==0 then return false,"Potrebna krožna delavnica" end; if not AstrolabeRingMaker.maker then return false,"Potreben krozar" end; return true end
function AstrolabeRingMaker.make(pt,qty) qty=qty or 1; local ok,e=AstrolabeRingMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then AstrolabeRingMaker.ironStock=AstrolabeRingMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then AstrolabeRingMaker.bronzeStock=AstrolabeRingMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then AstrolabeRingMaker.woodStock=AstrolabeRingMaker.woodStock-d.woodCost*qty end; if d.leatherCost then AstrolabeRingMaker.leatherStock=AstrolabeRingMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then AstrolabeRingMaker.silverStock=AstrolabeRingMaker.silverStock-d.silverCost*qty end; if d.goldCost then AstrolabeRingMaker.goldStock=AstrolabeRingMaker.goldStock-d.goldCost*qty end; if d.jewelCost then AstrolabeRingMaker.jewelStock=AstrolabeRingMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then AstrolabeRingMaker.pearlStock=AstrolabeRingMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if AstrolabeRingMaker.maker then t=math.max(1,t-math.floor(AstrolabeRingMaker.maker.skill/13)) end; table.insert(AstrolabeRingMaker.activeMaking,{id="astrolabering_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function AstrolabeRingMaker.completeMaking(m) local q=1.0+(AstrolabeRingMaker.getQualityBonus()/100); if AstrolabeRingMaker.maker then q=q+(AstrolabeRingMaker.maker.skill/140) end; q=math.min(2.5,q); AstrolabeRingMaker.productStock[m.productType]=(AstrolabeRingMaker.productStock[m.productType] or 0)+m.quantity; AstrolabeRingMaker.totalProducts=AstrolabeRingMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if AstrolabeRingMaker.maker then AstrolabeRingMaker.maker.itemsMade=AstrolabeRingMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then AstrolabeRingMaker.maker.skill=math.min(100,AstrolabeRingMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Obroč izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"astrolabering.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function AstrolabeRingMaker.update(dt) if not _G.state then return end; AstrolabeRingMaker.dayTimer=AstrolabeRingMaker.dayTimer+dt; if AstrolabeRingMaker.dayTimer>=30 then AstrolabeRingMaker.dayTimer=0; for i=#AstrolabeRingMaker.activeMaking,1,-1 do local m=AstrolabeRingMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then AstrolabeRingMaker.completeMaking(m); table.remove(AstrolabeRingMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(AstrolabeRingMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if AstrolabeRingMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function AstrolabeRingMaker.getStats() return {ironStock=AstrolabeRingMaker.ironStock,bronzeStock=AstrolabeRingMaker.bronzeStock,woodStock=AstrolabeRingMaker.woodStock,leatherStock=AstrolabeRingMaker.leatherStock,silverStock=AstrolabeRingMaker.silverStock,goldStock=AstrolabeRingMaker.goldStock,jewelStock=AstrolabeRingMaker.jewelStock,pearlStock=AstrolabeRingMaker.pearlStock,productStock=AstrolabeRingMaker.productStock,numBuildings=#AstrolabeRingMaker.buildings,hasMaker=AstrolabeRingMaker.maker~=nil,makerName=AstrolabeRingMaker.maker and AstrolabeRingMaker.maker.name or "—",makerSkill=AstrolabeRingMaker.maker and AstrolabeRingMaker.maker.skill or 0,activeMaking=#AstrolabeRingMaker.activeMaking,totalProducts=AstrolabeRingMaker.totalProducts} end
return AstrolabeRingMaker
