local MeadMaker = {}
local PRODUCTS = {
    simple_mead = { name = "Preprost medica", honeyCost = 2, waterCost = 1, time = 2, cost = 18, alcoholContent = 5, happiness = 2, description = "Preprost medica za kmete." },
    spiced_mead = { name = "Začinjen medica", honeyCost = 3, waterCost = 1, spiceCost = 1, time = 4, cost = 50, alcoholContent = 8, happiness = 3, prestige = 1, description = "Začinjen medica za slovesnosti." },
    melomel = { name = "Melomel", honeyCost = 3, fruitCost = 2, waterCost = 1, time = 6, cost = 130, alcoholContent = 11, happiness = 4, prestige = 3, description = "Medica z dodatkom sadja." },
    metheglin = { name = "Meteglin", honeyCost = 4, spiceCost = 2, waterCost = 2, time = 8, cost = 280, alcoholContent = 13, happiness = 6, prestige = 6, description = "Meteglin z redkimi začimbami." },
    silver_cask_mead = { name = "Srebrno sodni medica", honeyCost = 5, silverCost = 1, spiceCost = 2, waterCost = 2, time = 11, cost = 580, alcoholContent = 15, happiness = 9, prestige = 12, description = "Medica staran v srebrnem sodu." },
    royal_grand_mead = { name = "Kraljevski veliki medica", honeyCost = 8, goldCost = 1, silverCost = 1, jewelCost = 1, spiceCost = 2, fruitCost = 3, waterCost = 4, time = 16, cost = 1400, alcoholContent = 20, happiness = 18, prestige = 38, description = "Veliki kraljevski medica z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Medičarska delavnica", cost = { gold = 290, wood = 150 }, upkeep = 7, qualityBonus = 5 },
    meadery = { name = "Medičarna", cost = { gold = 950, wood = 280, stone = 350, honey = 10 }, upkeep = 23, qualityBonus = 18 },
    aging_cellar = { name = "Starilni sklep", cost = { gold = 2300, wood = 400, stone = 700, silver = 30, spice = 8 }, upkeep = 58, qualityBonus = 30 },
    royal_mead_atelier = { name = "Kraljevski atelje medice", cost = { gold = 9500, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 40 },
}
MeadMaker.honeyStock = 22; MeadMaker.waterStock = 18; MeadMaker.spiceStock = 12; MeadMaker.fruitStock = 14; MeadMaker.silverStock = 8; MeadMaker.goldStock = 6; MeadMaker.jewelStock = 6
MeadMaker.productStock = {}; MeadMaker.buildings = {}; MeadMaker.maker = nil; MeadMaker.activeMaking = {}; MeadMaker.totalProducts = 0; MeadMaker.dayTimer = 0
function MeadMaker.init() MeadMaker.honeyStock=22; MeadMaker.waterStock=18; MeadMaker.spiceStock=12; MeadMaker.fruitStock=14; MeadMaker.silverStock=8; MeadMaker.goldStock=6; MeadMaker.jewelStock=6; MeadMaker.productStock={}; MeadMaker.buildings={}; MeadMaker.maker=nil; MeadMaker.activeMaking={}; MeadMaker.totalProducts=0; MeadMaker.dayTimer=0; print("[MeadMaker] Royal Mead Maker System initialized (6 products, 4 buildings)") end
function MeadMaker.hireMaker(n,s) s=s or math.random(50,90); local c=510+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MeadMaker.maker={name=n or ("Medičar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Medičar najet: %s (spretnost: %d)",MeadMaker.maker.name,s),"success") end; return true end
function MeadMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MeadMaker.build(id) local ok,e=MeadMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MeadMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MeadMaker.getQualityBonus() local b=0; for _,bd in ipairs(MeadMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MeadMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.honeyCost and MeadMaker.honeyStock<(d.honeyCost or 0) then return false,"Premalo medu" end; if d.waterCost and MeadMaker.waterStock<(d.waterCost or 0) then return false,"Premalo vode" end; if d.spiceCost and MeadMaker.spiceStock<(d.spiceCost or 0) then return false,"Premalo začimb" end; if d.fruitCost and MeadMaker.fruitStock<(d.fruitCost or 0) then return false,"Premalo sadja" end; if d.silverCost and MeadMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MeadMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MeadMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #MeadMaker.buildings==0 then return false,"Potrebna delavnica" end; if not MeadMaker.maker then return false,"Potreben medičar" end; return true end
function MeadMaker.make(pt,qty) qty=qty or 5; local ok,e=MeadMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.honeyCost then MeadMaker.honeyStock=MeadMaker.honeyStock-d.honeyCost*qty end; if d.waterCost then MeadMaker.waterStock=MeadMaker.waterStock-d.waterCost*qty end; if d.spiceCost then MeadMaker.spiceStock=MeadMaker.spiceStock-d.spiceCost*qty end; if d.fruitCost then MeadMaker.fruitStock=MeadMaker.fruitStock-d.fruitCost*qty end; if d.silverCost then MeadMaker.silverStock=MeadMaker.silverStock-d.silverCost*qty end; if d.goldCost then MeadMaker.goldStock=MeadMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MeadMaker.jewelStock=MeadMaker.jewelStock-d.jewelCost*qty end; local t=d.time; if MeadMaker.maker then t=math.max(1,t-math.floor(MeadMaker.maker.skill/12)) end; table.insert(MeadMaker.activeMaking,{id="mead_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,alcoholContent=d.alcoholContent or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MeadMaker.completeMaking(m) local q=1.0+(MeadMaker.getQualityBonus()/100); if MeadMaker.maker then q=q+(MeadMaker.maker.skill/180) end; q=math.min(2.0,q); MeadMaker.productStock[m.productType]=(MeadMaker.productStock[m.productType] or 0)+m.quantity; MeadMaker.totalProducts=MeadMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MeadMaker.maker then MeadMaker.maker.itemsMade=MeadMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then MeadMaker.maker.skill=math.min(100,MeadMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Medica izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"mead.completed",{productName=m.productName,alcoholContent=m.alcoholContent,happiness=m.happiness}) end end
function MeadMaker.update(dt) if not _G.state then return end; MeadMaker.dayTimer=MeadMaker.dayTimer+dt; if MeadMaker.dayTimer>=30 then MeadMaker.dayTimer=0; for i=#MeadMaker.activeMaking,1,-1 do local m=MeadMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MeadMaker.completeMaking(m); table.remove(MeadMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MeadMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MeadMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MeadMaker.getStats() return {honeyStock=MeadMaker.honeyStock,waterStock=MeadMaker.waterStock,spiceStock=MeadMaker.spiceStock,fruitStock=MeadMaker.fruitStock,silverStock=MeadMaker.silverStock,goldStock=MeadMaker.goldStock,jewelStock=MeadMaker.jewelStock,productStock=MeadMaker.productStock,numBuildings=#MeadMaker.buildings,hasMaker=MeadMaker.maker~=nil,makerName=MeadMaker.maker and MeadMaker.maker.name or "—",makerSkill=MeadMaker.maker and MeadMaker.maker.skill or 0,activeMaking=#MeadMaker.activeMaking,totalProducts=MeadMaker.totalProducts} end
return MeadMaker
