local SmokedMeatCurer = {}
local PRODUCTS = {
    smoked_pork_belly = { name = "Prekajena svinjska prsa", porkCost = 3, saltCost = 1, fuelCost = 1, time = 4, cost = 40, flavorStrength = 40, happiness = 2, description = "Prekajena svinjska prsa za slane jedi." },
    smoked_ham = { name = "Prekajena šunka", porkCost = 4, saltCost = 1, spiceCost = 1, fuelCost = 1, time = 6, cost = 100, flavorStrength = 55, happiness = 3, prestige = 2, description = "Prekajena šunka za slovesne večerje." },
    smoked_bacon = { name = "Prekajen slanina", porkCost = 4, saltCost = 1, spiceCost = 1, fuelCost = 1, time = 7, cost = 180, flavorStrength = 65, happiness = 4, prestige = 3, description = "Prekajena slanina z bogatim okusom." },
    smoked_beef_brisket = { name = "Prekajena goveja prsa", beefCost = 5, saltCost = 1, spiceCost = 1, fuelCost = 2, time = 10, cost = 380, flavorStrength = 80, happiness = 5, prestige = 7, description = "Prekajena goveja prsa za plemiče." },
    silver_net_smoked_meat = { name = "Srebrno mrežasto prekajeno meso", beefCost = 5, porkCost = 2, silverCost = 1, saltCost = 1, spiceCost = 2, fuelCost = 2, time = 13, cost = 750, flavorStrength = 92, happiness = 7, prestige = 14, description = "Prekajeno meso v srebrni mreži za visoke plemiče." },
    royal_grand_smoked_meat = { name = "Kraljevski veliki prekajeno meso", beefCost = 8, porkCost = 4, goldCost = 1, silverCost = 1, jewelCost = 1, saltCost = 2, spiceCost = 3, fuelCost = 3, time = 18, cost = 2000, flavorStrength = 100, happiness = 15, prestige = 38, description = "Veliko kraljevsko prekajeno meso z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Prekajevalna delavnica", cost = { gold = 320, wood = 140, stone = 250 }, upkeep = 8, qualityBonus = 5 },
    smokehouse = { name = "Kadilnica", cost = { gold = 1000, wood = 280, stone = 450, fuel = 10 }, upkeep = 25, qualityBonus = 18 },
    curing_cellar = { name = "Konservirni sklep", cost = { gold = 2400, wood = 350, stone = 700, silver = 30, salt = 10 }, upkeep = 60, qualityBonus = 30 },
    royal_smoked_meat_atelier = { name = "Kraljevski atelje prekajenega mesa", cost = { gold = 9500, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 40 },
}
SmokedMeatCurer.porkStock = 22; SmokedMeatCurer.beefStock = 16; SmokedMeatCurer.saltStock = 14; SmokedMeatCurer.spiceStock = 12; SmokedMeatCurer.fuelStock = 16; SmokedMeatCurer.silverStock = 8; SmokedMeatCurer.goldStock = 6; SmokedMeatCurer.jewelStock = 6
SmokedMeatCurer.productStock = {}; SmokedMeatCurer.buildings = {}; SmokedMeatCurer.maker = nil; SmokedMeatCurer.activeMaking = {}; SmokedMeatCurer.totalProducts = 0; SmokedMeatCurer.dayTimer = 0
function SmokedMeatCurer.init() SmokedMeatCurer.porkStock=22; SmokedMeatCurer.beefStock=16; SmokedMeatCurer.saltStock=14; SmokedMeatCurer.spiceStock=12; SmokedMeatCurer.fuelStock=16; SmokedMeatCurer.silverStock=8; SmokedMeatCurer.goldStock=6; SmokedMeatCurer.jewelStock=6; SmokedMeatCurer.productStock={}; SmokedMeatCurer.buildings={}; SmokedMeatCurer.maker=nil; SmokedMeatCurer.activeMaking={}; SmokedMeatCurer.totalProducts=0; SmokedMeatCurer.dayTimer=0; print("[SmokedMeatCurer] Royal Smoked Meat Curer System initialized (6 products, 4 buildings)") end
function SmokedMeatCurer.hireMaker(n,s) s=s or math.random(50,90); local c=540+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SmokedMeatCurer.maker={name=n or ("Prekajevar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Prekajevar najet: %s (spretnost: %d)",SmokedMeatCurer.maker.name,s),"success") end; return true end
function SmokedMeatCurer.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SmokedMeatCurer.build(id) local ok,e=SmokedMeatCurer.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SmokedMeatCurer.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SmokedMeatCurer.getQualityBonus() local b=0; for _,bd in ipairs(SmokedMeatCurer.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SmokedMeatCurer.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.porkCost and SmokedMeatCurer.porkStock<(d.porkCost or 0) then return false,"Premalo svinjine" end; if d.beefCost and SmokedMeatCurer.beefStock<(d.beefCost or 0) then return false,"Premalo govedine" end; if d.saltCost and SmokedMeatCurer.saltStock<(d.saltCost or 0) then return false,"Premalo soli" end; if d.spiceCost and SmokedMeatCurer.spiceStock<(d.spiceCost or 0) then return false,"Premalo začimb" end; if d.fuelCost and SmokedMeatCurer.fuelStock<(d.fuelCost or 0) then return false,"Premalo goriva" end; if d.silverCost and SmokedMeatCurer.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SmokedMeatCurer.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SmokedMeatCurer.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #SmokedMeatCurer.buildings==0 then return false,"Potrebna delavnica" end; if not SmokedMeatCurer.maker then return false,"Potreben prekajevar" end; return true end
function SmokedMeatCurer.make(pt,qty) qty=qty or 5; local ok,e=SmokedMeatCurer.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.porkCost then SmokedMeatCurer.porkStock=SmokedMeatCurer.porkStock-d.porkCost*qty end; if d.beefCost then SmokedMeatCurer.beefStock=SmokedMeatCurer.beefStock-d.beefCost*qty end; if d.saltCost then SmokedMeatCurer.saltStock=SmokedMeatCurer.saltStock-d.saltCost*qty end; if d.spiceCost then SmokedMeatCurer.spiceStock=SmokedMeatCurer.spiceStock-d.spiceCost*qty end; if d.fuelCost then SmokedMeatCurer.fuelStock=SmokedMeatCurer.fuelStock-d.fuelCost*qty end; if d.silverCost then SmokedMeatCurer.silverStock=SmokedMeatCurer.silverStock-d.silverCost*qty end; if d.goldCost then SmokedMeatCurer.goldStock=SmokedMeatCurer.goldStock-d.goldCost*qty end; if d.jewelCost then SmokedMeatCurer.jewelStock=SmokedMeatCurer.jewelStock-d.jewelCost*qty end; local t=d.time; if SmokedMeatCurer.maker then t=math.max(1,t-math.floor(SmokedMeatCurer.maker.skill/12)) end; table.insert(SmokedMeatCurer.activeMaking,{id="smokedmeat_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,flavorStrength=d.flavorStrength or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SmokedMeatCurer.completeMaking(m) local q=1.0+(SmokedMeatCurer.getQualityBonus()/100); if SmokedMeatCurer.maker then q=q+(SmokedMeatCurer.maker.skill/180) end; q=math.min(2.0,q); SmokedMeatCurer.productStock[m.productType]=(SmokedMeatCurer.productStock[m.productType] or 0)+m.quantity; SmokedMeatCurer.totalProducts=SmokedMeatCurer.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SmokedMeatCurer.maker then SmokedMeatCurer.maker.itemsMade=SmokedMeatCurer.maker.itemsMade+m.quantity; if math.random()<0.20 then SmokedMeatCurer.maker.skill=math.min(100,SmokedMeatCurer.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Prekajeno meso izdelano: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"smokedmeat.completed",{productName=m.productName,flavorStrength=m.flavorStrength,happiness=m.happiness}) end end
function SmokedMeatCurer.update(dt) if not _G.state then return end; SmokedMeatCurer.dayTimer=SmokedMeatCurer.dayTimer+dt; if SmokedMeatCurer.dayTimer>=30 then SmokedMeatCurer.dayTimer=0; for i=#SmokedMeatCurer.activeMaking,1,-1 do local m=SmokedMeatCurer.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SmokedMeatCurer.completeMaking(m); table.remove(SmokedMeatCurer.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SmokedMeatCurer.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SmokedMeatCurer.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SmokedMeatCurer.getStats() return {porkStock=SmokedMeatCurer.porkStock,beefStock=SmokedMeatCurer.beefStock,saltStock=SmokedMeatCurer.saltStock,spiceStock=SmokedMeatCurer.spiceStock,fuelStock=SmokedMeatCurer.fuelStock,silverStock=SmokedMeatCurer.silverStock,goldStock=SmokedMeatCurer.goldStock,jewelStock=SmokedMeatCurer.jewelStock,productStock=SmokedMeatCurer.productStock,numBuildings=#SmokedMeatCurer.buildings,hasMaker=SmokedMeatCurer.maker~=nil,makerName=SmokedMeatCurer.maker and SmokedMeatCurer.maker.name or "—",makerSkill=SmokedMeatCurer.maker and SmokedMeatCurer.maker.skill or 0,activeMaking=#SmokedMeatCurer.activeMaking,totalProducts=SmokedMeatCurer.totalProducts} end
return SmokedMeatCurer
