local HatLiningMaker = {}
local PRODUCTS = {
    iron_hatlining = { name = "Železni podstav za klobuke", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni podstav za klobuke za klobucarje." },
    bronze_hatlining = { name = "Bronast podstav za klobuke", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast podstav za klobuke za klobucarje." },
    silver_hatlining = { name = "Srebrn podstav za klobuke", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn podstav za klobuke za klobucarje." },
    gilded_hatlining = { name = "Pozlačen podstav za klobuke", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen podstav za klobuke za klobucarje." },
    jewel_set_hatlining = { name = "Draguljast podstav za klobuke", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast podstav za klobuke za klobucarje." },
    royal_sovereign_hatlining = { name = "Kraljevski suveren podstav za klobuke", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren podstav za klobuke z biseri za krono." },
}
local BUILDINGS = {
    hatlining_workshop = { name = "Hatlining delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    hatlining_house = { name = "Hatlining hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_hatlining_atelier = { name = "Mojstrski hatlining atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_hatlining_palace = { name = "Suverena hatlining palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
HatLiningMaker.ironStock = 10; HatLiningMaker.bronzeStock = 8; HatLiningMaker.woodStock = 14; HatLiningMaker.leatherStock = 16; HatLiningMaker.silverStock = 8; HatLiningMaker.goldStock = 6; HatLiningMaker.jewelStock = 4; HatLiningMaker.pearlStock = 4
HatLiningMaker.productStock = {}; HatLiningMaker.buildings = {}; HatLiningMaker.maker = nil; HatLiningMaker.activeMaking = {}; HatLiningMaker.totalProducts = 0; HatLiningMaker.dayTimer = 0
function HatLiningMaker.init() HatLiningMaker.ironStock=10; HatLiningMaker.bronzeStock=8; HatLiningMaker.woodStock=14; HatLiningMaker.leatherStock=16; HatLiningMaker.silverStock=8; HatLiningMaker.goldStock=6; HatLiningMaker.jewelStock=4; HatLiningMaker.pearlStock=4; HatLiningMaker.productStock={}; HatLiningMaker.buildings={}; HatLiningMaker.maker=nil; HatLiningMaker.activeMaking={}; HatLiningMaker.totalProducts=0; HatLiningMaker.dayTimer=0; print("[HatLiningMaker] Royal Hat Lining Maker System initialized (6 products, 4 buildings)") end
function HatLiningMaker.hireMaker(n,s) s=s or math.random(55,90); local c=565+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HatLiningMaker.maker={name=n or ("Podstavnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Podstavnik najet: %s (spretnost: %d)",HatLiningMaker.maker.name,s),"success") end; return true end
function HatLiningMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HatLiningMaker.build(id) local ok,e=HatLiningMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HatLiningMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HatLiningMaker.getQualityBonus() local b=0; for _,bd in ipairs(HatLiningMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HatLiningMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and HatLiningMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and HatLiningMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and HatLiningMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and HatLiningMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and HatLiningMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HatLiningMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HatLiningMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HatLiningMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HatLiningMaker.buildings==0 then return false,"Potrebna podstavna delavnica" end; if not HatLiningMaker.maker then return false,"Potreben podstavnik" end; return true end
function HatLiningMaker.make(pt,qty) qty=qty or 1; local ok,e=HatLiningMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then HatLiningMaker.ironStock=HatLiningMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then HatLiningMaker.bronzeStock=HatLiningMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then HatLiningMaker.woodStock=HatLiningMaker.woodStock-d.woodCost*qty end; if d.leatherCost then HatLiningMaker.leatherStock=HatLiningMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then HatLiningMaker.silverStock=HatLiningMaker.silverStock-d.silverCost*qty end; if d.goldCost then HatLiningMaker.goldStock=HatLiningMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HatLiningMaker.jewelStock=HatLiningMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HatLiningMaker.pearlStock=HatLiningMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HatLiningMaker.maker then t=math.max(1,t-math.floor(HatLiningMaker.maker.skill/13)) end; table.insert(HatLiningMaker.activeMaking,{id="${MAKER_LOWER}_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HatLiningMaker.completeMaking(m) local q=1.0+(HatLiningMaker.getQualityBonus()/100); if HatLiningMaker.maker then q=q+(HatLiningMaker.maker.skill/140) end; q=math.min(2.5,q); HatLiningMaker.productStock[m.productType]=(HatLiningMaker.productStock[m.productType] or 0)+m.quantity; HatLiningMaker.totalProducts=HatLiningMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HatLiningMaker.maker then HatLiningMaker.maker.itemsMade=HatLiningMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then HatLiningMaker.maker.skill=math.min(100,HatLiningMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Podstav izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"${MAKER_LOWER}.completed",{productName=m.productName,prestige=m.prestige,happiness:m.happiness}) end end
function HatLiningMaker.update(dt) if not _G.state then return end; HatLiningMaker.dayTimer=HatLiningMaker.dayTimer+dt; if HatLiningMaker.dayTimer>=30 then HatLiningMaker.dayTimer=0; for i=#HatLiningMaker.activeMaking,1,-1 do local m=HatLiningMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HatLiningMaker.completeMaking(m); table.remove(HatLiningMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HatLiningMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HatLiningMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HatLiningMaker.getStats() return {ironStock=HatLiningMaker.ironStock,bronzeStock=HatLiningMaker.bronzeStock,woodStock=HatLiningMaker.woodStock,leatherStock=HatLiningMaker.leatherStock,silverStock=HatLiningMaker.silverStock,goldStock=HatLiningMaker.goldStock,jewelStock=HatLiningMaker.jewelStock,pearlStock=HatLiningMaker.pearlStock,productStock=HatLiningMaker.productStock,numBuildings=#HatLiningMaker.buildings,hasMaker=HatLiningMaker.maker~=nil,makerName=HatLiningMaker.maker and HatLiningMaker.maker.name or "—",makerSkill=HatLiningMaker.maker and HatLiningMaker.maker.skill or 0,activeMaking=#HatLiningMaker.activeMaking,totalProducts=HatLiningMaker.totalProducts} end
return HatLiningMaker
