local CorePasteMixerMaker = {}
local PRODUCTS = {
    iron_corepastemixer = { name = "Železni mešalnik jedrne paste", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni mešalnik jedrne paste za livarje." },
    bronze_corepastemixer = { name = "Bronast mešalnik jedrne paste", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast mešalnik jedrne paste za livarje." },
    silver_corepastemixer = { name = "Srebrn mešalnik jedrne paste", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn mešalnik jedrne paste za livarje." },
    gilded_corepastemixer = { name = "Pozlačen mešalnik jedrne paste", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen mešalnik jedrne paste za livarje." },
    jewel_set_corepastemixer = { name = "Draguljast mešalnik jedrne paste", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast mešalnik jedrne paste za livarje." },
    royal_sovereign_corepastemixer = { name = "Kraljevski suveren mešalnik jedrne paste", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren mešalnik jedrne paste z biseri za krono." },
}
local BUILDINGS = {
    corepastemixer_workshop = { name = "Corepastemixer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    corepastemixer_house = { name = "Corepastemixer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_corepastemixer_atelier = { name = "Mojstrski corepastemixer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_corepastemixer_palace = { name = "Suverena corepastemixer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
CorePasteMixerMaker.ironStock=14; CorePasteMixerMaker.bronzeStock=12; CorePasteMixerMaker.woodStock=14; CorePasteMixerMaker.leatherStock=8; CorePasteMixerMaker.silverStock=8; CorePasteMixerMaker.goldStock=6; CorePasteMixerMaker.jewelStock=4; CorePasteMixerMaker.pearlStock=4
CorePasteMixerMaker.productStock = {}; CorePasteMixerMaker.buildings = {}; CorePasteMixerMaker.maker = nil; CorePasteMixerMaker.activeMaking = {}; CorePasteMixerMaker.totalProducts = 0; CorePasteMixerMaker.dayTimer = 0
function CorePasteMixerMaker.init() CorePasteMixerMaker.ironStock=14; CorePasteMixerMaker.bronzeStock=12; CorePasteMixerMaker.woodStock=14; CorePasteMixerMaker.leatherStock=8; CorePasteMixerMaker.silverStock=8; CorePasteMixerMaker.goldStock=6; CorePasteMixerMaker.jewelStock=4; CorePasteMixerMaker.pearlStock=4; CorePasteMixerMaker.productStock={}; CorePasteMixerMaker.buildings={}; CorePasteMixerMaker.maker=nil; CorePasteMixerMaker.activeMaking={}; CorePasteMixerMaker.totalProducts=0; CorePasteMixerMaker.dayTimer=0; print("[CorePasteMixerMaker] Royal Core Paste Mixer Maker System initialized (6 products, 4 buildings)") end
function CorePasteMixerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CorePasteMixerMaker.maker={name=n or ("Mešalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mešalnik najet: %s (spretnost: %d)",CorePasteMixerMaker.maker.name,s),"success") end; return true end
function CorePasteMixerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CorePasteMixerMaker.build(id) local ok,e=CorePasteMixerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CorePasteMixerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CorePasteMixerMaker.getQualityBonus() local b=0; for _,bd in ipairs(CorePasteMixerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CorePasteMixerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CorePasteMixerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CorePasteMixerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CorePasteMixerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CorePasteMixerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CorePasteMixerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CorePasteMixerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CorePasteMixerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CorePasteMixerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CorePasteMixerMaker.buildings==0 then return false,"Potrebna mešalna delavnica" end; if not CorePasteMixerMaker.maker then return false,"Potreben mešalnik" end; return true end
function CorePasteMixerMaker.make(pt,qty) qty=qty or 1; local ok,e=CorePasteMixerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CorePasteMixerMaker.ironStock=CorePasteMixerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CorePasteMixerMaker.bronzeStock=CorePasteMixerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CorePasteMixerMaker.woodStock=CorePasteMixerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CorePasteMixerMaker.leatherStock=CorePasteMixerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CorePasteMixerMaker.silverStock=CorePasteMixerMaker.silverStock-d.silverCost*qty end; if d.goldCost then CorePasteMixerMaker.goldStock=CorePasteMixerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CorePasteMixerMaker.jewelStock=CorePasteMixerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CorePasteMixerMaker.pearlStock=CorePasteMixerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CorePasteMixerMaker.maker then t=math.max(1,t-math.floor(CorePasteMixerMaker.maker.skill/13)) end; table.insert(CorePasteMixerMaker.activeMaking,{id="corepastemixer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CorePasteMixerMaker.completeMaking(m) local q=1.0+(CorePasteMixerMaker.getQualityBonus()/100); if CorePasteMixerMaker.maker then q=q+(CorePasteMixerMaker.maker.skill/140) end; q=math.min(2.5,q); CorePasteMixerMaker.productStock[m.productType]=(CorePasteMixerMaker.productStock[m.productType] or 0)+m.quantity; CorePasteMixerMaker.totalProducts=CorePasteMixerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CorePasteMixerMaker.maker then CorePasteMixerMaker.maker.itemsMade=CorePasteMixerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CorePasteMixerMaker.maker.skill=math.min(100,CorePasteMixerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mešalnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"corepastemixer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CorePasteMixerMaker.update(dt) if not _G.state then return end; CorePasteMixerMaker.dayTimer=CorePasteMixerMaker.dayTimer+dt; if CorePasteMixerMaker.dayTimer>=30 then CorePasteMixerMaker.dayTimer=0; for i=#CorePasteMixerMaker.activeMaking,1,-1 do local m=CorePasteMixerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CorePasteMixerMaker.completeMaking(m); table.remove(CorePasteMixerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CorePasteMixerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CorePasteMixerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CorePasteMixerMaker.getStats() return {ironStock=CorePasteMixerMaker.ironStock,bronzeStock=CorePasteMixerMaker.bronzeStock,woodStock=CorePasteMixerMaker.woodStock,leatherStock=CorePasteMixerMaker.leatherStock,silverStock=CorePasteMixerMaker.silverStock,goldStock=CorePasteMixerMaker.goldStock,jewelStock=CorePasteMixerMaker.jewelStock,pearlStock=CorePasteMixerMaker.pearlStock,productStock=CorePasteMixerMaker.productStock,numBuildings=#CorePasteMixerMaker.buildings,hasMaker=CorePasteMixerMaker.maker~=nil,makerName=CorePasteMixerMaker.maker and CorePasteMixerMaker.maker.name or "—",makerSkill=CorePasteMixerMaker.maker and CorePasteMixerMaker.maker.skill or 0,activeMaking=#CorePasteMixerMaker.activeMaking,totalProducts=CorePasteMixerMaker.totalProducts} end
return CorePasteMixerMaker
