local RopeSpinner = {}
local PRODUCTS = {
    hemp_rope = { name = "Konopljeva vrv", hempCost = 3, time = 2, cost = 16, tensileStrength = 30, durability = 25, description = "Konopljeva vrv za vsakdanjo rabo." },
    tarred_rope = { name = "Katranova vrv", hempCost = 4, tarCost = 1, time = 3, cost = 45, tensileStrength = 45, durability = 35, prestige = 1, description = "Katranova vrv za pomorsko uporabo." },
    cable_rope = { name = "Kabelska vrv", hempCost = 5, tarCost = 1, time = 5, cost = 110, tensileStrength = 60, durability = 50, prestige = 3, happiness = 1, description = "Kabelska vrv za sidra in vitle." },
    silk_cord = { name = "Svilena vrvica", silkCost = 2, time = 6, cost = 260, tensileStrength = 75, durability = 60, prestige = 6, happiness = 2, description = "Svilena vrvica za fine namene." },
    silver_wire_rope = { name = "Srebrno žična vrv", silkCost = 2, silverCost = 1, hempCost = 2, time = 9, cost = 580, tensileStrength = 88, durability = 75, prestige = 12, happiness = 3, description = "Vrv s srebrno žico za plemiče." },
    royal_grand_rope = { name = "Kraljevski veliki vrv", silkCost = 4, hempCost = 4, goldCost = 1, silverCost = 1, jewelCost = 1, tarCost = 1, time = 14, cost = 1600, tensileStrength = 100, durability = 95, prestige = 35, happiness = 8, description = "Velika kraljevska vrv z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Vrivarska delavnica", cost = { gold = 260, wood = 130, stone = 200 }, upkeep = 6, qualityBonus = 5 },
    ropewalk = { name = "Vrivarska pot", cost = { gold = 900, wood = 280, stone = 400, hemp = 10 }, upkeep = 22, qualityBonus = 18 },
    tarring_house = { name = "Katranilnica", cost = { gold = 2200, wood = 350, stone = 600, silver = 30, tar = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_rope_atelier = { name = "Kraljevski atelje vrvi", cost = { gold = 8800, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 175, qualityBonus = 55, prestigeBonus = 40 },
}
RopeSpinner.hempStock = 22; RopeSpinner.tarStock = 14; RopeSpinner.silkStock = 12; RopeSpinner.silverStock = 8; RopeSpinner.goldStock = 6; RopeSpinner.jewelStock = 6
RopeSpinner.productStock = {}; RopeSpinner.buildings = {}; RopeSpinner.maker = nil; RopeSpinner.activeMaking = {}; RopeSpinner.totalProducts = 0; RopeSpinner.dayTimer = 0
function RopeSpinner.init() RopeSpinner.hempStock=22; RopeSpinner.tarStock=14; RopeSpinner.silkStock=12; RopeSpinner.silverStock=8; RopeSpinner.goldStock=6; RopeSpinner.jewelStock=6; RopeSpinner.productStock={}; RopeSpinner.buildings={}; RopeSpinner.maker=nil; RopeSpinner.activeMaking={}; RopeSpinner.totalProducts=0; RopeSpinner.dayTimer=0; print("[RopeSpinner] Royal Rope Spinner System initialized (6 products, 4 buildings)") end
function RopeSpinner.hireMaker(n,s) s=s or math.random(50,90); local c=490+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; RopeSpinner.maker={name=n or ("Vrivar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrivar najet: %s (spretnost: %d)",RopeSpinner.maker.name,s),"success") end; return true end
function RopeSpinner.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function RopeSpinner.build(id) local ok,e=RopeSpinner.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(RopeSpinner.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function RopeSpinner.getQualityBonus() local b=0; for _,bd in ipairs(RopeSpinner.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function RopeSpinner.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.hempCost and RopeSpinner.hempStock<(d.hempCost or 0) then return false,"Premalo konoplje" end; if d.tarCost and RopeSpinner.tarStock<(d.tarCost or 0) then return false,"Premalo katrana" end; if d.silkCost and RopeSpinner.silkStock<(d.silkCost or 0) then return false,"Premalo svile" end; if d.silverCost and RopeSpinner.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and RopeSpinner.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and RopeSpinner.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #RopeSpinner.buildings==0 then return false,"Potrebna delavnica" end; if not RopeSpinner.maker then return false,"Potreben vrivar" end; return true end
function RopeSpinner.make(pt,qty) qty=qty or 5; local ok,e=RopeSpinner.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.hempCost then RopeSpinner.hempStock=RopeSpinner.hempStock-d.hempCost*qty end; if d.tarCost then RopeSpinner.tarStock=RopeSpinner.tarStock-d.tarCost*qty end; if d.silkCost then RopeSpinner.silkStock=RopeSpinner.silkStock-d.silkCost*qty end; if d.silverCost then RopeSpinner.silverStock=RopeSpinner.silverStock-d.silverCost*qty end; if d.goldCost then RopeSpinner.goldStock=RopeSpinner.goldStock-d.goldCost*qty end; if d.jewelCost then RopeSpinner.jewelStock=RopeSpinner.jewelStock-d.jewelCost*qty end; local t=d.time; if RopeSpinner.maker then t=math.max(1,t-math.floor(RopeSpinner.maker.skill/12)) end; table.insert(RopeSpinner.activeMaking,{id="rope_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,tensileStrength=d.tensileStrength or 0,durability=d.durability or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function RopeSpinner.completeMaking(m) local q=1.0+(RopeSpinner.getQualityBonus()/100); if RopeSpinner.maker then q=q+(RopeSpinner.maker.skill/180) end; q=math.min(2.0,q); RopeSpinner.productStock[m.productType]=(RopeSpinner.productStock[m.productType] or 0)+m.quantity; RopeSpinner.totalProducts=RopeSpinner.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if RopeSpinner.maker then RopeSpinner.maker.itemsMade=RopeSpinner.maker.itemsMade+m.quantity; if math.random()<0.20 then RopeSpinner.maker.skill=math.min(100,RopeSpinner.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrv izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"rope.completed",{productName=m.productName,tensileStrength=m.tensileStrength,durability=m.durability}) end end
function RopeSpinner.update(dt) if not _G.state then return end; RopeSpinner.dayTimer=RopeSpinner.dayTimer+dt; if RopeSpinner.dayTimer>=30 then RopeSpinner.dayTimer=0; for i=#RopeSpinner.activeMaking,1,-1 do local m=RopeSpinner.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then RopeSpinner.completeMaking(m); table.remove(RopeSpinner.activeMaking,i) end end; local tu=0; for _,bd in ipairs(RopeSpinner.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if RopeSpinner.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function RopeSpinner.getStats() return {hempStock=RopeSpinner.hempStock,tarStock=RopeSpinner.tarStock,silkStock=RopeSpinner.silkStock,silverStock=RopeSpinner.silverStock,goldStock=RopeSpinner.goldStock,jewelStock=RopeSpinner.jewelStock,productStock=RopeSpinner.productStock,numBuildings=#RopeSpinner.buildings,hasMaker=RopeSpinner.maker~=nil,makerName=RopeSpinner.maker and RopeSpinner.maker.name or "—",makerSkill=RopeSpinner.maker and RopeSpinner.maker.skill or 0,activeMaking=#RopeSpinner.activeMaking,totalProducts=RopeSpinner.totalProducts} end
return RopeSpinner
