local ParadeMaceMaker = {}
local PRODUCTS = {
    simple_bronze_parade_mace = { name = "Preprost bronasta paradna buzdovan", bronzeCost = 3, woodCost = 1, time = 5, cost = 180, prestige = 5, happiness = 2, description = "Preprost bronasta paradna buzdovan za parade." },
    silver_head_parade_mace = { name = "Srebrnoglava paradna buzdovan", silverCost = 2, bronzeCost = 2, woodCost = 1, time = 8, cost = 440, prestige = 12, happiness = 3, description = "Srebrnoglava paradna buzdovan za trgovce." },
    gold_trimmed_parade_mace = { name = "Zlatookrasna paradna buzdovan", goldCost = 2, silverCost = 1, bronzeCost = 2, woodCost = 1, time = 12, cost = 1000, prestige = 22, happiness = 4, description = "Zlatookrasna paradna buzdovan za plemiče." },
    jewel_set_parade_mace = { name = "Draguljasta paradna buzdovan", goldCost = 2, silverCost = 1, bronzeCost = 2, woodCost = 1, jewelCost = 1, time = 16, cost = 2300, prestige = 35, happiness = 6, description = "Paradna buzdovan z draguljem za visoke plemiče." },
    pearl_set_parade_mace = { name = "Bisernavi paradna buzdovan", goldCost = 3, silverCost = 1, bronzeCost = 2, woodCost = 1, jewelCost = 1, pearlCost = 1, time = 20, cost = 4800, prestige = 50, happiness = 8, description = "Paradna buzdovan z biseri za visoko plemstvo." },
    royal_grand_parade_mace = { name = "Kraljevski veliki paradna buzdovan", goldCost = 4, silverCost = 2, bronzeCost = 2, woodCost = 1, jewelCost = 2, pearlCost = 2, time = 27, cost = 10000, prestige = 72, happiness = 13, description = "Veliki kraljevski paradna buzdovan z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    parade_workshop = { name = "Paradna delavnica", cost = { gold = 300, wood = 120, stone = 140, bronze = 6 }, upkeep = 7, qualityBonus = 5 },
    armorer_loft = { name = "Okleparska podstrešje", cost = { gold = 1100, wood = 280, stone = 280, silver = 6, gold = 4 }, upkeep = 26, qualityBonus = 18 },
    master_parade_atelier = { name = "Mojstrski paradni atelje", cost = { gold = 2800, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_armory_palace = { name = "Kraljevska orožarnaica palača", cost = { gold = 12000, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
ParadeMaceMaker.bronzeStock = 14; ParadeMaceMaker.woodStock = 10; ParadeMaceMaker.silverStock = 8; ParadeMaceMaker.goldStock = 6; ParadeMaceMaker.jewelStock = 4; ParadeMaceMaker.pearlStock = 4
ParadeMaceMaker.productStock = {}; ParadeMaceMaker.buildings = {}; ParadeMaceMaker.maker = nil; ParadeMaceMaker.activeMaking = {}; ParadeMaceMaker.totalProducts = 0; ParadeMaceMaker.dayTimer = 0
function ParadeMaceMaker.init() ParadeMaceMaker.bronzeStock=14; ParadeMaceMaker.woodStock=10; ParadeMaceMaker.silverStock=8; ParadeMaceMaker.goldStock=6; ParadeMaceMaker.jewelStock=4; ParadeMaceMaker.pearlStock=4; ParadeMaceMaker.productStock={}; ParadeMaceMaker.buildings={}; ParadeMaceMaker.maker=nil; ParadeMaceMaker.activeMaking={}; ParadeMaceMaker.totalProducts=0; ParadeMaceMaker.dayTimer=0; print("[ParadeMaceMaker] Royal Parade Mace Maker System initialized (6 products, 4 buildings)") end
function ParadeMaceMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ParadeMaceMaker.maker={name=n or ("Paradni buzdovnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Paradni buzdovnar najet: %s (spretnost: %d)",ParadeMaceMaker.maker.name,s),"success") end; return true end
function ParadeMaceMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ParadeMaceMaker.build(id) local ok,e=ParadeMaceMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ParadeMaceMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ParadeMaceMaker.getQualityBonus() local b=0; for _,bd in ipairs(ParadeMaceMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ParadeMaceMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.bronzeCost and ParadeMaceMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ParadeMaceMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.silverCost and ParadeMaceMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ParadeMaceMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ParadeMaceMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ParadeMaceMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ParadeMaceMaker.buildings==0 then return false,"Potrebna paradna delavnica" end; if not ParadeMaceMaker.maker then return false,"Potreben paradni buzdovnar" end; return true end
function ParadeMaceMaker.make(pt,qty) qty=qty or 1; local ok,e=ParadeMaceMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.bronzeCost then ParadeMaceMaker.bronzeStock=ParadeMaceMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ParadeMaceMaker.woodStock=ParadeMaceMaker.woodStock-d.woodCost*qty end; if d.silverCost then ParadeMaceMaker.silverStock=ParadeMaceMaker.silverStock-d.silverCost*qty end; if d.goldCost then ParadeMaceMaker.goldStock=ParadeMaceMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ParadeMaceMaker.jewelStock=ParadeMaceMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ParadeMaceMaker.pearlStock=ParadeMaceMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ParadeMaceMaker.maker then t=math.max(1,t-math.floor(ParadeMaceMaker.maker.skill/12)) end; table.insert(ParadeMaceMaker.activeMaking,{id="parademace_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ParadeMaceMaker.completeMaking(m) local q=1.0+(ParadeMaceMaker.getQualityBonus()/100); if ParadeMaceMaker.maker then q=q+(ParadeMaceMaker.maker.skill/140) end; q=math.min(2.5,q); ParadeMaceMaker.productStock[m.productType]=(ParadeMaceMaker.productStock[m.productType] or 0)+m.quantity; ParadeMaceMaker.totalProducts=ParadeMaceMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ParadeMaceMaker.maker then ParadeMaceMaker.maker.itemsMade=ParadeMaceMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ParadeMaceMaker.maker.skill=math.min(100,ParadeMaceMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Paradna buzdovan izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"parademace.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ParadeMaceMaker.update(dt) if not _G.state then return end; ParadeMaceMaker.dayTimer=ParadeMaceMaker.dayTimer+dt; if ParadeMaceMaker.dayTimer>=30 then ParadeMaceMaker.dayTimer=0; for i=#ParadeMaceMaker.activeMaking,1,-1 do local m=ParadeMaceMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ParadeMaceMaker.completeMaking(m); table.remove(ParadeMaceMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ParadeMaceMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ParadeMaceMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ParadeMaceMaker.getStats() return {bronzeStock=ParadeMaceMaker.bronzeStock,woodStock=ParadeMaceMaker.woodStock,silverStock=ParadeMaceMaker.silverStock,goldStock=ParadeMaceMaker.goldStock,jewelStock=ParadeMaceMaker.jewelStock,pearlStock=ParadeMaceMaker.pearlStock,productStock=ParadeMaceMaker.productStock,numBuildings=#ParadeMaceMaker.buildings,hasMaker=ParadeMaceMaker.maker~=nil,makerName=ParadeMaceMaker.maker and ParadeMaceMaker.maker.name or "—",makerSkill=ParadeMaceMaker.maker and ParadeMaceMaker.maker.skill or 0,activeMaking=#ParadeMaceMaker.activeMaking,totalProducts=ParadeMaceMaker.totalProducts} end
return ParadeMaceMaker
