local CodexBinder = {}
local PRODUCTS = {
    plain_wooden_codex = { name = "Preprost leseni kodeks", woodCost = 2, parchmentCost = 2, ropeCost = 1, time = 4, cost = 50, happiness = 1, description = "Preprost vezan kodeks za pisarno." },
    leather_bound_codex = { name = "Usnjeni vezan kodeks", woodCost = 1, leatherCost = 2, parchmentCost = 3, threadCost = 1, time = 6, cost = 130, happiness = 1, prestige = 2, description = "Usnjeni vezan kodeks za trgovce." },
    brass_clasp_codex = { name = "Medeninasto sponjeni kodeks", woodCost = 1, leatherCost = 2, parchmentCost = 3, brassCost = 1, threadCost = 1, time = 9, cost = 300, happiness = 2, prestige = 6, description = "Kodeks z medeninasto spono za plemiče." },
    silver_corner_codex = { name = "Srebrnokotni kodeks", woodCost = 1, leatherCost = 2, parchmentCost = 4, silverCost = 1, brassCost = 1, threadCost = 1, time = 13, cost = 720, happiness = 3, prestige = 15, description = "Kodeks s srebrnimi koti za visoke plemiče." },
    gold_embossed_codex = { name = "Zlato izbočeni kodeks", woodCost = 2, leatherCost = 3, parchmentCost = 4, goldCost = 2, silverCost = 1, jewelCost = 1, time = 17, cost = 1600, happiness = 5, prestige = 28, description = "Zlato izbočeni kodeks z draguljem za visoko plemstvo." },
    royal_grand_codex = { name = "Kraljevski veliki kodeks", woodCost = 3, leatherCost = 4, parchmentCost = 6, goldCost = 3, silverCost = 2, jewelCost = 2, pearlCost = 2, time = 24, cost = 3900, happiness = 12, prestige = 60, description = "Veliki kraljevski kodeks z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    binder_workshop = { name = "Vezalna delavnica", cost = { gold = 220, wood = 100, stone = 80, leather = 6 }, upkeep = 5, qualityBonus = 5 },
    scriptorium_atelier = { name = "Skriptorijski atelje", cost = { gold = 820, wood = 240, stone = 240, brass = 6, thread = 8 }, upkeep = 18, qualityBonus = 18 },
    goldsmith_bindery = { name = "Zlatarska vezava", cost = { gold = 2300, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 52, qualityBonus = 30 },
    royal_codex_palace = { name = "Kraljevska kodeksna palača", cost = { gold = 9500, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 50 },
}
CodexBinder.woodStock = 14; CodexBinder.leatherStock = 12; CodexBinder.parchmentStock = 14; CodexBinder.threadStock = 12; CodexBinder.ropeStock = 8; CodexBinder.brassStock = 8; CodexBinder.silverStock = 6; CodexBinder.goldStock = 6; CodexBinder.jewelStock = 4; CodexBinder.pearlStock = 4
CodexBinder.productStock = {}; CodexBinder.buildings = {}; CodexBinder.maker = nil; CodexBinder.activeMaking = {}; CodexBinder.totalProducts = 0; CodexBinder.dayTimer = 0
function CodexBinder.init() CodexBinder.woodStock=14; CodexBinder.leatherStock=12; CodexBinder.parchmentStock=14; CodexBinder.threadStock=12; CodexBinder.ropeStock=8; CodexBinder.brassStock=8; CodexBinder.silverStock=6; CodexBinder.goldStock=6; CodexBinder.jewelStock=4; CodexBinder.pearlStock=4; CodexBinder.productStock={}; CodexBinder.buildings={}; CodexBinder.maker=nil; CodexBinder.activeMaking={}; CodexBinder.totalProducts=0; CodexBinder.dayTimer=0; print("[CodexBinder] Royal Codex Binder System initialized (6 products, 4 buildings)") end
function CodexBinder.hireMaker(n,s) s=s or math.random(55,90); local c=500+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CodexBinder.maker={name=n or ("Vezalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vezalec najet: %s (spretnost: %d)",CodexBinder.maker.name,s),"success") end; return true end
function CodexBinder.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CodexBinder.build(id) local ok,e=CodexBinder.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CodexBinder.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CodexBinder.getQualityBonus() local b=0; for _,bd in ipairs(CodexBinder.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CodexBinder.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and CodexBinder.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CodexBinder.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.parchmentCost and CodexBinder.parchmentStock<(d.parchmentCost or 0) then return false,"Premalo pergamenta" end; if d.threadCost and CodexBinder.threadStock<(d.threadCost or 0) then return false,"Premalo niti" end; if d.ropeCost and CodexBinder.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.brassCost and CodexBinder.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and CodexBinder.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CodexBinder.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CodexBinder.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CodexBinder.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CodexBinder.buildings==0 then return false,"Potrebna vezalna delavnica" end; if not CodexBinder.maker then return false,"Potreben vezalec" end; return true end
function CodexBinder.make(pt,qty) qty=qty or 1; local ok,e=CodexBinder.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then CodexBinder.woodStock=CodexBinder.woodStock-d.woodCost*qty end; if d.leatherCost then CodexBinder.leatherStock=CodexBinder.leatherStock-d.leatherCost*qty end; if d.parchmentCost then CodexBinder.parchmentStock=CodexBinder.parchmentStock-d.parchmentCost*qty end; if d.threadCost then CodexBinder.threadStock=CodexBinder.threadStock-d.threadCost*qty end; if d.ropeCost then CodexBinder.ropeStock=CodexBinder.ropeStock-d.ropeCost*qty end; if d.brassCost then CodexBinder.brassStock=CodexBinder.brassStock-d.brassCost*qty end; if d.silverCost then CodexBinder.silverStock=CodexBinder.silverStock-d.silverCost*qty end; if d.goldCost then CodexBinder.goldStock=CodexBinder.goldStock-d.goldCost*qty end; if d.jewelCost then CodexBinder.jewelStock=CodexBinder.jewelStock-d.jewelCost*qty end; if d.pearlCost then CodexBinder.pearlStock=CodexBinder.pearlStock-d.pearlCost*qty end; local t=d.time; if CodexBinder.maker then t=math.max(1,t-math.floor(CodexBinder.maker.skill/13)) end; table.insert(CodexBinder.activeMaking,{id="codex_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vezava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CodexBinder.completeMaking(m) local q=1.0+(CodexBinder.getQualityBonus()/100); if CodexBinder.maker then q=q+(CodexBinder.maker.skill/150) end; q=math.min(2.4,q); CodexBinder.productStock[m.productType]=(CodexBinder.productStock[m.productType] or 0)+m.quantity; CodexBinder.totalProducts=CodexBinder.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CodexBinder.maker then CodexBinder.maker.itemsMade=CodexBinder.maker.itemsMade+m.quantity; if math.random()<0.25 then CodexBinder.maker.skill=math.min(100,CodexBinder.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kodeks vezan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"codex.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CodexBinder.update(dt) if not _G.state then return end; CodexBinder.dayTimer=CodexBinder.dayTimer+dt; if CodexBinder.dayTimer>=30 then CodexBinder.dayTimer=0; for i=#CodexBinder.activeMaking,1,-1 do local m=CodexBinder.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CodexBinder.completeMaking(m); table.remove(CodexBinder.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CodexBinder.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CodexBinder.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CodexBinder.getStats() return {woodStock=CodexBinder.woodStock,leatherStock=CodexBinder.leatherStock,parchmentStock=CodexBinder.parchmentStock,threadStock=CodexBinder.threadStock,ropeStock=CodexBinder.ropeStock,brassStock=CodexBinder.brassStock,silverStock=CodexBinder.silverStock,goldStock=CodexBinder.goldStock,jewelStock=CodexBinder.jewelStock,pearlStock=CodexBinder.pearlStock,productStock=CodexBinder.productStock,numBuildings=#CodexBinder.buildings,hasMaker=CodexBinder.maker~=nil,makerName=CodexBinder.maker and CodexBinder.maker.name or "—",makerSkill=CodexBinder.maker and CodexBinder.maker.skill or 0,activeMaking=#CodexBinder.activeMaking,totalProducts=CodexBinder.totalProducts} end
return CodexBinder
