local VitrailFoilMaker = {}
local PRODUCTS = {
    simple_lead_vitrail = { name = "Preprosta svinčeva vitraž", glassCost = 2, leadCost = 2, time = 4, cost = 50, beauty = 22, happiness = 2, description = "Preprosta svinčeva vitraž za okna." },
    painted_glass_vitrail = { name = "Poslikana vitraž", glassCost = 3, leadCost = 2, paintCost = 1, time = 7, cost = 150, beauty = 38, happiness = 2, prestige = 2, description = "Poslikana vitraž za trgovce." },
    silver_edged_vitrail = { name = "Srebrnookrasna vitraž", glassCost = 3, leadCost = 2, silverCost = 1, paintCost = 1, time = 10, cost = 380, beauty = 52, happiness = 3, prestige = 6, description = "Srebrnookrasna vitraž za plemiče." },
    gold_foil_vitrail = { name = "Zlatofolijna vitraž", glassCost = 4, leadCost = 2, goldCost = 1, silverCost = 1, paintCost = 1, time = 14, cost = 900, beauty = 68, happiness = 4, prestige = 14, description = "Zlatofolijna vitraž za visoke plemiče." },
    jewel_accent_vitrail = { name = "Draguljasta vitraž", glassCost = 4, leadCost = 2, goldCost = 2, silverCost = 1, paintCost = 1, jewelCost = 1, time = 18, cost = 2000, beauty = 82, happiness = 6, prestige = 27, description = "Vitraž z draguljem za visoko plemstvo." },
    royal_grand_vitrail = { name = "Kraljevski veliki vitraž", glassCost = 6, leadCost = 3, goldCost = 3, silverCost = 2, paintCost = 2, jewelCost = 2, pearlCost = 2, time = 25, cost = 4500, beauty = 95, happiness = 12, prestige = 58, description = "Veliki kraljevski vitraž z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    vitrail_workshop = { name = "Vitražna delavnica", cost = { gold = 260, wood = 100, stone = 120, glass = 6, lead = 6 }, upkeep = 6, qualityBonus = 5 },
    stained_loft = { name = "Vitražna podstrešje", cost = { gold = 900, wood = 240, stone = 240, silver = 6, paint = 6 }, upkeep = 21, qualityBonus = 18 },
    master_vitrail_atelier = { name = "Mojstrski vitražni atelje", cost = { gold = 2600, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 60, qualityBonus = 30 },
    royal_vitrail_palace = { name = "Kraljevska vitražna palača", cost = { gold = 11000, wood = 580, stone = 760, gold = 70, jewel = 18 }, upkeep = 220, qualityBonus = 55, prestigeBonus = 50 },
}
VitrailFoilMaker.glassStock = 18; VitrailFoilMaker.leadStock = 14; VitrailFoilMaker.paintStock = 10; VitrailFoilMaker.silverStock = 6; VitrailFoilMaker.goldStock = 6; VitrailFoilMaker.jewelStock = 4; VitrailFoilMaker.pearlStock = 4
VitrailFoilMaker.productStock = {}; VitrailFoilMaker.buildings = {}; VitrailFoilMaker.maker = nil; VitrailFoilMaker.activeMaking = {}; VitrailFoilMaker.totalProducts = 0; VitrailFoilMaker.dayTimer = 0
function VitrailFoilMaker.init() VitrailFoilMaker.glassStock=18; VitrailFoilMaker.leadStock=14; VitrailFoilMaker.paintStock=10; VitrailFoilMaker.silverStock=6; VitrailFoilMaker.goldStock=6; VitrailFoilMaker.jewelStock=4; VitrailFoilMaker.pearlStock=4; VitrailFoilMaker.productStock={}; VitrailFoilMaker.buildings={}; VitrailFoilMaker.maker=nil; VitrailFoilMaker.activeMaking={}; VitrailFoilMaker.totalProducts=0; VitrailFoilMaker.dayTimer=0; print("[VitrailFoilMaker] Royal Vitrail Foil Maker System initialized (6 products, 4 buildings)") end
function VitrailFoilMaker.hireMaker(n,s) s=s or math.random(55,90); local c=540+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; VitrailFoilMaker.maker={name=n or ("Vitražar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vitražar najet: %s (spretnost: %d)",VitrailFoilMaker.maker.name,s),"success") end; return true end
function VitrailFoilMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function VitrailFoilMaker.build(id) local ok,e=VitrailFoilMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(VitrailFoilMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function VitrailFoilMaker.getQualityBonus() local b=0; for _,bd in ipairs(VitrailFoilMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function VitrailFoilMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.glassCost and VitrailFoilMaker.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.leadCost and VitrailFoilMaker.leadStock<(d.leadCost or 0) then return false,"Premalo svinca" end; if d.paintCost and VitrailFoilMaker.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.silverCost and VitrailFoilMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and VitrailFoilMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and VitrailFoilMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and VitrailFoilMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #VitrailFoilMaker.buildings==0 then return false,"Potrebna vitražna delavnica" end; if not VitrailFoilMaker.maker then return false,"Potreben vitražar" end; return true end
function VitrailFoilMaker.make(pt,qty) qty=qty or 1; local ok,e=VitrailFoilMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.glassCost then VitrailFoilMaker.glassStock=VitrailFoilMaker.glassStock-d.glassCost*qty end; if d.leadCost then VitrailFoilMaker.leadStock=VitrailFoilMaker.leadStock-d.leadCost*qty end; if d.paintCost then VitrailFoilMaker.paintStock=VitrailFoilMaker.paintStock-d.paintCost*qty end; if d.silverCost then VitrailFoilMaker.silverStock=VitrailFoilMaker.silverStock-d.silverCost*qty end; if d.goldCost then VitrailFoilMaker.goldStock=VitrailFoilMaker.goldStock-d.goldCost*qty end; if d.jewelCost then VitrailFoilMaker.jewelStock=VitrailFoilMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then VitrailFoilMaker.pearlStock=VitrailFoilMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if VitrailFoilMaker.maker then t=math.max(1,t-math.floor(VitrailFoilMaker.maker.skill/13)) end; table.insert(VitrailFoilMaker.activeMaking,{id="vitrail_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,beauty=d.beauty or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function VitrailFoilMaker.completeMaking(m) local q=1.0+(VitrailFoilMaker.getQualityBonus()/100); if VitrailFoilMaker.maker then q=q+(VitrailFoilMaker.maker.skill/150) end; q=math.min(2.4,q); VitrailFoilMaker.productStock[m.productType]=(VitrailFoilMaker.productStock[m.productType] or 0)+m.quantity; VitrailFoilMaker.totalProducts=VitrailFoilMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if VitrailFoilMaker.maker then VitrailFoilMaker.maker.itemsMade=VitrailFoilMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then VitrailFoilMaker.maker.skill=math.min(100,VitrailFoilMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vitraž izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"vitrail.completed",{productName=m.productName,beauty=m.beauty,prestige=m.prestige,happiness=m.happiness}) end end
function VitrailFoilMaker.update(dt) if not _G.state then return end; VitrailFoilMaker.dayTimer=VitrailFoilMaker.dayTimer+dt; if VitrailFoilMaker.dayTimer>=30 then VitrailFoilMaker.dayTimer=0; for i=#VitrailFoilMaker.activeMaking,1,-1 do local m=VitrailFoilMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then VitrailFoilMaker.completeMaking(m); table.remove(VitrailFoilMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(VitrailFoilMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if VitrailFoilMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function VitrailFoilMaker.getStats() return {glassStock=VitrailFoilMaker.glassStock,leadStock=VitrailFoilMaker.leadStock,paintStock=VitrailFoilMaker.paintStock,silverStock=VitrailFoilMaker.silverStock,goldStock=VitrailFoilMaker.goldStock,jewelStock=VitrailFoilMaker.jewelStock,pearlStock=VitrailFoilMaker.pearlStock,productStock=VitrailFoilMaker.productStock,numBuildings=#VitrailFoilMaker.buildings,hasMaker=VitrailFoilMaker.maker~=nil,makerName=VitrailFoilMaker.maker and VitrailFoilMaker.maker.name or "—",makerSkill=VitrailFoilMaker.maker and VitrailFoilMaker.maker.skill or 0,activeMaking=#VitrailFoilMaker.activeMaking,totalProducts=VitrailFoilMaker.totalProducts} end
return VitrailFoilMaker
