local PocketWatchMaker = {}
local PRODUCTS = {
    simple_brass_watch = { name = "Preprosta medeninasta žepna ura", brassCost = 2, glassCost = 1, time = 6, cost = 100, science = 22, happiness = 2, prestige = 3, description = "Preprosta medeninasta žepna ura za trgovce." },
    silver_case_watch = { name = "Srebrnookrovna žepna ura", silverCost = 2, brassCost = 1, glassCost = 1, time = 9, cost = 280, science = 35, happiness = 2, prestige = 8, description = "Srebrnookrovna žepna ura za plemiče." },
    gold_case_watch = { name = "Zlatoookrovna žepna ura", goldCost = 2, silverCost = 1, brassCost = 1, glassCost = 1, time = 13, cost = 680, science = 50, happiness = 3, prestige = 16, description = "Zlatoookrovna žepna ura za visoke plemiče." }
    , jewel_bearing_watch = { name = "Draguljnoležajna žepna ura", goldCost = 2, silverCost = 1, brassCost = 1, glassCost = 1, jewelCost = 1, time = 17, cost = 1500, science = 65, happiness = 5, prestige = 28, description = "Žepna ura z draguljnim ležajem za visoko plemstvo." },
    pearl_face_watch = { name = "Bisernolicna žepna ura", goldCost = 2, silverCost = 1, brassCost = 1, glassCost = 1, jewelCost = 1, pearlCost = 1, time = 21, cost = 3200, science = 80, happiness = 7, prestige = 42, description = "Žepna ura z bisernim licem za visoko plemstvo." },
    royal_grand_watch = { name = "Kraljevski veliki žepna ura", goldCost = 3, silverCost = 2, brassCost = 1, glassCost = 2, jewelCost = 2, pearlCost = 2, time = 28, cost = 6800, science = 95, happiness = 13, prestige = 65, description = "Velika kraljevska žepna ura z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    watch_workshop = { name = "Urnarska delavnica", cost = { gold = 280, wood = 100, stone = 140, brass = 6, glass = 6 }, upkeep = 6, qualityBonus = 5 },
    horology_loft = { name = "Horološka podstrešje", cost = { gold = 1000, wood = 240, stone = 280, silver = 6, glass = 8 }, upkeep = 23, qualityBonus = 18 },
    master_watchmaker_atelier = { name = "Mojstrski urnarski atelje", cost = { gold = 2800, wood = 360, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_horology_palace = { name = "Kraljevska urnarska palača", cost = { gold = 12000, wood = 580, stone = 760, gold = 80, jewel = 18 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
PocketWatchMaker.brassStock = 12; PocketWatchMaker.glassStock = 12; PocketWatchMaker.silverStock = 8; PocketWatchMaker.goldStock = 6; PocketWatchMaker.jewelStock = 4; PocketWatchMaker.pearlStock = 4
PocketWatchMaker.productStock = {}; PocketWatchMaker.buildings = {}; PocketWatchMaker.maker = nil; PocketWatchMaker.activeMaking = {}; PocketWatchMaker.totalProducts = 0; PocketWatchMaker.dayTimer = 0
function PocketWatchMaker.init() PocketWatchMaker.brassStock=12; PocketWatchMaker.glassStock=12; PocketWatchMaker.silverStock=8; PocketWatchMaker.goldStock=6; PocketWatchMaker.jewelStock=4; PocketWatchMaker.pearlStock=4; PocketWatchMaker.productStock={}; PocketWatchMaker.buildings={}; PocketWatchMaker.maker=nil; PocketWatchMaker.activeMaking={}; PocketWatchMaker.totalProducts=0; PocketWatchMaker.dayTimer=0; print("[PocketWatchMaker] Royal Pocket Watch Maker System initialized (6 products, 4 buildings)") end
function PocketWatchMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PocketWatchMaker.maker={name=n or ("Urnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Urnar najet: %s (spretnost: %d)",PocketWatchMaker.maker.name,s),"success") end; return true end
function PocketWatchMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PocketWatchMaker.build(id) local ok,e=PocketWatchMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PocketWatchMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PocketWatchMaker.getQualityBonus() local b=0; for _,bd in ipairs(PocketWatchMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PocketWatchMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.brassCost and PocketWatchMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.glassCost and PocketWatchMaker.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.silverCost and PocketWatchMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PocketWatchMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PocketWatchMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PocketWatchMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PocketWatchMaker.buildings==0 then return false,"Potrebna urnarska delavnica" end; if not PocketWatchMaker.maker then return false,"Potreben urnar" end; return true end
function PocketWatchMaker.make(pt,qty) qty=qty or 1; local ok,e=PocketWatchMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.brassCost then PocketWatchMaker.brassStock=PocketWatchMaker.brassStock-d.brassCost*qty end; if d.glassCost then PocketWatchMaker.glassStock=PocketWatchMaker.glassStock-d.glassCost*qty end; if d.silverCost then PocketWatchMaker.silverStock=PocketWatchMaker.silverStock-d.silverCost*qty end; if d.goldCost then PocketWatchMaker.goldStock=PocketWatchMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PocketWatchMaker.jewelStock=PocketWatchMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PocketWatchMaker.pearlStock=PocketWatchMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PocketWatchMaker.maker then t=math.max(1,t-math.floor(PocketWatchMaker.maker.skill/12)) end; table.insert(PocketWatchMaker.activeMaking,{id="watch_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PocketWatchMaker.completeMaking(m) local q=1.0+(PocketWatchMaker.getQualityBonus()/100); if PocketWatchMaker.maker then q=q+(PocketWatchMaker.maker.skill/140) end; q=math.min(2.5,q); PocketWatchMaker.productStock[m.productType]=(PocketWatchMaker.productStock[m.productType] or 0)+m.quantity; PocketWatchMaker.totalProducts=PocketWatchMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PocketWatchMaker.maker then PocketWatchMaker.maker.itemsMade=PocketWatchMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PocketWatchMaker.maker.skill=math.min(100,PocketWatchMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ura izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"watch.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function PocketWatchMaker.update(dt) if not _G.state then return end; PocketWatchMaker.dayTimer=PocketWatchMaker.dayTimer+dt; if PocketWatchMaker.dayTimer>=30 then PocketWatchMaker.dayTimer=0; for i=#PocketWatchMaker.activeMaking,1,-1 do local m=PocketWatchMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PocketWatchMaker.completeMaking(m); table.remove(PocketWatchMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PocketWatchMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PocketWatchMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PocketWatchMaker.getStats() return {brassStock=PocketWatchMaker.brassStock,glassStock=PocketWatchMaker.glassStock,silverStock=PocketWatchMaker.silverStock,goldStock=PocketWatchMaker.goldStock,jewelStock=PocketWatchMaker.jewelStock,pearlStock=PocketWatchMaker.pearlStock,productStock=PocketWatchMaker.productStock,numBuildings=#PocketWatchMaker.buildings,hasMaker=PocketWatchMaker.maker~=nil,makerName=PocketWatchMaker.maker and PocketWatchMaker.maker.name or "—",makerSkill=PocketWatchMaker.maker and PocketWatchMaker.maker.skill or 0,activeMaking=#PocketWatchMaker.activeMaking,totalProducts=PocketWatchMaker.totalProducts} end
return PocketWatchMaker
