local GauntletMaker = {}
local PRODUCTS = {
    simple_leather_gauntlets = { name = "Preproste usnjene rokavice", leatherCost = 2, time = 4, cost = 100, defense = 15, happiness = 1, description = "Preproste usnjene rokavice za vojake." },
    iron_plate_gauntlets = { name = "Železnoploščate rokavice", ironCost = 2, leatherCost = 2, time = 7, cost = 280, defense = 28, happiness = 1, prestige = 3, description = "Železnoploščate rokavice za viteze." },
    silver_trimmed_gauntlets = { name = "Srebrnoobrobljene rokavice", ironCost = 2, silverCost = 1, leatherCost = 2, time = 10, cost = 620, defense = 42, happiness = 2, prestige = 8, description = "Srebrnoobrobljene rokavice za plemiške viteze." },
    gold_inlaid_gauntlets = { name = "Zlatovložene rokavice", ironCost = 2, goldCost = 1, silverCost = 1, leatherCost = 2, time = 14, cost = 1400, defense = 56, happiness = 3, prestige = 18, description = "Zlatovložene rokavice za visoke plemiče." },
    jewel_set_gauntlets = { name = "Draguljaste rokavice", ironCost = 2, goldCost = 1, silverCost = 1, leatherCost = 2, jewelCost = 1, time = 18, cost = 3000, defense = 68, happiness = 5, prestige = 32, description = "Rokavice z draguljem za visoko plemstvo." },
    royal_grand_gauntlets = { name = "Kraljevski velike rokavice", ironCost = 3, goldCost = 2, silverCost = 2, leatherCost = 2, jewelCost = 2, pearlCost = 2, time = 25, cost = 6500, defense = 84, happiness = 12, prestige = 60, description = "Velike kraljevske rokavice z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    gauntlet_workshop = { name = "Rokavična delavnica", cost = { gold = 240, wood = 100, stone = 120, iron = 6, leather = 6 }, upkeep = 5, qualityBonus = 5 },
    armor_loft = { name = "Oklepna podstrešje", cost = { gold = 950, wood = 260, stone = 280, silver = 6, leather = 8 }, upkeep = 22, qualityBonus = 18 },
    master_armorer_atelier = { name = "Mojstrski okleparski atelje", cost = { gold = 2700, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 62, qualityBonus = 30 },
    royal_gauntlet_palace = { name = "Kraljevska rokavična palača", cost = { gold = 11500, wood = 600, stone = 800, gold = 75, jewel = 18 }, upkeep = 230, qualityBonus = 55, prestigeBonus = 50 },
}
GauntletMaker.ironStock = 14; GauntletMaker.leatherStock = 14; GauntletMaker.silverStock = 6; GauntletMaker.goldStock = 6; GauntletMaker.jewelStock = 4; GauntletMaker.pearlStock = 4
GauntletMaker.productStock = {}; GauntletMaker.buildings = {}; GauntletMaker.maker = nil; GauntletMaker.activeMaking = {}; GauntletMaker.totalProducts = 0; GauntletMaker.dayTimer = 0
function GauntletMaker.init() GauntletMaker.ironStock=14; GauntletMaker.leatherStock=14; GauntletMaker.silverStock=6; GauntletMaker.goldStock=6; GauntletMaker.jewelStock=4; GauntletMaker.pearlStock=4; GauntletMaker.productStock={}; GauntletMaker.buildings={}; GauntletMaker.maker=nil; GauntletMaker.activeMaking={}; GauntletMaker.totalProducts=0; GauntletMaker.dayTimer=0; print("[GauntletMaker] Royal Gauntlet Maker System initialized (6 products, 4 buildings)") end
function GauntletMaker.hireMaker(n,s) s=s or math.random(55,90); local c=520+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GauntletMaker.maker={name=n or ("Rokavičar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rokavičar najet: %s (spretnost: %d)",GauntletMaker.maker.name,s),"success") end; return true end
function GauntletMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GauntletMaker.build(id) local ok,e=GauntletMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GauntletMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GauntletMaker.getQualityBonus() local b=0; for _,bd in ipairs(GauntletMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GauntletMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GauntletMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.leatherCost and GauntletMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GauntletMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GauntletMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GauntletMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GauntletMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GauntletMaker.buildings==0 then return false,"Potrebna rokavična delavnica" end; if not GauntletMaker.maker then return false,"Potreben rokavičar" end; return true end
function GauntletMaker.make(pt,qty) qty=qty or 1; local ok,e=GauntletMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GauntletMaker.ironStock=GauntletMaker.ironStock-d.ironCost*qty end; if d.leatherCost then GauntletMaker.leatherStock=GauntletMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GauntletMaker.silverStock=GauntletMaker.silverStock-d.silverCost*qty end; if d.goldCost then GauntletMaker.goldStock=GauntletMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GauntletMaker.jewelStock=GauntletMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GauntletMaker.pearlStock=GauntletMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GauntletMaker.maker then t=math.max(1,t-math.floor(GauntletMaker.maker.skill/12)) end; table.insert(GauntletMaker.activeMaking,{id="gauntlet_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,defense=d.defense or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GauntletMaker.completeMaking(m) local q=1.0+(GauntletMaker.getQualityBonus()/100); if GauntletMaker.maker then q=q+(GauntletMaker.maker.skill/140) end; q=math.min(2.5,q); GauntletMaker.productStock[m.productType]=(GauntletMaker.productStock[m.productType] or 0)+m.quantity; GauntletMaker.totalProducts=GauntletMaker.totalProducts+m.quantity; if m.defense>0 and _G.state then _G.state.defense=(_G.state.defense or 0)+m.defense end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GauntletMaker.maker then GauntletMaker.maker.itemsMade=GauntletMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GauntletMaker.maker.skill=math.min(100,GauntletMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rokavice izdelane: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gauntlet.completed",{productName=m.productName,defense=m.defense,prestige=m.prestige,happiness=m.happiness}) end end
function GauntletMaker.update(dt) if not _G.state then return end; GauntletMaker.dayTimer=GauntletMaker.dayTimer+dt; if GauntletMaker.dayTimer>=30 then GauntletMaker.dayTimer=0; for i=#GauntletMaker.activeMaking,1,-1 do local m=GauntletMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GauntletMaker.completeMaking(m); table.remove(GauntletMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GauntletMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GauntletMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GauntletMaker.getStats() return {ironStock=GauntletMaker.ironStock,leatherStock=GauntletMaker.leatherStock,silverStock=GauntletMaker.silverStock,goldStock=GauntletMaker.goldStock,jewelStock=GauntletMaker.jewelStock,pearlStock=GauntletMaker.pearlStock,productStock=GauntletMaker.productStock,numBuildings=#GauntletMaker.buildings,hasMaker=GauntletMaker.maker~=nil,makerName=GauntletMaker.maker and GauntletMaker.maker.name or "—",makerSkill=GauntletMaker.maker and GauntletMaker.maker.skill or 0,activeMaking=#GauntletMaker.activeMaking,totalProducts=GauntletMaker.totalProducts} end
return GauntletMaker
