local BookEdgeGiltBurnisherMaker = {}
local PRODUCTS = {
    iron_bookedgegiltburnisher = { name = "Železni polirnik za pozlate robov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni polirnik za pozlate robov za knjigoveze." },
    bronze_bookedgegiltburnisher = { name = "Bronast polirnik za pozlate robov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast polirnik za pozlate robov za knjigoveze." },
    silver_bookedgegiltburnisher = { name = "Srebrn polirnik za pozlate robov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn polirnik za pozlate robov za knjigoveze." },
    gilded_bookedgegiltburnisher = { name = "Pozlačen polirnik za pozlate robov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen polirnik za pozlate robov za knjigoveze." },
    jewel_set_bookedgegiltburnisher = { name = "Draguljast polirnik za pozlate robov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast polirnik za pozlate robov za knjigoveze." },
    royal_sovereign_bookedgegiltburnisher = { name = "Kraljevski suveren polirnik za pozlate robov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren polirnik za pozlate robov z biseri za krono." },
}
local BUILDINGS = {
    bookedgegiltburnisher_workshop = { name = "Bookedgegiltburnisher delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookedgegiltburnisher_house = { name = "Bookedgegiltburnisher hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookedgegiltburnisher_atelier = { name = "Mojstrski bookedgegiltburnisher atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookedgegiltburnisher_palace = { name = "Suverena bookedgegiltburnisher palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookEdgeGiltBurnisherMaker.ironStock=18; BookEdgeGiltBurnisherMaker.bronzeStock=14; BookEdgeGiltBurnisherMaker.woodStock=10; BookEdgeGiltBurnisherMaker.leatherStock=8; BookEdgeGiltBurnisherMaker.silverStock=8; BookEdgeGiltBurnisherMaker.goldStock=6; BookEdgeGiltBurnisherMaker.jewelStock=4; BookEdgeGiltBurnisherMaker.pearlStock=4
BookEdgeGiltBurnisherMaker.productStock = {}; BookEdgeGiltBurnisherMaker.buildings = {}; BookEdgeGiltBurnisherMaker.maker = nil; BookEdgeGiltBurnisherMaker.activeMaking = {}; BookEdgeGiltBurnisherMaker.totalProducts = 0; BookEdgeGiltBurnisherMaker.dayTimer = 0
function BookEdgeGiltBurnisherMaker.init() BookEdgeGiltBurnisherMaker.ironStock=18; BookEdgeGiltBurnisherMaker.bronzeStock=14; BookEdgeGiltBurnisherMaker.woodStock=10; BookEdgeGiltBurnisherMaker.leatherStock=8; BookEdgeGiltBurnisherMaker.silverStock=8; BookEdgeGiltBurnisherMaker.goldStock=6; BookEdgeGiltBurnisherMaker.jewelStock=4; BookEdgeGiltBurnisherMaker.pearlStock=4; BookEdgeGiltBurnisherMaker.productStock={}; BookEdgeGiltBurnisherMaker.buildings={}; BookEdgeGiltBurnisherMaker.maker=nil; BookEdgeGiltBurnisherMaker.activeMaking={}; BookEdgeGiltBurnisherMaker.totalProducts=0; BookEdgeGiltBurnisherMaker.dayTimer=0; print("[BookEdgeGiltBurnisherMaker] Royal Book Edge Gilt Burnisher Maker System initialized (6 products, 4 buildings)") end
function BookEdgeGiltBurnisherMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookEdgeGiltBurnisherMaker.maker={name=n or ("Polirnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Polirnik najet: %s (spretnost: %d)",BookEdgeGiltBurnisherMaker.maker.name,s),"success") end; return true end
function BookEdgeGiltBurnisherMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookEdgeGiltBurnisherMaker.build(id) local ok,e=BookEdgeGiltBurnisherMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookEdgeGiltBurnisherMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookEdgeGiltBurnisherMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookEdgeGiltBurnisherMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookEdgeGiltBurnisherMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookEdgeGiltBurnisherMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookEdgeGiltBurnisherMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookEdgeGiltBurnisherMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookEdgeGiltBurnisherMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookEdgeGiltBurnisherMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookEdgeGiltBurnisherMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookEdgeGiltBurnisherMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookEdgeGiltBurnisherMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookEdgeGiltBurnisherMaker.buildings==0 then return false,"Potrebna polirna delavnica" end; if not BookEdgeGiltBurnisherMaker.maker then return false,"Potreben polirnik" end; return true end
function BookEdgeGiltBurnisherMaker.make(pt,qty) qty=qty or 1; local ok,e=BookEdgeGiltBurnisherMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookEdgeGiltBurnisherMaker.ironStock=BookEdgeGiltBurnisherMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookEdgeGiltBurnisherMaker.bronzeStock=BookEdgeGiltBurnisherMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookEdgeGiltBurnisherMaker.woodStock=BookEdgeGiltBurnisherMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookEdgeGiltBurnisherMaker.leatherStock=BookEdgeGiltBurnisherMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookEdgeGiltBurnisherMaker.silverStock=BookEdgeGiltBurnisherMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookEdgeGiltBurnisherMaker.goldStock=BookEdgeGiltBurnisherMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookEdgeGiltBurnisherMaker.jewelStock=BookEdgeGiltBurnisherMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookEdgeGiltBurnisherMaker.pearlStock=BookEdgeGiltBurnisherMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookEdgeGiltBurnisherMaker.maker then t=math.max(1,t-math.floor(BookEdgeGiltBurnisherMaker.maker.skill/13)) end; table.insert(BookEdgeGiltBurnisherMaker.activeMaking,{id="bookedgegiltburnisher_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookEdgeGiltBurnisherMaker.completeMaking(m) local q=1.0+(BookEdgeGiltBurnisherMaker.getQualityBonus()/100); if BookEdgeGiltBurnisherMaker.maker then q=q+(BookEdgeGiltBurnisherMaker.maker.skill/140) end; q=math.min(2.5,q); BookEdgeGiltBurnisherMaker.productStock[m.productType]=(BookEdgeGiltBurnisherMaker.productStock[m.productType] or 0)+m.quantity; BookEdgeGiltBurnisherMaker.totalProducts=BookEdgeGiltBurnisherMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookEdgeGiltBurnisherMaker.maker then BookEdgeGiltBurnisherMaker.maker.itemsMade=BookEdgeGiltBurnisherMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookEdgeGiltBurnisherMaker.maker.skill=math.min(100,BookEdgeGiltBurnisherMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Polirnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookedgegiltburnisher.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookEdgeGiltBurnisherMaker.update(dt) if not _G.state then return end; BookEdgeGiltBurnisherMaker.dayTimer=BookEdgeGiltBurnisherMaker.dayTimer+dt; if BookEdgeGiltBurnisherMaker.dayTimer>=30 then BookEdgeGiltBurnisherMaker.dayTimer=0; for i=#BookEdgeGiltBurnisherMaker.activeMaking,1,-1 do local m=BookEdgeGiltBurnisherMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookEdgeGiltBurnisherMaker.completeMaking(m); table.remove(BookEdgeGiltBurnisherMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookEdgeGiltBurnisherMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookEdgeGiltBurnisherMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookEdgeGiltBurnisherMaker.getStats() return {ironStock=BookEdgeGiltBurnisherMaker.ironStock,bronzeStock=BookEdgeGiltBurnisherMaker.bronzeStock,woodStock=BookEdgeGiltBurnisherMaker.woodStock,leatherStock=BookEdgeGiltBurnisherMaker.leatherStock,silverStock=BookEdgeGiltBurnisherMaker.silverStock,goldStock=BookEdgeGiltBurnisherMaker.goldStock,jewelStock=BookEdgeGiltBurnisherMaker.jewelStock,pearlStock=BookEdgeGiltBurnisherMaker.pearlStock,productStock=BookEdgeGiltBurnisherMaker.productStock,numBuildings=#BookEdgeGiltBurnisherMaker.buildings,hasMaker=BookEdgeGiltBurnisherMaker.maker~=nil,makerName=BookEdgeGiltBurnisherMaker.maker and BookEdgeGiltBurnisherMaker.maker.name or "—",makerSkill=BookEdgeGiltBurnisherMaker.maker and BookEdgeGiltBurnisherMaker.maker.skill or 0,activeMaking=#BookEdgeGiltBurnisherMaker.activeMaking,totalProducts=BookEdgeGiltBurnisherMaker.totalProducts} end
return BookEdgeGiltBurnisherMaker
