local SandTestCupMaker = {}
local PRODUCTS = {
    iron_sandtestcup = { name = "Železni skodelica za testiranje peska", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni skodelica za testiranje peska za livarje." },
    bronze_sandtestcup = { name = "Bronast skodelica za testiranje peska", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast skodelica za testiranje peska za livarje." },
    silver_sandtestcup = { name = "Srebrn skodelica za testiranje peska", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn skodelica za testiranje peska za livarje." },
    gilded_sandtestcup = { name = "Pozlačen skodelica za testiranje peska", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen skodelica za testiranje peska za livarje." },
    jewel_set_sandtestcup = { name = "Draguljast skodelica za testiranje peska", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast skodelica za testiranje peska za livarje." },
    royal_sovereign_sandtestcup = { name = "Kraljevski suveren skodelica za testiranje peska", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren skodelica za testiranje peska z biseri za krono." },
}
local BUILDINGS = {
    sandtestcup_workshop = { name = "Sandtestcup delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    sandtestcup_house = { name = "Sandtestcup hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_sandtestcup_atelier = { name = "Mojstrski sandtestcup atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_sandtestcup_palace = { name = "Suverena sandtestcup palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SandTestCupMaker.ironStock=12; SandTestCupMaker.bronzeStock=10; SandTestCupMaker.woodStock=14; SandTestCupMaker.leatherStock=8; SandTestCupMaker.silverStock=8; SandTestCupMaker.goldStock=6; SandTestCupMaker.jewelStock=4; SandTestCupMaker.pearlStock=4
SandTestCupMaker.productStock = {}; SandTestCupMaker.buildings = {}; SandTestCupMaker.maker = nil; SandTestCupMaker.activeMaking = {}; SandTestCupMaker.totalProducts = 0; SandTestCupMaker.dayTimer = 0
function SandTestCupMaker.init() SandTestCupMaker.ironStock=12; SandTestCupMaker.bronzeStock=10; SandTestCupMaker.woodStock=14; SandTestCupMaker.leatherStock=8; SandTestCupMaker.silverStock=8; SandTestCupMaker.goldStock=6; SandTestCupMaker.jewelStock=4; SandTestCupMaker.pearlStock=4; SandTestCupMaker.productStock={}; SandTestCupMaker.buildings={}; SandTestCupMaker.maker=nil; SandTestCupMaker.activeMaking={}; SandTestCupMaker.totalProducts=0; SandTestCupMaker.dayTimer=0; print("[SandTestCupMaker] Royal Sand Test Cup Maker System initialized (6 products, 4 buildings)") end
function SandTestCupMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SandTestCupMaker.maker={name=n or ("Skodeličar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Skodeličar najet: %s (spretnost: %d)",SandTestCupMaker.maker.name,s),"success") end; return true end
function SandTestCupMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SandTestCupMaker.build(id) local ok,e=SandTestCupMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SandTestCupMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SandTestCupMaker.getQualityBonus() local b=0; for _,bd in ipairs(SandTestCupMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SandTestCupMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SandTestCupMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SandTestCupMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SandTestCupMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SandTestCupMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SandTestCupMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SandTestCupMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SandTestCupMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SandTestCupMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SandTestCupMaker.buildings==0 then return false,"Potrebna skodicna delavnica" end; if not SandTestCupMaker.maker then return false,"Potreben skodelicar" end; return true end
function SandTestCupMaker.make(pt,qty) qty=qty or 1; local ok,e=SandTestCupMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SandTestCupMaker.ironStock=SandTestCupMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SandTestCupMaker.bronzeStock=SandTestCupMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SandTestCupMaker.woodStock=SandTestCupMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SandTestCupMaker.leatherStock=SandTestCupMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SandTestCupMaker.silverStock=SandTestCupMaker.silverStock-d.silverCost*qty end; if d.goldCost then SandTestCupMaker.goldStock=SandTestCupMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SandTestCupMaker.jewelStock=SandTestCupMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SandTestCupMaker.pearlStock=SandTestCupMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SandTestCupMaker.maker then t=math.max(1,t-math.floor(SandTestCupMaker.maker.skill/13)) end; table.insert(SandTestCupMaker.activeMaking,{id="sandtestcup_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SandTestCupMaker.completeMaking(m) local q=1.0+(SandTestCupMaker.getQualityBonus()/100); if SandTestCupMaker.maker then q=q+(SandTestCupMaker.maker.skill/140) end; q=math.min(2.5,q); SandTestCupMaker.productStock[m.productType]=(SandTestCupMaker.productStock[m.productType] or 0)+m.quantity; SandTestCupMaker.totalProducts=SandTestCupMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SandTestCupMaker.maker then SandTestCupMaker.maker.itemsMade=SandTestCupMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SandTestCupMaker.maker.skill=math.min(100,SandTestCupMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Skodelica izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sandtestcup.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SandTestCupMaker.update(dt) if not _G.state then return end; SandTestCupMaker.dayTimer=SandTestCupMaker.dayTimer+dt; if SandTestCupMaker.dayTimer>=30 then SandTestCupMaker.dayTimer=0; for i=#SandTestCupMaker.activeMaking,1,-1 do local m=SandTestCupMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SandTestCupMaker.completeMaking(m); table.remove(SandTestCupMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SandTestCupMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SandTestCupMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SandTestCupMaker.getStats() return {ironStock=SandTestCupMaker.ironStock,bronzeStock=SandTestCupMaker.bronzeStock,woodStock=SandTestCupMaker.woodStock,leatherStock=SandTestCupMaker.leatherStock,silverStock=SandTestCupMaker.silverStock,goldStock=SandTestCupMaker.goldStock,jewelStock=SandTestCupMaker.jewelStock,pearlStock=SandTestCupMaker.pearlStock,productStock=SandTestCupMaker.productStock,numBuildings=#SandTestCupMaker.buildings,hasMaker=SandTestCupMaker.maker~=nil,makerName=SandTestCupMaker.maker and SandTestCupMaker.maker.name or "—",makerSkill=SandTestCupMaker.maker and SandTestCupMaker.maker.skill or 0,activeMaking=#SandTestCupMaker.activeMaking,totalProducts=SandTestCupMaker.totalProducts} end
return SandTestCupMaker
