local TubularBellsMaker = {}
local PRODUCTS = {
    iron_chime_tubular = { name = "Železno zveneče tubular", ironCost = 2, woodCost = 2, ropeCost = 1, time = 5, cost = 160, happiness = 1, prestige = 2, description = "Železno tubular za preprosto zvonjenje." },
    brass_orchestral_tubular = { name = "Medeninasto orkestralno tubular", brassCost = 2, ironCost = 1, woodCost = 2, ropeCost = 1, time = 8, cost = 410, happiness = 2, prestige = 6, description = "Orkestralno tubular za dvorne koncerte." },
    silver_tuned_tubular = { name = "Srebrno uglašeno tubular", silverCost = 2, brassCost = 1, ironCost = 1, woodCost = 2, ropeCost = 1, time = 12, cost = 1080, happiness = 3, prestige = 12, description = "Srebrno uglašeno tubular za plemiče." },
    gilded_cathedral_tubular = { name = "Pozlačeno katedralsko tubular", goldCost = 1, silverCost = 2, brassCost = 1, woodCost = 2, ropeCost = 1, time = 16, cost = 2500, happiness = 4, prestige = 23, description = "Pozlačeno tubular za katedralo." },
    jewel_set_royal_tubular = { name = "Draguljasta kraljevska tubular", goldCost = 2, silverCost = 2, jewelCost = 1, brassCost = 1, woodCost = 2, ropeCost = 1, time = 20, cost = 5300, happiness = 6, prestige = 41, description = "Draguljasto tubular za kraljevo kapelo." },
    sovereign_grand_tubular = { name = "Suvereni veliki tubular", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, brassCost = 1, woodCost = 3, ropeCost = 1, time = 27, cost = 11500, happiness = 12, prestige = 79, description = "Veliki suvereni tubular z biseri za krono." },
}
local BUILDINGS = {
    tubular_workshop = { name = "Tubular delavnica", cost = { gold = 320, wood = 160, stone = 120, iron = 6 }, upkeep = 6, qualityBonus = 5 },
    chime_tower_annex = { name = "Zvončni stolp priključek", cost = { gold = 1200, wood = 320, stone = 240, silver = 6, iron = 6 }, upkeep = 25, qualityBonus = 18 },
    master_tubular_atelier = { name = "Mojstrski tubular atelje", cost = { gold = 3000, wood = 400, stone = 500, silver = 36, gold = 6 }, upkeep = 72, qualityBonus = 30 },
    sovereign_resonance_palace = { name = "Suverena resonančna palača", cost = { gold = 13500, wood = 650, stone = 850, gold = 85, jewel = 18 }, upkeep = 255, qualityBonus = 55, prestigeBonus = 50 },
}
TubularBellsMaker.ironStock = 12; TubularBellsMaker.brassStock = 10; TubularBellsMaker.woodStock = 14; TubularBellsMaker.ropeStock = 10; TubularBellsMaker.silverStock = 8; TubularBellsMaker.goldStock = 6; TubularBellsMaker.jewelStock = 4; TubularBellsMaker.pearlStock = 4
TubularBellsMaker.productStock = {}; TubularBellsMaker.buildings = {}; TubularBellsMaker.maker = nil; TubularBellsMaker.activeMaking = {}; TubularBellsMaker.totalProducts = 0; TubularBellsMaker.dayTimer = 0
function TubularBellsMaker.init() TubularBellsMaker.ironStock=12; TubularBellsMaker.brassStock=10; TubularBellsMaker.woodStock=14; TubularBellsMaker.ropeStock=10; TubularBellsMaker.silverStock=8; TubularBellsMaker.goldStock=6; TubularBellsMaker.jewelStock=4; TubularBellsMaker.pearlStock=4; TubularBellsMaker.productStock={}; TubularBellsMaker.buildings={}; TubularBellsMaker.maker=nil; TubularBellsMaker.activeMaking={}; TubularBellsMaker.totalProducts=0; TubularBellsMaker.dayTimer=0; print("[TubularBellsMaker] Royal Tubular Bells Maker System initialized (6 products, 4 buildings)") end
function TubularBellsMaker.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TubularBellsMaker.maker={name=n or ("Tubularist "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tubularist najet: %s (spretnost: %d)",TubularBellsMaker.maker.name,s),"success") end; return true end
function TubularBellsMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TubularBellsMaker.build(id) local ok,e=TubularBellsMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TubularBellsMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TubularBellsMaker.getQualityBonus() local b=0; for _,bd in ipairs(TubularBellsMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TubularBellsMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and TubularBellsMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.brassCost and TubularBellsMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.woodCost and TubularBellsMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ropeCost and TubularBellsMaker.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.silverCost and TubularBellsMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and TubularBellsMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and TubularBellsMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and TubularBellsMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #TubularBellsMaker.buildings==0 then return false,"Potrebna tubular delavnica" end; if not TubularBellsMaker.maker then return false,"Potreben tubularist" end; return true end
function TubularBellsMaker.make(pt,qty) qty=qty or 1; local ok,e=TubularBellsMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then TubularBellsMaker.ironStock=TubularBellsMaker.ironStock-d.ironCost*qty end; if d.brassCost then TubularBellsMaker.brassStock=TubularBellsMaker.brassStock-d.brassCost*qty end; if d.woodCost then TubularBellsMaker.woodStock=TubularBellsMaker.woodStock-d.woodCost*qty end; if d.ropeCost then TubularBellsMaker.ropeStock=TubularBellsMaker.ropeStock-d.ropeCost*qty end; if d.silverCost then TubularBellsMaker.silverStock=TubularBellsMaker.silverStock-d.silverCost*qty end; if d.goldCost then TubularBellsMaker.goldStock=TubularBellsMaker.goldStock-d.goldCost*qty end; if d.jewelCost then TubularBellsMaker.jewelStock=TubularBellsMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then TubularBellsMaker.pearlStock=TubularBellsMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if TubularBellsMaker.maker then t=math.max(1,t-math.floor(TubularBellsMaker.maker.skill/13)) end; table.insert(TubularBellsMaker.activeMaking,{id="tubular_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TubularBellsMaker.completeMaking(m) local q=1.0+(TubularBellsMaker.getQualityBonus()/100); if TubularBellsMaker.maker then q=q+(TubularBellsMaker.maker.skill/140) end; q=math.min(2.5,q); TubularBellsMaker.productStock[m.productType]=(TubularBellsMaker.productStock[m.productType] or 0)+m.quantity; TubularBellsMaker.totalProducts=TubularBellsMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if TubularBellsMaker.maker then TubularBellsMaker.maker.itemsMade=TubularBellsMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then TubularBellsMaker.maker.skill=math.min(100,TubularBellsMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tubular izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"tubular.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function TubularBellsMaker.update(dt) if not _G.state then return end; TubularBellsMaker.dayTimer=TubularBellsMaker.dayTimer+dt; if TubularBellsMaker.dayTimer>=30 then TubularBellsMaker.dayTimer=0; for i=#TubularBellsMaker.activeMaking,1,-1 do local m=TubularBellsMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TubularBellsMaker.completeMaking(m); table.remove(TubularBellsMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TubularBellsMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TubularBellsMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TubularBellsMaker.getStats() return {ironStock=TubularBellsMaker.ironStock,brassStock=TubularBellsMaker.brassStock,woodStock=TubularBellsMaker.woodStock,ropeStock=TubularBellsMaker.ropeStock,silverStock=TubularBellsMaker.silverStock,goldStock=TubularBellsMaker.goldStock,jewelStock=TubularBellsMaker.jewelStock,pearlStock=TubularBellsMaker.pearlStock,productStock=TubularBellsMaker.productStock,numBuildings=#TubularBellsMaker.buildings,hasMaker=TubularBellsMaker.maker~=nil,makerName=TubularBellsMaker.maker and TubularBellsMaker.maker.name or "—",makerSkill=TubularBellsMaker.maker and TubularBellsMaker.maker.skill or 0,activeMaking=#TubularBellsMaker.activeMaking,totalProducts=TubularBellsMaker.totalProducts} end
return TubularBellsMaker
