local LuteMaker = {}
local PRODUCTS = {
    student_lute = { name = "Učenci lutnja", woodCost = 2, gutCost = 2, time = 2, cost = 35, soundQuality = 8, prestige = 1, description = "Preprosta lutnja za učence." },
    alto_lute = { name = "Alt lutnja", woodCost = 3, gutCost = 4, time = 4, cost = 110, soundQuality = 12, prestige = 3, description = "Alt lutnja z 6 zbori." },
    tenor_lute = { name = "Tenor lutnja", woodCost = 4, gutCost = 6, time = 6, cost = 280, soundQuality = 16, prestige = 6, happiness = 1, description = "Tenor lutnja za zborovsko glasbo." },
    theorbo = { name = "Teorba", woodCost = 5, gutCost = 8, time = 8, cost = 600, soundQuality = 20, prestige = 11, happiness = 2, description = "Teorba z dolgim vratom in basovimi strunami." },
    archlute = { name = "Arhilutnja", woodCost = 5, gutCost = 10, time = 10, cost = 1200, soundQuality = 26, prestige = 18, happiness = 4, description = "Arhilutnja za slovesne dvorne koncerte." },
    royal_pandora = { name = "Kraljevska pandora", woodCost = 6, goldCost = 1, silverCost = 1, gutCost = 12, pearlCost = 1, time = 14, cost = 2400, soundQuality = 38, prestige = 50, happiness = 10, description = "Kraljevska pandora z biseri in zlatim okovjem za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Lutnjarska delavnica", cost = { gold = 270, wood = 140 }, upkeep = 7, qualityBonus = 5 },
    stringing_room = { name = "Strunarska soba", cost = { gold = 850, wood = 240, stone = 200, gut = 8 }, upkeep = 20, qualityBonus = 18 },
    sounding_room = { name = "Zvočna soba", cost = { gold = 1800, wood = 300, stone = 400, silver = 25, wood2 = 8 }, upkeep = 42, qualityBonus = 30 },
    royal_lute_atelier = { name = "Kraljevski atelje lutnje", cost = { gold = 7000, wood = 600, stone = 800, gold = 50, gut = 20 }, upkeep = 130, qualityBonus = 55, prestigeBonus = 33 },
}
LuteMaker.woodStock = 18; LuteMaker.gutStock = 14; LuteMaker.goldStock = 6; LuteMaker.silverStock = 6; LuteMaker.pearlStock = 4
LuteMaker.productStock = {}; LuteMaker.buildings = {}; LuteMaker.maker = nil; LuteMaker.activeMaking = {}; LuteMaker.totalProducts = 0; LuteMaker.dayTimer = 0
function LuteMaker.init() LuteMaker.woodStock=18; LuteMaker.gutStock=14; LuteMaker.goldStock=6; LuteMaker.silverStock=6; LuteMaker.pearlStock=4; LuteMaker.productStock={}; LuteMaker.buildings={}; LuteMaker.maker=nil; LuteMaker.activeMaking={}; LuteMaker.totalProducts=0; LuteMaker.dayTimer=0; print("[LuteMaker] Royal Lute Maker System initialized (6 products, 4 buildings)") end
function LuteMaker.hireMaker(n,s) s=s or math.random(50,90); local c=490+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LuteMaker.maker={name=n or ("Lutnjar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lutnjar najet: %s (spretnost: %d)",LuteMaker.maker.name,s),"success") end; return true end
function LuteMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LuteMaker.build(id) local ok,e=LuteMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LuteMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LuteMaker.getQualityBonus() local b=0; for _,bd in ipairs(LuteMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LuteMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and LuteMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.gutCost and LuteMaker.gutStock<(d.gutCost or 0) then return false,"Premalo črevesja" end; if d.goldCost and LuteMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.silverCost and LuteMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.pearlCost and LuteMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #LuteMaker.buildings==0 then return false,"Potrebna delavnica" end; if not LuteMaker.maker then return false,"Potreben lutnjar" end; return true end
function LuteMaker.make(pt,qty) qty=qty or 1; local ok,e=LuteMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then LuteMaker.woodStock=LuteMaker.woodStock-d.woodCost*qty end; if d.gutCost then LuteMaker.gutStock=LuteMaker.gutStock-d.gutCost*qty end; if d.goldCost then LuteMaker.goldStock=LuteMaker.goldStock-d.goldCost*qty end; if d.silverCost then LuteMaker.silverStock=LuteMaker.silverStock-d.silverCost*qty end; if d.pearlCost then LuteMaker.pearlStock=LuteMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if LuteMaker.maker then t=math.max(1,t-math.floor(LuteMaker.maker.skill/12)) end; table.insert(LuteMaker.activeMaking,{id="lute_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,soundQuality=d.soundQuality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LuteMaker.completeMaking(m) local q=1.0+(LuteMaker.getQualityBonus()/100); if LuteMaker.maker then q=q+(LuteMaker.maker.skill/180) end; q=math.min(2.0,q); LuteMaker.productStock[m.productType]=(LuteMaker.productStock[m.productType] or 0)+m.quantity; LuteMaker.totalProducts=LuteMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LuteMaker.maker then LuteMaker.maker.itemsMade=LuteMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then LuteMaker.maker.skill=math.min(100,LuteMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lutnja izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"lute.completed",{productName=m.productName,soundQuality=m.soundQuality}) end end
function LuteMaker.update(dt) if not _G.state then return end; LuteMaker.dayTimer=LuteMaker.dayTimer+dt; if LuteMaker.dayTimer>=30 then LuteMaker.dayTimer=0; for i=#LuteMaker.activeMaking,1,-1 do local m=LuteMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LuteMaker.completeMaking(m); table.remove(LuteMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LuteMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LuteMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LuteMaker.getStats() return {woodStock=LuteMaker.woodStock,gutStock=LuteMaker.gutStock,goldStock=LuteMaker.goldStock,silverStock=LuteMaker.silverStock,pearlStock=LuteMaker.pearlStock,productStock=LuteMaker.productStock,numBuildings=#LuteMaker.buildings,hasMaker=LuteMaker.maker~=nil,makerName=LuteMaker.maker and LuteMaker.maker.name or "—",makerSkill=LuteMaker.maker and LuteMaker.maker.skill or 0,activeMaking=#LuteMaker.activeMaking,totalProducts=LuteMaker.totalProducts} end
return LuteMaker
