local PipeTaborMaker = {}
local PRODUCTS = {
    peasant_pipe = { name = "Kmečka piščal", woodCost = 1, time = 1, cost = 10, soundQuality = 7, prestige = 1, description = "Preprosta kmečka piščal." },
    three_hole_pipe = { name = "Trojnična piščal", woodCost = 1, brassCost = 1, time = 2, cost = 30, soundQuality = 10, prestige = 2, description = "Trojnična piščal za enoročno igro." },
    tabor_pipe = { name = "Tabor piščal", woodCost = 2, brassCost = 1, time = 4, cost = 80, soundQuality = 14, prestige = 4, happiness = 1, description = "Tabor piščal za par s tabor bobnom." },
    tenor_pipe = { name = "Tenor piščal", woodCost = 2, silverCost = 1, brassCost = 1, time = 6, cost = 200, soundQuality = 18, prestige = 7, happiness = 2, description = "Tenor piščal z močnim zvokom." },
    silver_pipe = { name = "Srebrna piščal", woodCost = 2, silverCost = 2, time = 8, cost = 480, soundQuality = 22, prestige = 12, happiness = 3, description = "Srebrna piščal za plemiške dvorane." },
    royal_pipe_tabor_set = { name = "Kraljevski komplet piščal in bobna", woodCost = 3, goldCost = 1, silverCost = 1, ivoryCost = 1, leatherCost = 1, pearlCost = 1, time = 13, cost = 1700, soundQuality = 35, prestige = 45, happiness = 9, description = "Veliki kraljevski komplet piščal in tabor bobna z zlatim, slonokoščenim in bisernim okovjem." },
}
local BUILDINGS = {
    workshop = { name = "Piščalna delavnica", cost = { gold = 240, wood = 120 }, upkeep = 6, qualityBonus = 5 },
    boring_room = { name = "Vrtalnica", cost = { gold = 750, wood = 220, stone = 200, brass = 6 }, upkeep = 18, qualityBonus = 18 },
    finishing_room = { name = "Dokončevalnica", cost = { gold = 1700, wood = 280, stone = 350, silver = 25, ivory = 8 }, upkeep = 40, qualityBonus = 30 },
    royal_pipe_atelier = { name = "Kraljevski atelje piščali", cost = { gold = 6500, wood = 500, stone = 700, gold = 50, ivory = 20 }, upkeep = 120, qualityBonus = 55, prestigeBonus = 30 },
}
PipeTaborMaker.woodStock = 14; PipeTaborMaker.brassStock = 8; PipeTaborMaker.silverStock = 6; PipeTaborMaker.goldStock = 6; PipeTaborMaker.ivoryStock = 6; PipeTaborMaker.leatherStock = 10; PipeTaborMaker.pearlStock = 4
PipeTaborMaker.productStock = {}; PipeTaborMaker.buildings = {}; PipeTaborMaker.maker = nil; PipeTaborMaker.activeMaking = {}; PipeTaborMaker.totalProducts = 0; PipeTaborMaker.dayTimer = 0
function PipeTaborMaker.init() PipeTaborMaker.woodStock=14; PipeTaborMaker.brassStock=8; PipeTaborMaker.silverStock=6; PipeTaborMaker.goldStock=6; PipeTaborMaker.ivoryStock=6; PipeTaborMaker.leatherStock=10; PipeTaborMaker.pearlStock=4; PipeTaborMaker.productStock={}; PipeTaborMaker.buildings={}; PipeTaborMaker.maker=nil; PipeTaborMaker.activeMaking={}; PipeTaborMaker.totalProducts=0; PipeTaborMaker.dayTimer=0; print("[PipeTaborMaker] Royal Pipe & Tabor Maker System initialized (6 products, 4 buildings)") end
function PipeTaborMaker.hireMaker(n,s) s=s or math.random(50,90); local c=460+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PipeTaborMaker.maker={name=n or ("Piščalar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Piščalar najet: %s (spretnost: %d)",PipeTaborMaker.maker.name,s),"success") end; return true end
function PipeTaborMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PipeTaborMaker.build(id) local ok,e=PipeTaborMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PipeTaborMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PipeTaborMaker.getQualityBonus() local b=0; for _,bd in ipairs(PipeTaborMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PipeTaborMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and PipeTaborMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.brassCost and PipeTaborMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and PipeTaborMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PipeTaborMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.ivoryCost and PipeTaborMaker.ivoryStock<(d.ivoryCost or 0) then return false,"Premalo slonovine" end; if d.leatherCost and PipeTaborMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.pearlCost and PipeTaborMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PipeTaborMaker.buildings==0 then return false,"Potrebna delavnica" end; if not PipeTaborMaker.maker then return false,"Potreben piščalar" end; return true end
function PipeTaborMaker.make(pt,qty) qty=qty or 1; local ok,e=PipeTaborMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then PipeTaborMaker.woodStock=PipeTaborMaker.woodStock-d.woodCost*qty end; if d.brassCost then PipeTaborMaker.brassStock=PipeTaborMaker.brassStock-d.brassCost*qty end; if d.silverCost then PipeTaborMaker.silverStock=PipeTaborMaker.silverStock-d.silverCost*qty end; if d.goldCost then PipeTaborMaker.goldStock=PipeTaborMaker.goldStock-d.goldCost*qty end; if d.ivoryCost then PipeTaborMaker.ivoryStock=PipeTaborMaker.ivoryStock-d.ivoryCost*qty end; if d.leatherCost then PipeTaborMaker.leatherStock=PipeTaborMaker.leatherStock-d.leatherCost*qty end; if d.pearlCost then PipeTaborMaker.pearlStock=PipeTaborMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PipeTaborMaker.maker then t=math.max(1,t-math.floor(PipeTaborMaker.maker.skill/12)) end; table.insert(PipeTaborMaker.activeMaking,{id="pipetabor_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,soundQuality=d.soundQuality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PipeTaborMaker.completeMaking(m) local q=1.0+(PipeTaborMaker.getQualityBonus()/100); if PipeTaborMaker.maker then q=q+(PipeTaborMaker.maker.skill/180) end; q=math.min(2.0,q); PipeTaborMaker.productStock[m.productType]=(PipeTaborMaker.productStock[m.productType] or 0)+m.quantity; PipeTaborMaker.totalProducts=PipeTaborMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PipeTaborMaker.maker then PipeTaborMaker.maker.itemsMade=PipeTaborMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then PipeTaborMaker.maker.skill=math.min(100,PipeTaborMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Piščal izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"pipetabor.completed",{productName=m.productName,soundQuality=m.soundQuality}) end end
function PipeTaborMaker.update(dt) if not _G.state then return end; PipeTaborMaker.dayTimer=PipeTaborMaker.dayTimer+dt; if PipeTaborMaker.dayTimer>=30 then PipeTaborMaker.dayTimer=0; for i=#PipeTaborMaker.activeMaking,1,-1 do local m=PipeTaborMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PipeTaborMaker.completeMaking(m); table.remove(PipeTaborMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PipeTaborMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PipeTaborMaker.maker then tu=tu+12 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PipeTaborMaker.getStats() return {woodStock=PipeTaborMaker.woodStock,brassStock=PipeTaborMaker.brassStock,silverStock=PipeTaborMaker.silverStock,goldStock=PipeTaborMaker.goldStock,ivoryStock=PipeTaborMaker.ivoryStock,leatherStock=PipeTaborMaker.leatherStock,pearlStock=PipeTaborMaker.pearlStock,productStock=PipeTaborMaker.productStock,numBuildings=#PipeTaborMaker.buildings,hasMaker=PipeTaborMaker.maker~=nil,makerName=PipeTaborMaker.maker and PipeTaborMaker.maker.name or "—",makerSkill=PipeTaborMaker.maker and PipeTaborMaker.maker.skill or 0,activeMaking=#PipeTaborMaker.activeMaking,totalProducts=PipeTaborMaker.totalProducts} end
return PipeTaborMaker
