local TorchHolderMaker = {}
local PRODUCTS = {
    simple_iron_torch_holder = { name = "Preprost železen bakloderžalec", ironCost = 2, woodCost = 1, time = 3, cost = 50, lightRadius = 25, happiness = 1, description = "Preprost železen bakloderžalec za zidove." },
    brass_torch_holder = { name = "Medeninast bakloderžalec", brassCost = 2, ironCost = 1, woodCost = 1, time = 5, cost = 130, lightRadius = 38, happiness = 1, prestige = 2, description = "Medeninast bakloderžalec za trgovce." },
    silver_trimmed_torch_holder = { name = "Srebrnoobrobljeni bakloderžalec", silverCost = 1, brassCost = 2, ironCost = 1, woodCost = 1, time = 8, cost = 320, lightRadius = 50, happiness = 2, prestige = 6, description = "Srebrnoobrobljeni bakloderžalec za plemiče." },
    gold_trimmed_torch_holder = { name = "Zlatookrasni bakloderžalec", goldCost = 1, silverCost = 1, brassCost = 2, ironCost = 1, woodCost = 1, time = 12, cost = 760, lightRadius = 62, happiness = 3, prestige = 14, description = "Zlatookrasni bakloderžalec za visoke plemiče." },
    jewel_set_torch_holder = { name = "Draguljasta bakloderžalec", goldCost = 1, silverCost = 1, brassCost = 2, ironCost = 1, woodCost = 1, jewelCost = 1, time = 16, cost = 1700, lightRadius = 76, happiness = 5, prestige = 27, description = "Bakloderžalec z draguljem za visoko plemstvo." },
    royal_grand_torch_holder = { name = "Kraljevski veliki bakloderžalec", goldCost = 2, silverCost = 2, brassCost = 2, ironCost = 1, woodCost = 1, jewelCost = 2, pearlCost = 2, time = 23, cost = 3900, lightRadius = 92, happiness = 12, prestige = 58, description = "Veliki kraljevski bakloderžalec z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    torch_holder_workshop = { name = "Bakloderžalna delavnica", cost = { gold = 240, wood = 120, stone = 120, iron = 6, brass = 6 }, upkeep = 5, qualityBonus = 5 },
    lighting_loft = { name = "Razsvetljena podstrešje", cost = { gold = 880, wood = 240, stone = 240, silver = 6, brass = 8 }, upkeep = 20, qualityBonus = 18 },
    master_holder_atelier = { name = "Mojstrski deržalni atelje", cost = { gold = 2500, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 58, qualityBonus = 30 },
    royal_lighting_palace = { name = "Kraljevska razsvetljenska palača", cost = { gold = 10500, wood = 580, stone = 760, gold = 65, jewel = 16 }, upkeep = 210, qualityBonus = 55, prestigeBonus = 50 },
}
TorchHolderMaker.ironStock = 14; TorchHolderMaker.woodStock = 10; TorchHolderMaker.brassStock = 14; TorchHolderMaker.silverStock = 6; TorchHolderMaker.goldStock = 6; TorchHolderMaker.jewelStock = 4; TorchHolderMaker.pearlStock = 4
TorchHolderMaker.productStock = {}; TorchHolderMaker.buildings = {}; TorchHolderMaker.maker = nil; TorchHolderMaker.activeMaking = {}; TorchHolderMaker.totalProducts = 0; TorchHolderMaker.dayTimer = 0
function TorchHolderMaker.init() TorchHolderMaker.ironStock=14; TorchHolderMaker.woodStock=10; TorchHolderMaker.brassStock=14; TorchHolderMaker.silverStock=6; TorchHolderMaker.goldStock=6; TorchHolderMaker.jewelStock=4; TorchHolderMaker.pearlStock=4; TorchHolderMaker.productStock={}; TorchHolderMaker.buildings={}; TorchHolderMaker.maker=nil; TorchHolderMaker.activeMaking={}; TorchHolderMaker.totalProducts=0; TorchHolderMaker.dayTimer=0; print("[TorchHolderMaker] Royal Torch Holder Maker System initialized (6 products, 4 buildings)") end
function TorchHolderMaker.hireMaker(n,s) s=s or math.random(55,90); local c=520+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TorchHolderMaker.maker={name=n or ("Bakloderžar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Bakloderžar najet: %s (spretnost: %d)",TorchHolderMaker.maker.name,s),"success") end; return true end
function TorchHolderMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TorchHolderMaker.build(id) local ok,e=TorchHolderMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TorchHolderMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TorchHolderMaker.getQualityBonus() local b=0; for _,bd in ipairs(TorchHolderMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TorchHolderMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and TorchHolderMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.woodCost and TorchHolderMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.brassCost and TorchHolderMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and TorchHolderMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and TorchHolderMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and TorchHolderMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and TorchHolderMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #TorchHolderMaker.buildings==0 then return false,"Potrebna bakloderžalna delavnica" end; if not TorchHolderMaker.maker then return false,"Potreben bakloderžar" end; return true end
function TorchHolderMaker.make(pt,qty) qty=qty or 1; local ok,e=TorchHolderMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then TorchHolderMaker.ironStock=TorchHolderMaker.ironStock-d.ironCost*qty end; if d.woodCost then TorchHolderMaker.woodStock=TorchHolderMaker.woodStock-d.woodCost*qty end; if d.brassCost then TorchHolderMaker.brassStock=TorchHolderMaker.brassStock-d.brassCost*qty end; if d.silverCost then TorchHolderMaker.silverStock=TorchHolderMaker.silverStock-d.silverCost*qty end; if d.goldCost then TorchHolderMaker.goldStock=TorchHolderMaker.goldStock-d.goldCost*qty end; if d.jewelCost then TorchHolderMaker.jewelStock=TorchHolderMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then TorchHolderMaker.pearlStock=TorchHolderMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if TorchHolderMaker.maker then t=math.max(1,t-math.floor(TorchHolderMaker.maker.skill/13)) end; table.insert(TorchHolderMaker.activeMaking,{id="torchholder_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,lightRadius=d.lightRadius or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TorchHolderMaker.completeMaking(m) local q=1.0+(TorchHolderMaker.getQualityBonus()/100); if TorchHolderMaker.maker then q=q+(TorchHolderMaker.maker.skill/140) end; q=math.min(2.5,q); TorchHolderMaker.productStock[m.productType]=(TorchHolderMaker.productStock[m.productType] or 0)+m.quantity; TorchHolderMaker.totalProducts=TorchHolderMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if TorchHolderMaker.maker then TorchHolderMaker.maker.itemsMade=TorchHolderMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then TorchHolderMaker.maker.skill=math.min(100,TorchHolderMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Bakloderžalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"torchholder.completed",{productName=m.productName,lightRadius=m.lightRadius,prestige=m.prestige,happiness=m.happiness}) end end
function TorchHolderMaker.update(dt) if not _G.state then return end; TorchHolderMaker.dayTimer=TorchHolderMaker.dayTimer+dt; if TorchHolderMaker.dayTimer>=30 then TorchHolderMaker.dayTimer=0; for i=#TorchHolderMaker.activeMaking,1,-1 do local m=TorchHolderMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TorchHolderMaker.completeMaking(m); table.remove(TorchHolderMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TorchHolderMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TorchHolderMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TorchHolderMaker.getStats() return {ironStock=TorchHolderMaker.ironStock,woodStock=TorchHolderMaker.woodStock,brassStock=TorchHolderMaker.brassStock,silverStock=TorchHolderMaker.silverStock,goldStock=TorchHolderMaker.goldStock,jewelStock=TorchHolderMaker.jewelStock,pearlStock=TorchHolderMaker.pearlStock,productStock=TorchHolderMaker.productStock,numBuildings=#TorchHolderMaker.buildings,hasMaker=TorchHolderMaker.maker~=nil,makerName=TorchHolderMaker.maker and TorchHolderMaker.maker.name or "—",makerSkill=TorchHolderMaker.maker and TorchHolderMaker.maker.skill or 0,activeMaking=#TorchHolderMaker.activeMaking,totalProducts=TorchHolderMaker.totalProducts} end
return TorchHolderMaker
