local QuenchTankStirrerMaker = {}
local PRODUCTS = {
    iron_quenchtankstirrer = { name = "Železni mešalo za kalilne kadi", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni mešalo za kalilne kadi za kovace." },
    bronze_quenchtankstirrer = { name = "Bronast mešalo za kalilne kadi", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast mešalo za kalilne kadi za kovace." },
    silver_quenchtankstirrer = { name = "Srebrn mešalo za kalilne kadi", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn mešalo za kalilne kadi za kovace." },
    gilded_quenchtankstirrer = { name = "Pozlačen mešalo za kalilne kadi", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen mešalo za kalilne kadi za kovace." },
    jewel_set_quenchtankstirrer = { name = "Draguljast mešalo za kalilne kadi", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast mešalo za kalilne kadi za kovace." },
    royal_sovereign_quenchtankstirrer = { name = "Kraljevski suveren mešalo za kalilne kadi", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren mešalo za kalilne kadi z biseri za krono." },
}
local BUILDINGS = {
    quenchtankstirrer_workshop = { name = "Quenchtankstirrer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    quenchtankstirrer_house = { name = "Quenchtankstirrer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_quenchtankstirrer_atelier = { name = "Mojstrski quenchtankstirrer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_quenchtankstirrer_palace = { name = "Suverena quenchtankstirrer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
QuenchTankStirrerMaker.ironStock=16; QuenchTankStirrerMaker.bronzeStock=12; QuenchTankStirrerMaker.woodStock=12; QuenchTankStirrerMaker.leatherStock=8; QuenchTankStirrerMaker.silverStock=8; QuenchTankStirrerMaker.goldStock=6; QuenchTankStirrerMaker.jewelStock=4; QuenchTankStirrerMaker.pearlStock=4
QuenchTankStirrerMaker.productStock = {}; QuenchTankStirrerMaker.buildings = {}; QuenchTankStirrerMaker.maker = nil; QuenchTankStirrerMaker.activeMaking = {}; QuenchTankStirrerMaker.totalProducts = 0; QuenchTankStirrerMaker.dayTimer = 0
function QuenchTankStirrerMaker.init() QuenchTankStirrerMaker.ironStock=16; QuenchTankStirrerMaker.bronzeStock=12; QuenchTankStirrerMaker.woodStock=12; QuenchTankStirrerMaker.leatherStock=8; QuenchTankStirrerMaker.silverStock=8; QuenchTankStirrerMaker.goldStock=6; QuenchTankStirrerMaker.jewelStock=4; QuenchTankStirrerMaker.pearlStock=4; QuenchTankStirrerMaker.productStock={}; QuenchTankStirrerMaker.buildings={}; QuenchTankStirrerMaker.maker=nil; QuenchTankStirrerMaker.activeMaking={}; QuenchTankStirrerMaker.totalProducts=0; QuenchTankStirrerMaker.dayTimer=0; print("[QuenchTankStirrerMaker] Royal Quench Tank Stirrer Maker System initialized (6 products, 4 buildings)") end
function QuenchTankStirrerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; QuenchTankStirrerMaker.maker={name=n or ("Mešalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mešalnik najet: %s (spretnost: %d)",QuenchTankStirrerMaker.maker.name,s),"success") end; return true end
function QuenchTankStirrerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function QuenchTankStirrerMaker.build(id) local ok,e=QuenchTankStirrerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(QuenchTankStirrerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function QuenchTankStirrerMaker.getQualityBonus() local b=0; for _,bd in ipairs(QuenchTankStirrerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function QuenchTankStirrerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and QuenchTankStirrerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and QuenchTankStirrerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and QuenchTankStirrerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and QuenchTankStirrerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and QuenchTankStirrerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and QuenchTankStirrerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and QuenchTankStirrerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and QuenchTankStirrerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #QuenchTankStirrerMaker.buildings==0 then return false,"Potrebna mešalna delavnica" end; if not QuenchTankStirrerMaker.maker then return false,"Potreben mesalnik" end; return true end
function QuenchTankStirrerMaker.make(pt,qty) qty=qty or 1; local ok,e=QuenchTankStirrerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then QuenchTankStirrerMaker.ironStock=QuenchTankStirrerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then QuenchTankStirrerMaker.bronzeStock=QuenchTankStirrerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then QuenchTankStirrerMaker.woodStock=QuenchTankStirrerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then QuenchTankStirrerMaker.leatherStock=QuenchTankStirrerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then QuenchTankStirrerMaker.silverStock=QuenchTankStirrerMaker.silverStock-d.silverCost*qty end; if d.goldCost then QuenchTankStirrerMaker.goldStock=QuenchTankStirrerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then QuenchTankStirrerMaker.jewelStock=QuenchTankStirrerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then QuenchTankStirrerMaker.pearlStock=QuenchTankStirrerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if QuenchTankStirrerMaker.maker then t=math.max(1,t-math.floor(QuenchTankStirrerMaker.maker.skill/13)) end; table.insert(QuenchTankStirrerMaker.activeMaking,{id="quenchtankstirrer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function QuenchTankStirrerMaker.completeMaking(m) local q=1.0+(QuenchTankStirrerMaker.getQualityBonus()/100); if QuenchTankStirrerMaker.maker then q=q+(QuenchTankStirrerMaker.maker.skill/140) end; q=math.min(2.5,q); QuenchTankStirrerMaker.productStock[m.productType]=(QuenchTankStirrerMaker.productStock[m.productType] or 0)+m.quantity; QuenchTankStirrerMaker.totalProducts=QuenchTankStirrerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if QuenchTankStirrerMaker.maker then QuenchTankStirrerMaker.maker.itemsMade=QuenchTankStirrerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then QuenchTankStirrerMaker.maker.skill=math.min(100,QuenchTankStirrerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mešalo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"quenchtankstirrer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function QuenchTankStirrerMaker.update(dt) if not _G.state then return end; QuenchTankStirrerMaker.dayTimer=QuenchTankStirrerMaker.dayTimer+dt; if QuenchTankStirrerMaker.dayTimer>=30 then QuenchTankStirrerMaker.dayTimer=0; for i=#QuenchTankStirrerMaker.activeMaking,1,-1 do local m=QuenchTankStirrerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then QuenchTankStirrerMaker.completeMaking(m); table.remove(QuenchTankStirrerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(QuenchTankStirrerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if QuenchTankStirrerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function QuenchTankStirrerMaker.getStats() return {ironStock=QuenchTankStirrerMaker.ironStock,bronzeStock=QuenchTankStirrerMaker.bronzeStock,woodStock=QuenchTankStirrerMaker.woodStock,leatherStock=QuenchTankStirrerMaker.leatherStock,silverStock=QuenchTankStirrerMaker.silverStock,goldStock=QuenchTankStirrerMaker.goldStock,jewelStock=QuenchTankStirrerMaker.jewelStock,pearlStock=QuenchTankStirrerMaker.pearlStock,productStock=QuenchTankStirrerMaker.productStock,numBuildings=#QuenchTankStirrerMaker.buildings,hasMaker=QuenchTankStirrerMaker.maker~=nil,makerName=QuenchTankStirrerMaker.maker and QuenchTankStirrerMaker.maker.name or "—",makerSkill=QuenchTankStirrerMaker.maker and QuenchTankStirrerMaker.maker.skill or 0,activeMaking=#QuenchTankStirrerMaker.activeMaking,totalProducts=QuenchTankStirrerMaker.totalProducts} end
return QuenchTankStirrerMaker
