local ButtonMaker = {}
local PRODUCTS = {
    wooden_button = { name = "Leseni gumb", woodCost = 1, time = 1, cost = 2, quantity = 20, description = "Preprosti leseni gumbi." },
    bone_button = { name = "Kosten gumb", boneCost = 1, time = 2, cost = 5, quantity = 15, description = "Gumbi iz kosti." },
    metal_button = { name = "Kovinski gumb", metalCost = 1, time = 2, cost = 8, quantity = 15, description = "Kovinski gumbi." },
    silver_buckle = { name = "Srebrna spona", silverCost = 1, time = 4, cost = 50, prestige = 3, description = "Srebrna spona za pas." },
    gold_buckle = { name = "Zlata spona", goldCost = 1, jewelCost = 1, time = 7, cost = 200, prestige = 10, description = "Zlata spona z drago kamen." },
    royal_button = { name = "Kraljevski gumb", goldCost = 1, jewelCost = 1, time = 5, cost = 150, quantity = 5, prestige = 8, happiness = 3, description = "Gumbi za kraljevska oblačila." },
}
local BUILDINGS = {
    workshop = { name = "Gumbarska delavnica", cost = { gold = 150, wood = 100 }, upkeep = 3, qualityBonus = 5 },
    button_shop = { name = "Gumbarna", cost = { gold = 500, wood = 200, stone = 100 }, upkeep = 12, qualityBonus = 15 },
    metal_shop = { name = "Kovinska delavnica", cost = { gold = 1000, wood = 200, stone = 200, iron = 50 }, upkeep = 25, qualityBonus = 20 },
    royal_buttoner = { name = "Kraljevski gumbar", cost = { gold = 3000, wood = 400, stone = 600, gold = 50 }, upkeep = 60, qualityBonus = 35, prestigeBonus = 15 },
}
ButtonMaker.woodStock = 15; ButtonMaker.boneStock = 5; ButtonMaker.metalStock = 8; ButtonMaker.silverStock = 3; ButtonMaker.goldStock = 3; ButtonMaker.jewelStock = 2
ButtonMaker.productStock = {}; ButtonMaker.buildings = {}; ButtonMaker.maker = nil; ButtonMaker.activeMaking = {}; ButtonMaker.totalProducts = 0; ButtonMaker.dayTimer = 0
function ButtonMaker.init() ButtonMaker.woodStock=15; ButtonMaker.boneStock=5; ButtonMaker.metalStock=8; ButtonMaker.silverStock=3; ButtonMaker.goldStock=3; ButtonMaker.jewelStock=2; ButtonMaker.productStock={}; ButtonMaker.buildings={}; ButtonMaker.maker=nil; ButtonMaker.activeMaking={}; ButtonMaker.totalProducts=0; ButtonMaker.dayTimer=0; print("[ButtonMaker] Royal Button & Buckle Maker System initialized (6 products, 4 buildings)") end
function ButtonMaker.hireMaker(n,s) s=s or math.random(35,75); local c=200+s*4; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ButtonMaker.maker={name=n or ("Gumbar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gumbar najet: %s (spretnost: %d)",ButtonMaker.maker.name,s),"success") end; return true end
function ButtonMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ButtonMaker.build(id) local ok,e=ButtonMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ButtonMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ButtonMaker.getQualityBonus() local b=0; for _,bd in ipairs(ButtonMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ButtonMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and ButtonMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.boneCost and ButtonMaker.boneStock<(d.boneCost or 0) then return false,"Premalo kosti" end; if d.metalCost and ButtonMaker.metalStock<(d.metalCost or 0) then return false,"Premalo kovine" end; if d.silverCost and ButtonMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ButtonMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ButtonMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo dragih kamnov" end; if #ButtonMaker.buildings==0 then return false,"Potrebna delavnica" end; if not ButtonMaker.maker then return false,"Potreben gumbar" end; return true end
function ButtonMaker.make(pt) local ok,e=ButtonMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then ButtonMaker.woodStock=ButtonMaker.woodStock-d.woodCost end; if d.boneCost then ButtonMaker.boneStock=ButtonMaker.boneStock-d.boneCost end; if d.metalCost then ButtonMaker.metalStock=ButtonMaker.metalStock-d.metalCost end; if d.silverCost then ButtonMaker.silverStock=ButtonMaker.silverStock-d.silverCost end; if d.goldCost then ButtonMaker.goldStock=ButtonMaker.goldStock-d.goldCost end; if d.jewelCost then ButtonMaker.jewelStock=ButtonMaker.jewelStock-d.jewelCost end; local t=d.time; if ButtonMaker.maker then t=math.max(1,t-math.floor(ButtonMaker.maker.skill/15)) end; table.insert(ButtonMaker.activeMaking,{id="btn_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost,quantity=d.quantity or 1,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %s (%d dni)",d.name,t),"info") end; return true end
function ButtonMaker.completeMaking(m) local q=1.0+(ButtonMaker.getQualityBonus()/100); if ButtonMaker.maker then q=q+(ButtonMaker.maker.skill/200) end; q=math.min(2.0,q); ButtonMaker.productStock[m.productType]=(ButtonMaker.productStock[m.productType] or 0)+m.quantity; ButtonMaker.totalProducts=ButtonMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ButtonMaker.maker then ButtonMaker.maker.itemsMade=ButtonMaker.maker.itemsMade+m.quantity; if math.random()<0.15 then ButtonMaker.maker.skill=math.min(100,ButtonMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gumbi izdelani: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end end
function ButtonMaker.update(dt) if not _G.state then return end; ButtonMaker.dayTimer=ButtonMaker.dayTimer+dt; if ButtonMaker.dayTimer>=30 then ButtonMaker.dayTimer=0; for i=#ButtonMaker.activeMaking,1,-1 do local m=ButtonMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ButtonMaker.completeMaking(m); table.remove(ButtonMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ButtonMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ButtonMaker.maker then tu=tu+5 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ButtonMaker.getStats() return {woodStock=ButtonMaker.woodStock,boneStock=ButtonMaker.boneStock,metalStock=ButtonMaker.metalStock,silverStock=ButtonMaker.silverStock,goldStock=ButtonMaker.goldStock,productStock=ButtonMaker.productStock,numBuildings=#ButtonMaker.buildings,hasMaker=ButtonMaker.maker~=nil,makerName=ButtonMaker.maker and ButtonMaker.maker.name or "—",makerSkill=ButtonMaker.maker and ButtonMaker.maker.skill or 0,activeMaking=#ButtonMaker.activeMaking,totalProducts=ButtonMaker.totalProducts} end
return ButtonMaker
