local PouringLadleLinerMaker = {}
local PRODUCTS = {
    iron_pouringladleliner = { name = "Železni obloga za zajemalke", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni obloga za zajemalke za livarje." },
    bronze_pouringladleliner = { name = "Bronast obloga za zajemalke", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast obloga za zajemalke za livarje." },
    silver_pouringladleliner = { name = "Srebrn obloga za zajemalke", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn obloga za zajemalke za livarje." },
    gilded_pouringladleliner = { name = "Pozlačen obloga za zajemalke", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen obloga za zajemalke za livarje." },
    jewel_set_pouringladleliner = { name = "Draguljast obloga za zajemalke", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast obloga za zajemalke za livarje." },
    royal_sovereign_pouringladleliner = { name = "Kraljevski suveren obloga za zajemalke", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren obloga za zajemalke z biseri za krono." },
}
local BUILDINGS = {
    pouringladleliner_workshop = { name = "Pouringladleliner delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    pouringladleliner_house = { name = "Pouringladleliner hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_pouringladleliner_atelier = { name = "Mojstrski pouringladleliner atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_pouringladleliner_palace = { name = "Suverena pouringladleliner palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
PouringLadleLinerMaker.ironStock=12; PouringLadleLinerMaker.bronzeStock=10; PouringLadleLinerMaker.woodStock=14; PouringLadleLinerMaker.leatherStock=12; PouringLadleLinerMaker.silverStock=8; PouringLadleLinerMaker.goldStock=6; PouringLadleLinerMaker.jewelStock=4; PouringLadleLinerMaker.pearlStock=4
PouringLadleLinerMaker.productStock = {}; PouringLadleLinerMaker.buildings = {}; PouringLadleLinerMaker.maker = nil; PouringLadleLinerMaker.activeMaking = {}; PouringLadleLinerMaker.totalProducts = 0; PouringLadleLinerMaker.dayTimer = 0
function PouringLadleLinerMaker.init() PouringLadleLinerMaker.ironStock=12; PouringLadleLinerMaker.bronzeStock=10; PouringLadleLinerMaker.woodStock=14; PouringLadleLinerMaker.leatherStock=12; PouringLadleLinerMaker.silverStock=8; PouringLadleLinerMaker.goldStock=6; PouringLadleLinerMaker.jewelStock=4; PouringLadleLinerMaker.pearlStock=4; PouringLadleLinerMaker.productStock={}; PouringLadleLinerMaker.buildings={}; PouringLadleLinerMaker.maker=nil; PouringLadleLinerMaker.activeMaking={}; PouringLadleLinerMaker.totalProducts=0; PouringLadleLinerMaker.dayTimer=0; print("[PouringLadleLinerMaker] Royal Pouring Ladle Liner Maker System initialized (6 products, 4 buildings)") end
function PouringLadleLinerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PouringLadleLinerMaker.maker={name=n or ("Oblogar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Oblogar najet: %s (spretnost: %d)",PouringLadleLinerMaker.maker.name,s),"success") end; return true end
function PouringLadleLinerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PouringLadleLinerMaker.build(id) local ok,e=PouringLadleLinerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PouringLadleLinerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PouringLadleLinerMaker.getQualityBonus() local b=0; for _,bd in ipairs(PouringLadleLinerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PouringLadleLinerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PouringLadleLinerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and PouringLadleLinerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and PouringLadleLinerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PouringLadleLinerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PouringLadleLinerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PouringLadleLinerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PouringLadleLinerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PouringLadleLinerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PouringLadleLinerMaker.buildings==0 then return false,"Potrebna obložna delavnica" end; if not PouringLadleLinerMaker.maker then return false,"Potreben oblogar" end; return true end
function PouringLadleLinerMaker.make(pt,qty) qty=qty or 1; local ok,e=PouringLadleLinerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PouringLadleLinerMaker.ironStock=PouringLadleLinerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then PouringLadleLinerMaker.bronzeStock=PouringLadleLinerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then PouringLadleLinerMaker.woodStock=PouringLadleLinerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PouringLadleLinerMaker.leatherStock=PouringLadleLinerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then PouringLadleLinerMaker.silverStock=PouringLadleLinerMaker.silverStock-d.silverCost*qty end; if d.goldCost then PouringLadleLinerMaker.goldStock=PouringLadleLinerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PouringLadleLinerMaker.jewelStock=PouringLadleLinerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PouringLadleLinerMaker.pearlStock=PouringLadleLinerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PouringLadleLinerMaker.maker then t=math.max(1,t-math.floor(PouringLadleLinerMaker.maker.skill/13)) end; table.insert(PouringLadleLinerMaker.activeMaking,{id="pouringladleliner_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PouringLadleLinerMaker.completeMaking(m) local q=1.0+(PouringLadleLinerMaker.getQualityBonus()/100); if PouringLadleLinerMaker.maker then q=q+(PouringLadleLinerMaker.maker.skill/140) end; q=math.min(2.5,q); PouringLadleLinerMaker.productStock[m.productType]=(PouringLadleLinerMaker.productStock[m.productType] or 0)+m.quantity; PouringLadleLinerMaker.totalProducts=PouringLadleLinerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PouringLadleLinerMaker.maker then PouringLadleLinerMaker.maker.itemsMade=PouringLadleLinerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PouringLadleLinerMaker.maker.skill=math.min(100,PouringLadleLinerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Obloga izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"pouringladleliner.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function PouringLadleLinerMaker.update(dt) if not _G.state then return end; PouringLadleLinerMaker.dayTimer=PouringLadleLinerMaker.dayTimer+dt; if PouringLadleLinerMaker.dayTimer>=30 then PouringLadleLinerMaker.dayTimer=0; for i=#PouringLadleLinerMaker.activeMaking,1,-1 do local m=PouringLadleLinerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PouringLadleLinerMaker.completeMaking(m); table.remove(PouringLadleLinerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PouringLadleLinerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PouringLadleLinerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PouringLadleLinerMaker.getStats() return {ironStock=PouringLadleLinerMaker.ironStock,bronzeStock=PouringLadleLinerMaker.bronzeStock,woodStock=PouringLadleLinerMaker.woodStock,leatherStock=PouringLadleLinerMaker.leatherStock,silverStock=PouringLadleLinerMaker.silverStock,goldStock=PouringLadleLinerMaker.goldStock,jewelStock=PouringLadleLinerMaker.jewelStock,pearlStock=PouringLadleLinerMaker.pearlStock,productStock=PouringLadleLinerMaker.productStock,numBuildings=#PouringLadleLinerMaker.buildings,hasMaker=PouringLadleLinerMaker.maker~=nil,makerName=PouringLadleLinerMaker.maker and PouringLadleLinerMaker.maker.name or "—",makerSkill=PouringLadleLinerMaker.maker and PouringLadleLinerMaker.maker.skill or 0,activeMaking=#PouringLadleLinerMaker.activeMaking,totalProducts=PouringLadleLinerMaker.totalProducts} end
return PouringLadleLinerMaker
