local SurgicalLancetMaker = {}
local PRODUCTS = {
    iron_lancet = { name = "Železna lanceta", ironCost = 2, woodCost = 1, leatherCost = 1, time = 5, cost = 150, prestige = 3, happiness = 1, description = "Železna lanceta za puščanje krvi." },
    bronze_lancet = { name = "Bronasta lanceta", bronzeCost = 2, ironCost = 1, woodCost = 1, leatherCost = 1, time = 7, cost = 360, prestige = 5, happiness = 2, description = "Bronasta lanceta za kirurga." },
    silver_lancet = { name = "Srebrna lanceta", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 11, cost = 850, prestige = 10, happiness = 3, description = "Srebrna lanceta za plemiške zdravnike." },
    gilded_lancet = { name = "Pozlačena lanceta", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 15, cost = 1820, prestige = 19, happiness = 4, description = "Pozlačena lanceta za dvornega kirurga." },
    jewel_set_lancet = { name = "Draguljasta lanceta", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 19, cost = 3920, prestige = 35, happiness = 6, description = "Draguljasta lanceta za kraljevega zdravnika." },
    royal_sovereign_lancet = { name = "Kraljevski suverena lanceta", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 26, cost = 8400, prestige = 68, happiness = 12, description = "Suverena lanceta z biseri za krono." },
}
local BUILDINGS = {
    lancet_workshop = { name = "Lancetna delavnica", cost = { gold = 340, wood = 175, stone = 135, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    lancet_house = { name = "Lancetna hiša", cost = { gold = 1220, wood = 355, stone = 270, silver = 7, iron = 7 }, upkeep = 26, qualityBonus = 18 },
    master_lancet_atelier = { name = "Mojstrski lancetni atelje", cost = { gold = 3050, wood = 415, stone = 520, silver = 35, gold = 7 }, upkeep = 72, qualityBonus = 30 },
    sovereign_surgical_palace = { name = "Suverena kirurška palača", cost = { gold = 13000, wood = 630, stone = 830, gold = 83, jewel = 19 }, upkeep = 255, qualityBonus = 55, prestigeBonus = 50 },
}
SurgicalLancetMaker.ironStock = 12; SurgicalLancetMaker.bronzeStock = 10; SurgicalLancetMaker.woodStock = 14; SurgicalLancetMaker.leatherStock = 10; SurgicalLancetMaker.silverStock = 8; SurgicalLancetMaker.goldStock = 6; SurgicalLancetMaker.jewelStock = 4; SurgicalLancetMaker.pearlStock = 4
SurgicalLancetMaker.productStock = {}; SurgicalLancetMaker.buildings = {}; SurgicalLancetMaker.maker = nil; SurgicalLancetMaker.activeMaking = {}; SurgicalLancetMaker.totalProducts = 0; SurgicalLancetMaker.dayTimer = 0
function SurgicalLancetMaker.init() SurgicalLancetMaker.ironStock=12; SurgicalLancetMaker.bronzeStock=10; SurgicalLancetMaker.woodStock=14; SurgicalLancetMaker.leatherStock=10; SurgicalLancetMaker.silverStock=8; SurgicalLancetMaker.goldStock=6; SurgicalLancetMaker.jewelStock=4; SurgicalLancetMaker.pearlStock=4; SurgicalLancetMaker.productStock={}; SurgicalLancetMaker.buildings={}; SurgicalLancetMaker.maker=nil; SurgicalLancetMaker.activeMaking={}; SurgicalLancetMaker.totalProducts=0; SurgicalLancetMaker.dayTimer=0; print("[SurgicalLancetMaker] Royal Surgical Lancet Maker System initialized (6 products, 4 buildings)") end
function SurgicalLancetMaker.hireMaker(n,s) s=s or math.random(55,90); local c=590+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SurgicalLancetMaker.maker={name=n or ("Lancetar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lancetar najet: %s (spretnost: %d)",SurgicalLancetMaker.maker.name,s),"success") end; return true end
function SurgicalLancetMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SurgicalLancetMaker.build(id) local ok,e=SurgicalLancetMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SurgicalLancetMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SurgicalLancetMaker.getQualityBonus() local b=0; for _,bd in ipairs(SurgicalLancetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SurgicalLancetMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SurgicalLancetMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SurgicalLancetMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SurgicalLancetMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SurgicalLancetMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SurgicalLancetMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SurgicalLancetMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SurgicalLancetMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SurgicalLancetMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SurgicalLancetMaker.buildings==0 then return false,"Potrebna lancetna delavnica" end; if not SurgicalLancetMaker.maker then return false,"Potreben lancetar" end; return true end
function SurgicalLancetMaker.make(pt,qty) qty=qty or 1; local ok,e=SurgicalLancetMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SurgicalLancetMaker.ironStock=SurgicalLancetMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SurgicalLancetMaker.bronzeStock=SurgicalLancetMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SurgicalLancetMaker.woodStock=SurgicalLancetMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SurgicalLancetMaker.leatherStock=SurgicalLancetMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SurgicalLancetMaker.silverStock=SurgicalLancetMaker.silverStock-d.silverCost*qty end; if d.goldCost then SurgicalLancetMaker.goldStock=SurgicalLancetMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SurgicalLancetMaker.jewelStock=SurgicalLancetMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SurgicalLancetMaker.pearlStock=SurgicalLancetMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SurgicalLancetMaker.maker then t=math.max(1,t-math.floor(SurgicalLancetMaker.maker.skill/13)) end; table.insert(SurgicalLancetMaker.activeMaking,{id="lancet_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SurgicalLancetMaker.completeMaking(m) local q=1.0+(SurgicalLancetMaker.getQualityBonus()/100); if SurgicalLancetMaker.maker then q=q+(SurgicalLancetMaker.maker.skill/140) end; q=math.min(2.5,q); SurgicalLancetMaker.productStock[m.productType]=(SurgicalLancetMaker.productStock[m.productType] or 0)+m.quantity; SurgicalLancetMaker.totalProducts=SurgicalLancetMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SurgicalLancetMaker.maker then SurgicalLancetMaker.maker.itemsMade=SurgicalLancetMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SurgicalLancetMaker.maker.skill=math.min(100,SurgicalLancetMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lanceta izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"lancet.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SurgicalLancetMaker.update(dt) if not _G.state then return end; SurgicalLancetMaker.dayTimer=SurgicalLancetMaker.dayTimer+dt; if SurgicalLancetMaker.dayTimer>=30 then SurgicalLancetMaker.dayTimer=0; for i=#SurgicalLancetMaker.activeMaking,1,-1 do local m=SurgicalLancetMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SurgicalLancetMaker.completeMaking(m); table.remove(SurgicalLancetMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SurgicalLancetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SurgicalLancetMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SurgicalLancetMaker.getStats() return {ironStock=SurgicalLancetMaker.ironStock,bronzeStock=SurgicalLancetMaker.bronzeStock,woodStock=SurgicalLancetMaker.woodStock,leatherStock=SurgicalLancetMaker.leatherStock,silverStock=SurgicalLancetMaker.silverStock,goldStock=SurgicalLancetMaker.goldStock,jewelStock=SurgicalLancetMaker.jewelStock,pearlStock=SurgicalLancetMaker.pearlStock,productStock=SurgicalLancetMaker.productStock,numBuildings=#SurgicalLancetMaker.buildings,hasMaker=SurgicalLancetMaker.maker~=nil,makerName=SurgicalLancetMaker.maker and SurgicalLancetMaker.maker.name or "—",makerSkill=SurgicalLancetMaker.maker and SurgicalLancetMaker.maker.skill or 0,activeMaking=#SurgicalLancetMaker.activeMaking,totalProducts=SurgicalLancetMaker.totalProducts} end
return SurgicalLancetMaker
