local SmithTongsJawInsertMaker = {}
local PRODUCTS = {
    iron_smithtongsjawinsert = { name = "Železni vstavki za celjusti klesce", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni vstavki za celjusti klesce za kovace." },
    bronze_smithtongsjawinsert = { name = "Bronast vstavki za celjusti klesce", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast vstavki za celjusti klesce za kovace." },
    silver_smithtongsjawinsert = { name = "Srebrn vstavki za celjusti klesce", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn vstavki za celjusti klesce za kovace." },
    gilded_smithtongsjawinsert = { name = "Pozlačen vstavki za celjusti klesce", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen vstavki za celjusti klesce za kovace." },
    jewel_set_smithtongsjawinsert = { name = "Draguljast vstavki za celjusti klesce", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast vstavki za celjusti klesce za kovace." },
    royal_sovereign_smithtongsjawinsert = { name = "Kraljevski suveren vstavki za celjusti klesce", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren vstavki za celjusti klesce z biseri za krono." },
}
local BUILDINGS = {
    smithtongsjawinsert_workshop = { name = "Smithtongsjawinsert delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    smithtongsjawinsert_house = { name = "Smithtongsjawinsert hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_smithtongsjawinsert_atelier = { name = "Mojstrski smithtongsjawinsert atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_smithtongsjawinsert_palace = { name = "Suverena smithtongsjawinsert palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SmithTongsJawInsertMaker.ironStock=18; SmithTongsJawInsertMaker.bronzeStock=14; SmithTongsJawInsertMaker.woodStock=10; SmithTongsJawInsertMaker.leatherStock=8; SmithTongsJawInsertMaker.silverStock=8; SmithTongsJawInsertMaker.goldStock=6; SmithTongsJawInsertMaker.jewelStock=4; SmithTongsJawInsertMaker.pearlStock=4
SmithTongsJawInsertMaker.productStock = {}; SmithTongsJawInsertMaker.buildings = {}; SmithTongsJawInsertMaker.maker = nil; SmithTongsJawInsertMaker.activeMaking = {}; SmithTongsJawInsertMaker.totalProducts = 0; SmithTongsJawInsertMaker.dayTimer = 0
function SmithTongsJawInsertMaker.init() SmithTongsJawInsertMaker.ironStock=18; SmithTongsJawInsertMaker.bronzeStock=14; SmithTongsJawInsertMaker.woodStock=10; SmithTongsJawInsertMaker.leatherStock=8; SmithTongsJawInsertMaker.silverStock=8; SmithTongsJawInsertMaker.goldStock=6; SmithTongsJawInsertMaker.jewelStock=4; SmithTongsJawInsertMaker.pearlStock=4; SmithTongsJawInsertMaker.productStock={}; SmithTongsJawInsertMaker.buildings={}; SmithTongsJawInsertMaker.maker=nil; SmithTongsJawInsertMaker.activeMaking={}; SmithTongsJawInsertMaker.totalProducts=0; SmithTongsJawInsertMaker.dayTimer=0; print("[SmithTongsJawInsertMaker] Royal Smith Tongs Jaw Insert Maker System initialized (6 products, 4 buildings)") end
function SmithTongsJawInsertMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SmithTongsJawInsertMaker.maker={name=n or ("Vstavljač "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vstavljač najet: %s (spretnost: %d)",SmithTongsJawInsertMaker.maker.name,s),"success") end; return true end
function SmithTongsJawInsertMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SmithTongsJawInsertMaker.build(id) local ok,e=SmithTongsJawInsertMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SmithTongsJawInsertMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SmithTongsJawInsertMaker.getQualityBonus() local b=0; for _,bd in ipairs(SmithTongsJawInsertMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SmithTongsJawInsertMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SmithTongsJawInsertMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SmithTongsJawInsertMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SmithTongsJawInsertMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SmithTongsJawInsertMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SmithTongsJawInsertMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SmithTongsJawInsertMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SmithTongsJawInsertMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SmithTongsJawInsertMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SmithTongsJawInsertMaker.buildings==0 then return false,"Potrebna vstavljalna delavnica" end; if not SmithTongsJawInsertMaker.maker then return false,"Potreben vstavljac" end; return true end
function SmithTongsJawInsertMaker.make(pt,qty) qty=qty or 1; local ok,e=SmithTongsJawInsertMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SmithTongsJawInsertMaker.ironStock=SmithTongsJawInsertMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SmithTongsJawInsertMaker.bronzeStock=SmithTongsJawInsertMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SmithTongsJawInsertMaker.woodStock=SmithTongsJawInsertMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SmithTongsJawInsertMaker.leatherStock=SmithTongsJawInsertMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SmithTongsJawInsertMaker.silverStock=SmithTongsJawInsertMaker.silverStock-d.silverCost*qty end; if d.goldCost then SmithTongsJawInsertMaker.goldStock=SmithTongsJawInsertMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SmithTongsJawInsertMaker.jewelStock=SmithTongsJawInsertMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SmithTongsJawInsertMaker.pearlStock=SmithTongsJawInsertMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SmithTongsJawInsertMaker.maker then t=math.max(1,t-math.floor(SmithTongsJawInsertMaker.maker.skill/13)) end; table.insert(SmithTongsJawInsertMaker.activeMaking,{id="smithtongsjawinsert_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SmithTongsJawInsertMaker.completeMaking(m) local q=1.0+(SmithTongsJawInsertMaker.getQualityBonus()/100); if SmithTongsJawInsertMaker.maker then q=q+(SmithTongsJawInsertMaker.maker.skill/140) end; q=math.min(2.5,q); SmithTongsJawInsertMaker.productStock[m.productType]=(SmithTongsJawInsertMaker.productStock[m.productType] or 0)+m.quantity; SmithTongsJawInsertMaker.totalProducts=SmithTongsJawInsertMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SmithTongsJawInsertMaker.maker then SmithTongsJawInsertMaker.maker.itemsMade=SmithTongsJawInsertMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SmithTongsJawInsertMaker.maker.skill=math.min(100,SmithTongsJawInsertMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vstavek izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"smithtongsjawinsert.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SmithTongsJawInsertMaker.update(dt) if not _G.state then return end; SmithTongsJawInsertMaker.dayTimer=SmithTongsJawInsertMaker.dayTimer+dt; if SmithTongsJawInsertMaker.dayTimer>=30 then SmithTongsJawInsertMaker.dayTimer=0; for i=#SmithTongsJawInsertMaker.activeMaking,1,-1 do local m=SmithTongsJawInsertMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SmithTongsJawInsertMaker.completeMaking(m); table.remove(SmithTongsJawInsertMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SmithTongsJawInsertMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SmithTongsJawInsertMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SmithTongsJawInsertMaker.getStats() return {ironStock=SmithTongsJawInsertMaker.ironStock,bronzeStock=SmithTongsJawInsertMaker.bronzeStock,woodStock=SmithTongsJawInsertMaker.woodStock,leatherStock=SmithTongsJawInsertMaker.leatherStock,silverStock=SmithTongsJawInsertMaker.silverStock,goldStock=SmithTongsJawInsertMaker.goldStock,jewelStock=SmithTongsJawInsertMaker.jewelStock,pearlStock=SmithTongsJawInsertMaker.pearlStock,productStock=SmithTongsJawInsertMaker.productStock,numBuildings=#SmithTongsJawInsertMaker.buildings,hasMaker=SmithTongsJawInsertMaker.maker~=nil,makerName=SmithTongsJawInsertMaker.maker and SmithTongsJawInsertMaker.maker.name or "—",makerSkill=SmithTongsJawInsertMaker.maker and SmithTongsJawInsertMaker.maker.skill or 0,activeMaking=#SmithTongsJawInsertMaker.activeMaking,totalProducts=SmithTongsJawInsertMaker.totalProducts} end
return SmithTongsJawInsertMaker
