local GardenHoeMaker = {}
local PRODUCTS = {
    iron_gardenhoe = { name = "Železni vrtna motika", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni vrtna motika za vrtnarje." },
    bronze_gardenhoe = { name = "Bronast vrtna motika", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast vrtna motika za vrtnarje." },
    silver_gardenhoe = { name = "Srebrn vrtna motika", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn vrtna motika za vrtnarje." },
    gilded_gardenhoe = { name = "Pozlačen vrtna motika", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen vrtna motika za vrtnarje." },
    jewel_set_gardenhoe = { name = "Draguljast vrtna motika", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast vrtna motika za vrtnarje." },
    royal_sovereign_gardenhoe = { name = "Kraljevski suveren vrtna motika", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren vrtna motika z biseri za krono." },
}
local BUILDINGS = {
    gardenhoe_workshop = { name = "Gardenhoe delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardenhoe_house = { name = "Gardenhoe hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardenhoe_atelier = { name = "Mojstrski gardenhoe atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardenhoe_palace = { name = "Suverena gardenhoe palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenHoeMaker.ironStock=16; GardenHoeMaker.bronzeStock=12; GardenHoeMaker.woodStock=14; GardenHoeMaker.leatherStock=8; GardenHoeMaker.silverStock=8; GardenHoeMaker.goldStock=6; GardenHoeMaker.jewelStock=4; GardenHoeMaker.pearlStock=4
GardenHoeMaker.productStock = {}; GardenHoeMaker.buildings = {}; GardenHoeMaker.maker = nil; GardenHoeMaker.activeMaking = {}; GardenHoeMaker.totalProducts = 0; GardenHoeMaker.dayTimer = 0
function GardenHoeMaker.init() GardenHoeMaker.ironStock=16; GardenHoeMaker.bronzeStock=12; GardenHoeMaker.woodStock=14; GardenHoeMaker.leatherStock=8; GardenHoeMaker.silverStock=8; GardenHoeMaker.goldStock=6; GardenHoeMaker.jewelStock=4; GardenHoeMaker.pearlStock=4; GardenHoeMaker.productStock={}; GardenHoeMaker.buildings={}; GardenHoeMaker.maker=nil; GardenHoeMaker.activeMaking={}; GardenHoeMaker.totalProducts=0; GardenHoeMaker.dayTimer=0; print("[GardenHoeMaker] Royal Garden Hoe Maker System initialized (6 products, 4 buildings)") end
function GardenHoeMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenHoeMaker.maker={name=n or ("Motikar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Motikar najet: %s (spretnost: %d)",GardenHoeMaker.maker.name,s),"success") end; return true end
function GardenHoeMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenHoeMaker.build(id) local ok,e=GardenHoeMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenHoeMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenHoeMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenHoeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenHoeMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenHoeMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenHoeMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenHoeMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenHoeMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenHoeMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenHoeMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenHoeMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenHoeMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenHoeMaker.buildings==0 then return false,"Potrebna motična delavnica" end; if not GardenHoeMaker.maker then return false,"Potreben motikar" end; return true end
function GardenHoeMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenHoeMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenHoeMaker.ironStock=GardenHoeMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenHoeMaker.bronzeStock=GardenHoeMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenHoeMaker.woodStock=GardenHoeMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenHoeMaker.leatherStock=GardenHoeMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenHoeMaker.silverStock=GardenHoeMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenHoeMaker.goldStock=GardenHoeMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenHoeMaker.jewelStock=GardenHoeMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenHoeMaker.pearlStock=GardenHoeMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenHoeMaker.maker then t=math.max(1,t-math.floor(GardenHoeMaker.maker.skill/13)) end; table.insert(GardenHoeMaker.activeMaking,{id="gardenhoe_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenHoeMaker.completeMaking(m) local q=1.0+(GardenHoeMaker.getQualityBonus()/100); if GardenHoeMaker.maker then q=q+(GardenHoeMaker.maker.skill/140) end; q=math.min(2.5,q); GardenHoeMaker.productStock[m.productType]=(GardenHoeMaker.productStock[m.productType] or 0)+m.quantity; GardenHoeMaker.totalProducts=GardenHoeMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenHoeMaker.maker then GardenHoeMaker.maker.itemsMade=GardenHoeMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenHoeMaker.maker.skill=math.min(100,GardenHoeMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Motika izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardenhoe.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenHoeMaker.update(dt) if not _G.state then return end; GardenHoeMaker.dayTimer=GardenHoeMaker.dayTimer+dt; if GardenHoeMaker.dayTimer>=30 then GardenHoeMaker.dayTimer=0; for i=#GardenHoeMaker.activeMaking,1,-1 do local m=GardenHoeMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenHoeMaker.completeMaking(m); table.remove(GardenHoeMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenHoeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenHoeMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenHoeMaker.getStats() return {ironStock=GardenHoeMaker.ironStock,bronzeStock=GardenHoeMaker.bronzeStock,woodStock=GardenHoeMaker.woodStock,leatherStock=GardenHoeMaker.leatherStock,silverStock=GardenHoeMaker.silverStock,goldStock=GardenHoeMaker.goldStock,jewelStock=GardenHoeMaker.jewelStock,pearlStock=GardenHoeMaker.pearlStock,productStock=GardenHoeMaker.productStock,numBuildings=#GardenHoeMaker.buildings,hasMaker=GardenHoeMaker.maker~=nil,makerName=GardenHoeMaker.maker and GardenHoeMaker.maker.name or "—",makerSkill=GardenHoeMaker.maker and GardenHoeMaker.maker.skill or 0,activeMaking=#GardenHoeMaker.activeMaking,totalProducts=GardenHoeMaker.totalProducts} end
return GardenHoeMaker
