local KnotBoardMaker = {}
local PRODUCTS = {
    iron_knot_board = { name = "Železna tabla za vozle", ironCost = 2, woodCost = 3, leatherCost = 1, time = 5, cost = 165, prestige = 4, happiness = 2, description = "Železna tabla za učenje vozlov." },
    bronze_knot_board = { name = "Bronasta tabla za vozle", bronzeCost = 2, ironCost = 1, woodCost = 3, leatherCost = 1, time = 7, cost = 400, prestige = 6, happiness = 3, description = "Bronasta tabla za vrvarje." },
    silver_knot_board = { name = "Srebrna tabla za vozle", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 3, leatherCost = 1, time = 11, cost = 970, prestige = 11, happiness = 4, description = "Srebrna tabla za plemiške vrvarje." },
    gilded_knot_board = { name = "Pozlačena tabla za vozle", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 15, cost = 2100, prestige = 20, happiness = 5, description = "Pozlačena tabla za dvorne vrvarje." },
    jewel_set_knot_board = { name = "Draguljasta tabla za vozle", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 19, cost = 4500, prestige = 36, happiness = 7, description = "Draguljasta tabla za kraljeve vrvarje." },
    royal_sovereign_knot_board = { name = "Kraljevski suverena tabla za vozle", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 4, leatherCost = 1, time = 26, cost = 9700, prestige = 69, happiness = 13, description = "Suverena tabla z biseri za krono." },
}
local BUILDINGS = {
    knotboard_workshop = { name = "Vozlena delavnica", cost = { gold = 330, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    knotboard_house = { name = "Vozlena hiša", cost = { gold = 1200, wood = 365, stone = 270, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_knotboard_atelier = { name = "Mojstrski vozleni atelje", cost = { gold = 3010, wood = 425, stone = 520, silver = 35, gold = 7 }, upkeep = 71, qualityBonus = 30 },
    sovereign_knotboard_palace = { name = "Suverena vozlena palača", cost = { gold = 13050, wood = 650, stone = 830, gold = 84, jewel = 19 }, upkeep = 255, qualityBonus = 55, prestigeBonus = 50 },
}
KnotBoardMaker.ironStock = 12; KnotBoardMaker.bronzeStock = 10; KnotBoardMaker.woodStock = 18; KnotBoardMaker.leatherStock = 10; KnotBoardMaker.silverStock = 8; KnotBoardMaker.goldStock = 6; KnotBoardMaker.jewelStock = 4; KnotBoardMaker.pearlStock = 4
KnotBoardMaker.productStock = {}; KnotBoardMaker.buildings = {}; KnotBoardMaker.maker = nil; KnotBoardMaker.activeMaking = {}; KnotBoardMaker.totalProducts = 0; KnotBoardMaker.dayTimer = 0
function KnotBoardMaker.init() KnotBoardMaker.ironStock=12; KnotBoardMaker.bronzeStock=10; KnotBoardMaker.woodStock=18; KnotBoardMaker.leatherStock=10; KnotBoardMaker.silverStock=8; KnotBoardMaker.goldStock=6; KnotBoardMaker.jewelStock=4; KnotBoardMaker.pearlStock=4; KnotBoardMaker.productStock={}; KnotBoardMaker.buildings={}; KnotBoardMaker.maker=nil; KnotBoardMaker.activeMaking={}; KnotBoardMaker.totalProducts=0; KnotBoardMaker.dayTimer=0; print("[KnotBoardMaker] Royal Knot Board Maker System initialized (6 products, 4 buildings)") end
function KnotBoardMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; KnotBoardMaker.maker={name=n or ("Vozlar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vozlar najet: %s (spretnost: %d)",KnotBoardMaker.maker.name,s),"success") end; return true end
function KnotBoardMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function KnotBoardMaker.build(id) local ok,e=KnotBoardMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(KnotBoardMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function KnotBoardMaker.getQualityBonus() local b=0; for _,bd in ipairs(KnotBoardMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function KnotBoardMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and KnotBoardMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and KnotBoardMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and KnotBoardMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and KnotBoardMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and KnotBoardMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and KnotBoardMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and KnotBoardMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and KnotBoardMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #KnotBoardMaker.buildings==0 then return false,"Potrebna vozlena delavnica" end; if not KnotBoardMaker.maker then return false,"Potreben vozlar" end; return true end
function KnotBoardMaker.make(pt,qty) qty=qty or 1; local ok,e=KnotBoardMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then KnotBoardMaker.ironStock=KnotBoardMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then KnotBoardMaker.bronzeStock=KnotBoardMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then KnotBoardMaker.woodStock=KnotBoardMaker.woodStock-d.woodCost*qty end; if d.leatherCost then KnotBoardMaker.leatherStock=KnotBoardMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then KnotBoardMaker.silverStock=KnotBoardMaker.silverStock-d.silverCost*qty end; if d.goldCost then KnotBoardMaker.goldStock=KnotBoardMaker.goldStock-d.goldCost*qty end; if d.jewelCost then KnotBoardMaker.jewelStock=KnotBoardMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then KnotBoardMaker.pearlStock=KnotBoardMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if KnotBoardMaker.maker then t=math.max(1,t-math.floor(KnotBoardMaker.maker.skill/13)) end; table.insert(KnotBoardMaker.activeMaking,{id="knotboard_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function KnotBoardMaker.completeMaking(m) local q=1.0+(KnotBoardMaker.getQualityBonus()/100); if KnotBoardMaker.maker then q=q+(KnotBoardMaker.maker.skill/140) end; q=math.min(2.5,q); KnotBoardMaker.productStock[m.productType]=(KnotBoardMaker.productStock[m.productType] or 0)+m.quantity; KnotBoardMaker.totalProducts=KnotBoardMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if KnotBoardMaker.maker then KnotBoardMaker.maker.itemsMade=KnotBoardMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then KnotBoardMaker.maker.skill=math.min(100,KnotBoardMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tabla izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"knotboard.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function KnotBoardMaker.update(dt) if not _G.state then return end; KnotBoardMaker.dayTimer=KnotBoardMaker.dayTimer+dt; if KnotBoardMaker.dayTimer>=30 then KnotBoardMaker.dayTimer=0; for i=#KnotBoardMaker.activeMaking,1,-1 do local m=KnotBoardMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then KnotBoardMaker.completeMaking(m); table.remove(KnotBoardMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(KnotBoardMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if KnotBoardMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function KnotBoardMaker.getStats() return {ironStock=KnotBoardMaker.ironStock,bronzeStock=KnotBoardMaker.bronzeStock,woodStock=KnotBoardMaker.woodStock,leatherStock=KnotBoardMaker.leatherStock,silverStock=KnotBoardMaker.silverStock,goldStock=KnotBoardMaker.goldStock,jewelStock=KnotBoardMaker.jewelStock,pearlStock=KnotBoardMaker.pearlStock,productStock=KnotBoardMaker.productStock,numBuildings=#KnotBoardMaker.buildings,hasMaker=KnotBoardMaker.maker~=nil,makerName=KnotBoardMaker.maker and KnotBoardMaker.maker.name or "—",makerSkill=KnotBoardMaker.maker and KnotBoardMaker.maker.skill or 0,activeMaking=#KnotBoardMaker.activeMaking,totalProducts=KnotBoardMaker.totalProducts} end
return KnotBoardMaker
