local CurtainMaker = {}
local PRODUCTS = {
    linen_curtain = { name = "Lnene zavese", linenCost = 3, ropeCost = 1, time = 3, cost = 30, warmth = 40, happiness = 1, description = "Lnene zavese za okna." },
    wool_curtain = { name = "Volnene zavese", woolCost = 3, ropeCost = 1, time = 4, cost = 65, warmth = 50, prestige = 2, happiness = 2, description = "Volnene zavese za dvorane." },
    tapestry_curtain = { name = "Tapiserijske zavese", woolCost = 3, silkCost = 1, threadCost = 1, ropeCost = 1, time = 6, cost = 150, warmth = 60, prestige = 5, happiness = 3, description = "Tapiserijske zavese z vzorci." },
    silver_trim_curtain = { name = "Srebrno obrobljene zavese", silkCost = 2, silverCost = 1, threadCost = 1, ropeCost = 1, time = 9, cost = 340, warmth = 70, prestige = 10, happiness = 4, description = "Srebrno obrobljene zavese za plemiče." },
    gold_thread_curtain = { name = "Zlatorobne zavese", silkCost = 3, goldCost = 1, silverCost = 1, threadCost = 1, ropeCost = 1, time = 12, cost = 720, warmth = 80, prestige = 18, happiness = 6, description = "Zlatorobne zavese za visoke plemiče." },
    royal_grand_curtain = { name = "Kraljevski velike zavese", silkCost = 5, goldCost = 2, silverCost = 1, jewelCost = 1, pearlCost = 1, threadCost = 2, ropeCost = 1, time = 17, cost = 2000, warmth = 100, prestige = 45, happiness = 12, description = "Velike kraljevske zavese z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Zavesarska delavnica", cost = { gold = 260, wood = 130, stone = 200 }, upkeep = 6, qualityBonus = 5 },
    sewing_room = { name = "Šivalnica", cost = { gold = 850, wood = 250, stone = 400, thread = 8 }, upkeep = 21, qualityBonus = 18 },
    embroidery_room = { name = "Vezenilnica", cost = { gold = 2200, wood = 350, stone = 600, silver = 25, silk = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_curtain_atelier = { name = "Kraljevski atelje zaves", cost = { gold = 9000, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
CurtainMaker.linenStock = 14; CurtainMaker.woolStock = 14; CurtainMaker.silkStock = 10; CurtainMaker.threadStock = 12; CurtainMaker.ropeStock = 10; CurtainMaker.silverStock = 8; CurtainMaker.goldStock = 6; CurtainMaker.jewelStock = 6; CurtainMaker.pearlStock = 4
CurtainMaker.productStock = {}; CurtainMaker.buildings = {}; CurtainMaker.maker = nil; CurtainMaker.activeMaking = {}; CurtainMaker.totalProducts = 0; CurtainMaker.dayTimer = 0
function CurtainMaker.init() CurtainMaker.linenStock=14; CurtainMaker.woolStock=14; CurtainMaker.silkStock=10; CurtainMaker.threadStock=12; CurtainMaker.ropeStock=10; CurtainMaker.silverStock=8; CurtainMaker.goldStock=6; CurtainMaker.jewelStock=6; CurtainMaker.pearlStock=4; CurtainMaker.productStock={}; CurtainMaker.buildings={}; CurtainMaker.maker=nil; CurtainMaker.activeMaking={}; CurtainMaker.totalProducts=0; CurtainMaker.dayTimer=0; print("[CurtainMaker] Royal Curtain Maker System initialized (6 products, 4 buildings)") end
function CurtainMaker.hireMaker(n,s) s=s or math.random(50,90); local c=500+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CurtainMaker.maker={name=n or ("Zavesar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zavesar najet: %s (spretnost: %d)",CurtainMaker.maker.name,s),"success") end; return true end
function CurtainMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CurtainMaker.build(id) local ok,e=CurtainMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CurtainMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CurtainMaker.getQualityBonus() local b=0; for _,bd in ipairs(CurtainMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CurtainMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.linenCost and CurtainMaker.linenStock<(d.linenCost or 0) then return false,"Premalo lana" end; if d.woolCost and CurtainMaker.woolStock<(d.woolCost or 0) then return false,"Premalo volne" end; if d.silkCost and CurtainMaker.silkStock<(d.silkCost or 0) then return false,"Premalo svile" end; if d.threadCost and CurtainMaker.threadStock<(d.threadCost or 0) then return false,"Premalo niti" end; if d.ropeCost and CurtainMaker.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.silverCost and CurtainMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CurtainMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CurtainMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CurtainMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CurtainMaker.buildings==0 then return false,"Potrebna delavnica" end; if not CurtainMaker.maker then return false,"Potreben zavesar" end; return true end
function CurtainMaker.make(pt,qty) qty=qty or 1; local ok,e=CurtainMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.linenCost then CurtainMaker.linenStock=CurtainMaker.linenStock-d.linenCost*qty end; if d.woolCost then CurtainMaker.woolStock=CurtainMaker.woolStock-d.woolCost*qty end; if d.silkCost then CurtainMaker.silkStock=CurtainMaker.silkStock-d.silkCost*qty end; if d.threadCost then CurtainMaker.threadStock=CurtainMaker.threadStock-d.threadCost*qty end; if d.ropeCost then CurtainMaker.ropeStock=CurtainMaker.ropeStock-d.ropeCost*qty end; if d.silverCost then CurtainMaker.silverStock=CurtainMaker.silverStock-d.silverCost*qty end; if d.goldCost then CurtainMaker.goldStock=CurtainMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CurtainMaker.jewelStock=CurtainMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CurtainMaker.pearlStock=CurtainMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CurtainMaker.maker then t=math.max(1,t-math.floor(CurtainMaker.maker.skill/12)) end; table.insert(CurtainMaker.activeMaking,{id="curtain_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,warmth=d.warmth or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CurtainMaker.completeMaking(m) local q=1.0+(CurtainMaker.getQualityBonus()/100); if CurtainMaker.maker then q=q+(CurtainMaker.maker.skill/180) end; q=math.min(2.0,q); CurtainMaker.productStock[m.productType]=(CurtainMaker.productStock[m.productType] or 0)+m.quantity; CurtainMaker.totalProducts=CurtainMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CurtainMaker.maker then CurtainMaker.maker.itemsMade=CurtainMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then CurtainMaker.maker.skill=math.min(100,CurtainMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zavese izdelane: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"curtain.completed",{productName=m.productName,warmth=m.warmth,prestige=m.prestige,happiness=m.happiness}) end end
function CurtainMaker.update(dt) if not _G.state then return end; CurtainMaker.dayTimer=CurtainMaker.dayTimer+dt; if CurtainMaker.dayTimer>=30 then CurtainMaker.dayTimer=0; for i=#CurtainMaker.activeMaking,1,-1 do local m=CurtainMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CurtainMaker.completeMaking(m); table.remove(CurtainMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CurtainMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CurtainMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CurtainMaker.getStats() return {linenStock=CurtainMaker.linenStock,woolStock=CurtainMaker.woolStock,silkStock=CurtainMaker.silkStock,threadStock=CurtainMaker.threadStock,ropeStock=CurtainMaker.ropeStock,silverStock=CurtainMaker.silverStock,goldStock=CurtainMaker.goldStock,jewelStock=CurtainMaker.jewelStock,pearlStock=CurtainMaker.pearlStock,productStock=CurtainMaker.productStock,numBuildings=#CurtainMaker.buildings,hasMaker=CurtainMaker.maker~=nil,makerName=CurtainMaker.maker and CurtainMaker.maker.name or "—",makerSkill=CurtainMaker.maker and CurtainMaker.maker.skill or 0,activeMaking=#CurtainMaker.activeMaking,totalProducts=CurtainMaker.totalProducts} end
return CurtainMaker
