local GlassColorantDryingTrayMaker = {}
local PRODUCTS = {
    iron_glasscolorantdryingtray = { name = "Železni pladenj za susenje barv", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni pladenj za susenje barv za steklarje." },
    bronze_glasscolorantdryingtray = { name = "Bronast pladenj za susenje barv", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast pladenj za susenje barv za steklarje." },
    silver_glasscolorantdryingtray = { name = "Srebrn pladenj za susenje barv", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn pladenj za susenje barv za steklarje." },
    gilded_glasscolorantdryingtray = { name = "Pozlačen pladenj za susenje barv", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen pladenj za susenje barv za steklarje." },
    jewel_set_glasscolorantdryingtray = { name = "Draguljast pladenj za susenje barv", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast pladenj za susenje barv za steklarje." },
    royal_sovereign_glasscolorantdryingtray = { name = "Kraljevski suveren pladenj za susenje barv", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren pladenj za susenje barv z biseri za krono." },
}
local BUILDINGS = {
    glasscolorantdryingtray_workshop = { name = "Glasscolorantdryingtray delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glasscolorantdryingtray_house = { name = "Glasscolorantdryingtray hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glasscolorantdryingtray_atelier = { name = "Mojstrski glasscolorantdryingtray atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glasscolorantdryingtray_palace = { name = "Suverena glasscolorantdryingtray palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassColorantDryingTrayMaker.ironStock=12; GlassColorantDryingTrayMaker.bronzeStock=10; GlassColorantDryingTrayMaker.woodStock=16; GlassColorantDryingTrayMaker.leatherStock=10; GlassColorantDryingTrayMaker.silverStock=8; GlassColorantDryingTrayMaker.goldStock=6; GlassColorantDryingTrayMaker.jewelStock=4; GlassColorantDryingTrayMaker.pearlStock=4
GlassColorantDryingTrayMaker.productStock = {}; GlassColorantDryingTrayMaker.buildings = {}; GlassColorantDryingTrayMaker.maker = nil; GlassColorantDryingTrayMaker.activeMaking = {}; GlassColorantDryingTrayMaker.totalProducts = 0; GlassColorantDryingTrayMaker.dayTimer = 0
function GlassColorantDryingTrayMaker.init() GlassColorantDryingTrayMaker.ironStock=12; GlassColorantDryingTrayMaker.bronzeStock=10; GlassColorantDryingTrayMaker.woodStock=16; GlassColorantDryingTrayMaker.leatherStock=10; GlassColorantDryingTrayMaker.silverStock=8; GlassColorantDryingTrayMaker.goldStock=6; GlassColorantDryingTrayMaker.jewelStock=4; GlassColorantDryingTrayMaker.pearlStock=4; GlassColorantDryingTrayMaker.productStock={}; GlassColorantDryingTrayMaker.buildings={}; GlassColorantDryingTrayMaker.maker=nil; GlassColorantDryingTrayMaker.activeMaking={}; GlassColorantDryingTrayMaker.totalProducts=0; GlassColorantDryingTrayMaker.dayTimer=0; print("[GlassColorantDryingTrayMaker] Royal Glass Colorant Drying Tray Maker System initialized (6 products, 4 buildings)") end
function GlassColorantDryingTrayMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassColorantDryingTrayMaker.maker={name=n or ("Pladnjar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pladnjar najet: %s (spretnost: %d)",GlassColorantDryingTrayMaker.maker.name,s),"success") end; return true end
function GlassColorantDryingTrayMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassColorantDryingTrayMaker.build(id) local ok,e=GlassColorantDryingTrayMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassColorantDryingTrayMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassColorantDryingTrayMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassColorantDryingTrayMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassColorantDryingTrayMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassColorantDryingTrayMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassColorantDryingTrayMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassColorantDryingTrayMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassColorantDryingTrayMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassColorantDryingTrayMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassColorantDryingTrayMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassColorantDryingTrayMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassColorantDryingTrayMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassColorantDryingTrayMaker.buildings==0 then return false,"Potrebna pladnjska delavnica" end; if not GlassColorantDryingTrayMaker.maker then return false,"Potreben pladnjar" end; return true end
function GlassColorantDryingTrayMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassColorantDryingTrayMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassColorantDryingTrayMaker.ironStock=GlassColorantDryingTrayMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassColorantDryingTrayMaker.bronzeStock=GlassColorantDryingTrayMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassColorantDryingTrayMaker.woodStock=GlassColorantDryingTrayMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassColorantDryingTrayMaker.leatherStock=GlassColorantDryingTrayMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassColorantDryingTrayMaker.silverStock=GlassColorantDryingTrayMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassColorantDryingTrayMaker.goldStock=GlassColorantDryingTrayMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassColorantDryingTrayMaker.jewelStock=GlassColorantDryingTrayMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassColorantDryingTrayMaker.pearlStock=GlassColorantDryingTrayMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassColorantDryingTrayMaker.maker then t=math.max(1,t-math.floor(GlassColorantDryingTrayMaker.maker.skill/13)) end; table.insert(GlassColorantDryingTrayMaker.activeMaking,{id="glasscolorantdryingtray_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassColorantDryingTrayMaker.completeMaking(m) local q=1.0+(GlassColorantDryingTrayMaker.getQualityBonus()/100); if GlassColorantDryingTrayMaker.maker then q=q+(GlassColorantDryingTrayMaker.maker.skill/140) end; q=math.min(2.5,q); GlassColorantDryingTrayMaker.productStock[m.productType]=(GlassColorantDryingTrayMaker.productStock[m.productType] or 0)+m.quantity; GlassColorantDryingTrayMaker.totalProducts=GlassColorantDryingTrayMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassColorantDryingTrayMaker.maker then GlassColorantDryingTrayMaker.maker.itemsMade=GlassColorantDryingTrayMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassColorantDryingTrayMaker.maker.skill=math.min(100,GlassColorantDryingTrayMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pladenj izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glasscolorantdryingtray.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassColorantDryingTrayMaker.update(dt) if not _G.state then return end; GlassColorantDryingTrayMaker.dayTimer=GlassColorantDryingTrayMaker.dayTimer+dt; if GlassColorantDryingTrayMaker.dayTimer>=30 then GlassColorantDryingTrayMaker.dayTimer=0; for i=#GlassColorantDryingTrayMaker.activeMaking,1,-1 do local m=GlassColorantDryingTrayMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassColorantDryingTrayMaker.completeMaking(m); table.remove(GlassColorantDryingTrayMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassColorantDryingTrayMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassColorantDryingTrayMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassColorantDryingTrayMaker.getStats() return {ironStock=GlassColorantDryingTrayMaker.ironStock,bronzeStock=GlassColorantDryingTrayMaker.bronzeStock,woodStock=GlassColorantDryingTrayMaker.woodStock,leatherStock=GlassColorantDryingTrayMaker.leatherStock,silverStock=GlassColorantDryingTrayMaker.silverStock,goldStock=GlassColorantDryingTrayMaker.goldStock,jewelStock=GlassColorantDryingTrayMaker.jewelStock,pearlStock=GlassColorantDryingTrayMaker.pearlStock,productStock=GlassColorantDryingTrayMaker.productStock,numBuildings=#GlassColorantDryingTrayMaker.buildings,hasMaker=GlassColorantDryingTrayMaker.maker~=nil,makerName=GlassColorantDryingTrayMaker.maker and GlassColorantDryingTrayMaker.maker.name or "—",makerSkill=GlassColorantDryingTrayMaker.maker and GlassColorantDryingTrayMaker.maker.skill or 0,activeMaking=#GlassColorantDryingTrayMaker.activeMaking,totalProducts=GlassColorantDryingTrayMaker.totalProducts} end
return GlassColorantDryingTrayMaker
