local ScentConeMaker = {}
local PRODUCTS = {
    iron_scentcone = { name = "Železni stožec za dišave", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni stožec za dišave za glasbila." },
    bronze_scentcone = { name = "Bronast stožec za dišave", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast stožec za dišave za fino glasbo." },
    silver_scentcone = { name = "Srebrn stožec za dišave", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn stožec za dišave za plemiške glasbenike." },
    gilded_scentcone = { name = "Pozlačen stožec za dišave", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen stožec za dišave za dvorne glasbenike." },
    jewel_set_scentcone = { name = "Draguljast stožec za dišave", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast stožec za dišave za kraljevske glasbenike." },
    royal_sovereign_scentcone = { name = "Kraljevski suveren stožec za dišave", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren stožec za dišave z biseri za krono." },
}
local BUILDINGS = {
    scentcone_workshop = { name = "Scentcone delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    scentcone_house = { name = "Scentcone hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_scentcone_atelier = { name = "Mojstrski scentcone atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_scentcone_palace = { name = "Suverena scentcone palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
ScentConeMaker.ironStock = 12; ScentConeMaker.bronzeStock = 10; ScentConeMaker.woodStock = 14; ScentConeMaker.leatherStock = 12; ScentConeMaker.silverStock = 8; ScentConeMaker.goldStock = 6; ScentConeMaker.jewelStock = 4; ScentConeMaker.pearlStock = 4
ScentConeMaker.productStock = {}; ScentConeMaker.buildings = {}; ScentConeMaker.maker = nil; ScentConeMaker.activeMaking = {}; ScentConeMaker.totalProducts = 0; ScentConeMaker.dayTimer = 0
function ScentConeMaker.init() ScentConeMaker.ironStock=12; ScentConeMaker.bronzeStock=10; ScentConeMaker.woodStock=14; ScentConeMaker.leatherStock=12; ScentConeMaker.silverStock=8; ScentConeMaker.goldStock=6; ScentConeMaker.jewelStock=4; ScentConeMaker.pearlStock=4; ScentConeMaker.productStock={}; ScentConeMaker.buildings={}; ScentConeMaker.maker=nil; ScentConeMaker.activeMaking={}; ScentConeMaker.totalProducts=0; ScentConeMaker.dayTimer=0; print("[ScentConeMaker] Royal Scent Cone Maker System initialized (6 products, 4 buildings)") end
function ScentConeMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ScentConeMaker.maker={name=n or ("Stožčar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stožčar najet: %s (spretnost: %d)",ScentConeMaker.maker.name,s),"success") end; return true end
function ScentConeMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ScentConeMaker.build(id) local ok,e=ScentConeMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ScentConeMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ScentConeMaker.getQualityBonus() local b=0; for _,bd in ipairs(ScentConeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ScentConeMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ScentConeMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and ScentConeMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ScentConeMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ScentConeMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ScentConeMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ScentConeMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ScentConeMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ScentConeMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ScentConeMaker.buildings==0 then return false,"Potrebna stožčasta delavnica" end; if not ScentConeMaker.maker then return false,"Potreben stozcar" end; return true end
function ScentConeMaker.make(pt,qty) qty=qty or 1; local ok,e=ScentConeMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ScentConeMaker.ironStock=ScentConeMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ScentConeMaker.bronzeStock=ScentConeMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ScentConeMaker.woodStock=ScentConeMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ScentConeMaker.leatherStock=ScentConeMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ScentConeMaker.silverStock=ScentConeMaker.silverStock-d.silverCost*qty end; if d.goldCost then ScentConeMaker.goldStock=ScentConeMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ScentConeMaker.jewelStock=ScentConeMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ScentConeMaker.pearlStock=ScentConeMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ScentConeMaker.maker then t=math.max(1,t-math.floor(ScentConeMaker.maker.skill/13)) end; table.insert(ScentConeMaker.activeMaking,{id="scentcone_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ScentConeMaker.completeMaking(m) local q=1.0+(ScentConeMaker.getQualityBonus()/100); if ScentConeMaker.maker then q=q+(ScentConeMaker.maker.skill/140) end; q=math.min(2.5,q); ScentConeMaker.productStock[m.productType]=(ScentConeMaker.productStock[m.productType] or 0)+m.quantity; ScentConeMaker.totalProducts=ScentConeMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ScentConeMaker.maker then ScentConeMaker.maker.itemsMade=ScentConeMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ScentConeMaker.maker.skill=math.min(100,ScentConeMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stožec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"scentcone.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ScentConeMaker.update(dt) if not _G.state then return end; ScentConeMaker.dayTimer=ScentConeMaker.dayTimer+dt; if ScentConeMaker.dayTimer>=30 then ScentConeMaker.dayTimer=0; for i=#ScentConeMaker.activeMaking,1,-1 do local m=ScentConeMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ScentConeMaker.completeMaking(m); table.remove(ScentConeMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ScentConeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ScentConeMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ScentConeMaker.getStats() return {ironStock=ScentConeMaker.ironStock,bronzeStock=ScentConeMaker.bronzeStock,woodStock=ScentConeMaker.woodStock,leatherStock=ScentConeMaker.leatherStock,silverStock=ScentConeMaker.silverStock,goldStock=ScentConeMaker.goldStock,jewelStock=ScentConeMaker.jewelStock,pearlStock=ScentConeMaker.pearlStock,productStock=ScentConeMaker.productStock,numBuildings=#ScentConeMaker.buildings,hasMaker=ScentConeMaker.maker~=nil,makerName=ScentConeMaker.maker and ScentConeMaker.maker.name or "—",makerSkill=ScentConeMaker.maker and ScentConeMaker.maker.skill or 0,activeMaking=#ScentConeMaker.activeMaking,totalProducts=ScentConeMaker.totalProducts} end
return ScentConeMaker
