local BookCoverCordWinderMaker = {}
local PRODUCTS = {
    iron_bookcovercordwinder = { name = "Železni navijalec vrvic za naslovnice", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni navijalec vrvic za naslovnice za knjigoveze." },
    bronze_bookcovercordwinder = { name = "Bronast navijalec vrvic za naslovnice", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast navijalec vrvic za naslovnice za knjigoveze." },
    silver_bookcovercordwinder = { name = "Srebrn navijalec vrvic za naslovnice", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn navijalec vrvic za naslovnice za knjigoveze." },
    gilded_bookcovercordwinder = { name = "Pozlačen navijalec vrvic za naslovnice", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen navijalec vrvic za naslovnice za knjigoveze." },
    jewel_set_bookcovercordwinder = { name = "Draguljast navijalec vrvic za naslovnice", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast navijalec vrvic za naslovnice za knjigoveze." },
    royal_sovereign_bookcovercordwinder = { name = "Kraljevski suveren navijalec vrvic za naslovnice", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren navijalec vrvic za naslovnice z biseri za krono." },
}
local BUILDINGS = {
    bookcovercordwinder_workshop = { name = "Bookcovercordwinder delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookcovercordwinder_house = { name = "Bookcovercordwinder hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookcovercordwinder_atelier = { name = "Mojstrski bookcovercordwinder atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookcovercordwinder_palace = { name = "Suverena bookcovercordwinder palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookCoverCordWinderMaker.ironStock=14; BookCoverCordWinderMaker.bronzeStock=12; BookCoverCordWinderMaker.woodStock=14; BookCoverCordWinderMaker.leatherStock=8; BookCoverCordWinderMaker.silverStock=8; BookCoverCordWinderMaker.goldStock=6; BookCoverCordWinderMaker.jewelStock=4; BookCoverCordWinderMaker.pearlStock=4
BookCoverCordWinderMaker.productStock = {}; BookCoverCordWinderMaker.buildings = {}; BookCoverCordWinderMaker.maker = nil; BookCoverCordWinderMaker.activeMaking = {}; BookCoverCordWinderMaker.totalProducts = 0; BookCoverCordWinderMaker.dayTimer = 0
function BookCoverCordWinderMaker.init() BookCoverCordWinderMaker.ironStock=14; BookCoverCordWinderMaker.bronzeStock=12; BookCoverCordWinderMaker.woodStock=14; BookCoverCordWinderMaker.leatherStock=8; BookCoverCordWinderMaker.silverStock=8; BookCoverCordWinderMaker.goldStock=6; BookCoverCordWinderMaker.jewelStock=4; BookCoverCordWinderMaker.pearlStock=4; BookCoverCordWinderMaker.productStock={}; BookCoverCordWinderMaker.buildings={}; BookCoverCordWinderMaker.maker=nil; BookCoverCordWinderMaker.activeMaking={}; BookCoverCordWinderMaker.totalProducts=0; BookCoverCordWinderMaker.dayTimer=0; print("[BookCoverCordWinderMaker] Royal Book Cover Cord Winder Maker System initialized (6 products, 4 buildings)") end
function BookCoverCordWinderMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookCoverCordWinderMaker.maker={name=n or ("Navijalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Navijalec najet: %s (spretnost: %d)",BookCoverCordWinderMaker.maker.name,s),"success") end; return true end
function BookCoverCordWinderMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookCoverCordWinderMaker.build(id) local ok,e=BookCoverCordWinderMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookCoverCordWinderMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookCoverCordWinderMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookCoverCordWinderMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookCoverCordWinderMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookCoverCordWinderMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookCoverCordWinderMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookCoverCordWinderMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookCoverCordWinderMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookCoverCordWinderMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookCoverCordWinderMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookCoverCordWinderMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookCoverCordWinderMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookCoverCordWinderMaker.buildings==0 then return false,"Potrebna navijalna delavnica" end; if not BookCoverCordWinderMaker.maker then return false,"Potreben navijalec" end; return true end
function BookCoverCordWinderMaker.make(pt,qty) qty=qty or 1; local ok,e=BookCoverCordWinderMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookCoverCordWinderMaker.ironStock=BookCoverCordWinderMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookCoverCordWinderMaker.bronzeStock=BookCoverCordWinderMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookCoverCordWinderMaker.woodStock=BookCoverCordWinderMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookCoverCordWinderMaker.leatherStock=BookCoverCordWinderMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookCoverCordWinderMaker.silverStock=BookCoverCordWinderMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookCoverCordWinderMaker.goldStock=BookCoverCordWinderMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookCoverCordWinderMaker.jewelStock=BookCoverCordWinderMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookCoverCordWinderMaker.pearlStock=BookCoverCordWinderMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookCoverCordWinderMaker.maker then t=math.max(1,t-math.floor(BookCoverCordWinderMaker.maker.skill/13)) end; table.insert(BookCoverCordWinderMaker.activeMaking,{id="bookcovercordwinder_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookCoverCordWinderMaker.completeMaking(m) local q=1.0+(BookCoverCordWinderMaker.getQualityBonus()/100); if BookCoverCordWinderMaker.maker then q=q+(BookCoverCordWinderMaker.maker.skill/140) end; q=math.min(2.5,q); BookCoverCordWinderMaker.productStock[m.productType]=(BookCoverCordWinderMaker.productStock[m.productType] or 0)+m.quantity; BookCoverCordWinderMaker.totalProducts=BookCoverCordWinderMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookCoverCordWinderMaker.maker then BookCoverCordWinderMaker.maker.itemsMade=BookCoverCordWinderMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookCoverCordWinderMaker.maker.skill=math.min(100,BookCoverCordWinderMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Navijalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookcovercordwinder.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookCoverCordWinderMaker.update(dt) if not _G.state then return end; BookCoverCordWinderMaker.dayTimer=BookCoverCordWinderMaker.dayTimer+dt; if BookCoverCordWinderMaker.dayTimer>=30 then BookCoverCordWinderMaker.dayTimer=0; for i=#BookCoverCordWinderMaker.activeMaking,1,-1 do local m=BookCoverCordWinderMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookCoverCordWinderMaker.completeMaking(m); table.remove(BookCoverCordWinderMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookCoverCordWinderMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookCoverCordWinderMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookCoverCordWinderMaker.getStats() return {ironStock=BookCoverCordWinderMaker.ironStock,bronzeStock=BookCoverCordWinderMaker.bronzeStock,woodStock=BookCoverCordWinderMaker.woodStock,leatherStock=BookCoverCordWinderMaker.leatherStock,silverStock=BookCoverCordWinderMaker.silverStock,goldStock=BookCoverCordWinderMaker.goldStock,jewelStock=BookCoverCordWinderMaker.jewelStock,pearlStock=BookCoverCordWinderMaker.pearlStock,productStock=BookCoverCordWinderMaker.productStock,numBuildings=#BookCoverCordWinderMaker.buildings,hasMaker=BookCoverCordWinderMaker.maker~=nil,makerName=BookCoverCordWinderMaker.maker and BookCoverCordWinderMaker.maker.name or "—",makerSkill=BookCoverCordWinderMaker.maker and BookCoverCordWinderMaker.maker.skill or 0,activeMaking=#BookCoverCordWinderMaker.activeMaking,totalProducts=BookCoverCordWinderMaker.totalProducts} end
return BookCoverCordWinderMaker
