local ForgeCokeRakeMaker = {}
local PRODUCTS = {
    iron_forgecokerake = { name = "Železni grebalec za koks", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni grebalec za koks za kovace." },
    bronze_forgecokerake = { name = "Bronast grebalec za koks", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast grebalec za koks za kovace." },
    silver_forgecokerake = { name = "Srebrn grebalec za koks", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn grebalec za koks za kovace." },
    gilded_forgecokerake = { name = "Pozlačen grebalec za koks", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen grebalec za koks za kovace." },
    jewel_set_forgecokerake = { name = "Draguljast grebalec za koks", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast grebalec za koks za kovace." },
    royal_sovereign_forgecokerake = { name = "Kraljevski suveren grebalec za koks", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren grebalec za koks z biseri za krono." },
}
local BUILDINGS = {
    forgecokerake_workshop = { name = "Forgecokerake delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    forgecokerake_house = { name = "Forgecokerake hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_forgecokerake_atelier = { name = "Mojstrski forgecokerake atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_forgecokerake_palace = { name = "Suverena forgecokerake palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
ForgeCokeRakeMaker.ironStock=16; ForgeCokeRakeMaker.bronzeStock=12; ForgeCokeRakeMaker.woodStock=14; ForgeCokeRakeMaker.leatherStock=8; ForgeCokeRakeMaker.silverStock=8; ForgeCokeRakeMaker.goldStock=6; ForgeCokeRakeMaker.jewelStock=4; ForgeCokeRakeMaker.pearlStock=4
ForgeCokeRakeMaker.productStock = {}; ForgeCokeRakeMaker.buildings = {}; ForgeCokeRakeMaker.maker = nil; ForgeCokeRakeMaker.activeMaking = {}; ForgeCokeRakeMaker.totalProducts = 0; ForgeCokeRakeMaker.dayTimer = 0
function ForgeCokeRakeMaker.init() ForgeCokeRakeMaker.ironStock=16; ForgeCokeRakeMaker.bronzeStock=12; ForgeCokeRakeMaker.woodStock=14; ForgeCokeRakeMaker.leatherStock=8; ForgeCokeRakeMaker.silverStock=8; ForgeCokeRakeMaker.goldStock=6; ForgeCokeRakeMaker.jewelStock=4; ForgeCokeRakeMaker.pearlStock=4; ForgeCokeRakeMaker.productStock={}; ForgeCokeRakeMaker.buildings={}; ForgeCokeRakeMaker.maker=nil; ForgeCokeRakeMaker.activeMaking={}; ForgeCokeRakeMaker.totalProducts=0; ForgeCokeRakeMaker.dayTimer=0; print("[ForgeCokeRakeMaker] Royal Forge Coke Rake Maker System initialized (6 products, 4 buildings)") end
function ForgeCokeRakeMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ForgeCokeRakeMaker.maker={name=n or ("KoksGrebar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("KoksGrebar najet: %s (spretnost: %d)",ForgeCokeRakeMaker.maker.name,s),"success") end; return true end
function ForgeCokeRakeMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ForgeCokeRakeMaker.build(id) local ok,e=ForgeCokeRakeMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ForgeCokeRakeMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ForgeCokeRakeMaker.getQualityBonus() local b=0; for _,bd in ipairs(ForgeCokeRakeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ForgeCokeRakeMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ForgeCokeRakeMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and ForgeCokeRakeMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ForgeCokeRakeMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ForgeCokeRakeMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ForgeCokeRakeMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ForgeCokeRakeMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ForgeCokeRakeMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ForgeCokeRakeMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ForgeCokeRakeMaker.buildings==0 then return false,"Potrebna koksgrebalna delavnica" end; if not ForgeCokeRakeMaker.maker then return false,"Potreben koksgrebar" end; return true end
function ForgeCokeRakeMaker.make(pt,qty) qty=qty or 1; local ok,e=ForgeCokeRakeMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ForgeCokeRakeMaker.ironStock=ForgeCokeRakeMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ForgeCokeRakeMaker.bronzeStock=ForgeCokeRakeMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ForgeCokeRakeMaker.woodStock=ForgeCokeRakeMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ForgeCokeRakeMaker.leatherStock=ForgeCokeRakeMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ForgeCokeRakeMaker.silverStock=ForgeCokeRakeMaker.silverStock-d.silverCost*qty end; if d.goldCost then ForgeCokeRakeMaker.goldStock=ForgeCokeRakeMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ForgeCokeRakeMaker.jewelStock=ForgeCokeRakeMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ForgeCokeRakeMaker.pearlStock=ForgeCokeRakeMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ForgeCokeRakeMaker.maker then t=math.max(1,t-math.floor(ForgeCokeRakeMaker.maker.skill/13)) end; table.insert(ForgeCokeRakeMaker.activeMaking,{id="forgecokerake_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ForgeCokeRakeMaker.completeMaking(m) local q=1.0+(ForgeCokeRakeMaker.getQualityBonus()/100); if ForgeCokeRakeMaker.maker then q=q+(ForgeCokeRakeMaker.maker.skill/140) end; q=math.min(2.5,q); ForgeCokeRakeMaker.productStock[m.productType]=(ForgeCokeRakeMaker.productStock[m.productType] or 0)+m.quantity; ForgeCokeRakeMaker.totalProducts=ForgeCokeRakeMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ForgeCokeRakeMaker.maker then ForgeCokeRakeMaker.maker.itemsMade=ForgeCokeRakeMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ForgeCokeRakeMaker.maker.skill=math.min(100,ForgeCokeRakeMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("KoksGrebar izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"forgecokerake.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ForgeCokeRakeMaker.update(dt) if not _G.state then return end; ForgeCokeRakeMaker.dayTimer=ForgeCokeRakeMaker.dayTimer+dt; if ForgeCokeRakeMaker.dayTimer>=30 then ForgeCokeRakeMaker.dayTimer=0; for i=#ForgeCokeRakeMaker.activeMaking,1,-1 do local m=ForgeCokeRakeMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ForgeCokeRakeMaker.completeMaking(m); table.remove(ForgeCokeRakeMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ForgeCokeRakeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ForgeCokeRakeMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ForgeCokeRakeMaker.getStats() return {ironStock=ForgeCokeRakeMaker.ironStock,bronzeStock=ForgeCokeRakeMaker.bronzeStock,woodStock=ForgeCokeRakeMaker.woodStock,leatherStock=ForgeCokeRakeMaker.leatherStock,silverStock=ForgeCokeRakeMaker.silverStock,goldStock=ForgeCokeRakeMaker.goldStock,jewelStock=ForgeCokeRakeMaker.jewelStock,pearlStock=ForgeCokeRakeMaker.pearlStock,productStock=ForgeCokeRakeMaker.productStock,numBuildings=#ForgeCokeRakeMaker.buildings,hasMaker=ForgeCokeRakeMaker.maker~=nil,makerName=ForgeCokeRakeMaker.maker and ForgeCokeRakeMaker.maker.name or "—",makerSkill=ForgeCokeRakeMaker.maker and ForgeCokeRakeMaker.maker.skill or 0,activeMaking=#ForgeCokeRakeMaker.activeMaking,totalProducts=ForgeCokeRakeMaker.totalProducts} end
return ForgeCokeRakeMaker
