local SpiceMerchant = {}
local PRODUCTS = {
    pepper = { name = "Poper", pepperCost = 1, time = 1, cost = 25, flavorStrength = 10, happiness = 1, description = "Poper za vsakdanjo rabo." },
    cinnamon = { name = "Cimet", cinnamonCost = 1, time = 2, cost = 60, flavorStrength = 15, happiness = 2, prestige = 2, description = "Cimet za sladice in pijače." },
    cloves = { name = "Nageljnove žbice", cloveCost = 1, time = 3, cost = 130, flavorStrength = 20, happiness = 3, prestige = 4, description = "Nageljnove žbice z močnim okusom." },
    nutmeg = { name = "Muškatni orešček", nutmegCost = 1, time = 4, cost = 280, flavorStrength = 25, happiness = 4, prestige = 7, description = "Muškatni orešček za fine jedi." },
    saffron = { name = "Žafran", saffronCost = 1, silverCost = 1, time = 7, cost = 620, flavorStrength = 35, happiness = 6, prestige = 14, description = "Žafran najdražja začimba." },
    royal_spice_blend = { name = "Kraljevski mešanica začimb", saffronCost = 1, goldCost = 1, silverCost = 1, jewelCost = 1, cloveCost = 1, cinnamonCost = 1, time = 12, cost = 1800, flavorStrength = 60, happiness = 14, prestige = 38, description = "Velika kraljevska mešanica začimb z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Zaščitarska delavnica", cost = { gold = 320, wood = 130 }, upkeep = 8, qualityBonus = 5 },
    drying_room = { name = "Sušilnica", cost = { gold = 1000, wood = 250, stone = 350, pepper = 8 }, upkeep = 25, qualityBonus = 18 },
    grinding_room = { name = "Mlinska soba", cost = { gold = 2400, wood = 350, stone = 600, silver = 40, stone2 = 10 }, upkeep = 60, qualityBonus = 30 },
    royal_spice_atelier = { name = "Kraljevski atelje začimb", cost = { gold = 10000, wood = 600, stone = 1100, gold = 80, jewel = 25 }, upkeep = 200, qualityBonus = 55, prestigeBonus = 45 },
}
SpiceMerchant.pepperStock = 14; SpiceMerchant.cinnamonStock = 12; SpiceMerchant.cloveStock = 10; SpiceMerchant.nutmegStock = 8; SpiceMerchant.saffronStock = 6; SpiceMerchant.silverStock = 8; SpiceMerchant.goldStock = 6; SpiceMerchant.jewelStock = 6
SpiceMerchant.productStock = {}; SpiceMerchant.buildings = {}; SpiceMerchant.maker = nil; SpiceMerchant.activeMaking = {}; SpiceMerchant.totalProducts = 0; SpiceMerchant.dayTimer = 0
function SpiceMerchant.init() SpiceMerchant.pepperStock=14; SpiceMerchant.cinnamonStock=12; SpiceMerchant.cloveStock=10; SpiceMerchant.nutmegStock=8; SpiceMerchant.saffronStock=6; SpiceMerchant.silverStock=8; SpiceMerchant.goldStock=6; SpiceMerchant.jewelStock=6; SpiceMerchant.productStock={}; SpiceMerchant.buildings={}; SpiceMerchant.maker=nil; SpiceMerchant.activeMaking={}; SpiceMerchant.totalProducts=0; SpiceMerchant.dayTimer=0; print("[SpiceMerchant] Royal Spice Merchant System initialized (6 products, 4 buildings)") end
function SpiceMerchant.hireMaker(n,s) s=s or math.random(50,90); local c=550+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SpiceMerchant.maker={name=n or ("Zaščitar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zaščitar najet: %s (spretnost: %d)",SpiceMerchant.maker.name,s),"success") end; return true end
function SpiceMerchant.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SpiceMerchant.build(id) local ok,e=SpiceMerchant.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SpiceMerchant.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SpiceMerchant.getQualityBonus() local b=0; for _,bd in ipairs(SpiceMerchant.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SpiceMerchant.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.pepperCost and SpiceMerchant.pepperStock<(d.pepperCost or 0) then return false,"Premalo popra" end; if d.cinnamonCost and SpiceMerchant.cinnamonStock<(d.cinnamonCost or 0) then return false,"Premalo cimeta" end; if d.cloveCost and SpiceMerchant.cloveStock<(d.cloveCost or 0) then return false,"Premalo nageljnovih žbic" end; if d.nutmegCost and SpiceMerchant.nutmegStock<(d.nutmegCost or 0) then return false,"Premalo muškatnega oreščka" end; if d.saffronCost and SpiceMerchant.saffronStock<(d.saffronCost or 0) then return false,"Premalo žafrana" end; if d.silverCost and SpiceMerchant.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SpiceMerchant.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SpiceMerchant.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #SpiceMerchant.buildings==0 then return false,"Potrebna delavnica" end; if not SpiceMerchant.maker then return false,"Potreben zaščitar" end; return true end
function SpiceMerchant.make(pt,qty) qty=qty or 5; local ok,e=SpiceMerchant.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.pepperCost then SpiceMerchant.pepperStock=SpiceMerchant.pepperStock-d.pepperCost*qty end; if d.cinnamonCost then SpiceMerchant.cinnamonStock=SpiceMerchant.cinnamonStock-d.cinnamonCost*qty end; if d.cloveCost then SpiceMerchant.cloveStock=SpiceMerchant.cloveStock-d.cloveCost*qty end; if d.nutmegCost then SpiceMerchant.nutmegStock=SpiceMerchant.nutmegStock-d.nutmegCost*qty end; if d.saffronCost then SpiceMerchant.saffronStock=SpiceMerchant.saffronStock-d.saffronCost*qty end; if d.silverCost then SpiceMerchant.silverStock=SpiceMerchant.silverStock-d.silverCost*qty end; if d.goldCost then SpiceMerchant.goldStock=SpiceMerchant.goldStock-d.goldCost*qty end; if d.jewelCost then SpiceMerchant.jewelStock=SpiceMerchant.jewelStock-d.jewelCost*qty end; local t=d.time; if SpiceMerchant.maker then t=math.max(1,t-math.floor(SpiceMerchant.maker.skill/12)) end; table.insert(SpiceMerchant.activeMaking,{id="spice_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,flavorStrength=d.flavorStrength or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SpiceMerchant.completeMaking(m) local q=1.0+(SpiceMerchant.getQualityBonus()/100); if SpiceMerchant.maker then q=q+(SpiceMerchant.maker.skill/180) end; q=math.min(2.0,q); SpiceMerchant.productStock[m.productType]=(SpiceMerchant.productStock[m.productType] or 0)+m.quantity; SpiceMerchant.totalProducts=SpiceMerchant.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SpiceMerchant.maker then SpiceMerchant.maker.itemsMade=SpiceMerchant.maker.itemsMade+m.quantity; if math.random()<0.20 then SpiceMerchant.maker.skill=math.min(100,SpiceMerchant.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Začimba izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"spice.completed",{productName=m.productName,flavorStrength=m.flavorStrength,happiness=m.happiness}) end end
function SpiceMerchant.update(dt) if not _G.state then return end; SpiceMerchant.dayTimer=SpiceMerchant.dayTimer+dt; if SpiceMerchant.dayTimer>=30 then SpiceMerchant.dayTimer=0; for i=#SpiceMerchant.activeMaking,1,-1 do local m=SpiceMerchant.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SpiceMerchant.completeMaking(m); table.remove(SpiceMerchant.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SpiceMerchant.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SpiceMerchant.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SpiceMerchant.getStats() return {pepperStock=SpiceMerchant.pepperStock,cinnamonStock=SpiceMerchant.cinnamonStock,cloveStock=SpiceMerchant.cloveStock,nutmegStock=SpiceMerchant.nutmegStock,saffronStock=SpiceMerchant.saffronStock,silverStock=SpiceMerchant.silverStock,goldStock=SpiceMerchant.goldStock,jewelStock=SpiceMerchant.jewelStock,productStock=SpiceMerchant.productStock,numBuildings=#SpiceMerchant.buildings,hasMaker=SpiceMerchant.maker~=nil,makerName=SpiceMerchant.maker and SpiceMerchant.maker.name or "—",makerSkill=SpiceMerchant.maker and SpiceMerchant.maker.skill or 0,activeMaking=#SpiceMerchant.activeMaking,totalProducts=SpiceMerchant.totalProducts} end
return SpiceMerchant
