local BookCoverCrimperMaker = {}
local PRODUCTS = {
    iron_bookcovercrimper = { name = "Železni gubalec naslovnic", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni gubalec naslovnic za knjigoveze." },
    bronze_bookcovercrimper = { name = "Bronast gubalec naslovnic", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast gubalec naslovnic za knjigoveze." },
    silver_bookcovercrimper = { name = "Srebrn gubalec naslovnic", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn gubalec naslovnic za knjigoveze." },
    gilded_bookcovercrimper = { name = "Pozlačen gubalec naslovnic", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen gubalec naslovnic za knjigoveze." },
    jewel_set_bookcovercrimper = { name = "Draguljast gubalec naslovnic", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast gubalec naslovnic za knjigoveze." },
    royal_sovereign_bookcovercrimper = { name = "Kraljevski suveren gubalec naslovnic", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren gubalec naslovnic z biseri za krono." },
}
local BUILDINGS = {
    bookcovercrimper_workshop = { name = "Bookcovercrimper delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookcovercrimper_house = { name = "Bookcovercrimper hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookcovercrimper_atelier = { name = "Mojstrski bookcovercrimper atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookcovercrimper_palace = { name = "Suverena bookcovercrimper palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookCoverCrimperMaker.ironStock=14; BookCoverCrimperMaker.bronzeStock=12; BookCoverCrimperMaker.woodStock=14; BookCoverCrimperMaker.leatherStock=8; BookCoverCrimperMaker.silverStock=8; BookCoverCrimperMaker.goldStock=6; BookCoverCrimperMaker.jewelStock=4; BookCoverCrimperMaker.pearlStock=4
BookCoverCrimperMaker.productStock = {}; BookCoverCrimperMaker.buildings = {}; BookCoverCrimperMaker.maker = nil; BookCoverCrimperMaker.activeMaking = {}; BookCoverCrimperMaker.totalProducts = 0; BookCoverCrimperMaker.dayTimer = 0
function BookCoverCrimperMaker.init() BookCoverCrimperMaker.ironStock=14; BookCoverCrimperMaker.bronzeStock=12; BookCoverCrimperMaker.woodStock=14; BookCoverCrimperMaker.leatherStock=8; BookCoverCrimperMaker.silverStock=8; BookCoverCrimperMaker.goldStock=6; BookCoverCrimperMaker.jewelStock=4; BookCoverCrimperMaker.pearlStock=4; BookCoverCrimperMaker.productStock={}; BookCoverCrimperMaker.buildings={}; BookCoverCrimperMaker.maker=nil; BookCoverCrimperMaker.activeMaking={}; BookCoverCrimperMaker.totalProducts=0; BookCoverCrimperMaker.dayTimer=0; print("[BookCoverCrimperMaker] Royal Book Cover Crimper Maker System initialized (6 products, 4 buildings)") end
function BookCoverCrimperMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookCoverCrimperMaker.maker={name=n or ("Gubalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gubalec najet: %s (spretnost: %d)",BookCoverCrimperMaker.maker.name,s),"success") end; return true end
function BookCoverCrimperMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookCoverCrimperMaker.build(id) local ok,e=BookCoverCrimperMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookCoverCrimperMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookCoverCrimperMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookCoverCrimperMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookCoverCrimperMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookCoverCrimperMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookCoverCrimperMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookCoverCrimperMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookCoverCrimperMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookCoverCrimperMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookCoverCrimperMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookCoverCrimperMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookCoverCrimperMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookCoverCrimperMaker.buildings==0 then return false,"Potrebna gubalna delavnica" end; if not BookCoverCrimperMaker.maker then return false,"Potreben gubalec" end; return true end
function BookCoverCrimperMaker.make(pt,qty) qty=qty or 1; local ok,e=BookCoverCrimperMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookCoverCrimperMaker.ironStock=BookCoverCrimperMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookCoverCrimperMaker.bronzeStock=BookCoverCrimperMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookCoverCrimperMaker.woodStock=BookCoverCrimperMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookCoverCrimperMaker.leatherStock=BookCoverCrimperMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookCoverCrimperMaker.silverStock=BookCoverCrimperMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookCoverCrimperMaker.goldStock=BookCoverCrimperMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookCoverCrimperMaker.jewelStock=BookCoverCrimperMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookCoverCrimperMaker.pearlStock=BookCoverCrimperMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookCoverCrimperMaker.maker then t=math.max(1,t-math.floor(BookCoverCrimperMaker.maker.skill/13)) end; table.insert(BookCoverCrimperMaker.activeMaking,{id="bookcovercrimper_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookCoverCrimperMaker.completeMaking(m) local q=1.0+(BookCoverCrimperMaker.getQualityBonus()/100); if BookCoverCrimperMaker.maker then q=q+(BookCoverCrimperMaker.maker.skill/140) end; q=math.min(2.5,q); BookCoverCrimperMaker.productStock[m.productType]=(BookCoverCrimperMaker.productStock[m.productType] or 0)+m.quantity; BookCoverCrimperMaker.totalProducts=BookCoverCrimperMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookCoverCrimperMaker.maker then BookCoverCrimperMaker.maker.itemsMade=BookCoverCrimperMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookCoverCrimperMaker.maker.skill=math.min(100,BookCoverCrimperMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gubalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookcovercrimper.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookCoverCrimperMaker.update(dt) if not _G.state then return end; BookCoverCrimperMaker.dayTimer=BookCoverCrimperMaker.dayTimer+dt; if BookCoverCrimperMaker.dayTimer>=30 then BookCoverCrimperMaker.dayTimer=0; for i=#BookCoverCrimperMaker.activeMaking,1,-1 do local m=BookCoverCrimperMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookCoverCrimperMaker.completeMaking(m); table.remove(BookCoverCrimperMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookCoverCrimperMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookCoverCrimperMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookCoverCrimperMaker.getStats() return {ironStock=BookCoverCrimperMaker.ironStock,bronzeStock=BookCoverCrimperMaker.bronzeStock,woodStock=BookCoverCrimperMaker.woodStock,leatherStock=BookCoverCrimperMaker.leatherStock,silverStock=BookCoverCrimperMaker.silverStock,goldStock=BookCoverCrimperMaker.goldStock,jewelStock=BookCoverCrimperMaker.jewelStock,pearlStock=BookCoverCrimperMaker.pearlStock,productStock=BookCoverCrimperMaker.productStock,numBuildings=#BookCoverCrimperMaker.buildings,hasMaker=BookCoverCrimperMaker.maker~=nil,makerName=BookCoverCrimperMaker.maker and BookCoverCrimperMaker.maker.name or "—",makerSkill=BookCoverCrimperMaker.maker and BookCoverCrimperMaker.maker.skill or 0,activeMaking=#BookCoverCrimperMaker.activeMaking,totalProducts=BookCoverCrimperMaker.totalProducts} end
return BookCoverCrimperMaker
