local QuiverMaker = {}
local PRODUCTS = {
    simple_leather_quiver = { name = "Preprost usnjen tulce", leatherCost = 2, woodCost = 1, time = 3, cost = 50, attack = 8, happiness = 1, description = "Preprost usnjen tulce za puščice." },
    fur_trimmed_quiver = { name = "Krznato obrobljeni tulce", leatherCost = 2, woolCost = 1, woodCost = 1, time = 5, cost = 140, attack = 12, happiness = 1, prestige = 2, description = "Krznato obrobljeni tulce za trgovce." },
    silver_buckled_quiver = { name = "Srebrnopasni tulce", leatherCost = 2, silverCost = 1, woolCost = 1, woodCost = 1, time = 8, cost = 340, attack = 18, happiness = 2, prestige = 6, description = "Srebrnopasni tulce za plemiče." },
    gold_embroidered_quiver = { name = "Zlato vezani tulce", leatherCost = 2, goldCost = 1, silverCost = 1, woolCost = 1, woodCost = 1, time = 12, cost = 800, attack = 24, happiness = 3, prestige = 14, description = "Zlato vezani tulce za visoke plemiče." },
    jewel_set_quiver = { name = "Draguljasta tulce", leatherCost = 2, goldCost = 1, silverCost = 1, woolCost = 1, woodCost = 1, jewelCost = 1, time = 16, cost = 1800, attack = 32, happiness = 5, prestige = 27, description = "Tulce z draguljem za visoko plemstvo." },
    royal_grand_quiver = { name = "Kraljevski veliki tulce", leatherCost = 3, goldCost = 2, silverCost = 2, woolCost = 1, woodCost = 1, jewelCost = 2, pearlCost = 2, time = 23, cost = 4000, attack = 45, happiness = 12, prestige = 58, description = "Veliki kraljevski tulce z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    quiver_workshop = { name = "Tulce delavnica", cost = { gold = 240, wood = 120, stone = 100, leather = 6 }, upkeep = 5, qualityBonus = 5 },
    leather_loft = { name = "Usnjena podstrešje", cost = { gold = 880, wood = 240, stone = 220, silver = 6, wool = 6 }, upkeep = 20, qualityBonus = 18 },
    master_leather_atelier = { name = "Mojstrski usnjarski atelje", cost = { gold = 2500, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 58, qualityBonus = 30 },
    royal_quiver_palace = { name = "Kraljevska tulce palača", cost = { gold = 10500, wood = 580, stone = 760, gold = 65, jewel = 16 }, upkeep = 210, qualityBonus = 55, prestigeBonus = 50 },
}
QuiverMaker.leatherStock = 14; QuiverMaker.woodStock = 12; QuiverMaker.woolStock = 10; QuiverMaker.silverStock = 6; QuiverMaker.goldStock = 6; QuiverMaker.jewelStock = 4; QuiverMaker.pearlStock = 4
QuiverMaker.productStock = {}; QuiverMaker.buildings = {}; QuiverMaker.maker = nil; QuiverMaker.activeMaking = {}; QuiverMaker.totalProducts = 0; QuiverMaker.dayTimer = 0
function QuiverMaker.init() QuiverMaker.leatherStock=14; QuiverMaker.woodStock=12; QuiverMaker.woolStock=10; QuiverMaker.silverStock=6; QuiverMaker.goldStock=6; QuiverMaker.jewelStock=4; QuiverMaker.pearlStock=4; QuiverMaker.productStock={}; QuiverMaker.buildings={}; QuiverMaker.maker=nil; QuiverMaker.activeMaking={}; QuiverMaker.totalProducts=0; QuiverMaker.dayTimer=0; print("[QuiverMaker] Royal Quiver Maker System initialized (6 products, 4 buildings)") end
function QuiverMaker.hireMaker(n,s) s=s or math.random(55,90); local c=500+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; QuiverMaker.maker={name=n or ("Tulcar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tulcar najet: %s (spretnost: %d)",QuiverMaker.maker.name,s),"success") end; return true end
function QuiverMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function QuiverMaker.build(id) local ok,e=QuiverMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(QuiverMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function QuiverMaker.getQualityBonus() local b=0; for _,bd in ipairs(QuiverMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function QuiverMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.leatherCost and QuiverMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.woodCost and QuiverMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.woolCost and QuiverMaker.woolStock<(d.woolCost or 0) then return false,"Premalo volne" end; if d.silverCost and QuiverMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and QuiverMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and QuiverMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and QuiverMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #QuiverMaker.buildings==0 then return false,"Potrebna tulce delavnica" end; if not QuiverMaker.maker then return false,"Potreben tulcar" end; return true end
function QuiverMaker.make(pt,qty) qty=qty or 1; local ok,e=QuiverMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.leatherCost then QuiverMaker.leatherStock=QuiverMaker.leatherStock-d.leatherCost*qty end; if d.woodCost then QuiverMaker.woodStock=QuiverMaker.woodStock-d.woodCost*qty end; if d.woolCost then QuiverMaker.woolStock=QuiverMaker.woolStock-d.woolCost*qty end; if d.silverCost then QuiverMaker.silverStock=QuiverMaker.silverStock-d.silverCost*qty end; if d.goldCost then QuiverMaker.goldStock=QuiverMaker.goldStock-d.goldCost*qty end; if d.jewelCost then QuiverMaker.jewelStock=QuiverMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then QuiverMaker.pearlStock=QuiverMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if QuiverMaker.maker then t=math.max(1,t-math.floor(QuiverMaker.maker.skill/13)) end; table.insert(QuiverMaker.activeMaking,{id="quiver_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,attack=d.attack or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Šivanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function QuiverMaker.completeMaking(m) local q=1.0+(QuiverMaker.getQualityBonus()/100); if QuiverMaker.maker then q=q+(QuiverMaker.maker.skill/140) end; q=math.min(2.5,q); QuiverMaker.productStock[m.productType]=(QuiverMaker.productStock[m.productType] or 0)+m.quantity; QuiverMaker.totalProducts=QuiverMaker.totalProducts+m.quantity; if m.attack>0 and _G.state then _G.state.attack=(_G.state.attack or 0)+m.attack end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if QuiverMaker.maker then QuiverMaker.maker.itemsMade=QuiverMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then QuiverMaker.maker.skill=math.min(100,QuiverMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tulce izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"quiver.completed",{productName=m.productName,attack=m.attack,prestige=m.prestige,happiness=m.happiness}) end end
function QuiverMaker.update(dt) if not _G.state then return end; QuiverMaker.dayTimer=QuiverMaker.dayTimer+dt; if QuiverMaker.dayTimer>=30 then QuiverMaker.dayTimer=0; for i=#QuiverMaker.activeMaking,1,-1 do local m=QuiverMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then QuiverMaker.completeMaking(m); table.remove(QuiverMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(QuiverMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if QuiverMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function QuiverMaker.getStats() return {leatherStock=QuiverMaker.leatherStock,woodStock=QuiverMaker.woodStock,woolStock=QuiverMaker.woolStock,silverStock=QuiverMaker.silverStock,goldStock=QuiverMaker.goldStock,jewelStock=QuiverMaker.jewelStock,pearlStock=QuiverMaker.pearlStock,productStock=QuiverMaker.productStock,numBuildings=#QuiverMaker.buildings,hasMaker=QuiverMaker.maker~=nil,makerName=QuiverMaker.maker and QuiverMaker.maker.name or "—",makerSkill=QuiverMaker.maker and QuiverMaker.maker.skill or 0,activeMaking=#QuiverMaker.activeMaking,totalProducts=QuiverMaker.totalProducts} end
return QuiverMaker
