local GardenSoilThermometerMaker = {}
local PRODUCTS = {
    iron_gardensoilthermometer = { name = "Železni termometer za prst", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni termometer za prst za vrtnarje." },
    bronze_gardensoilthermometer = { name = "Bronast termometer za prst", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast termometer za prst za vrtnarje." },
    silver_gardensoilthermometer = { name = "Srebrn termometer za prst", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn termometer za prst za vrtnarje." },
    gilded_gardensoilthermometer = { name = "Pozlačen termometer za prst", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen termometer za prst za vrtnarje." },
    jewel_set_gardensoilthermometer = { name = "Draguljast termometer za prst", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast termometer za prst za vrtnarje." },
    royal_sovereign_gardensoilthermometer = { name = "Kraljevski suveren termometer za prst", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren termometer za prst z biseri za krono." },
}
local BUILDINGS = {
    gardensoilthermometer_workshop = { name = "Gardensoilthermometer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardensoilthermometer_house = { name = "Gardensoilthermometer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardensoilthermometer_atelier = { name = "Mojstrski gardensoilthermometer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardensoilthermometer_palace = { name = "Suverena gardensoilthermometer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenSoilThermometerMaker.ironStock=14; GardenSoilThermometerMaker.bronzeStock=12; GardenSoilThermometerMaker.woodStock=12; GardenSoilThermometerMaker.leatherStock=8; GardenSoilThermometerMaker.silverStock=8; GardenSoilThermometerMaker.goldStock=6; GardenSoilThermometerMaker.jewelStock=4; GardenSoilThermometerMaker.pearlStock=4
GardenSoilThermometerMaker.productStock = {}; GardenSoilThermometerMaker.buildings = {}; GardenSoilThermometerMaker.maker = nil; GardenSoilThermometerMaker.activeMaking = {}; GardenSoilThermometerMaker.totalProducts = 0; GardenSoilThermometerMaker.dayTimer = 0
function GardenSoilThermometerMaker.init() GardenSoilThermometerMaker.ironStock=14; GardenSoilThermometerMaker.bronzeStock=12; GardenSoilThermometerMaker.woodStock=12; GardenSoilThermometerMaker.leatherStock=8; GardenSoilThermometerMaker.silverStock=8; GardenSoilThermometerMaker.goldStock=6; GardenSoilThermometerMaker.jewelStock=4; GardenSoilThermometerMaker.pearlStock=4; GardenSoilThermometerMaker.productStock={}; GardenSoilThermometerMaker.buildings={}; GardenSoilThermometerMaker.maker=nil; GardenSoilThermometerMaker.activeMaking={}; GardenSoilThermometerMaker.totalProducts=0; GardenSoilThermometerMaker.dayTimer=0; print("[GardenSoilThermometerMaker] Royal Garden Soil Thermometer Maker System initialized (6 products, 4 buildings)") end
function GardenSoilThermometerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenSoilThermometerMaker.maker={name=n or ("Termometrar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Termometrar najet: %s (spretnost: %d)",GardenSoilThermometerMaker.maker.name,s),"success") end; return true end
function GardenSoilThermometerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenSoilThermometerMaker.build(id) local ok,e=GardenSoilThermometerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenSoilThermometerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenSoilThermometerMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenSoilThermometerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenSoilThermometerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenSoilThermometerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenSoilThermometerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenSoilThermometerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenSoilThermometerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenSoilThermometerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenSoilThermometerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenSoilThermometerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenSoilThermometerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenSoilThermometerMaker.buildings==0 then return false,"Potrebna termometrska delavnica" end; if not GardenSoilThermometerMaker.maker then return false,"Potreben termometrar" end; return true end
function GardenSoilThermometerMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenSoilThermometerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenSoilThermometerMaker.ironStock=GardenSoilThermometerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenSoilThermometerMaker.bronzeStock=GardenSoilThermometerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenSoilThermometerMaker.woodStock=GardenSoilThermometerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenSoilThermometerMaker.leatherStock=GardenSoilThermometerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenSoilThermometerMaker.silverStock=GardenSoilThermometerMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenSoilThermometerMaker.goldStock=GardenSoilThermometerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenSoilThermometerMaker.jewelStock=GardenSoilThermometerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenSoilThermometerMaker.pearlStock=GardenSoilThermometerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenSoilThermometerMaker.maker then t=math.max(1,t-math.floor(GardenSoilThermometerMaker.maker.skill/13)) end; table.insert(GardenSoilThermometerMaker.activeMaking,{id="gardensoilthermometer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenSoilThermometerMaker.completeMaking(m) local q=1.0+(GardenSoilThermometerMaker.getQualityBonus()/100); if GardenSoilThermometerMaker.maker then q=q+(GardenSoilThermometerMaker.maker.skill/140) end; q=math.min(2.5,q); GardenSoilThermometerMaker.productStock[m.productType]=(GardenSoilThermometerMaker.productStock[m.productType] or 0)+m.quantity; GardenSoilThermometerMaker.totalProducts=GardenSoilThermometerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenSoilThermometerMaker.maker then GardenSoilThermometerMaker.maker.itemsMade=GardenSoilThermometerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenSoilThermometerMaker.maker.skill=math.min(100,GardenSoilThermometerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Termometer izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardensoilthermometer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenSoilThermometerMaker.update(dt) if not _G.state then return end; GardenSoilThermometerMaker.dayTimer=GardenSoilThermometerMaker.dayTimer+dt; if GardenSoilThermometerMaker.dayTimer>=30 then GardenSoilThermometerMaker.dayTimer=0; for i=#GardenSoilThermometerMaker.activeMaking,1,-1 do local m=GardenSoilThermometerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenSoilThermometerMaker.completeMaking(m); table.remove(GardenSoilThermometerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenSoilThermometerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenSoilThermometerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenSoilThermometerMaker.getStats() return {ironStock=GardenSoilThermometerMaker.ironStock,bronzeStock=GardenSoilThermometerMaker.bronzeStock,woodStock=GardenSoilThermometerMaker.woodStock,leatherStock=GardenSoilThermometerMaker.leatherStock,silverStock=GardenSoilThermometerMaker.silverStock,goldStock=GardenSoilThermometerMaker.goldStock,jewelStock=GardenSoilThermometerMaker.jewelStock,pearlStock=GardenSoilThermometerMaker.pearlStock,productStock=GardenSoilThermometerMaker.productStock,numBuildings=#GardenSoilThermometerMaker.buildings,hasMaker=GardenSoilThermometerMaker.maker~=nil,makerName=GardenSoilThermometerMaker.maker and GardenSoilThermometerMaker.maker.name or "—",makerSkill=GardenSoilThermometerMaker.maker and GardenSoilThermometerMaker.maker.skill or 0,activeMaking=#GardenSoilThermometerMaker.activeMaking,totalProducts=GardenSoilThermometerMaker.totalProducts} end
return GardenSoilThermometerMaker
