local GlockenspielMaker = {}
local PRODUCTS = {
    simple_iron_glockenspiel = { name = "Preprosti železni glockenspiel", ironCost = 2, woodCost = 2, time = 5, cost = 180, happiness = 1, prestige = 2, description = "Preprost glockenspiel z železnimi palčkami." },
    brass_tuned_glockenspiel = { name = "Medeninasto uglašen glockenspiel", brassCost = 2, ironCost = 1, woodCost = 2, time = 8, cost = 420, happiness = 2, prestige = 5, description = "Medeninast glockenspiel za dvorno glasbo." },
    silver_bar_glockenspiel = { name = "Srebrnopalični glockenspiel", silverCost = 2, brassCost = 1, ironCost = 1, woodCost = 2, time = 12, cost = 1100, happiness = 3, prestige = 11, description = "Srebrnopalični glockenspiel za plemiče." },
    gilded_court_glockenspiel = { name = "Pozlačeni dvorni glockenspiel", goldCost = 1, silverCost = 2, brassCost = 1, woodCost = 2, time = 16, cost = 2500, happiness = 4, prestige = 21, description = "Pozlačeni dvorni glockenspiel za slavnosti." },
    jewel_set_royal_glockenspiel = { name = "Draguljasta kraljevski glockenspiel", goldCost = 2, silverCost = 2, jewelCost = 1, brassCost = 1, woodCost = 2, time = 20, cost = 5200, happiness = 6, prestige = 38, description = "Draguljasti glockenspiel za kraljevo glasbo." },
    sovereign_grand_glockenspiel = { name = "Suvereni veliki glockenspiel", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, brassCost = 1, woodCost = 3, time = 27, cost = 11000, happiness = 12, prestige = 76, description = "Veliki suvereni glockenspiel z biseri za krono." },
}
local BUILDINGS = {
    glockenspiel_workshop = { name = "Glockenspiel delavnica", cost = { gold = 340, wood = 160, stone = 120, iron = 6 }, upkeep = 6, qualityBonus = 5 },
    tuned_percussion_house = { name = "Tonsko-udarna hiša", cost = { gold = 1200, wood = 320, stone = 240, silver = 6, iron = 6 }, upkeep = 26, qualityBonus = 18 },
    master_glockenspiel_atelier = { name = "Mojstrski glockenspiel atelje", cost = { gold = 3000, wood = 400, stone = 500, silver = 36, gold = 6 }, upkeep = 72, qualityBonus = 30 },
    sovereign_celesta_palace = { name = "Suverena celesta palača", cost = { gold = 13500, wood = 650, stone = 850, gold = 85, jewel = 18 }, upkeep = 255, qualityBonus = 55, prestigeBonus = 50 },
}
GlockenspielMaker.ironStock = 12; GlockenspielMaker.brassStock = 10; GlockenspielMaker.woodStock = 14; GlockenspielMaker.silverStock = 8; GlockenspielMaker.goldStock = 6; GlockenspielMaker.jewelStock = 4; GlockenspielMaker.pearlStock = 4
GlockenspielMaker.productStock = {}; GlockenspielMaker.buildings = {}; GlockenspielMaker.maker = nil; GlockenspielMaker.activeMaking = {}; GlockenspielMaker.totalProducts = 0; GlockenspielMaker.dayTimer = 0
function GlockenspielMaker.init() GlockenspielMaker.ironStock=12; GlockenspielMaker.brassStock=10; GlockenspielMaker.woodStock=14; GlockenspielMaker.silverStock=8; GlockenspielMaker.goldStock=6; GlockenspielMaker.jewelStock=4; GlockenspielMaker.pearlStock=4; GlockenspielMaker.productStock={}; GlockenspielMaker.buildings={}; GlockenspielMaker.maker=nil; GlockenspielMaker.activeMaking={}; GlockenspielMaker.totalProducts=0; GlockenspielMaker.dayTimer=0; print("[GlockenspielMaker] Royal Glockenspiel Maker System initialized (6 products, 4 buildings)") end
function GlockenspielMaker.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlockenspielMaker.maker={name=n or ("Glockenspieler "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Glockenspieler najet: %s (spretnost: %d)",GlockenspielMaker.maker.name,s),"success") end; return true end
function GlockenspielMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlockenspielMaker.build(id) local ok,e=GlockenspielMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlockenspielMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlockenspielMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlockenspielMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlockenspielMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlockenspielMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.brassCost and GlockenspielMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.woodCost and GlockenspielMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.silverCost and GlockenspielMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlockenspielMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlockenspielMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlockenspielMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlockenspielMaker.buildings==0 then return false,"Potrebna glockenspiel delavnica" end; if not GlockenspielMaker.maker then return false,"Potreben glockenspieler" end; return true end
function GlockenspielMaker.make(pt,qty) qty=qty or 1; local ok,e=GlockenspielMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlockenspielMaker.ironStock=GlockenspielMaker.ironStock-d.ironCost*qty end; if d.brassCost then GlockenspielMaker.brassStock=GlockenspielMaker.brassStock-d.brassCost*qty end; if d.woodCost then GlockenspielMaker.woodStock=GlockenspielMaker.woodStock-d.woodCost*qty end; if d.silverCost then GlockenspielMaker.silverStock=GlockenspielMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlockenspielMaker.goldStock=GlockenspielMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlockenspielMaker.jewelStock=GlockenspielMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlockenspielMaker.pearlStock=GlockenspielMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlockenspielMaker.maker then t=math.max(1,t-math.floor(GlockenspielMaker.maker.skill/13)) end; table.insert(GlockenspielMaker.activeMaking,{id="glockenspiel_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlockenspielMaker.completeMaking(m) local q=1.0+(GlockenspielMaker.getQualityBonus()/100); if GlockenspielMaker.maker then q=q+(GlockenspielMaker.maker.skill/140) end; q=math.min(2.5,q); GlockenspielMaker.productStock[m.productType]=(GlockenspielMaker.productStock[m.productType] or 0)+m.quantity; GlockenspielMaker.totalProducts=GlockenspielMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlockenspielMaker.maker then GlockenspielMaker.maker.itemsMade=GlockenspielMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlockenspielMaker.maker.skill=math.min(100,GlockenspielMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Glockenspiel izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glockenspiel.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlockenspielMaker.update(dt) if not _G.state then return end; GlockenspielMaker.dayTimer=GlockenspielMaker.dayTimer+dt; if GlockenspielMaker.dayTimer>=30 then GlockenspielMaker.dayTimer=0; for i=#GlockenspielMaker.activeMaking,1,-1 do local m=GlockenspielMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlockenspielMaker.completeMaking(m); table.remove(GlockenspielMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlockenspielMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlockenspielMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlockenspielMaker.getStats() return {ironStock=GlockenspielMaker.ironStock,brassStock=GlockenspielMaker.brassStock,woodStock=GlockenspielMaker.woodStock,silverStock=GlockenspielMaker.silverStock,goldStock=GlockenspielMaker.goldStock,jewelStock=GlockenspielMaker.jewelStock,pearlStock=GlockenspielMaker.pearlStock,productStock=GlockenspielMaker.productStock,numBuildings=#GlockenspielMaker.buildings,hasMaker=GlockenspielMaker.maker~=nil,makerName=GlockenspielMaker.maker and GlockenspielMaker.maker.name or "—",makerSkill=GlockenspielMaker.maker and GlockenspielMaker.maker.skill or 0,activeMaking=#GlockenspielMaker.activeMaking,totalProducts=GlockenspielMaker.totalProducts} end
return GlockenspielMaker
