local BookEdgePolishingStoneMaker = {}
local PRODUCTS = {
    iron_bookedgepolishingstone = { name = "Železni polirni kamen za robove", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni polirni kamen za robove za knjigoveze." },
    bronze_bookedgepolishingstone = { name = "Bronast polirni kamen za robove", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast polirni kamen za robove za knjigoveze." },
    silver_bookedgepolishingstone = { name = "Srebrn polirni kamen za robove", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn polirni kamen za robove za knjigoveze." },
    gilded_bookedgepolishingstone = { name = "Pozlačen polirni kamen za robove", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen polirni kamen za robove za knjigoveze." },
    jewel_set_bookedgepolishingstone = { name = "Draguljast polirni kamen za robove", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast polirni kamen za robove za knjigoveze." },
    royal_sovereign_bookedgepolishingstone = { name = "Kraljevski suveren polirni kamen za robove", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren polirni kamen za robove z biseri za krono." },
}
local BUILDINGS = {
    bookedgepolishingstone_workshop = { name = "Bookedgepolishingstone delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookedgepolishingstone_house = { name = "Bookedgepolishingstone hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookedgepolishingstone_atelier = { name = "Mojstrski bookedgepolishingstone atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookedgepolishingstone_palace = { name = "Suverena bookedgepolishingstone palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookEdgePolishingStoneMaker.ironStock=12; BookEdgePolishingStoneMaker.bronzeStock=10; BookEdgePolishingStoneMaker.woodStock=14; BookEdgePolishingStoneMaker.leatherStock=8; BookEdgePolishingStoneMaker.silverStock=8; BookEdgePolishingStoneMaker.goldStock=6; BookEdgePolishingStoneMaker.jewelStock=4; BookEdgePolishingStoneMaker.pearlStock=4
BookEdgePolishingStoneMaker.productStock = {}; BookEdgePolishingStoneMaker.buildings = {}; BookEdgePolishingStoneMaker.maker = nil; BookEdgePolishingStoneMaker.activeMaking = {}; BookEdgePolishingStoneMaker.totalProducts = 0; BookEdgePolishingStoneMaker.dayTimer = 0
function BookEdgePolishingStoneMaker.init() BookEdgePolishingStoneMaker.ironStock=12; BookEdgePolishingStoneMaker.bronzeStock=10; BookEdgePolishingStoneMaker.woodStock=14; BookEdgePolishingStoneMaker.leatherStock=8; BookEdgePolishingStoneMaker.silverStock=8; BookEdgePolishingStoneMaker.goldStock=6; BookEdgePolishingStoneMaker.jewelStock=4; BookEdgePolishingStoneMaker.pearlStock=4; BookEdgePolishingStoneMaker.productStock={}; BookEdgePolishingStoneMaker.buildings={}; BookEdgePolishingStoneMaker.maker=nil; BookEdgePolishingStoneMaker.activeMaking={}; BookEdgePolishingStoneMaker.totalProducts=0; BookEdgePolishingStoneMaker.dayTimer=0; print("[BookEdgePolishingStoneMaker] Royal Book Edge Polishing Stone Maker System initialized (6 products, 4 buildings)") end
function BookEdgePolishingStoneMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookEdgePolishingStoneMaker.maker={name=n or ("Kamnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kamnar najet: %s (spretnost: %d)",BookEdgePolishingStoneMaker.maker.name,s),"success") end; return true end
function BookEdgePolishingStoneMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookEdgePolishingStoneMaker.build(id) local ok,e=BookEdgePolishingStoneMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookEdgePolishingStoneMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookEdgePolishingStoneMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookEdgePolishingStoneMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookEdgePolishingStoneMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookEdgePolishingStoneMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookEdgePolishingStoneMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookEdgePolishingStoneMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookEdgePolishingStoneMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookEdgePolishingStoneMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookEdgePolishingStoneMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookEdgePolishingStoneMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookEdgePolishingStoneMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookEdgePolishingStoneMaker.buildings==0 then return false,"Potrebna kamnarska delavnica" end; if not BookEdgePolishingStoneMaker.maker then return false,"Potreben kamnar" end; return true end
function BookEdgePolishingStoneMaker.make(pt,qty) qty=qty or 1; local ok,e=BookEdgePolishingStoneMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookEdgePolishingStoneMaker.ironStock=BookEdgePolishingStoneMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookEdgePolishingStoneMaker.bronzeStock=BookEdgePolishingStoneMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookEdgePolishingStoneMaker.woodStock=BookEdgePolishingStoneMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookEdgePolishingStoneMaker.leatherStock=BookEdgePolishingStoneMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookEdgePolishingStoneMaker.silverStock=BookEdgePolishingStoneMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookEdgePolishingStoneMaker.goldStock=BookEdgePolishingStoneMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookEdgePolishingStoneMaker.jewelStock=BookEdgePolishingStoneMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookEdgePolishingStoneMaker.pearlStock=BookEdgePolishingStoneMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookEdgePolishingStoneMaker.maker then t=math.max(1,t-math.floor(BookEdgePolishingStoneMaker.maker.skill/13)) end; table.insert(BookEdgePolishingStoneMaker.activeMaking,{id="bookedgepolishingstone_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookEdgePolishingStoneMaker.completeMaking(m) local q=1.0+(BookEdgePolishingStoneMaker.getQualityBonus()/100); if BookEdgePolishingStoneMaker.maker then q=q+(BookEdgePolishingStoneMaker.maker.skill/140) end; q=math.min(2.5,q); BookEdgePolishingStoneMaker.productStock[m.productType]=(BookEdgePolishingStoneMaker.productStock[m.productType] or 0)+m.quantity; BookEdgePolishingStoneMaker.totalProducts=BookEdgePolishingStoneMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookEdgePolishingStoneMaker.maker then BookEdgePolishingStoneMaker.maker.itemsMade=BookEdgePolishingStoneMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookEdgePolishingStoneMaker.maker.skill=math.min(100,BookEdgePolishingStoneMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kamen izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookedgepolishingstone.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookEdgePolishingStoneMaker.update(dt) if not _G.state then return end; BookEdgePolishingStoneMaker.dayTimer=BookEdgePolishingStoneMaker.dayTimer+dt; if BookEdgePolishingStoneMaker.dayTimer>=30 then BookEdgePolishingStoneMaker.dayTimer=0; for i=#BookEdgePolishingStoneMaker.activeMaking,1,-1 do local m=BookEdgePolishingStoneMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookEdgePolishingStoneMaker.completeMaking(m); table.remove(BookEdgePolishingStoneMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookEdgePolishingStoneMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookEdgePolishingStoneMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookEdgePolishingStoneMaker.getStats() return {ironStock=BookEdgePolishingStoneMaker.ironStock,bronzeStock=BookEdgePolishingStoneMaker.bronzeStock,woodStock=BookEdgePolishingStoneMaker.woodStock,leatherStock=BookEdgePolishingStoneMaker.leatherStock,silverStock=BookEdgePolishingStoneMaker.silverStock,goldStock=BookEdgePolishingStoneMaker.goldStock,jewelStock=BookEdgePolishingStoneMaker.jewelStock,pearlStock=BookEdgePolishingStoneMaker.pearlStock,productStock=BookEdgePolishingStoneMaker.productStock,numBuildings=#BookEdgePolishingStoneMaker.buildings,hasMaker=BookEdgePolishingStoneMaker.maker~=nil,makerName=BookEdgePolishingStoneMaker.maker and BookEdgePolishingStoneMaker.maker.name or "—",makerSkill=BookEdgePolishingStoneMaker.maker and BookEdgePolishingStoneMaker.maker.skill or 0,activeMaking=#BookEdgePolishingStoneMaker.activeMaking,totalProducts=BookEdgePolishingStoneMaker.totalProducts} end
return BookEdgePolishingStoneMaker
