local MillstoneSpindleBearingMaker = {}
local PRODUCTS = {
    iron_millstonespindlebearing = { name = "Železni lezaj za vretena kamnov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni lezaj za vretena kamnov za mlinarje." },
    bronze_millstonespindlebearing = { name = "Bronast lezaj za vretena kamnov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast lezaj za vretena kamnov za mlinarje." },
    silver_millstonespindlebearing = { name = "Srebrn lezaj za vretena kamnov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn lezaj za vretena kamnov za mlinarje." },
    gilded_millstonespindlebearing = { name = "Pozlačen lezaj za vretena kamnov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen lezaj za vretena kamnov za mlinarje." },
    jewel_set_millstonespindlebearing = { name = "Draguljast lezaj za vretena kamnov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast lezaj za vretena kamnov za mlinarje." },
    royal_sovereign_millstonespindlebearing = { name = "Kraljevski suveren lezaj za vretena kamnov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren lezaj za vretena kamnov z biseri za krono." },
}
local BUILDINGS = {
    millstonespindlebearing_workshop = { name = "Millstonespindlebearing delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    millstonespindlebearing_house = { name = "Millstonespindlebearing hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_millstonespindlebearing_atelier = { name = "Mojstrski millstonespindlebearing atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_millstonespindlebearing_palace = { name = "Suverena millstonespindlebearing palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillstoneSpindleBearingMaker.ironStock=18; MillstoneSpindleBearingMaker.bronzeStock=14; MillstoneSpindleBearingMaker.woodStock=10; MillstoneSpindleBearingMaker.leatherStock=8; MillstoneSpindleBearingMaker.silverStock=8; MillstoneSpindleBearingMaker.goldStock=6; MillstoneSpindleBearingMaker.jewelStock=4; MillstoneSpindleBearingMaker.pearlStock=4
MillstoneSpindleBearingMaker.productStock = {}; MillstoneSpindleBearingMaker.buildings = {}; MillstoneSpindleBearingMaker.maker = nil; MillstoneSpindleBearingMaker.activeMaking = {}; MillstoneSpindleBearingMaker.totalProducts = 0; MillstoneSpindleBearingMaker.dayTimer = 0
function MillstoneSpindleBearingMaker.init() MillstoneSpindleBearingMaker.ironStock=18; MillstoneSpindleBearingMaker.bronzeStock=14; MillstoneSpindleBearingMaker.woodStock=10; MillstoneSpindleBearingMaker.leatherStock=8; MillstoneSpindleBearingMaker.silverStock=8; MillstoneSpindleBearingMaker.goldStock=6; MillstoneSpindleBearingMaker.jewelStock=4; MillstoneSpindleBearingMaker.pearlStock=4; MillstoneSpindleBearingMaker.productStock={}; MillstoneSpindleBearingMaker.buildings={}; MillstoneSpindleBearingMaker.maker=nil; MillstoneSpindleBearingMaker.activeMaking={}; MillstoneSpindleBearingMaker.totalProducts=0; MillstoneSpindleBearingMaker.dayTimer=0; print("[MillstoneSpindleBearingMaker] Royal Millstone Spindle Bearing Maker System initialized (6 products, 4 buildings)") end
function MillstoneSpindleBearingMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillstoneSpindleBearingMaker.maker={name=n or ("Ležajnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ležajnik najet: %s (spretnost: %d)",MillstoneSpindleBearingMaker.maker.name,s),"success") end; return true end
function MillstoneSpindleBearingMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillstoneSpindleBearingMaker.build(id) local ok,e=MillstoneSpindleBearingMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillstoneSpindleBearingMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillstoneSpindleBearingMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillstoneSpindleBearingMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillstoneSpindleBearingMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillstoneSpindleBearingMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillstoneSpindleBearingMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillstoneSpindleBearingMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillstoneSpindleBearingMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillstoneSpindleBearingMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillstoneSpindleBearingMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillstoneSpindleBearingMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillstoneSpindleBearingMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillstoneSpindleBearingMaker.buildings==0 then return false,"Potrebna lezajna delavnica" end; if not MillstoneSpindleBearingMaker.maker then return false,"Potreben lezajnik" end; return true end
function MillstoneSpindleBearingMaker.make(pt,qty) qty=qty or 1; local ok,e=MillstoneSpindleBearingMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillstoneSpindleBearingMaker.ironStock=MillstoneSpindleBearingMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillstoneSpindleBearingMaker.bronzeStock=MillstoneSpindleBearingMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillstoneSpindleBearingMaker.woodStock=MillstoneSpindleBearingMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillstoneSpindleBearingMaker.leatherStock=MillstoneSpindleBearingMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillstoneSpindleBearingMaker.silverStock=MillstoneSpindleBearingMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillstoneSpindleBearingMaker.goldStock=MillstoneSpindleBearingMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillstoneSpindleBearingMaker.jewelStock=MillstoneSpindleBearingMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillstoneSpindleBearingMaker.pearlStock=MillstoneSpindleBearingMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillstoneSpindleBearingMaker.maker then t=math.max(1,t-math.floor(MillstoneSpindleBearingMaker.maker.skill/13)) end; table.insert(MillstoneSpindleBearingMaker.activeMaking,{id="millstonespindlebearing_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillstoneSpindleBearingMaker.completeMaking(m) local q=1.0+(MillstoneSpindleBearingMaker.getQualityBonus()/100); if MillstoneSpindleBearingMaker.maker then q=q+(MillstoneSpindleBearingMaker.maker.skill/140) end; q=math.min(2.5,q); MillstoneSpindleBearingMaker.productStock[m.productType]=(MillstoneSpindleBearingMaker.productStock[m.productType] or 0)+m.quantity; MillstoneSpindleBearingMaker.totalProducts=MillstoneSpindleBearingMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillstoneSpindleBearingMaker.maker then MillstoneSpindleBearingMaker.maker.itemsMade=MillstoneSpindleBearingMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillstoneSpindleBearingMaker.maker.skill=math.min(100,MillstoneSpindleBearingMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ležaj izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millstonespindlebearing.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillstoneSpindleBearingMaker.update(dt) if not _G.state then return end; MillstoneSpindleBearingMaker.dayTimer=MillstoneSpindleBearingMaker.dayTimer+dt; if MillstoneSpindleBearingMaker.dayTimer>=30 then MillstoneSpindleBearingMaker.dayTimer=0; for i=#MillstoneSpindleBearingMaker.activeMaking,1,-1 do local m=MillstoneSpindleBearingMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillstoneSpindleBearingMaker.completeMaking(m); table.remove(MillstoneSpindleBearingMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillstoneSpindleBearingMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillstoneSpindleBearingMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillstoneSpindleBearingMaker.getStats() return {ironStock=MillstoneSpindleBearingMaker.ironStock,bronzeStock=MillstoneSpindleBearingMaker.bronzeStock,woodStock=MillstoneSpindleBearingMaker.woodStock,leatherStock=MillstoneSpindleBearingMaker.leatherStock,silverStock=MillstoneSpindleBearingMaker.silverStock,goldStock=MillstoneSpindleBearingMaker.goldStock,jewelStock=MillstoneSpindleBearingMaker.jewelStock,pearlStock=MillstoneSpindleBearingMaker.pearlStock,productStock=MillstoneSpindleBearingMaker.productStock,numBuildings=#MillstoneSpindleBearingMaker.buildings,hasMaker=MillstoneSpindleBearingMaker.maker~=nil,makerName=MillstoneSpindleBearingMaker.maker and MillstoneSpindleBearingMaker.maker.name or "—",makerSkill=MillstoneSpindleBearingMaker.maker and MillstoneSpindleBearingMaker.maker.skill or 0,activeMaking=#MillstoneSpindleBearingMaker.activeMaking,totalProducts=MillstoneSpindleBearingMaker.totalProducts} end
return MillstoneSpindleBearingMaker
