local MedalMinter = {}
local PRODUCTS = {
    bronze_service_medal = { name = "Bronasta službena medalja", bronzeCost = 1, ironCost = 1, time = 5, cost = 120, prestige = 3, happiness = 1, description = "Bronasta medalja za zasluge." },
    silver_bravery_medal = { name = "Srebrna medalja za hrabrost", silverCost = 1, ironCost = 1, time = 7, cost = 320, prestige = 7, happiness = 2, description = "Srebrna medalja za vojaško hrabrost." },
    gilded_merit_medal = { name = "Pozlačena medalja za zasluge", goldCost = 1, silverCost = 1, time = 11, cost = 780, prestige = 14, happiness = 3, description = "Pozlačena medalja za civilne zasluge." },
    jewel_set_civic_medal = { name = "Draguljasta meščanska medalja", goldCost = 1, silverCost = 1, jewelCost = 1, time = 15, cost = 1700, prestige = 24, happiness = 4, description = "Draguljasta medalja za meščanske dosežke." },
    grand_cross_medal = { name = "Veliki križec medalja", goldCost = 2, silverCost = 2, jewelCost = 1, time = 19, cost = 3700, prestige = 41, happiness = 6, description = "Veliki križec za visoke plemiče." },
    royal_sovereign_medal = { name = "Kraljevska suverena medalja", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, time = 26, cost = 8200, prestige = 78, happiness = 12, description = "Najvišja suverena medalja s trebuhi in biseri." },
}
local BUILDINGS = {
    medal_workshop = { name = "Medaljarska delavnica", cost = { gold = 320, wood = 140, stone = 120, iron = 6 }, upkeep = 6, qualityBonus = 5 },
    royal_mint_annex = { name = "Kraljevska kovnica priključek", cost = { gold = 1100, wood = 280, stone = 240, silver = 6, iron = 6 }, upkeep = 24, qualityBonus = 18 },
    master_medal_atelier = { name = "Mojstrski medaljarski atelje", cost = { gold = 2900, wood = 360, stone = 480, silver = 32, gold = 6 }, upkeep = 68, qualityBonus = 30 },
    sovereign_mint_palace = { name = "Suverena kovniška palača", cost = { gold = 12500, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 245, qualityBonus = 55, prestigeBonus = 50 },
}
MedalMinter.bronzeStock = 12; MedalMinter.ironStock = 10; MedalMinter.silverStock = 8; MedalMinter.goldStock = 6; MedalMinter.jewelStock = 4; MedalMinter.pearlStock = 4
MedalMinter.productStock = {}; MedalMinter.buildings = {}; MedalMinter.maker = nil; MedalMinter.activeMaking = {}; MedalMinter.totalProducts = 0; MedalMinter.dayTimer = 0
function MedalMinter.init() MedalMinter.bronzeStock=12; MedalMinter.ironStock=10; MedalMinter.silverStock=8; MedalMinter.goldStock=6; MedalMinter.jewelStock=4; MedalMinter.pearlStock=4; MedalMinter.productStock={}; MedalMinter.buildings={}; MedalMinter.maker=nil; MedalMinter.activeMaking={}; MedalMinter.totalProducts=0; MedalMinter.dayTimer=0; print("[MedalMinter] Royal Medal Minter System initialized (6 products, 4 buildings)") end
function MedalMinter.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MedalMinter.maker={name=n or ("Medaljar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Medaljar najet: %s (spretnost: %d)",MedalMinter.maker.name,s),"success") end; return true end
function MedalMinter.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MedalMinter.build(id) local ok,e=MedalMinter.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MedalMinter.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MedalMinter.getQualityBonus() local b=0; for _,bd in ipairs(MedalMinter.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MedalMinter.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.bronzeCost and MedalMinter.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.ironCost and MedalMinter.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.silverCost and MedalMinter.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MedalMinter.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MedalMinter.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MedalMinter.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MedalMinter.buildings==0 then return false,"Potrebna medaljarska delavnica" end; if not MedalMinter.maker then return false,"Potreben medaljar" end; return true end
function MedalMinter.make(pt,qty) qty=qty or 1; local ok,e=MedalMinter.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.bronzeCost then MedalMinter.bronzeStock=MedalMinter.bronzeStock-d.bronzeCost*qty end; if d.ironCost then MedalMinter.ironStock=MedalMinter.ironStock-d.ironCost*qty end; if d.silverCost then MedalMinter.silverStock=MedalMinter.silverStock-d.silverCost*qty end; if d.goldCost then MedalMinter.goldStock=MedalMinter.goldStock-d.goldCost*qty end; if d.jewelCost then MedalMinter.jewelStock=MedalMinter.jewelStock-d.jewelCost*qty end; if d.pearlCost then MedalMinter.pearlStock=MedalMinter.pearlStock-d.pearlCost*qty end; local t=d.time; if MedalMinter.maker then t=math.max(1,t-math.floor(MedalMinter.maker.skill/13)) end; table.insert(MedalMinter.activeMaking,{id="medal_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MedalMinter.completeMaking(m) local q=1.0+(MedalMinter.getQualityBonus()/100); if MedalMinter.maker then q=q+(MedalMinter.maker.skill/140) end; q=math.min(2.5,q); MedalMinter.productStock[m.productType]=(MedalMinter.productStock[m.productType] or 0)+m.quantity; MedalMinter.totalProducts=MedalMinter.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MedalMinter.maker then MedalMinter.maker.itemsMade=MedalMinter.maker.itemsMade+m.quantity; if math.random()<0.25 then MedalMinter.maker.skill=math.min(100,MedalMinter.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Medalja izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"medal.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MedalMinter.update(dt) if not _G.state then return end; MedalMinter.dayTimer=MedalMinter.dayTimer+dt; if MedalMinter.dayTimer>=30 then MedalMinter.dayTimer=0; for i=#MedalMinter.activeMaking,1,-1 do local m=MedalMinter.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MedalMinter.completeMaking(m); table.remove(MedalMinter.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MedalMinter.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MedalMinter.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MedalMinter.getStats() return {bronzeStock=MedalMinter.bronzeStock,ironStock=MedalMinter.ironStock,silverStock=MedalMinter.silverStock,goldStock=MedalMinter.goldStock,jewelStock=MedalMinter.jewelStock,pearlStock=MedalMinter.pearlStock,productStock=MedalMinter.productStock,numBuildings=#MedalMinter.buildings,hasMaker=MedalMinter.maker~=nil,makerName=MedalMinter.maker and MedalMinter.maker.name or "—",makerSkill=MedalMinter.maker and MedalMinter.maker.skill or 0,activeMaking=#MedalMinter.activeMaking,totalProducts=MedalMinter.totalProducts} end
return MedalMinter
