local GardenSeedPacketSealerMaker = {}
local PRODUCTS = {
    iron_gardenseedpacketsealer = { name = "Železni zatisnjevalec za semena", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni zatisnjevalec za semena za vrtnarje." },
    bronze_gardenseedpacketsealer = { name = "Bronast zatisnjevalec za semena", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast zatisnjevalec za semena za vrtnarje." },
    silver_gardenseedpacketsealer = { name = "Srebrn zatisnjevalec za semena", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn zatisnjevalec za semena za vrtnarje." },
    gilded_gardenseedpacketsealer = { name = "Pozlačen zatisnjevalec za semena", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen zatisnjevalec za semena za vrtnarje." },
    jewel_set_gardenseedpacketsealer = { name = "Draguljast zatisnjevalec za semena", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast zatisnjevalec za semena za vrtnarje." },
    royal_sovereign_gardenseedpacketsealer = { name = "Kraljevski suveren zatisnjevalec za semena", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren zatisnjevalec za semena z biseri za krono." },
}
local BUILDINGS = {
    gardenseedpacketsealer_workshop = { name = "Gardenseedpacketsealer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardenseedpacketsealer_house = { name = "Gardenseedpacketsealer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardenseedpacketsealer_atelier = { name = "Mojstrski gardenseedpacketsealer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardenseedpacketsealer_palace = { name = "Suverena gardenseedpacketsealer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenSeedPacketSealerMaker.ironStock=14; GardenSeedPacketSealerMaker.bronzeStock=12; GardenSeedPacketSealerMaker.woodStock=14; GardenSeedPacketSealerMaker.leatherStock=8; GardenSeedPacketSealerMaker.silverStock=8; GardenSeedPacketSealerMaker.goldStock=6; GardenSeedPacketSealerMaker.jewelStock=4; GardenSeedPacketSealerMaker.pearlStock=4
GardenSeedPacketSealerMaker.productStock = {}; GardenSeedPacketSealerMaker.buildings = {}; GardenSeedPacketSealerMaker.maker = nil; GardenSeedPacketSealerMaker.activeMaking = {}; GardenSeedPacketSealerMaker.totalProducts = 0; GardenSeedPacketSealerMaker.dayTimer = 0
function GardenSeedPacketSealerMaker.init() GardenSeedPacketSealerMaker.ironStock=14; GardenSeedPacketSealerMaker.bronzeStock=12; GardenSeedPacketSealerMaker.woodStock=14; GardenSeedPacketSealerMaker.leatherStock=8; GardenSeedPacketSealerMaker.silverStock=8; GardenSeedPacketSealerMaker.goldStock=6; GardenSeedPacketSealerMaker.jewelStock=4; GardenSeedPacketSealerMaker.pearlStock=4; GardenSeedPacketSealerMaker.productStock={}; GardenSeedPacketSealerMaker.buildings={}; GardenSeedPacketSealerMaker.maker=nil; GardenSeedPacketSealerMaker.activeMaking={}; GardenSeedPacketSealerMaker.totalProducts=0; GardenSeedPacketSealerMaker.dayTimer=0; print("[GardenSeedPacketSealerMaker] Royal Garden Seed Packet Sealer Maker System initialized (6 products, 4 buildings)") end
function GardenSeedPacketSealerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenSeedPacketSealerMaker.maker={name=n or ("Zatisnjevalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zatisnjevalec najet: %s (spretnost: %d)",GardenSeedPacketSealerMaker.maker.name,s),"success") end; return true end
function GardenSeedPacketSealerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenSeedPacketSealerMaker.build(id) local ok,e=GardenSeedPacketSealerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenSeedPacketSealerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenSeedPacketSealerMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenSeedPacketSealerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenSeedPacketSealerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenSeedPacketSealerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenSeedPacketSealerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenSeedPacketSealerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenSeedPacketSealerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenSeedPacketSealerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenSeedPacketSealerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenSeedPacketSealerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenSeedPacketSealerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenSeedPacketSealerMaker.buildings==0 then return false,"Potrebna zatisnjevalna delavnica" end; if not GardenSeedPacketSealerMaker.maker then return false,"Potreben zatisnjevalec" end; return true end
function GardenSeedPacketSealerMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenSeedPacketSealerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenSeedPacketSealerMaker.ironStock=GardenSeedPacketSealerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenSeedPacketSealerMaker.bronzeStock=GardenSeedPacketSealerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenSeedPacketSealerMaker.woodStock=GardenSeedPacketSealerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenSeedPacketSealerMaker.leatherStock=GardenSeedPacketSealerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenSeedPacketSealerMaker.silverStock=GardenSeedPacketSealerMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenSeedPacketSealerMaker.goldStock=GardenSeedPacketSealerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenSeedPacketSealerMaker.jewelStock=GardenSeedPacketSealerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenSeedPacketSealerMaker.pearlStock=GardenSeedPacketSealerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenSeedPacketSealerMaker.maker then t=math.max(1,t-math.floor(GardenSeedPacketSealerMaker.maker.skill/13)) end; table.insert(GardenSeedPacketSealerMaker.activeMaking,{id="gardenseedpacketsealer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenSeedPacketSealerMaker.completeMaking(m) local q=1.0+(GardenSeedPacketSealerMaker.getQualityBonus()/100); if GardenSeedPacketSealerMaker.maker then q=q+(GardenSeedPacketSealerMaker.maker.skill/140) end; q=math.min(2.5,q); GardenSeedPacketSealerMaker.productStock[m.productType]=(GardenSeedPacketSealerMaker.productStock[m.productType] or 0)+m.quantity; GardenSeedPacketSealerMaker.totalProducts=GardenSeedPacketSealerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenSeedPacketSealerMaker.maker then GardenSeedPacketSealerMaker.maker.itemsMade=GardenSeedPacketSealerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenSeedPacketSealerMaker.maker.skill=math.min(100,GardenSeedPacketSealerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zatisnjevalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardenseedpacketsealer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenSeedPacketSealerMaker.update(dt) if not _G.state then return end; GardenSeedPacketSealerMaker.dayTimer=GardenSeedPacketSealerMaker.dayTimer+dt; if GardenSeedPacketSealerMaker.dayTimer>=30 then GardenSeedPacketSealerMaker.dayTimer=0; for i=#GardenSeedPacketSealerMaker.activeMaking,1,-1 do local m=GardenSeedPacketSealerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenSeedPacketSealerMaker.completeMaking(m); table.remove(GardenSeedPacketSealerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenSeedPacketSealerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenSeedPacketSealerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenSeedPacketSealerMaker.getStats() return {ironStock=GardenSeedPacketSealerMaker.ironStock,bronzeStock=GardenSeedPacketSealerMaker.bronzeStock,woodStock=GardenSeedPacketSealerMaker.woodStock,leatherStock=GardenSeedPacketSealerMaker.leatherStock,silverStock=GardenSeedPacketSealerMaker.silverStock,goldStock=GardenSeedPacketSealerMaker.goldStock,jewelStock=GardenSeedPacketSealerMaker.jewelStock,pearlStock=GardenSeedPacketSealerMaker.pearlStock,productStock=GardenSeedPacketSealerMaker.productStock,numBuildings=#GardenSeedPacketSealerMaker.buildings,hasMaker=GardenSeedPacketSealerMaker.maker~=nil,makerName=GardenSeedPacketSealerMaker.maker and GardenSeedPacketSealerMaker.maker.name or "—",makerSkill=GardenSeedPacketSealerMaker.maker and GardenSeedPacketSealerMaker.maker.skill or 0,activeMaking=#GardenSeedPacketSealerMaker.activeMaking,totalProducts=GardenSeedPacketSealerMaker.totalProducts} end
return GardenSeedPacketSealerMaker
