local TileMaker = {}
local PRODUCTS = {
    floor_tile = { name = "Tlakovca", clayCost = 1, time = 1, cost = 5, durability = 10, description = "Glazena tlakovca za tla." },
    wall_tile = { name = "Stenska ploščica", clayCost = 1, time = 2, cost = 12, durability = 12, prestige = 1, description = "Okrasna stenska ploščica." },
    mosaic_tile = { name = "Mozaik ploščica", clayCost = 2, glassCost = 1, time = 3, cost = 35, durability = 15, prestige = 3, description = "Barvna mozaik ploščica." },
    faience_tile = { name = "Fajansa ploščica", clayCost = 2, tinCost = 1, time = 4, cost = 70, durability = 20, prestige = 6, description = "Kosmatena fajansa ploščica." },
    majolica_tile = { name = "Majolika ploščica", clayCost = 3, tinCost = 1, glassCost = 1, time = 5, cost = 130, durability = 25, prestige = 10, happiness = 1, description = "Bleščeča italijanska majolika." },
    royal_mosaic_panel = { name = "Kraljevski mozaik panel", clayCost = 5, glassCost = 3, goldCost = 1, tinCost = 2, time = 8, cost = 400, durability = 40, prestige = 25, happiness = 4, description = "Kraljevski mozaik panel s pozlačenimi detajli." },
}
local BUILDINGS = {
    workshop = { name = "Ploščičarska delavnica", cost = { gold = 220, wood = 120 }, upkeep = 5, qualityBonus = 5 },
    kiln = { name = "Peč za žganje", cost = { gold = 700, wood = 200, stone = 150 }, upkeep = 18, qualityBonus = 15 },
    glazing_room = { name = "Glazurnica", cost = { gold = 1200, wood = 250, stone = 250, tin = 25 }, upkeep = 28, qualityBonus = 22 },
    royal_tile_atelier = { name = "Kraljevski atelje ploščic", cost = { gold = 3500, wood = 400, stone = 500, gold = 30 }, upkeep = 65, qualityBonus = 38, prestigeBonus = 18 },
}
TileMaker.clayStock = 20; TileMaker.glassStock = 6; TileMaker.tinStock = 5; TileMaker.goldStock = 3
TileMaker.productStock = {}; TileMaker.buildings = {}; TileMaker.maker = nil; TileMaker.activeMaking = {}; TileMaker.totalProducts = 0; TileMaker.dayTimer = 0
function TileMaker.init() TileMaker.clayStock=20; TileMaker.glassStock=6; TileMaker.tinStock=5; TileMaker.goldStock=3; TileMaker.productStock={}; TileMaker.buildings={}; TileMaker.maker=nil; TileMaker.activeMaking={}; TileMaker.totalProducts=0; TileMaker.dayTimer=0; print("[TileMaker] Royal Tile Maker & Floor System initialized (6 products, 4 buildings)") end
function TileMaker.hireMaker(n,s) s=s or math.random(35,80); local c=270+s*5; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TileMaker.maker={name=n or ("Ploščičar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ploščičar najet: %s (spretnost: %d)",TileMaker.maker.name,s),"success") end; return true end
function TileMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TileMaker.build(id) local ok,e=TileMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TileMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TileMaker.getQualityBonus() local b=0; for _,bd in ipairs(TileMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TileMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.clayCost and TileMaker.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.glassCost and TileMaker.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.tinCost and TileMaker.tinStock<(d.tinCost or 0) then return false,"Premalo kositra" end; if d.goldCost and TileMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if #TileMaker.buildings==0 then return false,"Potrebna delavnica" end; if not TileMaker.maker then return false,"Potreben ploščičar" end; return true end
function TileMaker.make(pt,qty) qty=qty or 5; local ok,e=TileMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.clayCost then TileMaker.clayStock=TileMaker.clayStock-d.clayCost*qty end; if d.glassCost then TileMaker.glassStock=TileMaker.glassStock-d.glassCost*qty end; if d.tinCost then TileMaker.tinStock=TileMaker.tinStock-d.tinCost*qty end; if d.goldCost then TileMaker.goldStock=TileMaker.goldStock-d.goldCost*qty end; local t=d.time; if TileMaker.maker then t=math.max(1,t-math.floor(TileMaker.maker.skill/15)) end; table.insert(TileMaker.activeMaking,{id="tile_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,durability=d.durability or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TileMaker.completeMaking(m) local q=1.0+(TileMaker.getQualityBonus()/100); if TileMaker.maker then q=q+(TileMaker.maker.skill/200) end; q=math.min(2.0,q); TileMaker.productStock[m.productType]=(TileMaker.productStock[m.productType] or 0)+m.quantity; TileMaker.totalProducts=TileMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if TileMaker.maker then TileMaker.maker.itemsMade=TileMaker.maker.itemsMade+m.quantity; if math.random()<0.15 then TileMaker.maker.skill=math.min(100,TileMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ploščice izdelane: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end end
function TileMaker.update(dt) if not _G.state then return end; TileMaker.dayTimer=TileMaker.dayTimer+dt; if TileMaker.dayTimer>=30 then TileMaker.dayTimer=0; for i=#TileMaker.activeMaking,1,-1 do local m=TileMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TileMaker.completeMaking(m); table.remove(TileMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TileMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TileMaker.maker then tu=tu+8 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TileMaker.getStats() return {clayStock=TileMaker.clayStock,glassStock=TileMaker.glassStock,tinStock=TileMaker.tinStock,goldStock=TileMaker.goldStock,productStock=TileMaker.productStock,numBuildings=#TileMaker.buildings,hasMaker=TileMaker.maker~=nil,makerName=TileMaker.maker and TileMaker.maker.name or "—",makerSkill=TileMaker.maker and TileMaker.maker.skill or 0,activeMaking=#TileMaker.activeMaking,totalProducts=TileMaker.totalProducts} end
return TileMaker
