local RoyalSealStampMaker = {}
local PRODUCTS = {
    simple_iron_seal_stamp = { name = "Preprost železni pečatnik", ironCost = 2, woodCost = 1, time = 3, cost = 50, prestige = 3, happiness = 1, description = "Preprost železni pečatnik za listine." },
    brass_engraved_stamp = { name = "Medeninast gravirani pečatnik", brassCost = 2, ironCost = 1, woodCost = 1, time = 6, cost = 150, prestige = 8, happiness = 2, description = "Medeninast gravirani pečatnik za trgovce." },
    silver_handle_stamp = { name = "Srebrnorokavi pečatnik", silverCost = 2, brassCost = 1, ironCost = 1, woodCost = 1, time = 9, cost = 380, prestige = 16, happiness = 2, description = "Srebrnorokavi pečatnik za plemiče." },
    gold_signet_stamp = { name = "Zlati signet pečatnik", goldCost = 2, silverCost = 1, brassCost = 1, ironCost = 1, time = 13, cost = 900, prestige = 28, happiness = 3, description = "Zlati signet pečatnik za visoke plemiče." },
    jewel_set_signet = { name = "Draguljni signet pečatnik", goldCost = 2, silverCost = 1, brassCost = 1, jewelCost = 1, ironCost = 1, time = 17, cost = 2000, prestige = 42, happiness = 5, description = "Signet pečatnik z draguljem za visoko plemstvo." },
    royal_grand_seal_stamp = { name = "Kraljevski veliki pečatnik", goldCost = 3, silverCost = 2, brassCost = 1, ironCost = 1, jewelCost = 2, pearlCost = 2, time = 24, cost = 4500, prestige = 70, happiness = 12, description = "Veliki kraljevski pečatnik z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    seal_workshop = { name = "Pečatniška delavnica", cost = { gold = 240, wood = 100, stone = 120, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    engravers_loft = { name = "Graverska podstrešje", cost = { gold = 880, wood = 240, stone = 240, brass = 6, silver = 6 }, upkeep = 20, qualityBonus = 18 },
    master_seal_atelier = { name = "Mojstrski pečatni atelje", cost = { gold = 2500, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 58, qualityBonus = 30 },
    royal_seal_palace = { name = "Kraljevska pečatna palača", cost = { gold = 10500, wood = 580, stone = 760, gold = 65, jewel = 16 }, upkeep = 210, qualityBonus = 55, prestigeBonus = 50 },
}
RoyalSealStampMaker.ironStock = 14; RoyalSealStampMaker.woodStock = 10; RoyalSealStampMaker.brassStock = 12; RoyalSealStampMaker.silverStock = 6; RoyalSealStampMaker.goldStock = 6; RoyalSealStampMaker.jewelStock = 4; RoyalSealStampMaker.pearlStock = 4
RoyalSealStampMaker.productStock = {}; RoyalSealStampMaker.buildings = {}; RoyalSealStampMaker.maker = nil; RoyalSealStampMaker.activeMaking = {}; RoyalSealStampMaker.totalProducts = 0; RoyalSealStampMaker.dayTimer = 0
function RoyalSealStampMaker.init() RoyalSealStampMaker.ironStock=14; RoyalSealStampMaker.woodStock=10; RoyalSealStampMaker.brassStock=12; RoyalSealStampMaker.silverStock=6; RoyalSealStampMaker.goldStock=6; RoyalSealStampMaker.jewelStock=4; RoyalSealStampMaker.pearlStock=4; RoyalSealStampMaker.productStock={}; RoyalSealStampMaker.buildings={}; RoyalSealStampMaker.maker=nil; RoyalSealStampMaker.activeMaking={}; RoyalSealStampMaker.totalProducts=0; RoyalSealStampMaker.dayTimer=0; print("[RoyalSealStampMaker] Royal Seal Stamp Maker System initialized (6 products, 4 buildings)") end
function RoyalSealStampMaker.hireMaker(n,s) s=s or math.random(55,90); local c=540+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; RoyalSealStampMaker.maker={name=n or ("Pečatnikar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pečatnikar najet: %s (spretnost: %d)",RoyalSealStampMaker.maker.name,s),"success") end; return true end
function RoyalSealStampMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function RoyalSealStampMaker.build(id) local ok,e=RoyalSealStampMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(RoyalSealStampMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function RoyalSealStampMaker.getQualityBonus() local b=0; for _,bd in ipairs(RoyalSealStampMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function RoyalSealStampMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and RoyalSealStampMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.woodCost and RoyalSealStampMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.brassCost and RoyalSealStampMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and RoyalSealStampMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and RoyalSealStampMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and RoyalSealStampMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and RoyalSealStampMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #RoyalSealStampMaker.buildings==0 then return false,"Potrebna pečatniška delavnica" end; if not RoyalSealStampMaker.maker then return false,"Potreben pečatnikar" end; return true end
function RoyalSealStampMaker.make(pt,qty) qty=qty or 1; local ok,e=RoyalSealStampMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then RoyalSealStampMaker.ironStock=RoyalSealStampMaker.ironStock-d.ironCost*qty end; if d.woodCost then RoyalSealStampMaker.woodStock=RoyalSealStampMaker.woodStock-d.woodCost*qty end; if d.brassCost then RoyalSealStampMaker.brassStock=RoyalSealStampMaker.brassStock-d.brassCost*qty end; if d.silverCost then RoyalSealStampMaker.silverStock=RoyalSealStampMaker.silverStock-d.silverCost*qty end; if d.goldCost then RoyalSealStampMaker.goldStock=RoyalSealStampMaker.goldStock-d.goldCost*qty end; if d.jewelCost then RoyalSealStampMaker.jewelStock=RoyalSealStampMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then RoyalSealStampMaker.pearlStock=RoyalSealStampMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if RoyalSealStampMaker.maker then t=math.max(1,t-math.floor(RoyalSealStampMaker.maker.skill/12)) end; table.insert(RoyalSealStampMaker.activeMaking,{id="sealstamp_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Graviranje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function RoyalSealStampMaker.completeMaking(m) local q=1.0+(RoyalSealStampMaker.getQualityBonus()/100); if RoyalSealStampMaker.maker then q=q+(RoyalSealStampMaker.maker.skill/140) end; q=math.min(2.5,q); RoyalSealStampMaker.productStock[m.productType]=(RoyalSealStampMaker.productStock[m.productType] or 0)+m.quantity; RoyalSealStampMaker.totalProducts=RoyalSealStampMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if RoyalSealStampMaker.maker then RoyalSealStampMaker.maker.itemsMade=RoyalSealStampMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then RoyalSealStampMaker.maker.skill=math.min(100,RoyalSealStampMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pečatnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sealstamp.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function RoyalSealStampMaker.update(dt) if not _G.state then return end; RoyalSealStampMaker.dayTimer=RoyalSealStampMaker.dayTimer+dt; if RoyalSealStampMaker.dayTimer>=30 then RoyalSealStampMaker.dayTimer=0; for i=#RoyalSealStampMaker.activeMaking,1,-1 do local m=RoyalSealStampMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then RoyalSealStampMaker.completeMaking(m); table.remove(RoyalSealStampMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(RoyalSealStampMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if RoyalSealStampMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function RoyalSealStampMaker.getStats() return {ironStock=RoyalSealStampMaker.ironStock,woodStock=RoyalSealStampMaker.woodStock,brassStock=RoyalSealStampMaker.brassStock,silverStock=RoyalSealStampMaker.silverStock,goldStock=RoyalSealStampMaker.goldStock,jewelStock=RoyalSealStampMaker.jewelStock,pearlStock=RoyalSealStampMaker.pearlStock,productStock=RoyalSealStampMaker.productStock,numBuildings=#RoyalSealStampMaker.buildings,hasMaker=RoyalSealStampMaker.maker~=nil,makerName=RoyalSealStampMaker.maker and RoyalSealStampMaker.maker.name or "—",makerSkill=RoyalSealStampMaker.maker and RoyalSealStampMaker.maker.skill or 0,activeMaking=#RoyalSealStampMaker.activeMaking,totalProducts=RoyalSealStampMaker.totalProducts} end
return RoyalSealStampMaker
