local BellHammerMaker = {}
local PRODUCTS = {
    iron_bellhammer = { name = "Železni zvočno kladivo", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni zvočno kladivo za kovace." },
    bronze_bellhammer = { name = "Bronast zvočno kladivo", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast zvočno kladivo za kovace." },
    silver_bellhammer = { name = "Srebrn zvočno kladivo", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn zvočno kladivo za kovace." },
    gilded_bellhammer = { name = "Pozlačen zvočno kladivo", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen zvočno kladivo za kovace." },
    jewel_set_bellhammer = { name = "Draguljast zvočno kladivo", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast zvočno kladivo za kovace." },
    royal_sovereign_bellhammer = { name = "Kraljevski suveren zvočno kladivo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren zvočno kladivo z biseri za krono." },
}
local BUILDINGS = {
    bellhammer_workshop = { name = "Bellhammer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bellhammer_house = { name = "Bellhammer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bellhammer_atelier = { name = "Mojstrski bellhammer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bellhammer_palace = { name = "Suverena bellhammer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BellHammerMaker.ironStock=18; BellHammerMaker.bronzeStock=14; BellHammerMaker.woodStock=10; BellHammerMaker.leatherStock=8; BellHammerMaker.silverStock=8; BellHammerMaker.goldStock=6; BellHammerMaker.jewelStock=4; BellHammerMaker.pearlStock=4
BellHammerMaker.productStock = {}; BellHammerMaker.buildings = {}; BellHammerMaker.maker = nil; BellHammerMaker.activeMaking = {}; BellHammerMaker.totalProducts = 0; BellHammerMaker.dayTimer = 0
function BellHammerMaker.init() BellHammerMaker.ironStock=18; BellHammerMaker.bronzeStock=14; BellHammerMaker.woodStock=10; BellHammerMaker.leatherStock=8; BellHammerMaker.silverStock=8; BellHammerMaker.goldStock=6; BellHammerMaker.jewelStock=4; BellHammerMaker.pearlStock=4; BellHammerMaker.productStock={}; BellHammerMaker.buildings={}; BellHammerMaker.maker=nil; BellHammerMaker.activeMaking={}; BellHammerMaker.totalProducts=0; BellHammerMaker.dayTimer=0; print("[BellHammerMaker] Royal Bell Hammer Maker System initialized (6 products, 4 buildings)") end
function BellHammerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BellHammerMaker.maker={name=n or ("Zvokobijalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zvokobijalec najet: %s (spretnost: %d)",BellHammerMaker.maker.name,s),"success") end; return true end
function BellHammerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BellHammerMaker.build(id) local ok,e=BellHammerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BellHammerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BellHammerMaker.getQualityBonus() local b=0; for _,bd in ipairs(BellHammerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BellHammerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BellHammerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BellHammerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BellHammerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BellHammerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BellHammerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BellHammerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BellHammerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BellHammerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BellHammerMaker.buildings==0 then return false,"Potrebna zvokobijalna delavnica" end; if not BellHammerMaker.maker then return false,"Potreben zvokobijalec" end; return true end
function BellHammerMaker.make(pt,qty) qty=qty or 1; local ok,e=BellHammerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BellHammerMaker.ironStock=BellHammerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BellHammerMaker.bronzeStock=BellHammerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BellHammerMaker.woodStock=BellHammerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BellHammerMaker.leatherStock=BellHammerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BellHammerMaker.silverStock=BellHammerMaker.silverStock-d.silverCost*qty end; if d.goldCost then BellHammerMaker.goldStock=BellHammerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BellHammerMaker.jewelStock=BellHammerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BellHammerMaker.pearlStock=BellHammerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BellHammerMaker.maker then t=math.max(1,t-math.floor(BellHammerMaker.maker.skill/13)) end; table.insert(BellHammerMaker.activeMaking,{id="bellhammer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BellHammerMaker.completeMaking(m) local q=1.0+(BellHammerMaker.getQualityBonus()/100); if BellHammerMaker.maker then q=q+(BellHammerMaker.maker.skill/140) end; q=math.min(2.5,q); BellHammerMaker.productStock[m.productType]=(BellHammerMaker.productStock[m.productType] or 0)+m.quantity; BellHammerMaker.totalProducts=BellHammerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BellHammerMaker.maker then BellHammerMaker.maker.itemsMade=BellHammerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BellHammerMaker.maker.skill=math.min(100,BellHammerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zvokobijalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bellhammer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BellHammerMaker.update(dt) if not _G.state then return end; BellHammerMaker.dayTimer=BellHammerMaker.dayTimer+dt; if BellHammerMaker.dayTimer>=30 then BellHammerMaker.dayTimer=0; for i=#BellHammerMaker.activeMaking,1,-1 do local m=BellHammerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BellHammerMaker.completeMaking(m); table.remove(BellHammerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BellHammerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BellHammerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BellHammerMaker.getStats() return {ironStock=BellHammerMaker.ironStock,bronzeStock=BellHammerMaker.bronzeStock,woodStock=BellHammerMaker.woodStock,leatherStock=BellHammerMaker.leatherStock,silverStock=BellHammerMaker.silverStock,goldStock=BellHammerMaker.goldStock,jewelStock=BellHammerMaker.jewelStock,pearlStock=BellHammerMaker.pearlStock,productStock=BellHammerMaker.productStock,numBuildings=#BellHammerMaker.buildings,hasMaker=BellHammerMaker.maker~=nil,makerName=BellHammerMaker.maker and BellHammerMaker.maker.name or "—",makerSkill=BellHammerMaker.maker and BellHammerMaker.maker.skill or 0,activeMaking=#BellHammerMaker.activeMaking,totalProducts=BellHammerMaker.totalProducts} end
return BellHammerMaker
