local SackbutMaker = {}
local PRODUCTS = {
    alto_sackbut = { name = "Alt sakbut", brassCost = 2, leatherCost = 1, time = 3, cost = 80, soundQuality = 11, prestige = 2, description = "Alt sakbut za cerkvene zbore." },
    tenor_sackbut = { name = "Tenor sakbut", brassCost = 3, leatherCost = 1, time = 5, cost = 200, soundQuality = 15, prestige = 4, happiness = 1, description = "Tenor sakbut z drsnim tubusom." },
    bass_sackbut = { name = "Bas sakbut", brassCost = 4, leatherCost = 1, time = 7, cost = 450, soundQuality = 19, prestige = 8, happiness = 2, description = "Bas sakbut za močan zvok." },
    silver_sackbut = { name = "Srebrni sakbut", silverCost = 2, brassCost = 2, leatherCost = 1, time = 9, cost = 900, soundQuality = 24, prestige = 14, happiness = 3, description = "Srebrni sakbut za dvorne koncerte." },
    gold_trim_sackbut = { name = "Zlatorobni sakbut", goldCost = 1, silverCost = 1, brassCost = 3, leatherCost = 1, time = 11, cost = 1600, soundQuality = 28, prestige = 22, happiness = 5, description = "Sakbut z zlatorobnim okovjem." },
    royal_ceremonial_sackbut = { name = "Kraljevski slovesni sakbut", goldCost = 2, silverCost = 2, brassCost = 4, ivoryCost = 1, pearlCost = 1, time = 15, cost = 2900, soundQuality = 38, prestige = 55, happiness = 11, description = "Veliki kraljevski slovesni sakbut z zlatim okovjem, slonovino in biseri za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Sakbutska delavnica", cost = { gold = 280, wood = 120 }, upkeep = 7, qualityBonus = 5 },
    forge = { name = "Sakbutska kovačija", cost = { gold = 850, wood = 220, stone = 200, brass = 6 }, upkeep = 20, qualityBonus = 18 },
    slide_room = { name = "Drsničnica", cost = { gold = 1800, wood = 280, stone = 350, silver = 25, leather = 8 }, upkeep = 42, qualityBonus = 30 },
    royal_sackbut_atelier = { name = "Kraljevski atelje sakbutov", cost = { gold = 7000, wood = 500, stone = 700, gold = 50, ivory = 20 }, upkeep = 130, qualityBonus = 55, prestigeBonus = 33 },
}
SackbutMaker.brassStock = 12; SackbutMaker.leatherStock = 10; SackbutMaker.silverStock = 8; SackbutMaker.goldStock = 6; SackbutMaker.ivoryStock = 6; SackbutMaker.pearlStock = 4
SackbutMaker.productStock = {}; SackbutMaker.buildings = {}; SackbutMaker.maker = nil; SackbutMaker.activeMaking = {}; SackbutMaker.totalProducts = 0; SackbutMaker.dayTimer = 0
function SackbutMaker.init() SackbutMaker.brassStock=12; SackbutMaker.leatherStock=10; SackbutMaker.silverStock=8; SackbutMaker.goldStock=6; SackbutMaker.ivoryStock=6; SackbutMaker.pearlStock=4; SackbutMaker.productStock={}; SackbutMaker.buildings={}; SackbutMaker.maker=nil; SackbutMaker.activeMaking={}; SackbutMaker.totalProducts=0; SackbutMaker.dayTimer=0; print("[SackbutMaker] Royal Sackbut Maker System initialized (6 products, 4 buildings)") end
function SackbutMaker.hireMaker(n,s) s=s or math.random(50,90); local c=480+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SackbutMaker.maker={name=n or ("Sakbutar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sakbutar najet: %s (spretnost: %d)",SackbutMaker.maker.name,s),"success") end; return true end
function SackbutMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SackbutMaker.build(id) local ok,e=SackbutMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SackbutMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SackbutMaker.getQualityBonus() local b=0; for _,bd in ipairs(SackbutMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SackbutMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.brassCost and SackbutMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.leatherCost and SackbutMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SackbutMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SackbutMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.ivoryCost and SackbutMaker.ivoryStock<(d.ivoryCost or 0) then return false,"Premalo slonovine" end; if d.pearlCost and SackbutMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SackbutMaker.buildings==0 then return false,"Potrebna delavnica" end; if not SackbutMaker.maker then return false,"Potreben sakbutar" end; return true end
function SackbutMaker.make(pt,qty) qty=qty or 1; local ok,e=SackbutMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.brassCost then SackbutMaker.brassStock=SackbutMaker.brassStock-d.brassCost*qty end; if d.leatherCost then SackbutMaker.leatherStock=SackbutMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SackbutMaker.silverStock=SackbutMaker.silverStock-d.silverCost*qty end; if d.goldCost then SackbutMaker.goldStock=SackbutMaker.goldStock-d.goldCost*qty end; if d.ivoryCost then SackbutMaker.ivoryStock=SackbutMaker.ivoryStock-d.ivoryCost*qty end; if d.pearlCost then SackbutMaker.pearlStock=SackbutMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SackbutMaker.maker then t=math.max(1,t-math.floor(SackbutMaker.maker.skill/12)) end; table.insert(SackbutMaker.activeMaking,{id="sackbut_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,soundQuality=d.soundQuality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SackbutMaker.completeMaking(m) local q=1.0+(SackbutMaker.getQualityBonus()/100); if SackbutMaker.maker then q=q+(SackbutMaker.maker.skill/180) end; q=math.min(2.0,q); SackbutMaker.productStock[m.productType]=(SackbutMaker.productStock[m.productType] or 0)+m.quantity; SackbutMaker.totalProducts=SackbutMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SackbutMaker.maker then SackbutMaker.maker.itemsMade=SackbutMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then SackbutMaker.maker.skill=math.min(100,SackbutMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sakbut izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sackbut.completed",{productName=m.productName,soundQuality=m.soundQuality}) end end
function SackbutMaker.update(dt) if not _G.state then return end; SackbutMaker.dayTimer=SackbutMaker.dayTimer+dt; if SackbutMaker.dayTimer>=30 then SackbutMaker.dayTimer=0; for i=#SackbutMaker.activeMaking,1,-1 do local m=SackbutMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SackbutMaker.completeMaking(m); table.remove(SackbutMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SackbutMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SackbutMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SackbutMaker.getStats() return {brassStock=SackbutMaker.brassStock,leatherStock=SackbutMaker.leatherStock,silverStock=SackbutMaker.silverStock,goldStock=SackbutMaker.goldStock,ivoryStock=SackbutMaker.ivoryStock,pearlStock=SackbutMaker.pearlStock,productStock=SackbutMaker.productStock,numBuildings=#SackbutMaker.buildings,hasMaker=SackbutMaker.maker~=nil,makerName=SackbutMaker.maker and SackbutMaker.maker.name or "—",makerSkill=SackbutMaker.maker and SackbutMaker.maker.skill or 0,activeMaking=#SackbutMaker.activeMaking,totalProducts=SackbutMaker.totalProducts} end
return SackbutMaker
