local BookCoverStampingFoilMaker = {}
local PRODUCTS = {
    iron_bookcoverstampingfoil = { name = "Železni folija za žigosanje naslovnic", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni folija za žigosanje naslovnic za knjigoveze." },
    bronze_bookcoverstampingfoil = { name = "Bronast folija za žigosanje naslovnic", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast folija za žigosanje naslovnic za knjigoveze." },
    silver_bookcoverstampingfoil = { name = "Srebrn folija za žigosanje naslovnic", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn folija za žigosanje naslovnic za knjigoveze." },
    gilded_bookcoverstampingfoil = { name = "Pozlačen folija za žigosanje naslovnic", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen folija za žigosanje naslovnic za knjigoveze." },
    jewel_set_bookcoverstampingfoil = { name = "Draguljast folija za žigosanje naslovnic", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast folija za žigosanje naslovnic za knjigoveze." },
    royal_sovereign_bookcoverstampingfoil = { name = "Kraljevski suveren folija za žigosanje naslovnic", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren folija za žigosanje naslovnic z biseri za krono." },
}
local BUILDINGS = {
    bookcoverstampingfoil_workshop = { name = "Bookcoverstampingfoil delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookcoverstampingfoil_house = { name = "Bookcoverstampingfoil hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookcoverstampingfoil_atelier = { name = "Mojstrski bookcoverstampingfoil atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookcoverstampingfoil_palace = { name = "Suverena bookcoverstampingfoil palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookCoverStampingFoilMaker.ironStock=12; BookCoverStampingFoilMaker.bronzeStock=10; BookCoverStampingFoilMaker.woodStock=14; BookCoverStampingFoilMaker.leatherStock=10; BookCoverStampingFoilMaker.silverStock=8; BookCoverStampingFoilMaker.goldStock=6; BookCoverStampingFoilMaker.jewelStock=4; BookCoverStampingFoilMaker.pearlStock=4
BookCoverStampingFoilMaker.productStock = {}; BookCoverStampingFoilMaker.buildings = {}; BookCoverStampingFoilMaker.maker = nil; BookCoverStampingFoilMaker.activeMaking = {}; BookCoverStampingFoilMaker.totalProducts = 0; BookCoverStampingFoilMaker.dayTimer = 0
function BookCoverStampingFoilMaker.init() BookCoverStampingFoilMaker.ironStock=12; BookCoverStampingFoilMaker.bronzeStock=10; BookCoverStampingFoilMaker.woodStock=14; BookCoverStampingFoilMaker.leatherStock=10; BookCoverStampingFoilMaker.silverStock=8; BookCoverStampingFoilMaker.goldStock=6; BookCoverStampingFoilMaker.jewelStock=4; BookCoverStampingFoilMaker.pearlStock=4; BookCoverStampingFoilMaker.productStock={}; BookCoverStampingFoilMaker.buildings={}; BookCoverStampingFoilMaker.maker=nil; BookCoverStampingFoilMaker.activeMaking={}; BookCoverStampingFoilMaker.totalProducts=0; BookCoverStampingFoilMaker.dayTimer=0; print("[BookCoverStampingFoilMaker] Royal Book Cover Stamping Foil Maker System initialized (6 products, 4 buildings)") end
function BookCoverStampingFoilMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookCoverStampingFoilMaker.maker={name=n or ("Foljar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Foljar najet: %s (spretnost: %d)",BookCoverStampingFoilMaker.maker.name,s),"success") end; return true end
function BookCoverStampingFoilMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookCoverStampingFoilMaker.build(id) local ok,e=BookCoverStampingFoilMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookCoverStampingFoilMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookCoverStampingFoilMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookCoverStampingFoilMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookCoverStampingFoilMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookCoverStampingFoilMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookCoverStampingFoilMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookCoverStampingFoilMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookCoverStampingFoilMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookCoverStampingFoilMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookCoverStampingFoilMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookCoverStampingFoilMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookCoverStampingFoilMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookCoverStampingFoilMaker.buildings==0 then return false,"Potrebna foljna delavnica" end; if not BookCoverStampingFoilMaker.maker then return false,"Potreben foljar" end; return true end
function BookCoverStampingFoilMaker.make(pt,qty) qty=qty or 1; local ok,e=BookCoverStampingFoilMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookCoverStampingFoilMaker.ironStock=BookCoverStampingFoilMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookCoverStampingFoilMaker.bronzeStock=BookCoverStampingFoilMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookCoverStampingFoilMaker.woodStock=BookCoverStampingFoilMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookCoverStampingFoilMaker.leatherStock=BookCoverStampingFoilMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookCoverStampingFoilMaker.silverStock=BookCoverStampingFoilMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookCoverStampingFoilMaker.goldStock=BookCoverStampingFoilMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookCoverStampingFoilMaker.jewelStock=BookCoverStampingFoilMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookCoverStampingFoilMaker.pearlStock=BookCoverStampingFoilMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookCoverStampingFoilMaker.maker then t=math.max(1,t-math.floor(BookCoverStampingFoilMaker.maker.skill/13)) end; table.insert(BookCoverStampingFoilMaker.activeMaking,{id="bookcoverstampingfoil_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookCoverStampingFoilMaker.completeMaking(m) local q=1.0+(BookCoverStampingFoilMaker.getQualityBonus()/100); if BookCoverStampingFoilMaker.maker then q=q+(BookCoverStampingFoilMaker.maker.skill/140) end; q=math.min(2.5,q); BookCoverStampingFoilMaker.productStock[m.productType]=(BookCoverStampingFoilMaker.productStock[m.productType] or 0)+m.quantity; BookCoverStampingFoilMaker.totalProducts=BookCoverStampingFoilMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookCoverStampingFoilMaker.maker then BookCoverStampingFoilMaker.maker.itemsMade=BookCoverStampingFoilMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookCoverStampingFoilMaker.maker.skill=math.min(100,BookCoverStampingFoilMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Folija izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookcoverstampingfoil.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookCoverStampingFoilMaker.update(dt) if not _G.state then return end; BookCoverStampingFoilMaker.dayTimer=BookCoverStampingFoilMaker.dayTimer+dt; if BookCoverStampingFoilMaker.dayTimer>=30 then BookCoverStampingFoilMaker.dayTimer=0; for i=#BookCoverStampingFoilMaker.activeMaking,1,-1 do local m=BookCoverStampingFoilMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookCoverStampingFoilMaker.completeMaking(m); table.remove(BookCoverStampingFoilMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookCoverStampingFoilMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookCoverStampingFoilMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookCoverStampingFoilMaker.getStats() return {ironStock=BookCoverStampingFoilMaker.ironStock,bronzeStock=BookCoverStampingFoilMaker.bronzeStock,woodStock=BookCoverStampingFoilMaker.woodStock,leatherStock=BookCoverStampingFoilMaker.leatherStock,silverStock=BookCoverStampingFoilMaker.silverStock,goldStock=BookCoverStampingFoilMaker.goldStock,jewelStock=BookCoverStampingFoilMaker.jewelStock,pearlStock=BookCoverStampingFoilMaker.pearlStock,productStock=BookCoverStampingFoilMaker.productStock,numBuildings=#BookCoverStampingFoilMaker.buildings,hasMaker=BookCoverStampingFoilMaker.maker~=nil,makerName=BookCoverStampingFoilMaker.maker and BookCoverStampingFoilMaker.maker.name or "—",makerSkill=BookCoverStampingFoilMaker.maker and BookCoverStampingFoilMaker.maker.skill or 0,activeMaking=#BookCoverStampingFoilMaker.activeMaking,totalProducts=BookCoverStampingFoilMaker.totalProducts} end
return BookCoverStampingFoilMaker
