local FlourSackMaker = {}
local PRODUCTS = {
    iron_floursack = { name = "Železni vrecka za moko", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni vrecka za moko za mlinarje." },
    bronze_floursack = { name = "Bronast vrecka za moko", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast vrecka za moko za mlinarje." },
    silver_floursack = { name = "Srebrn vrecka za moko", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn vrecka za moko za mlinarje." },
    gilded_floursack = { name = "Pozlačen vrecka za moko", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen vrecka za moko za mlinarje." },
    jewel_set_floursack = { name = "Draguljast vrecka za moko", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast vrecka za moko za mlinarje." },
    royal_sovereign_floursack = { name = "Kraljevski suveren vrecka za moko", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren vrecka za moko z biseri za krono." },
}
local BUILDINGS = {
    floursack_workshop = { name = "Floursack delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    floursack_house = { name = "Floursack hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_floursack_atelier = { name = "Mojstrski floursack atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_floursack_palace = { name = "Suverena floursack palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
FlourSackMaker.ironStock = 10; FlourSackMaker.bronzeStock = 8; FlourSackMaker.woodStock = 14; FlourSackMaker.leatherStock = 18; FlourSackMaker.silverStock = 8; FlourSackMaker.goldStock = 6; FlourSackMaker.jewelStock = 4; FlourSackMaker.pearlStock = 4
FlourSackMaker.productStock = {}; FlourSackMaker.buildings = {}; FlourSackMaker.maker = nil; FlourSackMaker.activeMaking = {}; FlourSackMaker.totalProducts = 0; FlourSackMaker.dayTimer = 0
function FlourSackMaker.init() FlourSackMaker.ironStock=10; FlourSackMaker.bronzeStock=8; FlourSackMaker.woodStock=14; FlourSackMaker.leatherStock=18; FlourSackMaker.silverStock=8; FlourSackMaker.goldStock=6; FlourSackMaker.jewelStock=4; FlourSackMaker.pearlStock=4; FlourSackMaker.productStock={}; FlourSackMaker.buildings={}; FlourSackMaker.maker=nil; FlourSackMaker.activeMaking={}; FlourSackMaker.totalProducts=0; FlourSackMaker.dayTimer=0; print("[FlourSackMaker] Royal Flour Sack Maker System initialized (6 products, 4 buildings)") end
function FlourSackMaker.hireMaker(n,s) s=s or math.random(55,90); local c=565+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; FlourSackMaker.maker={name=n or ("Vreckar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vreckar najet: %s (spretnost: %d)",FlourSackMaker.maker.name,s),"success") end; return true end
function FlourSackMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function FlourSackMaker.build(id) local ok,e=FlourSackMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(FlourSackMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function FlourSackMaker.getQualityBonus() local b=0; for _,bd in ipairs(FlourSackMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function FlourSackMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and FlourSackMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and FlourSackMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and FlourSackMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and FlourSackMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and FlourSackMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and FlourSackMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and FlourSackMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and FlourSackMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #FlourSackMaker.buildings==0 then return false,"Potrebna vreckarska delavnica" end; if not FlourSackMaker.maker then return false,"Potreben vreckar" end; return true end
function FlourSackMaker.make(pt,qty) qty=qty or 1; local ok,e=FlourSackMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then FlourSackMaker.ironStock=FlourSackMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then FlourSackMaker.bronzeStock=FlourSackMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then FlourSackMaker.woodStock=FlourSackMaker.woodStock-d.woodCost*qty end; if d.leatherCost then FlourSackMaker.leatherStock=FlourSackMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then FlourSackMaker.silverStock=FlourSackMaker.silverStock-d.silverCost*qty end; if d.goldCost then FlourSackMaker.goldStock=FlourSackMaker.goldStock-d.goldCost*qty end; if d.jewelCost then FlourSackMaker.jewelStock=FlourSackMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then FlourSackMaker.pearlStock=FlourSackMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if FlourSackMaker.maker then t=math.max(1,t-math.floor(FlourSackMaker.maker.skill/13)) end; table.insert(FlourSackMaker.activeMaking,{id="floursack_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function FlourSackMaker.completeMaking(m) local q=1.0+(FlourSackMaker.getQualityBonus()/100); if FlourSackMaker.maker then q=q+(FlourSackMaker.maker.skill/140) end; q=math.min(2.5,q); FlourSackMaker.productStock[m.productType]=(FlourSackMaker.productStock[m.productType] or 0)+m.quantity; FlourSackMaker.totalProducts=FlourSackMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if FlourSackMaker.maker then FlourSackMaker.maker.itemsMade=FlourSackMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then FlourSackMaker.maker.skill=math.min(100,FlourSackMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrecka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"floursack.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function FlourSackMaker.update(dt) if not _G.state then return end; FlourSackMaker.dayTimer=FlourSackMaker.dayTimer+dt; if FlourSackMaker.dayTimer>=30 then FlourSackMaker.dayTimer=0; for i=#FlourSackMaker.activeMaking,1,-1 do local m=FlourSackMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then FlourSackMaker.completeMaking(m); table.remove(FlourSackMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(FlourSackMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if FlourSackMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function FlourSackMaker.getStats() return {ironStock=FlourSackMaker.ironStock,bronzeStock=FlourSackMaker.bronzeStock,woodStock=FlourSackMaker.woodStock,leatherStock=FlourSackMaker.leatherStock,silverStock=FlourSackMaker.silverStock,goldStock=FlourSackMaker.goldStock,jewelStock=FlourSackMaker.jewelStock,pearlStock=FlourSackMaker.pearlStock,productStock=FlourSackMaker.productStock,numBuildings=#FlourSackMaker.buildings,hasMaker=FlourSackMaker.maker~=nil,makerName=FlourSackMaker.maker and FlourSackMaker.maker.name or "—",makerSkill=FlourSackMaker.maker and FlourSackMaker.maker.skill or 0,activeMaking=#FlourSackMaker.activeMaking,totalProducts=FlourSackMaker.totalProducts} end
return FlourSackMaker
