local GlassMoltenGlassSkimLadleMaker = {}
local PRODUCTS = {
    iron_glassmoltenglassskimladle = { name = "Železni zajemalka za strgalce taline", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni zajemalka za strgalce taline za steklarje." },
    bronze_glassmoltenglassskimladle = { name = "Bronast zajemalka za strgalce taline", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast zajemalka za strgalce taline za steklarje." },
    silver_glassmoltenglassskimladle = { name = "Srebrn zajemalka za strgalce taline", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn zajemalka za strgalce taline za steklarje." },
    gilded_glassmoltenglassskimladle = { name = "Pozlačen zajemalka za strgalce taline", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen zajemalka za strgalce taline za steklarje." },
    jewel_set_glassmoltenglassskimladle = { name = "Draguljast zajemalka za strgalce taline", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast zajemalka za strgalce taline za steklarje." },
    royal_sovereign_glassmoltenglassskimladle = { name = "Kraljevski suveren zajemalka za strgalce taline", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren zajemalka za strgalce taline z biseri za krono." },
}
local BUILDINGS = {
    glassmoltenglassskimladle_workshop = { name = "Glassmoltenglassskimladle delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glassmoltenglassskimladle_house = { name = "Glassmoltenglassskimladle hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glassmoltenglassskimladle_atelier = { name = "Mojstrski glassmoltenglassskimladle atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glassmoltenglassskimladle_palace = { name = "Suverena glassmoltenglassskimladle palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassMoltenGlassSkimLadleMaker.ironStock=14; GlassMoltenGlassSkimLadleMaker.bronzeStock=12; GlassMoltenGlassSkimLadleMaker.woodStock=12; GlassMoltenGlassSkimLadleMaker.leatherStock=8; GlassMoltenGlassSkimLadleMaker.silverStock=8; GlassMoltenGlassSkimLadleMaker.goldStock=6; GlassMoltenGlassSkimLadleMaker.jewelStock=4; GlassMoltenGlassSkimLadleMaker.pearlStock=4
GlassMoltenGlassSkimLadleMaker.productStock = {}; GlassMoltenGlassSkimLadleMaker.buildings = {}; GlassMoltenGlassSkimLadleMaker.maker = nil; GlassMoltenGlassSkimLadleMaker.activeMaking = {}; GlassMoltenGlassSkimLadleMaker.totalProducts = 0; GlassMoltenGlassSkimLadleMaker.dayTimer = 0
function GlassMoltenGlassSkimLadleMaker.init() GlassMoltenGlassSkimLadleMaker.ironStock=14; GlassMoltenGlassSkimLadleMaker.bronzeStock=12; GlassMoltenGlassSkimLadleMaker.woodStock=12; GlassMoltenGlassSkimLadleMaker.leatherStock=8; GlassMoltenGlassSkimLadleMaker.silverStock=8; GlassMoltenGlassSkimLadleMaker.goldStock=6; GlassMoltenGlassSkimLadleMaker.jewelStock=4; GlassMoltenGlassSkimLadleMaker.pearlStock=4; GlassMoltenGlassSkimLadleMaker.productStock={}; GlassMoltenGlassSkimLadleMaker.buildings={}; GlassMoltenGlassSkimLadleMaker.maker=nil; GlassMoltenGlassSkimLadleMaker.activeMaking={}; GlassMoltenGlassSkimLadleMaker.totalProducts=0; GlassMoltenGlassSkimLadleMaker.dayTimer=0; print("[GlassMoltenGlassSkimLadleMaker] Royal Glass Molten Glass Skim Ladle Maker System initialized (6 products, 4 buildings)") end
function GlassMoltenGlassSkimLadleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassMoltenGlassSkimLadleMaker.maker={name=n or ("Zajemalkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zajemalkar najet: %s (spretnost: %d)",GlassMoltenGlassSkimLadleMaker.maker.name,s),"success") end; return true end
function GlassMoltenGlassSkimLadleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassMoltenGlassSkimLadleMaker.build(id) local ok,e=GlassMoltenGlassSkimLadleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassMoltenGlassSkimLadleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassMoltenGlassSkimLadleMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassMoltenGlassSkimLadleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassMoltenGlassSkimLadleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassMoltenGlassSkimLadleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassMoltenGlassSkimLadleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassMoltenGlassSkimLadleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassMoltenGlassSkimLadleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassMoltenGlassSkimLadleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassMoltenGlassSkimLadleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassMoltenGlassSkimLadleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassMoltenGlassSkimLadleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassMoltenGlassSkimLadleMaker.buildings==0 then return false,"Potrebna zajemalna delavnica" end; if not GlassMoltenGlassSkimLadleMaker.maker then return false,"Potreben zajemalkar" end; return true end
function GlassMoltenGlassSkimLadleMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassMoltenGlassSkimLadleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassMoltenGlassSkimLadleMaker.ironStock=GlassMoltenGlassSkimLadleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassMoltenGlassSkimLadleMaker.bronzeStock=GlassMoltenGlassSkimLadleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassMoltenGlassSkimLadleMaker.woodStock=GlassMoltenGlassSkimLadleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassMoltenGlassSkimLadleMaker.leatherStock=GlassMoltenGlassSkimLadleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassMoltenGlassSkimLadleMaker.silverStock=GlassMoltenGlassSkimLadleMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassMoltenGlassSkimLadleMaker.goldStock=GlassMoltenGlassSkimLadleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassMoltenGlassSkimLadleMaker.jewelStock=GlassMoltenGlassSkimLadleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassMoltenGlassSkimLadleMaker.pearlStock=GlassMoltenGlassSkimLadleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassMoltenGlassSkimLadleMaker.maker then t=math.max(1,t-math.floor(GlassMoltenGlassSkimLadleMaker.maker.skill/13)) end; table.insert(GlassMoltenGlassSkimLadleMaker.activeMaking,{id="glassmoltenglassskimladle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassMoltenGlassSkimLadleMaker.completeMaking(m) local q=1.0+(GlassMoltenGlassSkimLadleMaker.getQualityBonus()/100); if GlassMoltenGlassSkimLadleMaker.maker then q=q+(GlassMoltenGlassSkimLadleMaker.maker.skill/140) end; q=math.min(2.5,q); GlassMoltenGlassSkimLadleMaker.productStock[m.productType]=(GlassMoltenGlassSkimLadleMaker.productStock[m.productType] or 0)+m.quantity; GlassMoltenGlassSkimLadleMaker.totalProducts=GlassMoltenGlassSkimLadleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassMoltenGlassSkimLadleMaker.maker then GlassMoltenGlassSkimLadleMaker.maker.itemsMade=GlassMoltenGlassSkimLadleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassMoltenGlassSkimLadleMaker.maker.skill=math.min(100,GlassMoltenGlassSkimLadleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zajemalka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glassmoltenglassskimladle.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassMoltenGlassSkimLadleMaker.update(dt) if not _G.state then return end; GlassMoltenGlassSkimLadleMaker.dayTimer=GlassMoltenGlassSkimLadleMaker.dayTimer+dt; if GlassMoltenGlassSkimLadleMaker.dayTimer>=30 then GlassMoltenGlassSkimLadleMaker.dayTimer=0; for i=#GlassMoltenGlassSkimLadleMaker.activeMaking,1,-1 do local m=GlassMoltenGlassSkimLadleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassMoltenGlassSkimLadleMaker.completeMaking(m); table.remove(GlassMoltenGlassSkimLadleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassMoltenGlassSkimLadleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassMoltenGlassSkimLadleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassMoltenGlassSkimLadleMaker.getStats() return {ironStock=GlassMoltenGlassSkimLadleMaker.ironStock,bronzeStock=GlassMoltenGlassSkimLadleMaker.bronzeStock,woodStock=GlassMoltenGlassSkimLadleMaker.woodStock,leatherStock=GlassMoltenGlassSkimLadleMaker.leatherStock,silverStock=GlassMoltenGlassSkimLadleMaker.silverStock,goldStock=GlassMoltenGlassSkimLadleMaker.goldStock,jewelStock=GlassMoltenGlassSkimLadleMaker.jewelStock,pearlStock=GlassMoltenGlassSkimLadleMaker.pearlStock,productStock=GlassMoltenGlassSkimLadleMaker.productStock,numBuildings=#GlassMoltenGlassSkimLadleMaker.buildings,hasMaker=GlassMoltenGlassSkimLadleMaker.maker~=nil,makerName=GlassMoltenGlassSkimLadleMaker.maker and GlassMoltenGlassSkimLadleMaker.maker.name or "—",makerSkill=GlassMoltenGlassSkimLadleMaker.maker and GlassMoltenGlassSkimLadleMaker.maker.skill or 0,activeMaking=#GlassMoltenGlassSkimLadleMaker.activeMaking,totalProducts=GlassMoltenGlassSkimLadleMaker.totalProducts} end
return GlassMoltenGlassSkimLadleMaker
