local WoodLatheMaker = {}
local PRODUCTS = {
    simple_wood_lathe = { name = "Preprost leseni stružnica", woodCost = 5, ironCost = 2, time = 6, cost = 200, science = 22, happiness = 1, description = "Preprost leseni stružnica za oblikovanje." },
    iron_reinforced_lathe = { name = "Železnookrepljen stružnica", woodCost = 4, ironCost = 3, steelCost = 1, time = 9, cost = 480, science = 35, happiness = 2, prestige = 2, description = "Železnookrepljen stružnica za trgovce." },
    silver_spindle_lathe = { name = "Srebrnavretenni stružnica", woodCost = 4, ironCost = 2, silverCost = 1, steelCost = 1, time = 13, cost = 1100, science = 50, happiness = 2, prestige = 6, description = "Srebrnavretenni stružnica za plemiče." },
    gold_trimmed_lathe = { name = "Zlatookrasni stružnica", woodCost = 4, ironCost = 2, goldCost = 1, silverCost = 1, steelCost = 1, time = 17, cost = 2500, science = 65, happiness = 3, prestige = 14, description = "Zlatookrasni stružnica za visoke plemiče." },
    jewel_set_lathe = { name = "Draguljasta stružnica", woodCost = 4, ironCost = 2, goldCost = 1, silverCost = 1, steelCost = 1, jewelCost = 1, time = 21, cost = 5200, science = 80, happiness = 5, prestige = 27, description = "Stružnica z draguljem za visoko plemstvo." },
    royal_grand_lathe = { name = "Kraljevski veliki stružnica", woodCost = 6, ironCost = 3, goldCost = 2, silverCost = 2, steelCost = 1, jewelCost = 2, pearlCost = 2, time = 28, cost = 11000, science = 95, happiness = 12, prestige = 58, description = "Veliki kraljevski stružnica z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    lathe_workshop = { name = "Stružniška delavnica", cost = { gold = 320, wood = 180, stone = 140, iron = 6 }, upkeep = 7, qualityBonus = 5 },
    machinery_loft = { name = "Strojna podstrešje", cost = { gold = 1100, wood = 320, stone = 280, silver = 6, steel = 4 }, upkeep = 26, qualityBonus = 18 },
    master_machinist_atelier = { name = "Mojstrski strojniški atelje", cost = { gold = 2900, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 68, qualityBonus = 30 },
    royal_machinery_palace = { name = "Kraljevska strojna palača", cost = { gold = 12500, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 250, qualityBonus = 55, prestigeBonus = 50 },
}
WoodLatheMaker.woodStock = 22; WoodLatheMaker.ironStock = 14; WoodLatheMaker.steelStock = 8; WoodLatheMaker.silverStock = 6; WoodLatheMaker.goldStock = 6; WoodLatheMaker.jewelStock = 4; WoodLatheMaker.pearlStock = 4
WoodLatheMaker.productStock = {}; WoodLatheMaker.buildings = {}; WoodLatheMaker.maker = nil; WoodLatheMaker.activeMaking = {}; WoodLatheMaker.totalProducts = 0; WoodLatheMaker.dayTimer = 0
function WoodLatheMaker.init() WoodLatheMaker.woodStock=22; WoodLatheMaker.ironStock=14; WoodLatheMaker.steelStock=8; WoodLatheMaker.silverStock=6; WoodLatheMaker.goldStock=6; WoodLatheMaker.jewelStock=4; WoodLatheMaker.pearlStock=4; WoodLatheMaker.productStock={}; WoodLatheMaker.buildings={}; WoodLatheMaker.maker=nil; WoodLatheMaker.activeMaking={}; WoodLatheMaker.totalProducts=0; WoodLatheMaker.dayTimer=0; print("[WoodLatheMaker] Royal Wood Lathe Maker System initialized (6 products, 4 buildings)") end
function WoodLatheMaker.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; WoodLatheMaker.maker={name=n or ("Stružnikar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stružnikar najet: %s (spretnost: %d)",WoodLatheMaker.maker.name,s),"success") end; return true end
function WoodLatheMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function WoodLatheMaker.build(id) local ok,e=WoodLatheMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(WoodLatheMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function WoodLatheMaker.getQualityBonus() local b=0; for _,bd in ipairs(WoodLatheMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function WoodLatheMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and WoodLatheMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and WoodLatheMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and WoodLatheMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.silverCost and WoodLatheMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and WoodLatheMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and WoodLatheMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and WoodLatheMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #WoodLatheMaker.buildings==0 then return false,"Potrebna stružniška delavnica" end; if not WoodLatheMaker.maker then return false,"Potreben stružnikar" end; return true end
function WoodLatheMaker.make(pt,qty) qty=qty or 1; local ok,e=WoodLatheMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then WoodLatheMaker.woodStock=WoodLatheMaker.woodStock-d.woodCost*qty end; if d.ironCost then WoodLatheMaker.ironStock=WoodLatheMaker.ironStock-d.ironCost*qty end; if d.steelCost then WoodLatheMaker.steelStock=WoodLatheMaker.steelStock-d.steelCost*qty end; if d.silverCost then WoodLatheMaker.silverStock=WoodLatheMaker.silverStock-d.silverCost*qty end; if d.goldCost then WoodLatheMaker.goldStock=WoodLatheMaker.goldStock-d.goldCost*qty end; if d.jewelCost then WoodLatheMaker.jewelStock=WoodLatheMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then WoodLatheMaker.pearlStock=WoodLatheMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if WoodLatheMaker.maker then t=math.max(1,t-math.floor(WoodLatheMaker.maker.skill/12)) end; table.insert(WoodLatheMaker.activeMaking,{id="woodlathe_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function WoodLatheMaker.completeMaking(m) local q=1.0+(WoodLatheMaker.getQualityBonus()/100); if WoodLatheMaker.maker then q=q+(WoodLatheMaker.maker.skill/140) end; q=math.min(2.5,q); WoodLatheMaker.productStock[m.productType]=(WoodLatheMaker.productStock[m.productType] or 0)+m.quantity; WoodLatheMaker.totalProducts=WoodLatheMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if WoodLatheMaker.maker then WoodLatheMaker.maker.itemsMade=WoodLatheMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then WoodLatheMaker.maker.skill=math.min(100,WoodLatheMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stružnica izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"woodlathe.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function WoodLatheMaker.update(dt) if not _G.state then return end; WoodLatheMaker.dayTimer=WoodLatheMaker.dayTimer+dt; if WoodLatheMaker.dayTimer>=30 then WoodLatheMaker.dayTimer=0; for i=#WoodLatheMaker.activeMaking,1,-1 do local m=WoodLatheMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then WoodLatheMaker.completeMaking(m); table.remove(WoodLatheMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(WoodLatheMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if WoodLatheMaker.maker then tu=tu+16 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function WoodLatheMaker.getStats() return {woodStock=WoodLatheMaker.woodStock,ironStock=WoodLatheMaker.ironStock,steelStock=WoodLatheMaker.steelStock,silverStock=WoodLatheMaker.silverStock,goldStock=WoodLatheMaker.goldStock,jewelStock=WoodLatheMaker.jewelStock,pearlStock=WoodLatheMaker.pearlStock,productStock=WoodLatheMaker.productStock,numBuildings=#WoodLatheMaker.buildings,hasMaker=WoodLatheMaker.maker~=nil,makerName=WoodLatheMaker.maker and WoodLatheMaker.maker.name or "—",makerSkill=WoodLatheMaker.maker and WoodLatheMaker.maker.skill or 0,activeMaking=#WoodLatheMaker.activeMaking,totalProducts=WoodLatheMaker.totalProducts} end
return WoodLatheMaker
