local BathBucketMaker = {}
local PRODUCTS = {
    iron_bathbucket = { name = "Železni kopališko vedro", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni kopališko vedro za kopališča." },
    bronze_bathbucket = { name = "Bronast kopališko vedro", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast kopališko vedro za kopališča." },
    silver_bathbucket = { name = "Srebrn kopališko vedro", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn kopališko vedro za kopališča." },
    gilded_bathbucket = { name = "Pozlačen kopališko vedro", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen kopališko vedro za kopališča." },
    jewel_set_bathbucket = { name = "Draguljast kopališko vedro", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast kopališko vedro za kopališča." },
    royal_sovereign_bathbucket = { name = "Kraljevski suveren kopališko vedro", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren kopališko vedro z biseri za krono." },
}
local BUILDINGS = {
    bathbucket_workshop = { name = "Bathbucket delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bathbucket_house = { name = "Bathbucket hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bathbucket_atelier = { name = "Mojstrski bathbucket atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bathbucket_palace = { name = "Suverena bathbucket palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BathBucketMaker.ironStock = 10; BathBucketMaker.bronzeStock = 8; BathBucketMaker.woodStock = 18; BathBucketMaker.leatherStock = 12; BathBucketMaker.silverStock = 8; BathBucketMaker.goldStock = 6; BathBucketMaker.jewelStock = 4; BathBucketMaker.pearlStock = 4
BathBucketMaker.productStock = {}; BathBucketMaker.buildings = {}; BathBucketMaker.maker = nil; BathBucketMaker.activeMaking = {}; BathBucketMaker.totalProducts = 0; BathBucketMaker.dayTimer = 0
function BathBucketMaker.init() BathBucketMaker.ironStock=10; BathBucketMaker.bronzeStock=8; BathBucketMaker.woodStock=18; BathBucketMaker.leatherStock=12; BathBucketMaker.silverStock=8; BathBucketMaker.goldStock=6; BathBucketMaker.jewelStock=4; BathBucketMaker.pearlStock=4; BathBucketMaker.productStock={}; BathBucketMaker.buildings={}; BathBucketMaker.maker=nil; BathBucketMaker.activeMaking={}; BathBucketMaker.totalProducts=0; BathBucketMaker.dayTimer=0; print("[BathBucketMaker] Royal Bath Bucket Maker System initialized (6 products, 4 buildings)") end
function BathBucketMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BathBucketMaker.maker={name=n or ("Vedrnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vedrnar najet: %s (spretnost: %d)",BathBucketMaker.maker.name,s),"success") end; return true end
function BathBucketMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BathBucketMaker.build(id) local ok,e=BathBucketMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BathBucketMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BathBucketMaker.getQualityBonus() local b=0; for _,bd in ipairs(BathBucketMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BathBucketMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BathBucketMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BathBucketMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BathBucketMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BathBucketMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BathBucketMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BathBucketMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BathBucketMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BathBucketMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BathBucketMaker.buildings==0 then return false,"Potrebna vedrarska delavnica" end; if not BathBucketMaker.maker then return false,"Potreben vedrnar" end; return true end
function BathBucketMaker.make(pt,qty) qty=qty or 1; local ok,e=BathBucketMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BathBucketMaker.ironStock=BathBucketMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BathBucketMaker.bronzeStock=BathBucketMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BathBucketMaker.woodStock=BathBucketMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BathBucketMaker.leatherStock=BathBucketMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BathBucketMaker.silverStock=BathBucketMaker.silverStock-d.silverCost*qty end; if d.goldCost then BathBucketMaker.goldStock=BathBucketMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BathBucketMaker.jewelStock=BathBucketMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BathBucketMaker.pearlStock=BathBucketMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BathBucketMaker.maker then t=math.max(1,t-math.floor(BathBucketMaker.maker.skill/13)) end; table.insert(BathBucketMaker.activeMaking,{id="bathbucket_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BathBucketMaker.completeMaking(m) local q=1.0+(BathBucketMaker.getQualityBonus()/100); if BathBucketMaker.maker then q=q+(BathBucketMaker.maker.skill/140) end; q=math.min(2.5,q); BathBucketMaker.productStock[m.productType]=(BathBucketMaker.productStock[m.productType] or 0)+m.quantity; BathBucketMaker.totalProducts=BathBucketMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BathBucketMaker.maker then BathBucketMaker.maker.itemsMade=BathBucketMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BathBucketMaker.maker.skill=math.min(100,BathBucketMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vedro izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bathbucket.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BathBucketMaker.update(dt) if not _G.state then return end; BathBucketMaker.dayTimer=BathBucketMaker.dayTimer+dt; if BathBucketMaker.dayTimer>=30 then BathBucketMaker.dayTimer=0; for i=#BathBucketMaker.activeMaking,1,-1 do local m=BathBucketMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BathBucketMaker.completeMaking(m); table.remove(BathBucketMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BathBucketMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BathBucketMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BathBucketMaker.getStats() return {ironStock=BathBucketMaker.ironStock,bronzeStock=BathBucketMaker.bronzeStock,woodStock=BathBucketMaker.woodStock,leatherStock=BathBucketMaker.leatherStock,silverStock=BathBucketMaker.silverStock,goldStock=BathBucketMaker.goldStock,jewelStock=BathBucketMaker.jewelStock,pearlStock=BathBucketMaker.pearlStock,productStock=BathBucketMaker.productStock,numBuildings=#BathBucketMaker.buildings,hasMaker=BathBucketMaker.maker~=nil,makerName=BathBucketMaker.maker and BathBucketMaker.maker.name or "—",makerSkill=BathBucketMaker.maker and BathBucketMaker.maker.skill or 0,activeMaking=#BathBucketMaker.activeMaking,totalProducts=BathBucketMaker.totalProducts} end
return BathBucketMaker
