local GardenCompostThermometerProbeMaker = {}
local PRODUCTS = {
    iron_gardencompostthermometerprobe = { name = "Železni sonda za kompost", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni sonda za kompost za vrtnarje." },
    bronze_gardencompostthermometerprobe = { name = "Bronast sonda za kompost", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast sonda za kompost za vrtnarje." },
    silver_gardencompostthermometerprobe = { name = "Srebrn sonda za kompost", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn sonda za kompost za vrtnarje." },
    gilded_gardencompostthermometerprobe = { name = "Pozlačen sonda za kompost", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen sonda za kompost za vrtnarje." },
    jewel_set_gardencompostthermometerprobe = { name = "Draguljast sonda za kompost", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast sonda za kompost za vrtnarje." },
    royal_sovereign_gardencompostthermometerprobe = { name = "Kraljevski suveren sonda za kompost", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren sonda za kompost z biseri za krono." },
}
local BUILDINGS = {
    gardencompostthermometerprobe_workshop = { name = "Gardencompostthermometerprobe delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardencompostthermometerprobe_house = { name = "Gardencompostthermometerprobe hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardencompostthermometerprobe_atelier = { name = "Mojstrski gardencompostthermometerprobe atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardencompostthermometerprobe_palace = { name = "Suverena gardencompostthermometerprobe palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenCompostThermometerProbeMaker.ironStock=14; GardenCompostThermometerProbeMaker.bronzeStock=12; GardenCompostThermometerProbeMaker.woodStock=12; GardenCompostThermometerProbeMaker.leatherStock=8; GardenCompostThermometerProbeMaker.silverStock=8; GardenCompostThermometerProbeMaker.goldStock=6; GardenCompostThermometerProbeMaker.jewelStock=4; GardenCompostThermometerProbeMaker.pearlStock=4
GardenCompostThermometerProbeMaker.productStock = {}; GardenCompostThermometerProbeMaker.buildings = {}; GardenCompostThermometerProbeMaker.maker = nil; GardenCompostThermometerProbeMaker.activeMaking = {}; GardenCompostThermometerProbeMaker.totalProducts = 0; GardenCompostThermometerProbeMaker.dayTimer = 0
function GardenCompostThermometerProbeMaker.init() GardenCompostThermometerProbeMaker.ironStock=14; GardenCompostThermometerProbeMaker.bronzeStock=12; GardenCompostThermometerProbeMaker.woodStock=12; GardenCompostThermometerProbeMaker.leatherStock=8; GardenCompostThermometerProbeMaker.silverStock=8; GardenCompostThermometerProbeMaker.goldStock=6; GardenCompostThermometerProbeMaker.jewelStock=4; GardenCompostThermometerProbeMaker.pearlStock=4; GardenCompostThermometerProbeMaker.productStock={}; GardenCompostThermometerProbeMaker.buildings={}; GardenCompostThermometerProbeMaker.maker=nil; GardenCompostThermometerProbeMaker.activeMaking={}; GardenCompostThermometerProbeMaker.totalProducts=0; GardenCompostThermometerProbeMaker.dayTimer=0; print("[GardenCompostThermometerProbeMaker] Royal Garden Compost Thermometer Probe Maker System initialized (6 products, 4 buildings)") end
function GardenCompostThermometerProbeMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenCompostThermometerProbeMaker.maker={name=n or ("Sondar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sondar najet: %s (spretnost: %d)",GardenCompostThermometerProbeMaker.maker.name,s),"success") end; return true end
function GardenCompostThermometerProbeMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenCompostThermometerProbeMaker.build(id) local ok,e=GardenCompostThermometerProbeMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenCompostThermometerProbeMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenCompostThermometerProbeMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenCompostThermometerProbeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenCompostThermometerProbeMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenCompostThermometerProbeMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenCompostThermometerProbeMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenCompostThermometerProbeMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenCompostThermometerProbeMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenCompostThermometerProbeMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenCompostThermometerProbeMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenCompostThermometerProbeMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenCompostThermometerProbeMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenCompostThermometerProbeMaker.buildings==0 then return false,"Potrebna sondalna delavnica" end; if not GardenCompostThermometerProbeMaker.maker then return false,"Potreben sondar" end; return true end
function GardenCompostThermometerProbeMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenCompostThermometerProbeMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenCompostThermometerProbeMaker.ironStock=GardenCompostThermometerProbeMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenCompostThermometerProbeMaker.bronzeStock=GardenCompostThermometerProbeMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenCompostThermometerProbeMaker.woodStock=GardenCompostThermometerProbeMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenCompostThermometerProbeMaker.leatherStock=GardenCompostThermometerProbeMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenCompostThermometerProbeMaker.silverStock=GardenCompostThermometerProbeMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenCompostThermometerProbeMaker.goldStock=GardenCompostThermometerProbeMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenCompostThermometerProbeMaker.jewelStock=GardenCompostThermometerProbeMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenCompostThermometerProbeMaker.pearlStock=GardenCompostThermometerProbeMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenCompostThermometerProbeMaker.maker then t=math.max(1,t-math.floor(GardenCompostThermometerProbeMaker.maker.skill/13)) end; table.insert(GardenCompostThermometerProbeMaker.activeMaking,{id="gardencompostthermometerprobe_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenCompostThermometerProbeMaker.completeMaking(m) local q=1.0+(GardenCompostThermometerProbeMaker.getQualityBonus()/100); if GardenCompostThermometerProbeMaker.maker then q=q+(GardenCompostThermometerProbeMaker.maker.skill/140) end; q=math.min(2.5,q); GardenCompostThermometerProbeMaker.productStock[m.productType]=(GardenCompostThermometerProbeMaker.productStock[m.productType] or 0)+m.quantity; GardenCompostThermometerProbeMaker.totalProducts=GardenCompostThermometerProbeMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenCompostThermometerProbeMaker.maker then GardenCompostThermometerProbeMaker.maker.itemsMade=GardenCompostThermometerProbeMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenCompostThermometerProbeMaker.maker.skill=math.min(100,GardenCompostThermometerProbeMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sonda izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardencompostthermometerprobe.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenCompostThermometerProbeMaker.update(dt) if not _G.state then return end; GardenCompostThermometerProbeMaker.dayTimer=GardenCompostThermometerProbeMaker.dayTimer+dt; if GardenCompostThermometerProbeMaker.dayTimer>=30 then GardenCompostThermometerProbeMaker.dayTimer=0; for i=#GardenCompostThermometerProbeMaker.activeMaking,1,-1 do local m=GardenCompostThermometerProbeMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenCompostThermometerProbeMaker.completeMaking(m); table.remove(GardenCompostThermometerProbeMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenCompostThermometerProbeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenCompostThermometerProbeMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenCompostThermometerProbeMaker.getStats() return {ironStock=GardenCompostThermometerProbeMaker.ironStock,bronzeStock=GardenCompostThermometerProbeMaker.bronzeStock,woodStock=GardenCompostThermometerProbeMaker.woodStock,leatherStock=GardenCompostThermometerProbeMaker.leatherStock,silverStock=GardenCompostThermometerProbeMaker.silverStock,goldStock=GardenCompostThermometerProbeMaker.goldStock,jewelStock=GardenCompostThermometerProbeMaker.jewelStock,pearlStock=GardenCompostThermometerProbeMaker.pearlStock,productStock=GardenCompostThermometerProbeMaker.productStock,numBuildings=#GardenCompostThermometerProbeMaker.buildings,hasMaker=GardenCompostThermometerProbeMaker.maker~=nil,makerName=GardenCompostThermometerProbeMaker.maker and GardenCompostThermometerProbeMaker.maker.name or "—",makerSkill=GardenCompostThermometerProbeMaker.maker and GardenCompostThermometerProbeMaker.maker.skill or 0,activeMaking=#GardenCompostThermometerProbeMaker.activeMaking,totalProducts=GardenCompostThermometerProbeMaker.totalProducts} end
return GardenCompostThermometerProbeMaker
