local LadlePreheaterMaker = {}
local PRODUCTS = {
    iron_ladlepreheater = { name = "Železni predgrevalec zajemalk", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni predgrevalec zajemalk za livarje." },
    bronze_ladlepreheater = { name = "Bronast predgrevalec zajemalk", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast predgrevalec zajemalk za livarje." },
    silver_ladlepreheater = { name = "Srebrn predgrevalec zajemalk", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn predgrevalec zajemalk za livarje." },
    gilded_ladlepreheater = { name = "Pozlačen predgrevalec zajemalk", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen predgrevalec zajemalk za livarje." },
    jewel_set_ladlepreheater = { name = "Draguljast predgrevalec zajemalk", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast predgrevalec zajemalk za livarje." },
    royal_sovereign_ladlepreheater = { name = "Kraljevski suveren predgrevalec zajemalk", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren predgrevalec zajemalk z biseri za krono." },
}
local BUILDINGS = {
    ladlepreheater_workshop = { name = "Ladlepreheater delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    ladlepreheater_house = { name = "Ladlepreheater hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_ladlepreheater_atelier = { name = "Mojstrski ladlepreheater atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_ladlepreheater_palace = { name = "Suverena ladlepreheater palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
LadlePreheaterMaker.ironStock=16; LadlePreheaterMaker.bronzeStock=12; LadlePreheaterMaker.woodStock=12; LadlePreheaterMaker.leatherStock=8; LadlePreheaterMaker.silverStock=8; LadlePreheaterMaker.goldStock=6; LadlePreheaterMaker.jewelStock=4; LadlePreheaterMaker.pearlStock=4
LadlePreheaterMaker.productStock = {}; LadlePreheaterMaker.buildings = {}; LadlePreheaterMaker.maker = nil; LadlePreheaterMaker.activeMaking = {}; LadlePreheaterMaker.totalProducts = 0; LadlePreheaterMaker.dayTimer = 0
function LadlePreheaterMaker.init() LadlePreheaterMaker.ironStock=16; LadlePreheaterMaker.bronzeStock=12; LadlePreheaterMaker.woodStock=12; LadlePreheaterMaker.leatherStock=8; LadlePreheaterMaker.silverStock=8; LadlePreheaterMaker.goldStock=6; LadlePreheaterMaker.jewelStock=4; LadlePreheaterMaker.pearlStock=4; LadlePreheaterMaker.productStock={}; LadlePreheaterMaker.buildings={}; LadlePreheaterMaker.maker=nil; LadlePreheaterMaker.activeMaking={}; LadlePreheaterMaker.totalProducts=0; LadlePreheaterMaker.dayTimer=0; print("[LadlePreheaterMaker] Royal Ladle Preheater Maker System initialized (6 products, 4 buildings)") end
function LadlePreheaterMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LadlePreheaterMaker.maker={name=n or ("Predgrevalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Predgrevalec najet: %s (spretnost: %d)",LadlePreheaterMaker.maker.name,s),"success") end; return true end
function LadlePreheaterMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LadlePreheaterMaker.build(id) local ok,e=LadlePreheaterMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LadlePreheaterMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LadlePreheaterMaker.getQualityBonus() local b=0; for _,bd in ipairs(LadlePreheaterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LadlePreheaterMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and LadlePreheaterMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and LadlePreheaterMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and LadlePreheaterMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and LadlePreheaterMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and LadlePreheaterMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and LadlePreheaterMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and LadlePreheaterMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and LadlePreheaterMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #LadlePreheaterMaker.buildings==0 then return false,"Potrebna predgrevalna delavnica" end; if not LadlePreheaterMaker.maker then return false,"Potreben predgrevalec" end; return true end
function LadlePreheaterMaker.make(pt,qty) qty=qty or 1; local ok,e=LadlePreheaterMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then LadlePreheaterMaker.ironStock=LadlePreheaterMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then LadlePreheaterMaker.bronzeStock=LadlePreheaterMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then LadlePreheaterMaker.woodStock=LadlePreheaterMaker.woodStock-d.woodCost*qty end; if d.leatherCost then LadlePreheaterMaker.leatherStock=LadlePreheaterMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then LadlePreheaterMaker.silverStock=LadlePreheaterMaker.silverStock-d.silverCost*qty end; if d.goldCost then LadlePreheaterMaker.goldStock=LadlePreheaterMaker.goldStock-d.goldCost*qty end; if d.jewelCost then LadlePreheaterMaker.jewelStock=LadlePreheaterMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then LadlePreheaterMaker.pearlStock=LadlePreheaterMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if LadlePreheaterMaker.maker then t=math.max(1,t-math.floor(LadlePreheaterMaker.maker.skill/13)) end; table.insert(LadlePreheaterMaker.activeMaking,{id="ladlepreheater_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LadlePreheaterMaker.completeMaking(m) local q=1.0+(LadlePreheaterMaker.getQualityBonus()/100); if LadlePreheaterMaker.maker then q=q+(LadlePreheaterMaker.maker.skill/140) end; q=math.min(2.5,q); LadlePreheaterMaker.productStock[m.productType]=(LadlePreheaterMaker.productStock[m.productType] or 0)+m.quantity; LadlePreheaterMaker.totalProducts=LadlePreheaterMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LadlePreheaterMaker.maker then LadlePreheaterMaker.maker.itemsMade=LadlePreheaterMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then LadlePreheaterMaker.maker.skill=math.min(100,LadlePreheaterMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Predgrevač izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"ladlepreheater.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function LadlePreheaterMaker.update(dt) if not _G.state then return end; LadlePreheaterMaker.dayTimer=LadlePreheaterMaker.dayTimer+dt; if LadlePreheaterMaker.dayTimer>=30 then LadlePreheaterMaker.dayTimer=0; for i=#LadlePreheaterMaker.activeMaking,1,-1 do local m=LadlePreheaterMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LadlePreheaterMaker.completeMaking(m); table.remove(LadlePreheaterMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LadlePreheaterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LadlePreheaterMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LadlePreheaterMaker.getStats() return {ironStock=LadlePreheaterMaker.ironStock,bronzeStock=LadlePreheaterMaker.bronzeStock,woodStock=LadlePreheaterMaker.woodStock,leatherStock=LadlePreheaterMaker.leatherStock,silverStock=LadlePreheaterMaker.silverStock,goldStock=LadlePreheaterMaker.goldStock,jewelStock=LadlePreheaterMaker.jewelStock,pearlStock=LadlePreheaterMaker.pearlStock,productStock=LadlePreheaterMaker.productStock,numBuildings=#LadlePreheaterMaker.buildings,hasMaker=LadlePreheaterMaker.maker~=nil,makerName=LadlePreheaterMaker.maker and LadlePreheaterMaker.maker.name or "—",makerSkill=LadlePreheaterMaker.maker and LadlePreheaterMaker.maker.skill or 0,activeMaking=#LadlePreheaterMaker.activeMaking,totalProducts=LadlePreheaterMaker.totalProducts} end
return LadlePreheaterMaker
