local ArmillarySphereMaker = {}
local PRODUCTS = {
    brass_armillary = { name = "Medeninasta armilarna sfera", brassCost = 3, time = 6, cost = 120, accuracy = 55, prestige = 5, description = "Medeninasta armilarna sfera za astronomijo." },
    silver_armillary = { name = "Srebrna armilarna sfera", silverCost = 2, brassCost = 1, time = 8, cost = 300, accuracy = 70, prestige = 10, happiness = 1, description = "Srebrna armilarna sfera za učenjake." },
    engraved_armillary = { name = "Vgravirana armilarna sfera", silverCost = 2, brassCost = 1, goldCost = 1, time = 11, cost = 680, accuracy = 82, prestige = 16, happiness = 2, description = "Vgravirana armilarna sfera z zvezdnimi oznakami." },
    silver_meridian_armillary = { name = "Srebrnomeridian armilarna sfera", silverCost = 2, goldCost = 1, brassCost = 1, time = 14, cost = 1400, accuracy = 90, prestige = 24, happiness = 4, description = "Armilarna sfera s srebrnim meridianom za plemiče." },
    gold_ring_armillary = { name = "Zlatorobna armilarna sfera", goldCost = 2, silverCost = 1, jewelCost = 1, brassCost = 1, time = 18, cost = 2800, accuracy = 96, prestige = 38, happiness = 7, description = "Armilarna sfera z zlatimi obroči za visoke plemiče." },
    royal_grand_armillary = { name = "Kraljevski veliki armilarna sfera", goldCost = 3, silverCost = 2, jewelCost = 2, pearlCost = 1, brassCost = 1, time = 24, cost = 5000, accuracy = 100, prestige = 65, happiness = 14, description = "Veliki kraljevski armilarna sfera z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Armilarska delavnica", cost = { gold = 380, wood = 140, stone = 300 }, upkeep = 10, qualityBonus = 5 },
    sphere_forge = { name = "Sferna kovačija", cost = { gold = 1300, wood = 300, stone = 600, brass = 8 }, upkeep = 32, qualityBonus = 18 },
    calibration_observatory = { name = "Kalibracijski observatorij", cost = { gold = 3000, wood = 400, stone = 900, silver = 50, glass = 8 }, upkeep = 75, qualityBonus = 30 },
    royal_armillary_atelier = { name = "Kraljevski atelje armilarnih sfer", cost = { gold = 13000, wood = 700, stone = 1300, gold = 80, jewel = 25 }, upkeep = 260, qualityBonus = 55, prestigeBonus = 55 },
}
ArmillarySphereMaker.brassStock = 14; ArmillarySphereMaker.silverStock = 8; ArmillarySphereMaker.goldStock = 6; ArmillarySphereMaker.jewelStock = 6; ArmillarySphereMaker.pearlStock = 4
ArmillarySphereMaker.productStock = {}; ArmillarySphereMaker.buildings = {}; ArmillarySphereMaker.maker = nil; ArmillarySphereMaker.activeMaking = {}; ArmillarySphereMaker.totalProducts = 0; ArmillarySphereMaker.dayTimer = 0
function ArmillarySphereMaker.init() ArmillarySphereMaker.brassStock=14; ArmillarySphereMaker.silverStock=8; ArmillarySphereMaker.goldStock=6; ArmillarySphereMaker.jewelStock=6; ArmillarySphereMaker.pearlStock=4; ArmillarySphereMaker.productStock={}; ArmillarySphereMaker.buildings={}; ArmillarySphereMaker.maker=nil; ArmillarySphereMaker.activeMaking={}; ArmillarySphereMaker.totalProducts=0; ArmillarySphereMaker.dayTimer=0; print("[ArmillarySphereMaker] Royal Armillary Sphere Maker System initialized (6 products, 4 buildings)") end
function ArmillarySphereMaker.hireMaker(n,s) s=s or math.random(55,90); local c=620+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ArmillarySphereMaker.maker={name=n or ("Armilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Armilar najet: %s (spretnost: %d)",ArmillarySphereMaker.maker.name,s),"success") end; return true end
function ArmillarySphereMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ArmillarySphereMaker.build(id) local ok,e=ArmillarySphereMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ArmillarySphereMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ArmillarySphereMaker.getQualityBonus() local b=0; for _,bd in ipairs(ArmillarySphereMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ArmillarySphereMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.brassCost and ArmillarySphereMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and ArmillarySphereMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ArmillarySphereMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ArmillarySphereMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ArmillarySphereMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ArmillarySphereMaker.buildings==0 then return false,"Potrebna delavnica" end; if not ArmillarySphereMaker.maker then return false,"Potreben armilar" end; return true end
function ArmillarySphereMaker.make(pt,qty) qty=qty or 1; local ok,e=ArmillarySphereMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.brassCost then ArmillarySphereMaker.brassStock=ArmillarySphereMaker.brassStock-d.brassCost*qty end; if d.silverCost then ArmillarySphereMaker.silverStock=ArmillarySphereMaker.silverStock-d.silverCost*qty end; if d.goldCost then ArmillarySphereMaker.goldStock=ArmillarySphereMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ArmillarySphereMaker.jewelStock=ArmillarySphereMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ArmillarySphereMaker.pearlStock=ArmillarySphereMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ArmillarySphereMaker.maker then t=math.max(1,t-math.floor(ArmillarySphereMaker.maker.skill/12)) end; table.insert(ArmillarySphereMaker.activeMaking,{id="armillary_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,accuracy=d.accuracy or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ArmillarySphereMaker.completeMaking(m) local q=1.0+(ArmillarySphereMaker.getQualityBonus()/100); if ArmillarySphereMaker.maker then q=q+(ArmillarySphereMaker.maker.skill/150) end; q=math.min(2.5,q); ArmillarySphereMaker.productStock[m.productType]=(ArmillarySphereMaker.productStock[m.productType] or 0)+m.quantity; ArmillarySphereMaker.totalProducts=ArmillarySphereMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ArmillarySphereMaker.maker then ArmillarySphereMaker.maker.itemsMade=ArmillarySphereMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ArmillarySphereMaker.maker.skill=math.min(100,ArmillarySphereMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Armilarna sfera izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"armillary.completed",{productName=m.productName,accuracy=m.accuracy,prestige=m.prestige,happiness=m.happiness}) end end
function ArmillarySphereMaker.update(dt) if not _G.state then return end; ArmillarySphereMaker.dayTimer=ArmillarySphereMaker.dayTimer+dt; if ArmillarySphereMaker.dayTimer>=30 then ArmillarySphereMaker.dayTimer=0; for i=#ArmillarySphereMaker.activeMaking,1,-1 do local m=ArmillarySphereMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ArmillarySphereMaker.completeMaking(m); table.remove(ArmillarySphereMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ArmillarySphereMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ArmillarySphereMaker.maker then tu=tu+22 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ArmillarySphereMaker.getStats() return {brassStock=ArmillarySphereMaker.brassStock,silverStock=ArmillarySphereMaker.silverStock,goldStock=ArmillarySphereMaker.goldStock,jewelStock=ArmillarySphereMaker.jewelStock,pearlStock=ArmillarySphereMaker.pearlStock,productStock=ArmillarySphereMaker.productStock,numBuildings=#ArmillarySphereMaker.buildings,hasMaker=ArmillarySphereMaker.maker~=nil,makerName=ArmillarySphereMaker.maker and ArmillarySphereMaker.maker.name or "—",makerSkill=ArmillarySphereMaker.maker and ArmillarySphereMaker.maker.skill or 0,activeMaking=#ArmillarySphereMaker.activeMaking,totalProducts=ArmillarySphereMaker.totalProducts} end
return ArmillarySphereMaker
