local ReadingDeskMaker = {}
local PRODUCTS = {
    simple_oak_reading_desk = { name = "Preprost hrastov bralni miza", woodCost = 3, time = 4, cost = 60, beauty = 18, education = 12, happiness = 1, description = "Preprost hrastov bralni miza za knjižnico." },
    carved_lectern_desk = { name = "Izrezljan pultni miza", woodCost = 3, leatherCost = 1, time = 6, cost = 160, beauty = 35, education = 22, happiness = 2, prestige = 2, description = "Izrezljan pultni miza za trgovce." },
    silver_trimmed_desk = { name = "Srebrnoobrobljeni bralni miza", woodCost = 3, silverCost = 1, leatherCost = 1, time = 9, cost = 380, beauty = 52, education = 32, happiness = 2, prestige = 6, description = "Srebrnoobrobljeni bralni miza za plemiče." },
    gold_inlaid_desk = { name = "Zlatovloženi bralni miza", woodCost = 3, goldCost = 1, silverCost = 1, leatherCost = 1, time = 13, cost = 900, beauty = 68, education = 42, happiness = 3, prestige = 14, description = "Zlatovloženi bralni miza za visoke plemiče." },
    jewel_set_desk = { name = "Draguljasta bralni miza", woodCost = 3, goldCost = 1, silverCost = 1, leatherCost = 1, jewelCost = 1, time = 17, cost = 2000, beauty = 82, education = 55, happiness = 5, prestige = 27, description = "Bralni miza z draguljem za visoko plemstvo." },
    royal_grand_reading_desk = { name = "Kraljevski veliki bralni miza", woodCost = 5, goldCost = 2, silverCost = 2, leatherCost = 1, jewelCost = 2, pearlCost = 2, time = 24, cost = 4500, beauty = 95, education = 75, happiness = 12, prestige = 58, description = "Veliki kraljevski bralni miza z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    desk_workshop = { name = "Mizarska delavnica", cost = { gold = 240, wood = 160, stone = 100 }, upkeep = 5, qualityBonus = 5 },
    furniture_loft = { name = "Pohištvena podstrešje", cost = { gold = 880, wood = 320, stone = 220, silver = 6 }, upkeep = 20, qualityBonus = 18 },
    master_desk_atelier = { name = "Mojstrski mizarski atelje", cost = { gold = 2500, wood = 380, stone = 480, silver = 30, gold = 6 }, upkeep = 58, qualityBonus = 30 },
    royal_furniture_palace = { name = "Kraljevska pohištvena palača", cost = { gold = 10500, wood = 600, stone = 760, gold = 65, jewel = 16 }, upkeep = 210, qualityBonus = 55, prestigeBonus = 50 },
}
ReadingDeskMaker.woodStock = 18; ReadingDeskMaker.leatherStock = 10; ReadingDeskMaker.silverStock = 6; ReadingDeskMaker.goldStock = 6; ReadingDeskMaker.jewelStock = 4; ReadingDeskMaker.pearlStock = 4
ReadingDeskMaker.productStock = {}; ReadingDeskMaker.buildings = {}; ReadingDeskMaker.maker = nil; ReadingDeskMaker.activeMaking = {}; ReadingDeskMaker.totalProducts = 0; ReadingDeskMaker.dayTimer = 0
function ReadingDeskMaker.init() ReadingDeskMaker.woodStock=18; ReadingDeskMaker.leatherStock=10; ReadingDeskMaker.silverStock=6; ReadingDeskMaker.goldStock=6; ReadingDeskMaker.jewelStock=4; ReadingDeskMaker.pearlStock=4; ReadingDeskMaker.productStock={}; ReadingDeskMaker.buildings={}; ReadingDeskMaker.maker=nil; ReadingDeskMaker.activeMaking={}; ReadingDeskMaker.totalProducts=0; ReadingDeskMaker.dayTimer=0; print("[ReadingDeskMaker] Royal Reading Desk Maker System initialized (6 products, 4 buildings)") end
function ReadingDeskMaker.hireMaker(n,s) s=s or math.random(55,90); local c=520+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ReadingDeskMaker.maker={name=n or ("Bralnimizar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Bralnimizar najet: %s (spretnost: %d)",ReadingDeskMaker.maker.name,s),"success") end; return true end
function ReadingDeskMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ReadingDeskMaker.build(id) local ok,e=ReadingDeskMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ReadingDeskMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ReadingDeskMaker.getQualityBonus() local b=0; for _,bd in ipairs(ReadingDeskMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ReadingDeskMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and ReadingDeskMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ReadingDeskMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ReadingDeskMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ReadingDeskMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ReadingDeskMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ReadingDeskMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ReadingDeskMaker.buildings==0 then return false,"Potrebna mizarska delavnica" end; if not ReadingDeskMaker.maker then return false,"Potreben bralnimizar" end; return true end
function ReadingDeskMaker.make(pt,qty) qty=qty or 1; local ok,e=ReadingDeskMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then ReadingDeskMaker.woodStock=ReadingDeskMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ReadingDeskMaker.leatherStock=ReadingDeskMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ReadingDeskMaker.silverStock=ReadingDeskMaker.silverStock-d.silverCost*qty end; if d.goldCost then ReadingDeskMaker.goldStock=ReadingDeskMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ReadingDeskMaker.jewelStock=ReadingDeskMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ReadingDeskMaker.pearlStock=ReadingDeskMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ReadingDeskMaker.maker then t=math.max(1,t-math.floor(ReadingDeskMaker.maker.skill/13)) end; table.insert(ReadingDeskMaker.activeMaking,{id="readingdesk_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,beauty=d.beauty or 0,education=d.education or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ReadingDeskMaker.completeMaking(m) local q=1.0+(ReadingDeskMaker.getQualityBonus()/100); if ReadingDeskMaker.maker then q=q+(ReadingDeskMaker.maker.skill/140) end; q=math.min(2.5,q); ReadingDeskMaker.productStock[m.productType]=(ReadingDeskMaker.productStock[m.productType] or 0)+m.quantity; ReadingDeskMaker.totalProducts=ReadingDeskMaker.totalProducts+m.quantity; if m.education>0 and _G.state then _G.state.education=(_G.state.education or 0)+m.education end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ReadingDeskMaker.maker then ReadingDeskMaker.maker.itemsMade=ReadingDeskMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ReadingDeskMaker.maker.skill=math.min(100,ReadingDeskMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Bralni miza izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"readingdesk.completed",{productName=m.productName,beauty=m.beauty,education=m.education,prestige=m.prestige,happiness=m.happiness}) end end
function ReadingDeskMaker.update(dt) if not _G.state then return end; ReadingDeskMaker.dayTimer=ReadingDeskMaker.dayTimer+dt; if ReadingDeskMaker.dayTimer>=30 then ReadingDeskMaker.dayTimer=0; for i=#ReadingDeskMaker.activeMaking,1,-1 do local m=ReadingDeskMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ReadingDeskMaker.completeMaking(m); table.remove(ReadingDeskMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ReadingDeskMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ReadingDeskMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ReadingDeskMaker.getStats() return {woodStock=ReadingDeskMaker.woodStock,leatherStock=ReadingDeskMaker.leatherStock,silverStock=ReadingDeskMaker.silverStock,goldStock=ReadingDeskMaker.goldStock,jewelStock=ReadingDeskMaker.jewelStock,pearlStock=ReadingDeskMaker.pearlStock,productStock=ReadingDeskMaker.productStock,numBuildings=#ReadingDeskMaker.buildings,hasMaker=ReadingDeskMaker.maker~=nil,makerName=ReadingDeskMaker.maker and ReadingDeskMaker.maker.name or "—",makerSkill=ReadingDeskMaker.maker and ReadingDeskMaker.maker.skill or 0,activeMaking=#ReadingDeskMaker.activeMaking,totalProducts=ReadingDeskMaker.totalProducts} end
return ReadingDeskMaker
