local BookEdgeGilderMaker = {}
local PRODUCTS = {
    iron_bookedgegilder = { name = "Železni pozlačevalec robov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni pozlačevalec robov za knjigoveze." },
    bronze_bookedgegilder = { name = "Bronast pozlačevalec robov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast pozlačevalec robov za knjigoveze." },
    silver_bookedgegilder = { name = "Srebrn pozlačevalec robov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn pozlačevalec robov za knjigoveze." },
    gilded_bookedgegilder = { name = "Pozlačen pozlačevalec robov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen pozlačevalec robov za knjigoveze." },
    jewel_set_bookedgegilder = { name = "Draguljast pozlačevalec robov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast pozlačevalec robov za knjigoveze." },
    royal_sovereign_bookedgegilder = { name = "Kraljevski suveren pozlačevalec robov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren pozlačevalec robov z biseri za krono." },
}
local BUILDINGS = {
    bookedgegilder_workshop = { name = "Bookedgegilder delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookedgegilder_house = { name = "Bookedgegilder hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookedgegilder_atelier = { name = "Mojstrski bookedgegilder atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookedgegilder_palace = { name = "Suverena bookedgegilder palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookEdgeGilderMaker.ironStock=12; BookEdgeGilderMaker.bronzeStock=10; BookEdgeGilderMaker.woodStock=14; BookEdgeGilderMaker.leatherStock=10; BookEdgeGilderMaker.silverStock=8; BookEdgeGilderMaker.goldStock=6; BookEdgeGilderMaker.jewelStock=4; BookEdgeGilderMaker.pearlStock=4
BookEdgeGilderMaker.productStock = {}; BookEdgeGilderMaker.buildings = {}; BookEdgeGilderMaker.maker = nil; BookEdgeGilderMaker.activeMaking = {}; BookEdgeGilderMaker.totalProducts = 0; BookEdgeGilderMaker.dayTimer = 0
function BookEdgeGilderMaker.init() BookEdgeGilderMaker.ironStock=12; BookEdgeGilderMaker.bronzeStock=10; BookEdgeGilderMaker.woodStock=14; BookEdgeGilderMaker.leatherStock=10; BookEdgeGilderMaker.silverStock=8; BookEdgeGilderMaker.goldStock=6; BookEdgeGilderMaker.jewelStock=4; BookEdgeGilderMaker.pearlStock=4; BookEdgeGilderMaker.productStock={}; BookEdgeGilderMaker.buildings={}; BookEdgeGilderMaker.maker=nil; BookEdgeGilderMaker.activeMaking={}; BookEdgeGilderMaker.totalProducts=0; BookEdgeGilderMaker.dayTimer=0; print("[BookEdgeGilderMaker] Royal Book Edge Gilder Maker System initialized (6 products, 4 buildings)") end
function BookEdgeGilderMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookEdgeGilderMaker.maker={name=n or ("Pozlačevalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pozlačevalnik najet: %s (spretnost: %d)",BookEdgeGilderMaker.maker.name,s),"success") end; return true end
function BookEdgeGilderMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookEdgeGilderMaker.build(id) local ok,e=BookEdgeGilderMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookEdgeGilderMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookEdgeGilderMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookEdgeGilderMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookEdgeGilderMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookEdgeGilderMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookEdgeGilderMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookEdgeGilderMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookEdgeGilderMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookEdgeGilderMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookEdgeGilderMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookEdgeGilderMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookEdgeGilderMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookEdgeGilderMaker.buildings==0 then return false,"Potrebna pozlačevalna delavnica" end; if not BookEdgeGilderMaker.maker then return false,"Potreben pozlačevalnik" end; return true end
function BookEdgeGilderMaker.make(pt,qty) qty=qty or 1; local ok,e=BookEdgeGilderMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookEdgeGilderMaker.ironStock=BookEdgeGilderMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookEdgeGilderMaker.bronzeStock=BookEdgeGilderMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookEdgeGilderMaker.woodStock=BookEdgeGilderMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookEdgeGilderMaker.leatherStock=BookEdgeGilderMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookEdgeGilderMaker.silverStock=BookEdgeGilderMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookEdgeGilderMaker.goldStock=BookEdgeGilderMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookEdgeGilderMaker.jewelStock=BookEdgeGilderMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookEdgeGilderMaker.pearlStock=BookEdgeGilderMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookEdgeGilderMaker.maker then t=math.max(1,t-math.floor(BookEdgeGilderMaker.maker.skill/13)) end; table.insert(BookEdgeGilderMaker.activeMaking,{id="bookedgegilder_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookEdgeGilderMaker.completeMaking(m) local q=1.0+(BookEdgeGilderMaker.getQualityBonus()/100); if BookEdgeGilderMaker.maker then q=q+(BookEdgeGilderMaker.maker.skill/140) end; q=math.min(2.5,q); BookEdgeGilderMaker.productStock[m.productType]=(BookEdgeGilderMaker.productStock[m.productType] or 0)+m.quantity; BookEdgeGilderMaker.totalProducts=BookEdgeGilderMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookEdgeGilderMaker.maker then BookEdgeGilderMaker.maker.itemsMade=BookEdgeGilderMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookEdgeGilderMaker.maker.skill=math.min(100,BookEdgeGilderMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pozlačevalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookedgegilder.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookEdgeGilderMaker.update(dt) if not _G.state then return end; BookEdgeGilderMaker.dayTimer=BookEdgeGilderMaker.dayTimer+dt; if BookEdgeGilderMaker.dayTimer>=30 then BookEdgeGilderMaker.dayTimer=0; for i=#BookEdgeGilderMaker.activeMaking,1,-1 do local m=BookEdgeGilderMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookEdgeGilderMaker.completeMaking(m); table.remove(BookEdgeGilderMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookEdgeGilderMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookEdgeGilderMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookEdgeGilderMaker.getStats() return {ironStock=BookEdgeGilderMaker.ironStock,bronzeStock=BookEdgeGilderMaker.bronzeStock,woodStock=BookEdgeGilderMaker.woodStock,leatherStock=BookEdgeGilderMaker.leatherStock,silverStock=BookEdgeGilderMaker.silverStock,goldStock=BookEdgeGilderMaker.goldStock,jewelStock=BookEdgeGilderMaker.jewelStock,pearlStock=BookEdgeGilderMaker.pearlStock,productStock=BookEdgeGilderMaker.productStock,numBuildings=#BookEdgeGilderMaker.buildings,hasMaker=BookEdgeGilderMaker.maker~=nil,makerName=BookEdgeGilderMaker.maker and BookEdgeGilderMaker.maker.name or "—",makerSkill=BookEdgeGilderMaker.maker and BookEdgeGilderMaker.maker.skill or 0,activeMaking=#BookEdgeGilderMaker.activeMaking,totalProducts=BookEdgeGilderMaker.totalProducts} end
return BookEdgeGilderMaker
