local BookClaspMaker = {}
local PRODUCTS = {
    iron_bookclasp = { name = "Železni sponka za knjige", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni sponka za knjige za knjigoveze." },
    bronze_bookclasp = { name = "Bronast sponka za knjige", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast sponka za knjige za knjigoveze." },
    silver_bookclasp = { name = "Srebrn sponka za knjige", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn sponka za knjige za knjigoveze." },
    gilded_bookclasp = { name = "Pozlačen sponka za knjige", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen sponka za knjige za knjigoveze." },
    jewel_set_bookclasp = { name = "Draguljast sponka za knjige", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast sponka za knjige za knjigoveze." },
    royal_sovereign_bookclasp = { name = "Kraljevski suveren sponka za knjige", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren sponka za knjige z biseri za krono." },
}
local BUILDINGS = {
    bookclasp_workshop = { name = "Bookclasp delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookclasp_house = { name = "Bookclasp hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookclasp_atelier = { name = "Mojstrski bookclasp atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookclasp_palace = { name = "Suverena bookclasp palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookClaspMaker.ironStock=18; BookClaspMaker.bronzeStock=14; BookClaspMaker.woodStock=10; BookClaspMaker.leatherStock=8; BookClaspMaker.silverStock=8; BookClaspMaker.goldStock=6; BookClaspMaker.jewelStock=4; BookClaspMaker.pearlStock=4
BookClaspMaker.productStock = {}; BookClaspMaker.buildings = {}; BookClaspMaker.maker = nil; BookClaspMaker.activeMaking = {}; BookClaspMaker.totalProducts = 0; BookClaspMaker.dayTimer = 0
function BookClaspMaker.init() BookClaspMaker.ironStock=18; BookClaspMaker.bronzeStock=14; BookClaspMaker.woodStock=10; BookClaspMaker.leatherStock=8; BookClaspMaker.silverStock=8; BookClaspMaker.goldStock=6; BookClaspMaker.jewelStock=4; BookClaspMaker.pearlStock=4; BookClaspMaker.productStock={}; BookClaspMaker.buildings={}; BookClaspMaker.maker=nil; BookClaspMaker.activeMaking={}; BookClaspMaker.totalProducts=0; BookClaspMaker.dayTimer=0; print("[BookClaspMaker] Royal Book Clasp Maker System initialized (6 products, 4 buildings)") end
function BookClaspMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookClaspMaker.maker={name=n or ("Sponkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sponkar najet: %s (spretnost: %d)",BookClaspMaker.maker.name,s),"success") end; return true end
function BookClaspMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookClaspMaker.build(id) local ok,e=BookClaspMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookClaspMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookClaspMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookClaspMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookClaspMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookClaspMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookClaspMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookClaspMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookClaspMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookClaspMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookClaspMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookClaspMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookClaspMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookClaspMaker.buildings==0 then return false,"Potrebna sponkaška delavnica" end; if not BookClaspMaker.maker then return false,"Potreben sponkar" end; return true end
function BookClaspMaker.make(pt,qty) qty=qty or 1; local ok,e=BookClaspMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookClaspMaker.ironStock=BookClaspMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookClaspMaker.bronzeStock=BookClaspMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookClaspMaker.woodStock=BookClaspMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookClaspMaker.leatherStock=BookClaspMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookClaspMaker.silverStock=BookClaspMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookClaspMaker.goldStock=BookClaspMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookClaspMaker.jewelStock=BookClaspMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookClaspMaker.pearlStock=BookClaspMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookClaspMaker.maker then t=math.max(1,t-math.floor(BookClaspMaker.maker.skill/13)) end; table.insert(BookClaspMaker.activeMaking,{id="bookclasp_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookClaspMaker.completeMaking(m) local q=1.0+(BookClaspMaker.getQualityBonus()/100); if BookClaspMaker.maker then q=q+(BookClaspMaker.maker.skill/140) end; q=math.min(2.5,q); BookClaspMaker.productStock[m.productType]=(BookClaspMaker.productStock[m.productType] or 0)+m.quantity; BookClaspMaker.totalProducts=BookClaspMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookClaspMaker.maker then BookClaspMaker.maker.itemsMade=BookClaspMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookClaspMaker.maker.skill=math.min(100,BookClaspMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sponka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookclasp.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookClaspMaker.update(dt) if not _G.state then return end; BookClaspMaker.dayTimer=BookClaspMaker.dayTimer+dt; if BookClaspMaker.dayTimer>=30 then BookClaspMaker.dayTimer=0; for i=#BookClaspMaker.activeMaking,1,-1 do local m=BookClaspMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookClaspMaker.completeMaking(m); table.remove(BookClaspMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookClaspMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookClaspMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookClaspMaker.getStats() return {ironStock=BookClaspMaker.ironStock,bronzeStock=BookClaspMaker.bronzeStock,woodStock=BookClaspMaker.woodStock,leatherStock=BookClaspMaker.leatherStock,silverStock=BookClaspMaker.silverStock,goldStock=BookClaspMaker.goldStock,jewelStock=BookClaspMaker.jewelStock,pearlStock=BookClaspMaker.pearlStock,productStock=BookClaspMaker.productStock,numBuildings=#BookClaspMaker.buildings,hasMaker=BookClaspMaker.maker~=nil,makerName=BookClaspMaker.maker and BookClaspMaker.maker.name or "—",makerSkill=BookClaspMaker.maker and BookClaspMaker.maker.skill or 0,activeMaking=#BookClaspMaker.activeMaking,totalProducts=BookClaspMaker.totalProducts} end
return BookClaspMaker
