local MapMaker = {}
local PRODUCTS = {
    regional_map = { name = "Regionalni zemljevid", parchmentCost = 1, inkCost = 1, time = 3, cost = 35, accuracy = 50, prestige = 2, description = "Regionalni zemljevid za navigacijo." },
    trade_route_map = { name = "Trgovska pot zemljevid", parchmentCost = 1, inkCost = 1, silverCost = 1, time = 5, cost = 90, accuracy = 65, prestige = 5, happiness = 1, description = "Zemljevid trgovskih poti za trgovce." },
    coastal_chart = { name = "Obalna karta", parchmentCost = 2, inkCost = 1, silverCost = 1, time = 7, cost = 200, accuracy = 78, prestige = 9, happiness = 2, description = "Obalna karta za pomorščake." },
    silver_filigree_map = { name = "Srebrno filigranski zemljevid", parchmentCost = 2, inkCost = 1, silverCost = 1, goldCost = 1, time = 10, cost = 480, accuracy = 88, prestige = 16, happiness = 3, description = "Srebrno filigranski zemljevid za plemiče." },
    silver_frame_map = { name = "Srebrno okvirni zemljevid", parchmentCost = 3, inkCost = 1, silverCost = 1, goldCost = 1, time = 13, cost = 950, accuracy = 94, prestige = 24, happiness = 5, description = "Zemljevid v srebrnem okvirju za visoke plemiče." },
    royal_grand_atlas = { name = "Kraljevski veliki atlas", parchmentCost = 5, inkCost = 2, goldCost = 2, silverCost = 1, jewelCost = 1, time = 18, cost = 2200, accuracy = 100, prestige = 55, happiness = 11, description = "Veliki kraljevski atlas z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Kartografska postaja", cost = { gold = 300, wood = 130, stone = 200 }, upkeep = 7, qualityBonus = 5 },
    cartography_house = { name = "Kartografska hiša", cost = { gold = 1000, wood = 280, stone = 450, ink = 8 }, upkeep = 25, qualityBonus = 18 },
    surveying_tower = { name = "Geodetski stolp", cost = { gold = 2500, wood = 400, stone = 800, silver = 40, brass = 8 }, upkeep = 62, qualityBonus = 30 },
    royal_cartography_atelier = { name = "Kraljevski atelje kartografije", cost = { gold = 10000, wood = 600, stone = 1100, gold = 80, jewel = 25 }, upkeep = 200, qualityBonus = 55, prestigeBonus = 45 },
}
MapMaker.parchmentStock = 18; MapMaker.inkStock = 14; MapMaker.silverStock = 8; MapMaker.goldStock = 6; MapMaker.jewelStock = 6
MapMaker.productStock = {}; MapMaker.buildings = {}; MapMaker.maker = nil; MapMaker.activeMaking = {}; MapMaker.totalProducts = 0; MapMaker.dayTimer = 0
function MapMaker.init() MapMaker.parchmentStock=18; MapMaker.inkStock=14; MapMaker.silverStock=8; MapMaker.goldStock=6; MapMaker.jewelStock=6; MapMaker.productStock={}; MapMaker.buildings={}; MapMaker.maker=nil; MapMaker.activeMaking={}; MapMaker.totalProducts=0; MapMaker.dayTimer=0; print("[MapMaker] Royal Map Maker System initialized (6 products, 4 buildings)") end
function MapMaker.hireMaker(n,s) s=s or math.random(55,90); local c=560+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MapMaker.maker={name=n or ("Kartograf "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kartograf najet: %s (spretnost: %d)",MapMaker.maker.name,s),"success") end; return true end
function MapMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MapMaker.build(id) local ok,e=MapMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MapMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MapMaker.getQualityBonus() local b=0; for _,bd in ipairs(MapMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MapMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.parchmentCost and MapMaker.parchmentStock<(d.parchmentCost or 0) then return false,"Premalo pergamenta" end; if d.inkCost and MapMaker.inkStock<(d.inkCost or 0) then return false,"Premalo črnila" end; if d.silverCost and MapMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MapMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MapMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #MapMaker.buildings==0 then return false,"Potrebna delavnica" end; if not MapMaker.maker then return false,"Potreben kartograf" end; return true end
function MapMaker.make(pt,qty) qty=qty or 1; local ok,e=MapMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.parchmentCost then MapMaker.parchmentStock=MapMaker.parchmentStock-d.parchmentCost*qty end; if d.inkCost then MapMaker.inkStock=MapMaker.inkStock-d.inkCost*qty end; if d.silverCost then MapMaker.silverStock=MapMaker.silverStock-d.silverCost*qty end; if d.goldCost then MapMaker.goldStock=MapMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MapMaker.jewelStock=MapMaker.jewelStock-d.jewelCost*qty end; local t=d.time; if MapMaker.maker then t=math.max(1,t-math.floor(MapMaker.maker.skill/12)) end; table.insert(MapMaker.activeMaking,{id="map_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,accuracy=d.accuracy or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MapMaker.completeMaking(m) local q=1.0+(MapMaker.getQualityBonus()/100); if MapMaker.maker then q=q+(MapMaker.maker.skill/150) end; q=math.min(2.5,q); MapMaker.productStock[m.productType]=(MapMaker.productStock[m.productType] or 0)+m.quantity; MapMaker.totalProducts=MapMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MapMaker.maker then MapMaker.maker.itemsMade=MapMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MapMaker.maker.skill=math.min(100,MapMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zemljevid izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"map.completed",{productName=m.productName,accuracy=m.accuracy,prestige=m.prestige,happiness=m.happiness}) end end
function MapMaker.update(dt) if not _G.state then return end; MapMaker.dayTimer=MapMaker.dayTimer+dt; if MapMaker.dayTimer>=30 then MapMaker.dayTimer=0; for i=#MapMaker.activeMaking,1,-1 do local m=MapMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MapMaker.completeMaking(m); table.remove(MapMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MapMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MapMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MapMaker.getStats() return {parchmentStock=MapMaker.parchmentStock,inkStock=MapMaker.inkStock,silverStock=MapMaker.silverStock,goldStock=MapMaker.goldStock,jewelStock=MapMaker.jewelStock,productStock=MapMaker.productStock,numBuildings=#MapMaker.buildings,hasMaker=MapMaker.maker~=nil,makerName=MapMaker.maker and MapMaker.maker.name or "—",makerSkill=MapMaker.maker and MapMaker.maker.skill or 0,activeMaking=#MapMaker.activeMaking,totalProducts=MapMaker.totalProducts} end
return MapMaker
