local CompassNeedleMaker = {}
local PRODUCTS = {
    iron_compassneedle = { name = "Železni kompasna igla", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni kompasna igla za kompase." },
    bronze_compassneedle = { name = "Bronast kompasna igla", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast kompasna igla za kompase." },
    silver_compassneedle = { name = "Srebrn kompasna igla", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn kompasna igla za kompase." },
    gilded_compassneedle = { name = "Pozlačen kompasna igla", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen kompasna igla za kompase." },
    jewel_set_compassneedle = { name = "Draguljast kompasna igla", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast kompasna igla za kompase." },
    royal_sovereign_compassneedle = { name = "Kraljevski suveren kompasna igla", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren kompasna igla z biseri za krono." },
}
local BUILDINGS = {
    compassneedle_workshop = { name = "Compassneedle delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    compassneedle_house = { name = "Compassneedle hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_compassneedle_atelier = { name = "Mojstrski compassneedle atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_compassneedle_palace = { name = "Suverena compassneedle palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
CompassNeedleMaker.ironStock = 18; CompassNeedleMaker.bronzeStock = 14; CompassNeedleMaker.woodStock = 10; CompassNeedleMaker.leatherStock = 8; CompassNeedleMaker.silverStock = 8; CompassNeedleMaker.goldStock = 6; CompassNeedleMaker.jewelStock = 4; CompassNeedleMaker.pearlStock = 4
CompassNeedleMaker.productStock = {}; CompassNeedleMaker.buildings = {}; CompassNeedleMaker.maker = nil; CompassNeedleMaker.activeMaking = {}; CompassNeedleMaker.totalProducts = 0; CompassNeedleMaker.dayTimer = 0
function CompassNeedleMaker.init() CompassNeedleMaker.ironStock=18; CompassNeedleMaker.bronzeStock=14; CompassNeedleMaker.woodStock=10; CompassNeedleMaker.leatherStock=8; CompassNeedleMaker.silverStock=8; CompassNeedleMaker.goldStock=6; CompassNeedleMaker.jewelStock=4; CompassNeedleMaker.pearlStock=4; CompassNeedleMaker.productStock={}; CompassNeedleMaker.buildings={}; CompassNeedleMaker.maker=nil; CompassNeedleMaker.activeMaking={}; CompassNeedleMaker.totalProducts=0; CompassNeedleMaker.dayTimer=0; print("[CompassNeedleMaker] Royal Compass Needle Maker System initialized (6 products, 4 buildings)") end
function CompassNeedleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CompassNeedleMaker.maker={name=n or ("Iglec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Iglec najet: %s (spretnost: %d)",CompassNeedleMaker.maker.name,s),"success") end; return true end
function CompassNeedleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CompassNeedleMaker.build(id) local ok,e=CompassNeedleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CompassNeedleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CompassNeedleMaker.getQualityBonus() local b=0; for _,bd in ipairs(CompassNeedleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CompassNeedleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CompassNeedleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CompassNeedleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CompassNeedleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CompassNeedleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CompassNeedleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CompassNeedleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CompassNeedleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CompassNeedleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CompassNeedleMaker.buildings==0 then return false,"Potrebna iglena delavnica" end; if not CompassNeedleMaker.maker then return false,"Potreben iglec" end; return true end
function CompassNeedleMaker.make(pt,qty) qty=qty or 1; local ok,e=CompassNeedleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CompassNeedleMaker.ironStock=CompassNeedleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CompassNeedleMaker.bronzeStock=CompassNeedleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CompassNeedleMaker.woodStock=CompassNeedleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CompassNeedleMaker.leatherStock=CompassNeedleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CompassNeedleMaker.silverStock=CompassNeedleMaker.silverStock-d.silverCost*qty end; if d.goldCost then CompassNeedleMaker.goldStock=CompassNeedleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CompassNeedleMaker.jewelStock=CompassNeedleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CompassNeedleMaker.pearlStock=CompassNeedleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CompassNeedleMaker.maker then t=math.max(1,t-math.floor(CompassNeedleMaker.maker.skill/13)) end; table.insert(CompassNeedleMaker.activeMaking,{id="compassneedle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CompassNeedleMaker.completeMaking(m) local q=1.0+(CompassNeedleMaker.getQualityBonus()/100); if CompassNeedleMaker.maker then q=q+(CompassNeedleMaker.maker.skill/140) end; q=math.min(2.5,q); CompassNeedleMaker.productStock[m.productType]=(CompassNeedleMaker.productStock[m.productType] or 0)+m.quantity; CompassNeedleMaker.totalProducts=CompassNeedleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CompassNeedleMaker.maker then CompassNeedleMaker.maker.itemsMade=CompassNeedleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CompassNeedleMaker.maker.skill=math.min(100,CompassNeedleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("IglA izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"compassneedle.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CompassNeedleMaker.update(dt) if not _G.state then return end; CompassNeedleMaker.dayTimer=CompassNeedleMaker.dayTimer+dt; if CompassNeedleMaker.dayTimer>=30 then CompassNeedleMaker.dayTimer=0; for i=#CompassNeedleMaker.activeMaking,1,-1 do local m=CompassNeedleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CompassNeedleMaker.completeMaking(m); table.remove(CompassNeedleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CompassNeedleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CompassNeedleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CompassNeedleMaker.getStats() return {ironStock=CompassNeedleMaker.ironStock,bronzeStock=CompassNeedleMaker.bronzeStock,woodStock=CompassNeedleMaker.woodStock,leatherStock=CompassNeedleMaker.leatherStock,silverStock=CompassNeedleMaker.silverStock,goldStock=CompassNeedleMaker.goldStock,jewelStock=CompassNeedleMaker.jewelStock,pearlStock=CompassNeedleMaker.pearlStock,productStock=CompassNeedleMaker.productStock,numBuildings=#CompassNeedleMaker.buildings,hasMaker=CompassNeedleMaker.maker~=nil,makerName=CompassNeedleMaker.maker and CompassNeedleMaker.maker.name or "—",makerSkill=CompassNeedleMaker.maker and CompassNeedleMaker.maker.skill or 0,activeMaking=#CompassNeedleMaker.activeMaking,totalProducts=CompassNeedleMaker.totalProducts} end
return CompassNeedleMaker
