local SextantMaker = {}
local PRODUCTS = {
    brass_sextant = { name = "Medeninast sekstant", brassCost = 2, glassCost = 1, time = 5, cost = 90, accuracy = 60, prestige = 4, description = "Medeninast sekstant za navigacijo." },
    silver_sextant = { name = "Srebrn sekstant", silverCost = 2, glassCost = 1, brassCost = 1, time = 7, cost = 220, accuracy = 75, prestige = 8, happiness = 1, description = "Srebrn sekstant za pomorščake." },
    engraved_sextant = { name = "Vgraviran sekstant", silverCost = 2, glassCost = 1, brassCost = 1, time = 10, cost = 500, accuracy = 85, prestige = 14, happiness = 2, description = "Vgraviran sekstant za kapitane." },
    silver_arc_sextant = { name = "Srebrno ločni sekstant", silverCost = 2, goldCost = 1, glassCost = 1, brassCost = 1, time = 13, cost = 1000, accuracy = 92, prestige = 22, happiness = 4, description = "Sekstant s srebrnim lokom za plemiče." },
    gold_arc_sextant = { name = "Zlatolocni sekstant", goldCost = 2, silverCost = 1, glassCost = 1, jewelCost = 1, time = 16, cost = 2000, accuracy = 96, prestige = 32, happiness = 6, description = "Sekstant z zlatim lokom za visoke plemiče." },
    royal_grand_sextant = { name = "Kraljevski veliki sekstant", goldCost = 3, silverCost = 2, jewelCost = 2, pearlCost = 1, glassCost = 1, time = 22, cost = 4000, accuracy = 100, prestige = 62, happiness = 13, description = "Veliki kraljevski sekstant z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Sekstantska delavnica", cost = { gold = 350, wood = 130, stone = 250 }, upkeep = 9, qualityBonus = 5 },
    instrument_forge = { name = "Inštrumentska kovačija", cost = { gold = 1200, wood = 280, stone = 500, brass = 8 }, upkeep = 30, qualityBonus = 18 },
    calibration_room = { name = "Kalibrirnica", cost = { gold = 2800, wood = 400, stone = 800, silver = 40, glass = 8 }, upkeep = 70, qualityBonus = 30 },
    royal_sextant_atelier = { name = "Kraljevski atelje sekstantov", cost = { gold = 12000, wood = 600, stone = 1200, gold = 80, jewel = 25 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
SextantMaker.brassStock = 14; SextantMaker.glassStock = 10; SextantMaker.silverStock = 8; SextantMaker.goldStock = 6; SextantMaker.jewelStock = 6; SextantMaker.pearlStock = 4
SextantMaker.productStock = {}; SextantMaker.buildings = {}; SextantMaker.maker = nil; SextantMaker.activeMaking = {}; SextantMaker.totalProducts = 0; SextantMaker.dayTimer = 0
function SextantMaker.init() SextantMaker.brassStock=14; SextantMaker.glassStock=10; SextantMaker.silverStock=8; SextantMaker.goldStock=6; SextantMaker.jewelStock=6; SextantMaker.pearlStock=4; SextantMaker.productStock={}; SextantMaker.buildings={}; SextantMaker.maker=nil; SextantMaker.activeMaking={}; SextantMaker.totalProducts=0; SextantMaker.dayTimer=0; print("[SextantMaker] Royal Sextant Maker System initialized (6 products, 4 buildings)") end
function SextantMaker.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SextantMaker.maker={name=n or ("Sekstantar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sekstantar najet: %s (spretnost: %d)",SextantMaker.maker.name,s),"success") end; return true end
function SextantMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SextantMaker.build(id) local ok,e=SextantMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SextantMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SextantMaker.getQualityBonus() local b=0; for _,bd in ipairs(SextantMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SextantMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.brassCost and SextantMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.glassCost and SextantMaker.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.silverCost and SextantMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SextantMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SextantMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SextantMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SextantMaker.buildings==0 then return false,"Potrebna delavnica" end; if not SextantMaker.maker then return false,"Potreben sekstantar" end; return true end
function SextantMaker.make(pt,qty) qty=qty or 1; local ok,e=SextantMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.brassCost then SextantMaker.brassStock=SextantMaker.brassStock-d.brassCost*qty end; if d.glassCost then SextantMaker.glassStock=SextantMaker.glassStock-d.glassCost*qty end; if d.silverCost then SextantMaker.silverStock=SextantMaker.silverStock-d.silverCost*qty end; if d.goldCost then SextantMaker.goldStock=SextantMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SextantMaker.jewelStock=SextantMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SextantMaker.pearlStock=SextantMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SextantMaker.maker then t=math.max(1,t-math.floor(SextantMaker.maker.skill/12)) end; table.insert(SextantMaker.activeMaking,{id="sextant_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,accuracy=d.accuracy or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SextantMaker.completeMaking(m) local q=1.0+(SextantMaker.getQualityBonus()/100); if SextantMaker.maker then q=q+(SextantMaker.maker.skill/150) end; q=math.min(2.5,q); SextantMaker.productStock[m.productType]=(SextantMaker.productStock[m.productType] or 0)+m.quantity; SextantMaker.totalProducts=SextantMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SextantMaker.maker then SextantMaker.maker.itemsMade=SextantMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SextantMaker.maker.skill=math.min(100,SextantMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sekstant izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sextant.completed",{productName=m.productName,accuracy=m.accuracy,prestige=m.prestige,happiness=m.happiness}) end end
function SextantMaker.update(dt) if not _G.state then return end; SextantMaker.dayTimer=SextantMaker.dayTimer+dt; if SextantMaker.dayTimer>=30 then SextantMaker.dayTimer=0; for i=#SextantMaker.activeMaking,1,-1 do local m=SextantMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SextantMaker.completeMaking(m); table.remove(SextantMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SextantMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SextantMaker.maker then tu=tu+20 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SextantMaker.getStats() return {brassStock=SextantMaker.brassStock,glassStock=SextantMaker.glassStock,silverStock=SextantMaker.silverStock,goldStock=SextantMaker.goldStock,jewelStock=SextantMaker.jewelStock,pearlStock=SextantMaker.pearlStock,productStock=SextantMaker.productStock,numBuildings=#SextantMaker.buildings,hasMaker=SextantMaker.maker~=nil,makerName=SextantMaker.maker and SextantMaker.maker.name or "—",makerSkill=SextantMaker.maker and SextantMaker.maker.skill or 0,activeMaking=#SextantMaker.activeMaking,totalProducts=SextantMaker.totalProducts} end
return SextantMaker
