local AleBrewer = {}
local PRODUCTS = {
    small_ale = { name = "Majhno pivo", barleyCost = 2, hopsCost = 1, waterCost = 1, time = 2, cost = 12, alcoholContent = 3, happiness = 1, description = "Majhno pivo za kmete." },
    brown_ale = { name = "Rjavo pivo", barleyCost = 3, hopsCost = 2, waterCost = 1, time = 4, cost = 35, alcoholContent = 5, happiness = 2, prestige = 1, description = "Rjavo pivo z močnim okusom." },
    strong_ale = { name = "Močno pivo", barleyCost = 4, hopsCost = 2, waterCost = 2, time = 6, cost = 85, alcoholContent = 8, happiness = 3, prestige = 2, description = "Močno pivo za dvorne slovesnosti." },
    spiced_ale = { name = "Začinjeno pivo", barleyCost = 4, hopsCost = 2, spiceCost = 1, waterCost = 2, time = 8, cost = 180, alcoholContent = 10, happiness = 5, prestige = 5, description = "Začinjeno pivo z redkimi začimbami." },
    silver_brew_ale = { name = "Srebrno pivovarsko pivo", barleyCost = 5, hopsCost = 3, silverCost = 1, spiceCost = 1, waterCost = 3, time = 11, cost = 380, alcoholContent = 12, happiness = 8, prestige = 10, description = "Srebrno pivovarsko pivo za plemiče." },
    royal_grand_ale = { name = "Kraljevski veliki pivo", barleyCost = 8, hopsCost = 4, goldCost = 1, silverCost = 1, jewelCost = 1, spiceCost = 2, waterCost = 4, time = 16, cost = 950, alcoholContent = 16, happiness = 15, prestige = 30, description = "Veliko kraljevsko pivo z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Pivovarska delavnica", cost = { gold = 280, wood = 150 }, upkeep = 7, qualityBonus = 5 },
    brewery = { name = "Pivovarna", cost = { gold = 900, wood = 280, stone = 350, barley = 10 }, upkeep = 22, qualityBonus = 18 },
    aging_cellar = { name = "Starilni sklep", cost = { gold = 2200, wood = 400, stone = 700, silver = 30, hops = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_ale_atelier = { name = "Kraljevski atelje piva", cost = { gold = 9000, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
AleBrewer.barleyStock = 22; AleBrewer.hopsStock = 14; AleBrewer.waterStock = 18; AleBrewer.spiceStock = 10; AleBrewer.silverStock = 8; AleBrewer.goldStock = 6; AleBrewer.jewelStock = 6
AleBrewer.productStock = {}; AleBrewer.buildings = {}; AleBrewer.maker = nil; AleBrewer.activeMaking = {}; AleBrewer.totalProducts = 0; AleBrewer.dayTimer = 0
function AleBrewer.init() AleBrewer.barleyStock=22; AleBrewer.hopsStock=14; AleBrewer.waterStock=18; AleBrewer.spiceStock=10; AleBrewer.silverStock=8; AleBrewer.goldStock=6; AleBrewer.jewelStock=6; AleBrewer.productStock={}; AleBrewer.buildings={}; AleBrewer.maker=nil; AleBrewer.activeMaking={}; AleBrewer.totalProducts=0; AleBrewer.dayTimer=0; print("[AleBrewer] Royal Ale Brewer System initialized (6 products, 4 buildings)") end
function AleBrewer.hireMaker(n,s) s=s or math.random(50,90); local c=500+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; AleBrewer.maker={name=n or ("Pivar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pivar najet: %s (spretnost: %d)",AleBrewer.maker.name,s),"success") end; return true end
function AleBrewer.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function AleBrewer.build(id) local ok,e=AleBrewer.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(AleBrewer.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function AleBrewer.getQualityBonus() local b=0; for _,bd in ipairs(AleBrewer.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function AleBrewer.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.barleyCost and AleBrewer.barleyStock<(d.barleyCost or 0) then return false,"Premalo ječmena" end; if d.hopsCost and AleBrewer.hopsStock<(d.hopsCost or 0) then return false,"Premalo hmelja" end; if d.waterCost and AleBrewer.waterStock<(d.waterCost or 0) then return false,"Premalo vode" end; if d.spiceCost and AleBrewer.spiceStock<(d.spiceCost or 0) then return false,"Premalo začimb" end; if d.silverCost and AleBrewer.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and AleBrewer.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and AleBrewer.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #AleBrewer.buildings==0 then return false,"Potrebna delavnica" end; if not AleBrewer.maker then return false,"Potreben pivar" end; return true end
function AleBrewer.make(pt,qty) qty=qty or 5; local ok,e=AleBrewer.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.barleyCost then AleBrewer.barleyStock=AleBrewer.barleyStock-d.barleyCost*qty end; if d.hopsCost then AleBrewer.hopsStock=AleBrewer.hopsStock-d.hopsCost*qty end; if d.waterCost then AleBrewer.waterStock=AleBrewer.waterStock-d.waterCost*qty end; if d.spiceCost then AleBrewer.spiceStock=AleBrewer.spiceStock-d.spiceCost*qty end; if d.silverCost then AleBrewer.silverStock=AleBrewer.silverStock-d.silverCost*qty end; if d.goldCost then AleBrewer.goldStock=AleBrewer.goldStock-d.goldCost*qty end; if d.jewelCost then AleBrewer.jewelStock=AleBrewer.jewelStock-d.jewelCost*qty end; local t=d.time; if AleBrewer.maker then t=math.max(1,t-math.floor(AleBrewer.maker.skill/12)) end; table.insert(AleBrewer.activeMaking,{id="ale_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,alcoholContent=d.alcoholContent or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function AleBrewer.completeMaking(m) local q=1.0+(AleBrewer.getQualityBonus()/100); if AleBrewer.maker then q=q+(AleBrewer.maker.skill/180) end; q=math.min(2.0,q); AleBrewer.productStock[m.productType]=(AleBrewer.productStock[m.productType] or 0)+m.quantity; AleBrewer.totalProducts=AleBrewer.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if AleBrewer.maker then AleBrewer.maker.itemsMade=AleBrewer.maker.itemsMade+m.quantity; if math.random()<0.20 then AleBrewer.maker.skill=math.min(100,AleBrewer.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pivo izdelano: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"ale.completed",{productName=m.productName,alcoholContent=m.alcoholContent,happiness=m.happiness}) end end
function AleBrewer.update(dt) if not _G.state then return end; AleBrewer.dayTimer=AleBrewer.dayTimer+dt; if AleBrewer.dayTimer>=30 then AleBrewer.dayTimer=0; for i=#AleBrewer.activeMaking,1,-1 do local m=AleBrewer.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then AleBrewer.completeMaking(m); table.remove(AleBrewer.activeMaking,i) end end; local tu=0; for _,bd in ipairs(AleBrewer.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if AleBrewer.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function AleBrewer.getStats() return {barleyStock=AleBrewer.barleyStock,hopsStock=AleBrewer.hopsStock,waterStock=AleBrewer.waterStock,spiceStock=AleBrewer.spiceStock,silverStock=AleBrewer.silverStock,goldStock=AleBrewer.goldStock,jewelStock=AleBrewer.jewelStock,productStock=AleBrewer.productStock,numBuildings=#AleBrewer.buildings,hasMaker=AleBrewer.maker~=nil,makerName=AleBrewer.maker and AleBrewer.maker.name or "—",makerSkill=AleBrewer.maker and AleBrewer.maker.skill or 0,activeMaking=#AleBrewer.activeMaking,totalProducts=AleBrewer.totalProducts} end
return AleBrewer
