local SoapDishMaker = {}
local PRODUCTS = {
    iron_soapdish = { name = "Železni posoda za milo", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni posoda za milo za kopališča." },
    bronze_soapdish = { name = "Bronast posoda za milo", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast posoda za milo za kopališča." },
    silver_soapdish = { name = "Srebrn posoda za milo", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn posoda za milo za kopališča." },
    gilded_soapdish = { name = "Pozlačen posoda za milo", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen posoda za milo za kopališča." },
    jewel_set_soapdish = { name = "Draguljast posoda za milo", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast posoda za milo za kopališča." },
    royal_sovereign_soapdish = { name = "Kraljevski suveren posoda za milo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren posoda za milo z biseri za krono." },
}
local BUILDINGS = {
    soapdish_workshop = { name = "Soapdish delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    soapdish_house = { name = "Soapdish hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_soapdish_atelier = { name = "Mojstrski soapdish atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_soapdish_palace = { name = "Suverena soapdish palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SoapDishMaker.ironStock = 10; SoapDishMaker.bronzeStock = 8; SoapDishMaker.woodStock = 16; SoapDishMaker.leatherStock = 12; SoapDishMaker.silverStock = 8; SoapDishMaker.goldStock = 6; SoapDishMaker.jewelStock = 4; SoapDishMaker.pearlStock = 4
SoapDishMaker.productStock = {}; SoapDishMaker.buildings = {}; SoapDishMaker.maker = nil; SoapDishMaker.activeMaking = {}; SoapDishMaker.totalProducts = 0; SoapDishMaker.dayTimer = 0
function SoapDishMaker.init() SoapDishMaker.ironStock=10; SoapDishMaker.bronzeStock=8; SoapDishMaker.woodStock=16; SoapDishMaker.leatherStock=12; SoapDishMaker.silverStock=8; SoapDishMaker.goldStock=6; SoapDishMaker.jewelStock=4; SoapDishMaker.pearlStock=4; SoapDishMaker.productStock={}; SoapDishMaker.buildings={}; SoapDishMaker.maker=nil; SoapDishMaker.activeMaking={}; SoapDishMaker.totalProducts=0; SoapDishMaker.dayTimer=0; print("[SoapDishMaker] Royal Soap Dish Maker System initialized (6 products, 4 buildings)") end
function SoapDishMaker.hireMaker(n,s) s=s or math.random(55,90); local c=565+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SoapDishMaker.maker={name=n or ("Posodica "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Posodica najet: %s (spretnost: %d)",SoapDishMaker.maker.name,s),"success") end; return true end
function SoapDishMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SoapDishMaker.build(id) local ok,e=SoapDishMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SoapDishMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SoapDishMaker.getQualityBonus() local b=0; for _,bd in ipairs(SoapDishMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SoapDishMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SoapDishMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SoapDishMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SoapDishMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SoapDishMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SoapDishMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SoapDishMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SoapDishMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SoapDishMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SoapDishMaker.buildings==0 then return false,"Potrebna posodična delavnica" end; if not SoapDishMaker.maker then return false,"Potreben posodica" end; return true end
function SoapDishMaker.make(pt,qty) qty=qty or 1; local ok,e=SoapDishMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SoapDishMaker.ironStock=SoapDishMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SoapDishMaker.bronzeStock=SoapDishMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SoapDishMaker.woodStock=SoapDishMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SoapDishMaker.leatherStock=SoapDishMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SoapDishMaker.silverStock=SoapDishMaker.silverStock-d.silverCost*qty end; if d.goldCost then SoapDishMaker.goldStock=SoapDishMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SoapDishMaker.jewelStock=SoapDishMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SoapDishMaker.pearlStock=SoapDishMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SoapDishMaker.maker then t=math.max(1,t-math.floor(SoapDishMaker.maker.skill/13)) end; table.insert(SoapDishMaker.activeMaking,{id="soapdish_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SoapDishMaker.completeMaking(m) local q=1.0+(SoapDishMaker.getQualityBonus()/100); if SoapDishMaker.maker then q=q+(SoapDishMaker.maker.skill/140) end; q=math.min(2.5,q); SoapDishMaker.productStock[m.productType]=(SoapDishMaker.productStock[m.productType] or 0)+m.quantity; SoapDishMaker.totalProducts=SoapDishMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SoapDishMaker.maker then SoapDishMaker.maker.itemsMade=SoapDishMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SoapDishMaker.maker.skill=math.min(100,SoapDishMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Posoda izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"soapdish.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SoapDishMaker.update(dt) if not _G.state then return end; SoapDishMaker.dayTimer=SoapDishMaker.dayTimer+dt; if SoapDishMaker.dayTimer>=30 then SoapDishMaker.dayTimer=0; for i=#SoapDishMaker.activeMaking,1,-1 do local m=SoapDishMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SoapDishMaker.completeMaking(m); table.remove(SoapDishMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SoapDishMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SoapDishMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SoapDishMaker.getStats() return {ironStock=SoapDishMaker.ironStock,bronzeStock=SoapDishMaker.bronzeStock,woodStock=SoapDishMaker.woodStock,leatherStock=SoapDishMaker.leatherStock,silverStock=SoapDishMaker.silverStock,goldStock=SoapDishMaker.goldStock,jewelStock=SoapDishMaker.jewelStock,pearlStock=SoapDishMaker.pearlStock,productStock=SoapDishMaker.productStock,numBuildings=#SoapDishMaker.buildings,hasMaker=SoapDishMaker.maker~=nil,makerName=SoapDishMaker.maker and SoapDishMaker.maker.name or "—",makerSkill=SoapDishMaker.maker and SoapDishMaker.maker.skill or 0,activeMaking=#SoapDishMaker.activeMaking,totalProducts=SoapDishMaker.totalProducts} end
return SoapDishMaker
