local SandMullerBladeMaker = {}
local PRODUCTS = {
    iron_sandmullerblade = { name = "Železni lopice mešalca peska", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni lopice mešalca peska za livarje." },
    bronze_sandmullerblade = { name = "Bronast lopice mešalca peska", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast lopice mešalca peska za livarje." },
    silver_sandmullerblade = { name = "Srebrn lopice mešalca peska", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn lopice mešalca peska za livarje." },
    gilded_sandmullerblade = { name = "Pozlačen lopice mešalca peska", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen lopice mešalca peska za livarje." },
    jewel_set_sandmullerblade = { name = "Draguljast lopice mešalca peska", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast lopice mešalca peska za livarje." },
    royal_sovereign_sandmullerblade = { name = "Kraljevski suveren lopice mešalca peska", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren lopice mešalca peska z biseri za krono." },
}
local BUILDINGS = {
    sandmullerblade_workshop = { name = "Sandmullerblade delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    sandmullerblade_house = { name = "Sandmullerblade hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_sandmullerblade_atelier = { name = "Mojstrski sandmullerblade atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_sandmullerblade_palace = { name = "Suverena sandmullerblade palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SandMullerBladeMaker.ironStock=16; SandMullerBladeMaker.bronzeStock=12; SandMullerBladeMaker.woodStock=12; SandMullerBladeMaker.leatherStock=8; SandMullerBladeMaker.silverStock=8; SandMullerBladeMaker.goldStock=6; SandMullerBladeMaker.jewelStock=4; SandMullerBladeMaker.pearlStock=4
SandMullerBladeMaker.productStock = {}; SandMullerBladeMaker.buildings = {}; SandMullerBladeMaker.maker = nil; SandMullerBladeMaker.activeMaking = {}; SandMullerBladeMaker.totalProducts = 0; SandMullerBladeMaker.dayTimer = 0
function SandMullerBladeMaker.init() SandMullerBladeMaker.ironStock=16; SandMullerBladeMaker.bronzeStock=12; SandMullerBladeMaker.woodStock=12; SandMullerBladeMaker.leatherStock=8; SandMullerBladeMaker.silverStock=8; SandMullerBladeMaker.goldStock=6; SandMullerBladeMaker.jewelStock=4; SandMullerBladeMaker.pearlStock=4; SandMullerBladeMaker.productStock={}; SandMullerBladeMaker.buildings={}; SandMullerBladeMaker.maker=nil; SandMullerBladeMaker.activeMaking={}; SandMullerBladeMaker.totalProducts=0; SandMullerBladeMaker.dayTimer=0; print("[SandMullerBladeMaker] Royal Sand Muller Blade Maker System initialized (6 products, 4 buildings)") end
function SandMullerBladeMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SandMullerBladeMaker.maker={name=n or ("Lopatičar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lopatičar najet: %s (spretnost: %d)",SandMullerBladeMaker.maker.name,s),"success") end; return true end
function SandMullerBladeMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SandMullerBladeMaker.build(id) local ok,e=SandMullerBladeMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SandMullerBladeMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SandMullerBladeMaker.getQualityBonus() local b=0; for _,bd in ipairs(SandMullerBladeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SandMullerBladeMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SandMullerBladeMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SandMullerBladeMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SandMullerBladeMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SandMullerBladeMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SandMullerBladeMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SandMullerBladeMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SandMullerBladeMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SandMullerBladeMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SandMullerBladeMaker.buildings==0 then return false,"Potrebna lopaticna delavnica" end; if not SandMullerBladeMaker.maker then return false,"Potreben lopaticar" end; return true end
function SandMullerBladeMaker.make(pt,qty) qty=qty or 1; local ok,e=SandMullerBladeMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SandMullerBladeMaker.ironStock=SandMullerBladeMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SandMullerBladeMaker.bronzeStock=SandMullerBladeMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SandMullerBladeMaker.woodStock=SandMullerBladeMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SandMullerBladeMaker.leatherStock=SandMullerBladeMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SandMullerBladeMaker.silverStock=SandMullerBladeMaker.silverStock-d.silverCost*qty end; if d.goldCost then SandMullerBladeMaker.goldStock=SandMullerBladeMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SandMullerBladeMaker.jewelStock=SandMullerBladeMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SandMullerBladeMaker.pearlStock=SandMullerBladeMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SandMullerBladeMaker.maker then t=math.max(1,t-math.floor(SandMullerBladeMaker.maker.skill/13)) end; table.insert(SandMullerBladeMaker.activeMaking,{id="sandmullerblade_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SandMullerBladeMaker.completeMaking(m) local q=1.0+(SandMullerBladeMaker.getQualityBonus()/100); if SandMullerBladeMaker.maker then q=q+(SandMullerBladeMaker.maker.skill/140) end; q=math.min(2.5,q); SandMullerBladeMaker.productStock[m.productType]=(SandMullerBladeMaker.productStock[m.productType] or 0)+m.quantity; SandMullerBladeMaker.totalProducts=SandMullerBladeMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SandMullerBladeMaker.maker then SandMullerBladeMaker.maker.itemsMade=SandMullerBladeMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SandMullerBladeMaker.maker.skill=math.min(100,SandMullerBladeMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lopatica izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sandmullerblade.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SandMullerBladeMaker.update(dt) if not _G.state then return end; SandMullerBladeMaker.dayTimer=SandMullerBladeMaker.dayTimer+dt; if SandMullerBladeMaker.dayTimer>=30 then SandMullerBladeMaker.dayTimer=0; for i=#SandMullerBladeMaker.activeMaking,1,-1 do local m=SandMullerBladeMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SandMullerBladeMaker.completeMaking(m); table.remove(SandMullerBladeMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SandMullerBladeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SandMullerBladeMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SandMullerBladeMaker.getStats() return {ironStock=SandMullerBladeMaker.ironStock,bronzeStock=SandMullerBladeMaker.bronzeStock,woodStock=SandMullerBladeMaker.woodStock,leatherStock=SandMullerBladeMaker.leatherStock,silverStock=SandMullerBladeMaker.silverStock,goldStock=SandMullerBladeMaker.goldStock,jewelStock=SandMullerBladeMaker.jewelStock,pearlStock=SandMullerBladeMaker.pearlStock,productStock=SandMullerBladeMaker.productStock,numBuildings=#SandMullerBladeMaker.buildings,hasMaker=SandMullerBladeMaker.maker~=nil,makerName=SandMullerBladeMaker.maker and SandMullerBladeMaker.maker.name or "—",makerSkill=SandMullerBladeMaker.maker and SandMullerBladeMaker.maker.skill or 0,activeMaking=#SandMullerBladeMaker.activeMaking,totalProducts=SandMullerBladeMaker.totalProducts} end
return SandMullerBladeMaker
