local GlassEngravingLatheChuckMaker = {}
local PRODUCTS = {
    iron_glassengravinglathechuck = { name = "Železni stiskalnik za stružnico", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni stiskalnik za stružnico za steklarje." },
    bronze_glassengravinglathechuck = { name = "Bronast stiskalnik za stružnico", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast stiskalnik za stružnico za steklarje." },
    silver_glassengravinglathechuck = { name = "Srebrn stiskalnik za stružnico", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn stiskalnik za stružnico za steklarje." },
    gilded_glassengravinglathechuck = { name = "Pozlačen stiskalnik za stružnico", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen stiskalnik za stružnico za steklarje." },
    jewel_set_glassengravinglathechuck = { name = "Draguljast stiskalnik za stružnico", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast stiskalnik za stružnico za steklarje." },
    royal_sovereign_glassengravinglathechuck = { name = "Kraljevski suveren stiskalnik za stružnico", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren stiskalnik za stružnico z biseri za krono." },
}
local BUILDINGS = {
    glassengravinglathechuck_workshop = { name = "Glassengravinglathechuck delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glassengravinglathechuck_house = { name = "Glassengravinglathechuck hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glassengravinglathechuck_atelier = { name = "Mojstrski glassengravinglathechuck atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glassengravinglathechuck_palace = { name = "Suverena glassengravinglathechuck palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassEngravingLatheChuckMaker.ironStock=18; GlassEngravingLatheChuckMaker.bronzeStock=14; GlassEngravingLatheChuckMaker.woodStock=10; GlassEngravingLatheChuckMaker.leatherStock=8; GlassEngravingLatheChuckMaker.silverStock=8; GlassEngravingLatheChuckMaker.goldStock=6; GlassEngravingLatheChuckMaker.jewelStock=4; GlassEngravingLatheChuckMaker.pearlStock=4
GlassEngravingLatheChuckMaker.productStock = {}; GlassEngravingLatheChuckMaker.buildings = {}; GlassEngravingLatheChuckMaker.maker = nil; GlassEngravingLatheChuckMaker.activeMaking = {}; GlassEngravingLatheChuckMaker.totalProducts = 0; GlassEngravingLatheChuckMaker.dayTimer = 0
function GlassEngravingLatheChuckMaker.init() GlassEngravingLatheChuckMaker.ironStock=18; GlassEngravingLatheChuckMaker.bronzeStock=14; GlassEngravingLatheChuckMaker.woodStock=10; GlassEngravingLatheChuckMaker.leatherStock=8; GlassEngravingLatheChuckMaker.silverStock=8; GlassEngravingLatheChuckMaker.goldStock=6; GlassEngravingLatheChuckMaker.jewelStock=4; GlassEngravingLatheChuckMaker.pearlStock=4; GlassEngravingLatheChuckMaker.productStock={}; GlassEngravingLatheChuckMaker.buildings={}; GlassEngravingLatheChuckMaker.maker=nil; GlassEngravingLatheChuckMaker.activeMaking={}; GlassEngravingLatheChuckMaker.totalProducts=0; GlassEngravingLatheChuckMaker.dayTimer=0; print("[GlassEngravingLatheChuckMaker] Royal Glass Engraving Lathe Chuck Maker System initialized (6 products, 4 buildings)") end
function GlassEngravingLatheChuckMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassEngravingLatheChuckMaker.maker={name=n or ("Stiskalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stiskalnik najet: %s (spretnost: %d)",GlassEngravingLatheChuckMaker.maker.name,s),"success") end; return true end
function GlassEngravingLatheChuckMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassEngravingLatheChuckMaker.build(id) local ok,e=GlassEngravingLatheChuckMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassEngravingLatheChuckMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassEngravingLatheChuckMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassEngravingLatheChuckMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassEngravingLatheChuckMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassEngravingLatheChuckMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassEngravingLatheChuckMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassEngravingLatheChuckMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassEngravingLatheChuckMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassEngravingLatheChuckMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassEngravingLatheChuckMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassEngravingLatheChuckMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassEngravingLatheChuckMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassEngravingLatheChuckMaker.buildings==0 then return false,"Potrebna stiskalna delavnica" end; if not GlassEngravingLatheChuckMaker.maker then return false,"Potreben stiskalnik" end; return true end
function GlassEngravingLatheChuckMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassEngravingLatheChuckMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassEngravingLatheChuckMaker.ironStock=GlassEngravingLatheChuckMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassEngravingLatheChuckMaker.bronzeStock=GlassEngravingLatheChuckMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassEngravingLatheChuckMaker.woodStock=GlassEngravingLatheChuckMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassEngravingLatheChuckMaker.leatherStock=GlassEngravingLatheChuckMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassEngravingLatheChuckMaker.silverStock=GlassEngravingLatheChuckMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassEngravingLatheChuckMaker.goldStock=GlassEngravingLatheChuckMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassEngravingLatheChuckMaker.jewelStock=GlassEngravingLatheChuckMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassEngravingLatheChuckMaker.pearlStock=GlassEngravingLatheChuckMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassEngravingLatheChuckMaker.maker then t=math.max(1,t-math.floor(GlassEngravingLatheChuckMaker.maker.skill/13)) end; table.insert(GlassEngravingLatheChuckMaker.activeMaking,{id="glassengravinglathechuck_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassEngravingLatheChuckMaker.completeMaking(m) local q=1.0+(GlassEngravingLatheChuckMaker.getQualityBonus()/100); if GlassEngravingLatheChuckMaker.maker then q=q+(GlassEngravingLatheChuckMaker.maker.skill/140) end; q=math.min(2.5,q); GlassEngravingLatheChuckMaker.productStock[m.productType]=(GlassEngravingLatheChuckMaker.productStock[m.productType] or 0)+m.quantity; GlassEngravingLatheChuckMaker.totalProducts=GlassEngravingLatheChuckMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassEngravingLatheChuckMaker.maker then GlassEngravingLatheChuckMaker.maker.itemsMade=GlassEngravingLatheChuckMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassEngravingLatheChuckMaker.maker.skill=math.min(100,GlassEngravingLatheChuckMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stiskalnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glassengravinglathechuck.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassEngravingLatheChuckMaker.update(dt) if not _G.state then return end; GlassEngravingLatheChuckMaker.dayTimer=GlassEngravingLatheChuckMaker.dayTimer+dt; if GlassEngravingLatheChuckMaker.dayTimer>=30 then GlassEngravingLatheChuckMaker.dayTimer=0; for i=#GlassEngravingLatheChuckMaker.activeMaking,1,-1 do local m=GlassEngravingLatheChuckMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassEngravingLatheChuckMaker.completeMaking(m); table.remove(GlassEngravingLatheChuckMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassEngravingLatheChuckMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassEngravingLatheChuckMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassEngravingLatheChuckMaker.getStats() return {ironStock=GlassEngravingLatheChuckMaker.ironStock,bronzeStock=GlassEngravingLatheChuckMaker.bronzeStock,woodStock=GlassEngravingLatheChuckMaker.woodStock,leatherStock=GlassEngravingLatheChuckMaker.leatherStock,silverStock=GlassEngravingLatheChuckMaker.silverStock,goldStock=GlassEngravingLatheChuckMaker.goldStock,jewelStock=GlassEngravingLatheChuckMaker.jewelStock,pearlStock=GlassEngravingLatheChuckMaker.pearlStock,productStock=GlassEngravingLatheChuckMaker.productStock,numBuildings=#GlassEngravingLatheChuckMaker.buildings,hasMaker=GlassEngravingLatheChuckMaker.maker~=nil,makerName=GlassEngravingLatheChuckMaker.maker and GlassEngravingLatheChuckMaker.maker.name or "—",makerSkill=GlassEngravingLatheChuckMaker.maker and GlassEngravingLatheChuckMaker.maker.skill or 0,activeMaking=#GlassEngravingLatheChuckMaker.activeMaking,totalProducts=GlassEngravingLatheChuckMaker.totalProducts} end
return GlassEngravingLatheChuckMaker
