local MillHopperShakerMaker = {}
local PRODUCTS = {
    iron_millhoppershaker = { name = "Železni tresoče stresalo za lijak", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni tresoče stresalo za lijak za mlinarje." },
    bronze_millhoppershaker = { name = "Bronast tresoče stresalo za lijak", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast tresoče stresalo za lijak za mlinarje." },
    silver_millhoppershaker = { name = "Srebrn tresoče stresalo za lijak", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn tresoče stresalo za lijak za mlinarje." },
    gilded_millhoppershaker = { name = "Pozlačen tresoče stresalo za lijak", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen tresoče stresalo za lijak za mlinarje." },
    jewel_set_millhoppershaker = { name = "Draguljast tresoče stresalo za lijak", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast tresoče stresalo za lijak za mlinarje." },
    royal_sovereign_millhoppershaker = { name = "Kraljevski suveren tresoče stresalo za lijak", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren tresoče stresalo za lijak z biseri za krono." },
}
local BUILDINGS = {
    millhoppershaker_workshop = { name = "Millhoppershaker delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    millhoppershaker_house = { name = "Millhoppershaker hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_millhoppershaker_atelier = { name = "Mojstrski millhoppershaker atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_millhoppershaker_palace = { name = "Suverena millhoppershaker palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillHopperShakerMaker.ironStock=16; MillHopperShakerMaker.bronzeStock=12; MillHopperShakerMaker.woodStock=12; MillHopperShakerMaker.leatherStock=8; MillHopperShakerMaker.silverStock=8; MillHopperShakerMaker.goldStock=6; MillHopperShakerMaker.jewelStock=4; MillHopperShakerMaker.pearlStock=4
MillHopperShakerMaker.productStock = {}; MillHopperShakerMaker.buildings = {}; MillHopperShakerMaker.maker = nil; MillHopperShakerMaker.activeMaking = {}; MillHopperShakerMaker.totalProducts = 0; MillHopperShakerMaker.dayTimer = 0
function MillHopperShakerMaker.init() MillHopperShakerMaker.ironStock=16; MillHopperShakerMaker.bronzeStock=12; MillHopperShakerMaker.woodStock=12; MillHopperShakerMaker.leatherStock=8; MillHopperShakerMaker.silverStock=8; MillHopperShakerMaker.goldStock=6; MillHopperShakerMaker.jewelStock=4; MillHopperShakerMaker.pearlStock=4; MillHopperShakerMaker.productStock={}; MillHopperShakerMaker.buildings={}; MillHopperShakerMaker.maker=nil; MillHopperShakerMaker.activeMaking={}; MillHopperShakerMaker.totalProducts=0; MillHopperShakerMaker.dayTimer=0; print("[MillHopperShakerMaker] Royal Mill Hopper Shaker Maker System initialized (6 products, 4 buildings)") end
function MillHopperShakerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillHopperShakerMaker.maker={name=n or ("Treskar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Treskar najet: %s (spretnost: %d)",MillHopperShakerMaker.maker.name,s),"success") end; return true end
function MillHopperShakerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillHopperShakerMaker.build(id) local ok,e=MillHopperShakerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillHopperShakerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillHopperShakerMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillHopperShakerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillHopperShakerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillHopperShakerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillHopperShakerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillHopperShakerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillHopperShakerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillHopperShakerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillHopperShakerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillHopperShakerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillHopperShakerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillHopperShakerMaker.buildings==0 then return false,"Potrebna treskalna delavnica" end; if not MillHopperShakerMaker.maker then return false,"Potreben treskar" end; return true end
function MillHopperShakerMaker.make(pt,qty) qty=qty or 1; local ok,e=MillHopperShakerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillHopperShakerMaker.ironStock=MillHopperShakerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillHopperShakerMaker.bronzeStock=MillHopperShakerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillHopperShakerMaker.woodStock=MillHopperShakerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillHopperShakerMaker.leatherStock=MillHopperShakerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillHopperShakerMaker.silverStock=MillHopperShakerMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillHopperShakerMaker.goldStock=MillHopperShakerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillHopperShakerMaker.jewelStock=MillHopperShakerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillHopperShakerMaker.pearlStock=MillHopperShakerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillHopperShakerMaker.maker then t=math.max(1,t-math.floor(MillHopperShakerMaker.maker.skill/13)) end; table.insert(MillHopperShakerMaker.activeMaking,{id="millhoppershaker_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillHopperShakerMaker.completeMaking(m) local q=1.0+(MillHopperShakerMaker.getQualityBonus()/100); if MillHopperShakerMaker.maker then q=q+(MillHopperShakerMaker.maker.skill/140) end; q=math.min(2.5,q); MillHopperShakerMaker.productStock[m.productType]=(MillHopperShakerMaker.productStock[m.productType] or 0)+m.quantity; MillHopperShakerMaker.totalProducts=MillHopperShakerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillHopperShakerMaker.maker then MillHopperShakerMaker.maker.itemsMade=MillHopperShakerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillHopperShakerMaker.maker.skill=math.min(100,MillHopperShakerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Treskač izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millhoppershaker.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillHopperShakerMaker.update(dt) if not _G.state then return end; MillHopperShakerMaker.dayTimer=MillHopperShakerMaker.dayTimer+dt; if MillHopperShakerMaker.dayTimer>=30 then MillHopperShakerMaker.dayTimer=0; for i=#MillHopperShakerMaker.activeMaking,1,-1 do local m=MillHopperShakerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillHopperShakerMaker.completeMaking(m); table.remove(MillHopperShakerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillHopperShakerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillHopperShakerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillHopperShakerMaker.getStats() return {ironStock=MillHopperShakerMaker.ironStock,bronzeStock=MillHopperShakerMaker.bronzeStock,woodStock=MillHopperShakerMaker.woodStock,leatherStock=MillHopperShakerMaker.leatherStock,silverStock=MillHopperShakerMaker.silverStock,goldStock=MillHopperShakerMaker.goldStock,jewelStock=MillHopperShakerMaker.jewelStock,pearlStock=MillHopperShakerMaker.pearlStock,productStock=MillHopperShakerMaker.productStock,numBuildings=#MillHopperShakerMaker.buildings,hasMaker=MillHopperShakerMaker.maker~=nil,makerName=MillHopperShakerMaker.maker and MillHopperShakerMaker.maker.name or "—",makerSkill=MillHopperShakerMaker.maker and MillHopperShakerMaker.maker.skill or 0,activeMaking=#MillHopperShakerMaker.activeMaking,totalProducts=MillHopperShakerMaker.totalProducts} end
return MillHopperShakerMaker
