local BoneSawMaker = {}
local PRODUCTS = {
    iron_bonesaw = { name = "Zelezna kostna zaga", ironCost = 3, woodCost = 2, leatherCost = 1, time = 6, cost = 180, prestige = 3, happiness = 1, description = "Zelezna zaga za amputacijo kosti." },
    bronze_bonesaw = { name = "Bronasta kostna zaga", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 8, cost = 420, prestige = 6, happiness = 2, description = "Bronasta zaga za kirurske amputacije." },
    silver_bonesaw = { name = "Srebrna kostna zaga", silverCost = 2, bronzeCost = 2, ironCost = 1, woodCost = 1, leatherCost = 1, time = 12, cost = 980, prestige = 11, happiness = 3, description = "Srebrna zaga za plemiske kirurge." },
    gilded_bonesaw = { name = "Pozlacena kostna zaga", goldCost = 1, silverCost = 2, bronzeCost = 2, woodCost = 1, leatherCost = 1, time = 16, cost = 2100, prestige = 20, happiness = 4, description = "Pozlacena zaga za dvornega kirurga." },
    jewel_set_bonesaw = { name = "Draguljasta kostna zaga", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 20, cost = 4500, prestige = 38, happiness = 6, description = "Draguljasta zaga za kraljevega zdravnika." },
    royal_sovereign_bonesaw = { name = "Kraljevski suverena kostna zaga", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 27, cost = 9600, prestige = 72, happiness = 12, description = "Suverena kostna zaga z biseri za krono." },
}
local BUILDINGS = {
    bonesaw_workshop = { name = "Zagarska delavnica", cost = { gold = 360, wood = 180, stone = 140, iron = 8 }, upkeep = 7, qualityBonus = 5 },
    bonesaw_house = { name = "Zagarska hisa", cost = { gold = 1280, wood = 370, stone = 280, silver = 8, iron = 8 }, upkeep = 28, qualityBonus = 18 },
    master_bonesaw_atelier = { name = "Mojstrski zagarski atelje", cost = { gold = 3200, wood = 430, stone = 540, silver = 38, gold = 8 }, upkeep = 76, qualityBonus = 30 },
    sovereign_surgical_palace = { name = "Suverena kirurska palaca", cost = { gold = 13500, wood = 650, stone = 860, gold = 88, jewel = 20 }, upkeep = 268, qualityBonus = 55, prestigeBonus = 55 },
}
BoneSawMaker.ironStock = 12; BoneSawMaker.bronzeStock = 10; BoneSawMaker.woodStock = 14; BoneSawMaker.leatherStock = 10; BoneSawMaker.silverStock = 8; BoneSawMaker.goldStock = 6; BoneSawMaker.jewelStock = 4; BoneSawMaker.pearlStock = 4
BoneSawMaker.productStock = {}; BoneSawMaker.buildings = {}; BoneSawMaker.maker = nil; BoneSawMaker.activeMaking = {}; BoneSawMaker.totalProducts = 0; BoneSawMaker.dayTimer = 0
function BoneSawMaker.init() BoneSawMaker.ironStock=12; BoneSawMaker.bronzeStock=10; BoneSawMaker.woodStock=14; BoneSawMaker.leatherStock=10; BoneSawMaker.silverStock=8; BoneSawMaker.goldStock=6; BoneSawMaker.jewelStock=4; BoneSawMaker.pearlStock=4; BoneSawMaker.productStock={}; BoneSawMaker.buildings={}; BoneSawMaker.maker=nil; BoneSawMaker.activeMaking={}; BoneSawMaker.totalProducts=0; BoneSawMaker.dayTimer=0; print("[BoneSawMaker] Royal Bone Saw Maker System initialized (6 products, 4 buildings)") end
function BoneSawMaker.hireMaker(n,s) s=s or math.random(55,90); local c=620+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BoneSawMaker.maker={name=n or ("Kostni zagar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kostni zagar najet: %s (spretnost: %d)",BoneSawMaker.maker.name,s),"success") end; return true end
function BoneSawMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BoneSawMaker.build(id) local ok,e=BoneSawMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BoneSawMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BoneSawMaker.getQualityBonus() local b=0; for _,bd in ipairs(BoneSawMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BoneSawMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BoneSawMaker.ironStock<(d.ironCost or 0) then return false,"Premalo zeleza" end; if d.bronzeCost and BoneSawMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BoneSawMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BoneSawMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BoneSawMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BoneSawMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BoneSawMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BoneSawMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BoneSawMaker.buildings==0 then return false,"Potrebna delavnica" end; if not BoneSawMaker.maker then return false,"Potreben mojster" end; return true end
function BoneSawMaker.make(pt,qty) qty=qty or 1; local ok,e=BoneSawMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BoneSawMaker.ironStock=BoneSawMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BoneSawMaker.bronzeStock=BoneSawMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BoneSawMaker.woodStock=BoneSawMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BoneSawMaker.leatherStock=BoneSawMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BoneSawMaker.silverStock=BoneSawMaker.silverStock-d.silverCost*qty end; if d.goldCost then BoneSawMaker.goldStock=BoneSawMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BoneSawMaker.jewelStock=BoneSawMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BoneSawMaker.pearlStock=BoneSawMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BoneSawMaker.maker then t=math.max(1,t-math.floor(BoneSawMaker.maker.skill/13)) end; table.insert(BoneSawMaker.activeMaking,{id="bonesaw_"..tostring(os.time()).."_a"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BoneSawMaker.completeMaking(m) local q=1.0+(BoneSawMaker.getQualityBonus()/100); if BoneSawMaker.maker then q=q+(BoneSawMaker.maker.skill/140) end; q=math.min(2.5,q); BoneSawMaker.productStock[m.productType]=(BoneSawMaker.productStock[m.productType] or 0)+m.quantity; BoneSawMaker.totalProducts=BoneSawMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BoneSawMaker.maker then BoneSawMaker.maker.itemsMade=BoneSawMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BoneSawMaker.maker.skill=math.min(100,BoneSawMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bonesaw.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BoneSawMaker.update(dt) if not _G.state then return end; BoneSawMaker.dayTimer=BoneSawMaker.dayTimer+dt; if BoneSawMaker.dayTimer>=30 then BoneSawMaker.dayTimer=0; for i=#BoneSawMaker.activeMaking,1,-1 do local m=BoneSawMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BoneSawMaker.completeMaking(m); table.remove(BoneSawMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BoneSawMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BoneSawMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BoneSawMaker.getStats() return {ironStock=BoneSawMaker.ironStock,bronzeStock=BoneSawMaker.bronzeStock,woodStock=BoneSawMaker.woodStock,leatherStock=BoneSawMaker.leatherStock,silverStock=BoneSawMaker.silverStock,goldStock=BoneSawMaker.goldStock,jewelStock=BoneSawMaker.jewelStock,pearlStock=BoneSawMaker.pearlStock,productStock=BoneSawMaker.productStock,numBuildings=#BoneSawMaker.buildings,hasMaker=BoneSawMaker.maker~=nil,makerName=BoneSawMaker.maker and BoneSawMaker.maker.name or "Â",makerSkill=BoneSawMaker.maker and BoneSawMaker.maker.skill or 0,activeMaking=#BoneSawMaker.activeMaking,totalProducts=BoneSawMaker.totalProducts} end
return BoneSawMaker
