local MillstoneDressingCompassMaker = {}
local PRODUCTS = {
    iron_millstonedressingcompass = { name = "Železni šestilo za oblikovanje kamnov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni šestilo za oblikovanje kamnov za mlinarje." },
    bronze_millstonedressingcompass = { name = "Bronast šestilo za oblikovanje kamnov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast šestilo za oblikovanje kamnov za mlinarje." },
    silver_millstonedressingcompass = { name = "Srebrn šestilo za oblikovanje kamnov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn šestilo za oblikovanje kamnov za mlinarje." },
    gilded_millstonedressingcompass = { name = "Pozlačen šestilo za oblikovanje kamnov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen šestilo za oblikovanje kamnov za mlinarje." },
    jewel_set_millstonedressingcompass = { name = "Draguljast šestilo za oblikovanje kamnov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast šestilo za oblikovanje kamnov za mlinarje." },
    royal_sovereign_millstonedressingcompass = { name = "Kraljevski suveren šestilo za oblikovanje kamnov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren šestilo za oblikovanje kamnov z biseri za krono." },
}
local BUILDINGS = {
    millstonedressingcompass_workshop = { name = "Millstonedressingcompass delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    millstonedressingcompass_house = { name = "Millstonedressingcompass hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_millstonedressingcompass_atelier = { name = "Mojstrski millstonedressingcompass atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_millstonedressingcompass_palace = { name = "Suverena millstonedressingcompass palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillstoneDressingCompassMaker.ironStock=14; MillstoneDressingCompassMaker.bronzeStock=12; MillstoneDressingCompassMaker.woodStock=12; MillstoneDressingCompassMaker.leatherStock=8; MillstoneDressingCompassMaker.silverStock=8; MillstoneDressingCompassMaker.goldStock=6; MillstoneDressingCompassMaker.jewelStock=4; MillstoneDressingCompassMaker.pearlStock=4
MillstoneDressingCompassMaker.productStock = {}; MillstoneDressingCompassMaker.buildings = {}; MillstoneDressingCompassMaker.maker = nil; MillstoneDressingCompassMaker.activeMaking = {}; MillstoneDressingCompassMaker.totalProducts = 0; MillstoneDressingCompassMaker.dayTimer = 0
function MillstoneDressingCompassMaker.init() MillstoneDressingCompassMaker.ironStock=14; MillstoneDressingCompassMaker.bronzeStock=12; MillstoneDressingCompassMaker.woodStock=12; MillstoneDressingCompassMaker.leatherStock=8; MillstoneDressingCompassMaker.silverStock=8; MillstoneDressingCompassMaker.goldStock=6; MillstoneDressingCompassMaker.jewelStock=4; MillstoneDressingCompassMaker.pearlStock=4; MillstoneDressingCompassMaker.productStock={}; MillstoneDressingCompassMaker.buildings={}; MillstoneDressingCompassMaker.maker=nil; MillstoneDressingCompassMaker.activeMaking={}; MillstoneDressingCompassMaker.totalProducts=0; MillstoneDressingCompassMaker.dayTimer=0; print("[MillstoneDressingCompassMaker] Royal Millstone Dressing Compass Maker System initialized (6 products, 4 buildings)") end
function MillstoneDressingCompassMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillstoneDressingCompassMaker.maker={name=n or ("Šestilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Šestilar najet: %s (spretnost: %d)",MillstoneDressingCompassMaker.maker.name,s),"success") end; return true end
function MillstoneDressingCompassMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillstoneDressingCompassMaker.build(id) local ok,e=MillstoneDressingCompassMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillstoneDressingCompassMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillstoneDressingCompassMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillstoneDressingCompassMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillstoneDressingCompassMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillstoneDressingCompassMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillstoneDressingCompassMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillstoneDressingCompassMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillstoneDressingCompassMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillstoneDressingCompassMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillstoneDressingCompassMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillstoneDressingCompassMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillstoneDressingCompassMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillstoneDressingCompassMaker.buildings==0 then return false,"Potrebna šestilna delavnica" end; if not MillstoneDressingCompassMaker.maker then return false,"Potreben sestilar" end; return true end
function MillstoneDressingCompassMaker.make(pt,qty) qty=qty or 1; local ok,e=MillstoneDressingCompassMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillstoneDressingCompassMaker.ironStock=MillstoneDressingCompassMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillstoneDressingCompassMaker.bronzeStock=MillstoneDressingCompassMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillstoneDressingCompassMaker.woodStock=MillstoneDressingCompassMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillstoneDressingCompassMaker.leatherStock=MillstoneDressingCompassMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillstoneDressingCompassMaker.silverStock=MillstoneDressingCompassMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillstoneDressingCompassMaker.goldStock=MillstoneDressingCompassMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillstoneDressingCompassMaker.jewelStock=MillstoneDressingCompassMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillstoneDressingCompassMaker.pearlStock=MillstoneDressingCompassMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillstoneDressingCompassMaker.maker then t=math.max(1,t-math.floor(MillstoneDressingCompassMaker.maker.skill/13)) end; table.insert(MillstoneDressingCompassMaker.activeMaking,{id="millstonedressingcompass_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillstoneDressingCompassMaker.completeMaking(m) local q=1.0+(MillstoneDressingCompassMaker.getQualityBonus()/100); if MillstoneDressingCompassMaker.maker then q=q+(MillstoneDressingCompassMaker.maker.skill/140) end; q=math.min(2.5,q); MillstoneDressingCompassMaker.productStock[m.productType]=(MillstoneDressingCompassMaker.productStock[m.productType] or 0)+m.quantity; MillstoneDressingCompassMaker.totalProducts=MillstoneDressingCompassMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillstoneDressingCompassMaker.maker then MillstoneDressingCompassMaker.maker.itemsMade=MillstoneDressingCompassMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillstoneDressingCompassMaker.maker.skill=math.min(100,MillstoneDressingCompassMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Šestilo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millstonedressingcompass.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillstoneDressingCompassMaker.update(dt) if not _G.state then return end; MillstoneDressingCompassMaker.dayTimer=MillstoneDressingCompassMaker.dayTimer+dt; if MillstoneDressingCompassMaker.dayTimer>=30 then MillstoneDressingCompassMaker.dayTimer=0; for i=#MillstoneDressingCompassMaker.activeMaking,1,-1 do local m=MillstoneDressingCompassMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillstoneDressingCompassMaker.completeMaking(m); table.remove(MillstoneDressingCompassMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillstoneDressingCompassMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillstoneDressingCompassMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillstoneDressingCompassMaker.getStats() return {ironStock=MillstoneDressingCompassMaker.ironStock,bronzeStock=MillstoneDressingCompassMaker.bronzeStock,woodStock=MillstoneDressingCompassMaker.woodStock,leatherStock=MillstoneDressingCompassMaker.leatherStock,silverStock=MillstoneDressingCompassMaker.silverStock,goldStock=MillstoneDressingCompassMaker.goldStock,jewelStock=MillstoneDressingCompassMaker.jewelStock,pearlStock=MillstoneDressingCompassMaker.pearlStock,productStock=MillstoneDressingCompassMaker.productStock,numBuildings=#MillstoneDressingCompassMaker.buildings,hasMaker=MillstoneDressingCompassMaker.maker~=nil,makerName=MillstoneDressingCompassMaker.maker and MillstoneDressingCompassMaker.maker.name or "—",makerSkill=MillstoneDressingCompassMaker.maker and MillstoneDressingCompassMaker.maker.skill or 0,activeMaking=#MillstoneDressingCompassMaker.activeMaking,totalProducts=MillstoneDressingCompassMaker.totalProducts} end
return MillstoneDressingCompassMaker
