local MoldKilnMaker = {}
local PRODUCTS = {
    simple_clay_mold_kiln = { name = "Preprosta glinena kalupna peč", clayCost = 4, brickCost = 2, time = 5, cost = 200, science = 22, happiness = 1, description = "Preprosta glinena kalupna peč za kalupe." },
    iron_reinforced_mold_kiln = { name = "Železnookrepljena kalupna peč", clayCost = 3, ironCost = 2, brickCost = 2, time = 8, cost = 480, science = 35, happiness = 2, prestige = 2, description = "Železnookrepljena kalupna peč za trgovce." },
    silver_banded_mold_kiln = { name = "Srebrnopasna kalupna peč", clayCost = 3, silverCost = 1, ironCost = 2, brickCost = 2, time = 12, cost = 1100, science = 50, happiness = 2, prestige = 6, description = "Srebrnopasna kalupna peč za plemiče." },
    gold_trimmed_mold_kiln = { name = "Zlatookrasna kalupna peč", clayCost = 3, goldCost = 1, silverCost = 1, ironCost = 2, brickCost = 2, time = 16, cost = 2500, science = 65, happiness = 3, prestige = 14, description = "Zlatookrasna kalupna peč za visoke plemiče." },
    jewel_set_mold_kiln = { name = "Draguljasta kalupna peč", clayCost = 3, goldCost = 1, silverCost = 1, ironCost = 2, brickCost = 2, jewelCost = 1, time = 20, cost = 5400, science = 80, happiness = 5, prestige = 27, description = "Kalupna peč z draguljem za visoko plemstvo." },
    royal_grand_mold_kiln = { name = "Kraljevski veliki kalupna peč", clayCost = 4, goldCost = 2, silverCost = 2, ironCost = 2, brickCost = 2, jewelCost = 2, pearlCost = 2, time = 27, cost = 11500, science = 95, happiness = 12, prestige = 58, description = "Velika kraljevska kalupna peč z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    mold_kiln_workshop = { name = "Kalupna pečna delavnica", cost = { gold = 300, wood = 140, stone = 180, clay = 8, brick = 6 }, upkeep = 7, qualityBonus = 5 },
    casting_loft = { name = "Livna podstrešje", cost = { gold = 1100, wood = 320, stone = 320, silver = 6, iron = 6 }, upkeep = 26, qualityBonus = 18 },
    master_kiln_atelier = { name = "Mojstrski pečni atelje", cost = { gold = 2800, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_casting_palace = { name = "Kraljevska livna palača", cost = { gold = 12000, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
MoldKilnMaker.clayStock = 16; MoldKilnMaker.brickStock = 14; MoldKilnMaker.ironStock = 12; MoldKilnMaker.silverStock = 6; MoldKilnMaker.goldStock = 6; MoldKilnMaker.jewelStock = 4; MoldKilnMaker.pearlStock = 4
MoldKilnMaker.productStock = {}; MoldKilnMaker.buildings = {}; MoldKilnMaker.maker = nil; MoldKilnMaker.activeMaking = {}; MoldKilnMaker.totalProducts = 0; MoldKilnMaker.dayTimer = 0
function MoldKilnMaker.init() MoldKilnMaker.clayStock=16; MoldKilnMaker.brickStock=14; MoldKilnMaker.ironStock=12; MoldKilnMaker.silverStock=6; MoldKilnMaker.goldStock=6; MoldKilnMaker.jewelStock=4; MoldKilnMaker.pearlStock=4; MoldKilnMaker.productStock={}; MoldKilnMaker.buildings={}; MoldKilnMaker.maker=nil; MoldKilnMaker.activeMaking={}; MoldKilnMaker.totalProducts=0; MoldKilnMaker.dayTimer=0; print("[MoldKilnMaker] Royal Mold Kiln Maker System initialized (6 products, 4 buildings)") end
function MoldKilnMaker.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MoldKilnMaker.maker={name=n or ("Kalupni pečar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kalupni pečar najet: %s (spretnost: %d)",MoldKilnMaker.maker.name,s),"success") end; return true end
function MoldKilnMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MoldKilnMaker.build(id) local ok,e=MoldKilnMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MoldKilnMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MoldKilnMaker.getQualityBonus() local b=0; for _,bd in ipairs(MoldKilnMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MoldKilnMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.clayCost and MoldKilnMaker.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.brickCost and MoldKilnMaker.brickStock<(d.brickCost or 0) then return false,"Premalo opek" end; if d.ironCost and MoldKilnMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.silverCost and MoldKilnMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MoldKilnMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MoldKilnMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MoldKilnMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MoldKilnMaker.buildings==0 then return false,"Potrebna kalupna pečna delavnica" end; if not MoldKilnMaker.maker then return false,"Potreben kalupni pečar" end; return true end
function MoldKilnMaker.make(pt,qty) qty=qty or 1; local ok,e=MoldKilnMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.clayCost then MoldKilnMaker.clayStock=MoldKilnMaker.clayStock-d.clayCost*qty end; if d.brickCost then MoldKilnMaker.brickStock=MoldKilnMaker.brickStock-d.brickCost*qty end; if d.ironCost then MoldKilnMaker.ironStock=MoldKilnMaker.ironStock-d.ironCost*qty end; if d.silverCost then MoldKilnMaker.silverStock=MoldKilnMaker.silverStock-d.silverCost*qty end; if d.goldCost then MoldKilnMaker.goldStock=MoldKilnMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MoldKilnMaker.jewelStock=MoldKilnMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MoldKilnMaker.pearlStock=MoldKilnMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MoldKilnMaker.maker then t=math.max(1,t-math.floor(MoldKilnMaker.maker.skill/13)) end; table.insert(MoldKilnMaker.activeMaking,{id="moldkiln_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gradnja: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MoldKilnMaker.completeMaking(m) local q=1.0+(MoldKilnMaker.getQualityBonus()/100); if MoldKilnMaker.maker then q=q+(MoldKilnMaker.maker.skill/140) end; q=math.min(2.5,q); MoldKilnMaker.productStock[m.productType]=(MoldKilnMaker.productStock[m.productType] or 0)+m.quantity; MoldKilnMaker.totalProducts=MoldKilnMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MoldKilnMaker.maker then MoldKilnMaker.maker.itemsMade=MoldKilnMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MoldKilnMaker.maker.skill=math.min(100,MoldKilnMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kalupna peč izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"moldkiln.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function MoldKilnMaker.update(dt) if not _G.state then return end; MoldKilnMaker.dayTimer=MoldKilnMaker.dayTimer+dt; if MoldKilnMaker.dayTimer>=30 then MoldKilnMaker.dayTimer=0; for i=#MoldKilnMaker.activeMaking,1,-1 do local m=MoldKilnMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MoldKilnMaker.completeMaking(m); table.remove(MoldKilnMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MoldKilnMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MoldKilnMaker.maker then tu=tu+16 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MoldKilnMaker.getStats() return {clayStock=MoldKilnMaker.clayStock,brickStock=MoldKilnMaker.brickStock,ironStock=MoldKilnMaker.ironStock,silverStock=MoldKilnMaker.silverStock,goldStock=MoldKilnMaker.goldStock,jewelStock=MoldKilnMaker.jewelStock,pearlStock=MoldKilnMaker.pearlStock,productStock=MoldKilnMaker.productStock,numBuildings=#MoldKilnMaker.buildings,hasMaker=MoldKilnMaker.maker~=nil,makerName=MoldKilnMaker.maker and MoldKilnMaker.maker.name or "—",makerSkill=MoldKilnMaker.maker and MoldKilnMaker.maker.skill or 0,activeMaking=#MoldKilnMaker.activeMaking,totalProducts=MoldKilnMaker.totalProducts} end
return MoldKilnMaker
