local MillstoneBalanceWeightMaker = {}
local PRODUCTS = {
    iron_millstonebalanceweight = { name = "Železni utež za uravnoteženje kamnov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni utež za uravnoteženje kamnov za mlinarje." },
    bronze_millstonebalanceweight = { name = "Bronast utež za uravnoteženje kamnov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast utež za uravnoteženje kamnov za mlinarje." },
    silver_millstonebalanceweight = { name = "Srebrn utež za uravnoteženje kamnov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn utež za uravnoteženje kamnov za mlinarje." },
    gilded_millstonebalanceweight = { name = "Pozlačen utež za uravnoteženje kamnov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen utež za uravnoteženje kamnov za mlinarje." },
    jewel_set_millstonebalanceweight = { name = "Draguljast utež za uravnoteženje kamnov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast utež za uravnoteženje kamnov za mlinarje." },
    royal_sovereign_millstonebalanceweight = { name = "Kraljevski suveren utež za uravnoteženje kamnov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren utež za uravnoteženje kamnov z biseri za krono." },
}
local BUILDINGS = {
    millstonebalanceweight_workshop = { name = "Millstonebalanceweight delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    millstonebalanceweight_house = { name = "Millstonebalanceweight hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_millstonebalanceweight_atelier = { name = "Mojstrski millstonebalanceweight atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_millstonebalanceweight_palace = { name = "Suverena millstonebalanceweight palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillstoneBalanceWeightMaker.ironStock=18; MillstoneBalanceWeightMaker.bronzeStock=14; MillstoneBalanceWeightMaker.woodStock=10; MillstoneBalanceWeightMaker.leatherStock=8; MillstoneBalanceWeightMaker.silverStock=8; MillstoneBalanceWeightMaker.goldStock=6; MillstoneBalanceWeightMaker.jewelStock=4; MillstoneBalanceWeightMaker.pearlStock=4
MillstoneBalanceWeightMaker.productStock = {}; MillstoneBalanceWeightMaker.buildings = {}; MillstoneBalanceWeightMaker.maker = nil; MillstoneBalanceWeightMaker.activeMaking = {}; MillstoneBalanceWeightMaker.totalProducts = 0; MillstoneBalanceWeightMaker.dayTimer = 0
function MillstoneBalanceWeightMaker.init() MillstoneBalanceWeightMaker.ironStock=18; MillstoneBalanceWeightMaker.bronzeStock=14; MillstoneBalanceWeightMaker.woodStock=10; MillstoneBalanceWeightMaker.leatherStock=8; MillstoneBalanceWeightMaker.silverStock=8; MillstoneBalanceWeightMaker.goldStock=6; MillstoneBalanceWeightMaker.jewelStock=4; MillstoneBalanceWeightMaker.pearlStock=4; MillstoneBalanceWeightMaker.productStock={}; MillstoneBalanceWeightMaker.buildings={}; MillstoneBalanceWeightMaker.maker=nil; MillstoneBalanceWeightMaker.activeMaking={}; MillstoneBalanceWeightMaker.totalProducts=0; MillstoneBalanceWeightMaker.dayTimer=0; print("[MillstoneBalanceWeightMaker] Royal Millstone Balance Weight Maker System initialized (6 products, 4 buildings)") end
function MillstoneBalanceWeightMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillstoneBalanceWeightMaker.maker={name=n or ("Utežar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Utežar najet: %s (spretnost: %d)",MillstoneBalanceWeightMaker.maker.name,s),"success") end; return true end
function MillstoneBalanceWeightMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillstoneBalanceWeightMaker.build(id) local ok,e=MillstoneBalanceWeightMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillstoneBalanceWeightMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillstoneBalanceWeightMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillstoneBalanceWeightMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillstoneBalanceWeightMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillstoneBalanceWeightMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillstoneBalanceWeightMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillstoneBalanceWeightMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillstoneBalanceWeightMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillstoneBalanceWeightMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillstoneBalanceWeightMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillstoneBalanceWeightMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillstoneBalanceWeightMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillstoneBalanceWeightMaker.buildings==0 then return false,"Potrebna utezna delavnica" end; if not MillstoneBalanceWeightMaker.maker then return false,"Potreben utezar" end; return true end
function MillstoneBalanceWeightMaker.make(pt,qty) qty=qty or 1; local ok,e=MillstoneBalanceWeightMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillstoneBalanceWeightMaker.ironStock=MillstoneBalanceWeightMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillstoneBalanceWeightMaker.bronzeStock=MillstoneBalanceWeightMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillstoneBalanceWeightMaker.woodStock=MillstoneBalanceWeightMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillstoneBalanceWeightMaker.leatherStock=MillstoneBalanceWeightMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillstoneBalanceWeightMaker.silverStock=MillstoneBalanceWeightMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillstoneBalanceWeightMaker.goldStock=MillstoneBalanceWeightMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillstoneBalanceWeightMaker.jewelStock=MillstoneBalanceWeightMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillstoneBalanceWeightMaker.pearlStock=MillstoneBalanceWeightMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillstoneBalanceWeightMaker.maker then t=math.max(1,t-math.floor(MillstoneBalanceWeightMaker.maker.skill/13)) end; table.insert(MillstoneBalanceWeightMaker.activeMaking,{id="millstonebalanceweight_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillstoneBalanceWeightMaker.completeMaking(m) local q=1.0+(MillstoneBalanceWeightMaker.getQualityBonus()/100); if MillstoneBalanceWeightMaker.maker then q=q+(MillstoneBalanceWeightMaker.maker.skill/140) end; q=math.min(2.5,q); MillstoneBalanceWeightMaker.productStock[m.productType]=(MillstoneBalanceWeightMaker.productStock[m.productType] or 0)+m.quantity; MillstoneBalanceWeightMaker.totalProducts=MillstoneBalanceWeightMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillstoneBalanceWeightMaker.maker then MillstoneBalanceWeightMaker.maker.itemsMade=MillstoneBalanceWeightMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillstoneBalanceWeightMaker.maker.skill=math.min(100,MillstoneBalanceWeightMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Utež izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millstonebalanceweight.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillstoneBalanceWeightMaker.update(dt) if not _G.state then return end; MillstoneBalanceWeightMaker.dayTimer=MillstoneBalanceWeightMaker.dayTimer+dt; if MillstoneBalanceWeightMaker.dayTimer>=30 then MillstoneBalanceWeightMaker.dayTimer=0; for i=#MillstoneBalanceWeightMaker.activeMaking,1,-1 do local m=MillstoneBalanceWeightMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillstoneBalanceWeightMaker.completeMaking(m); table.remove(MillstoneBalanceWeightMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillstoneBalanceWeightMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillstoneBalanceWeightMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillstoneBalanceWeightMaker.getStats() return {ironStock=MillstoneBalanceWeightMaker.ironStock,bronzeStock=MillstoneBalanceWeightMaker.bronzeStock,woodStock=MillstoneBalanceWeightMaker.woodStock,leatherStock=MillstoneBalanceWeightMaker.leatherStock,silverStock=MillstoneBalanceWeightMaker.silverStock,goldStock=MillstoneBalanceWeightMaker.goldStock,jewelStock=MillstoneBalanceWeightMaker.jewelStock,pearlStock=MillstoneBalanceWeightMaker.pearlStock,productStock=MillstoneBalanceWeightMaker.productStock,numBuildings=#MillstoneBalanceWeightMaker.buildings,hasMaker=MillstoneBalanceWeightMaker.maker~=nil,makerName=MillstoneBalanceWeightMaker.maker and MillstoneBalanceWeightMaker.maker.name or "—",makerSkill=MillstoneBalanceWeightMaker.maker and MillstoneBalanceWeightMaker.maker.skill or 0,activeMaking=#MillstoneBalanceWeightMaker.activeMaking,totalProducts=MillstoneBalanceWeightMaker.totalProducts} end
return MillstoneBalanceWeightMaker
