local TopMaker = {}
local PRODUCTS = {
    wooden_top = { name = "Leseni vrtavka", woodCost = 1, time = 1, cost = 8, spinTime = 40, happiness = 2, description = "Leseni vrtavka za otroke." },
    painted_top = { name = "Poslikana vrtavka", woodCost = 1, paintCost = 1, time = 2, cost = 20, spinTime = 55, prestige = 1, happiness = 3, description = "Poslikana vrtavka z barvami." },
    brass_tipped_top = { name = "Medeninastovrhovna vrtavka", woodCost = 1, brassCost = 1, paintCost = 1, time = 3, cost = 45, spinTime = 68, prestige = 3, happiness = 4, description = "Vrtavka z medeninastim vrhom." },
    silver_banded_top = { name = "Srebrno obrobljena vrtavka", woodCost = 1, silverCost = 1, brassCost = 1, paintCost = 1, time = 5, cost = 110, spinTime = 80, prestige = 6, happiness = 5, description = "Vrtavka s srebrnim obročem za plemiče." },
    gold_inlaid_top = { name = "Zlatointarzirana vrtavka", woodCost = 1, goldCost = 1, silverCost = 1, jewelCost = 1, paintCost = 1, time = 8, cost = 280, spinTime = 92, prestige = 13, happiness = 7, description = "Zlatointarzirana vrtavka za visoke plemiče." },
    royal_grand_top = { name = "Kraljevski veliki vrtavka", woodCost = 2, goldCost = 2, silverCost = 1, jewelCost = 1, pearlCost = 1, paintCost = 2, time = 13, cost = 1100, spinTime = 100, prestige = 35, happiness = 12, description = "Velika kraljevska vrtavka z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Vrtavkarska delavnica", cost = { gold = 220, wood = 120, stone = 150 }, upkeep = 5, qualityBonus = 5 },
    lathe_room = { name = "Stružnica", cost = { gold = 750, wood = 220, stone = 300, wood2 = 8 }, upkeep = 19, qualityBonus = 18 },
    finishing_room = { name = "Dokončevalnica", cost = { gold = 1900, wood = 300, stone = 500, silver = 25, brass = 8 }, upkeep = 48, qualityBonus = 30 },
    royal_top_atelier = { name = "Kraljevski atelje vrtavk", cost = { gold = 8000, wood = 500, stone = 900, gold = 60, jewel = 20 }, upkeep = 160, qualityBonus = 55, prestigeBonus = 40 },
}
TopMaker.woodStock = 18; TopMaker.paintStock = 12; TopMaker.brassStock = 10; TopMaker.silverStock = 8; TopMaker.goldStock = 6; TopMaker.jewelStock = 6; TopMaker.pearlStock = 4
TopMaker.productStock = {}; TopMaker.buildings = {}; TopMaker.maker = nil; TopMaker.activeMaking = {}; TopMaker.totalProducts = 0; TopMaker.dayTimer = 0
function TopMaker.init() TopMaker.woodStock=18; TopMaker.paintStock=12; TopMaker.brassStock=10; TopMaker.silverStock=8; TopMaker.goldStock=6; TopMaker.jewelStock=6; TopMaker.pearlStock=4; TopMaker.productStock={}; TopMaker.buildings={}; TopMaker.maker=nil; TopMaker.activeMaking={}; TopMaker.totalProducts=0; TopMaker.dayTimer=0; print("[TopMaker] Royal Top Maker System initialized (6 products, 4 buildings)") end
function TopMaker.hireMaker(n,s) s=s or math.random(45,85); local c=440+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TopMaker.maker={name=n or ("Vrtavkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrtavkar najet: %s (spretnost: %d)",TopMaker.maker.name,s),"success") end; return true end
function TopMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TopMaker.build(id) local ok,e=TopMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TopMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TopMaker.getQualityBonus() local b=0; for _,bd in ipairs(TopMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TopMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and TopMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.paintCost and TopMaker.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.brassCost and TopMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and TopMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and TopMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and TopMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and TopMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #TopMaker.buildings==0 then return false,"Potrebna delavnica" end; if not TopMaker.maker then return false,"Potreben vrtavkar" end; return true end
function TopMaker.make(pt,qty) qty=qty or 1; local ok,e=TopMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then TopMaker.woodStock=TopMaker.woodStock-d.woodCost*qty end; if d.paintCost then TopMaker.paintStock=TopMaker.paintStock-d.paintCost*qty end; if d.brassCost then TopMaker.brassStock=TopMaker.brassStock-d.brassCost*qty end; if d.silverCost then TopMaker.silverStock=TopMaker.silverStock-d.silverCost*qty end; if d.goldCost then TopMaker.goldStock=TopMaker.goldStock-d.goldCost*qty end; if d.jewelCost then TopMaker.jewelStock=TopMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then TopMaker.pearlStock=TopMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if TopMaker.maker then t=math.max(1,t-math.floor(TopMaker.maker.skill/12)) end; table.insert(TopMaker.activeMaking,{id="top_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,spinTime=d.spinTime or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TopMaker.completeMaking(m) local q=1.0+(TopMaker.getQualityBonus()/100); if TopMaker.maker then q=q+(TopMaker.maker.skill/180) end; q=math.min(2.0,q); TopMaker.productStock[m.productType]=(TopMaker.productStock[m.productType] or 0)+m.quantity; TopMaker.totalProducts=TopMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if TopMaker.maker then TopMaker.maker.itemsMade=TopMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then TopMaker.maker.skill=math.min(100,TopMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vrtavka izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"top.completed",{productName=m.productName,spinTime=m.spinTime,happiness=m.happiness}) end end
function TopMaker.update(dt) if not _G.state then return end; TopMaker.dayTimer=TopMaker.dayTimer+dt; if TopMaker.dayTimer>=30 then TopMaker.dayTimer=0; for i=#TopMaker.activeMaking,1,-1 do local m=TopMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TopMaker.completeMaking(m); table.remove(TopMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TopMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TopMaker.maker then tu=tu+11 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TopMaker.getStats() return {woodStock=TopMaker.woodStock,paintStock=TopMaker.paintStock,brassStock=TopMaker.brassStock,silverStock=TopMaker.silverStock,goldStock=TopMaker.goldStock,jewelStock=TopMaker.jewelStock,pearlStock=TopMaker.pearlStock,productStock=TopMaker.productStock,numBuildings=#TopMaker.buildings,hasMaker=TopMaker.maker~=nil,makerName=TopMaker.maker and TopMaker.maker.name or "—",makerSkill=TopMaker.maker and TopMaker.maker.skill or 0,activeMaking=#TopMaker.activeMaking,totalProducts=TopMaker.totalProducts} end
return TopMaker
