local GlassEngraverMaker = {}
local PRODUCTS = {
    iron_glass_engraver = { name = "Železni rezkar za steklo", ironCost = 3, woodCost = 1, leatherCost = 1, time = 5, cost = 195, prestige = 4, happiness = 2, description = "Železni rezkar za gravuranje stekla." },
    bronze_glass_engraver = { name = "Bronast rezkar za steklo", bronzeCost = 3, ironCost = 1, woodCost = 1, leatherCost = 1, time = 7, cost = 470, prestige = 6, happiness = 3, description = "Bronast rezkar za fino gravuro." },
    silver_glass_engraver = { name = "Srebrni rezkar za steklo", silverCost = 4, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 11, cost = 1130, prestige = 11, happiness = 4, description = "Srebrni rezkar za plemiške steklarje." },
    gilded_glass_engraver = { name = "Pozlačeni rezkar za steklo", goldCost = 1, silverCost = 4, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 15, cost = 2420, prestige = 20, happiness = 5, description = "Pozlačeni rezkar za dvorne steklarje." },
    jewel_set_glass_engraver = { name = "Draguljasti rezkar za steklo", goldCost = 2, silverCost = 4, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 19, cost = 5200, prestige = 36, happiness = 7, description = "Draguljasti rezkar za kraljeve steklarje." },
    royal_sovereign_glass_engraver = { name = "Kraljevski suvereni rezkar za steklo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 26, cost = 11100, prestige = 69, happiness = 13, description = "Suvereni rezkar z biseri za krono." },
}
local BUILDINGS = {
    glassengraver_workshop = { name = "Rezkarska delavnica", cost = { gold = 370, wood = 175, stone = 150, iron = 10 }, upkeep = 7, qualityBonus = 5 },
    glassengraver_house = { name = "Rezkarska hiša", cost = { gold = 1285, wood = 360, stone = 290, silver = 8, iron = 8 }, upkeep = 27, qualityBonus = 18 },
    master_glassengraver_atelier = { name = "Mojstrski rezkarski atelje", cost = { gold = 3200, wood = 420, stone = 545, silver = 39, gold = 8 }, upkeep = 75, qualityBonus = 30 },
    sovereign_glassengraver_palace = { name = "Suverena rezkarska palača", cost = { gold = 13600, wood = 650, stone = 860, gold = 88, jewel = 20 }, upkeep = 263, qualityBonus = 55, prestigeBonus = 50 },
}
GlassEngraverMaker.ironStock = 14; GlassEngraverMaker.bronzeStock = 10; GlassEngraverMaker.woodStock = 12; GlassEngraverMaker.leatherStock = 10; GlassEngraverMaker.silverStock = 10; GlassEngraverMaker.goldStock = 6; GlassEngraverMaker.jewelStock = 4; GlassEngraverMaker.pearlStock = 4
GlassEngraverMaker.productStock = {}; GlassEngraverMaker.buildings = {}; GlassEngraverMaker.maker = nil; GlassEngraverMaker.activeMaking = {}; GlassEngraverMaker.totalProducts = 0; GlassEngraverMaker.dayTimer = 0
function GlassEngraverMaker.init() GlassEngraverMaker.ironStock=14; GlassEngraverMaker.bronzeStock=10; GlassEngraverMaker.woodStock=12; GlassEngraverMaker.leatherStock=10; GlassEngraverMaker.silverStock=10; GlassEngraverMaker.goldStock=6; GlassEngraverMaker.jewelStock=4; GlassEngraverMaker.pearlStock=4; GlassEngraverMaker.productStock={}; GlassEngraverMaker.buildings={}; GlassEngraverMaker.maker=nil; GlassEngraverMaker.activeMaking={}; GlassEngraverMaker.totalProducts=0; GlassEngraverMaker.dayTimer=0; print("[GlassEngraverMaker] Royal Glass Engraver Maker System initialized (6 products, 4 buildings)") end
function GlassEngraverMaker.hireMaker(n,s) s=s or math.random(55,90); local c=595+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassEngraverMaker.maker={name=n or ("Rezkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rezkar najet: %s (spretnost: %d)",GlassEngraverMaker.maker.name,s),"success") end; return true end
function GlassEngraverMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassEngraverMaker.build(id) local ok,e=GlassEngraverMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassEngraverMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassEngraverMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassEngraverMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassEngraverMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassEngraverMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassEngraverMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassEngraverMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassEngraverMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassEngraverMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassEngraverMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassEngraverMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassEngraverMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassEngraverMaker.buildings==0 then return false,"Potrebna rezkarska delavnica" end; if not GlassEngraverMaker.maker then return false,"Potreben rezkar" end; return true end
function GlassEngraverMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassEngraverMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassEngraverMaker.ironStock=GlassEngraverMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassEngraverMaker.bronzeStock=GlassEngraverMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassEngraverMaker.woodStock=GlassEngraverMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassEngraverMaker.leatherStock=GlassEngraverMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassEngraverMaker.silverStock=GlassEngraverMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassEngraverMaker.goldStock=GlassEngraverMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassEngraverMaker.jewelStock=GlassEngraverMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassEngraverMaker.pearlStock=GlassEngraverMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassEngraverMaker.maker then t=math.max(1,t-math.floor(GlassEngraverMaker.maker.skill/13)) end; table.insert(GlassEngraverMaker.activeMaking,{id="glassengraver_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassEngraverMaker.completeMaking(m) local q=1.0+(GlassEngraverMaker.getQualityBonus()/100); if GlassEngraverMaker.maker then q=q+(GlassEngraverMaker.maker.skill/140) end; q=math.min(2.5,q); GlassEngraverMaker.productStock[m.productType]=(GlassEngraverMaker.productStock[m.productType] or 0)+m.quantity; GlassEngraverMaker.totalProducts=GlassEngraverMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassEngraverMaker.maker then GlassEngraverMaker.maker.itemsMade=GlassEngraverMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassEngraverMaker.maker.skill=math.min(100,GlassEngraverMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rezkar izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glassengraver.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassEngraverMaker.update(dt) if not _G.state then return end; GlassEngraverMaker.dayTimer=GlassEngraverMaker.dayTimer+dt; if GlassEngraverMaker.dayTimer>=30 then GlassEngraverMaker.dayTimer=0; for i=#GlassEngraverMaker.activeMaking,1,-1 do local m=GlassEngraverMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassEngraverMaker.completeMaking(m); table.remove(GlassEngraverMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassEngraverMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassEngraverMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassEngraverMaker.getStats() return {ironStock=GlassEngraverMaker.ironStock,bronzeStock=GlassEngraverMaker.bronzeStock,woodStock=GlassEngraverMaker.woodStock,leatherStock=GlassEngraverMaker.leatherStock,silverStock=GlassEngraverMaker.silverStock,goldStock=GlassEngraverMaker.goldStock,jewelStock=GlassEngraverMaker.jewelStock,pearlStock=GlassEngraverMaker.pearlStock,productStock=GlassEngraverMaker.productStock,numBuildings=#GlassEngraverMaker.buildings,hasMaker=GlassEngraverMaker.maker~=nil,makerName=GlassEngraverMaker.maker and GlassEngraverMaker.maker.name or "—",makerSkill=GlassEngraverMaker.maker and GlassEngraverMaker.maker.skill or 0,activeMaking=#GlassEngraverMaker.activeMaking,totalProducts=GlassEngraverMaker.totalProducts} end
return GlassEngraverMaker
