local BathFixtureMaker = {}
local PRODUCTS = {
    simple_stone_bath = { name = "Preprosta kamnita kopalna kad", stoneCost = 4, clayCost = 1, time = 6, cost = 200, happiness = 2, health = 8, description = "Preprosta kamnita kopalna kad za umivanje." },
    marble_bath_fixture = { name = "Marmornata kopalna oprema", marbleCost = 3, stoneCost = 2, clayCost = 1, time = 9, cost = 480, happiness = 3, health = 14, prestige = 3, description = "Marmornata kopalna oprema za trgovce." },
    silver_faucet_bath = { name = "Srebrnopipna kopalna oprema", marbleCost = 3, silverCost = 1, stoneCost = 2, clayCost = 1, time = 13, cost = 1100, happiness = 4, health = 20, prestige = 8, description = "Srebrnopipna kopalna oprema za plemiče." },
    gold_trimmed_bath = { name = "Zlatookrasna kopalna oprema", marbleCost = 3, goldCost = 1, silverCost = 1, stoneCost = 2, clayCost = 1, time = 17, cost = 2500, happiness = 5, health = 28, prestige = 16, description = "Zlatookrasna kopalna oprema za visoke plemiče." },
    jewel_set_bath = { name = "Draguljasta kopalna oprema", marbleCost = 3, goldCost = 1, silverCost = 1, stoneCost = 2, clayCost = 1, jewelCost = 1, time = 21, cost = 5200, happiness = 7, health = 38, prestige = 30, description = "Kopalna oprema z draguljem za visoko plemstvo." },
    royal_grand_bath = { name = "Kraljevski veliki kopalna oprema", marbleCost = 4, goldCost = 2, silverCost = 2, stoneCost = 2, clayCost = 1, jewelCost = 2, pearlCost = 2, time = 28, cost = 11000, happiness = 13, health = 55, prestige = 62, description = "Velika kraljevska kopalna oprema z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    bath_workshop = { name = "Kopalna delavnica", cost = { gold = 320, wood = 140, stone = 180, marble = 4 }, upkeep = 7, qualityBonus = 5 },
    plumbing_loft = { name = "Vodovodna podstrešje", cost = { gold = 1100, wood = 280, stone = 320, silver = 6, clay = 8 }, upkeep = 26, qualityBonus = 18 },
    master_bath_atelier = { name = "Mojstrski kopalni atelje", cost = { gold = 2900, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 68, qualityBonus = 30 },
    royal_bath_palace = { name = "Kraljevska kopalna palača", cost = { gold = 12500, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 250, qualityBonus = 55, prestigeBonus = 50 },
}
BathFixtureMaker.stoneStock = 20; BathFixtureMaker.marbleStock = 12; BathFixtureMaker.clayStock = 10; BathFixtureMaker.silverStock = 6; BathFixtureMaker.goldStock = 6; BathFixtureMaker.jewelStock = 4; BathFixtureMaker.pearlStock = 4
BathFixtureMaker.productStock = {}; BathFixtureMaker.buildings = {}; BathFixtureMaker.maker = nil; BathFixtureMaker.activeMaking = {}; BathFixtureMaker.totalProducts = 0; BathFixtureMaker.dayTimer = 0
function BathFixtureMaker.init() BathFixtureMaker.stoneStock=20; BathFixtureMaker.marbleStock=12; BathFixtureMaker.clayStock=10; BathFixtureMaker.silverStock=6; BathFixtureMaker.goldStock=6; BathFixtureMaker.jewelStock=4; BathFixtureMaker.pearlStock=4; BathFixtureMaker.productStock={}; BathFixtureMaker.buildings={}; BathFixtureMaker.maker=nil; BathFixtureMaker.activeMaking={}; BathFixtureMaker.totalProducts=0; BathFixtureMaker.dayTimer=0; print("[BathFixtureMaker] Royal Bath Fixture Maker System initialized (6 products, 4 buildings)") end
function BathFixtureMaker.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BathFixtureMaker.maker={name=n or ("Kopalni opremljevalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kopalni opremljevalec najet: %s (spretnost: %d)",BathFixtureMaker.maker.name,s),"success") end; return true end
function BathFixtureMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BathFixtureMaker.build(id) local ok,e=BathFixtureMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BathFixtureMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BathFixtureMaker.getQualityBonus() local b=0; for _,bd in ipairs(BathFixtureMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BathFixtureMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.stoneCost and BathFixtureMaker.stoneStock<(d.stoneCost or 0) then return false,"Premalo kamna" end; if d.marbleCost and BathFixtureMaker.marbleStock<(d.marbleCost or 0) then return false,"Premalo marmorja" end; if d.clayCost and BathFixtureMaker.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.silverCost and BathFixtureMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BathFixtureMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BathFixtureMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BathFixtureMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BathFixtureMaker.buildings==0 then return false,"Potrebna kopalna delavnica" end; if not BathFixtureMaker.maker then return false,"Potreben kopalni opremljevalec" end; return true end
function BathFixtureMaker.make(pt,qty) qty=qty or 1; local ok,e=BathFixtureMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.stoneCost then BathFixtureMaker.stoneStock=BathFixtureMaker.stoneStock-d.stoneCost*qty end; if d.marbleCost then BathFixtureMaker.marbleStock=BathFixtureMaker.marbleStock-d.marbleCost*qty end; if d.clayCost then BathFixtureMaker.clayStock=BathFixtureMaker.clayStock-d.clayCost*qty end; if d.silverCost then BathFixtureMaker.silverStock=BathFixtureMaker.silverStock-d.silverCost*qty end; if d.goldCost then BathFixtureMaker.goldStock=BathFixtureMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BathFixtureMaker.jewelStock=BathFixtureMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BathFixtureMaker.pearlStock=BathFixtureMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BathFixtureMaker.maker then t=math.max(1,t-math.floor(BathFixtureMaker.maker.skill/12)) end; table.insert(BathFixtureMaker.activeMaking,{id="bath_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,health=d.health or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BathFixtureMaker.completeMaking(m) local q=1.0+(BathFixtureMaker.getQualityBonus()/100); if BathFixtureMaker.maker then q=q+(BathFixtureMaker.maker.skill/140) end; q=math.min(2.5,q); BathFixtureMaker.productStock[m.productType]=(BathFixtureMaker.productStock[m.productType] or 0)+m.quantity; BathFixtureMaker.totalProducts=BathFixtureMaker.totalProducts+m.quantity; if m.health>0 and _G.state then _G.state.health=(_G.state.health or 0)+m.health end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BathFixtureMaker.maker then BathFixtureMaker.maker.itemsMade=BathFixtureMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BathFixtureMaker.maker.skill=math.min(100,BathFixtureMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kopalna oprema izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bath.completed",{productName=m.productName,health=m.health,prestige=m.prestige,happiness=m.happiness}) end end
function BathFixtureMaker.update(dt) if not _G.state then return end; BathFixtureMaker.dayTimer=BathFixtureMaker.dayTimer+dt; if BathFixtureMaker.dayTimer>=30 then BathFixtureMaker.dayTimer=0; for i=#BathFixtureMaker.activeMaking,1,-1 do local m=BathFixtureMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BathFixtureMaker.completeMaking(m); table.remove(BathFixtureMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BathFixtureMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BathFixtureMaker.maker then tu=tu+16 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BathFixtureMaker.getStats() return {stoneStock=BathFixtureMaker.stoneStock,marbleStock=BathFixtureMaker.marbleStock,clayStock=BathFixtureMaker.clayStock,silverStock=BathFixtureMaker.silverStock,goldStock=BathFixtureMaker.goldStock,jewelStock=BathFixtureMaker.jewelStock,pearlStock=BathFixtureMaker.pearlStock,productStock=BathFixtureMaker.productStock,numBuildings=#BathFixtureMaker.buildings,hasMaker=BathFixtureMaker.maker~=nil,makerName=BathFixtureMaker.maker and BathFixtureMaker.maker.name or "—",makerSkill=BathFixtureMaker.maker and BathFixtureMaker.maker.skill or 0,activeMaking=#BathFixtureMaker.activeMaking,totalProducts=BathFixtureMaker.totalProducts} end
return BathFixtureMaker
