local KitchenKnifeMaker = {}
local PRODUCTS = {
    simple_iron_kitchen_knife = { name = "Preprost železni kuhinjski nož", ironCost = 1, woodCost = 1, time = 2, cost = 30, culinary = 18, happiness = 1, description = "Preprost železni kuhinjski nož za kuhinjo." },
    steel_blade_chef_knife = { name = "Jeklenorezni kuharski nož", ironCost = 2, woodCost = 1, leatherCost = 1, time = 5, cost = 100, culinary = 32, happiness = 1, prestige = 2, description = "Jeklenorezni kuharski nož za trgovce." },
    silver_handle_carving_knife = { name = "Srebrnorokavi rezilni nož", ironCost = 2, silverCost = 1, woodCost = 1, leatherCost = 1, time = 8, cost = 260, culinary = 48, happiness = 2, prestige = 6, description = "Srebrnorokavi rezilni nož za plemiče." },
    gold_trimmed_fillet_knife = { name = "Zlatookrasni filejni nož", ironCost = 2, goldCost = 1, silverCost = 1, woodCost = 1, leatherCost = 1, time = 12, cost = 620, culinary = 62, happiness = 3, prestige = 14, description = "Zlatookrasni filejni nož za visoke plemiče." },
    jewel_pommel_ceremonial_knife = { name = "Draguljnogrbi slovesnostni nož", ironCost = 2, goldCost = 2, silverCost = 1, woodCost = 1, leatherCost = 1, jewelCost = 1, time = 16, cost = 1400, culinary = 78, happiness = 5, prestige = 27, description = "Slovesnostni nož z draguljnim grbičem za visoko plemstvo." },
    royal_grand_carving_set = { name = "Kraljevski veliki rezilni set", ironCost = 3, goldCost = 3, silverCost = 2, woodCost = 2, leatherCost = 1, jewelCost = 2, pearlCost = 2, time = 23, cost = 3200, culinary = 92, happiness = 12, prestige = 56, description = "Veliki kraljevski rezilni set z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    knife_workshop = { name = "Nožniška delavnica", cost = { gold = 220, wood = 120, stone = 100, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    cutlery_loft = { name = "Priborno podstrešje", cost = { gold = 800, wood = 240, stone = 220, silver = 6, leather = 6 }, upkeep = 18, qualityBonus = 18 },
    master_bladesmith_atelier = { name = "Mojstrski rezbarski atelje", cost = { gold = 2300, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 52, qualityBonus = 30 },
    royal_cutlery_palace = { name = "Kraljevska nožniška palača", cost = { gold = 9500, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 50 },
}
KitchenKnifeMaker.ironStock = 16; KitchenKnifeMaker.woodStock = 12; KitchenKnifeMaker.leatherStock = 10; KitchenKnifeMaker.silverStock = 6; KitchenKnifeMaker.goldStock = 6; KitchenKnifeMaker.jewelStock = 4; KitchenKnifeMaker.pearlStock = 4
KitchenKnifeMaker.productStock = {}; KitchenKnifeMaker.buildings = {}; KitchenKnifeMaker.maker = nil; KitchenKnifeMaker.activeMaking = {}; KitchenKnifeMaker.totalProducts = 0; KitchenKnifeMaker.dayTimer = 0
function KitchenKnifeMaker.init() KitchenKnifeMaker.ironStock=16; KitchenKnifeMaker.woodStock=12; KitchenKnifeMaker.leatherStock=10; KitchenKnifeMaker.silverStock=6; KitchenKnifeMaker.goldStock=6; KitchenKnifeMaker.jewelStock=4; KitchenKnifeMaker.pearlStock=4; KitchenKnifeMaker.productStock={}; KitchenKnifeMaker.buildings={}; KitchenKnifeMaker.maker=nil; KitchenKnifeMaker.activeMaking={}; KitchenKnifeMaker.totalProducts=0; KitchenKnifeMaker.dayTimer=0; print("[KitchenKnifeMaker] Royal Kitchen Knife Maker System initialized (6 products, 4 buildings)") end
function KitchenKnifeMaker.hireMaker(n,s) s=s or math.random(55,90); local c=480+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; KitchenKnifeMaker.maker={name=n or ("Nožničar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Nožničar najet: %s (spretnost: %d)",KitchenKnifeMaker.maker.name,s),"success") end; return true end
function KitchenKnifeMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function KitchenKnifeMaker.build(id) local ok,e=KitchenKnifeMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(KitchenKnifeMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function KitchenKnifeMaker.getQualityBonus() local b=0; for _,bd in ipairs(KitchenKnifeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function KitchenKnifeMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and KitchenKnifeMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.woodCost and KitchenKnifeMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and KitchenKnifeMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and KitchenKnifeMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and KitchenKnifeMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and KitchenKnifeMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and KitchenKnifeMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #KitchenKnifeMaker.buildings==0 then return false,"Potrebna nožniška delavnica" end; if not KitchenKnifeMaker.maker then return false,"Potreben nožničar" end; return true end
function KitchenKnifeMaker.make(pt,qty) qty=qty or 1; local ok,e=KitchenKnifeMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then KitchenKnifeMaker.ironStock=KitchenKnifeMaker.ironStock-d.ironCost*qty end; if d.woodCost then KitchenKnifeMaker.woodStock=KitchenKnifeMaker.woodStock-d.woodCost*qty end; if d.leatherCost then KitchenKnifeMaker.leatherStock=KitchenKnifeMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then KitchenKnifeMaker.silverStock=KitchenKnifeMaker.silverStock-d.silverCost*qty end; if d.goldCost then KitchenKnifeMaker.goldStock=KitchenKnifeMaker.goldStock-d.goldCost*qty end; if d.jewelCost then KitchenKnifeMaker.jewelStock=KitchenKnifeMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then KitchenKnifeMaker.pearlStock=KitchenKnifeMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if KitchenKnifeMaker.maker then t=math.max(1,t-math.floor(KitchenKnifeMaker.maker.skill/13)) end; table.insert(KitchenKnifeMaker.activeMaking,{id="knife_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,culinary=d.culinary or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function KitchenKnifeMaker.completeMaking(m) local q=1.0+(KitchenKnifeMaker.getQualityBonus()/100); if KitchenKnifeMaker.maker then q=q+(KitchenKnifeMaker.maker.skill/150) end; q=math.min(2.4,q); KitchenKnifeMaker.productStock[m.productType]=(KitchenKnifeMaker.productStock[m.productType] or 0)+m.quantity; KitchenKnifeMaker.totalProducts=KitchenKnifeMaker.totalProducts+m.quantity; if m.culinary>0 and _G.state then _G.state.culinary=(_G.state.culinary or 0)+m.culinary end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if KitchenKnifeMaker.maker then KitchenKnifeMaker.maker.itemsMade=KitchenKnifeMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then KitchenKnifeMaker.maker.skill=math.min(100,KitchenKnifeMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Nož izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"knife.completed",{productName=m.productName,culinary=m.culinary,prestige=m.prestige,happiness=m.happiness}) end end
function KitchenKnifeMaker.update(dt) if not _G.state then return end; KitchenKnifeMaker.dayTimer=KitchenKnifeMaker.dayTimer+dt; if KitchenKnifeMaker.dayTimer>=30 then KitchenKnifeMaker.dayTimer=0; for i=#KitchenKnifeMaker.activeMaking,1,-1 do local m=KitchenKnifeMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then KitchenKnifeMaker.completeMaking(m); table.remove(KitchenKnifeMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(KitchenKnifeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if KitchenKnifeMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function KitchenKnifeMaker.getStats() return {ironStock=KitchenKnifeMaker.ironStock,woodStock=KitchenKnifeMaker.woodStock,leatherStock=KitchenKnifeMaker.leatherStock,silverStock=KitchenKnifeMaker.silverStock,goldStock=KitchenKnifeMaker.goldStock,jewelStock=KitchenKnifeMaker.jewelStock,pearlStock=KitchenKnifeMaker.pearlStock,productStock=KitchenKnifeMaker.productStock,numBuildings=#KitchenKnifeMaker.buildings,hasMaker=KitchenKnifeMaker.maker~=nil,makerName=KitchenKnifeMaker.maker and KitchenKnifeMaker.maker.name or "—",makerSkill=KitchenKnifeMaker.maker and KitchenKnifeMaker.maker.skill or 0,activeMaking=#KitchenKnifeMaker.activeMaking,totalProducts=KitchenKnifeMaker.totalProducts} end
return KitchenKnifeMaker
