local TongsRestMaker = {}
local PRODUCTS = {
    iron_tongsrest = { name = "Železni stojalo za klesce", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni stojalo za klesce za kovace." },
    bronze_tongsrest = { name = "Bronast stojalo za klesce", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast stojalo za klesce za kovace." },
    silver_tongsrest = { name = "Srebrn stojalo za klesce", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn stojalo za klesce za kovace." },
    gilded_tongsrest = { name = "Pozlačen stojalo za klesce", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen stojalo za klesce za kovace." },
    jewel_set_tongsrest = { name = "Draguljast stojalo za klesce", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast stojalo za klesce za kovace." },
    royal_sovereign_tongsrest = { name = "Kraljevski suveren stojalo za klesce", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren stojalo za klesce z biseri za krono." },
}
local BUILDINGS = {
    tongsrest_workshop = { name = "Tongsrest delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    tongsrest_house = { name = "Tongsrest hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_tongsrest_atelier = { name = "Mojstrski tongsrest atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_tongsrest_palace = { name = "Suverena tongsrest palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
TongsRestMaker.ironStock = 14; TongsRestMaker.bronzeStock = 12; TongsRestMaker.woodStock = 14; TongsRestMaker.leatherStock = 8; TongsRestMaker.silverStock = 8; TongsRestMaker.goldStock = 6; TongsRestMaker.jewelStock = 4; TongsRestMaker.pearlStock = 4
TongsRestMaker.productStock = {}; TongsRestMaker.buildings = {}; TongsRestMaker.maker = nil; TongsRestMaker.activeMaking = {}; TongsRestMaker.totalProducts = 0; TongsRestMaker.dayTimer = 0
function TongsRestMaker.init() TongsRestMaker.ironStock=14; TongsRestMaker.bronzeStock=12; TongsRestMaker.woodStock=14; TongsRestMaker.leatherStock=8; TongsRestMaker.silverStock=8; TongsRestMaker.goldStock=6; TongsRestMaker.jewelStock=4; TongsRestMaker.pearlStock=4; TongsRestMaker.productStock={}; TongsRestMaker.buildings={}; TongsRestMaker.maker=nil; TongsRestMaker.activeMaking={}; TongsRestMaker.totalProducts=0; TongsRestMaker.dayTimer=0; print("[TongsRestMaker] Royal Tongs Rest Maker System initialized (6 products, 4 buildings)") end
function TongsRestMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; TongsRestMaker.maker={name=n or ("Stojalar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stojalar najet: %s (spretnost: %d)",TongsRestMaker.maker.name,s),"success") end; return true end
function TongsRestMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function TongsRestMaker.build(id) local ok,e=TongsRestMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(TongsRestMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function TongsRestMaker.getQualityBonus() local b=0; for _,bd in ipairs(TongsRestMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function TongsRestMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and TongsRestMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and TongsRestMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and TongsRestMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and TongsRestMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and TongsRestMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and TongsRestMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and TongsRestMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and TongsRestMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #TongsRestMaker.buildings==0 then return false,"Potrebna stojalna delavnica" end; if not TongsRestMaker.maker then return false,"Potreben stojalar" end; return true end
function TongsRestMaker.make(pt,qty) qty=qty or 1; local ok,e=TongsRestMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then TongsRestMaker.ironStock=TongsRestMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then TongsRestMaker.bronzeStock=TongsRestMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then TongsRestMaker.woodStock=TongsRestMaker.woodStock-d.woodCost*qty end; if d.leatherCost then TongsRestMaker.leatherStock=TongsRestMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then TongsRestMaker.silverStock=TongsRestMaker.silverStock-d.silverCost*qty end; if d.goldCost then TongsRestMaker.goldStock=TongsRestMaker.goldStock-d.goldCost*qty end; if d.jewelCost then TongsRestMaker.jewelStock=TongsRestMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then TongsRestMaker.pearlStock=TongsRestMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if TongsRestMaker.maker then t=math.max(1,t-math.floor(TongsRestMaker.maker.skill/13)) end; table.insert(TongsRestMaker.activeMaking,{id="${MAKER_LOWER}_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function TongsRestMaker.completeMaking(m) local q=1.0+(TongsRestMaker.getQualityBonus()/100); if TongsRestMaker.maker then q=q+(TongsRestMaker.maker.skill/140) end; q=math.min(2.5,q); TongsRestMaker.productStock[m.productType]=(TongsRestMaker.productStock[m.productType] or 0)+m.quantity; TongsRestMaker.totalProducts=TongsRestMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if TongsRestMaker.maker then TongsRestMaker.maker.itemsMade=TongsRestMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then TongsRestMaker.maker.skill=math.min(100,TongsRestMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stojalo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"${MAKER_LOWER}.completed",{productName=m.productName,prestige=m.prestige,happiness:m.happiness}) end end
function TongsRestMaker.update(dt) if not _G.state then return end; TongsRestMaker.dayTimer=TongsRestMaker.dayTimer+dt; if TongsRestMaker.dayTimer>=30 then TongsRestMaker.dayTimer=0; for i=#TongsRestMaker.activeMaking,1,-1 do local m=TongsRestMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then TongsRestMaker.completeMaking(m); table.remove(TongsRestMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(TongsRestMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if TongsRestMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function TongsRestMaker.getStats() return {ironStock=TongsRestMaker.ironStock,bronzeStock=TongsRestMaker.bronzeStock,woodStock=TongsRestMaker.woodStock,leatherStock=TongsRestMaker.leatherStock,silverStock=TongsRestMaker.silverStock,goldStock=TongsRestMaker.goldStock,jewelStock=TongsRestMaker.jewelStock,pearlStock=TongsRestMaker.pearlStock,productStock=TongsRestMaker.productStock,numBuildings=#TongsRestMaker.buildings,hasMaker=TongsRestMaker.maker~=nil,makerName=TongsRestMaker.maker and TongsRestMaker.maker.name or "—",makerSkill=TongsRestMaker.maker and TongsRestMaker.maker.skill or 0,activeMaking=#TongsRestMaker.activeMaking,totalProducts=TongsRestMaker.totalProducts} end
return TongsRestMaker
