local PouringLadleSkimmerSieveMaker = {}
local PRODUCTS = {
    iron_pouringladleskimmersieve = { name = "Železni sitana za strgalce zajemalk", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni sitana za strgalce zajemalk za livarje." },
    bronze_pouringladleskimmersieve = { name = "Bronast sitana za strgalce zajemalk", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast sitana za strgalce zajemalk za livarje." },
    silver_pouringladleskimmersieve = { name = "Srebrn sitana za strgalce zajemalk", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn sitana za strgalce zajemalk za livarje." },
    gilded_pouringladleskimmersieve = { name = "Pozlačen sitana za strgalce zajemalk", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen sitana za strgalce zajemalk za livarje." },
    jewel_set_pouringladleskimmersieve = { name = "Draguljast sitana za strgalce zajemalk", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast sitana za strgalce zajemalk za livarje." },
    royal_sovereign_pouringladleskimmersieve = { name = "Kraljevski suveren sitana za strgalce zajemalk", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren sitana za strgalce zajemalk z biseri za krono." },
}
local BUILDINGS = {
    pouringladleskimmersieve_workshop = { name = "Pouringladleskimmersieve delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    pouringladleskimmersieve_house = { name = "Pouringladleskimmersieve hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_pouringladleskimmersieve_atelier = { name = "Mojstrski pouringladleskimmersieve atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_pouringladleskimmersieve_palace = { name = "Suverena pouringladleskimmersieve palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
PouringLadleSkimmerSieveMaker.ironStock=12; PouringLadleSkimmerSieveMaker.bronzeStock=10; PouringLadleSkimmerSieveMaker.woodStock=14; PouringLadleSkimmerSieveMaker.leatherStock=10; PouringLadleSkimmerSieveMaker.silverStock=8; PouringLadleSkimmerSieveMaker.goldStock=6; PouringLadleSkimmerSieveMaker.jewelStock=4; PouringLadleSkimmerSieveMaker.pearlStock=4
PouringLadleSkimmerSieveMaker.productStock = {}; PouringLadleSkimmerSieveMaker.buildings = {}; PouringLadleSkimmerSieveMaker.maker = nil; PouringLadleSkimmerSieveMaker.activeMaking = {}; PouringLadleSkimmerSieveMaker.totalProducts = 0; PouringLadleSkimmerSieveMaker.dayTimer = 0
function PouringLadleSkimmerSieveMaker.init() PouringLadleSkimmerSieveMaker.ironStock=12; PouringLadleSkimmerSieveMaker.bronzeStock=10; PouringLadleSkimmerSieveMaker.woodStock=14; PouringLadleSkimmerSieveMaker.leatherStock=10; PouringLadleSkimmerSieveMaker.silverStock=8; PouringLadleSkimmerSieveMaker.goldStock=6; PouringLadleSkimmerSieveMaker.jewelStock=4; PouringLadleSkimmerSieveMaker.pearlStock=4; PouringLadleSkimmerSieveMaker.productStock={}; PouringLadleSkimmerSieveMaker.buildings={}; PouringLadleSkimmerSieveMaker.maker=nil; PouringLadleSkimmerSieveMaker.activeMaking={}; PouringLadleSkimmerSieveMaker.totalProducts=0; PouringLadleSkimmerSieveMaker.dayTimer=0; print("[PouringLadleSkimmerSieveMaker] Royal Pouring Ladle Skimmer Sieve Maker System initialized (6 products, 4 buildings)") end
function PouringLadleSkimmerSieveMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PouringLadleSkimmerSieveMaker.maker={name=n or ("Sitnikar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sitnikar najet: %s (spretnost: %d)",PouringLadleSkimmerSieveMaker.maker.name,s),"success") end; return true end
function PouringLadleSkimmerSieveMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PouringLadleSkimmerSieveMaker.build(id) local ok,e=PouringLadleSkimmerSieveMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PouringLadleSkimmerSieveMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PouringLadleSkimmerSieveMaker.getQualityBonus() local b=0; for _,bd in ipairs(PouringLadleSkimmerSieveMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PouringLadleSkimmerSieveMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PouringLadleSkimmerSieveMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and PouringLadleSkimmerSieveMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and PouringLadleSkimmerSieveMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PouringLadleSkimmerSieveMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PouringLadleSkimmerSieveMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PouringLadleSkimmerSieveMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PouringLadleSkimmerSieveMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PouringLadleSkimmerSieveMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PouringLadleSkimmerSieveMaker.buildings==0 then return false,"Potrebna sitnična delavnica" end; if not PouringLadleSkimmerSieveMaker.maker then return false,"Potreben sitnikar" end; return true end
function PouringLadleSkimmerSieveMaker.make(pt,qty) qty=qty or 1; local ok,e=PouringLadleSkimmerSieveMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PouringLadleSkimmerSieveMaker.ironStock=PouringLadleSkimmerSieveMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then PouringLadleSkimmerSieveMaker.bronzeStock=PouringLadleSkimmerSieveMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then PouringLadleSkimmerSieveMaker.woodStock=PouringLadleSkimmerSieveMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PouringLadleSkimmerSieveMaker.leatherStock=PouringLadleSkimmerSieveMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then PouringLadleSkimmerSieveMaker.silverStock=PouringLadleSkimmerSieveMaker.silverStock-d.silverCost*qty end; if d.goldCost then PouringLadleSkimmerSieveMaker.goldStock=PouringLadleSkimmerSieveMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PouringLadleSkimmerSieveMaker.jewelStock=PouringLadleSkimmerSieveMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PouringLadleSkimmerSieveMaker.pearlStock=PouringLadleSkimmerSieveMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PouringLadleSkimmerSieveMaker.maker then t=math.max(1,t-math.floor(PouringLadleSkimmerSieveMaker.maker.skill/13)) end; table.insert(PouringLadleSkimmerSieveMaker.activeMaking,{id="pouringladleskimmersieve_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PouringLadleSkimmerSieveMaker.completeMaking(m) local q=1.0+(PouringLadleSkimmerSieveMaker.getQualityBonus()/100); if PouringLadleSkimmerSieveMaker.maker then q=q+(PouringLadleSkimmerSieveMaker.maker.skill/140) end; q=math.min(2.5,q); PouringLadleSkimmerSieveMaker.productStock[m.productType]=(PouringLadleSkimmerSieveMaker.productStock[m.productType] or 0)+m.quantity; PouringLadleSkimmerSieveMaker.totalProducts=PouringLadleSkimmerSieveMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PouringLadleSkimmerSieveMaker.maker then PouringLadleSkimmerSieveMaker.maker.itemsMade=PouringLadleSkimmerSieveMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PouringLadleSkimmerSieveMaker.maker.skill=math.min(100,PouringLadleSkimmerSieveMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sito izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"pouringladleskimmersieve.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function PouringLadleSkimmerSieveMaker.update(dt) if not _G.state then return end; PouringLadleSkimmerSieveMaker.dayTimer=PouringLadleSkimmerSieveMaker.dayTimer+dt; if PouringLadleSkimmerSieveMaker.dayTimer>=30 then PouringLadleSkimmerSieveMaker.dayTimer=0; for i=#PouringLadleSkimmerSieveMaker.activeMaking,1,-1 do local m=PouringLadleSkimmerSieveMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PouringLadleSkimmerSieveMaker.completeMaking(m); table.remove(PouringLadleSkimmerSieveMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PouringLadleSkimmerSieveMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PouringLadleSkimmerSieveMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PouringLadleSkimmerSieveMaker.getStats() return {ironStock=PouringLadleSkimmerSieveMaker.ironStock,bronzeStock=PouringLadleSkimmerSieveMaker.bronzeStock,woodStock=PouringLadleSkimmerSieveMaker.woodStock,leatherStock=PouringLadleSkimmerSieveMaker.leatherStock,silverStock=PouringLadleSkimmerSieveMaker.silverStock,goldStock=PouringLadleSkimmerSieveMaker.goldStock,jewelStock=PouringLadleSkimmerSieveMaker.jewelStock,pearlStock=PouringLadleSkimmerSieveMaker.pearlStock,productStock=PouringLadleSkimmerSieveMaker.productStock,numBuildings=#PouringLadleSkimmerSieveMaker.buildings,hasMaker=PouringLadleSkimmerSieveMaker.maker~=nil,makerName=PouringLadleSkimmerSieveMaker.maker and PouringLadleSkimmerSieveMaker.maker.name or "—",makerSkill=PouringLadleSkimmerSieveMaker.maker and PouringLadleSkimmerSieveMaker.maker.skill or 0,activeMaking=#PouringLadleSkimmerSieveMaker.activeMaking,totalProducts=PouringLadleSkimmerSieveMaker.totalProducts} end
return PouringLadleSkimmerSieveMaker
