local ForgeAshRiddleMaker = {}
local PRODUCTS = {
    iron_forgeashriddle = { name = "Železni sitana za pepel", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni sitana za pepel za kovace." },
    bronze_forgeashriddle = { name = "Bronast sitana za pepel", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast sitana za pepel za kovace." },
    silver_forgeashriddle = { name = "Srebrn sitana za pepel", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn sitana za pepel za kovace." },
    gilded_forgeashriddle = { name = "Pozlačen sitana za pepel", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen sitana za pepel za kovace." },
    jewel_set_forgeashriddle = { name = "Draguljast sitana za pepel", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast sitana za pepel za kovace." },
    royal_sovereign_forgeashriddle = { name = "Kraljevski suveren sitana za pepel", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren sitana za pepel z biseri za krono." },
}
local BUILDINGS = {
    forgeashriddle_workshop = { name = "Forgeashriddle delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    forgeashriddle_house = { name = "Forgeashriddle hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_forgeashriddle_atelier = { name = "Mojstrski forgeashriddle atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_forgeashriddle_palace = { name = "Suverena forgeashriddle palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
ForgeAshRiddleMaker.ironStock=12; ForgeAshRiddleMaker.bronzeStock=10; ForgeAshRiddleMaker.woodStock=16; ForgeAshRiddleMaker.leatherStock=10; ForgeAshRiddleMaker.silverStock=8; ForgeAshRiddleMaker.goldStock=6; ForgeAshRiddleMaker.jewelStock=4; ForgeAshRiddleMaker.pearlStock=4
ForgeAshRiddleMaker.productStock = {}; ForgeAshRiddleMaker.buildings = {}; ForgeAshRiddleMaker.maker = nil; ForgeAshRiddleMaker.activeMaking = {}; ForgeAshRiddleMaker.totalProducts = 0; ForgeAshRiddleMaker.dayTimer = 0
function ForgeAshRiddleMaker.init() ForgeAshRiddleMaker.ironStock=12; ForgeAshRiddleMaker.bronzeStock=10; ForgeAshRiddleMaker.woodStock=16; ForgeAshRiddleMaker.leatherStock=10; ForgeAshRiddleMaker.silverStock=8; ForgeAshRiddleMaker.goldStock=6; ForgeAshRiddleMaker.jewelStock=4; ForgeAshRiddleMaker.pearlStock=4; ForgeAshRiddleMaker.productStock={}; ForgeAshRiddleMaker.buildings={}; ForgeAshRiddleMaker.maker=nil; ForgeAshRiddleMaker.activeMaking={}; ForgeAshRiddleMaker.totalProducts=0; ForgeAshRiddleMaker.dayTimer=0; print("[ForgeAshRiddleMaker] Royal Forge Ash Riddle Maker System initialized (6 products, 4 buildings)") end
function ForgeAshRiddleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ForgeAshRiddleMaker.maker={name=n or ("Sitar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sitar najet: %s (spretnost: %d)",ForgeAshRiddleMaker.maker.name,s),"success") end; return true end
function ForgeAshRiddleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ForgeAshRiddleMaker.build(id) local ok,e=ForgeAshRiddleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ForgeAshRiddleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ForgeAshRiddleMaker.getQualityBonus() local b=0; for _,bd in ipairs(ForgeAshRiddleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ForgeAshRiddleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ForgeAshRiddleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and ForgeAshRiddleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ForgeAshRiddleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ForgeAshRiddleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ForgeAshRiddleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ForgeAshRiddleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ForgeAshRiddleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ForgeAshRiddleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ForgeAshRiddleMaker.buildings==0 then return false,"Potrebna sitalna delavnica" end; if not ForgeAshRiddleMaker.maker then return false,"Potreben sitar" end; return true end
function ForgeAshRiddleMaker.make(pt,qty) qty=qty or 1; local ok,e=ForgeAshRiddleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ForgeAshRiddleMaker.ironStock=ForgeAshRiddleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ForgeAshRiddleMaker.bronzeStock=ForgeAshRiddleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ForgeAshRiddleMaker.woodStock=ForgeAshRiddleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ForgeAshRiddleMaker.leatherStock=ForgeAshRiddleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ForgeAshRiddleMaker.silverStock=ForgeAshRiddleMaker.silverStock-d.silverCost*qty end; if d.goldCost then ForgeAshRiddleMaker.goldStock=ForgeAshRiddleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ForgeAshRiddleMaker.jewelStock=ForgeAshRiddleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ForgeAshRiddleMaker.pearlStock=ForgeAshRiddleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ForgeAshRiddleMaker.maker then t=math.max(1,t-math.floor(ForgeAshRiddleMaker.maker.skill/13)) end; table.insert(ForgeAshRiddleMaker.activeMaking,{id="forgeashriddle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ForgeAshRiddleMaker.completeMaking(m) local q=1.0+(ForgeAshRiddleMaker.getQualityBonus()/100); if ForgeAshRiddleMaker.maker then q=q+(ForgeAshRiddleMaker.maker.skill/140) end; q=math.min(2.5,q); ForgeAshRiddleMaker.productStock[m.productType]=(ForgeAshRiddleMaker.productStock[m.productType] or 0)+m.quantity; ForgeAshRiddleMaker.totalProducts=ForgeAshRiddleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ForgeAshRiddleMaker.maker then ForgeAshRiddleMaker.maker.itemsMade=ForgeAshRiddleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ForgeAshRiddleMaker.maker.skill=math.min(100,ForgeAshRiddleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sito izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"forgeashriddle.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ForgeAshRiddleMaker.update(dt) if not _G.state then return end; ForgeAshRiddleMaker.dayTimer=ForgeAshRiddleMaker.dayTimer+dt; if ForgeAshRiddleMaker.dayTimer>=30 then ForgeAshRiddleMaker.dayTimer=0; for i=#ForgeAshRiddleMaker.activeMaking,1,-1 do local m=ForgeAshRiddleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ForgeAshRiddleMaker.completeMaking(m); table.remove(ForgeAshRiddleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ForgeAshRiddleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ForgeAshRiddleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ForgeAshRiddleMaker.getStats() return {ironStock=ForgeAshRiddleMaker.ironStock,bronzeStock=ForgeAshRiddleMaker.bronzeStock,woodStock=ForgeAshRiddleMaker.woodStock,leatherStock=ForgeAshRiddleMaker.leatherStock,silverStock=ForgeAshRiddleMaker.silverStock,goldStock=ForgeAshRiddleMaker.goldStock,jewelStock=ForgeAshRiddleMaker.jewelStock,pearlStock=ForgeAshRiddleMaker.pearlStock,productStock=ForgeAshRiddleMaker.productStock,numBuildings=#ForgeAshRiddleMaker.buildings,hasMaker=ForgeAshRiddleMaker.maker~=nil,makerName=ForgeAshRiddleMaker.maker and ForgeAshRiddleMaker.maker.name or "—",makerSkill=ForgeAshRiddleMaker.maker and ForgeAshRiddleMaker.maker.skill or 0,activeMaking=#ForgeAshRiddleMaker.activeMaking,totalProducts=ForgeAshRiddleMaker.totalProducts} end
return ForgeAshRiddleMaker
