local ForgeTongsMaker = {}
local PRODUCTS = {
    iron_forge_tongs = { name = "Železne kovaške klešče za žar", ironCost = 6, woodCost = 1, leatherCost = 1, time = 6, cost = 215, prestige = 5, happiness = 2, description = "Železne kovaške klešče za prijemanje vroče kovine iz žara." },
    bronze_forge_tongs = { name = "Bronaste kovaške klešče za žar", bronzeCost = 6, ironCost = 1, woodCost = 1, leatherCost = 1, time = 8, cost = 520, prestige = 7, happiness = 3, description = "Bronaste kovaške klešče za visoke temperature." },
    silver_forge_tongs = { name = "Srebrne kovaške klešče za žar", silverCost = 6, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 12, cost = 1250, prestige = 12, happiness = 4, description = "Srebrne kovaške klešče za plemiške kovače." },
    gilded_forge_tongs = { name = "Pozlačene kovaške klešče za žar", goldCost = 1, silverCost = 6, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 16, cost = 2700, prestige = 21, happiness = 5, description = "Pozlačene kovaške klešče za dvorne kovače." },
    jewel_set_forge_tongs = { name = "Draguljaste kovaške klešče za žar", goldCost = 2, silverCost = 6, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 20, cost = 5800, prestige = 37, happiness = 7, description = "Draguljaste kovaške klešče za kraljevske kovače." },
    royal_sovereign_forge_tongs = { name = "Kraljevski suverene kovaške klešče za žar", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 27, cost = 12400, prestige = 71, happiness = 13, description = "Suverene kovaške klešče z biseri za krono." },
}
local BUILDINGS = {
    forgetongs_workshop = { name = "Žarna delavnica", cost = { gold = 390, wood = 175, stone = 160, iron = 12 }, upkeep = 8, qualityBonus = 5 },
    forgetongs_house = { name = "Žarna hiša", cost = { gold = 1320, wood = 360, stone = 295, silver = 8, iron = 10 }, upkeep = 28, qualityBonus = 18 },
    master_forgetongs_atelier = { name = "Mojstrski žarni atelje", cost = { gold = 3250, wood = 420, stone = 550, silver = 40, gold = 8 }, upkeep = 76, qualityBonus = 30 },
    sovereign_forgetongs_palace = { name = "Suverena žarna palača", cost = { gold = 13850, wood = 650, stone = 870, gold = 89, jewel = 20 }, upkeep = 265, qualityBonus = 55, prestigeBonus = 50 },
}
ForgeTongsMaker.ironStock = 20; ForgeTongsMaker.bronzeStock = 14; ForgeTongsMaker.woodStock = 8; ForgeTongsMaker.leatherStock = 10; ForgeTongsMaker.silverStock = 8; ForgeTongsMaker.goldStock = 6; ForgeTongsMaker.jewelStock = 4; ForgeTongsMaker.pearlStock = 4
ForgeTongsMaker.productStock = {}; ForgeTongsMaker.buildings = {}; ForgeTongsMaker.maker = nil; ForgeTongsMaker.activeMaking = {}; ForgeTongsMaker.totalProducts = 0; ForgeTongsMaker.dayTimer = 0
function ForgeTongsMaker.init() ForgeTongsMaker.ironStock=20; ForgeTongsMaker.bronzeStock=14; ForgeTongsMaker.woodStock=8; ForgeTongsMaker.leatherStock=10; ForgeTongsMaker.silverStock=8; ForgeTongsMaker.goldStock=6; ForgeTongsMaker.jewelStock=4; ForgeTongsMaker.pearlStock=4; ForgeTongsMaker.productStock={}; ForgeTongsMaker.buildings={}; ForgeTongsMaker.maker=nil; ForgeTongsMaker.activeMaking={}; ForgeTongsMaker.totalProducts=0; ForgeTongsMaker.dayTimer=0; print("[ForgeTongsMaker] Royal Forge Tongs Maker System initialized (6 products, 4 buildings)") end
function ForgeTongsMaker.hireMaker(n,s) s=s or math.random(55,90); local c=590+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ForgeTongsMaker.maker={name=n or ("Žarist "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Žarist najet: %s (spretnost: %d)",ForgeTongsMaker.maker.name,s),"success") end; return true end
function ForgeTongsMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ForgeTongsMaker.build(id) local ok,e=ForgeTongsMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ForgeTongsMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ForgeTongsMaker.getQualityBonus() local b=0; for _,bd in ipairs(ForgeTongsMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ForgeTongsMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ForgeTongsMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and ForgeTongsMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ForgeTongsMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ForgeTongsMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ForgeTongsMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ForgeTongsMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ForgeTongsMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ForgeTongsMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ForgeTongsMaker.buildings==0 then return false,"Potrebna žarna delavnica" end; if not ForgeTongsMaker.maker then return false,"Potreben žarist" end; return true end
function ForgeTongsMaker.make(pt,qty) qty=qty or 1; local ok,e=ForgeTongsMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ForgeTongsMaker.ironStock=ForgeTongsMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ForgeTongsMaker.bronzeStock=ForgeTongsMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ForgeTongsMaker.woodStock=ForgeTongsMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ForgeTongsMaker.leatherStock=ForgeTongsMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ForgeTongsMaker.silverStock=ForgeTongsMaker.silverStock-d.silverCost*qty end; if d.goldCost then ForgeTongsMaker.goldStock=ForgeTongsMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ForgeTongsMaker.jewelStock=ForgeTongsMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ForgeTongsMaker.pearlStock=ForgeTongsMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ForgeTongsMaker.maker then t=math.max(1,t-math.floor(ForgeTongsMaker.maker.skill/13)) end; table.insert(ForgeTongsMaker.activeMaking,{id="forgetongs_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ForgeTongsMaker.completeMaking(m) local q=1.0+(ForgeTongsMaker.getQualityBonus()/100); if ForgeTongsMaker.maker then q=q+(ForgeTongsMaker.maker.skill/140) end; q=math.min(2.5,q); ForgeTongsMaker.productStock[m.productType]=(ForgeTongsMaker.productStock[m.productType] or 0)+m.quantity; ForgeTongsMaker.totalProducts=ForgeTongsMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ForgeTongsMaker.maker then ForgeTongsMaker.maker.itemsMade=ForgeTongsMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ForgeTongsMaker.maker.skill=math.min(100,ForgeTongsMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovaške klešče izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"forgetongs.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ForgeTongsMaker.update(dt) if not _G.state then return end; ForgeTongsMaker.dayTimer=ForgeTongsMaker.dayTimer+dt; if ForgeTongsMaker.dayTimer>=30 then ForgeTongsMaker.dayTimer=0; for i=#ForgeTongsMaker.activeMaking,1,-1 do local m=ForgeTongsMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ForgeTongsMaker.completeMaking(m); table.remove(ForgeTongsMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ForgeTongsMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ForgeTongsMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ForgeTongsMaker.getStats() return {ironStock=ForgeTongsMaker.ironStock,bronzeStock=ForgeTongsMaker.bronzeStock,woodStock=ForgeTongsMaker.woodStock,leatherStock=ForgeTongsMaker.leatherStock,silverStock=ForgeTongsMaker.silverStock,goldStock=ForgeTongsMaker.goldStock,jewelStock=ForgeTongsMaker.jewelStock,pearlStock=ForgeTongsMaker.pearlStock,productStock=ForgeTongsMaker.productStock,numBuildings=#ForgeTongsMaker.buildings,hasMaker=ForgeTongsMaker.maker~=nil,makerName=ForgeTongsMaker.maker and ForgeTongsMaker.maker.name or "—",makerSkill=ForgeTongsMaker.maker and ForgeTongsMaker.maker.skill or 0,activeMaking=#ForgeTongsMaker.activeMaking,totalProducts=ForgeTongsMaker.totalProducts} end
return ForgeTongsMaker
