local GlassPuntyWarmerMaker = {}
local PRODUCTS = {
    iron_glasspuntywarmer = { name = "Železni grevalnik palic za steklo", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni grevalnik palic za steklo za steklarje." },
    bronze_glasspuntywarmer = { name = "Bronast grevalnik palic za steklo", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast grevalnik palic za steklo za steklarje." },
    silver_glasspuntywarmer = { name = "Srebrn grevalnik palic za steklo", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn grevalnik palic za steklo za steklarje." },
    gilded_glasspuntywarmer = { name = "Pozlačen grevalnik palic za steklo", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen grevalnik palic za steklo za steklarje." },
    jewel_set_glasspuntywarmer = { name = "Draguljast grevalnik palic za steklo", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast grevalnik palic za steklo za steklarje." },
    royal_sovereign_glasspuntywarmer = { name = "Kraljevski suveren grevalnik palic za steklo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren grevalnik palic za steklo z biseri za krono." },
}
local BUILDINGS = {
    glasspuntywarmer_workshop = { name = "Glasspuntywarmer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glasspuntywarmer_house = { name = "Glasspuntywarmer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glasspuntywarmer_atelier = { name = "Mojstrski glasspuntywarmer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glasspuntywarmer_palace = { name = "Suverena glasspuntywarmer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassPuntyWarmerMaker.ironStock=16; GlassPuntyWarmerMaker.bronzeStock=12; GlassPuntyWarmerMaker.woodStock=12; GlassPuntyWarmerMaker.leatherStock=8; GlassPuntyWarmerMaker.silverStock=8; GlassPuntyWarmerMaker.goldStock=6; GlassPuntyWarmerMaker.jewelStock=4; GlassPuntyWarmerMaker.pearlStock=4
GlassPuntyWarmerMaker.productStock = {}; GlassPuntyWarmerMaker.buildings = {}; GlassPuntyWarmerMaker.maker = nil; GlassPuntyWarmerMaker.activeMaking = {}; GlassPuntyWarmerMaker.totalProducts = 0; GlassPuntyWarmerMaker.dayTimer = 0
function GlassPuntyWarmerMaker.init() GlassPuntyWarmerMaker.ironStock=16; GlassPuntyWarmerMaker.bronzeStock=12; GlassPuntyWarmerMaker.woodStock=12; GlassPuntyWarmerMaker.leatherStock=8; GlassPuntyWarmerMaker.silverStock=8; GlassPuntyWarmerMaker.goldStock=6; GlassPuntyWarmerMaker.jewelStock=4; GlassPuntyWarmerMaker.pearlStock=4; GlassPuntyWarmerMaker.productStock={}; GlassPuntyWarmerMaker.buildings={}; GlassPuntyWarmerMaker.maker=nil; GlassPuntyWarmerMaker.activeMaking={}; GlassPuntyWarmerMaker.totalProducts=0; GlassPuntyWarmerMaker.dayTimer=0; print("[GlassPuntyWarmerMaker] Royal Glass Punty Warmer Maker System initialized (6 products, 4 buildings)") end
function GlassPuntyWarmerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassPuntyWarmerMaker.maker={name=n or ("Grevalnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Grevalnik najet: %s (spretnost: %d)",GlassPuntyWarmerMaker.maker.name,s),"success") end; return true end
function GlassPuntyWarmerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassPuntyWarmerMaker.build(id) local ok,e=GlassPuntyWarmerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassPuntyWarmerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassPuntyWarmerMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassPuntyWarmerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassPuntyWarmerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassPuntyWarmerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassPuntyWarmerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassPuntyWarmerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassPuntyWarmerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassPuntyWarmerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassPuntyWarmerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassPuntyWarmerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassPuntyWarmerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassPuntyWarmerMaker.buildings==0 then return false,"Potrebna grevalna delavnica" end; if not GlassPuntyWarmerMaker.maker then return false,"Potreben grevalnik" end; return true end
function GlassPuntyWarmerMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassPuntyWarmerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassPuntyWarmerMaker.ironStock=GlassPuntyWarmerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassPuntyWarmerMaker.bronzeStock=GlassPuntyWarmerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassPuntyWarmerMaker.woodStock=GlassPuntyWarmerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassPuntyWarmerMaker.leatherStock=GlassPuntyWarmerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassPuntyWarmerMaker.silverStock=GlassPuntyWarmerMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassPuntyWarmerMaker.goldStock=GlassPuntyWarmerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassPuntyWarmerMaker.jewelStock=GlassPuntyWarmerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassPuntyWarmerMaker.pearlStock=GlassPuntyWarmerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassPuntyWarmerMaker.maker then t=math.max(1,t-math.floor(GlassPuntyWarmerMaker.maker.skill/13)) end; table.insert(GlassPuntyWarmerMaker.activeMaking,{id="glasspuntywarmer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassPuntyWarmerMaker.completeMaking(m) local q=1.0+(GlassPuntyWarmerMaker.getQualityBonus()/100); if GlassPuntyWarmerMaker.maker then q=q+(GlassPuntyWarmerMaker.maker.skill/140) end; q=math.min(2.5,q); GlassPuntyWarmerMaker.productStock[m.productType]=(GlassPuntyWarmerMaker.productStock[m.productType] or 0)+m.quantity; GlassPuntyWarmerMaker.totalProducts=GlassPuntyWarmerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassPuntyWarmerMaker.maker then GlassPuntyWarmerMaker.maker.itemsMade=GlassPuntyWarmerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassPuntyWarmerMaker.maker.skill=math.min(100,GlassPuntyWarmerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Grevalnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glasspuntywarmer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassPuntyWarmerMaker.update(dt) if not _G.state then return end; GlassPuntyWarmerMaker.dayTimer=GlassPuntyWarmerMaker.dayTimer+dt; if GlassPuntyWarmerMaker.dayTimer>=30 then GlassPuntyWarmerMaker.dayTimer=0; for i=#GlassPuntyWarmerMaker.activeMaking,1,-1 do local m=GlassPuntyWarmerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassPuntyWarmerMaker.completeMaking(m); table.remove(GlassPuntyWarmerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassPuntyWarmerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassPuntyWarmerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassPuntyWarmerMaker.getStats() return {ironStock=GlassPuntyWarmerMaker.ironStock,bronzeStock=GlassPuntyWarmerMaker.bronzeStock,woodStock=GlassPuntyWarmerMaker.woodStock,leatherStock=GlassPuntyWarmerMaker.leatherStock,silverStock=GlassPuntyWarmerMaker.silverStock,goldStock=GlassPuntyWarmerMaker.goldStock,jewelStock=GlassPuntyWarmerMaker.jewelStock,pearlStock=GlassPuntyWarmerMaker.pearlStock,productStock=GlassPuntyWarmerMaker.productStock,numBuildings=#GlassPuntyWarmerMaker.buildings,hasMaker=GlassPuntyWarmerMaker.maker~=nil,makerName=GlassPuntyWarmerMaker.maker and GlassPuntyWarmerMaker.maker.name or "—",makerSkill=GlassPuntyWarmerMaker.maker and GlassPuntyWarmerMaker.maker.skill or 0,activeMaking=#GlassPuntyWarmerMaker.activeMaking,totalProducts=GlassPuntyWarmerMaker.totalProducts} end
return GlassPuntyWarmerMaker
