local MillstoneLifterHooksMaker = {}
local PRODUCTS = {
    iron_millstonelifterhooks = { name = "Železni kljuki za dviganje kamnov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni kljuki za dviganje kamnov za mlinarje." },
    bronze_millstonelifterhooks = { name = "Bronast kljuki za dviganje kamnov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast kljuki za dviganje kamnov za mlinarje." },
    silver_millstonelifterhooks = { name = "Srebrn kljuki za dviganje kamnov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn kljuki za dviganje kamnov za mlinarje." },
    gilded_millstonelifterhooks = { name = "Pozlačen kljuki za dviganje kamnov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen kljuki za dviganje kamnov za mlinarje." },
    jewel_set_millstonelifterhooks = { name = "Draguljast kljuki za dviganje kamnov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast kljuki za dviganje kamnov za mlinarje." },
    royal_sovereign_millstonelifterhooks = { name = "Kraljevski suveren kljuki za dviganje kamnov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren kljuki za dviganje kamnov z biseri za krono." },
}
local BUILDINGS = {
    millstonelifterhooks_workshop = { name = "Millstonelifterhooks delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    millstonelifterhooks_house = { name = "Millstonelifterhooks hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_millstonelifterhooks_atelier = { name = "Mojstrski millstonelifterhooks atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_millstonelifterhooks_palace = { name = "Suverena millstonelifterhooks palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillstoneLifterHooksMaker.ironStock=18; MillstoneLifterHooksMaker.bronzeStock=14; MillstoneLifterHooksMaker.woodStock=10; MillstoneLifterHooksMaker.leatherStock=8; MillstoneLifterHooksMaker.silverStock=8; MillstoneLifterHooksMaker.goldStock=6; MillstoneLifterHooksMaker.jewelStock=4; MillstoneLifterHooksMaker.pearlStock=4
MillstoneLifterHooksMaker.productStock = {}; MillstoneLifterHooksMaker.buildings = {}; MillstoneLifterHooksMaker.maker = nil; MillstoneLifterHooksMaker.activeMaking = {}; MillstoneLifterHooksMaker.totalProducts = 0; MillstoneLifterHooksMaker.dayTimer = 0
function MillstoneLifterHooksMaker.init() MillstoneLifterHooksMaker.ironStock=18; MillstoneLifterHooksMaker.bronzeStock=14; MillstoneLifterHooksMaker.woodStock=10; MillstoneLifterHooksMaker.leatherStock=8; MillstoneLifterHooksMaker.silverStock=8; MillstoneLifterHooksMaker.goldStock=6; MillstoneLifterHooksMaker.jewelStock=4; MillstoneLifterHooksMaker.pearlStock=4; MillstoneLifterHooksMaker.productStock={}; MillstoneLifterHooksMaker.buildings={}; MillstoneLifterHooksMaker.maker=nil; MillstoneLifterHooksMaker.activeMaking={}; MillstoneLifterHooksMaker.totalProducts=0; MillstoneLifterHooksMaker.dayTimer=0; print("[MillstoneLifterHooksMaker] Royal Millstone Lifter Hooks Maker System initialized (6 products, 4 buildings)") end
function MillstoneLifterHooksMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillstoneLifterHooksMaker.maker={name=n or ("Dvigalkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Dvigalkar najet: %s (spretnost: %d)",MillstoneLifterHooksMaker.maker.name,s),"success") end; return true end
function MillstoneLifterHooksMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillstoneLifterHooksMaker.build(id) local ok,e=MillstoneLifterHooksMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillstoneLifterHooksMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillstoneLifterHooksMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillstoneLifterHooksMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillstoneLifterHooksMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillstoneLifterHooksMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillstoneLifterHooksMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillstoneLifterHooksMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillstoneLifterHooksMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillstoneLifterHooksMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillstoneLifterHooksMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillstoneLifterHooksMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillstoneLifterHooksMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillstoneLifterHooksMaker.buildings==0 then return false,"Potrebna dvigalna delavnica" end; if not MillstoneLifterHooksMaker.maker then return false,"Potreben dvigalkar" end; return true end
function MillstoneLifterHooksMaker.make(pt,qty) qty=qty or 1; local ok,e=MillstoneLifterHooksMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillstoneLifterHooksMaker.ironStock=MillstoneLifterHooksMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillstoneLifterHooksMaker.bronzeStock=MillstoneLifterHooksMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillstoneLifterHooksMaker.woodStock=MillstoneLifterHooksMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillstoneLifterHooksMaker.leatherStock=MillstoneLifterHooksMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillstoneLifterHooksMaker.silverStock=MillstoneLifterHooksMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillstoneLifterHooksMaker.goldStock=MillstoneLifterHooksMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillstoneLifterHooksMaker.jewelStock=MillstoneLifterHooksMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillstoneLifterHooksMaker.pearlStock=MillstoneLifterHooksMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillstoneLifterHooksMaker.maker then t=math.max(1,t-math.floor(MillstoneLifterHooksMaker.maker.skill/13)) end; table.insert(MillstoneLifterHooksMaker.activeMaking,{id="millstonelifterhooks_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillstoneLifterHooksMaker.completeMaking(m) local q=1.0+(MillstoneLifterHooksMaker.getQualityBonus()/100); if MillstoneLifterHooksMaker.maker then q=q+(MillstoneLifterHooksMaker.maker.skill/140) end; q=math.min(2.5,q); MillstoneLifterHooksMaker.productStock[m.productType]=(MillstoneLifterHooksMaker.productStock[m.productType] or 0)+m.quantity; MillstoneLifterHooksMaker.totalProducts=MillstoneLifterHooksMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillstoneLifterHooksMaker.maker then MillstoneLifterHooksMaker.maker.itemsMade=MillstoneLifterHooksMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillstoneLifterHooksMaker.maker.skill=math.min(100,MillstoneLifterHooksMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Dvigalka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millstonelifterhooks.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillstoneLifterHooksMaker.update(dt) if not _G.state then return end; MillstoneLifterHooksMaker.dayTimer=MillstoneLifterHooksMaker.dayTimer+dt; if MillstoneLifterHooksMaker.dayTimer>=30 then MillstoneLifterHooksMaker.dayTimer=0; for i=#MillstoneLifterHooksMaker.activeMaking,1,-1 do local m=MillstoneLifterHooksMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillstoneLifterHooksMaker.completeMaking(m); table.remove(MillstoneLifterHooksMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillstoneLifterHooksMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillstoneLifterHooksMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillstoneLifterHooksMaker.getStats() return {ironStock=MillstoneLifterHooksMaker.ironStock,bronzeStock=MillstoneLifterHooksMaker.bronzeStock,woodStock=MillstoneLifterHooksMaker.woodStock,leatherStock=MillstoneLifterHooksMaker.leatherStock,silverStock=MillstoneLifterHooksMaker.silverStock,goldStock=MillstoneLifterHooksMaker.goldStock,jewelStock=MillstoneLifterHooksMaker.jewelStock,pearlStock=MillstoneLifterHooksMaker.pearlStock,productStock=MillstoneLifterHooksMaker.productStock,numBuildings=#MillstoneLifterHooksMaker.buildings,hasMaker=MillstoneLifterHooksMaker.maker~=nil,makerName=MillstoneLifterHooksMaker.maker and MillstoneLifterHooksMaker.maker.name or "—",makerSkill=MillstoneLifterHooksMaker.maker and MillstoneLifterHooksMaker.maker.skill or 0,activeMaking=#MillstoneLifterHooksMaker.activeMaking,totalProducts=MillstoneLifterHooksMaker.totalProducts} end
return MillstoneLifterHooksMaker
