local WineStrainerMaker = {}
local PRODUCTS = {
    iron_winestrainer = { name = "Železni cedilo za vino", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni cedilo za vino za kuhinjo." },
    bronze_winestrainer = { name = "Bronast cedilo za vino", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast cedilo za vino za kuhinjo." },
    silver_winestrainer = { name = "Srebrn cedilo za vino", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn cedilo za vino za kuhinjo." },
    gilded_winestrainer = { name = "Pozlačen cedilo za vino", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen cedilo za vino za kuhinjo." },
    jewel_set_winestrainer = { name = "Draguljast cedilo za vino", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast cedilo za vino za kuhinjo." },
    royal_sovereign_winestrainer = { name = "Kraljevski suveren cedilo za vino", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren cedilo za vino z biseri za krono." },
}
local BUILDINGS = {
    winestrainer_workshop = { name = "Winestrainer delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    winestrainer_house = { name = "Winestrainer hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_winestrainer_atelier = { name = "Mojstrski winestrainer atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_winestrainer_palace = { name = "Suverena winestrainer palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
WineStrainerMaker.ironStock = 12; WineStrainerMaker.bronzeStock = 10; WineStrainerMaker.woodStock = 14; WineStrainerMaker.leatherStock = 12; WineStrainerMaker.silverStock = 8; WineStrainerMaker.goldStock = 6; WineStrainerMaker.jewelStock = 4; WineStrainerMaker.pearlStock = 4
WineStrainerMaker.productStock = {}; WineStrainerMaker.buildings = {}; WineStrainerMaker.maker = nil; WineStrainerMaker.activeMaking = {}; WineStrainerMaker.totalProducts = 0; WineStrainerMaker.dayTimer = 0
function WineStrainerMaker.init() WineStrainerMaker.ironStock=12; WineStrainerMaker.bronzeStock=10; WineStrainerMaker.woodStock=14; WineStrainerMaker.leatherStock=12; WineStrainerMaker.silverStock=8; WineStrainerMaker.goldStock=6; WineStrainerMaker.jewelStock=4; WineStrainerMaker.pearlStock=4; WineStrainerMaker.productStock={}; WineStrainerMaker.buildings={}; WineStrainerMaker.maker=nil; WineStrainerMaker.activeMaking={}; WineStrainerMaker.totalProducts=0; WineStrainerMaker.dayTimer=0; print("[WineStrainerMaker] Royal Wine Strainer Maker System initialized (6 products, 4 buildings)") end
function WineStrainerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; WineStrainerMaker.maker={name=n or ("Cedilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Cedilar najet: %s (spretnost: %d)",WineStrainerMaker.maker.name,s),"success") end; return true end
function WineStrainerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function WineStrainerMaker.build(id) local ok,e=WineStrainerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(WineStrainerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function WineStrainerMaker.getQualityBonus() local b=0; for _,bd in ipairs(WineStrainerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function WineStrainerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and WineStrainerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and WineStrainerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and WineStrainerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and WineStrainerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and WineStrainerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and WineStrainerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and WineStrainerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and WineStrainerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #WineStrainerMaker.buildings==0 then return false,"Potrebna cedilna delavnica" end; if not WineStrainerMaker.maker then return false,"Potreben cedilar" end; return true end
function WineStrainerMaker.make(pt,qty) qty=qty or 1; local ok,e=WineStrainerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then WineStrainerMaker.ironStock=WineStrainerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then WineStrainerMaker.bronzeStock=WineStrainerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then WineStrainerMaker.woodStock=WineStrainerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then WineStrainerMaker.leatherStock=WineStrainerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then WineStrainerMaker.silverStock=WineStrainerMaker.silverStock-d.silverCost*qty end; if d.goldCost then WineStrainerMaker.goldStock=WineStrainerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then WineStrainerMaker.jewelStock=WineStrainerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then WineStrainerMaker.pearlStock=WineStrainerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if WineStrainerMaker.maker then t=math.max(1,t-math.floor(WineStrainerMaker.maker.skill/13)) end; table.insert(WineStrainerMaker.activeMaking,{id="winestrainer_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function WineStrainerMaker.completeMaking(m) local q=1.0+(WineStrainerMaker.getQualityBonus()/100); if WineStrainerMaker.maker then q=q+(WineStrainerMaker.maker.skill/140) end; q=math.min(2.5,q); WineStrainerMaker.productStock[m.productType]=(WineStrainerMaker.productStock[m.productType] or 0)+m.quantity; WineStrainerMaker.totalProducts=WineStrainerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if WineStrainerMaker.maker then WineStrainerMaker.maker.itemsMade=WineStrainerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then WineStrainerMaker.maker.skill=math.min(100,WineStrainerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Cedilo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"winestrainer.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function WineStrainerMaker.update(dt) if not _G.state then return end; WineStrainerMaker.dayTimer=WineStrainerMaker.dayTimer+dt; if WineStrainerMaker.dayTimer>=30 then WineStrainerMaker.dayTimer=0; for i=#WineStrainerMaker.activeMaking,1,-1 do local m=WineStrainerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then WineStrainerMaker.completeMaking(m); table.remove(WineStrainerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(WineStrainerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if WineStrainerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function WineStrainerMaker.getStats() return {ironStock=WineStrainerMaker.ironStock,bronzeStock=WineStrainerMaker.bronzeStock,woodStock=WineStrainerMaker.woodStock,leatherStock=WineStrainerMaker.leatherStock,silverStock=WineStrainerMaker.silverStock,goldStock=WineStrainerMaker.goldStock,jewelStock=WineStrainerMaker.jewelStock,pearlStock=WineStrainerMaker.pearlStock,productStock=WineStrainerMaker.productStock,numBuildings=#WineStrainerMaker.buildings,hasMaker=WineStrainerMaker.maker~=nil,makerName=WineStrainerMaker.maker and WineStrainerMaker.maker.name or "—",makerSkill=WineStrainerMaker.maker and WineStrainerMaker.maker.skill or 0,activeMaking=#WineStrainerMaker.activeMaking,totalProducts=WineStrainerMaker.totalProducts} end
return WineStrainerMaker
