local HotCutHardyMaker = {}
local PRODUCTS = {
    iron_hotcuthardy = { name = "Železni vroče rezalni trdi nastavek", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni vroče rezalni trdi nastavek za kovace." },
    bronze_hotcuthardy = { name = "Bronast vroče rezalni trdi nastavek", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast vroče rezalni trdi nastavek za kovace." },
    silver_hotcuthardy = { name = "Srebrn vroče rezalni trdi nastavek", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn vroče rezalni trdi nastavek za kovace." },
    gilded_hotcuthardy = { name = "Pozlačen vroče rezalni trdi nastavek", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen vroče rezalni trdi nastavek za kovace." },
    jewel_set_hotcuthardy = { name = "Draguljast vroče rezalni trdi nastavek", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast vroče rezalni trdi nastavek za kovace." },
    royal_sovereign_hotcuthardy = { name = "Kraljevski suveren vroče rezalni trdi nastavek", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren vroče rezalni trdi nastavek z biseri za krono." },
}
local BUILDINGS = {
    hotcuthardy_workshop = { name = "Hotcuthardy delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    hotcuthardy_house = { name = "Hotcuthardy hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_hotcuthardy_atelier = { name = "Mojstrski hotcuthardy atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_hotcuthardy_palace = { name = "Suverena hotcuthardy palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
HotCutHardyMaker.ironStock=18; HotCutHardyMaker.bronzeStock=14; HotCutHardyMaker.woodStock=10; HotCutHardyMaker.leatherStock=8; HotCutHardyMaker.silverStock=8; HotCutHardyMaker.goldStock=6; HotCutHardyMaker.jewelStock=4; HotCutHardyMaker.pearlStock=4
HotCutHardyMaker.productStock = {}; HotCutHardyMaker.buildings = {}; HotCutHardyMaker.maker = nil; HotCutHardyMaker.activeMaking = {}; HotCutHardyMaker.totalProducts = 0; HotCutHardyMaker.dayTimer = 0
function HotCutHardyMaker.init() HotCutHardyMaker.ironStock=18; HotCutHardyMaker.bronzeStock=14; HotCutHardyMaker.woodStock=10; HotCutHardyMaker.leatherStock=8; HotCutHardyMaker.silverStock=8; HotCutHardyMaker.goldStock=6; HotCutHardyMaker.jewelStock=4; HotCutHardyMaker.pearlStock=4; HotCutHardyMaker.productStock={}; HotCutHardyMaker.buildings={}; HotCutHardyMaker.maker=nil; HotCutHardyMaker.activeMaking={}; HotCutHardyMaker.totalProducts=0; HotCutHardyMaker.dayTimer=0; print("[HotCutHardyMaker] Royal Hot Cut Hardy Maker System initialized (6 products, 4 buildings)") end
function HotCutHardyMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HotCutHardyMaker.maker={name=n or ("Vročoreznik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vročoreznik najet: %s (spretnost: %d)",HotCutHardyMaker.maker.name,s),"success") end; return true end
function HotCutHardyMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HotCutHardyMaker.build(id) local ok,e=HotCutHardyMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HotCutHardyMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HotCutHardyMaker.getQualityBonus() local b=0; for _,bd in ipairs(HotCutHardyMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HotCutHardyMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and HotCutHardyMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and HotCutHardyMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and HotCutHardyMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and HotCutHardyMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and HotCutHardyMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HotCutHardyMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HotCutHardyMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HotCutHardyMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HotCutHardyMaker.buildings==0 then return false,"Potrebna vročorezna delavnica" end; if not HotCutHardyMaker.maker then return false,"Potreben vročoreznik" end; return true end
function HotCutHardyMaker.make(pt,qty) qty=qty or 1; local ok,e=HotCutHardyMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then HotCutHardyMaker.ironStock=HotCutHardyMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then HotCutHardyMaker.bronzeStock=HotCutHardyMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then HotCutHardyMaker.woodStock=HotCutHardyMaker.woodStock-d.woodCost*qty end; if d.leatherCost then HotCutHardyMaker.leatherStock=HotCutHardyMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then HotCutHardyMaker.silverStock=HotCutHardyMaker.silverStock-d.silverCost*qty end; if d.goldCost then HotCutHardyMaker.goldStock=HotCutHardyMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HotCutHardyMaker.jewelStock=HotCutHardyMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HotCutHardyMaker.pearlStock=HotCutHardyMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HotCutHardyMaker.maker then t=math.max(1,t-math.floor(HotCutHardyMaker.maker.skill/13)) end; table.insert(HotCutHardyMaker.activeMaking,{id="hotcuthardy_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HotCutHardyMaker.completeMaking(m) local q=1.0+(HotCutHardyMaker.getQualityBonus()/100); if HotCutHardyMaker.maker then q=q+(HotCutHardyMaker.maker.skill/140) end; q=math.min(2.5,q); HotCutHardyMaker.productStock[m.productType]=(HotCutHardyMaker.productStock[m.productType] or 0)+m.quantity; HotCutHardyMaker.totalProducts=HotCutHardyMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HotCutHardyMaker.maker then HotCutHardyMaker.maker.itemsMade=HotCutHardyMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then HotCutHardyMaker.maker.skill=math.min(100,HotCutHardyMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vročoreznik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"hotcuthardy.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function HotCutHardyMaker.update(dt) if not _G.state then return end; HotCutHardyMaker.dayTimer=HotCutHardyMaker.dayTimer+dt; if HotCutHardyMaker.dayTimer>=30 then HotCutHardyMaker.dayTimer=0; for i=#HotCutHardyMaker.activeMaking,1,-1 do local m=HotCutHardyMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HotCutHardyMaker.completeMaking(m); table.remove(HotCutHardyMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HotCutHardyMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HotCutHardyMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HotCutHardyMaker.getStats() return {ironStock=HotCutHardyMaker.ironStock,bronzeStock=HotCutHardyMaker.bronzeStock,woodStock=HotCutHardyMaker.woodStock,leatherStock=HotCutHardyMaker.leatherStock,silverStock=HotCutHardyMaker.silverStock,goldStock=HotCutHardyMaker.goldStock,jewelStock=HotCutHardyMaker.jewelStock,pearlStock=HotCutHardyMaker.pearlStock,productStock=HotCutHardyMaker.productStock,numBuildings=#HotCutHardyMaker.buildings,hasMaker=HotCutHardyMaker.maker~=nil,makerName=HotCutHardyMaker.maker and HotCutHardyMaker.maker.name or "—",makerSkill=HotCutHardyMaker.maker and HotCutHardyMaker.maker.skill or 0,activeMaking=#HotCutHardyMaker.activeMaking,totalProducts=HotCutHardyMaker.totalProducts} end
return HotCutHardyMaker
