local HatBlockMaker = {}
local PRODUCTS = {
    iron_hat_block = { name = "Železni model za klobuke", ironCost = 1, woodCost = 4, leatherCost = 1, time = 5, cost = 150, prestige = 3, happiness = 2, description = "Železni model za oblikovanje klobukov." },
    bronze_hat_block = { name = "Bronast model za klobuke", bronzeCost = 1, ironCost = 1, woodCost = 4, leatherCost = 1, time = 7, cost = 360, prestige = 5, happiness = 3, description = "Bronast model za klobučarje." },
    silver_hat_block = { name = "Srebrni model za klobuke", silverCost = 1, bronzeCost = 1, ironCost = 1, woodCost = 4, leatherCost = 1, time = 11, cost = 870, prestige = 10, happiness = 4, description = "Srebrni model za plemiške klobučarje." },
    gilded_hat_block = { name = "Pozlačeni model za klobuke", goldCost = 1, silverCost = 1, bronzeCost = 1, woodCost = 4, leatherCost = 1, time = 15, cost = 1880, prestige = 19, happiness = 5, description = "Pozlačeni model za dvorne klobučarje." },
    jewel_set_hat_block = { name = "Draguljasti model za klobuke", goldCost = 2, silverCost = 1, jewelCost = 1, bronzeCost = 1, woodCost = 4, leatherCost = 1, time = 19, cost = 4050, prestige = 35, happiness = 7, description = "Draguljasti model za kraljeve klobučarje." },
    royal_sovereign_hat_block = { name = "Kraljevski suvereni model za klobuke", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 5, leatherCost = 1, time = 26, cost = 8700, prestige = 67, happiness = 13, description = "Suvereni model z biseri za krono." },
}
local BUILDINGS = {
    hatblock_workshop = { name = "Modelna delavnica", cost = { gold = 310, wood = 195, stone = 125, iron = 6 }, upkeep = 6, qualityBonus = 5 },
    hatblock_house = { name = "Modelna hiša", cost = { gold = 1150, wood = 380, stone = 260, silver = 6, iron = 6 }, upkeep = 24, qualityBonus = 18 },
    master_hatblock_atelier = { name = "Mojstrski modelni atelje", cost = { gold = 2900, wood = 440, stone = 500, silver = 32, gold = 6 }, upkeep = 68, qualityBonus = 30 },
    sovereign_hatblock_palace = { name = "Suverena modelna palača", cost = { gold = 12600, wood = 680, stone = 810, gold = 79, jewel = 18 }, upkeep = 247, qualityBonus = 55, prestigeBonus = 50 },
}
HatBlockMaker.ironStock = 10; HatBlockMaker.bronzeStock = 8; HatBlockMaker.woodStock = 20; HatBlockMaker.leatherStock = 10; HatBlockMaker.silverStock = 8; HatBlockMaker.goldStock = 6; HatBlockMaker.jewelStock = 4; HatBlockMaker.pearlStock = 4
HatBlockMaker.productStock = {}; HatBlockMaker.buildings = {}; HatBlockMaker.maker = nil; HatBlockMaker.activeMaking = {}; HatBlockMaker.totalProducts = 0; HatBlockMaker.dayTimer = 0
function HatBlockMaker.init() HatBlockMaker.ironStock=10; HatBlockMaker.bronzeStock=8; HatBlockMaker.woodStock=20; HatBlockMaker.leatherStock=10; HatBlockMaker.silverStock=8; HatBlockMaker.goldStock=6; HatBlockMaker.jewelStock=4; HatBlockMaker.pearlStock=4; HatBlockMaker.productStock={}; HatBlockMaker.buildings={}; HatBlockMaker.maker=nil; HatBlockMaker.activeMaking={}; HatBlockMaker.totalProducts=0; HatBlockMaker.dayTimer=0; print("[HatBlockMaker] Royal Hat Block Maker System initialized (6 products, 4 buildings)") end
function HatBlockMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HatBlockMaker.maker={name=n or ("Modelar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Modelar najet: %s (spretnost: %d)",HatBlockMaker.maker.name,s),"success") end; return true end
function HatBlockMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HatBlockMaker.build(id) local ok,e=HatBlockMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HatBlockMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HatBlockMaker.getQualityBonus() local b=0; for _,bd in ipairs(HatBlockMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HatBlockMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and HatBlockMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and HatBlockMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and HatBlockMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and HatBlockMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and HatBlockMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HatBlockMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HatBlockMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HatBlockMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HatBlockMaker.buildings==0 then return false,"Potrebna modelna delavnica" end; if not HatBlockMaker.maker then return false,"Potreben modelar" end; return true end
function HatBlockMaker.make(pt,qty) qty=qty or 1; local ok,e=HatBlockMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then HatBlockMaker.ironStock=HatBlockMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then HatBlockMaker.bronzeStock=HatBlockMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then HatBlockMaker.woodStock=HatBlockMaker.woodStock-d.woodCost*qty end; if d.leatherCost then HatBlockMaker.leatherStock=HatBlockMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then HatBlockMaker.silverStock=HatBlockMaker.silverStock-d.silverCost*qty end; if d.goldCost then HatBlockMaker.goldStock=HatBlockMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HatBlockMaker.jewelStock=HatBlockMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HatBlockMaker.pearlStock=HatBlockMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HatBlockMaker.maker then t=math.max(1,t-math.floor(HatBlockMaker.maker.skill/13)) end; table.insert(HatBlockMaker.activeMaking,{id="hatblock_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HatBlockMaker.completeMaking(m) local q=1.0+(HatBlockMaker.getQualityBonus()/100); if HatBlockMaker.maker then q=q+(HatBlockMaker.maker.skill/140) end; q=math.min(2.5,q); HatBlockMaker.productStock[m.productType]=(HatBlockMaker.productStock[m.productType] or 0)+m.quantity; HatBlockMaker.totalProducts=HatBlockMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HatBlockMaker.maker then HatBlockMaker.maker.itemsMade=HatBlockMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then HatBlockMaker.maker.skill=math.min(100,HatBlockMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Model izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"hatblock.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function HatBlockMaker.update(dt) if not _G.state then return end; HatBlockMaker.dayTimer=HatBlockMaker.dayTimer+dt; if HatBlockMaker.dayTimer>=30 then HatBlockMaker.dayTimer=0; for i=#HatBlockMaker.activeMaking,1,-1 do local m=HatBlockMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HatBlockMaker.completeMaking(m); table.remove(HatBlockMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HatBlockMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HatBlockMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HatBlockMaker.getStats() return {ironStock=HatBlockMaker.ironStock,bronzeStock=HatBlockMaker.bronzeStock,woodStock=HatBlockMaker.woodStock,leatherStock=HatBlockMaker.leatherStock,silverStock=HatBlockMaker.silverStock,goldStock=HatBlockMaker.goldStock,jewelStock=HatBlockMaker.jewelStock,pearlStock=HatBlockMaker.pearlStock,productStock=HatBlockMaker.productStock,numBuildings=#HatBlockMaker.buildings,hasMaker=HatBlockMaker.maker~=nil,makerName=HatBlockMaker.maker and HatBlockMaker.maker.name or "—",makerSkill=HatBlockMaker.maker and HatBlockMaker.maker.skill or 0,activeMaking=#HatBlockMaker.activeMaking,totalProducts=HatBlockMaker.totalProducts} end
return HatBlockMaker
