local LeatherBurnisherMaker = {}
local PRODUCTS = {
    iron_leatherburnisher = { name = "Železni poliralec usnja", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni poliralec usnja za usnjarje." },
    bronze_leatherburnisher = { name = "Bronast poliralec usnja", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast poliralec usnja za usnjarje." },
    silver_leatherburnisher = { name = "Srebrn poliralec usnja", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn poliralec usnja za usnjarje." },
    gilded_leatherburnisher = { name = "Pozlačen poliralec usnja", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen poliralec usnja za usnjarje." },
    jewel_set_leatherburnisher = { name = "Draguljast poliralec usnja", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast poliralec usnja za usnjarje." },
    royal_sovereign_leatherburnisher = { name = "Kraljevski suveren poliralec usnja", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren poliralec usnja z biseri za krono." },
}
local BUILDINGS = {
    leatherburnisher_workshop = { name = "Leatherburnisher delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    leatherburnisher_house = { name = "Leatherburnisher hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_leatherburnisher_atelier = { name = "Mojstrski leatherburnisher atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_leatherburnisher_palace = { name = "Suverena leatherburnisher palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
LeatherBurnisherMaker.ironStock = 14; LeatherBurnisherMaker.bronzeStock = 12; LeatherBurnisherMaker.woodStock = 12; LeatherBurnisherMaker.leatherStock = 12; LeatherBurnisherMaker.silverStock = 8; LeatherBurnisherMaker.goldStock = 6; LeatherBurnisherMaker.jewelStock = 4; LeatherBurnisherMaker.pearlStock = 4
LeatherBurnisherMaker.productStock = {}; LeatherBurnisherMaker.buildings = {}; LeatherBurnisherMaker.maker = nil; LeatherBurnisherMaker.activeMaking = {}; LeatherBurnisherMaker.totalProducts = 0; LeatherBurnisherMaker.dayTimer = 0
function LeatherBurnisherMaker.init() LeatherBurnisherMaker.ironStock=14; LeatherBurnisherMaker.bronzeStock=12; LeatherBurnisherMaker.woodStock=12; LeatherBurnisherMaker.leatherStock=12; LeatherBurnisherMaker.silverStock=8; LeatherBurnisherMaker.goldStock=6; LeatherBurnisherMaker.jewelStock=4; LeatherBurnisherMaker.pearlStock=4; LeatherBurnisherMaker.productStock={}; LeatherBurnisherMaker.buildings={}; LeatherBurnisherMaker.maker=nil; LeatherBurnisherMaker.activeMaking={}; LeatherBurnisherMaker.totalProducts=0; LeatherBurnisherMaker.dayTimer=0; print("[LeatherBurnisherMaker] Royal Leather Burnisher Maker System initialized (6 products, 4 buildings)") end
function LeatherBurnisherMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LeatherBurnisherMaker.maker={name=n or ("Poliralec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Poliralec najet: %s (spretnost: %d)",LeatherBurnisherMaker.maker.name,s),"success") end; return true end
function LeatherBurnisherMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LeatherBurnisherMaker.build(id) local ok,e=LeatherBurnisherMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LeatherBurnisherMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LeatherBurnisherMaker.getQualityBonus() local b=0; for _,bd in ipairs(LeatherBurnisherMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LeatherBurnisherMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and LeatherBurnisherMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and LeatherBurnisherMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and LeatherBurnisherMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and LeatherBurnisherMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and LeatherBurnisherMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and LeatherBurnisherMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and LeatherBurnisherMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and LeatherBurnisherMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #LeatherBurnisherMaker.buildings==0 then return false,"Potrebna poliralna delavnica" end; if not LeatherBurnisherMaker.maker then return false,"Potreben poliralec" end; return true end
function LeatherBurnisherMaker.make(pt,qty) qty=qty or 1; local ok,e=LeatherBurnisherMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then LeatherBurnisherMaker.ironStock=LeatherBurnisherMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then LeatherBurnisherMaker.bronzeStock=LeatherBurnisherMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then LeatherBurnisherMaker.woodStock=LeatherBurnisherMaker.woodStock-d.woodCost*qty end; if d.leatherCost then LeatherBurnisherMaker.leatherStock=LeatherBurnisherMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then LeatherBurnisherMaker.silverStock=LeatherBurnisherMaker.silverStock-d.silverCost*qty end; if d.goldCost then LeatherBurnisherMaker.goldStock=LeatherBurnisherMaker.goldStock-d.goldCost*qty end; if d.jewelCost then LeatherBurnisherMaker.jewelStock=LeatherBurnisherMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then LeatherBurnisherMaker.pearlStock=LeatherBurnisherMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if LeatherBurnisherMaker.maker then t=math.max(1,t-math.floor(LeatherBurnisherMaker.maker.skill/13)) end; table.insert(LeatherBurnisherMaker.activeMaking,{id="leatherburnisher_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LeatherBurnisherMaker.completeMaking(m) local q=1.0+(LeatherBurnisherMaker.getQualityBonus()/100); if LeatherBurnisherMaker.maker then q=q+(LeatherBurnisherMaker.maker.skill/140) end; q=math.min(2.5,q); LeatherBurnisherMaker.productStock[m.productType]=(LeatherBurnisherMaker.productStock[m.productType] or 0)+m.quantity; LeatherBurnisherMaker.totalProducts=LeatherBurnisherMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LeatherBurnisherMaker.maker then LeatherBurnisherMaker.maker.itemsMade=LeatherBurnisherMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then LeatherBurnisherMaker.maker.skill=math.min(100,LeatherBurnisherMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Poliralec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"leatherburnisher.completed",{productName=m.productName,prestige=m.prestige,happiness:m.happiness}) end end
function LeatherBurnisherMaker.update(dt) if not _G.state then return end; LeatherBurnisherMaker.dayTimer=LeatherBurnisherMaker.dayTimer+dt; if LeatherBurnisherMaker.dayTimer>=30 then LeatherBurnisherMaker.dayTimer=0; for i=#LeatherBurnisherMaker.activeMaking,1,-1 do local m=LeatherBurnisherMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LeatherBurnisherMaker.completeMaking(m); table.remove(LeatherBurnisherMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LeatherBurnisherMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LeatherBurnisherMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LeatherBurnisherMaker.getStats() return {ironStock=LeatherBurnisherMaker.ironStock,bronzeStock=LeatherBurnisherMaker.bronzeStock,woodStock=LeatherBurnisherMaker.woodStock,leatherStock=LeatherBurnisherMaker.leatherStock,silverStock=LeatherBurnisherMaker.silverStock,goldStock=LeatherBurnisherMaker.goldStock,jewelStock=LeatherBurnisherMaker.jewelStock,pearlStock=LeatherBurnisherMaker.pearlStock,productStock=LeatherBurnisherMaker.productStock,numBuildings=#LeatherBurnisherMaker.buildings,hasMaker=LeatherBurnisherMaker.maker~=nil,makerName=LeatherBurnisherMaker.maker and LeatherBurnisherMaker.maker.name or "—",makerSkill=LeatherBurnisherMaker.maker and LeatherBurnisherMaker.maker.skill or 0,activeMaking=#LeatherBurnisherMaker.activeMaking,totalProducts=LeatherBurnisherMaker.totalProducts} end
return LeatherBurnisherMaker
