local SalveJarMaker = {}
local PRODUCTS = {
    iron_salve_jar = { name = "Železni kozarec za mazila", ironCost = 2, woodCost = 1, leatherCost = 1, time = 4, cost = 115, prestige = 2, happiness = 1, description = "Železni kozarec za mazila in balzame." },
    bronze_salve_jar = { name = "Bronast kozarec za mazila", bronzeCost = 2, ironCost = 1, woodCost = 1, leatherCost = 1, time = 6, cost = 290, prestige = 4, happiness = 2, description = "Bronast kozarec za apoteko." },
    silver_salve_jar = { name = "Srebrni kozarec za mazila", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 10, cost = 730, prestige = 8, happiness = 3, description = "Srebrni kozarec za plemiške lekarne." },
    gilded_salve_jar = { name = "Pozlačeni kozarec za mazila", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 14, cost = 1620, prestige = 16, happiness = 4, description = "Pozlačeni kozarec za dvorno lekarno." },
    jewel_set_salve_jar = { name = "Draguljasti kozarec za mazila", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 18, cost = 3550, prestige = 31, happiness = 6, description = "Draguljasti kozarec za kraljevo lekarno." },
    royal_sovereign_salve_jar = { name = "Kraljevski suvereni kozarec za mazila", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 25, cost = 7900, prestige = 61, happiness = 12, description = "Suvereni kozarec z biseri za krono." },
}
local BUILDINGS = {
    salve_workshop = { name = "Mazilna delavnica", cost = { gold = 295, wood = 160, stone = 120, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    salve_house = { name = "Mazilna hiša", cost = { gold = 1100, wood = 340, stone = 250, silver = 6, iron = 6 }, upkeep = 23, qualityBonus = 18 },
    master_salve_atelier = { name = "Mojstrski mazilni atelje", cost = { gold = 2870, wood = 400, stone = 500, silver = 32, gold = 6 }, upkeep = 67, qualityBonus = 30 },
    sovereign_salve_palace = { name = "Suverena mazilna palača", cost = { gold = 12450, wood = 610, stone = 810, gold = 80, jewel = 18 }, upkeep = 246, qualityBonus = 55, prestigeBonus = 50 },
}
SalveJarMaker.ironStock = 12; SalveJarMaker.bronzeStock = 10; SalveJarMaker.woodStock = 14; SalveJarMaker.leatherStock = 10; SalveJarMaker.silverStock = 8; SalveJarMaker.goldStock = 6; SalveJarMaker.jewelStock = 4; SalveJarMaker.pearlStock = 4
SalveJarMaker.productStock = {}; SalveJarMaker.buildings = {}; SalveJarMaker.maker = nil; SalveJarMaker.activeMaking = {}; SalveJarMaker.totalProducts = 0; SalveJarMaker.dayTimer = 0
function SalveJarMaker.init() SalveJarMaker.ironStock=12; SalveJarMaker.bronzeStock=10; SalveJarMaker.woodStock=14; SalveJarMaker.leatherStock=10; SalveJarMaker.silverStock=8; SalveJarMaker.goldStock=6; SalveJarMaker.jewelStock=4; SalveJarMaker.pearlStock=4; SalveJarMaker.productStock={}; SalveJarMaker.buildings={}; SalveJarMaker.maker=nil; SalveJarMaker.activeMaking={}; SalveJarMaker.totalProducts=0; SalveJarMaker.dayTimer=0; print("[SalveJarMaker] Royal Salve Jar Maker System initialized (6 products, 4 buildings)") end
function SalveJarMaker.hireMaker(n,s) s=s or math.random(55,90); local c=565+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SalveJarMaker.maker={name=n or ("Mazilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mazilar najet: %s (spretnost: %d)",SalveJarMaker.maker.name,s),"success") end; return true end
function SalveJarMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SalveJarMaker.build(id) local ok,e=SalveJarMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SalveJarMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SalveJarMaker.getQualityBonus() local b=0; for _,bd in ipairs(SalveJarMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SalveJarMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SalveJarMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SalveJarMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SalveJarMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SalveJarMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SalveJarMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SalveJarMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SalveJarMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SalveJarMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SalveJarMaker.buildings==0 then return false,"Potrebna mazilna delavnica" end; if not SalveJarMaker.maker then return false,"Potreben mazilar" end; return true end
function SalveJarMaker.make(pt,qty) qty=qty or 1; local ok,e=SalveJarMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SalveJarMaker.ironStock=SalveJarMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SalveJarMaker.bronzeStock=SalveJarMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SalveJarMaker.woodStock=SalveJarMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SalveJarMaker.leatherStock=SalveJarMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SalveJarMaker.silverStock=SalveJarMaker.silverStock-d.silverCost*qty end; if d.goldCost then SalveJarMaker.goldStock=SalveJarMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SalveJarMaker.jewelStock=SalveJarMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SalveJarMaker.pearlStock=SalveJarMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SalveJarMaker.maker then t=math.max(1,t-math.floor(SalveJarMaker.maker.skill/13)) end; table.insert(SalveJarMaker.activeMaking,{id="salve_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SalveJarMaker.completeMaking(m) local q=1.0+(SalveJarMaker.getQualityBonus()/100); if SalveJarMaker.maker then q=q+(SalveJarMaker.maker.skill/140) end; q=math.min(2.5,q); SalveJarMaker.productStock[m.productType]=(SalveJarMaker.productStock[m.productType] or 0)+m.quantity; SalveJarMaker.totalProducts=SalveJarMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SalveJarMaker.maker then SalveJarMaker.maker.itemsMade=SalveJarMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SalveJarMaker.maker.skill=math.min(100,SalveJarMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kozarec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"salve.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SalveJarMaker.update(dt) if not _G.state then return end; SalveJarMaker.dayTimer=SalveJarMaker.dayTimer+dt; if SalveJarMaker.dayTimer>=30 then SalveJarMaker.dayTimer=0; for i=#SalveJarMaker.activeMaking,1,-1 do local m=SalveJarMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SalveJarMaker.completeMaking(m); table.remove(SalveJarMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SalveJarMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SalveJarMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SalveJarMaker.getStats() return {ironStock=SalveJarMaker.ironStock,bronzeStock=SalveJarMaker.bronzeStock,woodStock=SalveJarMaker.woodStock,leatherStock=SalveJarMaker.leatherStock,silverStock=SalveJarMaker.silverStock,goldStock=SalveJarMaker.goldStock,jewelStock=SalveJarMaker.jewelStock,pearlStock=SalveJarMaker.pearlStock,productStock=SalveJarMaker.productStock,numBuildings=#SalveJarMaker.buildings,hasMaker=SalveJarMaker.maker~=nil,makerName=SalveJarMaker.maker and SalveJarMaker.maker.name or "—",makerSkill=SalveJarMaker.maker and SalveJarMaker.maker.skill or 0,activeMaking=#SalveJarMaker.activeMaking,totalProducts=SalveJarMaker.totalProducts} end
return SalveJarMaker
