local GlassShearsMaker = {}
local PRODUCTS = {
    iron_glassshears = { name = "Železni škarde za steklo", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni škarde za steklo za steklarje." },
    bronze_glassshears = { name = "Bronast škarde za steklo", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast škarde za steklo za steklarje." },
    silver_glassshears = { name = "Srebrn škarde za steklo", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn škarde za steklo za steklarje." },
    gilded_glassshears = { name = "Pozlačen škarde za steklo", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen škarde za steklo za steklarje." },
    jewel_set_glassshears = { name = "Draguljast škarde za steklo", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast škarde za steklo za steklarje." },
    royal_sovereign_glassshears = { name = "Kraljevski suveren škarde za steklo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren škarde za steklo z biseri za krono." },
}
local BUILDINGS = {
    glassshears_workshop = { name = "Glassshears delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glassshears_house = { name = "Glassshears hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glassshears_atelier = { name = "Mojstrski glassshears atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glassshears_palace = { name = "Suverena glassshears palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassShearsMaker.ironStock=18; GlassShearsMaker.bronzeStock=14; GlassShearsMaker.woodStock=10; GlassShearsMaker.leatherStock=8; GlassShearsMaker.silverStock=8; GlassShearsMaker.goldStock=6; GlassShearsMaker.jewelStock=4; GlassShearsMaker.pearlStock=4
GlassShearsMaker.productStock = {}; GlassShearsMaker.buildings = {}; GlassShearsMaker.maker = nil; GlassShearsMaker.activeMaking = {}; GlassShearsMaker.totalProducts = 0; GlassShearsMaker.dayTimer = 0
function GlassShearsMaker.init() GlassShearsMaker.ironStock=18; GlassShearsMaker.bronzeStock=14; GlassShearsMaker.woodStock=10; GlassShearsMaker.leatherStock=8; GlassShearsMaker.silverStock=8; GlassShearsMaker.goldStock=6; GlassShearsMaker.jewelStock=4; GlassShearsMaker.pearlStock=4; GlassShearsMaker.productStock={}; GlassShearsMaker.buildings={}; GlassShearsMaker.maker=nil; GlassShearsMaker.activeMaking={}; GlassShearsMaker.totalProducts=0; GlassShearsMaker.dayTimer=0; print("[GlassShearsMaker] Royal Glass Shears Maker System initialized (6 products, 4 buildings)") end
function GlassShearsMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassShearsMaker.maker={name=n or ("Škardar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Škardar najet: %s (spretnost: %d)",GlassShearsMaker.maker.name,s),"success") end; return true end
function GlassShearsMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassShearsMaker.build(id) local ok,e=GlassShearsMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassShearsMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassShearsMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassShearsMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassShearsMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassShearsMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassShearsMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassShearsMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassShearsMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassShearsMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassShearsMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassShearsMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassShearsMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassShearsMaker.buildings==0 then return false,"Potrebna škardna delavnica" end; if not GlassShearsMaker.maker then return false,"Potreben škardar" end; return true end
function GlassShearsMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassShearsMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassShearsMaker.ironStock=GlassShearsMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassShearsMaker.bronzeStock=GlassShearsMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassShearsMaker.woodStock=GlassShearsMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassShearsMaker.leatherStock=GlassShearsMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassShearsMaker.silverStock=GlassShearsMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassShearsMaker.goldStock=GlassShearsMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassShearsMaker.jewelStock=GlassShearsMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassShearsMaker.pearlStock=GlassShearsMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassShearsMaker.maker then t=math.max(1,t-math.floor(GlassShearsMaker.maker.skill/13)) end; table.insert(GlassShearsMaker.activeMaking,{id="glassshears_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassShearsMaker.completeMaking(m) local q=1.0+(GlassShearsMaker.getQualityBonus()/100); if GlassShearsMaker.maker then q=q+(GlassShearsMaker.maker.skill/140) end; q=math.min(2.5,q); GlassShearsMaker.productStock[m.productType]=(GlassShearsMaker.productStock[m.productType] or 0)+m.quantity; GlassShearsMaker.totalProducts=GlassShearsMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassShearsMaker.maker then GlassShearsMaker.maker.itemsMade=GlassShearsMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassShearsMaker.maker.skill=math.min(100,GlassShearsMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Škarde izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glassshears.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassShearsMaker.update(dt) if not _G.state then return end; GlassShearsMaker.dayTimer=GlassShearsMaker.dayTimer+dt; if GlassShearsMaker.dayTimer>=30 then GlassShearsMaker.dayTimer=0; for i=#GlassShearsMaker.activeMaking,1,-1 do local m=GlassShearsMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassShearsMaker.completeMaking(m); table.remove(GlassShearsMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassShearsMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassShearsMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassShearsMaker.getStats() return {ironStock=GlassShearsMaker.ironStock,bronzeStock=GlassShearsMaker.bronzeStock,woodStock=GlassShearsMaker.woodStock,leatherStock=GlassShearsMaker.leatherStock,silverStock=GlassShearsMaker.silverStock,goldStock=GlassShearsMaker.goldStock,jewelStock=GlassShearsMaker.jewelStock,pearlStock=GlassShearsMaker.pearlStock,productStock=GlassShearsMaker.productStock,numBuildings=#GlassShearsMaker.buildings,hasMaker=GlassShearsMaker.maker~=nil,makerName=GlassShearsMaker.maker and GlassShearsMaker.maker.name or "—",makerSkill=GlassShearsMaker.maker and GlassShearsMaker.maker.skill or 0,activeMaking=#GlassShearsMaker.activeMaking,totalProducts=GlassShearsMaker.totalProducts} end
return GlassShearsMaker
