local LawnAeratorMaker = {}
local PRODUCTS = {
    iron_lawnaerator = { name = "Železni zračilec travnikov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni zračilec travnikov za vrtnarje." },
    bronze_lawnaerator = { name = "Bronast zračilec travnikov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast zračilec travnikov za vrtnarje." },
    silver_lawnaerator = { name = "Srebrn zračilec travnikov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn zračilec travnikov za vrtnarje." },
    gilded_lawnaerator = { name = "Pozlačen zračilec travnikov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen zračilec travnikov za vrtnarje." },
    jewel_set_lawnaerator = { name = "Draguljast zračilec travnikov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast zračilec travnikov za vrtnarje." },
    royal_sovereign_lawnaerator = { name = "Kraljevski suveren zračilec travnikov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren zračilec travnikov z biseri za krono." },
}
local BUILDINGS = {
    lawnaerator_workshop = { name = "Lawnaerator delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    lawnaerator_house = { name = "Lawnaerator hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_lawnaerator_atelier = { name = "Mojstrski lawnaerator atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_lawnaerator_palace = { name = "Suverena lawnaerator palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
LawnAeratorMaker.ironStock=16; LawnAeratorMaker.bronzeStock=12; LawnAeratorMaker.woodStock=14; LawnAeratorMaker.leatherStock=8; LawnAeratorMaker.silverStock=8; LawnAeratorMaker.goldStock=6; LawnAeratorMaker.jewelStock=4; LawnAeratorMaker.pearlStock=4
LawnAeratorMaker.productStock = {}; LawnAeratorMaker.buildings = {}; LawnAeratorMaker.maker = nil; LawnAeratorMaker.activeMaking = {}; LawnAeratorMaker.totalProducts = 0; LawnAeratorMaker.dayTimer = 0
function LawnAeratorMaker.init() LawnAeratorMaker.ironStock=16; LawnAeratorMaker.bronzeStock=12; LawnAeratorMaker.woodStock=14; LawnAeratorMaker.leatherStock=8; LawnAeratorMaker.silverStock=8; LawnAeratorMaker.goldStock=6; LawnAeratorMaker.jewelStock=4; LawnAeratorMaker.pearlStock=4; LawnAeratorMaker.productStock={}; LawnAeratorMaker.buildings={}; LawnAeratorMaker.maker=nil; LawnAeratorMaker.activeMaking={}; LawnAeratorMaker.totalProducts=0; LawnAeratorMaker.dayTimer=0; print("[LawnAeratorMaker] Royal Lawn Aerator Maker System initialized (6 products, 4 buildings)") end
function LawnAeratorMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LawnAeratorMaker.maker={name=n or ("Zračnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zračnik najet: %s (spretnost: %d)",LawnAeratorMaker.maker.name,s),"success") end; return true end
function LawnAeratorMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LawnAeratorMaker.build(id) local ok,e=LawnAeratorMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LawnAeratorMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LawnAeratorMaker.getQualityBonus() local b=0; for _,bd in ipairs(LawnAeratorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LawnAeratorMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and LawnAeratorMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and LawnAeratorMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and LawnAeratorMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and LawnAeratorMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and LawnAeratorMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and LawnAeratorMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and LawnAeratorMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and LawnAeratorMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #LawnAeratorMaker.buildings==0 then return false,"Potrebna zračilna delavnica" end; if not LawnAeratorMaker.maker then return false,"Potreben zračnik" end; return true end
function LawnAeratorMaker.make(pt,qty) qty=qty or 1; local ok,e=LawnAeratorMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then LawnAeratorMaker.ironStock=LawnAeratorMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then LawnAeratorMaker.bronzeStock=LawnAeratorMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then LawnAeratorMaker.woodStock=LawnAeratorMaker.woodStock-d.woodCost*qty end; if d.leatherCost then LawnAeratorMaker.leatherStock=LawnAeratorMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then LawnAeratorMaker.silverStock=LawnAeratorMaker.silverStock-d.silverCost*qty end; if d.goldCost then LawnAeratorMaker.goldStock=LawnAeratorMaker.goldStock-d.goldCost*qty end; if d.jewelCost then LawnAeratorMaker.jewelStock=LawnAeratorMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then LawnAeratorMaker.pearlStock=LawnAeratorMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if LawnAeratorMaker.maker then t=math.max(1,t-math.floor(LawnAeratorMaker.maker.skill/13)) end; table.insert(LawnAeratorMaker.activeMaking,{id="lawnaerator_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LawnAeratorMaker.completeMaking(m) local q=1.0+(LawnAeratorMaker.getQualityBonus()/100); if LawnAeratorMaker.maker then q=q+(LawnAeratorMaker.maker.skill/140) end; q=math.min(2.5,q); LawnAeratorMaker.productStock[m.productType]=(LawnAeratorMaker.productStock[m.productType] or 0)+m.quantity; LawnAeratorMaker.totalProducts=LawnAeratorMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LawnAeratorMaker.maker then LawnAeratorMaker.maker.itemsMade=LawnAeratorMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then LawnAeratorMaker.maker.skill=math.min(100,LawnAeratorMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Zračilec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"lawnaerator.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function LawnAeratorMaker.update(dt) if not _G.state then return end; LawnAeratorMaker.dayTimer=LawnAeratorMaker.dayTimer+dt; if LawnAeratorMaker.dayTimer>=30 then LawnAeratorMaker.dayTimer=0; for i=#LawnAeratorMaker.activeMaking,1,-1 do local m=LawnAeratorMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LawnAeratorMaker.completeMaking(m); table.remove(LawnAeratorMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LawnAeratorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LawnAeratorMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LawnAeratorMaker.getStats() return {ironStock=LawnAeratorMaker.ironStock,bronzeStock=LawnAeratorMaker.bronzeStock,woodStock=LawnAeratorMaker.woodStock,leatherStock=LawnAeratorMaker.leatherStock,silverStock=LawnAeratorMaker.silverStock,goldStock=LawnAeratorMaker.goldStock,jewelStock=LawnAeratorMaker.jewelStock,pearlStock=LawnAeratorMaker.pearlStock,productStock=LawnAeratorMaker.productStock,numBuildings=#LawnAeratorMaker.buildings,hasMaker=LawnAeratorMaker.maker~=nil,makerName=LawnAeratorMaker.maker and LawnAeratorMaker.maker.name or "—",makerSkill=LawnAeratorMaker.maker and LawnAeratorMaker.maker.skill or 0,activeMaking=#LawnAeratorMaker.activeMaking,totalProducts=LawnAeratorMaker.totalProducts} end
return LawnAeratorMaker
