local IronBeamMaker = {}
local PRODUCTS = {
    simple_iron_beam = { name = "Preprost železni tram", ironCost = 4, time = 5, cost = 100, defense = 18, happiness = 1, description = "Preprost železni tram za gradnjo." },
    riveted_steel_beam = { name = "Zakovučeni jekleni tram", ironCost = 3, steelCost = 3, time = 8, cost = 280, defense = 32, happiness = 2, prestige = 2, description = "Zakovučeni jekleni tram za trgovce." },
    silver_painted_beam = { name = "Srebrnopolirana tram", ironCost = 3, steelCost = 2, silverCost = 1, time = 11, cost = 680, defense = 45, happiness = 2, prestige = 6, description = "Srebrnopolirana tram za plemiče." },
    gold_trimmed_beam = { name = "Zlatookrasna tram", ironCost = 3, steelCost = 2, goldCost = 1, silverCost = 1, time = 15, cost = 1500, defense = 58, happiness = 3, prestige = 14, description = "Zlatookrasna tram za visoke plemiče." },
    jewel_set_beam = { name = "Draguljasta tram", ironCost = 3, steelCost = 2, goldCost = 2, silverCost = 1, jewelCost = 1, time = 19, cost = 3200, defense = 72, happiness = 5, prestige = 27, description = "Tram z draguljem za visoko plemstvo." },
    royal_grand_beam = { name = "Kraljevski veliki tram", ironCost = 5, steelCost = 3, goldCost = 3, silverCost = 2, jewelCost = 2, pearlCost = 2, time = 26, cost = 7000, defense = 92, happiness = 12, prestige = 58, description = "Veliki kraljevski tram z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    beam_workshop = { name = "Tramska delavnica", cost = { gold = 280, wood = 100, stone = 160, iron = 8 }, upkeep = 6, qualityBonus = 5 },
    foundry_loft = { name = "Livarna podstrešje", cost = { gold = 1000, wood = 240, stone = 320, steel = 6, silver = 6 }, upkeep = 23, qualityBonus = 18 },
    master_foundry_atelier = { name = "Mojstrski livarski atelje", cost = { gold = 2800, wood = 360, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_foundry_palace = { name = "Kraljevska livarska palača", cost = { gold = 12000, wood = 580, stone = 800, gold = 80, jewel = 18 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
IronBeamMaker.ironStock = 20; IronBeamMaker.steelStock = 14; IronBeamMaker.silverStock = 6; IronBeamMaker.goldStock = 6; IronBeamMaker.jewelStock = 4; IronBeamMaker.pearlStock = 4
IronBeamMaker.productStock = {}; IronBeamMaker.buildings = {}; IronBeamMaker.maker = nil; IronBeamMaker.activeMaking = {}; IronBeamMaker.totalProducts = 0; IronBeamMaker.dayTimer = 0
function IronBeamMaker.init() IronBeamMaker.ironStock=20; IronBeamMaker.steelStock=14; IronBeamMaker.silverStock=6; IronBeamMaker.goldStock=6; IronBeamMaker.jewelStock=4; IronBeamMaker.pearlStock=4; IronBeamMaker.productStock={}; IronBeamMaker.buildings={}; IronBeamMaker.maker=nil; IronBeamMaker.activeMaking={}; IronBeamMaker.totalProducts=0; IronBeamMaker.dayTimer=0; print("[IronBeamMaker] Royal Iron Beam Maker System initialized (6 products, 4 buildings)") end
function IronBeamMaker.hireMaker(n,s) s=s or math.random(55,90); local c=560+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; IronBeamMaker.maker={name=n or ("Tramar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tramar najet: %s (spretnost: %d)",IronBeamMaker.maker.name,s),"success") end; return true end
function IronBeamMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function IronBeamMaker.build(id) local ok,e=IronBeamMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(IronBeamMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function IronBeamMaker.getQualityBonus() local b=0; for _,bd in ipairs(IronBeamMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function IronBeamMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and IronBeamMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and IronBeamMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.silverCost and IronBeamMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and IronBeamMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and IronBeamMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and IronBeamMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #IronBeamMaker.buildings==0 then return false,"Potrebna tramska delavnica" end; if not IronBeamMaker.maker then return false,"Potreben tramar" end; return true end
function IronBeamMaker.make(pt,qty) qty=qty or 1; local ok,e=IronBeamMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then IronBeamMaker.ironStock=IronBeamMaker.ironStock-d.ironCost*qty end; if d.steelCost then IronBeamMaker.steelStock=IronBeamMaker.steelStock-d.steelCost*qty end; if d.silverCost then IronBeamMaker.silverStock=IronBeamMaker.silverStock-d.silverCost*qty end; if d.goldCost then IronBeamMaker.goldStock=IronBeamMaker.goldStock-d.goldCost*qty end; if d.jewelCost then IronBeamMaker.jewelStock=IronBeamMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then IronBeamMaker.pearlStock=IronBeamMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if IronBeamMaker.maker then t=math.max(1,t-math.floor(IronBeamMaker.maker.skill/12)) end; table.insert(IronBeamMaker.activeMaking,{id="beam_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,defense=d.defense or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Litje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function IronBeamMaker.completeMaking(m) local q=1.0+(IronBeamMaker.getQualityBonus()/100); if IronBeamMaker.maker then q=q+(IronBeamMaker.maker.skill/140) end; q=math.min(2.5,q); IronBeamMaker.productStock[m.productType]=(IronBeamMaker.productStock[m.productType] or 0)+m.quantity; IronBeamMaker.totalProducts=IronBeamMaker.totalProducts+m.quantity; if m.defense>0 and _G.state then _G.state.defense=(_G.state.defense or 0)+m.defense end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if IronBeamMaker.maker then IronBeamMaker.maker.itemsMade=IronBeamMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then IronBeamMaker.maker.skill=math.min(100,IronBeamMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Tram izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"beam.completed",{productName=m.productName,defense=m.defense,prestige=m.prestige,happiness=m.happiness}) end end
function IronBeamMaker.update(dt) if not _G.state then return end; IronBeamMaker.dayTimer=IronBeamMaker.dayTimer+dt; if IronBeamMaker.dayTimer>=30 then IronBeamMaker.dayTimer=0; for i=#IronBeamMaker.activeMaking,1,-1 do local m=IronBeamMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then IronBeamMaker.completeMaking(m); table.remove(IronBeamMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(IronBeamMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if IronBeamMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function IronBeamMaker.getStats() return {ironStock=IronBeamMaker.ironStock,steelStock=IronBeamMaker.steelStock,silverStock=IronBeamMaker.silverStock,goldStock=IronBeamMaker.goldStock,jewelStock=IronBeamMaker.jewelStock,pearlStock=IronBeamMaker.pearlStock,productStock=IronBeamMaker.productStock,numBuildings=#IronBeamMaker.buildings,hasMaker=IronBeamMaker.maker~=nil,makerName=IronBeamMaker.maker and IronBeamMaker.maker.name or "—",makerSkill=IronBeamMaker.maker and IronBeamMaker.maker.skill or 0,activeMaking=#IronBeamMaker.activeMaking,totalProducts=IronBeamMaker.totalProducts} end
return IronBeamMaker
