local HuntingTrapMaker = {}
local PRODUCTS = {
    simple_iron_snare = { name = "Preprosta železna zanka", ironCost = 1, ropeCost = 1, time = 2, cost = 30, attack = 8, happiness = 1, description = "Preprosta železna zanka za male živali." },
    steel_jaw_trap = { name = "Jeklenovelikostna past", ironCost = 2, steelCost = 1, ropeCost = 1, time = 5, cost = 110, attack = 18, happiness = 1, prestige = 2, description = "Jeklenovelikostna past za trgovce." },
    silver_sprung_trap = { name = "Srebrnonosilna past", ironCost = 2, silverCost = 1, steelCost = 1, ropeCost = 1, time = 8, cost = 280, attack = 28, happiness = 2, prestige = 6, description = "Srebrnonosilna past za plemiče." },
    gold_trimmed_bear_trap = { name = "Zlatookrasna medvedja past", ironCost = 3, goldCost = 1, silverCost = 1, steelCost = 1, ropeCost = 1, time = 12, cost = 680, attack = 40, happiness = 3, prestige = 14, description = "Zlatookrasna medvedja past za visoke plemiče." },
    jewel_pinned_trap = { name = "Draguljnopripeta past", ironCost = 3, goldCost = 1, silverCost = 1, steelCost = 1, ropeCost = 1, jewelCost = 1, time = 16, cost = 1500, attack = 52, happiness = 5, prestige = 27, description = "Past s draguljno priponko za visoko plemstvo." },
    royal_grand_trap_set = { name = "Kraljevski veliki set pasti", ironCost = 4, goldCost = 2, silverCost = 2, steelCost = 2, ropeCost = 1, jewelCost = 2, pearlCost = 2, time = 23, cost = 3400, attack = 68, happiness = 12, prestige = 58, description = "Veliki kraljevski set pasti z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    trap_workshop = { name = "Pastna delavnica", cost = { gold = 240, wood = 100, stone = 120, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    trapping_loft = { name = "Pastna podstrešje", cost = { gold = 880, wood = 240, stone = 240, steel = 6, rope = 6 }, upkeep = 20, qualityBonus = 18 },
    master_trapper_atelier = { name = "Mojstrski pastirski atelje", cost = { gold = 2500, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 58, qualityBonus = 30 },
    royal_trapping_palace = { name = "Kraljevska pastna palača", cost = { gold = 10500, wood = 580, stone = 760, gold = 65, jewel = 16 }, upkeep = 210, qualityBonus = 55, prestigeBonus = 50 },
}
HuntingTrapMaker.ironStock = 14; HuntingTrapMaker.steelStock = 10; HuntingTrapMaker.ropeStock = 12; HuntingTrapMaker.silverStock = 6; HuntingTrapMaker.goldStock = 6; HuntingTrapMaker.jewelStock = 4; HuntingTrapMaker.pearlStock = 4
HuntingTrapMaker.productStock = {}; HuntingTrapMaker.buildings = {}; HuntingTrapMaker.maker = nil; HuntingTrapMaker.activeMaking = {}; HuntingTrapMaker.totalProducts = 0; HuntingTrapMaker.dayTimer = 0
function HuntingTrapMaker.init() HuntingTrapMaker.ironStock=14; HuntingTrapMaker.steelStock=10; HuntingTrapMaker.ropeStock=12; HuntingTrapMaker.silverStock=6; HuntingTrapMaker.goldStock=6; HuntingTrapMaker.jewelStock=4; HuntingTrapMaker.pearlStock=4; HuntingTrapMaker.productStock={}; HuntingTrapMaker.buildings={}; HuntingTrapMaker.maker=nil; HuntingTrapMaker.activeMaking={}; HuntingTrapMaker.totalProducts=0; HuntingTrapMaker.dayTimer=0; print("[HuntingTrapMaker] Royal Hunting Trap Maker System initialized (6 products, 4 buildings)") end
function HuntingTrapMaker.hireMaker(n,s) s=s or math.random(55,90); local c=500+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HuntingTrapMaker.maker={name=n or ("Pastir "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pastir najet: %s (spretnost: %d)",HuntingTrapMaker.maker.name,s),"success") end; return true end
function HuntingTrapMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HuntingTrapMaker.build(id) local ok,e=HuntingTrapMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HuntingTrapMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HuntingTrapMaker.getQualityBonus() local b=0; for _,bd in ipairs(HuntingTrapMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HuntingTrapMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and HuntingTrapMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and HuntingTrapMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.ropeCost and HuntingTrapMaker.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.silverCost and HuntingTrapMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HuntingTrapMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HuntingTrapMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HuntingTrapMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HuntingTrapMaker.buildings==0 then return false,"Potrebna pastna delavnica" end; if not HuntingTrapMaker.maker then return false,"Potreben pastir" end; return true end
function HuntingTrapMaker.make(pt,qty) qty=qty or 1; local ok,e=HuntingTrapMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then HuntingTrapMaker.ironStock=HuntingTrapMaker.ironStock-d.ironCost*qty end; if d.steelCost then HuntingTrapMaker.steelStock=HuntingTrapMaker.steelStock-d.steelCost*qty end; if d.ropeCost then HuntingTrapMaker.ropeStock=HuntingTrapMaker.ropeStock-d.ropeCost*qty end; if d.silverCost then HuntingTrapMaker.silverStock=HuntingTrapMaker.silverStock-d.silverCost*qty end; if d.goldCost then HuntingTrapMaker.goldStock=HuntingTrapMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HuntingTrapMaker.jewelStock=HuntingTrapMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HuntingTrapMaker.pearlStock=HuntingTrapMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HuntingTrapMaker.maker then t=math.max(1,t-math.floor(HuntingTrapMaker.maker.skill/13)) end; table.insert(HuntingTrapMaker.activeMaking,{id="trap_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,attack=d.attack or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HuntingTrapMaker.completeMaking(m) local q=1.0+(HuntingTrapMaker.getQualityBonus()/100); if HuntingTrapMaker.maker then q=q+(HuntingTrapMaker.maker.skill/140) end; q=math.min(2.5,q); HuntingTrapMaker.productStock[m.productType]=(HuntingTrapMaker.productStock[m.productType] or 0)+m.quantity; HuntingTrapMaker.totalProducts=HuntingTrapMaker.totalProducts+m.quantity; if m.attack>0 and _G.state then _G.state.attack=(_G.state.attack or 0)+m.attack end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HuntingTrapMaker.maker then HuntingTrapMaker.maker.itemsMade=HuntingTrapMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then HuntingTrapMaker.maker.skill=math.min(100,HuntingTrapMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Past izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"trap.completed",{productName=m.productName,attack=m.attack,prestige=m.prestige,happiness=m.happiness}) end end
function HuntingTrapMaker.update(dt) if not _G.state then return end; HuntingTrapMaker.dayTimer=HuntingTrapMaker.dayTimer+dt; if HuntingTrapMaker.dayTimer>=30 then HuntingTrapMaker.dayTimer=0; for i=#HuntingTrapMaker.activeMaking,1,-1 do local m=HuntingTrapMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HuntingTrapMaker.completeMaking(m); table.remove(HuntingTrapMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HuntingTrapMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HuntingTrapMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HuntingTrapMaker.getStats() return {ironStock=HuntingTrapMaker.ironStock,steelStock=HuntingTrapMaker.steelStock,ropeStock=HuntingTrapMaker.ropeStock,silverStock=HuntingTrapMaker.silverStock,goldStock=HuntingTrapMaker.goldStock,jewelStock=HuntingTrapMaker.jewelStock,pearlStock=HuntingTrapMaker.pearlStock,productStock=HuntingTrapMaker.productStock,numBuildings=#HuntingTrapMaker.buildings,hasMaker=HuntingTrapMaker.maker~=nil,makerName=HuntingTrapMaker.maker and HuntingTrapMaker.maker.name or "—",makerSkill=HuntingTrapMaker.maker and HuntingTrapMaker.maker.skill or 0,activeMaking=#HuntingTrapMaker.activeMaking,totalProducts=HuntingTrapMaker.totalProducts} end
return HuntingTrapMaker
