local PotteryKiln = {}
local PRODUCTS = {
    earthenware = { name = "Glina lončenaina", clayCost = 3, time = 2, cost = 16, durability = 30, happiness = 1, description = "Preprosta glinena posoda." },
    stoneware = { name = "Kamnina", clayCost = 4, fuelCost = 2, time = 4, cost = 45, durability = 55, prestige = 1, happiness = 2, description = "Kamnina z žgano glino." },
    glazed_pottery = { name = "Glazirana lončeniina", clayCost = 4, glassCost = 1, fuelCost = 2, time = 5, cost = 100, durability = 70, prestige = 3, happiness = 2, description = "Glazirana lončeniina za vsakdanjo rabo." },
    porcelain = { name = "Porcelan", kaolinCost = 3, glassCost = 1, fuelCost = 2, time = 7, cost = 240, durability = 80, prestige = 6, happiness = 3, description = "Porcelan iz kaolina za plemiče." },
    silver_rim_pottery = { name = "Srebrno obrobljena lončeniina", kaolinCost = 4, silverCost = 1, glassCost = 1, fuelCost = 2, time = 10, cost = 520, durability = 90, prestige = 12, happiness = 4, description = "Lončeniina s srebrnim obroblom za visoke plemiče." },
    royal_grand_pottery = { name = "Kraljevski veliki lončeniina", kaolinCost = 6, goldCost = 1, silverCost = 1, jewelCost = 1, glassCost = 1, fuelCost = 3, time = 15, cost = 1700, durability = 100, prestige = 36, happiness = 9, description = "Velika kraljevska lončeniina z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Lončarska delavnica", cost = { gold = 260, wood = 130, stone = 250 }, upkeep = 6, qualityBonus = 5 },
    kiln = { name = "Lončarska peč", cost = { gold = 900, wood = 280, stone = 500, clay = 10 }, upkeep = 22, qualityBonus = 18 },
    glazing_house = { name = "Glazirnica", cost = { gold = 2200, wood = 350, stone = 700, silver = 30, glass = 8 }, upkeep = 55, qualityBonus = 30 },
    royal_pottery_atelier = { name = "Kraljevski atelje lončeniine", cost = { gold = 9000, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
PotteryKiln.clayStock = 22; PotteryKiln.kaolinStock = 16; PotteryKiln.glassStock = 12; PotteryKiln.fuelStock = 16; PotteryKiln.silverStock = 8; PotteryKiln.goldStock = 6; PotteryKiln.jewelStock = 6
PotteryKiln.productStock = {}; PotteryKiln.buildings = {}; PotteryKiln.maker = nil; PotteryKiln.activeMaking = {}; PotteryKiln.totalProducts = 0; PotteryKiln.dayTimer = 0
function PotteryKiln.init() PotteryKiln.clayStock=22; PotteryKiln.kaolinStock=16; PotteryKiln.glassStock=12; PotteryKiln.fuelStock=16; PotteryKiln.silverStock=8; PotteryKiln.goldStock=6; PotteryKiln.jewelStock=6; PotteryKiln.productStock={}; PotteryKiln.buildings={}; PotteryKiln.maker=nil; PotteryKiln.activeMaking={}; PotteryKiln.totalProducts=0; PotteryKiln.dayTimer=0; print("[PotteryKiln] Royal Pottery Kiln System initialized (6 products, 4 buildings)") end
function PotteryKiln.hireMaker(n,s) s=s or math.random(50,90); local c=510+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PotteryKiln.maker={name=n or ("Lončar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lončar najet: %s (spretnost: %d)",PotteryKiln.maker.name,s),"success") end; return true end
function PotteryKiln.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PotteryKiln.build(id) local ok,e=PotteryKiln.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PotteryKiln.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PotteryKiln.getQualityBonus() local b=0; for _,bd in ipairs(PotteryKiln.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PotteryKiln.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.clayCost and PotteryKiln.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.kaolinCost and PotteryKiln.kaolinStock<(d.kaolinCost or 0) then return false,"Premalo kaolina" end; if d.glassCost and PotteryKiln.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.fuelCost and PotteryKiln.fuelStock<(d.fuelCost or 0) then return false,"Premalo goriva" end; if d.silverCost and PotteryKiln.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PotteryKiln.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PotteryKiln.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #PotteryKiln.buildings==0 then return false,"Potrebna delavnica" end; if not PotteryKiln.maker then return false,"Potreben lončar" end; return true end
function PotteryKiln.make(pt,qty) qty=qty or 5; local ok,e=PotteryKiln.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.clayCost then PotteryKiln.clayStock=PotteryKiln.clayStock-d.clayCost*qty end; if d.kaolinCost then PotteryKiln.kaolinStock=PotteryKiln.kaolinStock-d.kaolinCost*qty end; if d.glassCost then PotteryKiln.glassStock=PotteryKiln.glassStock-d.glassCost*qty end; if d.fuelCost then PotteryKiln.fuelStock=PotteryKiln.fuelStock-d.fuelCost*qty end; if d.silverCost then PotteryKiln.silverStock=PotteryKiln.silverStock-d.silverCost*qty end; if d.goldCost then PotteryKiln.goldStock=PotteryKiln.goldStock-d.goldCost*qty end; if d.jewelCost then PotteryKiln.jewelStock=PotteryKiln.jewelStock-d.jewelCost*qty end; local t=d.time; if PotteryKiln.maker then t=math.max(1,t-math.floor(PotteryKiln.maker.skill/12)) end; table.insert(PotteryKiln.activeMaking,{id="pottery_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,durability=d.durability or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PotteryKiln.completeMaking(m) local q=1.0+(PotteryKiln.getQualityBonus()/100); if PotteryKiln.maker then q=q+(PotteryKiln.maker.skill/180) end; q=math.min(2.0,q); PotteryKiln.productStock[m.productType]=(PotteryKiln.productStock[m.productType] or 0)+m.quantity; PotteryKiln.totalProducts=PotteryKiln.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PotteryKiln.maker then PotteryKiln.maker.itemsMade=PotteryKiln.maker.itemsMade+m.quantity; if math.random()<0.20 then PotteryKiln.maker.skill=math.min(100,PotteryKiln.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lončeniina izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"pottery.completed",{productName=m.productName,durability=m.durability,happiness=m.happiness}) end end
function PotteryKiln.update(dt) if not _G.state then return end; PotteryKiln.dayTimer=PotteryKiln.dayTimer+dt; if PotteryKiln.dayTimer>=30 then PotteryKiln.dayTimer=0; for i=#PotteryKiln.activeMaking,1,-1 do local m=PotteryKiln.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PotteryKiln.completeMaking(m); table.remove(PotteryKiln.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PotteryKiln.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PotteryKiln.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PotteryKiln.getStats() return {clayStock=PotteryKiln.clayStock,kaolinStock=PotteryKiln.kaolinStock,glassStock=PotteryKiln.glassStock,fuelStock=PotteryKiln.fuelStock,silverStock=PotteryKiln.silverStock,goldStock=PotteryKiln.goldStock,jewelStock=PotteryKiln.jewelStock,productStock=PotteryKiln.productStock,numBuildings=#PotteryKiln.buildings,hasMaker=PotteryKiln.maker~=nil,makerName=PotteryKiln.maker and PotteryKiln.maker.name or "—",makerSkill=PotteryKiln.maker and PotteryKiln.maker.skill or 0,activeMaking=#PotteryKiln.activeMaking,totalProducts=PotteryKiln.totalProducts} end
return PotteryKiln
