local CabinetMaker = {}
local PRODUCTS = {
    simple_pine_cabinet = { name = "Preprost borova omara", woodCost = 4, ironCost = 1, time = 5, cost = 90, beauty = 22, happiness = 1, description = "Preprost borova omara za hišo." },
    carved_oak_cabinet = { name = "Izrezljana hrastova omara", woodCost = 4, ironCost = 1, leatherCost = 1, time = 8, cost = 240, beauty = 38, happiness = 2, prestige = 2, description = "Izrezljana hrastova omara za trgovce." },
    silver_handle_cabinet = { name = "Srebrnorokavnata omara", woodCost = 4, silverCost = 1, ironCost = 1, leatherCost = 1, time = 11, cost = 580, beauty = 52, happiness = 2, prestige = 6, description = "Srebrnorokavnata omara za plemiče." },
    gold_trimmed_cabinet = { name = "Zlatookrasna omara", woodCost = 5, goldCost = 1, silverCost = 1, ironCost = 1, leatherCost = 1, time = 15, cost = 1300, beauty = 65, happiness = 3, prestige = 14, description = "Zlatookrasna omara za visoke plemiče." },
    jewel_set_cabinet = { name = "Draguljasta omara", woodCost = 5, goldCost = 2, silverCost = 1, ironCost = 1, leatherCost = 1, jewelCost = 1, time = 19, cost = 2900, beauty = 78, happiness = 5, prestige = 27, description = "Omara z draguljem za visoko plemstvo." },
    royal_grand_cabinet = { name = "Kraljevski veliki omara", woodCost = 7, goldCost = 3, silverCost = 2, ironCost = 1, leatherCost = 1, jewelCost = 2, pearlCost = 2, time = 26, cost = 6200, beauty = 92, happiness = 12, prestige = 58, description = "Veliki kraljevska omara z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    cabinet_workshop = { name = "Omaraska delavnica", cost = { gold = 260, wood = 180, stone = 100, iron = 4 }, upkeep = 6, qualityBonus = 5 },
    furniture_loft = { name = "Pohištvena podstrešje", cost = { gold = 950, wood = 340, stone = 220, silver = 6, leather = 6 }, upkeep = 22, qualityBonus = 18 },
    master_cabinet_atelier = { name = "Mojstrski omarski atelje", cost = { gold = 2700, wood = 380, stone = 480, silver = 30, gold = 6 }, upkeep = 62, qualityBonus = 30 },
    royal_cabinet_palace = { name = "Kraljevska omarska palača", cost = { gold = 11500, wood = 600, stone = 760, gold = 75, jewel = 18 }, upkeep = 230, qualityBonus = 55, prestigeBonus = 50 },
}
CabinetMaker.woodStock = 22; CabinetMaker.ironStock = 10; CabinetMaker.leatherStock = 10; CabinetMaker.silverStock = 6; CabinetMaker.goldStock = 6; CabinetMaker.jewelStock = 4; CabinetMaker.pearlStock = 4
CabinetMaker.productStock = {}; CabinetMaker.buildings = {}; CabinetMaker.maker = nil; CabinetMaker.activeMaking = {}; CabinetMaker.totalProducts = 0; CabinetMaker.dayTimer = 0
function CabinetMaker.init() CabinetMaker.woodStock=22; CabinetMaker.ironStock=10; CabinetMaker.leatherStock=10; CabinetMaker.silverStock=6; CabinetMaker.goldStock=6; CabinetMaker.jewelStock=4; CabinetMaker.pearlStock=4; CabinetMaker.productStock={}; CabinetMaker.buildings={}; CabinetMaker.maker=nil; CabinetMaker.activeMaking={}; CabinetMaker.totalProducts=0; CabinetMaker.dayTimer=0; print("[CabinetMaker] Royal Cabinet Maker System initialized (6 products, 4 buildings)") end
function CabinetMaker.hireMaker(n,s) s=s or math.random(55,90); local c=540+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CabinetMaker.maker={name=n or ("Omarar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Omarar najet: %s (spretnost: %d)",CabinetMaker.maker.name,s),"success") end; return true end
function CabinetMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CabinetMaker.build(id) local ok,e=CabinetMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CabinetMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CabinetMaker.getQualityBonus() local b=0; for _,bd in ipairs(CabinetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CabinetMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and CabinetMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and CabinetMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.leatherCost and CabinetMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CabinetMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CabinetMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CabinetMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CabinetMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CabinetMaker.buildings==0 then return false,"Potrebna omaraska delavnica" end; if not CabinetMaker.maker then return false,"Potreben omarar" end; return true end
function CabinetMaker.make(pt,qty) qty=qty or 1; local ok,e=CabinetMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then CabinetMaker.woodStock=CabinetMaker.woodStock-d.woodCost*qty end; if d.ironCost then CabinetMaker.ironStock=CabinetMaker.ironStock-d.ironCost*qty end; if d.leatherCost then CabinetMaker.leatherStock=CabinetMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CabinetMaker.silverStock=CabinetMaker.silverStock-d.silverCost*qty end; if d.goldCost then CabinetMaker.goldStock=CabinetMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CabinetMaker.jewelStock=CabinetMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CabinetMaker.pearlStock=CabinetMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CabinetMaker.maker then t=math.max(1,t-math.floor(CabinetMaker.maker.skill/12)) end; table.insert(CabinetMaker.activeMaking,{id="cabinet_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,beauty=d.beauty or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CabinetMaker.completeMaking(m) local q=1.0+(CabinetMaker.getQualityBonus()/100); if CabinetMaker.maker then q=q+(CabinetMaker.maker.skill/140) end; q=math.min(2.5,q); CabinetMaker.productStock[m.productType]=(CabinetMaker.productStock[m.productType] or 0)+m.quantity; CabinetMaker.totalProducts=CabinetMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CabinetMaker.maker then CabinetMaker.maker.itemsMade=CabinetMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CabinetMaker.maker.skill=math.min(100,CabinetMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Omara izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"cabinet.completed",{productName=m.productName,beauty=m.beauty,prestige=m.prestige,happiness=m.happiness}) end end
function CabinetMaker.update(dt) if not _G.state then return end; CabinetMaker.dayTimer=CabinetMaker.dayTimer+dt; if CabinetMaker.dayTimer>=30 then CabinetMaker.dayTimer=0; for i=#CabinetMaker.activeMaking,1,-1 do local m=CabinetMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CabinetMaker.completeMaking(m); table.remove(CabinetMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CabinetMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CabinetMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CabinetMaker.getStats() return {woodStock=CabinetMaker.woodStock,ironStock=CabinetMaker.ironStock,leatherStock=CabinetMaker.leatherStock,silverStock=CabinetMaker.silverStock,goldStock=CabinetMaker.goldStock,jewelStock=CabinetMaker.jewelStock,pearlStock=CabinetMaker.pearlStock,productStock=CabinetMaker.productStock,numBuildings=#CabinetMaker.buildings,hasMaker=CabinetMaker.maker~=nil,makerName=CabinetMaker.maker and CabinetMaker.maker.name or "—",makerSkill=CabinetMaker.maker and CabinetMaker.maker.skill or 0,activeMaking=#CabinetMaker.activeMaking,totalProducts=CabinetMaker.totalProducts} end
return CabinetMaker
