local ParchmentRackMaker = {}
local PRODUCTS = {
    iron_parchment_rack = { name = "Železno stojalo za pergament", ironCost = 2, woodCost = 3, leatherCost = 1, time = 5, cost = 150, prestige = 3, happiness = 2, description = "Železno stojalo za shranjevanje pergamenta." },
    bronze_parchment_rack = { name = "Bronasto stojalo za pergament", bronzeCost = 2, ironCost = 1, woodCost = 3, leatherCost = 1, time = 7, cost = 365, prestige = 5, happiness = 3, description = "Bronasto stojalo za pisarne." },
    silver_parchment_rack = { name = "Srebrno stojalo za pergament", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 3, leatherCost = 1, time = 11, cost = 880, prestige = 10, happiness = 4, description = "Srebrno stojalo za plemiške pisarje." },
    gilded_parchment_rack = { name = "Pozlačeno stojalo za pergament", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 15, cost = 1900, prestige = 19, happiness = 5, description = "Pozlačeno stojalo za dvorne pisarje." },
    jewel_set_parchment_rack = { name = "Draguljasto stojalo za pergament", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 19, cost = 4100, prestige = 35, happiness = 7, description = "Draguljasto stojalo za kraljevske pisarje." },
    royal_sovereign_parchment_rack = { name = "Kraljevski suvereno stojalo za pergament", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 4, leatherCost = 1, time = 26, cost = 8800, prestige = 67, happiness = 13, description = "Suvereno stojalo z biseri za krono." },
}
local BUILDINGS = {
    parchmentrack_workshop = { name = "Pergamentna delavnica", cost = { gold = 315, wood = 185, stone = 130, iron = 6 }, upkeep = 6, qualityBonus = 5 },
    parchmentrack_house = { name = "Pergamentna hiša", cost = { gold = 1165, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 24, qualityBonus = 18 },
    master_parchmentrack_atelier = { name = "Mojstrski pergamentni atelje", cost = { gold = 2935, wood = 430, stone = 510, silver = 34, gold = 7 }, upkeep = 69, qualityBonus = 30 },
    sovereign_parchmentrack_palace = { name = "Suverena pergamentna palača", cost = { gold = 12780, wood = 655, stone = 820, gold = 82, jewel = 19 }, upkeep = 251, qualityBonus = 55, prestigeBonus = 50 },
}
ParchmentRackMaker.ironStock = 12; ParchmentRackMaker.bronzeStock = 10; ParchmentRackMaker.woodStock = 18; ParchmentRackMaker.leatherStock = 10; ParchmentRackMaker.silverStock = 8; ParchmentRackMaker.goldStock = 6; ParchmentRackMaker.jewelStock = 4; ParchmentRackMaker.pearlStock = 4
ParchmentRackMaker.productStock = {}; ParchmentRackMaker.buildings = {}; ParchmentRackMaker.maker = nil; ParchmentRackMaker.activeMaking = {}; ParchmentRackMaker.totalProducts = 0; ParchmentRackMaker.dayTimer = 0
function ParchmentRackMaker.init() ParchmentRackMaker.ironStock=12; ParchmentRackMaker.bronzeStock=10; ParchmentRackMaker.woodStock=18; ParchmentRackMaker.leatherStock=10; ParchmentRackMaker.silverStock=8; ParchmentRackMaker.goldStock=6; ParchmentRackMaker.jewelStock=4; ParchmentRackMaker.pearlStock=4; ParchmentRackMaker.productStock={}; ParchmentRackMaker.buildings={}; ParchmentRackMaker.maker=nil; ParchmentRackMaker.activeMaking={}; ParchmentRackMaker.totalProducts=0; ParchmentRackMaker.dayTimer=0; print("[ParchmentRackMaker] Royal Parchment Rack Maker System initialized (6 products, 4 buildings)") end
function ParchmentRackMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ParchmentRackMaker.maker={name=n or ("Pergamentist "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pergamentist najet: %s (spretnost: %d)",ParchmentRackMaker.maker.name,s),"success") end; return true end
function ParchmentRackMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ParchmentRackMaker.build(id) local ok,e=ParchmentRackMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ParchmentRackMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ParchmentRackMaker.getQualityBonus() local b=0; for _,bd in ipairs(ParchmentRackMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ParchmentRackMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ParchmentRackMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and ParchmentRackMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ParchmentRackMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ParchmentRackMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ParchmentRackMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ParchmentRackMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ParchmentRackMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ParchmentRackMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ParchmentRackMaker.buildings==0 then return false,"Potrebna pergamentna delavnica" end; if not ParchmentRackMaker.maker then return false,"Potreben pergamentist" end; return true end
function ParchmentRackMaker.make(pt,qty) qty=qty or 1; local ok,e=ParchmentRackMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ParchmentRackMaker.ironStock=ParchmentRackMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ParchmentRackMaker.bronzeStock=ParchmentRackMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ParchmentRackMaker.woodStock=ParchmentRackMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ParchmentRackMaker.leatherStock=ParchmentRackMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ParchmentRackMaker.silverStock=ParchmentRackMaker.silverStock-d.silverCost*qty end; if d.goldCost then ParchmentRackMaker.goldStock=ParchmentRackMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ParchmentRackMaker.jewelStock=ParchmentRackMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ParchmentRackMaker.pearlStock=ParchmentRackMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ParchmentRackMaker.maker then t=math.max(1,t-math.floor(ParchmentRackMaker.maker.skill/13)) end; table.insert(ParchmentRackMaker.activeMaking,{id="parchmentrack_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ParchmentRackMaker.completeMaking(m) local q=1.0+(ParchmentRackMaker.getQualityBonus()/100); if ParchmentRackMaker.maker then q=q+(ParchmentRackMaker.maker.skill/140) end; q=math.min(2.5,q); ParchmentRackMaker.productStock[m.productType]=(ParchmentRackMaker.productStock[m.productType] or 0)+m.quantity; ParchmentRackMaker.totalProducts=ParchmentRackMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ParchmentRackMaker.maker then ParchmentRackMaker.maker.itemsMade=ParchmentRackMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ParchmentRackMaker.maker.skill=math.min(100,ParchmentRackMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stojalo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"parchmentrack.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ParchmentRackMaker.update(dt) if not _G.state then return end; ParchmentRackMaker.dayTimer=ParchmentRackMaker.dayTimer+dt; if ParchmentRackMaker.dayTimer>=30 then ParchmentRackMaker.dayTimer=0; for i=#ParchmentRackMaker.activeMaking,1,-1 do local m=ParchmentRackMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ParchmentRackMaker.completeMaking(m); table.remove(ParchmentRackMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ParchmentRackMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ParchmentRackMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ParchmentRackMaker.getStats() return {ironStock=ParchmentRackMaker.ironStock,bronzeStock=ParchmentRackMaker.bronzeStock,woodStock=ParchmentRackMaker.woodStock,leatherStock=ParchmentRackMaker.leatherStock,silverStock=ParchmentRackMaker.silverStock,goldStock=ParchmentRackMaker.goldStock,jewelStock=ParchmentRackMaker.jewelStock,pearlStock=ParchmentRackMaker.pearlStock,productStock=ParchmentRackMaker.productStock,numBuildings=#ParchmentRackMaker.buildings,hasMaker=ParchmentRackMaker.maker~=nil,makerName=ParchmentRackMaker.maker and ParchmentRackMaker.maker.name or "—",makerSkill=ParchmentRackMaker.maker and ParchmentRackMaker.maker.skill or 0,activeMaking=#ParchmentRackMaker.activeMaking,totalProducts=ParchmentRackMaker.totalProducts} end
return ParchmentRackMaker
