local MillHopperVibratorMaker = {}
local PRODUCTS = {
    iron_millhoppervibrator = { name = "Železni vibrator za lijak mlina", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni vibrator za lijak mlina za mlinarje." },
    bronze_millhoppervibrator = { name = "Bronast vibrator za lijak mlina", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast vibrator za lijak mlina za mlinarje." },
    silver_millhoppervibrator = { name = "Srebrn vibrator za lijak mlina", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn vibrator za lijak mlina za mlinarje." },
    gilded_millhoppervibrator = { name = "Pozlačen vibrator za lijak mlina", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen vibrator za lijak mlina za mlinarje." },
    jewel_set_millhoppervibrator = { name = "Draguljast vibrator za lijak mlina", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast vibrator za lijak mlina za mlinarje." },
    royal_sovereign_millhoppervibrator = { name = "Kraljevski suveren vibrator za lijak mlina", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren vibrator za lijak mlina z biseri za krono." },
}
local BUILDINGS = {
    millhoppervibrator_workshop = { name = "Millhoppervibrator delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    millhoppervibrator_house = { name = "Millhoppervibrator hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_millhoppervibrator_atelier = { name = "Mojstrski millhoppervibrator atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_millhoppervibrator_palace = { name = "Suverena millhoppervibrator palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MillHopperVibratorMaker.ironStock=16; MillHopperVibratorMaker.bronzeStock=12; MillHopperVibratorMaker.woodStock=12; MillHopperVibratorMaker.leatherStock=8; MillHopperVibratorMaker.silverStock=8; MillHopperVibratorMaker.goldStock=6; MillHopperVibratorMaker.jewelStock=4; MillHopperVibratorMaker.pearlStock=4
MillHopperVibratorMaker.productStock = {}; MillHopperVibratorMaker.buildings = {}; MillHopperVibratorMaker.maker = nil; MillHopperVibratorMaker.activeMaking = {}; MillHopperVibratorMaker.totalProducts = 0; MillHopperVibratorMaker.dayTimer = 0
function MillHopperVibratorMaker.init() MillHopperVibratorMaker.ironStock=16; MillHopperVibratorMaker.bronzeStock=12; MillHopperVibratorMaker.woodStock=12; MillHopperVibratorMaker.leatherStock=8; MillHopperVibratorMaker.silverStock=8; MillHopperVibratorMaker.goldStock=6; MillHopperVibratorMaker.jewelStock=4; MillHopperVibratorMaker.pearlStock=4; MillHopperVibratorMaker.productStock={}; MillHopperVibratorMaker.buildings={}; MillHopperVibratorMaker.maker=nil; MillHopperVibratorMaker.activeMaking={}; MillHopperVibratorMaker.totalProducts=0; MillHopperVibratorMaker.dayTimer=0; print("[MillHopperVibratorMaker] Royal Mill Hopper Vibrator Maker System initialized (6 products, 4 buildings)") end
function MillHopperVibratorMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillHopperVibratorMaker.maker={name=n or ("Treskar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Treskar najet: %s (spretnost: %d)",MillHopperVibratorMaker.maker.name,s),"success") end; return true end
function MillHopperVibratorMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillHopperVibratorMaker.build(id) local ok,e=MillHopperVibratorMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillHopperVibratorMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillHopperVibratorMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillHopperVibratorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillHopperVibratorMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillHopperVibratorMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillHopperVibratorMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillHopperVibratorMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillHopperVibratorMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillHopperVibratorMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillHopperVibratorMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillHopperVibratorMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillHopperVibratorMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillHopperVibratorMaker.buildings==0 then return false,"Potrebna treskalna delavnica" end; if not MillHopperVibratorMaker.maker then return false,"Potreben treskar" end; return true end
function MillHopperVibratorMaker.make(pt,qty) qty=qty or 1; local ok,e=MillHopperVibratorMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillHopperVibratorMaker.ironStock=MillHopperVibratorMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillHopperVibratorMaker.bronzeStock=MillHopperVibratorMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillHopperVibratorMaker.woodStock=MillHopperVibratorMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillHopperVibratorMaker.leatherStock=MillHopperVibratorMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillHopperVibratorMaker.silverStock=MillHopperVibratorMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillHopperVibratorMaker.goldStock=MillHopperVibratorMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillHopperVibratorMaker.jewelStock=MillHopperVibratorMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillHopperVibratorMaker.pearlStock=MillHopperVibratorMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillHopperVibratorMaker.maker then t=math.max(1,t-math.floor(MillHopperVibratorMaker.maker.skill/13)) end; table.insert(MillHopperVibratorMaker.activeMaking,{id="millhoppervibrator_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillHopperVibratorMaker.completeMaking(m) local q=1.0+(MillHopperVibratorMaker.getQualityBonus()/100); if MillHopperVibratorMaker.maker then q=q+(MillHopperVibratorMaker.maker.skill/140) end; q=math.min(2.5,q); MillHopperVibratorMaker.productStock[m.productType]=(MillHopperVibratorMaker.productStock[m.productType] or 0)+m.quantity; MillHopperVibratorMaker.totalProducts=MillHopperVibratorMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillHopperVibratorMaker.maker then MillHopperVibratorMaker.maker.itemsMade=MillHopperVibratorMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillHopperVibratorMaker.maker.skill=math.min(100,MillHopperVibratorMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vibrator izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millhoppervibrator.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MillHopperVibratorMaker.update(dt) if not _G.state then return end; MillHopperVibratorMaker.dayTimer=MillHopperVibratorMaker.dayTimer+dt; if MillHopperVibratorMaker.dayTimer>=30 then MillHopperVibratorMaker.dayTimer=0; for i=#MillHopperVibratorMaker.activeMaking,1,-1 do local m=MillHopperVibratorMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillHopperVibratorMaker.completeMaking(m); table.remove(MillHopperVibratorMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillHopperVibratorMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillHopperVibratorMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillHopperVibratorMaker.getStats() return {ironStock=MillHopperVibratorMaker.ironStock,bronzeStock=MillHopperVibratorMaker.bronzeStock,woodStock=MillHopperVibratorMaker.woodStock,leatherStock=MillHopperVibratorMaker.leatherStock,silverStock=MillHopperVibratorMaker.silverStock,goldStock=MillHopperVibratorMaker.goldStock,jewelStock=MillHopperVibratorMaker.jewelStock,pearlStock=MillHopperVibratorMaker.pearlStock,productStock=MillHopperVibratorMaker.productStock,numBuildings=#MillHopperVibratorMaker.buildings,hasMaker=MillHopperVibratorMaker.maker~=nil,makerName=MillHopperVibratorMaker.maker and MillHopperVibratorMaker.maker.name or "—",makerSkill=MillHopperVibratorMaker.maker and MillHopperVibratorMaker.maker.skill or 0,activeMaking=#MillHopperVibratorMaker.activeMaking,totalProducts=MillHopperVibratorMaker.totalProducts} end
return MillHopperVibratorMaker
