local CutlerySmith = {}
local PRODUCTS = {
    simple_iron_fork = { name = "Preprosta železna vilice", ironCost = 1, time = 2, cost = 25, culinary = 15, happiness = 1, description = "Preprosta železna vilice za jedilnico." },
    bronze_spoon_set = { name = "Bronasta žličkasta garnitura", bronzeCost = 2, ironCost = 1, time = 4, cost = 90, culinary = 28, happiness = 1, prestige = 2, description = "Bronasta žličkasta garnitura za trgovce." },
    silver_dinner_set = { name = "Srebrna večerja garnitura", silverCost = 2, bronzeCost = 1, ironCost = 1, time = 8, cost = 240, culinary = 42, happiness = 2, prestige = 6, description = "Srebrna večerja garnitura za plemiče." },
    gold_trimmed_cutlery = { name = "Zlatookrasni jedilni pribor", goldCost = 1, silverCost = 2, bronzeCost = 1, ironCost = 1, time = 12, cost = 580, culinary = 58, happiness = 3, prestige = 14, description = "Zlatookrasni jedilni pribor za visoke plemiče." },
    jewel_handled_cutlery = { name = "Draguljnorokavni jedilni pribor", goldCost = 2, silverCost = 1, bronzeCost = 1, ironCost = 1, jewelCost = 1, time = 16, cost = 1300, culinary = 75, happiness = 5, prestige = 26, description = "Jedilni pribor z draguljnimi ročaji za visoko plemstvo." },
    royal_grand_cutlery_set = { name = "Kraljevski veliki jedilni pribor", goldCost = 3, silverCost = 2, bronzeCost = 1, ironCost = 1, jewelCost = 2, pearlCost = 2, time = 23, cost = 3000, culinary = 92, happiness = 12, prestige = 56, description = "Veliki kraljevski jedilni pribor z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    cutlery_workshop = { name = "Priborna delavnica", cost = { gold = 220, wood = 100, stone = 100, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    flatware_loft = { name = "Priborno podstrešje", cost = { gold = 800, wood = 240, stone = 220, bronze = 6, silver = 6 }, upkeep = 18, qualityBonus = 18 },
    master_silversmith_atelier = { name = "Mojstrski srebrarsski atelje", cost = { gold = 2300, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 52, qualityBonus = 30 },
    royal_flatware_palace = { name = "Kraljevska priborna palača", cost = { gold = 9500, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 50 },
}
CutlerySmith.ironStock = 14; CutlerySmith.bronzeStock = 12; CutlerySmith.silverStock = 8; CutlerySmith.goldStock = 6; CutlerySmith.jewelStock = 4; CutlerySmith.pearlStock = 4
CutlerySmith.productStock = {}; CutlerySmith.buildings = {}; CutlerySmith.maker = nil; CutlerySmith.activeMaking = {}; CutlerySmith.totalProducts = 0; CutlerySmith.dayTimer = 0
function CutlerySmith.init() CutlerySmith.ironStock=14; CutlerySmith.bronzeStock=12; CutlerySmith.silverStock=8; CutlerySmith.goldStock=6; CutlerySmith.jewelStock=4; CutlerySmith.pearlStock=4; CutlerySmith.productStock={}; CutlerySmith.buildings={}; CutlerySmith.maker=nil; CutlerySmith.activeMaking={}; CutlerySmith.totalProducts=0; CutlerySmith.dayTimer=0; print("[CutlerySmith] Royal Cutlery Smith System initialized (6 products, 4 buildings)") end
function CutlerySmith.hireMaker(n,s) s=s or math.random(55,90); local c=460+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CutlerySmith.maker={name=n or ("Priborar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Priborar najet: %s (spretnost: %d)",CutlerySmith.maker.name,s),"success") end; return true end
function CutlerySmith.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CutlerySmith.build(id) local ok,e=CutlerySmith.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CutlerySmith.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CutlerySmith.getQualityBonus() local b=0; for _,bd in ipairs(CutlerySmith.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CutlerySmith.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CutlerySmith.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CutlerySmith.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.silverCost and CutlerySmith.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CutlerySmith.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CutlerySmith.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CutlerySmith.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CutlerySmith.buildings==0 then return false,"Potrebna priborna delavnica" end; if not CutlerySmith.maker then return false,"Potreben priborar" end; return true end
function CutlerySmith.make(pt,qty) qty=qty or 1; local ok,e=CutlerySmith.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CutlerySmith.ironStock=CutlerySmith.ironStock-d.ironCost*qty end; if d.bronzeCost then CutlerySmith.bronzeStock=CutlerySmith.bronzeStock-d.bronzeCost*qty end; if d.silverCost then CutlerySmith.silverStock=CutlerySmith.silverStock-d.silverCost*qty end; if d.goldCost then CutlerySmith.goldStock=CutlerySmith.goldStock-d.goldCost*qty end; if d.jewelCost then CutlerySmith.jewelStock=CutlerySmith.jewelStock-d.jewelCost*qty end; if d.pearlCost then CutlerySmith.pearlStock=CutlerySmith.pearlStock-d.pearlCost*qty end; local t=d.time; if CutlerySmith.maker then t=math.max(1,t-math.floor(CutlerySmith.maker.skill/13)) end; table.insert(CutlerySmith.activeMaking,{id="cutlery_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,culinary=d.culinary or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CutlerySmith.completeMaking(m) local q=1.0+(CutlerySmith.getQualityBonus()/100); if CutlerySmith.maker then q=q+(CutlerySmith.maker.skill/150) end; q=math.min(2.4,q); CutlerySmith.productStock[m.productType]=(CutlerySmith.productStock[m.productType] or 0)+m.quantity; CutlerySmith.totalProducts=CutlerySmith.totalProducts+m.quantity; if m.culinary>0 and _G.state then _G.state.culinary=(_G.state.culinary or 0)+m.culinary end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CutlerySmith.maker then CutlerySmith.maker.itemsMade=CutlerySmith.maker.itemsMade+m.quantity; if math.random()<0.25 then CutlerySmith.maker.skill=math.min(100,CutlerySmith.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pribor izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"cutlery.completed",{productName=m.productName,culinary=m.culinary,prestige=m.prestige,happiness=m.happiness}) end end
function CutlerySmith.update(dt) if not _G.state then return end; CutlerySmith.dayTimer=CutlerySmith.dayTimer+dt; if CutlerySmith.dayTimer>=30 then CutlerySmith.dayTimer=0; for i=#CutlerySmith.activeMaking,1,-1 do local m=CutlerySmith.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CutlerySmith.completeMaking(m); table.remove(CutlerySmith.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CutlerySmith.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CutlerySmith.maker then tu=tu+12 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CutlerySmith.getStats() return {ironStock=CutlerySmith.ironStock,bronzeStock=CutlerySmith.bronzeStock,silverStock=CutlerySmith.silverStock,goldStock=CutlerySmith.goldStock,jewelStock=CutlerySmith.jewelStock,pearlStock=CutlerySmith.pearlStock,productStock=CutlerySmith.productStock,numBuildings=#CutlerySmith.buildings,hasMaker=CutlerySmith.maker~=nil,makerName=CutlerySmith.maker and CutlerySmith.maker.name or "—",makerSkill=CutlerySmith.maker and CutlerySmith.maker.skill or 0,activeMaking=#CutlerySmith.activeMaking,totalProducts=CutlerySmith.totalProducts} end
return CutlerySmith
