local GardenTrowelSharpenerMaker = {}
local PRODUCTS = {
    iron_gardentrowelsharpener = { name = "Železni brusilec lopatk", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni brusilec lopatk za vrtnarje." },
    bronze_gardentrowelsharpener = { name = "Bronast brusilec lopatk", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast brusilec lopatk za vrtnarje." },
    silver_gardentrowelsharpener = { name = "Srebrn brusilec lopatk", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn brusilec lopatk za vrtnarje." },
    gilded_gardentrowelsharpener = { name = "Pozlačen brusilec lopatk", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen brusilec lopatk za vrtnarje." },
    jewel_set_gardentrowelsharpener = { name = "Draguljast brusilec lopatk", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast brusilec lopatk za vrtnarje." },
    royal_sovereign_gardentrowelsharpener = { name = "Kraljevski suveren brusilec lopatk", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren brusilec lopatk z biseri za krono." },
}
local BUILDINGS = {
    gardentrowelsharpener_workshop = { name = "Gardentrowelsharpener delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardentrowelsharpener_house = { name = "Gardentrowelsharpener hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardentrowelsharpener_atelier = { name = "Mojstrski gardentrowelsharpener atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardentrowelsharpener_palace = { name = "Suverena gardentrowelsharpener palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenTrowelSharpenerMaker.ironStock=16; GardenTrowelSharpenerMaker.bronzeStock=12; GardenTrowelSharpenerMaker.woodStock=14; GardenTrowelSharpenerMaker.leatherStock=8; GardenTrowelSharpenerMaker.silverStock=8; GardenTrowelSharpenerMaker.goldStock=6; GardenTrowelSharpenerMaker.jewelStock=4; GardenTrowelSharpenerMaker.pearlStock=4
GardenTrowelSharpenerMaker.productStock = {}; GardenTrowelSharpenerMaker.buildings = {}; GardenTrowelSharpenerMaker.maker = nil; GardenTrowelSharpenerMaker.activeMaking = {}; GardenTrowelSharpenerMaker.totalProducts = 0; GardenTrowelSharpenerMaker.dayTimer = 0
function GardenTrowelSharpenerMaker.init() GardenTrowelSharpenerMaker.ironStock=16; GardenTrowelSharpenerMaker.bronzeStock=12; GardenTrowelSharpenerMaker.woodStock=14; GardenTrowelSharpenerMaker.leatherStock=8; GardenTrowelSharpenerMaker.silverStock=8; GardenTrowelSharpenerMaker.goldStock=6; GardenTrowelSharpenerMaker.jewelStock=4; GardenTrowelSharpenerMaker.pearlStock=4; GardenTrowelSharpenerMaker.productStock={}; GardenTrowelSharpenerMaker.buildings={}; GardenTrowelSharpenerMaker.maker=nil; GardenTrowelSharpenerMaker.activeMaking={}; GardenTrowelSharpenerMaker.totalProducts=0; GardenTrowelSharpenerMaker.dayTimer=0; print("[GardenTrowelSharpenerMaker] Royal Garden Trowel Sharpener Maker System initialized (6 products, 4 buildings)") end
function GardenTrowelSharpenerMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenTrowelSharpenerMaker.maker={name=n or ("Brusilnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Brusilnik najet: %s (spretnost: %d)",GardenTrowelSharpenerMaker.maker.name,s),"success") end; return true end
function GardenTrowelSharpenerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenTrowelSharpenerMaker.build(id) local ok,e=GardenTrowelSharpenerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenTrowelSharpenerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenTrowelSharpenerMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenTrowelSharpenerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenTrowelSharpenerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenTrowelSharpenerMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenTrowelSharpenerMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenTrowelSharpenerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenTrowelSharpenerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenTrowelSharpenerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenTrowelSharpenerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenTrowelSharpenerMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenTrowelSharpenerMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenTrowelSharpenerMaker.buildings==0 then return false,"Potrebna brusilna delavnica" end; if not GardenTrowelSharpenerMaker.maker then return false,"Potreben brusilnik" end; return true end
function GardenTrowelSharpenerMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenTrowelSharpenerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenTrowelSharpenerMaker.ironStock=GardenTrowelSharpenerMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenTrowelSharpenerMaker.bronzeStock=GardenTrowelSharpenerMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenTrowelSharpenerMaker.woodStock=GardenTrowelSharpenerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenTrowelSharpenerMaker.leatherStock=GardenTrowelSharpenerMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenTrowelSharpenerMaker.silverStock=GardenTrowelSharpenerMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenTrowelSharpenerMaker.goldStock=GardenTrowelSharpenerMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenTrowelSharpenerMaker.jewelStock=GardenTrowelSharpenerMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenTrowelSharpenerMaker.pearlStock=GardenTrowelSharpenerMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenTrowelSharpenerMaker.maker then t=math.max(1,t-math.floor(GardenTrowelSharpenerMaker.maker.skill/13)) end; table.insert(GardenTrowelSharpenerMaker.activeMaking,{id="gardentrowelsharpener_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenTrowelSharpenerMaker.completeMaking(m) local q=1.0+(GardenTrowelSharpenerMaker.getQualityBonus()/100); if GardenTrowelSharpenerMaker.maker then q=q+(GardenTrowelSharpenerMaker.maker.skill/140) end; q=math.min(2.5,q); GardenTrowelSharpenerMaker.productStock[m.productType]=(GardenTrowelSharpenerMaker.productStock[m.productType] or 0)+m.quantity; GardenTrowelSharpenerMaker.totalProducts=GardenTrowelSharpenerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenTrowelSharpenerMaker.maker then GardenTrowelSharpenerMaker.maker.itemsMade=GardenTrowelSharpenerMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenTrowelSharpenerMaker.maker.skill=math.min(100,GardenTrowelSharpenerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Brusilnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardentrowelsharpener.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenTrowelSharpenerMaker.update(dt) if not _G.state then return end; GardenTrowelSharpenerMaker.dayTimer=GardenTrowelSharpenerMaker.dayTimer+dt; if GardenTrowelSharpenerMaker.dayTimer>=30 then GardenTrowelSharpenerMaker.dayTimer=0; for i=#GardenTrowelSharpenerMaker.activeMaking,1,-1 do local m=GardenTrowelSharpenerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenTrowelSharpenerMaker.completeMaking(m); table.remove(GardenTrowelSharpenerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenTrowelSharpenerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenTrowelSharpenerMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenTrowelSharpenerMaker.getStats() return {ironStock=GardenTrowelSharpenerMaker.ironStock,bronzeStock=GardenTrowelSharpenerMaker.bronzeStock,woodStock=GardenTrowelSharpenerMaker.woodStock,leatherStock=GardenTrowelSharpenerMaker.leatherStock,silverStock=GardenTrowelSharpenerMaker.silverStock,goldStock=GardenTrowelSharpenerMaker.goldStock,jewelStock=GardenTrowelSharpenerMaker.jewelStock,pearlStock=GardenTrowelSharpenerMaker.pearlStock,productStock=GardenTrowelSharpenerMaker.productStock,numBuildings=#GardenTrowelSharpenerMaker.buildings,hasMaker=GardenTrowelSharpenerMaker.maker~=nil,makerName=GardenTrowelSharpenerMaker.maker and GardenTrowelSharpenerMaker.maker.name or "—",makerSkill=GardenTrowelSharpenerMaker.maker and GardenTrowelSharpenerMaker.maker.skill or 0,activeMaking=#GardenTrowelSharpenerMaker.activeMaking,totalProducts=GardenTrowelSharpenerMaker.totalProducts} end
return GardenTrowelSharpenerMaker
