local WellBuilder = {}
local PRODUCTS = {
    simple_stone_well = { name = "Preprost kamnit vodnjak", stoneCost = 4, woodCost = 2, ropeCost = 1, time = 6, cost = 200, waterSupply = 30, happiness = 2, description = "Preprost kamnit vodnjak za vodo." },
    brick_lined_well = { name = "Opečnoobložen vodnjak", brickCost = 3, stoneCost = 2, woodCost = 2, ropeCost = 1, time = 9, cost = 480, waterSupply = 50, happiness = 2, prestige = 2, description = "Opečnoobložen vodnjak za trgovce." },
    marble_curb_well = { name = "Marmornatorobni vodnjak", marbleCost = 2, brickCost = 2, stoneCost = 2, woodCost = 2, ropeCost = 1, time = 13, cost = 1100, waterSupply = 70, happiness = 3, prestige = 6, description = "Marmornatorobni vodnjak za plemiče." },
    silver_bucket_well = { name = "Srebrnovedrni vodnjak", marbleCost = 2, silverCost = 1, brickCost = 2, stoneCost = 2, woodCost = 2, ropeCost = 1, time = 17, cost = 2500, waterSupply = 90, happiness = 4, prestige = 14, description = "Srebrnovedrni vodnjak za visoke plemiče." },
    jewel_set_well = { name = "Draguljasta vodnjak", marbleCost = 2, goldCost = 1, silverCost = 1, brickCost = 2, stoneCost = 2, woodCost = 2, ropeCost = 1, jewelCost = 1, time = 21, cost = 5200, waterSupply = 110, happiness = 6, prestige = 27, description = "Vodnjak z draguljem za visoko plemstvo." },
    royal_grand_well = { name = "Kraljevski veliki vodnjak", marbleCost = 3, goldCost = 2, silverCost = 2, brickCost = 2, stoneCost = 2, woodCost = 2, ropeCost = 1, jewelCost = 2, pearlCost = 2, time = 28, cost = 11000, waterSupply = 150, happiness = 13, prestige = 58, description = "Veliki kraljevski vodnjak z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    well_workshop = { name = "Vodnjakarska delavnica", cost = { gold = 320, wood = 160, stone = 180, rope = 6 }, upkeep = 7, qualityBonus = 5 },
    waterworks_loft = { name = "Vodovodna podstrešje", cost = { gold = 1100, wood = 320, stone = 320, silver = 6, marble = 4 }, upkeep = 26, qualityBonus = 18 },
    master_well_atelier = { name = "Mojstrski vodnjakarski atelje", cost = { gold = 2900, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 68, qualityBonus = 30 },
    royal_waterworks_palace = { name = "Kraljevska vodovodna palača", cost = { gold = 12500, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 250, qualityBonus = 55, prestigeBonus = 50 },
}
WellBuilder.stoneStock = 20; WellBuilder.brickStock = 14; WellBuilder.marbleStock = 10; WellBuilder.woodStock = 14; WellBuilder.ropeStock = 8; WellBuilder.silverStock = 6; WellBuilder.goldStock = 6; WellBuilder.jewelStock = 4; WellBuilder.pearlStock = 4
WellBuilder.productStock = {}; WellBuilder.buildings = {}; WellBuilder.maker = nil; WellBuilder.activeMaking = {}; WellBuilder.totalProducts = 0; WellBuilder.dayTimer = 0
function WellBuilder.init() WellBuilder.stoneStock=20; WellBuilder.brickStock=14; WellBuilder.marbleStock=10; WellBuilder.woodStock=14; WellBuilder.ropeStock=8; WellBuilder.silverStock=6; WellBuilder.goldStock=6; WellBuilder.jewelStock=4; WellBuilder.pearlStock=4; WellBuilder.productStock={}; WellBuilder.buildings={}; WellBuilder.maker=nil; WellBuilder.activeMaking={}; WellBuilder.totalProducts=0; WellBuilder.dayTimer=0; print("[WellBuilder] Royal Well Builder System initialized (6 products, 4 buildings)") end
function WellBuilder.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; WellBuilder.maker={name=n or ("Vodnjakar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vodnjakar najet: %s (spretnost: %d)",WellBuilder.maker.name,s),"success") end; return true end
function WellBuilder.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function WellBuilder.build(id) local ok,e=WellBuilder.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(WellBuilder.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function WellBuilder.getQualityBonus() local b=0; for _,bd in ipairs(WellBuilder.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function WellBuilder.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.stoneCost and WellBuilder.stoneStock<(d.stoneCost or 0) then return false,"Premalo kamna" end; if d.brickCost and WellBuilder.brickStock<(d.brickCost or 0) then return false,"Premalo opek" end; if d.marbleCost and WellBuilder.marbleStock<(d.marbleCost or 0) then return false,"Premalo marmorja" end; if d.woodCost and WellBuilder.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ropeCost and WellBuilder.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.silverCost and WellBuilder.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and WellBuilder.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and WellBuilder.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and WellBuilder.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #WellBuilder.buildings==0 then return false,"Potrebna vodnjakarska delavnica" end; if not WellBuilder.maker then return false,"Potreben vodnjakar" end; return true end
function WellBuilder.make(pt,qty) qty=qty or 1; local ok,e=WellBuilder.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.stoneCost then WellBuilder.stoneStock=WellBuilder.stoneStock-d.stoneCost*qty end; if d.brickCost then WellBuilder.brickStock=WellBuilder.brickStock-d.brickCost*qty end; if d.marbleCost then WellBuilder.marbleStock=WellBuilder.marbleStock-d.marbleCost*qty end; if d.woodCost then WellBuilder.woodStock=WellBuilder.woodStock-d.woodCost*qty end; if d.ropeCost then WellBuilder.ropeStock=WellBuilder.ropeStock-d.ropeCost*qty end; if d.silverCost then WellBuilder.silverStock=WellBuilder.silverStock-d.silverCost*qty end; if d.goldCost then WellBuilder.goldStock=WellBuilder.goldStock-d.goldCost*qty end; if d.jewelCost then WellBuilder.jewelStock=WellBuilder.jewelStock-d.jewelCost*qty end; if d.pearlCost then WellBuilder.pearlStock=WellBuilder.pearlStock-d.pearlCost*qty end; local t=d.time; if WellBuilder.maker then t=math.max(1,t-math.floor(WellBuilder.maker.skill/12)) end; table.insert(WellBuilder.activeMaking,{id="well_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,waterSupply=d.waterSupply or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kopanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function WellBuilder.completeMaking(m) local q=1.0+(WellBuilder.getQualityBonus()/100); if WellBuilder.maker then q=q+(WellBuilder.maker.skill/140) end; q=math.min(2.5,q); WellBuilder.productStock[m.productType]=(WellBuilder.productStock[m.productType] or 0)+m.quantity; WellBuilder.totalProducts=WellBuilder.totalProducts+m.quantity; if m.waterSupply>0 and _G.state then _G.state.water=(_G.state.water or 0)+m.waterSupply end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if WellBuilder.maker then WellBuilder.maker.itemsMade=WellBuilder.maker.itemsMade+m.quantity; if math.random()<0.25 then WellBuilder.maker.skill=math.min(100,WellBuilder.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vodnjak izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"well.completed",{productName=m.productName,waterSupply=m.waterSupply,prestige=m.prestige,happiness=m.happiness}) end end
function WellBuilder.update(dt) if not _G.state then return end; WellBuilder.dayTimer=WellBuilder.dayTimer+dt; if WellBuilder.dayTimer>=30 then WellBuilder.dayTimer=0; for i=#WellBuilder.activeMaking,1,-1 do local m=WellBuilder.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then WellBuilder.completeMaking(m); table.remove(WellBuilder.activeMaking,i) end end; local tu=0; for _,bd in ipairs(WellBuilder.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if WellBuilder.maker then tu=tu+16 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function WellBuilder.getStats() return {stoneStock=WellBuilder.stoneStock,brickStock=WellBuilder.brickStock,marbleStock=WellBuilder.marbleStock,woodStock=WellBuilder.woodStock,ropeStock=WellBuilder.ropeStock,silverStock=WellBuilder.silverStock,goldStock=WellBuilder.goldStock,jewelStock=WellBuilder.jewelStock,pearlStock=WellBuilder.pearlStock,productStock=WellBuilder.productStock,numBuildings=#WellBuilder.buildings,hasMaker=WellBuilder.maker~=nil,makerName=WellBuilder.maker and WellBuilder.maker.name or "—",makerSkill=WellBuilder.maker and WellBuilder.maker.skill or 0,activeMaking=#WellBuilder.activeMaking,totalProducts=WellBuilder.totalProducts} end
return WellBuilder
