local CrucibleFurnaceMaker = {}
local PRODUCTS = {
    simple_clay_crucible_furnace = { name = "Preprosta glinena talilna peč", clayCost = 4, brickCost = 2, ironCost = 1, time = 6, cost = 240, science = 25, happiness = 1, description = "Preprosta glinena talilna peč za taljenje kovin." },
    iron_reinforced_crucible_furnace = { name = "Železnookrepljena talilna peč", clayCost = 3, ironCost = 2, brickCost = 2, time = 9, cost = 560, science = 38, happiness = 2, prestige = 2, description = "Železnookrepljena talilna peč za trgovce." },
    silver_banded_crucible_furnace = { name = "Srebrnopasna talilna peč", clayCost = 3, silverCost = 1, ironCost = 2, brickCost = 2, time = 13, cost = 1300, science = 52, happiness = 2, prestige = 6, description = "Srebrnopasna talilna peč za plemiče." },
    gold_trimmed_crucible_furnace = { name = "Zlatookrasna talilna peč", clayCost = 3, goldCost = 1, silverCost = 1, ironCost = 2, brickCost = 2, time = 17, cost = 2900, science = 68, happiness = 3, prestige = 14, description = "Zlatookrasna talilna peč za visoke plemiče." },
    jewel_set_crucible_furnace = { name = "Draguljasta talilna peč", clayCost = 3, goldCost = 1, silverCost = 1, ironCost = 2, brickCost = 2, jewelCost = 1, time = 21, cost = 6200, science = 82, happiness = 5, prestige = 27, description = "Talilna peč z draguljem za visoko plemstvo." },
    royal_grand_crucible_furnace = { name = "Kraljevski veliki talilna peč", clayCost = 4, goldCost = 2, silverCost = 2, ironCost = 2, brickCost = 2, jewelCost = 2, pearlCost = 2, time = 28, cost = 13000, science = 95, happiness = 12, prestige = 58, description = "Velika kraljevska talilna peč z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    crucible_furnace_workshop = { name = "Talilna pečna delavnica", cost = { gold = 320, wood = 140, stone = 180, clay = 8, brick = 6 }, upkeep = 7, qualityBonus = 5 },
    metallurgy_loft = { name = "Metalurška podstrešje", cost = { gold = 1100, wood = 320, stone = 320, silver = 6, iron = 8 }, upkeep = 26, qualityBonus = 18 },
    master_furnace_atelier = { name = "Mojstrski pečni atelje", cost = { gold = 2800, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_metallurgy_palace = { name = "Kraljevska metalurška palača", cost = { gold = 12000, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
CrucibleFurnaceMaker.clayStock = 16; CrucibleFurnaceMaker.brickStock = 14; CrucibleFurnaceMaker.ironStock = 12; CrucibleFurnaceMaker.silverStock = 6; CrucibleFurnaceMaker.goldStock = 6; CrucibleFurnaceMaker.jewelStock = 4; CrucibleFurnaceMaker.pearlStock = 4
CrucibleFurnaceMaker.productStock = {}; CrucibleFurnaceMaker.buildings = {}; CrucibleFurnaceMaker.maker = nil; CrucibleFurnaceMaker.activeMaking = {}; CrucibleFurnaceMaker.totalProducts = 0; CrucibleFurnaceMaker.dayTimer = 0
function CrucibleFurnaceMaker.init() CrucibleFurnaceMaker.clayStock=16; CrucibleFurnaceMaker.brickStock=14; CrucibleFurnaceMaker.ironStock=12; CrucibleFurnaceMaker.silverStock=6; CrucibleFurnaceMaker.goldStock=6; CrucibleFurnaceMaker.jewelStock=4; CrucibleFurnaceMaker.pearlStock=4; CrucibleFurnaceMaker.productStock={}; CrucibleFurnaceMaker.buildings={}; CrucibleFurnaceMaker.maker=nil; CrucibleFurnaceMaker.activeMaking={}; CrucibleFurnaceMaker.totalProducts=0; CrucibleFurnaceMaker.dayTimer=0; print("[CrucibleFurnaceMaker] Royal Crucible Furnace Maker System initialized (6 products, 4 buildings)") end
function CrucibleFurnaceMaker.hireMaker(n,s) s=s or math.random(55,90); local c=620+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CrucibleFurnaceMaker.maker={name=n or ("Talilni pečar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Talilni pečar najet: %s (spretnost: %d)",CrucibleFurnaceMaker.maker.name,s),"success") end; return true end
function CrucibleFurnaceMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CrucibleFurnaceMaker.build(id) local ok,e=CrucibleFurnaceMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CrucibleFurnaceMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CrucibleFurnaceMaker.getQualityBonus() local b=0; for _,bd in ipairs(CrucibleFurnaceMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CrucibleFurnaceMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.clayCost and CrucibleFurnaceMaker.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.brickCost and CrucibleFurnaceMaker.brickStock<(d.brickCost or 0) then return false,"Premalo opek" end; if d.ironCost and CrucibleFurnaceMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.silverCost and CrucibleFurnaceMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CrucibleFurnaceMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CrucibleFurnaceMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CrucibleFurnaceMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CrucibleFurnaceMaker.buildings==0 then return false,"Potrebna talilna pečna delavnica" end; if not CrucibleFurnaceMaker.maker then return false,"Potreben talilni pečar" end; return true end
function CrucibleFurnaceMaker.make(pt,qty) qty=qty or 1; local ok,e=CrucibleFurnaceMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.clayCost then CrucibleFurnaceMaker.clayStock=CrucibleFurnaceMaker.clayStock-d.clayCost*qty end; if d.brickCost then CrucibleFurnaceMaker.brickStock=CrucibleFurnaceMaker.brickStock-d.brickCost*qty end; if d.ironCost then CrucibleFurnaceMaker.ironStock=CrucibleFurnaceMaker.ironStock-d.ironCost*qty end; if d.silverCost then CrucibleFurnaceMaker.silverStock=CrucibleFurnaceMaker.silverStock-d.silverCost*qty end; if d.goldCost then CrucibleFurnaceMaker.goldStock=CrucibleFurnaceMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CrucibleFurnaceMaker.jewelStock=CrucibleFurnaceMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CrucibleFurnaceMaker.pearlStock=CrucibleFurnaceMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CrucibleFurnaceMaker.maker then t=math.max(1,t-math.floor(CrucibleFurnaceMaker.maker.skill/12)) end; table.insert(CrucibleFurnaceMaker.activeMaking,{id="cruciblefurnace_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gradnja: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CrucibleFurnaceMaker.completeMaking(m) local q=1.0+(CrucibleFurnaceMaker.getQualityBonus()/100); if CrucibleFurnaceMaker.maker then q=q+(CrucibleFurnaceMaker.maker.skill/140) end; q=math.min(2.5,q); CrucibleFurnaceMaker.productStock[m.productType]=(CrucibleFurnaceMaker.productStock[m.productType] or 0)+m.quantity; CrucibleFurnaceMaker.totalProducts=CrucibleFurnaceMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CrucibleFurnaceMaker.maker then CrucibleFurnaceMaker.maker.itemsMade=CrucibleFurnaceMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CrucibleFurnaceMaker.maker.skill=math.min(100,CrucibleFurnaceMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Talilna peč izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"cruciblefurnace.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function CrucibleFurnaceMaker.update(dt) if not _G.state then return end; CrucibleFurnaceMaker.dayTimer=CrucibleFurnaceMaker.dayTimer+dt; if CrucibleFurnaceMaker.dayTimer>=30 then CrucibleFurnaceMaker.dayTimer=0; for i=#CrucibleFurnaceMaker.activeMaking,1,-1 do local m=CrucibleFurnaceMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CrucibleFurnaceMaker.completeMaking(m); table.remove(CrucibleFurnaceMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CrucibleFurnaceMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CrucibleFurnaceMaker.maker then tu=tu+17 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CrucibleFurnaceMaker.getStats() return {clayStock=CrucibleFurnaceMaker.clayStock,brickStock=CrucibleFurnaceMaker.brickStock,ironStock=CrucibleFurnaceMaker.ironStock,silverStock=CrucibleFurnaceMaker.silverStock,goldStock=CrucibleFurnaceMaker.goldStock,jewelStock=CrucibleFurnaceMaker.jewelStock,pearlStock=CrucibleFurnaceMaker.pearlStock,productStock=CrucibleFurnaceMaker.productStock,numBuildings=#CrucibleFurnaceMaker.buildings,hasMaker=CrucibleFurnaceMaker.maker~=nil,makerName=CrucibleFurnaceMaker.maker and CrucibleFurnaceMaker.maker.name or "—",makerSkill=CrucibleFurnaceMaker.maker and CrucibleFurnaceMaker.maker.skill or 0,activeMaking=#CrucibleFurnaceMaker.activeMaking,totalProducts=CrucibleFurnaceMaker.totalProducts} end
return CrucibleFurnaceMaker
