local GardenPlantTieCutterMaker = {}
local PRODUCTS = {
    iron_gardenplanttiecutter = { name = "Železni škarje za veze rastlin", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni škarje za veze rastlin za vrtnarje." },
    bronze_gardenplanttiecutter = { name = "Bronast škarje za veze rastlin", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast škarje za veze rastlin za vrtnarje." },
    silver_gardenplanttiecutter = { name = "Srebrn škarje za veze rastlin", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn škarje za veze rastlin za vrtnarje." },
    gilded_gardenplanttiecutter = { name = "Pozlačen škarje za veze rastlin", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen škarje za veze rastlin za vrtnarje." },
    jewel_set_gardenplanttiecutter = { name = "Draguljast škarje za veze rastlin", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast škarje za veze rastlin za vrtnarje." },
    royal_sovereign_gardenplanttiecutter = { name = "Kraljevski suveren škarje za veze rastlin", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren škarje za veze rastlin z biseri za krono." },
}
local BUILDINGS = {
    gardenplanttiecutter_workshop = { name = "Gardenplanttiecutter delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardenplanttiecutter_house = { name = "Gardenplanttiecutter hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardenplanttiecutter_atelier = { name = "Mojstrski gardenplanttiecutter atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardenplanttiecutter_palace = { name = "Suverena gardenplanttiecutter palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenPlantTieCutterMaker.ironStock=18; GardenPlantTieCutterMaker.bronzeStock=14; GardenPlantTieCutterMaker.woodStock=10; GardenPlantTieCutterMaker.leatherStock=8; GardenPlantTieCutterMaker.silverStock=8; GardenPlantTieCutterMaker.goldStock=6; GardenPlantTieCutterMaker.jewelStock=4; GardenPlantTieCutterMaker.pearlStock=4
GardenPlantTieCutterMaker.productStock = {}; GardenPlantTieCutterMaker.buildings = {}; GardenPlantTieCutterMaker.maker = nil; GardenPlantTieCutterMaker.activeMaking = {}; GardenPlantTieCutterMaker.totalProducts = 0; GardenPlantTieCutterMaker.dayTimer = 0
function GardenPlantTieCutterMaker.init() GardenPlantTieCutterMaker.ironStock=18; GardenPlantTieCutterMaker.bronzeStock=14; GardenPlantTieCutterMaker.woodStock=10; GardenPlantTieCutterMaker.leatherStock=8; GardenPlantTieCutterMaker.silverStock=8; GardenPlantTieCutterMaker.goldStock=6; GardenPlantTieCutterMaker.jewelStock=4; GardenPlantTieCutterMaker.pearlStock=4; GardenPlantTieCutterMaker.productStock={}; GardenPlantTieCutterMaker.buildings={}; GardenPlantTieCutterMaker.maker=nil; GardenPlantTieCutterMaker.activeMaking={}; GardenPlantTieCutterMaker.totalProducts=0; GardenPlantTieCutterMaker.dayTimer=0; print("[GardenPlantTieCutterMaker] Royal Garden Plant Tie Cutter Maker System initialized (6 products, 4 buildings)") end
function GardenPlantTieCutterMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenPlantTieCutterMaker.maker={name=n or ("Reznik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Reznik najet: %s (spretnost: %d)",GardenPlantTieCutterMaker.maker.name,s),"success") end; return true end
function GardenPlantTieCutterMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenPlantTieCutterMaker.build(id) local ok,e=GardenPlantTieCutterMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenPlantTieCutterMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenPlantTieCutterMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenPlantTieCutterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenPlantTieCutterMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenPlantTieCutterMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenPlantTieCutterMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenPlantTieCutterMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenPlantTieCutterMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenPlantTieCutterMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenPlantTieCutterMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenPlantTieCutterMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenPlantTieCutterMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenPlantTieCutterMaker.buildings==0 then return false,"Potrebna rezna delavnica" end; if not GardenPlantTieCutterMaker.maker then return false,"Potreben reznik" end; return true end
function GardenPlantTieCutterMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenPlantTieCutterMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenPlantTieCutterMaker.ironStock=GardenPlantTieCutterMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenPlantTieCutterMaker.bronzeStock=GardenPlantTieCutterMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenPlantTieCutterMaker.woodStock=GardenPlantTieCutterMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenPlantTieCutterMaker.leatherStock=GardenPlantTieCutterMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenPlantTieCutterMaker.silverStock=GardenPlantTieCutterMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenPlantTieCutterMaker.goldStock=GardenPlantTieCutterMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenPlantTieCutterMaker.jewelStock=GardenPlantTieCutterMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenPlantTieCutterMaker.pearlStock=GardenPlantTieCutterMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenPlantTieCutterMaker.maker then t=math.max(1,t-math.floor(GardenPlantTieCutterMaker.maker.skill/13)) end; table.insert(GardenPlantTieCutterMaker.activeMaking,{id="gardenplanttiecutter_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenPlantTieCutterMaker.completeMaking(m) local q=1.0+(GardenPlantTieCutterMaker.getQualityBonus()/100); if GardenPlantTieCutterMaker.maker then q=q+(GardenPlantTieCutterMaker.maker.skill/140) end; q=math.min(2.5,q); GardenPlantTieCutterMaker.productStock[m.productType]=(GardenPlantTieCutterMaker.productStock[m.productType] or 0)+m.quantity; GardenPlantTieCutterMaker.totalProducts=GardenPlantTieCutterMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenPlantTieCutterMaker.maker then GardenPlantTieCutterMaker.maker.itemsMade=GardenPlantTieCutterMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenPlantTieCutterMaker.maker.skill=math.min(100,GardenPlantTieCutterMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Reznik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardenplanttiecutter.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenPlantTieCutterMaker.update(dt) if not _G.state then return end; GardenPlantTieCutterMaker.dayTimer=GardenPlantTieCutterMaker.dayTimer+dt; if GardenPlantTieCutterMaker.dayTimer>=30 then GardenPlantTieCutterMaker.dayTimer=0; for i=#GardenPlantTieCutterMaker.activeMaking,1,-1 do local m=GardenPlantTieCutterMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenPlantTieCutterMaker.completeMaking(m); table.remove(GardenPlantTieCutterMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenPlantTieCutterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenPlantTieCutterMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenPlantTieCutterMaker.getStats() return {ironStock=GardenPlantTieCutterMaker.ironStock,bronzeStock=GardenPlantTieCutterMaker.bronzeStock,woodStock=GardenPlantTieCutterMaker.woodStock,leatherStock=GardenPlantTieCutterMaker.leatherStock,silverStock=GardenPlantTieCutterMaker.silverStock,goldStock=GardenPlantTieCutterMaker.goldStock,jewelStock=GardenPlantTieCutterMaker.jewelStock,pearlStock=GardenPlantTieCutterMaker.pearlStock,productStock=GardenPlantTieCutterMaker.productStock,numBuildings=#GardenPlantTieCutterMaker.buildings,hasMaker=GardenPlantTieCutterMaker.maker~=nil,makerName=GardenPlantTieCutterMaker.maker and GardenPlantTieCutterMaker.maker.name or "—",makerSkill=GardenPlantTieCutterMaker.maker and GardenPlantTieCutterMaker.maker.skill or 0,activeMaking=#GardenPlantTieCutterMaker.activeMaking,totalProducts=GardenPlantTieCutterMaker.totalProducts} end
return GardenPlantTieCutterMaker
