local MoldClampMaker = {}
local PRODUCTS = {
    iron_moldclamp = { name = "Železni sponka za kalupe", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni sponka za kalupe za livarje." },
    bronze_moldclamp = { name = "Bronast sponka za kalupe", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast sponka za kalupe za livarje." },
    silver_moldclamp = { name = "Srebrn sponka za kalupe", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn sponka za kalupe za livarje." },
    gilded_moldclamp = { name = "Pozlačen sponka za kalupe", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen sponka za kalupe za livarje." },
    jewel_set_moldclamp = { name = "Draguljast sponka za kalupe", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast sponka za kalupe za livarje." },
    royal_sovereign_moldclamp = { name = "Kraljevski suveren sponka za kalupe", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren sponka za kalupe z biseri za krono." },
}
local BUILDINGS = {
    moldclamp_workshop = { name = "Moldclamp delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    moldclamp_house = { name = "Moldclamp hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_moldclamp_atelier = { name = "Mojstrski moldclamp atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_moldclamp_palace = { name = "Suverena moldclamp palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MoldClampMaker.ironStock=16; MoldClampMaker.bronzeStock=12; MoldClampMaker.woodStock=12; MoldClampMaker.leatherStock=8; MoldClampMaker.silverStock=8; MoldClampMaker.goldStock=6; MoldClampMaker.jewelStock=4; MoldClampMaker.pearlStock=4
MoldClampMaker.productStock = {}; MoldClampMaker.buildings = {}; MoldClampMaker.maker = nil; MoldClampMaker.activeMaking = {}; MoldClampMaker.totalProducts = 0; MoldClampMaker.dayTimer = 0
function MoldClampMaker.init() MoldClampMaker.ironStock=16; MoldClampMaker.bronzeStock=12; MoldClampMaker.woodStock=12; MoldClampMaker.leatherStock=8; MoldClampMaker.silverStock=8; MoldClampMaker.goldStock=6; MoldClampMaker.jewelStock=4; MoldClampMaker.pearlStock=4; MoldClampMaker.productStock={}; MoldClampMaker.buildings={}; MoldClampMaker.maker=nil; MoldClampMaker.activeMaking={}; MoldClampMaker.totalProducts=0; MoldClampMaker.dayTimer=0; print("[MoldClampMaker] Royal Mold Clamp Maker System initialized (6 products, 4 buildings)") end
function MoldClampMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MoldClampMaker.maker={name=n or ("Sponkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sponkar najet: %s (spretnost: %d)",MoldClampMaker.maker.name,s),"success") end; return true end
function MoldClampMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MoldClampMaker.build(id) local ok,e=MoldClampMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MoldClampMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MoldClampMaker.getQualityBonus() local b=0; for _,bd in ipairs(MoldClampMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MoldClampMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MoldClampMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MoldClampMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MoldClampMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MoldClampMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MoldClampMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MoldClampMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MoldClampMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MoldClampMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MoldClampMaker.buildings==0 then return false,"Potrebna sponkaška delavnica" end; if not MoldClampMaker.maker then return false,"Potreben sponkar" end; return true end
function MoldClampMaker.make(pt,qty) qty=qty or 1; local ok,e=MoldClampMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MoldClampMaker.ironStock=MoldClampMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MoldClampMaker.bronzeStock=MoldClampMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MoldClampMaker.woodStock=MoldClampMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MoldClampMaker.leatherStock=MoldClampMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MoldClampMaker.silverStock=MoldClampMaker.silverStock-d.silverCost*qty end; if d.goldCost then MoldClampMaker.goldStock=MoldClampMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MoldClampMaker.jewelStock=MoldClampMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MoldClampMaker.pearlStock=MoldClampMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MoldClampMaker.maker then t=math.max(1,t-math.floor(MoldClampMaker.maker.skill/13)) end; table.insert(MoldClampMaker.activeMaking,{id="moldclamp_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MoldClampMaker.completeMaking(m) local q=1.0+(MoldClampMaker.getQualityBonus()/100); if MoldClampMaker.maker then q=q+(MoldClampMaker.maker.skill/140) end; q=math.min(2.5,q); MoldClampMaker.productStock[m.productType]=(MoldClampMaker.productStock[m.productType] or 0)+m.quantity; MoldClampMaker.totalProducts=MoldClampMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MoldClampMaker.maker then MoldClampMaker.maker.itemsMade=MoldClampMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MoldClampMaker.maker.skill=math.min(100,MoldClampMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sponka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"moldclamp.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MoldClampMaker.update(dt) if not _G.state then return end; MoldClampMaker.dayTimer=MoldClampMaker.dayTimer+dt; if MoldClampMaker.dayTimer>=30 then MoldClampMaker.dayTimer=0; for i=#MoldClampMaker.activeMaking,1,-1 do local m=MoldClampMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MoldClampMaker.completeMaking(m); table.remove(MoldClampMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MoldClampMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MoldClampMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MoldClampMaker.getStats() return {ironStock=MoldClampMaker.ironStock,bronzeStock=MoldClampMaker.bronzeStock,woodStock=MoldClampMaker.woodStock,leatherStock=MoldClampMaker.leatherStock,silverStock=MoldClampMaker.silverStock,goldStock=MoldClampMaker.goldStock,jewelStock=MoldClampMaker.jewelStock,pearlStock=MoldClampMaker.pearlStock,productStock=MoldClampMaker.productStock,numBuildings=#MoldClampMaker.buildings,hasMaker=MoldClampMaker.maker~=nil,makerName=MoldClampMaker.maker and MoldClampMaker.maker.name or "—",makerSkill=MoldClampMaker.maker and MoldClampMaker.maker.skill or 0,activeMaking=#MoldClampMaker.activeMaking,totalProducts=MoldClampMaker.totalProducts} end
return MoldClampMaker
