local IronForgeToolMaker = {}
local PRODUCTS = {
    simple_iron_tongs = { name = "Preproste železne klešče", ironCost = 2, woodCost = 1, time = 3, cost = 60, science = 15, happiness = 1, description = "Preproste železne klešče za kovače." },
    steel_hammer = { name = "Jekleno kladivo", ironCost = 2, steelCost = 1, woodCost = 1, time = 5, cost = 160, science = 28, happiness = 1, prestige = 2, description = "Jekleno kladivo za trgovce." },
    silver_anvil = { name = "Srebrnonakovalo", ironCost = 2, silverCost = 1, steelCost = 1, woodCost = 1, time = 8, cost = 400, science = 42, happiness = 2, prestige = 6, description = "Srebrnonakovalo za plemiče." },
    gold_trimmed_tongs = { name = "Zlatookrasne klešče", ironCost = 2, goldCost = 1, silverCost = 1, steelCost = 1, woodCost = 1, time = 12, cost = 950, science = 56, happiness = 3, prestige = 14, description = "Zlatookrasne klešče za visoke plemiče." },
    jewel_set_anvil = { name = "Draguljasta nakovalo", ironCost = 2, goldCost = 1, silverCost = 1, steelCost = 1, woodCost = 1, jewelCost = 1, time = 16, cost = 2100, science = 72, happiness = 5, prestige = 27, description = "Nakovalo z draguljem za visoko plemstvo." },
    royal_grand_forge_set = { name = "Kraljevski veliki kovaški set", ironCost = 3, goldCost = 2, silverCost = 2, steelCost = 1, woodCost = 1, jewelCost = 2, pearlCost = 2, time = 23, cost = 4800, science = 90, happiness = 12, prestige = 58, description = "Veliki kraljevski kovaški set z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    forge_tool_workshop = { name = "Kovaška orodna delavnica", cost = { gold = 280, wood = 120, stone = 140, iron = 6, steel = 4 }, upkeep = 6, qualityBonus = 5 },
    forge_loft = { name = "Kovaška podstrešje", cost = { gold = 1000, wood = 280, stone = 280, silver = 6, steel = 6 }, upkeep = 23, qualityBonus = 18 },
    master_forge_atelier = { name = "Mojstrski kovaški atelje", cost = { gold = 2800, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_forge_palace = { name = "Kraljevska kovaška palača", cost = { gold = 12000, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 240, qualityBonus = 55, prestigeBonus = 50 },
}
IronForgeToolMaker.ironStock = 14; IronForgeToolMaker.steelStock = 10; IronForgeToolMaker.woodStock = 10; IronForgeToolMaker.silverStock = 6; IronForgeToolMaker.goldStock = 6; IronForgeToolMaker.jewelStock = 4; IronForgeToolMaker.pearlStock = 4
IronForgeToolMaker.productStock = {}; IronForgeToolMaker.buildings = {}; IronForgeToolMaker.maker = nil; IronForgeToolMaker.activeMaking = {}; IronForgeToolMaker.totalProducts = 0; IronForgeToolMaker.dayTimer = 0
function IronForgeToolMaker.init() IronForgeToolMaker.ironStock=14; IronForgeToolMaker.steelStock=10; IronForgeToolMaker.woodStock=10; IronForgeToolMaker.silverStock=6; IronForgeToolMaker.goldStock=6; IronForgeToolMaker.jewelStock=4; IronForgeToolMaker.pearlStock=4; IronForgeToolMaker.productStock={}; IronForgeToolMaker.buildings={}; IronForgeToolMaker.maker=nil; IronForgeToolMaker.activeMaking={}; IronForgeToolMaker.totalProducts=0; IronForgeToolMaker.dayTimer=0; print("[IronForgeToolMaker] Royal Iron Forge Tool Maker System initialized (6 products, 4 buildings)") end
function IronForgeToolMaker.hireMaker(n,s) s=s or math.random(55,90); local c=560+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; IronForgeToolMaker.maker={name=n or ("Kovaški orodjar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovaški orodjar najet: %s (spretnost: %d)",IronForgeToolMaker.maker.name,s),"success") end; return true end
function IronForgeToolMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function IronForgeToolMaker.build(id) local ok,e=IronForgeToolMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(IronForgeToolMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function IronForgeToolMaker.getQualityBonus() local b=0; for _,bd in ipairs(IronForgeToolMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function IronForgeToolMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and IronForgeToolMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.steelCost and IronForgeToolMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.woodCost and IronForgeToolMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.silverCost and IronForgeToolMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and IronForgeToolMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and IronForgeToolMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and IronForgeToolMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #IronForgeToolMaker.buildings==0 then return false,"Potrebna kovaška orodna delavnica" end; if not IronForgeToolMaker.maker then return false,"Potreben kovaški orodjar" end; return true end
function IronForgeToolMaker.make(pt,qty) qty=qty or 1; local ok,e=IronForgeToolMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then IronForgeToolMaker.ironStock=IronForgeToolMaker.ironStock-d.ironCost*qty end; if d.steelCost then IronForgeToolMaker.steelStock=IronForgeToolMaker.steelStock-d.steelCost*qty end; if d.woodCost then IronForgeToolMaker.woodStock=IronForgeToolMaker.woodStock-d.woodCost*qty end; if d.silverCost then IronForgeToolMaker.silverStock=IronForgeToolMaker.silverStock-d.silverCost*qty end; if d.goldCost then IronForgeToolMaker.goldStock=IronForgeToolMaker.goldStock-d.goldCost*qty end; if d.jewelCost then IronForgeToolMaker.jewelStock=IronForgeToolMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then IronForgeToolMaker.pearlStock=IronForgeToolMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if IronForgeToolMaker.maker then t=math.max(1,t-math.floor(IronForgeToolMaker.maker.skill/13)) end; table.insert(IronForgeToolMaker.activeMaking,{id="ironforgetool_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function IronForgeToolMaker.completeMaking(m) local q=1.0+(IronForgeToolMaker.getQualityBonus()/100); if IronForgeToolMaker.maker then q=q+(IronForgeToolMaker.maker.skill/140) end; q=math.min(2.5,q); IronForgeToolMaker.productStock[m.productType]=(IronForgeToolMaker.productStock[m.productType] or 0)+m.quantity; IronForgeToolMaker.totalProducts=IronForgeToolMaker.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if IronForgeToolMaker.maker then IronForgeToolMaker.maker.itemsMade=IronForgeToolMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then IronForgeToolMaker.maker.skill=math.min(100,IronForgeToolMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kovaško orodje izdelano: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"ironforgetool.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function IronForgeToolMaker.update(dt) if not _G.state then return end; IronForgeToolMaker.dayTimer=IronForgeToolMaker.dayTimer+dt; if IronForgeToolMaker.dayTimer>=30 then IronForgeToolMaker.dayTimer=0; for i=#IronForgeToolMaker.activeMaking,1,-1 do local m=IronForgeToolMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then IronForgeToolMaker.completeMaking(m); table.remove(IronForgeToolMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(IronForgeToolMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if IronForgeToolMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function IronForgeToolMaker.getStats() return {ironStock=IronForgeToolMaker.ironStock,steelStock=IronForgeToolMaker.steelStock,woodStock=IronForgeToolMaker.woodStock,silverStock=IronForgeToolMaker.silverStock,goldStock=IronForgeToolMaker.goldStock,jewelStock=IronForgeToolMaker.jewelStock,pearlStock=IronForgeToolMaker.pearlStock,productStock=IronForgeToolMaker.productStock,numBuildings=#IronForgeToolMaker.buildings,hasMaker=IronForgeToolMaker.maker~=nil,makerName=IronForgeToolMaker.maker and IronForgeToolMaker.maker.name or "—",makerSkill=IronForgeToolMaker.maker and IronForgeToolMaker.maker.skill or 0,activeMaking=#IronForgeToolMaker.activeMaking,totalProducts=IronForgeToolMaker.totalProducts} end
return IronForgeToolMaker
