local GardenTwineDispenserMaker = {}
local PRODUCTS = {
    iron_gardentwinedispenser = { name = "Železni razdelilec vrvice", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni razdelilec vrvice za vrtnarje." },
    bronze_gardentwinedispenser = { name = "Bronast razdelilec vrvice", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast razdelilec vrvice za vrtnarje." },
    silver_gardentwinedispenser = { name = "Srebrn razdelilec vrvice", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn razdelilec vrvice za vrtnarje." },
    gilded_gardentwinedispenser = { name = "Pozlačen razdelilec vrvice", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen razdelilec vrvice za vrtnarje." },
    jewel_set_gardentwinedispenser = { name = "Draguljast razdelilec vrvice", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast razdelilec vrvice za vrtnarje." },
    royal_sovereign_gardentwinedispenser = { name = "Kraljevski suveren razdelilec vrvice", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren razdelilec vrvice z biseri za krono." },
}
local BUILDINGS = {
    gardentwinedispenser_workshop = { name = "Gardentwinedispenser delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardentwinedispenser_house = { name = "Gardentwinedispenser hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardentwinedispenser_atelier = { name = "Mojstrski gardentwinedispenser atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardentwinedispenser_palace = { name = "Suverena gardentwinedispenser palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenTwineDispenserMaker.ironStock=12; GardenTwineDispenserMaker.bronzeStock=10; GardenTwineDispenserMaker.woodStock=16; GardenTwineDispenserMaker.leatherStock=10; GardenTwineDispenserMaker.silverStock=8; GardenTwineDispenserMaker.goldStock=6; GardenTwineDispenserMaker.jewelStock=4; GardenTwineDispenserMaker.pearlStock=4
GardenTwineDispenserMaker.productStock = {}; GardenTwineDispenserMaker.buildings = {}; GardenTwineDispenserMaker.maker = nil; GardenTwineDispenserMaker.activeMaking = {}; GardenTwineDispenserMaker.totalProducts = 0; GardenTwineDispenserMaker.dayTimer = 0
function GardenTwineDispenserMaker.init() GardenTwineDispenserMaker.ironStock=12; GardenTwineDispenserMaker.bronzeStock=10; GardenTwineDispenserMaker.woodStock=16; GardenTwineDispenserMaker.leatherStock=10; GardenTwineDispenserMaker.silverStock=8; GardenTwineDispenserMaker.goldStock=6; GardenTwineDispenserMaker.jewelStock=4; GardenTwineDispenserMaker.pearlStock=4; GardenTwineDispenserMaker.productStock={}; GardenTwineDispenserMaker.buildings={}; GardenTwineDispenserMaker.maker=nil; GardenTwineDispenserMaker.activeMaking={}; GardenTwineDispenserMaker.totalProducts=0; GardenTwineDispenserMaker.dayTimer=0; print("[GardenTwineDispenserMaker] Royal Garden Twine Dispenser Maker System initialized (6 products, 4 buildings)") end
function GardenTwineDispenserMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenTwineDispenserMaker.maker={name=n or ("Razdelilnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Razdelilnik najet: %s (spretnost: %d)",GardenTwineDispenserMaker.maker.name,s),"success") end; return true end
function GardenTwineDispenserMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenTwineDispenserMaker.build(id) local ok,e=GardenTwineDispenserMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenTwineDispenserMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenTwineDispenserMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenTwineDispenserMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenTwineDispenserMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenTwineDispenserMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenTwineDispenserMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenTwineDispenserMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenTwineDispenserMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenTwineDispenserMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenTwineDispenserMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenTwineDispenserMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenTwineDispenserMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenTwineDispenserMaker.buildings==0 then return false,"Potrebna razdelilna delavnica" end; if not GardenTwineDispenserMaker.maker then return false,"Potreben razdelilnik" end; return true end
function GardenTwineDispenserMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenTwineDispenserMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenTwineDispenserMaker.ironStock=GardenTwineDispenserMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenTwineDispenserMaker.bronzeStock=GardenTwineDispenserMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenTwineDispenserMaker.woodStock=GardenTwineDispenserMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenTwineDispenserMaker.leatherStock=GardenTwineDispenserMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenTwineDispenserMaker.silverStock=GardenTwineDispenserMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenTwineDispenserMaker.goldStock=GardenTwineDispenserMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenTwineDispenserMaker.jewelStock=GardenTwineDispenserMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenTwineDispenserMaker.pearlStock=GardenTwineDispenserMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenTwineDispenserMaker.maker then t=math.max(1,t-math.floor(GardenTwineDispenserMaker.maker.skill/13)) end; table.insert(GardenTwineDispenserMaker.activeMaking,{id="gardentwinedispenser_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenTwineDispenserMaker.completeMaking(m) local q=1.0+(GardenTwineDispenserMaker.getQualityBonus()/100); if GardenTwineDispenserMaker.maker then q=q+(GardenTwineDispenserMaker.maker.skill/140) end; q=math.min(2.5,q); GardenTwineDispenserMaker.productStock[m.productType]=(GardenTwineDispenserMaker.productStock[m.productType] or 0)+m.quantity; GardenTwineDispenserMaker.totalProducts=GardenTwineDispenserMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenTwineDispenserMaker.maker then GardenTwineDispenserMaker.maker.itemsMade=GardenTwineDispenserMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenTwineDispenserMaker.maker.skill=math.min(100,GardenTwineDispenserMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Razdelilnik izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardentwinedispenser.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenTwineDispenserMaker.update(dt) if not _G.state then return end; GardenTwineDispenserMaker.dayTimer=GardenTwineDispenserMaker.dayTimer+dt; if GardenTwineDispenserMaker.dayTimer>=30 then GardenTwineDispenserMaker.dayTimer=0; for i=#GardenTwineDispenserMaker.activeMaking,1,-1 do local m=GardenTwineDispenserMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenTwineDispenserMaker.completeMaking(m); table.remove(GardenTwineDispenserMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenTwineDispenserMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenTwineDispenserMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenTwineDispenserMaker.getStats() return {ironStock=GardenTwineDispenserMaker.ironStock,bronzeStock=GardenTwineDispenserMaker.bronzeStock,woodStock=GardenTwineDispenserMaker.woodStock,leatherStock=GardenTwineDispenserMaker.leatherStock,silverStock=GardenTwineDispenserMaker.silverStock,goldStock=GardenTwineDispenserMaker.goldStock,jewelStock=GardenTwineDispenserMaker.jewelStock,pearlStock=GardenTwineDispenserMaker.pearlStock,productStock=GardenTwineDispenserMaker.productStock,numBuildings=#GardenTwineDispenserMaker.buildings,hasMaker=GardenTwineDispenserMaker.maker~=nil,makerName=GardenTwineDispenserMaker.maker and GardenTwineDispenserMaker.maker.name or "—",makerSkill=GardenTwineDispenserMaker.maker and GardenTwineDispenserMaker.maker.skill or 0,activeMaking=#GardenTwineDispenserMaker.activeMaking,totalProducts=GardenTwineDispenserMaker.totalProducts} end
return GardenTwineDispenserMaker
