local CompassMaker = {}
local PRODUCTS = {
    simple_iron_compass = { name = "Preprost železni kompas", woodCost = 1, ironCost = 2, glassCost = 1, time = 3, cost = 40, navigation = 18, happiness = 1, description = "Preprost železni kompas za mornarje." },
    brass_housed_compass = { name = "Medeninasti kompas", woodCost = 1, brassCost = 2, ironCost = 1, glassCost = 1, time = 6, cost = 130, navigation = 32, happiness = 1, prestige = 2, description = "Medeninasti kompas za trgovce." },
    silver_ring_compass = { name = "Srebrnoprstanski kompas", woodCost = 1, silverCost = 2, brassCost = 1, ironCost = 1, glassCost = 1, time = 9, cost = 320, navigation = 48, happiness = 2, prestige = 6, description = "Srebrnoprstanski kompas za plemiče." },
    gold_trimmed_compass = { name = "Zlatookrasni kompas", woodCost = 1, goldCost = 2, silverCost = 1, brassCost = 1, glassCost = 1, time = 13, cost = 760, navigation = 62, happiness = 3, prestige = 14, description = "Zlatookrasni kompas za visoke plemiče." },
    jewel_bearing_compass = { name = "Draguljnoležajni kompas", woodCost = 1, goldCost = 2, silverCost = 1, brassCost = 1, jewelCost = 1, glassCost = 1, time = 17, cost = 1700, navigation = 78, happiness = 5, prestige = 27, description = "Kompas z draguljnim ležajem za visoko plemstvo." },
    royal_grand_compass = { name = "Kraljevski veliki kompas", woodCost = 2, goldCost = 3, silverCost = 2, brassCost = 1, jewelCost = 2, pearlCost = 2, glassCost = 2, time = 24, cost = 3900, navigation = 92, happiness = 12, prestige = 58, description = "Veliki kraljevski kompas z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    compass_workshop = { name = "Kompasna delavnica", cost = { gold = 220, wood = 100, stone = 100, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    magnetic_loft = { name = "Magnetska podstrešje", cost = { gold = 820, wood = 240, stone = 220, brass = 6, silver = 6 }, upkeep = 19, qualityBonus = 18 },
    master_navigation_atelier = { name = "Mojstrski navigacijski atelje", cost = { gold = 2400, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 55, qualityBonus = 30 },
    royal_compass_palace = { name = "Kraljevska kompasna palača", cost = { gold = 9800, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 195, qualityBonus = 55, prestigeBonus = 50 },
}
CompassMaker.woodStock = 12; CompassMaker.ironStock = 14; CompassMaker.brassStock = 12; CompassMaker.glassStock = 12; CompassMaker.silverStock = 6; CompassMaker.goldStock = 6; CompassMaker.jewelStock = 4; CompassMaker.pearlStock = 4
CompassMaker.productStock = {}; CompassMaker.buildings = {}; CompassMaker.maker = nil; CompassMaker.activeMaking = {}; CompassMaker.totalProducts = 0; CompassMaker.dayTimer = 0
function CompassMaker.init() CompassMaker.woodStock=12; CompassMaker.ironStock=14; CompassMaker.brassStock=12; CompassMaker.glassStock=12; CompassMaker.silverStock=6; CompassMaker.goldStock=6; CompassMaker.jewelStock=4; CompassMaker.pearlStock=4; CompassMaker.productStock={}; CompassMaker.buildings={}; CompassMaker.maker=nil; CompassMaker.activeMaking={}; CompassMaker.totalProducts=0; CompassMaker.dayTimer=0; print("[CompassMaker] Royal Compass Maker System initialized (6 products, 4 buildings)") end
function CompassMaker.hireMaker(n,s) s=s or math.random(55,90); local c=500+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CompassMaker.maker={name=n or ("Komparist "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Komparist najet: %s (spretnost: %d)",CompassMaker.maker.name,s),"success") end; return true end
function CompassMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CompassMaker.build(id) local ok,e=CompassMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CompassMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CompassMaker.getQualityBonus() local b=0; for _,bd in ipairs(CompassMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CompassMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and CompassMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.ironCost and CompassMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.brassCost and CompassMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.glassCost and CompassMaker.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.silverCost and CompassMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CompassMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CompassMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CompassMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CompassMaker.buildings==0 then return false,"Potrebna kompasna delavnica" end; if not CompassMaker.maker then return false,"Potreben komparist" end; return true end
function CompassMaker.make(pt,qty) qty=qty or 1; local ok,e=CompassMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then CompassMaker.woodStock=CompassMaker.woodStock-d.woodCost*qty end; if d.ironCost then CompassMaker.ironStock=CompassMaker.ironStock-d.ironCost*qty end; if d.brassCost then CompassMaker.brassStock=CompassMaker.brassStock-d.brassCost*qty end; if d.glassCost then CompassMaker.glassStock=CompassMaker.glassStock-d.glassCost*qty end; if d.silverCost then CompassMaker.silverStock=CompassMaker.silverStock-d.silverCost*qty end; if d.goldCost then CompassMaker.goldStock=CompassMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CompassMaker.jewelStock=CompassMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CompassMaker.pearlStock=CompassMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CompassMaker.maker then t=math.max(1,t-math.floor(CompassMaker.maker.skill/13)) end; table.insert(CompassMaker.activeMaking,{id="compass_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,navigation=d.navigation or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CompassMaker.completeMaking(m) local q=1.0+(CompassMaker.getQualityBonus()/100); if CompassMaker.maker then q=q+(CompassMaker.maker.skill/150) end; q=math.min(2.4,q); CompassMaker.productStock[m.productType]=(CompassMaker.productStock[m.productType] or 0)+m.quantity; CompassMaker.totalProducts=CompassMaker.totalProducts+m.quantity; if m.navigation>0 and _G.state then _G.state.navigation=(_G.state.navigation or 0)+m.navigation end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CompassMaker.maker then CompassMaker.maker.itemsMade=CompassMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CompassMaker.maker.skill=math.min(100,CompassMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Kompas izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"compass.completed",{productName=m.productName,navigation=m.navigation,prestige=m.prestige,happiness=m.happiness}) end end
function CompassMaker.update(dt) if not _G.state then return end; CompassMaker.dayTimer=CompassMaker.dayTimer+dt; if CompassMaker.dayTimer>=30 then CompassMaker.dayTimer=0; for i=#CompassMaker.activeMaking,1,-1 do local m=CompassMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CompassMaker.completeMaking(m); table.remove(CompassMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CompassMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CompassMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CompassMaker.getStats() return {woodStock=CompassMaker.woodStock,ironStock=CompassMaker.ironStock,brassStock=CompassMaker.brassStock,glassStock=CompassMaker.glassStock,silverStock=CompassMaker.silverStock,goldStock=CompassMaker.goldStock,jewelStock=CompassMaker.jewelStock,pearlStock=CompassMaker.pearlStock,productStock=CompassMaker.productStock,numBuildings=#CompassMaker.buildings,hasMaker=CompassMaker.maker~=nil,makerName=CompassMaker.maker and CompassMaker.maker.name or "—",makerSkill=CompassMaker.maker and CompassMaker.maker.skill or 0,activeMaking=#CompassMaker.activeMaking,totalProducts=CompassMaker.totalProducts} end
return CompassMaker
