local HatPinMaker = {}
local PRODUCTS = {
    iron_hat_pin = { name = "Železna sponka za klobuke", ironCost = 3, woodCost = 1, leatherCost = 1, time = 5, cost = 160, prestige = 3, happiness = 2, description = "Železna sponka za pritrditev klobuka." },
    bronze_hat_pin = { name = "Bronasta sponka za klobuke", bronzeCost = 3, ironCost = 1, woodCost = 1, leatherCost = 1, time = 7, cost = 390, prestige = 5, happiness = 3, description = "Bronasta sponka za klobučarje." },
    silver_hat_pin = { name = "Srebrna sponka za klobuke", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 11, cost = 940, prestige = 10, happiness = 4, description = "Srebrna sponka za plemiške klobučarje." },
    gilded_hat_pin = { name = "Pozlačena sponka za klobuke", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 15, cost = 2030, prestige = 19, happiness = 5, description = "Pozlačena sponka za dvorne klobučarje." },
    jewel_set_hat_pin = { name = "Draguljasta sponka za klobuke", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 19, cost = 4380, prestige = 35, happiness = 7, description = "Draguljasta sponka za kraljeve klobučarje." },
    royal_sovereign_hat_pin = { name = "Kraljevski suverena sponka za klobuke", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 26, cost = 9400, prestige = 67, happiness = 13, description = "Suverena sponka z biseri za krono." },
}
local BUILDINGS = {
    hatpin_workshop = { name = "Spončna delavnica", cost = { gold = 325, wood = 175, stone = 130, iron = 8 }, upkeep = 6, qualityBonus = 5 },
    hatpin_house = { name = "Spončna hiša", cost = { gold = 1185, wood = 355, stone = 270, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_hatpin_atelier = { name = "Mojstrski spončni atelje", cost = { gold = 2975, wood = 415, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_hatpin_palace = { name = "Suverena spončna palača", cost = { gold = 12920, wood = 635, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
HatPinMaker.ironStock = 14; HatPinMaker.bronzeStock = 12; HatPinMaker.woodStock = 10; HatPinMaker.leatherStock = 8; HatPinMaker.silverStock = 8; HatPinMaker.goldStock = 6; HatPinMaker.jewelStock = 4; HatPinMaker.pearlStock = 4
HatPinMaker.productStock = {}; HatPinMaker.buildings = {}; HatPinMaker.maker = nil; HatPinMaker.activeMaking = {}; HatPinMaker.totalProducts = 0; HatPinMaker.dayTimer = 0
function HatPinMaker.init() HatPinMaker.ironStock=14; HatPinMaker.bronzeStock=12; HatPinMaker.woodStock=10; HatPinMaker.leatherStock=8; HatPinMaker.silverStock=8; HatPinMaker.goldStock=6; HatPinMaker.jewelStock=4; HatPinMaker.pearlStock=4; HatPinMaker.productStock={}; HatPinMaker.buildings={}; HatPinMaker.maker=nil; HatPinMaker.activeMaking={}; HatPinMaker.totalProducts=0; HatPinMaker.dayTimer=0; print("[HatPinMaker] Royal Hat Pin Maker System initialized (6 products, 4 buildings)") end
function HatPinMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HatPinMaker.maker={name=n or ("Sponkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sponkar najet: %s (spretnost: %d)",HatPinMaker.maker.name,s),"success") end; return true end
function HatPinMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HatPinMaker.build(id) local ok,e=HatPinMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HatPinMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HatPinMaker.getQualityBonus() local b=0; for _,bd in ipairs(HatPinMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HatPinMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and HatPinMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and HatPinMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and HatPinMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and HatPinMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and HatPinMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HatPinMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HatPinMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and HatPinMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #HatPinMaker.buildings==0 then return false,"Potrebna spončna delavnica" end; if not HatPinMaker.maker then return false,"Potreben sponkar" end; return true end
function HatPinMaker.make(pt,qty) qty=qty or 1; local ok,e=HatPinMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then HatPinMaker.ironStock=HatPinMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then HatPinMaker.bronzeStock=HatPinMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then HatPinMaker.woodStock=HatPinMaker.woodStock-d.woodCost*qty end; if d.leatherCost then HatPinMaker.leatherStock=HatPinMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then HatPinMaker.silverStock=HatPinMaker.silverStock-d.silverCost*qty end; if d.goldCost then HatPinMaker.goldStock=HatPinMaker.goldStock-d.goldCost*qty end; if d.jewelCost then HatPinMaker.jewelStock=HatPinMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then HatPinMaker.pearlStock=HatPinMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if HatPinMaker.maker then t=math.max(1,t-math.floor(HatPinMaker.maker.skill/13)) end; table.insert(HatPinMaker.activeMaking,{id="hatpin_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HatPinMaker.completeMaking(m) local q=1.0+(HatPinMaker.getQualityBonus()/100); if HatPinMaker.maker then q=q+(HatPinMaker.maker.skill/140) end; q=math.min(2.5,q); HatPinMaker.productStock[m.productType]=(HatPinMaker.productStock[m.productType] or 0)+m.quantity; HatPinMaker.totalProducts=HatPinMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HatPinMaker.maker then HatPinMaker.maker.itemsMade=HatPinMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then HatPinMaker.maker.skill=math.min(100,HatPinMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sponka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"hatpin.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function HatPinMaker.update(dt) if not _G.state then return end; HatPinMaker.dayTimer=HatPinMaker.dayTimer+dt; if HatPinMaker.dayTimer>=30 then HatPinMaker.dayTimer=0; for i=#HatPinMaker.activeMaking,1,-1 do local m=HatPinMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HatPinMaker.completeMaking(m); table.remove(HatPinMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HatPinMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HatPinMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HatPinMaker.getStats() return {ironStock=HatPinMaker.ironStock,bronzeStock=HatPinMaker.bronzeStock,woodStock=HatPinMaker.woodStock,leatherStock=HatPinMaker.leatherStock,silverStock=HatPinMaker.silverStock,goldStock=HatPinMaker.goldStock,jewelStock=HatPinMaker.jewelStock,pearlStock=HatPinMaker.pearlStock,productStock=HatPinMaker.productStock,numBuildings=#HatPinMaker.buildings,hasMaker=HatPinMaker.maker~=nil,makerName=HatPinMaker.maker and HatPinMaker.maker.name or "—",makerSkill=HatPinMaker.maker and HatPinMaker.maker.skill or 0,activeMaking=#HatPinMaker.activeMaking,totalProducts=HatPinMaker.totalProducts} end
return HatPinMaker
