local CanvasWeaver = {}
local PRODUCTS = {
    coarse_canvas = { name = "Hrapavo platno", hempCost = 3, time = 2, cost = 18, durability = 30, description = "Hrapavo platno za šotore in jadra." },
    sail_canvas = { name = "Jadrno platno", hempCost = 4, oilCost = 1, time = 4, cost = 50, durability = 50, prestige = 1, description = "Jadrno platno z oljno impregnacijo." },
    tent_canvas = { name = "Šotorsko platno", hempCost = 4, oilCost = 1, waxCost = 1, time = 5, cost = 110, durability = 65, prestige = 2, happiness = 1, description = "Šotorsko platno z voskom za vodoodpornost." },
    painters_canvas = { name = "Slikarsko platno", linenCost = 3, gessoCost = 1, time = 7, cost = 240, durability = 75, prestige = 5, happiness = 2, description = "Slikarsko platno z gesso podlago." },
    silver_thread_canvas = { name = "Srebrno nitno platno", linenCost = 4, silverCost = 1, gessoCost = 1, time = 10, cost = 520, durability = 88, prestige = 12, happiness = 3, description = "Platno s srebrnimi nitmi za plemiče." },
    royal_grand_canvas = { name = "Kraljevski veliki platno", linenCost = 6, hempCost = 4, goldCost = 1, silverCost = 1, jewelCost = 1, gessoCost = 2, time = 15, cost = 1600, durability = 100, prestige = 36, happiness = 8, description = "Veliko kraljevsko platno z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Platnarska delavnica", cost = { gold = 280, wood = 140, stone = 200 }, upkeep = 7, qualityBonus = 5 },
    loom_house = { name = "Tkalnica", cost = { gold = 950, wood = 280, stone = 400, hemp = 8 }, upkeep = 23, qualityBonus = 18 },
    finishing_room = { name = "Dokončevalnica", cost = { gold = 2300, wood = 350, stone = 600, silver = 30, oil = 8 }, upkeep = 58, qualityBonus = 30 },
    royal_canvas_atelier = { name = "Kraljevski atelje platna", cost = { gold = 9200, wood = 600, stone = 1000, gold = 60, jewel = 20 }, upkeep = 180, qualityBonus = 55, prestigeBonus = 40 },
}
CanvasWeaver.hempStock = 22; CanvasWeaver.linenStock = 18; CanvasWeaver.oilStock = 14; CanvasWeaver.waxStock = 12; CanvasWeaver.gessoStock = 12; CanvasWeaver.silverStock = 8; CanvasWeaver.goldStock = 6; CanvasWeaver.jewelStock = 6
CanvasWeaver.productStock = {}; CanvasWeaver.buildings = {}; CanvasWeaver.maker = nil; CanvasWeaver.activeMaking = {}; CanvasWeaver.totalProducts = 0; CanvasWeaver.dayTimer = 0
function CanvasWeaver.init() CanvasWeaver.hempStock=22; CanvasWeaver.linenStock=18; CanvasWeaver.oilStock=14; CanvasWeaver.waxStock=12; CanvasWeaver.gessoStock=12; CanvasWeaver.silverStock=8; CanvasWeaver.goldStock=6; CanvasWeaver.jewelStock=6; CanvasWeaver.productStock={}; CanvasWeaver.buildings={}; CanvasWeaver.maker=nil; CanvasWeaver.activeMaking={}; CanvasWeaver.totalProducts=0; CanvasWeaver.dayTimer=0; print("[CanvasWeaver] Royal Canvas Weaver System initialized (6 products, 4 buildings)") end
function CanvasWeaver.hireMaker(n,s) s=s or math.random(50,90); local c=510+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CanvasWeaver.maker={name=n or ("Platnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Platnar najet: %s (spretnost: %d)",CanvasWeaver.maker.name,s),"success") end; return true end
function CanvasWeaver.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CanvasWeaver.build(id) local ok,e=CanvasWeaver.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CanvasWeaver.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CanvasWeaver.getQualityBonus() local b=0; for _,bd in ipairs(CanvasWeaver.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CanvasWeaver.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.hempCost and CanvasWeaver.hempStock<(d.hempCost or 0) then return false,"Premalo konoplje" end; if d.linenCost and CanvasWeaver.linenStock<(d.linenCost or 0) then return false,"Premalo lana" end; if d.oilCost and CanvasWeaver.oilStock<(d.oilCost or 0) then return false,"Premalo olja" end; if d.waxCost and CanvasWeaver.waxStock<(d.waxCost or 0) then return false,"Premalo voska" end; if d.gessoCost and CanvasWeaver.gessoStock<(d.gessoCost or 0) then return false,"Premalo gesso" end; if d.silverCost and CanvasWeaver.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CanvasWeaver.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CanvasWeaver.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #CanvasWeaver.buildings==0 then return false,"Potrebna delavnica" end; if not CanvasWeaver.maker then return false,"Potreben platnar" end; return true end
function CanvasWeaver.make(pt,qty) qty=qty or 5; local ok,e=CanvasWeaver.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.hempCost then CanvasWeaver.hempStock=CanvasWeaver.hempStock-d.hempCost*qty end; if d.linenCost then CanvasWeaver.linenStock=CanvasWeaver.linenStock-d.linenCost*qty end; if d.oilCost then CanvasWeaver.oilStock=CanvasWeaver.oilStock-d.oilCost*qty end; if d.waxCost then CanvasWeaver.waxStock=CanvasWeaver.waxStock-d.waxCost*qty end; if d.gessoCost then CanvasWeaver.gessoStock=CanvasWeaver.gessoStock-d.gessoCost*qty end; if d.silverCost then CanvasWeaver.silverStock=CanvasWeaver.silverStock-d.silverCost*qty end; if d.goldCost then CanvasWeaver.goldStock=CanvasWeaver.goldStock-d.goldCost*qty end; if d.jewelCost then CanvasWeaver.jewelStock=CanvasWeaver.jewelStock-d.jewelCost*qty end; local t=d.time; if CanvasWeaver.maker then t=math.max(1,t-math.floor(CanvasWeaver.maker.skill/12)) end; table.insert(CanvasWeaver.activeMaking,{id="canvas_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,durability=d.durability or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CanvasWeaver.completeMaking(m) local q=1.0+(CanvasWeaver.getQualityBonus()/100); if CanvasWeaver.maker then q=q+(CanvasWeaver.maker.skill/180) end; q=math.min(2.0,q); CanvasWeaver.productStock[m.productType]=(CanvasWeaver.productStock[m.productType] or 0)+m.quantity; CanvasWeaver.totalProducts=CanvasWeaver.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CanvasWeaver.maker then CanvasWeaver.maker.itemsMade=CanvasWeaver.maker.itemsMade+m.quantity; if math.random()<0.20 then CanvasWeaver.maker.skill=math.min(100,CanvasWeaver.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Platno izdelano: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"canvas.completed",{productName=m.productName,durability=m.durability}) end end
function CanvasWeaver.update(dt) if not _G.state then return end; CanvasWeaver.dayTimer=CanvasWeaver.dayTimer+dt; if CanvasWeaver.dayTimer>=30 then CanvasWeaver.dayTimer=0; for i=#CanvasWeaver.activeMaking,1,-1 do local m=CanvasWeaver.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CanvasWeaver.completeMaking(m); table.remove(CanvasWeaver.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CanvasWeaver.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CanvasWeaver.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CanvasWeaver.getStats() return {hempStock=CanvasWeaver.hempStock,linenStock=CanvasWeaver.linenStock,oilStock=CanvasWeaver.oilStock,waxStock=CanvasWeaver.waxStock,gessoStock=CanvasWeaver.gessoStock,silverStock=CanvasWeaver.silverStock,goldStock=CanvasWeaver.goldStock,jewelStock=CanvasWeaver.jewelStock,productStock=CanvasWeaver.productStock,numBuildings=#CanvasWeaver.buildings,hasMaker=CanvasWeaver.maker~=nil,makerName=CanvasWeaver.maker and CanvasWeaver.maker.name or "—",makerSkill=CanvasWeaver.maker and CanvasWeaver.maker.skill or 0,activeMaking=#CanvasWeaver.activeMaking,totalProducts=CanvasWeaver.totalProducts} end
return CanvasWeaver
