local SandRiddleMaker = {}
local PRODUCTS = {
    iron_sandriddle = { name = "Železni sito za pesek", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni sito za pesek za livarje." },
    bronze_sandriddle = { name = "Bronast sito za pesek", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast sito za pesek za livarje." },
    silver_sandriddle = { name = "Srebrn sito za pesek", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn sito za pesek za livarje." },
    gilded_sandriddle = { name = "Pozlačen sito za pesek", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen sito za pesek za livarje." },
    jewel_set_sandriddle = { name = "Draguljast sito za pesek", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast sito za pesek za livarje." },
    royal_sovereign_sandriddle = { name = "Kraljevski suveren sito za pesek", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren sito za pesek z biseri za krono." },
}
local BUILDINGS = {
    sandriddle_workshop = { name = "Sandriddle delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    sandriddle_house = { name = "Sandriddle hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_sandriddle_atelier = { name = "Mojstrski sandriddle atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_sandriddle_palace = { name = "Suverena sandriddle palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SandRiddleMaker.ironStock=12; SandRiddleMaker.bronzeStock=10; SandRiddleMaker.woodStock=16; SandRiddleMaker.leatherStock=10; SandRiddleMaker.silverStock=8; SandRiddleMaker.goldStock=6; SandRiddleMaker.jewelStock=4; SandRiddleMaker.pearlStock=4
SandRiddleMaker.productStock = {}; SandRiddleMaker.buildings = {}; SandRiddleMaker.maker = nil; SandRiddleMaker.activeMaking = {}; SandRiddleMaker.totalProducts = 0; SandRiddleMaker.dayTimer = 0
function SandRiddleMaker.init() SandRiddleMaker.ironStock=12; SandRiddleMaker.bronzeStock=10; SandRiddleMaker.woodStock=16; SandRiddleMaker.leatherStock=10; SandRiddleMaker.silverStock=8; SandRiddleMaker.goldStock=6; SandRiddleMaker.jewelStock=4; SandRiddleMaker.pearlStock=4; SandRiddleMaker.productStock={}; SandRiddleMaker.buildings={}; SandRiddleMaker.maker=nil; SandRiddleMaker.activeMaking={}; SandRiddleMaker.totalProducts=0; SandRiddleMaker.dayTimer=0; print("[SandRiddleMaker] Royal Sand Riddle Maker System initialized (6 products, 4 buildings)") end
function SandRiddleMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SandRiddleMaker.maker={name=n or ("Sitar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sitar najet: %s (spretnost: %d)",SandRiddleMaker.maker.name,s),"success") end; return true end
function SandRiddleMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SandRiddleMaker.build(id) local ok,e=SandRiddleMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SandRiddleMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SandRiddleMaker.getQualityBonus() local b=0; for _,bd in ipairs(SandRiddleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SandRiddleMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SandRiddleMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SandRiddleMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SandRiddleMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SandRiddleMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SandRiddleMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SandRiddleMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SandRiddleMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SandRiddleMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SandRiddleMaker.buildings==0 then return false,"Potrebna sitalna delavnica" end; if not SandRiddleMaker.maker then return false,"Potreben sitar" end; return true end
function SandRiddleMaker.make(pt,qty) qty=qty or 1; local ok,e=SandRiddleMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SandRiddleMaker.ironStock=SandRiddleMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SandRiddleMaker.bronzeStock=SandRiddleMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SandRiddleMaker.woodStock=SandRiddleMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SandRiddleMaker.leatherStock=SandRiddleMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SandRiddleMaker.silverStock=SandRiddleMaker.silverStock-d.silverCost*qty end; if d.goldCost then SandRiddleMaker.goldStock=SandRiddleMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SandRiddleMaker.jewelStock=SandRiddleMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SandRiddleMaker.pearlStock=SandRiddleMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SandRiddleMaker.maker then t=math.max(1,t-math.floor(SandRiddleMaker.maker.skill/13)) end; table.insert(SandRiddleMaker.activeMaking,{id="sandriddle_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SandRiddleMaker.completeMaking(m) local q=1.0+(SandRiddleMaker.getQualityBonus()/100); if SandRiddleMaker.maker then q=q+(SandRiddleMaker.maker.skill/140) end; q=math.min(2.5,q); SandRiddleMaker.productStock[m.productType]=(SandRiddleMaker.productStock[m.productType] or 0)+m.quantity; SandRiddleMaker.totalProducts=SandRiddleMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SandRiddleMaker.maker then SandRiddleMaker.maker.itemsMade=SandRiddleMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SandRiddleMaker.maker.skill=math.min(100,SandRiddleMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sito izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sandriddle.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SandRiddleMaker.update(dt) if not _G.state then return end; SandRiddleMaker.dayTimer=SandRiddleMaker.dayTimer+dt; if SandRiddleMaker.dayTimer>=30 then SandRiddleMaker.dayTimer=0; for i=#SandRiddleMaker.activeMaking,1,-1 do local m=SandRiddleMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SandRiddleMaker.completeMaking(m); table.remove(SandRiddleMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SandRiddleMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SandRiddleMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SandRiddleMaker.getStats() return {ironStock=SandRiddleMaker.ironStock,bronzeStock=SandRiddleMaker.bronzeStock,woodStock=SandRiddleMaker.woodStock,leatherStock=SandRiddleMaker.leatherStock,silverStock=SandRiddleMaker.silverStock,goldStock=SandRiddleMaker.goldStock,jewelStock=SandRiddleMaker.jewelStock,pearlStock=SandRiddleMaker.pearlStock,productStock=SandRiddleMaker.productStock,numBuildings=#SandRiddleMaker.buildings,hasMaker=SandRiddleMaker.maker~=nil,makerName=SandRiddleMaker.maker and SandRiddleMaker.maker.name or "—",makerSkill=SandRiddleMaker.maker and SandRiddleMaker.maker.skill or 0,activeMaking=#SandRiddleMaker.activeMaking,totalProducts=SandRiddleMaker.totalProducts} end
return SandRiddleMaker
