local MoldReleaseAgentMaker = {}
local PRODUCTS = {
    iron_moldreleaseagent = { name = "Železni sredstvo za ločitev kalupov", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni sredstvo za ločitev kalupov za livarje." },
    bronze_moldreleaseagent = { name = "Bronast sredstvo za ločitev kalupov", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast sredstvo za ločitev kalupov za livarje." },
    silver_moldreleaseagent = { name = "Srebrn sredstvo za ločitev kalupov", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn sredstvo za ločitev kalupov za livarje." },
    gilded_moldreleaseagent = { name = "Pozlačen sredstvo za ločitev kalupov", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen sredstvo za ločitev kalupov za livarje." },
    jewel_set_moldreleaseagent = { name = "Draguljast sredstvo za ločitev kalupov", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast sredstvo za ločitev kalupov za livarje." },
    royal_sovereign_moldreleaseagent = { name = "Kraljevski suveren sredstvo za ločitev kalupov", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren sredstvo za ločitev kalupov z biseri za krono." },
}
local BUILDINGS = {
    moldreleaseagent_workshop = { name = "Moldreleaseagent delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    moldreleaseagent_house = { name = "Moldreleaseagent hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_moldreleaseagent_atelier = { name = "Mojstrski moldreleaseagent atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_moldreleaseagent_palace = { name = "Suverena moldreleaseagent palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MoldReleaseAgentMaker.ironStock=12; MoldReleaseAgentMaker.bronzeStock=10; MoldReleaseAgentMaker.woodStock=14; MoldReleaseAgentMaker.leatherStock=12; MoldReleaseAgentMaker.silverStock=8; MoldReleaseAgentMaker.goldStock=6; MoldReleaseAgentMaker.jewelStock=4; MoldReleaseAgentMaker.pearlStock=4
MoldReleaseAgentMaker.productStock = {}; MoldReleaseAgentMaker.buildings = {}; MoldReleaseAgentMaker.maker = nil; MoldReleaseAgentMaker.activeMaking = {}; MoldReleaseAgentMaker.totalProducts = 0; MoldReleaseAgentMaker.dayTimer = 0
function MoldReleaseAgentMaker.init() MoldReleaseAgentMaker.ironStock=12; MoldReleaseAgentMaker.bronzeStock=10; MoldReleaseAgentMaker.woodStock=14; MoldReleaseAgentMaker.leatherStock=12; MoldReleaseAgentMaker.silverStock=8; MoldReleaseAgentMaker.goldStock=6; MoldReleaseAgentMaker.jewelStock=4; MoldReleaseAgentMaker.pearlStock=4; MoldReleaseAgentMaker.productStock={}; MoldReleaseAgentMaker.buildings={}; MoldReleaseAgentMaker.maker=nil; MoldReleaseAgentMaker.activeMaking={}; MoldReleaseAgentMaker.totalProducts=0; MoldReleaseAgentMaker.dayTimer=0; print("[MoldReleaseAgentMaker] Royal Mold Release Agent Maker System initialized (6 products, 4 buildings)") end
function MoldReleaseAgentMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MoldReleaseAgentMaker.maker={name=n or ("Ločilar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ločilar najet: %s (spretnost: %d)",MoldReleaseAgentMaker.maker.name,s),"success") end; return true end
function MoldReleaseAgentMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MoldReleaseAgentMaker.build(id) local ok,e=MoldReleaseAgentMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MoldReleaseAgentMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MoldReleaseAgentMaker.getQualityBonus() local b=0; for _,bd in ipairs(MoldReleaseAgentMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MoldReleaseAgentMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MoldReleaseAgentMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MoldReleaseAgentMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MoldReleaseAgentMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MoldReleaseAgentMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MoldReleaseAgentMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MoldReleaseAgentMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MoldReleaseAgentMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MoldReleaseAgentMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MoldReleaseAgentMaker.buildings==0 then return false,"Potrebna ločilna delavnica" end; if not MoldReleaseAgentMaker.maker then return false,"Potreben ločilar" end; return true end
function MoldReleaseAgentMaker.make(pt,qty) qty=qty or 1; local ok,e=MoldReleaseAgentMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MoldReleaseAgentMaker.ironStock=MoldReleaseAgentMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MoldReleaseAgentMaker.bronzeStock=MoldReleaseAgentMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MoldReleaseAgentMaker.woodStock=MoldReleaseAgentMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MoldReleaseAgentMaker.leatherStock=MoldReleaseAgentMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MoldReleaseAgentMaker.silverStock=MoldReleaseAgentMaker.silverStock-d.silverCost*qty end; if d.goldCost then MoldReleaseAgentMaker.goldStock=MoldReleaseAgentMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MoldReleaseAgentMaker.jewelStock=MoldReleaseAgentMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MoldReleaseAgentMaker.pearlStock=MoldReleaseAgentMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MoldReleaseAgentMaker.maker then t=math.max(1,t-math.floor(MoldReleaseAgentMaker.maker.skill/13)) end; table.insert(MoldReleaseAgentMaker.activeMaking,{id="moldreleaseagent_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MoldReleaseAgentMaker.completeMaking(m) local q=1.0+(MoldReleaseAgentMaker.getQualityBonus()/100); if MoldReleaseAgentMaker.maker then q=q+(MoldReleaseAgentMaker.maker.skill/140) end; q=math.min(2.5,q); MoldReleaseAgentMaker.productStock[m.productType]=(MoldReleaseAgentMaker.productStock[m.productType] or 0)+m.quantity; MoldReleaseAgentMaker.totalProducts=MoldReleaseAgentMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MoldReleaseAgentMaker.maker then MoldReleaseAgentMaker.maker.itemsMade=MoldReleaseAgentMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MoldReleaseAgentMaker.maker.skill=math.min(100,MoldReleaseAgentMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Ločilo izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"moldreleaseagent.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MoldReleaseAgentMaker.update(dt) if not _G.state then return end; MoldReleaseAgentMaker.dayTimer=MoldReleaseAgentMaker.dayTimer+dt; if MoldReleaseAgentMaker.dayTimer>=30 then MoldReleaseAgentMaker.dayTimer=0; for i=#MoldReleaseAgentMaker.activeMaking,1,-1 do local m=MoldReleaseAgentMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MoldReleaseAgentMaker.completeMaking(m); table.remove(MoldReleaseAgentMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MoldReleaseAgentMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MoldReleaseAgentMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MoldReleaseAgentMaker.getStats() return {ironStock=MoldReleaseAgentMaker.ironStock,bronzeStock=MoldReleaseAgentMaker.bronzeStock,woodStock=MoldReleaseAgentMaker.woodStock,leatherStock=MoldReleaseAgentMaker.leatherStock,silverStock=MoldReleaseAgentMaker.silverStock,goldStock=MoldReleaseAgentMaker.goldStock,jewelStock=MoldReleaseAgentMaker.jewelStock,pearlStock=MoldReleaseAgentMaker.pearlStock,productStock=MoldReleaseAgentMaker.productStock,numBuildings=#MoldReleaseAgentMaker.buildings,hasMaker=MoldReleaseAgentMaker.maker~=nil,makerName=MoldReleaseAgentMaker.maker and MoldReleaseAgentMaker.maker.name or "—",makerSkill=MoldReleaseAgentMaker.maker and MoldReleaseAgentMaker.maker.skill or 0,activeMaking=#MoldReleaseAgentMaker.activeMaking,totalProducts=MoldReleaseAgentMaker.totalProducts} end
return MoldReleaseAgentMaker
