local SmithTongsRingMaker = {}
local PRODUCTS = {
    iron_smithtongsring = { name = "Železni obroč za kovaške klešče", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni obroč za kovaške klešče za kovace." },
    bronze_smithtongsring = { name = "Bronast obroč za kovaške klešče", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast obroč za kovaške klešče za kovace." },
    silver_smithtongsring = { name = "Srebrn obroč za kovaške klešče", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn obroč za kovaške klešče za kovace." },
    gilded_smithtongsring = { name = "Pozlačen obroč za kovaške klešče", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen obroč za kovaške klešče za kovace." },
    jewel_set_smithtongsring = { name = "Draguljast obroč za kovaške klešče", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast obroč za kovaške klešče za kovace." },
    royal_sovereign_smithtongsring = { name = "Kraljevski suveren obroč za kovaške klešče", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren obroč za kovaške klešče z biseri za krono." },
}
local BUILDINGS = {
    smithtongsring_workshop = { name = "Smithtongsring delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    smithtongsring_house = { name = "Smithtongsring hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_smithtongsring_atelier = { name = "Mojstrski smithtongsring atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_smithtongsring_palace = { name = "Suverena smithtongsring palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
SmithTongsRingMaker.ironStock=14; SmithTongsRingMaker.bronzeStock=12; SmithTongsRingMaker.woodStock=12; SmithTongsRingMaker.leatherStock=8; SmithTongsRingMaker.silverStock=8; SmithTongsRingMaker.goldStock=6; SmithTongsRingMaker.jewelStock=4; SmithTongsRingMaker.pearlStock=4
SmithTongsRingMaker.productStock = {}; SmithTongsRingMaker.buildings = {}; SmithTongsRingMaker.maker = nil; SmithTongsRingMaker.activeMaking = {}; SmithTongsRingMaker.totalProducts = 0; SmithTongsRingMaker.dayTimer = 0
function SmithTongsRingMaker.init() SmithTongsRingMaker.ironStock=14; SmithTongsRingMaker.bronzeStock=12; SmithTongsRingMaker.woodStock=12; SmithTongsRingMaker.leatherStock=8; SmithTongsRingMaker.silverStock=8; SmithTongsRingMaker.goldStock=6; SmithTongsRingMaker.jewelStock=4; SmithTongsRingMaker.pearlStock=4; SmithTongsRingMaker.productStock={}; SmithTongsRingMaker.buildings={}; SmithTongsRingMaker.maker=nil; SmithTongsRingMaker.activeMaking={}; SmithTongsRingMaker.totalProducts=0; SmithTongsRingMaker.dayTimer=0; print("[SmithTongsRingMaker] Royal Smith Tongs Ring Maker System initialized (6 products, 4 buildings)") end
function SmithTongsRingMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SmithTongsRingMaker.maker={name=n or ("Obročnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Obročnik najet: %s (spretnost: %d)",SmithTongsRingMaker.maker.name,s),"success") end; return true end
function SmithTongsRingMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SmithTongsRingMaker.build(id) local ok,e=SmithTongsRingMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SmithTongsRingMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SmithTongsRingMaker.getQualityBonus() local b=0; for _,bd in ipairs(SmithTongsRingMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SmithTongsRingMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and SmithTongsRingMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and SmithTongsRingMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and SmithTongsRingMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and SmithTongsRingMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and SmithTongsRingMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SmithTongsRingMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SmithTongsRingMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SmithTongsRingMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SmithTongsRingMaker.buildings==0 then return false,"Potrebna obročna delavnica" end; if not SmithTongsRingMaker.maker then return false,"Potreben obrocnik" end; return true end
function SmithTongsRingMaker.make(pt,qty) qty=qty or 1; local ok,e=SmithTongsRingMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then SmithTongsRingMaker.ironStock=SmithTongsRingMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then SmithTongsRingMaker.bronzeStock=SmithTongsRingMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then SmithTongsRingMaker.woodStock=SmithTongsRingMaker.woodStock-d.woodCost*qty end; if d.leatherCost then SmithTongsRingMaker.leatherStock=SmithTongsRingMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then SmithTongsRingMaker.silverStock=SmithTongsRingMaker.silverStock-d.silverCost*qty end; if d.goldCost then SmithTongsRingMaker.goldStock=SmithTongsRingMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SmithTongsRingMaker.jewelStock=SmithTongsRingMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SmithTongsRingMaker.pearlStock=SmithTongsRingMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SmithTongsRingMaker.maker then t=math.max(1,t-math.floor(SmithTongsRingMaker.maker.skill/13)) end; table.insert(SmithTongsRingMaker.activeMaking,{id="smithtongsring_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SmithTongsRingMaker.completeMaking(m) local q=1.0+(SmithTongsRingMaker.getQualityBonus()/100); if SmithTongsRingMaker.maker then q=q+(SmithTongsRingMaker.maker.skill/140) end; q=math.min(2.5,q); SmithTongsRingMaker.productStock[m.productType]=(SmithTongsRingMaker.productStock[m.productType] or 0)+m.quantity; SmithTongsRingMaker.totalProducts=SmithTongsRingMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SmithTongsRingMaker.maker then SmithTongsRingMaker.maker.itemsMade=SmithTongsRingMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SmithTongsRingMaker.maker.skill=math.min(100,SmithTongsRingMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Obroč izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"smithtongsring.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function SmithTongsRingMaker.update(dt) if not _G.state then return end; SmithTongsRingMaker.dayTimer=SmithTongsRingMaker.dayTimer+dt; if SmithTongsRingMaker.dayTimer>=30 then SmithTongsRingMaker.dayTimer=0; for i=#SmithTongsRingMaker.activeMaking,1,-1 do local m=SmithTongsRingMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SmithTongsRingMaker.completeMaking(m); table.remove(SmithTongsRingMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SmithTongsRingMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SmithTongsRingMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SmithTongsRingMaker.getStats() return {ironStock=SmithTongsRingMaker.ironStock,bronzeStock=SmithTongsRingMaker.bronzeStock,woodStock=SmithTongsRingMaker.woodStock,leatherStock=SmithTongsRingMaker.leatherStock,silverStock=SmithTongsRingMaker.silverStock,goldStock=SmithTongsRingMaker.goldStock,jewelStock=SmithTongsRingMaker.jewelStock,pearlStock=SmithTongsRingMaker.pearlStock,productStock=SmithTongsRingMaker.productStock,numBuildings=#SmithTongsRingMaker.buildings,hasMaker=SmithTongsRingMaker.maker~=nil,makerName=SmithTongsRingMaker.maker and SmithTongsRingMaker.maker.name or "—",makerSkill=SmithTongsRingMaker.maker and SmithTongsRingMaker.maker.skill or 0,activeMaking=#SmithTongsRingMaker.activeMaking,totalProducts=SmithTongsRingMaker.totalProducts} end
return SmithTongsRingMaker
