local AnvilSaddleBlockMaker = {}
local PRODUCTS = {
    iron_anvilsaddleblock = { name = "Železni blok za nakovalo", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni blok za nakovalo za kovace." },
    bronze_anvilsaddleblock = { name = "Bronast blok za nakovalo", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast blok za nakovalo za kovace." },
    silver_anvilsaddleblock = { name = "Srebrn blok za nakovalo", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn blok za nakovalo za kovace." },
    gilded_anvilsaddleblock = { name = "Pozlačen blok za nakovalo", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen blok za nakovalo za kovace." },
    jewel_set_anvilsaddleblock = { name = "Draguljast blok za nakovalo", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast blok za nakovalo za kovace." },
    royal_sovereign_anvilsaddleblock = { name = "Kraljevski suveren blok za nakovalo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren blok za nakovalo z biseri za krono." },
}
local BUILDINGS = {
    anvilsaddleblock_workshop = { name = "Anvilsaddleblock delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    anvilsaddleblock_house = { name = "Anvilsaddleblock hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_anvilsaddleblock_atelier = { name = "Mojstrski anvilsaddleblock atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_anvilsaddleblock_palace = { name = "Suverena anvilsaddleblock palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
AnvilSaddleBlockMaker.ironStock=18; AnvilSaddleBlockMaker.bronzeStock=14; AnvilSaddleBlockMaker.woodStock=10; AnvilSaddleBlockMaker.leatherStock=8; AnvilSaddleBlockMaker.silverStock=8; AnvilSaddleBlockMaker.goldStock=6; AnvilSaddleBlockMaker.jewelStock=4; AnvilSaddleBlockMaker.pearlStock=4
AnvilSaddleBlockMaker.productStock = {}; AnvilSaddleBlockMaker.buildings = {}; AnvilSaddleBlockMaker.maker = nil; AnvilSaddleBlockMaker.activeMaking = {}; AnvilSaddleBlockMaker.totalProducts = 0; AnvilSaddleBlockMaker.dayTimer = 0
function AnvilSaddleBlockMaker.init() AnvilSaddleBlockMaker.ironStock=18; AnvilSaddleBlockMaker.bronzeStock=14; AnvilSaddleBlockMaker.woodStock=10; AnvilSaddleBlockMaker.leatherStock=8; AnvilSaddleBlockMaker.silverStock=8; AnvilSaddleBlockMaker.goldStock=6; AnvilSaddleBlockMaker.jewelStock=4; AnvilSaddleBlockMaker.pearlStock=4; AnvilSaddleBlockMaker.productStock={}; AnvilSaddleBlockMaker.buildings={}; AnvilSaddleBlockMaker.maker=nil; AnvilSaddleBlockMaker.activeMaking={}; AnvilSaddleBlockMaker.totalProducts=0; AnvilSaddleBlockMaker.dayTimer=0; print("[AnvilSaddleBlockMaker] Royal Anvil Saddle Block Maker System initialized (6 products, 4 buildings)") end
function AnvilSaddleBlockMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; AnvilSaddleBlockMaker.maker={name=n or ("Blokirnik "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Blokirnik najet: %s (spretnost: %d)",AnvilSaddleBlockMaker.maker.name,s),"success") end; return true end
function AnvilSaddleBlockMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function AnvilSaddleBlockMaker.build(id) local ok,e=AnvilSaddleBlockMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(AnvilSaddleBlockMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function AnvilSaddleBlockMaker.getQualityBonus() local b=0; for _,bd in ipairs(AnvilSaddleBlockMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function AnvilSaddleBlockMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and AnvilSaddleBlockMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and AnvilSaddleBlockMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and AnvilSaddleBlockMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and AnvilSaddleBlockMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and AnvilSaddleBlockMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and AnvilSaddleBlockMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and AnvilSaddleBlockMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and AnvilSaddleBlockMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #AnvilSaddleBlockMaker.buildings==0 then return false,"Potrebna blokna delavnica" end; if not AnvilSaddleBlockMaker.maker then return false,"Potreben blokirnik" end; return true end
function AnvilSaddleBlockMaker.make(pt,qty) qty=qty or 1; local ok,e=AnvilSaddleBlockMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then AnvilSaddleBlockMaker.ironStock=AnvilSaddleBlockMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then AnvilSaddleBlockMaker.bronzeStock=AnvilSaddleBlockMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then AnvilSaddleBlockMaker.woodStock=AnvilSaddleBlockMaker.woodStock-d.woodCost*qty end; if d.leatherCost then AnvilSaddleBlockMaker.leatherStock=AnvilSaddleBlockMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then AnvilSaddleBlockMaker.silverStock=AnvilSaddleBlockMaker.silverStock-d.silverCost*qty end; if d.goldCost then AnvilSaddleBlockMaker.goldStock=AnvilSaddleBlockMaker.goldStock-d.goldCost*qty end; if d.jewelCost then AnvilSaddleBlockMaker.jewelStock=AnvilSaddleBlockMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then AnvilSaddleBlockMaker.pearlStock=AnvilSaddleBlockMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if AnvilSaddleBlockMaker.maker then t=math.max(1,t-math.floor(AnvilSaddleBlockMaker.maker.skill/13)) end; table.insert(AnvilSaddleBlockMaker.activeMaking,{id="anvilsaddleblock_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function AnvilSaddleBlockMaker.completeMaking(m) local q=1.0+(AnvilSaddleBlockMaker.getQualityBonus()/100); if AnvilSaddleBlockMaker.maker then q=q+(AnvilSaddleBlockMaker.maker.skill/140) end; q=math.min(2.5,q); AnvilSaddleBlockMaker.productStock[m.productType]=(AnvilSaddleBlockMaker.productStock[m.productType] or 0)+m.quantity; AnvilSaddleBlockMaker.totalProducts=AnvilSaddleBlockMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if AnvilSaddleBlockMaker.maker then AnvilSaddleBlockMaker.maker.itemsMade=AnvilSaddleBlockMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then AnvilSaddleBlockMaker.maker.skill=math.min(100,AnvilSaddleBlockMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Blok izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"anvilsaddleblock.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function AnvilSaddleBlockMaker.update(dt) if not _G.state then return end; AnvilSaddleBlockMaker.dayTimer=AnvilSaddleBlockMaker.dayTimer+dt; if AnvilSaddleBlockMaker.dayTimer>=30 then AnvilSaddleBlockMaker.dayTimer=0; for i=#AnvilSaddleBlockMaker.activeMaking,1,-1 do local m=AnvilSaddleBlockMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then AnvilSaddleBlockMaker.completeMaking(m); table.remove(AnvilSaddleBlockMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(AnvilSaddleBlockMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if AnvilSaddleBlockMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function AnvilSaddleBlockMaker.getStats() return {ironStock=AnvilSaddleBlockMaker.ironStock,bronzeStock=AnvilSaddleBlockMaker.bronzeStock,woodStock=AnvilSaddleBlockMaker.woodStock,leatherStock=AnvilSaddleBlockMaker.leatherStock,silverStock=AnvilSaddleBlockMaker.silverStock,goldStock=AnvilSaddleBlockMaker.goldStock,jewelStock=AnvilSaddleBlockMaker.jewelStock,pearlStock=AnvilSaddleBlockMaker.pearlStock,productStock=AnvilSaddleBlockMaker.productStock,numBuildings=#AnvilSaddleBlockMaker.buildings,hasMaker=AnvilSaddleBlockMaker.maker~=nil,makerName=AnvilSaddleBlockMaker.maker and AnvilSaddleBlockMaker.maker.name or "—",makerSkill=AnvilSaddleBlockMaker.maker and AnvilSaddleBlockMaker.maker.skill or 0,activeMaking=#AnvilSaddleBlockMaker.activeMaking,totalProducts=AnvilSaddleBlockMaker.totalProducts} end
return AnvilSaddleBlockMaker
