local GlassSeedMaker = {}
local PRODUCTS = {
    iron_glass_seed = { name = "Železno seme za steklo", ironCost = 2, woodCost = 2, leatherCost = 1, time = 5, cost = 155, prestige = 3, happiness = 2, description = "Železno seme za osnovno steklo." },
    bronze_glass_seed = { name = "Bronasto seme za steklo", bronzeCost = 2, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 375, prestige = 5, happiness = 3, description = "Bronasto seme za fino steklo." },
    silver_glass_seed = { name = "Srebrno seme za steklo", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 910, prestige = 10, happiness = 4, description = "Srebrno seme za plemiško steklo." },
    gilded_glass_seed = { name = "Pozlačeno seme za steklo", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1960, prestige = 19, happiness = 5, description = "Pozlačeno seme za dvorno steklo." },
    jewel_set_glass_seed = { name = "Draguljasto seme za steklo", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4250, prestige = 35, happiness = 7, description = "Draguljasto seme za kraljevsko steklo." },
    royal_sovereign_glass_seed = { name = "Kraljevski suvereno seme za steklo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 9100, prestige = 67, happiness = 13, description = "Suvereno seme z biseri za krono." },
}
local BUILDINGS = {
    glassseed_workshop = { name = "Semenska delavnica", cost = { gold = 320, wood = 180, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    glassseed_house = { name = "Semenska hiša", cost = { gold = 1185, wood = 360, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_glassseed_atelier = { name = "Mojstrski semenski atelje", cost = { gold = 2980, wood = 420, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_glassseed_palace = { name = "Suverena semenska palača", cost = { gold = 12920, wood = 645, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GlassSeedMaker.ironStock = 12; GlassSeedMaker.bronzeStock = 10; GlassSeedMaker.woodStock = 14; GlassSeedMaker.leatherStock = 8; GlassSeedMaker.silverStock = 8; GlassSeedMaker.goldStock = 6; GlassSeedMaker.jewelStock = 4; GlassSeedMaker.pearlStock = 4
GlassSeedMaker.productStock = {}; GlassSeedMaker.buildings = {}; GlassSeedMaker.maker = nil; GlassSeedMaker.activeMaking = {}; GlassSeedMaker.totalProducts = 0; GlassSeedMaker.dayTimer = 0
function GlassSeedMaker.init() GlassSeedMaker.ironStock=12; GlassSeedMaker.bronzeStock=10; GlassSeedMaker.woodStock=14; GlassSeedMaker.leatherStock=8; GlassSeedMaker.silverStock=8; GlassSeedMaker.goldStock=6; GlassSeedMaker.jewelStock=4; GlassSeedMaker.pearlStock=4; GlassSeedMaker.productStock={}; GlassSeedMaker.buildings={}; GlassSeedMaker.maker=nil; GlassSeedMaker.activeMaking={}; GlassSeedMaker.totalProducts=0; GlassSeedMaker.dayTimer=0; print("[GlassSeedMaker] Royal Glass Seed Maker System initialized (6 products, 4 buildings)") end
function GlassSeedMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassSeedMaker.maker={name=n or ("Seminar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Seminar najet: %s (spretnost: %d)",GlassSeedMaker.maker.name,s),"success") end; return true end
function GlassSeedMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassSeedMaker.build(id) local ok,e=GlassSeedMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassSeedMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassSeedMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassSeedMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassSeedMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassSeedMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassSeedMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassSeedMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassSeedMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassSeedMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassSeedMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassSeedMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassSeedMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassSeedMaker.buildings==0 then return false,"Potrebna semenska delavnica" end; if not GlassSeedMaker.maker then return false,"Potreben seminar" end; return true end
function GlassSeedMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassSeedMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassSeedMaker.ironStock=GlassSeedMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassSeedMaker.bronzeStock=GlassSeedMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassSeedMaker.woodStock=GlassSeedMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassSeedMaker.leatherStock=GlassSeedMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassSeedMaker.silverStock=GlassSeedMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassSeedMaker.goldStock=GlassSeedMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassSeedMaker.jewelStock=GlassSeedMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassSeedMaker.pearlStock=GlassSeedMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassSeedMaker.maker then t=math.max(1,t-math.floor(GlassSeedMaker.maker.skill/13)) end; table.insert(GlassSeedMaker.activeMaking,{id="glassseed_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassSeedMaker.completeMaking(m) local q=1.0+(GlassSeedMaker.getQualityBonus()/100); if GlassSeedMaker.maker then q=q+(GlassSeedMaker.maker.skill/140) end; q=math.min(2.5,q); GlassSeedMaker.productStock[m.productType]=(GlassSeedMaker.productStock[m.productType] or 0)+m.quantity; GlassSeedMaker.totalProducts=GlassSeedMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassSeedMaker.maker then GlassSeedMaker.maker.itemsMade=GlassSeedMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassSeedMaker.maker.skill=math.min(100,GlassSeedMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Seme izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glassseed.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassSeedMaker.update(dt) if not _G.state then return end; GlassSeedMaker.dayTimer=GlassSeedMaker.dayTimer+dt; if GlassSeedMaker.dayTimer>=30 then GlassSeedMaker.dayTimer=0; for i=#GlassSeedMaker.activeMaking,1,-1 do local m=GlassSeedMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassSeedMaker.completeMaking(m); table.remove(GlassSeedMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassSeedMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassSeedMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassSeedMaker.getStats() return {ironStock=GlassSeedMaker.ironStock,bronzeStock=GlassSeedMaker.bronzeStock,woodStock=GlassSeedMaker.woodStock,leatherStock=GlassSeedMaker.leatherStock,silverStock=GlassSeedMaker.silverStock,goldStock=GlassSeedMaker.goldStock,jewelStock=GlassSeedMaker.jewelStock,pearlStock=GlassSeedMaker.pearlStock,productStock=GlassSeedMaker.productStock,numBuildings=#GlassSeedMaker.buildings,hasMaker=GlassSeedMaker.maker~=nil,makerName=GlassSeedMaker.maker and GlassSeedMaker.maker.name or "—",makerSkill=GlassSeedMaker.maker and GlassSeedMaker.maker.skill or 0,activeMaking=#GlassSeedMaker.activeMaking,totalProducts=GlassSeedMaker.totalProducts} end
return GlassSeedMaker
