local DrummerMaker = {}
local PRODUCTS = {
    tabor = { name = "Tabor", woodCost = 1, leatherCost = 1, time = 1, cost = 12, soundQuality = 6, description = "Majhen boben za potujoče glasbenike." },
    side_drum = { name = "Stranski boben", woodCost = 2, leatherCost = 2, time = 3, cost = 40, soundQuality = 10, prestige = 1, description = "Stranski boben za vojaške godbe." },
    kettle_drum = { name = "Pavilon", copperCost = 2, leatherCost = 2, time = 5, cost = 130, soundQuality = 14, prestige = 4, description = "Pavion z bakrenim koritom." },
    tenor_drum = { name = "Tenorski boben", woodCost = 3, brassCost = 1, leatherCost = 2, time = 7, cost = 300, soundQuality = 18, prestige = 8, happiness = 1, description = "Tenorski boben z medeninastim obročem." },
    silver_kettle_drum = { name = "Srebrni pavion", silverCost = 2, leatherCost = 2, time = 10, cost = 700, soundQuality = 24, prestige = 16, happiness = 3, description = "Srebrni pavion za kraljevske godbe." },
    royal_timpani = { name = "Kraljevska timpana", goldCost = 2, silverCost = 2, copperCost = 2, leatherCost = 3, time = 14, cost = 1800, soundQuality = 36, prestige = 45, happiness = 9, description = "Veliki kraljevski par timpan z zlatim in srebrnim okovjem." },
}
local BUILDINGS = {
    workshop = { name = "Bobnarska delavnica", cost = { gold = 240, wood = 120 }, upkeep = 6, qualityBonus = 5 },
    skinning_room = { name = "Strgarna", cost = { gold = 750, wood = 220, stone = 200, leather = 8 }, upkeep = 18, qualityBonus = 18 },
    metal_room = { name = "Kovinska soba", cost = { gold = 1700, wood = 280, stone = 350, silver = 25, copper = 8 }, upkeep = 40, qualityBonus = 30 },
    royal_drum_atelier = { name = "Kraljevski atelje bobnov", cost = { gold = 6500, wood = 500, stone = 700, gold = 50, silver = 30 }, upkeep = 120, qualityBonus = 55, prestigeBonus = 30 },
}
DrummerMaker.woodStock = 14; DrummerMaker.leatherStock = 12; DrummerMaker.copperStock = 10; DrummerMaker.brassStock = 8; DrummerMaker.silverStock = 6; DrummerMaker.goldStock = 6
DrummerMaker.productStock = {}; DrummerMaker.buildings = {}; DrummerMaker.maker = nil; DrummerMaker.activeMaking = {}; DrummerMaker.totalProducts = 0; DrummerMaker.dayTimer = 0
function DrummerMaker.init() DrummerMaker.woodStock=14; DrummerMaker.leatherStock=12; DrummerMaker.copperStock=10; DrummerMaker.brassStock=8; DrummerMaker.silverStock=6; DrummerMaker.goldStock=6; DrummerMaker.productStock={}; DrummerMaker.buildings={}; DrummerMaker.maker=nil; DrummerMaker.activeMaking={}; DrummerMaker.totalProducts=0; DrummerMaker.dayTimer=0; print("[DrummerMaker] Royal Drummer Maker System initialized (6 products, 4 buildings)") end
function DrummerMaker.hireMaker(n,s) s=s or math.random(50,90); local c=450+s*10; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; DrummerMaker.maker={name=n or ("Bobnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Bobnar najet: %s (spretnost: %d)",DrummerMaker.maker.name,s),"success") end; return true end
function DrummerMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function DrummerMaker.build(id) local ok,e=DrummerMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(DrummerMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function DrummerMaker.getQualityBonus() local b=0; for _,bd in ipairs(DrummerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function DrummerMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and DrummerMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and DrummerMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.copperCost and DrummerMaker.copperStock<(d.copperCost or 0) then return false,"Premalo bakra" end; if d.brassCost and DrummerMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.silverCost and DrummerMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and DrummerMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if #DrummerMaker.buildings==0 then return false,"Potrebna delavnica" end; if not DrummerMaker.maker then return false,"Potreben bobnar" end; return true end
function DrummerMaker.make(pt,qty) qty=qty or 1; local ok,e=DrummerMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then DrummerMaker.woodStock=DrummerMaker.woodStock-d.woodCost*qty end; if d.leatherCost then DrummerMaker.leatherStock=DrummerMaker.leatherStock-d.leatherCost*qty end; if d.copperCost then DrummerMaker.copperStock=DrummerMaker.copperStock-d.copperCost*qty end; if d.brassCost then DrummerMaker.brassStock=DrummerMaker.brassStock-d.brassCost*qty end; if d.silverCost then DrummerMaker.silverStock=DrummerMaker.silverStock-d.silverCost*qty end; if d.goldCost then DrummerMaker.goldStock=DrummerMaker.goldStock-d.goldCost*qty end; local t=d.time; if DrummerMaker.maker then t=math.max(1,t-math.floor(DrummerMaker.maker.skill/12)) end; table.insert(DrummerMaker.activeMaking,{id="drum_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,soundQuality=d.soundQuality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function DrummerMaker.completeMaking(m) local q=1.0+(DrummerMaker.getQualityBonus()/100); if DrummerMaker.maker then q=q+(DrummerMaker.maker.skill/180) end; q=math.min(2.0,q); DrummerMaker.productStock[m.productType]=(DrummerMaker.productStock[m.productType] or 0)+m.quantity; DrummerMaker.totalProducts=DrummerMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if DrummerMaker.maker then DrummerMaker.maker.itemsMade=DrummerMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then DrummerMaker.maker.skill=math.min(100,DrummerMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Boben izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"drum.completed",{productName=m.productName,soundQuality=m.soundQuality}) end end
function DrummerMaker.update(dt) if not _G.state then return end; DrummerMaker.dayTimer=DrummerMaker.dayTimer+dt; if DrummerMaker.dayTimer>=30 then DrummerMaker.dayTimer=0; for i=#DrummerMaker.activeMaking,1,-1 do local m=DrummerMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then DrummerMaker.completeMaking(m); table.remove(DrummerMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(DrummerMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if DrummerMaker.maker then tu=tu+12 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function DrummerMaker.getStats() return {woodStock=DrummerMaker.woodStock,leatherStock=DrummerMaker.leatherStock,copperStock=DrummerMaker.copperStock,brassStock=DrummerMaker.brassStock,silverStock=DrummerMaker.silverStock,goldStock=DrummerMaker.goldStock,productStock=DrummerMaker.productStock,numBuildings=#DrummerMaker.buildings,hasMaker=DrummerMaker.maker~=nil,makerName=DrummerMaker.maker and DrummerMaker.maker.name or "—",makerSkill=DrummerMaker.maker and DrummerMaker.maker.skill or 0,activeMaking=#DrummerMaker.activeMaking,totalProducts=DrummerMaker.totalProducts} end
return DrummerMaker
