local LeatherCreaserMaker = {}
local PRODUCTS = {
    iron_leathercreaser = { name = "Železni gubalec usnja", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni gubalec usnja za usnjarje." },
    bronze_leathercreaser = { name = "Bronast gubalec usnja", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast gubalec usnja za usnjarje." },
    silver_leathercreaser = { name = "Srebrn gubalec usnja", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn gubalec usnja za usnjarje." },
    gilded_leathercreaser = { name = "Pozlačen gubalec usnja", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen gubalec usnja za usnjarje." },
    jewel_set_leathercreaser = { name = "Draguljast gubalec usnja", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast gubalec usnja za usnjarje." },
    royal_sovereign_leathercreaser = { name = "Kraljevski suveren gubalec usnja", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren gubalec usnja z biseri za krono." },
}
local BUILDINGS = {
    leathercreaser_workshop = { name = "Leathercreaser delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    leathercreaser_house = { name = "Leathercreaser hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_leathercreaser_atelier = { name = "Mojstrski leathercreaser atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_leathercreaser_palace = { name = "Suverena leathercreaser palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
LeatherCreaserMaker.ironStock = 14; LeatherCreaserMaker.bronzeStock = 12; LeatherCreaserMaker.woodStock = 12; LeatherCreaserMaker.leatherStock = 12; LeatherCreaserMaker.silverStock = 8; LeatherCreaserMaker.goldStock = 6; LeatherCreaserMaker.jewelStock = 4; LeatherCreaserMaker.pearlStock = 4
LeatherCreaserMaker.productStock = {}; LeatherCreaserMaker.buildings = {}; LeatherCreaserMaker.maker = nil; LeatherCreaserMaker.activeMaking = {}; LeatherCreaserMaker.totalProducts = 0; LeatherCreaserMaker.dayTimer = 0
function LeatherCreaserMaker.init() LeatherCreaserMaker.ironStock=14; LeatherCreaserMaker.bronzeStock=12; LeatherCreaserMaker.woodStock=12; LeatherCreaserMaker.leatherStock=12; LeatherCreaserMaker.silverStock=8; LeatherCreaserMaker.goldStock=6; LeatherCreaserMaker.jewelStock=4; LeatherCreaserMaker.pearlStock=4; LeatherCreaserMaker.productStock={}; LeatherCreaserMaker.buildings={}; LeatherCreaserMaker.maker=nil; LeatherCreaserMaker.activeMaking={}; LeatherCreaserMaker.totalProducts=0; LeatherCreaserMaker.dayTimer=0; print("[LeatherCreaserMaker] Royal Leather Creaser Maker System initialized (6 products, 4 buildings)") end
function LeatherCreaserMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; LeatherCreaserMaker.maker={name=n or ("Gubalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gubalec najet: %s (spretnost: %d)",LeatherCreaserMaker.maker.name,s),"success") end; return true end
function LeatherCreaserMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function LeatherCreaserMaker.build(id) local ok,e=LeatherCreaserMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(LeatherCreaserMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function LeatherCreaserMaker.getQualityBonus() local b=0; for _,bd in ipairs(LeatherCreaserMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function LeatherCreaserMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and LeatherCreaserMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and LeatherCreaserMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and LeatherCreaserMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and LeatherCreaserMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and LeatherCreaserMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and LeatherCreaserMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and LeatherCreaserMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and LeatherCreaserMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #LeatherCreaserMaker.buildings==0 then return false,"Potrebna gubalna delavnica" end; if not LeatherCreaserMaker.maker then return false,"Potreben gubalec" end; return true end
function LeatherCreaserMaker.make(pt,qty) qty=qty or 1; local ok,e=LeatherCreaserMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then LeatherCreaserMaker.ironStock=LeatherCreaserMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then LeatherCreaserMaker.bronzeStock=LeatherCreaserMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then LeatherCreaserMaker.woodStock=LeatherCreaserMaker.woodStock-d.woodCost*qty end; if d.leatherCost then LeatherCreaserMaker.leatherStock=LeatherCreaserMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then LeatherCreaserMaker.silverStock=LeatherCreaserMaker.silverStock-d.silverCost*qty end; if d.goldCost then LeatherCreaserMaker.goldStock=LeatherCreaserMaker.goldStock-d.goldCost*qty end; if d.jewelCost then LeatherCreaserMaker.jewelStock=LeatherCreaserMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then LeatherCreaserMaker.pearlStock=LeatherCreaserMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if LeatherCreaserMaker.maker then t=math.max(1,t-math.floor(LeatherCreaserMaker.maker.skill/13)) end; table.insert(LeatherCreaserMaker.activeMaking,{id="${MAKER_LOWER}_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function LeatherCreaserMaker.completeMaking(m) local q=1.0+(LeatherCreaserMaker.getQualityBonus()/100); if LeatherCreaserMaker.maker then q=q+(LeatherCreaserMaker.maker.skill/140) end; q=math.min(2.5,q); LeatherCreaserMaker.productStock[m.productType]=(LeatherCreaserMaker.productStock[m.productType] or 0)+m.quantity; LeatherCreaserMaker.totalProducts=LeatherCreaserMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if LeatherCreaserMaker.maker then LeatherCreaserMaker.maker.itemsMade=LeatherCreaserMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then LeatherCreaserMaker.maker.skill=math.min(100,LeatherCreaserMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gubalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"${MAKER_LOWER}.completed",{productName=m.productName,prestige=m.prestige,happiness:m.happiness}) end end
function LeatherCreaserMaker.update(dt) if not _G.state then return end; LeatherCreaserMaker.dayTimer=LeatherCreaserMaker.dayTimer+dt; if LeatherCreaserMaker.dayTimer>=30 then LeatherCreaserMaker.dayTimer=0; for i=#LeatherCreaserMaker.activeMaking,1,-1 do local m=LeatherCreaserMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then LeatherCreaserMaker.completeMaking(m); table.remove(LeatherCreaserMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(LeatherCreaserMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if LeatherCreaserMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function LeatherCreaserMaker.getStats() return {ironStock=LeatherCreaserMaker.ironStock,bronzeStock=LeatherCreaserMaker.bronzeStock,woodStock=LeatherCreaserMaker.woodStock,leatherStock=LeatherCreaserMaker.leatherStock,silverStock=LeatherCreaserMaker.silverStock,goldStock=LeatherCreaserMaker.goldStock,jewelStock=LeatherCreaserMaker.jewelStock,pearlStock=LeatherCreaserMaker.pearlStock,productStock=LeatherCreaserMaker.productStock,numBuildings=#LeatherCreaserMaker.buildings,hasMaker=LeatherCreaserMaker.maker~=nil,makerName=LeatherCreaserMaker.maker and LeatherCreaserMaker.maker.name or "—",makerSkill=LeatherCreaserMaker.maker and LeatherCreaserMaker.maker.skill or 0,activeMaking=#LeatherCreaserMaker.activeMaking,totalProducts=LeatherCreaserMaker.totalProducts} end
return LeatherCreaserMaker
