local BookEndbandLoomMaker = {}
local PRODUCTS = {
    iron_bookendbandloom = { name = "Železni statvi za kapice knjig", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni statvi za kapice knjig za knjigoveze." },
    bronze_bookendbandloom = { name = "Bronast statvi za kapice knjig", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast statvi za kapice knjig za knjigoveze." },
    silver_bookendbandloom = { name = "Srebrn statvi za kapice knjig", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn statvi za kapice knjig za knjigoveze." },
    gilded_bookendbandloom = { name = "Pozlačen statvi za kapice knjig", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen statvi za kapice knjig za knjigoveze." },
    jewel_set_bookendbandloom = { name = "Draguljast statvi za kapice knjig", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast statvi za kapice knjig za knjigoveze." },
    royal_sovereign_bookendbandloom = { name = "Kraljevski suveren statvi za kapice knjig", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren statvi za kapice knjig z biseri za krono." },
}
local BUILDINGS = {
    bookendbandloom_workshop = { name = "Bookendbandloom delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookendbandloom_house = { name = "Bookendbandloom hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookendbandloom_atelier = { name = "Mojstrski bookendbandloom atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookendbandloom_palace = { name = "Suverena bookendbandloom palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookEndbandLoomMaker.ironStock=12; BookEndbandLoomMaker.bronzeStock=10; BookEndbandLoomMaker.woodStock=16; BookEndbandLoomMaker.leatherStock=10; BookEndbandLoomMaker.silverStock=8; BookEndbandLoomMaker.goldStock=6; BookEndbandLoomMaker.jewelStock=4; BookEndbandLoomMaker.pearlStock=4
BookEndbandLoomMaker.productStock = {}; BookEndbandLoomMaker.buildings = {}; BookEndbandLoomMaker.maker = nil; BookEndbandLoomMaker.activeMaking = {}; BookEndbandLoomMaker.totalProducts = 0; BookEndbandLoomMaker.dayTimer = 0
function BookEndbandLoomMaker.init() BookEndbandLoomMaker.ironStock=12; BookEndbandLoomMaker.bronzeStock=10; BookEndbandLoomMaker.woodStock=16; BookEndbandLoomMaker.leatherStock=10; BookEndbandLoomMaker.silverStock=8; BookEndbandLoomMaker.goldStock=6; BookEndbandLoomMaker.jewelStock=4; BookEndbandLoomMaker.pearlStock=4; BookEndbandLoomMaker.productStock={}; BookEndbandLoomMaker.buildings={}; BookEndbandLoomMaker.maker=nil; BookEndbandLoomMaker.activeMaking={}; BookEndbandLoomMaker.totalProducts=0; BookEndbandLoomMaker.dayTimer=0; print("[BookEndbandLoomMaker] Royal Book Endband Loom Maker System initialized (6 products, 4 buildings)") end
function BookEndbandLoomMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookEndbandLoomMaker.maker={name=n or ("Statvar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Statvar najet: %s (spretnost: %d)",BookEndbandLoomMaker.maker.name,s),"success") end; return true end
function BookEndbandLoomMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookEndbandLoomMaker.build(id) local ok,e=BookEndbandLoomMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookEndbandLoomMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookEndbandLoomMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookEndbandLoomMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookEndbandLoomMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookEndbandLoomMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookEndbandLoomMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookEndbandLoomMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookEndbandLoomMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookEndbandLoomMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookEndbandLoomMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookEndbandLoomMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookEndbandLoomMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookEndbandLoomMaker.buildings==0 then return false,"Potrebna statvena delavnica" end; if not BookEndbandLoomMaker.maker then return false,"Potreben statvar" end; return true end
function BookEndbandLoomMaker.make(pt,qty) qty=qty or 1; local ok,e=BookEndbandLoomMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookEndbandLoomMaker.ironStock=BookEndbandLoomMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookEndbandLoomMaker.bronzeStock=BookEndbandLoomMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookEndbandLoomMaker.woodStock=BookEndbandLoomMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookEndbandLoomMaker.leatherStock=BookEndbandLoomMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookEndbandLoomMaker.silverStock=BookEndbandLoomMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookEndbandLoomMaker.goldStock=BookEndbandLoomMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookEndbandLoomMaker.jewelStock=BookEndbandLoomMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookEndbandLoomMaker.pearlStock=BookEndbandLoomMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookEndbandLoomMaker.maker then t=math.max(1,t-math.floor(BookEndbandLoomMaker.maker.skill/13)) end; table.insert(BookEndbandLoomMaker.activeMaking,{id="bookendbandloom_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookEndbandLoomMaker.completeMaking(m) local q=1.0+(BookEndbandLoomMaker.getQualityBonus()/100); if BookEndbandLoomMaker.maker then q=q+(BookEndbandLoomMaker.maker.skill/140) end; q=math.min(2.5,q); BookEndbandLoomMaker.productStock[m.productType]=(BookEndbandLoomMaker.productStock[m.productType] or 0)+m.quantity; BookEndbandLoomMaker.totalProducts=BookEndbandLoomMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookEndbandLoomMaker.maker then BookEndbandLoomMaker.maker.itemsMade=BookEndbandLoomMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookEndbandLoomMaker.maker.skill=math.min(100,BookEndbandLoomMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Stati izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookendbandloom.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookEndbandLoomMaker.update(dt) if not _G.state then return end; BookEndbandLoomMaker.dayTimer=BookEndbandLoomMaker.dayTimer+dt; if BookEndbandLoomMaker.dayTimer>=30 then BookEndbandLoomMaker.dayTimer=0; for i=#BookEndbandLoomMaker.activeMaking,1,-1 do local m=BookEndbandLoomMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookEndbandLoomMaker.completeMaking(m); table.remove(BookEndbandLoomMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookEndbandLoomMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookEndbandLoomMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookEndbandLoomMaker.getStats() return {ironStock=BookEndbandLoomMaker.ironStock,bronzeStock=BookEndbandLoomMaker.bronzeStock,woodStock=BookEndbandLoomMaker.woodStock,leatherStock=BookEndbandLoomMaker.leatherStock,silverStock=BookEndbandLoomMaker.silverStock,goldStock=BookEndbandLoomMaker.goldStock,jewelStock=BookEndbandLoomMaker.jewelStock,pearlStock=BookEndbandLoomMaker.pearlStock,productStock=BookEndbandLoomMaker.productStock,numBuildings=#BookEndbandLoomMaker.buildings,hasMaker=BookEndbandLoomMaker.maker~=nil,makerName=BookEndbandLoomMaker.maker and BookEndbandLoomMaker.maker.name or "—",makerSkill=BookEndbandLoomMaker.maker and BookEndbandLoomMaker.maker.skill or 0,activeMaking=#BookEndbandLoomMaker.activeMaking,totalProducts=BookEndbandLoomMaker.totalProducts} end
return BookEndbandLoomMaker
