local BeakerBlower = {}
local PRODUCTS = {
    simple_glass_beaker = { name = "Preprost steklen lonček", glassCost = 2, time = 3, cost = 35, science = 18, happiness = 1, description = "Preprost steklen lonček za laboratorij." },
    graduated_beaker = { name = "Merilni steklen lonček", glassCost = 2, paintCost = 1, time = 5, cost = 100, science = 32, happiness = 1, prestige = 2, description = "Merilni steklen lonček za trgovce." },
    silver_rim_beaker = { name = "Srebrnookrasni lonček", glassCost = 3, silverCost = 1, paintCost = 1, time = 8, cost = 260, science = 48, happiness = 2, prestige = 6, description = "Srebrnookrasni lonček za plemiče." },
    gold_trimmed_beaker = { name = "Zlatookrasni lonček", glassCost = 3, goldCost = 1, silverCost = 1, paintCost = 1, time = 12, cost = 620, science = 62, happiness = 3, prestige = 14, description = "Zlatookrasni lonček za visoke plemiče." },
    jewel_set_beaker = { name = "Draguljasta lonček", glassCost = 4, goldCost = 1, silverCost = 1, paintCost = 1, jewelCost = 1, time = 16, cost = 1400, science = 78, happiness = 5, prestige = 27, description = "Lonček z draguljem za visoko plemstvo." },
    royal_grand_beaker_set = { name = "Kraljevski veliki set lončkov", glassCost = 6, goldCost = 2, silverCost = 2, paintCost = 2, jewelCost = 2, pearlCost = 2, time = 23, cost = 3200, science = 92, happiness = 12, prestige = 56, description = "Veliki kraljevski set lončkov z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    beaker_workshop = { name = "Lončkarska delavnica", cost = { gold = 220, wood = 100, stone = 120, glass = 6 }, upkeep = 5, qualityBonus = 5 },
    blowing_loft = { name = "Pihalna podstrešje", cost = { gold = 800, wood = 240, stone = 240, silver = 6, paint = 6 }, upkeep = 18, qualityBonus = 18 },
    master_glassblower_atelier = { name = "Mojstrski steklopihalski atelje", cost = { gold = 2300, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 52, qualityBonus = 30 },
    royal_beaker_palace = { name = "Kraljevska lončkarska palača", cost = { gold = 9500, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 50 },
}
BeakerBlower.glassStock = 18; BeakerBlower.paintStock = 10; BeakerBlower.silverStock = 6; BeakerBlower.goldStock = 6; BeakerBlower.jewelStock = 4; BeakerBlower.pearlStock = 4
BeakerBlower.productStock = {}; BeakerBlower.buildings = {}; BeakerBlower.maker = nil; BeakerBlower.activeMaking = {}; BeakerBlower.totalProducts = 0; BeakerBlower.dayTimer = 0
function BeakerBlower.init() BeakerBlower.glassStock=18; BeakerBlower.paintStock=10; BeakerBlower.silverStock=6; BeakerBlower.goldStock=6; BeakerBlower.jewelStock=4; BeakerBlower.pearlStock=4; BeakerBlower.productStock={}; BeakerBlower.buildings={}; BeakerBlower.maker=nil; BeakerBlower.activeMaking={}; BeakerBlower.totalProducts=0; BeakerBlower.dayTimer=0; print("[BeakerBlower] Royal Beaker Blower System initialized (6 products, 4 buildings)") end
function BeakerBlower.hireMaker(n,s) s=s or math.random(55,90); local c=480+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BeakerBlower.maker={name=n or ("Lončkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lončkar najet: %s (spretnost: %d)",BeakerBlower.maker.name,s),"success") end; return true end
function BeakerBlower.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BeakerBlower.build(id) local ok,e=BeakerBlower.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BeakerBlower.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BeakerBlower.getQualityBonus() local b=0; for _,bd in ipairs(BeakerBlower.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BeakerBlower.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.glassCost and BeakerBlower.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.paintCost and BeakerBlower.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.silverCost and BeakerBlower.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BeakerBlower.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BeakerBlower.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BeakerBlower.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BeakerBlower.buildings==0 then return false,"Potrebna lončkarska delavnica" end; if not BeakerBlower.maker then return false,"Potreben lončkar" end; return true end
function BeakerBlower.make(pt,qty) qty=qty or 1; local ok,e=BeakerBlower.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.glassCost then BeakerBlower.glassStock=BeakerBlower.glassStock-d.glassCost*qty end; if d.paintCost then BeakerBlower.paintStock=BeakerBlower.paintStock-d.paintCost*qty end; if d.silverCost then BeakerBlower.silverStock=BeakerBlower.silverStock-d.silverCost*qty end; if d.goldCost then BeakerBlower.goldStock=BeakerBlower.goldStock-d.goldCost*qty end; if d.jewelCost then BeakerBlower.jewelStock=BeakerBlower.jewelStock-d.jewelCost*qty end; if d.pearlCost then BeakerBlower.pearlStock=BeakerBlower.pearlStock-d.pearlCost*qty end; local t=d.time; if BeakerBlower.maker then t=math.max(1,t-math.floor(BeakerBlower.maker.skill/13)) end; table.insert(BeakerBlower.activeMaking,{id="beaker_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,science=d.science or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pihanje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BeakerBlower.completeMaking(m) local q=1.0+(BeakerBlower.getQualityBonus()/100); if BeakerBlower.maker then q=q+(BeakerBlower.maker.skill/150) end; q=math.min(2.4,q); BeakerBlower.productStock[m.productType]=(BeakerBlower.productStock[m.productType] or 0)+m.quantity; BeakerBlower.totalProducts=BeakerBlower.totalProducts+m.quantity; if m.science>0 and _G.state then _G.state.science=(_G.state.science or 0)+m.science end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BeakerBlower.maker then BeakerBlower.maker.itemsMade=BeakerBlower.maker.itemsMade+m.quantity; if math.random()<0.25 then BeakerBlower.maker.skill=math.min(100,BeakerBlower.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Lonček izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"beaker.completed",{productName=m.productName,science=m.science,prestige=m.prestige,happiness=m.happiness}) end end
function BeakerBlower.update(dt) if not _G.state then return end; BeakerBlower.dayTimer=BeakerBlower.dayTimer+dt; if BeakerBlower.dayTimer>=30 then BeakerBlower.dayTimer=0; for i=#BeakerBlower.activeMaking,1,-1 do local m=BeakerBlower.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BeakerBlower.completeMaking(m); table.remove(BeakerBlower.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BeakerBlower.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BeakerBlower.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BeakerBlower.getStats() return {glassStock=BeakerBlower.glassStock,paintStock=BeakerBlower.paintStock,silverStock=BeakerBlower.silverStock,goldStock=BeakerBlower.goldStock,jewelStock=BeakerBlower.jewelStock,pearlStock=BeakerBlower.pearlStock,productStock=BeakerBlower.productStock,numBuildings=#BeakerBlower.buildings,hasMaker=BeakerBlower.maker~=nil,makerName=BeakerBlower.maker and BeakerBlower.maker.name or "—",makerSkill=BeakerBlower.maker and BeakerBlower.maker.skill or 0,activeMaking=#BeakerBlower.activeMaking,totalProducts=BeakerBlower.totalProducts} end
return BeakerBlower
