local CalendarMaker = {}
local PRODUCTS = {
    simple_wooden_calendar = { name = "Preprost lesen koledar", woodCost = 2, time = 3, cost = 35, happiness = 1, description = "Preprost leseni koledar za hišo." },
    painted_parchment_calendar = { name = "Poslikani pergamentni koledar", woodCost = 1, parchmentCost = 2, paintCost = 1, time = 5, cost = 90, happiness = 1, prestige = 1, description = "Poslikani pergamentni koledar za trgovce." },
    illuminated_vellum_calendar = { name = "Iluminirani velumski koledar", woodCost = 1, parchmentCost = 3, paintCost = 2, goldCost = 1, time = 8, cost = 240, happiness = 2, prestige = 5, description = "Iluminirani velumski koledar za plemiče." },
    silver_trimmed_calendar = { name = "Srebrno obrobljeni koledar", woodCost = 2, parchmentCost = 3, paintCost = 2, silverCost = 1, goldCost = 1, time = 12, cost = 580, happiness = 3, prestige = 13, description = "Srebrno obrobljeni koledar za visoke plemiče." },
    gold_embossed_calendar = { name = "Zlato izbočeni koledar", woodCost = 2, parchmentCost = 4, paintCost = 2, goldCost = 2, silverCost = 1, jewelCost = 1, time = 16, cost = 1300, happiness = 5, prestige = 25, description = "Zlato izbočeni koledar z draguljem za visoko plemstvo." },
    royal_astronomy_calendar = { name = "Kraljevski astronomski koledar", woodCost = 3, parchmentCost = 5, paintCost = 3, goldCost = 3, silverCost = 2, jewelCost = 2, pearlCost = 1, time = 23, cost = 3300, happiness = 11, prestige = 58, description = "Veliki kraljevski astronomski koledar z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    calendar_workshop = { name = "Koledarska delavnica", cost = { gold = 200, wood = 100, stone = 80, parchment = 6 }, upkeep = 5, qualityBonus = 5 },
    scriptorium_loft = { name = "Skriptorijska podstrešje", cost = { gold = 780, wood = 220, stone = 220, paint = 6, parchment = 10 }, upkeep = 18, qualityBonus = 18 },
    astronomical_atelier = { name = "Astronomski atelje", cost = { gold = 2200, wood = 340, stone = 480, silver = 28, gold = 6 }, upkeep = 50, qualityBonus = 30 },
    royal_calendar_palace = { name = "Kraljevska koledarska palača", cost = { gold = 9200, wood = 580, stone = 720, gold = 55, jewel = 14 }, upkeep = 185, qualityBonus = 55, prestigeBonus = 50 },
}
CalendarMaker.woodStock = 14; CalendarMaker.parchmentStock = 14; CalendarMaker.paintStock = 12; CalendarMaker.silverStock = 6; CalendarMaker.goldStock = 6; CalendarMaker.jewelStock = 4; CalendarMaker.pearlStock = 4
CalendarMaker.productStock = {}; CalendarMaker.buildings = {}; CalendarMaker.maker = nil; CalendarMaker.activeMaking = {}; CalendarMaker.totalProducts = 0; CalendarMaker.dayTimer = 0
function CalendarMaker.init() CalendarMaker.woodStock=14; CalendarMaker.parchmentStock=14; CalendarMaker.paintStock=12; CalendarMaker.silverStock=6; CalendarMaker.goldStock=6; CalendarMaker.jewelStock=4; CalendarMaker.pearlStock=4; CalendarMaker.productStock={}; CalendarMaker.buildings={}; CalendarMaker.maker=nil; CalendarMaker.activeMaking={}; CalendarMaker.totalProducts=0; CalendarMaker.dayTimer=0; print("[CalendarMaker] Royal Calendar Maker System initialized (6 products, 4 buildings)") end
function CalendarMaker.hireMaker(n,s) s=s or math.random(55,90); local c=480+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CalendarMaker.maker={name=n or ("Koledar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Koledarjar najet: %s (spretnost: %d)",CalendarMaker.maker.name,s),"success") end; return true end
function CalendarMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CalendarMaker.build(id) local ok,e=CalendarMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CalendarMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CalendarMaker.getQualityBonus() local b=0; for _,bd in ipairs(CalendarMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CalendarMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and CalendarMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.parchmentCost and CalendarMaker.parchmentStock<(d.parchmentCost or 0) then return false,"Premalo pergamenta" end; if d.paintCost and CalendarMaker.paintStock<(d.paintCost or 0) then return false,"Premalo barve" end; if d.silverCost and CalendarMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CalendarMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CalendarMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CalendarMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CalendarMaker.buildings==0 then return false,"Potrebna koledarska delavnica" end; if not CalendarMaker.maker then return false,"Potreben koledarjar" end; return true end
function CalendarMaker.make(pt,qty) qty=qty or 1; local ok,e=CalendarMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then CalendarMaker.woodStock=CalendarMaker.woodStock-d.woodCost*qty end; if d.parchmentCost then CalendarMaker.parchmentStock=CalendarMaker.parchmentStock-d.parchmentCost*qty end; if d.paintCost then CalendarMaker.paintStock=CalendarMaker.paintStock-d.paintCost*qty end; if d.silverCost then CalendarMaker.silverStock=CalendarMaker.silverStock-d.silverCost*qty end; if d.goldCost then CalendarMaker.goldStock=CalendarMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CalendarMaker.jewelStock=CalendarMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CalendarMaker.pearlStock=CalendarMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CalendarMaker.maker then t=math.max(1,t-math.floor(CalendarMaker.maker.skill/13)) end; table.insert(CalendarMaker.activeMaking,{id="calendar_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CalendarMaker.completeMaking(m) local q=1.0+(CalendarMaker.getQualityBonus()/100); if CalendarMaker.maker then q=q+(CalendarMaker.maker.skill/150) end; q=math.min(2.4,q); CalendarMaker.productStock[m.productType]=(CalendarMaker.productStock[m.productType] or 0)+m.quantity; CalendarMaker.totalProducts=CalendarMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CalendarMaker.maker then CalendarMaker.maker.itemsMade=CalendarMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CalendarMaker.maker.skill=math.min(100,CalendarMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Koledar izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"calendar.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CalendarMaker.update(dt) if not _G.state then return end; CalendarMaker.dayTimer=CalendarMaker.dayTimer+dt; if CalendarMaker.dayTimer>=30 then CalendarMaker.dayTimer=0; for i=#CalendarMaker.activeMaking,1,-1 do local m=CalendarMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CalendarMaker.completeMaking(m); table.remove(CalendarMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CalendarMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CalendarMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CalendarMaker.getStats() return {woodStock=CalendarMaker.woodStock,parchmentStock=CalendarMaker.parchmentStock,paintStock=CalendarMaker.paintStock,silverStock=CalendarMaker.silverStock,goldStock=CalendarMaker.goldStock,jewelStock=CalendarMaker.jewelStock,pearlStock=CalendarMaker.pearlStock,productStock=CalendarMaker.productStock,numBuildings=#CalendarMaker.buildings,hasMaker=CalendarMaker.maker~=nil,makerName=CalendarMaker.maker and CalendarMaker.maker.name or "—",makerSkill=CalendarMaker.maker and CalendarMaker.maker.skill or 0,activeMaking=#CalendarMaker.activeMaking,totalProducts=CalendarMaker.totalProducts} end
return CalendarMaker
