local RecurveBowMaker = {}
local PRODUCTS = {
    simple_wood_recurve = { name = "Preprost povratni lok", woodCost = 3, hornCost = 1, ropeCost = 1, time = 5, cost = 90, attack = 30, happiness = 1, description = "Preprost povratni lok za konjenike." },
    sinew_backed_recurve = { name = "Kitemovpovratni lok", woodCost = 3, hornCost = 1, leatherCost = 1, ropeCost = 1, time = 8, cost = 240, attack = 45, happiness = 2, prestige = 2, description = "Kitemovpovratni lok za trgovce." },
    silver_tipped_recurve = { name = "Srebrnokončni povratni lok", woodCost = 3, silverCost = 1, hornCost = 1, leatherCost = 1, ropeCost = 1, time = 11, cost = 580, attack = 60, happiness = 2, prestige = 6, description = "Srebrnokončni povratni lok za plemiče." },
    gold_inlaid_recurve = { name = "Zlatovloženi povratni lok", woodCost = 3, goldCost = 1, silverCost = 1, hornCost = 1, leatherCost = 1, ropeCost = 1, time = 15, cost = 1400, attack = 72, happiness = 3, prestige = 14, description = "Zlatovloženi povratni lok za visoke plemiče." },
    jewel_grip_recurve = { name = "Draguljnoročajni povratni lok", woodCost = 3, goldCost = 1, silverCost = 1, hornCost = 1, leatherCost = 1, ropeCost = 1, jewelCost = 1, time = 19, cost = 3000, attack = 84, happiness = 5, prestige = 27, description = "Povratni lok z draguljnim ročajem za visoko plemstvo." },
    royal_grand_recurve = { name = "Kraljevski veliki povratni lok", woodCost = 5, goldCost = 2, silverCost = 2, hornCost = 1, leatherCost = 1, ropeCost = 1, jewelCost = 2, pearlCost = 2, time = 26, cost = 6800, attack = 95, happiness = 12, prestige = 58, description = "Veliki kraljevski povratni lok z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    recurve_workshop = { name = "Povratna delavnica", cost = { gold = 280, wood = 160, stone = 100, rope = 6, horn = 4 }, upkeep = 6, qualityBonus = 5 },
    composite_loft = { name = "Kompozitna podstrešje", cost = { gold = 1000, wood = 320, stone = 240, silver = 6, leather = 6 }, upkeep = 23, qualityBonus = 18 },
    master_composite_atelier = { name = "Mojstrski kompozitni atelje", cost = { gold = 2800, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 65, qualityBonus = 30 },
    royal_recurve_palace = { name = "Kraljevska povratna palača", cost = { gold = 11800, wood = 600, stone = 800, gold = 75, jewel = 18 }, upkeep = 235, qualityBonus = 55, prestigeBonus = 50 },
}
RecurveBowMaker.woodStock = 18; RecurveBowMaker.hornStock = 10; RecurveBowMaker.ropeStock = 12; RecurveBowMaker.leatherStock = 10; RecurveBowMaker.silverStock = 6; RecurveBowMaker.goldStock = 6; RecurveBowMaker.jewelStock = 4; RecurveBowMaker.pearlStock = 4
RecurveBowMaker.productStock = {}; RecurveBowMaker.buildings = {}; RecurveBowMaker.maker = nil; RecurveBowMaker.activeMaking = {}; RecurveBowMaker.totalProducts = 0; RecurveBowMaker.dayTimer = 0
function RecurveBowMaker.init() RecurveBowMaker.woodStock=18; RecurveBowMaker.hornStock=10; RecurveBowMaker.ropeStock=12; RecurveBowMaker.leatherStock=10; RecurveBowMaker.silverStock=6; RecurveBowMaker.goldStock=6; RecurveBowMaker.jewelStock=4; RecurveBowMaker.pearlStock=4; RecurveBowMaker.productStock={}; RecurveBowMaker.buildings={}; RecurveBowMaker.maker=nil; RecurveBowMaker.activeMaking={}; RecurveBowMaker.totalProducts=0; RecurveBowMaker.dayTimer=0; print("[RecurveBowMaker] Royal Recurve Bow Maker System initialized (6 products, 4 buildings)") end
function RecurveBowMaker.hireMaker(n,s) s=s or math.random(55,90); local c=540+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; RecurveBowMaker.maker={name=n or ("Povratnar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Povratnar najet: %s (spretnost: %d)",RecurveBowMaker.maker.name,s),"success") end; return true end
function RecurveBowMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function RecurveBowMaker.build(id) local ok,e=RecurveBowMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(RecurveBowMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function RecurveBowMaker.getQualityBonus() local b=0; for _,bd in ipairs(RecurveBowMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function RecurveBowMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and RecurveBowMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.hornCost and RecurveBowMaker.hornStock<(d.hornCost or 0) then return false,"Premalo rogovja" end; if d.ropeCost and RecurveBowMaker.ropeStock<(d.ropeCost or 0) then return false,"Premalo vrvi" end; if d.leatherCost and RecurveBowMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and RecurveBowMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and RecurveBowMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and RecurveBowMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and RecurveBowMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #RecurveBowMaker.buildings==0 then return false,"Potrebna povratna delavnica" end; if not RecurveBowMaker.maker then return false,"Potreben povratnar" end; return true end
function RecurveBowMaker.make(pt,qty) qty=qty or 1; local ok,e=RecurveBowMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then RecurveBowMaker.woodStock=RecurveBowMaker.woodStock-d.woodCost*qty end; if d.hornCost then RecurveBowMaker.hornStock=RecurveBowMaker.hornStock-d.hornCost*qty end; if d.ropeCost then RecurveBowMaker.ropeStock=RecurveBowMaker.ropeStock-d.ropeCost*qty end; if d.leatherCost then RecurveBowMaker.leatherStock=RecurveBowMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then RecurveBowMaker.silverStock=RecurveBowMaker.silverStock-d.silverCost*qty end; if d.goldCost then RecurveBowMaker.goldStock=RecurveBowMaker.goldStock-d.goldCost*qty end; if d.jewelCost then RecurveBowMaker.jewelStock=RecurveBowMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then RecurveBowMaker.pearlStock=RecurveBowMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if RecurveBowMaker.maker then t=math.max(1,t-math.floor(RecurveBowMaker.maker.skill/12)) end; table.insert(RecurveBowMaker.activeMaking,{id="recurve_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,attack=d.attack or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function RecurveBowMaker.completeMaking(m) local q=1.0+(RecurveBowMaker.getQualityBonus()/100); if RecurveBowMaker.maker then q=q+(RecurveBowMaker.maker.skill/140) end; q=math.min(2.5,q); RecurveBowMaker.productStock[m.productType]=(RecurveBowMaker.productStock[m.productType] or 0)+m.quantity; RecurveBowMaker.totalProducts=RecurveBowMaker.totalProducts+m.quantity; if m.attack>0 and _G.state then _G.state.attack=(_G.state.attack or 0)+m.attack end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if RecurveBowMaker.maker then RecurveBowMaker.maker.itemsMade=RecurveBowMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then RecurveBowMaker.maker.skill=math.min(100,RecurveBowMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Povratni lok izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"recurve.completed",{productName=m.productName,attack=m.attack,prestige=m.prestige,happiness=m.happiness}) end end
function RecurveBowMaker.update(dt) if not _G.state then return end; RecurveBowMaker.dayTimer=RecurveBowMaker.dayTimer+dt; if RecurveBowMaker.dayTimer>=30 then RecurveBowMaker.dayTimer=0; for i=#RecurveBowMaker.activeMaking,1,-1 do local m=RecurveBowMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then RecurveBowMaker.completeMaking(m); table.remove(RecurveBowMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(RecurveBowMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if RecurveBowMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function RecurveBowMaker.getStats() return {woodStock=RecurveBowMaker.woodStock,hornStock=RecurveBowMaker.hornStock,ropeStock=RecurveBowMaker.ropeStock,leatherStock=RecurveBowMaker.leatherStock,silverStock=RecurveBowMaker.silverStock,goldStock=RecurveBowMaker.goldStock,jewelStock=RecurveBowMaker.jewelStock,pearlStock=RecurveBowMaker.pearlStock,productStock=RecurveBowMaker.productStock,numBuildings=#RecurveBowMaker.buildings,hasMaker=RecurveBowMaker.maker~=nil,makerName=RecurveBowMaker.maker and RecurveBowMaker.maker.name or "—",makerSkill=RecurveBowMaker.maker and RecurveBowMaker.maker.skill or 0,activeMaking=#RecurveBowMaker.activeMaking,totalProducts=RecurveBowMaker.totalProducts} end
return RecurveBowMaker
