local VestibuleLightMaker = {}
local PRODUCTS = {
    simple_brass_vestibule_light = { name = "Preprosta medeninasta vhodna luč", brassCost = 2, glassCost = 1, waxCost = 1, time = 4, cost = 80, lightRadius = 30, happiness = 1, description = "Preprosta medeninasta vhodna luč za vhode." }
    , iron_reinforced_vestibule = { name = "Železnookrepljena vhodna luč", brassCost = 2, ironCost = 1, glassCost = 1, waxCost = 1, time = 6, cost = 220, lightRadius = 42, happiness = 1, prestige = 2, description = "Železnookrepljena vhodna luč za trgovce." },
    silver_trimmed_vestibule = { name = "Srebrnoobrobljena vhodna luč", silverCost = 1, brassCost = 2, ironCost = 1, glassCost = 1, waxCost = 1, time = 9, cost = 540, lightRadius = 55, happiness = 2, prestige = 6, description = "Srebrnoobrobljena vhodna luč za plemiče." },
    gold_trimmed_vestibule = { name = "Zlatookrasna vhodna luč", goldCost = 1, silverCost = 1, brassCost = 2, ironCost = 1, glassCost = 1, waxCost = 1, time = 13, cost = 1300, lightRadius = 68, happiness = 3, prestige = 14, description = "Zlatookrasna vhodna luč za visoke plemiče." },
    jewel_set_vestibule = { name = "Draguljasta vhodna luč", goldCost = 1, silverCost = 1, brassCost = 2, ironCost = 1, glassCost = 1, waxCost = 1, jewelCost = 1, time = 17, cost = 2900, lightRadius = 82, happiness = 5, prestige = 27, description = "Vhodna luč z draguljem za visoko plemstvo." },
    royal_grand_vestibule = { name = "Kraljevski veliki vhodna luč", goldCost = 2, silverCost = 2, brassCost = 2, ironCost = 1, glassCost = 1, waxCost = 1, jewelCost = 2, pearlCost = 2, time = 24, cost = 6200, lightRadius = 100, happiness = 12, prestige = 58, description = "Velika kraljevska vhodna luč z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    vestibule_workshop = { name = "Vhodna lučna delavnica", cost = { gold = 260, wood = 100, stone = 120, brass = 6, glass = 6 }, upkeep = 6, qualityBonus = 5 },
    lighting_loft = { name = "Razsvetljena podstrešje", cost = { gold = 950, wood = 240, stone = 240, silver = 6, iron = 6 }, upkeep = 22, qualityBonus = 18 },
    master_vestibule_atelier = { name = "Mojstrski vhodni lučni atelje", cost = { gold = 2700, wood = 360, stone = 520, silver = 32, gold = 6 }, upkeep = 62, qualityBonus = 30 },
    royal_lighting_palace = { name = "Kraljevska razsvetljenska palača", cost = { gold = 11500, wood = 580, stone = 760, gold = 75, jewel = 18 }, upkeep = 230, qualityBonus = 55, prestigeBonus = 50 },
}
VestibuleLightMaker.brassStock = 14; VestibuleLightMaker.glassStock = 12; VestibuleLightMaker.waxStock = 10; VestibuleLightMaker.ironStock = 10; VestibuleLightMaker.silverStock = 6; VestibuleLightMaker.goldStock = 6; VestibuleLightMaker.jewelStock = 4; VestibuleLightMaker.pearlStock = 4
VestibuleLightMaker.productStock = {}; VestibuleLightMaker.buildings = {}; VestibuleLightMaker.maker = nil; VestibuleLightMaker.activeMaking = {}; VestibuleLightMaker.totalProducts = 0; VestibuleLightMaker.dayTimer = 0
function VestibuleLightMaker.init() VestibuleLightMaker.brassStock=14; VestibuleLightMaker.glassStock=12; VestibuleLightMaker.waxStock=10; VestibuleLightMaker.ironStock=10; VestibuleLightMaker.silverStock=6; VestibuleLightMaker.goldStock=6; VestibuleLightMaker.jewelStock=4; VestibuleLightMaker.pearlStock=4; VestibuleLightMaker.productStock={}; VestibuleLightMaker.buildings={}; VestibuleLightMaker.maker=nil; VestibuleLightMaker.activeMaking={}; VestibuleLightMaker.totalProducts=0; VestibuleLightMaker.dayTimer=0; print("[VestibuleLightMaker] Royal Vestibule Light Maker System initialized (6 products, 4 buildings)") end
function VestibuleLightMaker.hireMaker(n,s) s=s or math.random(55,90); local c=540+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; VestibuleLightMaker.maker={name=n or ("Vhodni lučar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vhodni lučar najet: %s (spretnost: %d)",VestibuleLightMaker.maker.name,s),"success") end; return true end
function VestibuleLightMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function VestibuleLightMaker.build(id) local ok,e=VestibuleLightMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(VestibuleLightMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function VestibuleLightMaker.getQualityBonus() local b=0; for _,bd in ipairs(VestibuleLightMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function VestibuleLightMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.brassCost and VestibuleLightMaker.brassStock<(d.brassCost or 0) then return false,"Premalo medenine" end; if d.glassCost and VestibuleLightMaker.glassStock<(d.glassCost or 0) then return false,"Premalo stekla" end; if d.waxCost and VestibuleLightMaker.waxStock<(d.waxCost or 0) then return false,"Premalo voska" end; if d.ironCost and VestibuleLightMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.silverCost and VestibuleLightMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and VestibuleLightMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and VestibuleLightMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and VestibuleLightMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #VestibuleLightMaker.buildings==0 then return false,"Potrebna vhodna lučna delavnica" end; if not VestibuleLightMaker.maker then return false,"Potreben vhodni lučar" end; return true end
function VestibuleLightMaker.make(pt,qty) qty=qty or 1; local ok,e=VestibuleLightMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.brassCost then VestibuleLightMaker.brassStock=VestibuleLightMaker.brassStock-d.brassCost*qty end; if d.glassCost then VestibuleLightMaker.glassStock=VestibuleLightMaker.glassStock-d.glassCost*qty end; if d.waxCost then VestibuleLightMaker.waxStock=VestibuleLightMaker.waxStock-d.waxCost*qty end; if d.ironCost then VestibuleLightMaker.ironStock=VestibuleLightMaker.ironStock-d.ironCost*qty end; if d.silverCost then VestibuleLightMaker.silverStock=VestibuleLightMaker.silverStock-d.silverCost*qty end; if d.goldCost then VestibuleLightMaker.goldStock=VestibuleLightMaker.goldStock-d.goldCost*qty end; if d.jewelCost then VestibuleLightMaker.jewelStock=VestibuleLightMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then VestibuleLightMaker.pearlStock=VestibuleLightMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if VestibuleLightMaker.maker then t=math.max(1,t-math.floor(VestibuleLightMaker.maker.skill/13)) end; table.insert(VestibuleLightMaker.activeMaking,{id="vestibule_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,lightRadius=d.lightRadius or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function VestibuleLightMaker.completeMaking(m) local q=1.0+(VestibuleLightMaker.getQualityBonus()/100); if VestibuleLightMaker.maker then q=q+(VestibuleLightMaker.maker.skill/140) end; q=math.min(2.5,q); VestibuleLightMaker.productStock[m.productType]=(VestibuleLightMaker.productStock[m.productType] or 0)+m.quantity; VestibuleLightMaker.totalProducts=VestibuleLightMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if VestibuleLightMaker.maker then VestibuleLightMaker.maker.itemsMade=VestibuleLightMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then VestibuleLightMaker.maker.skill=math.min(100,VestibuleLightMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vhodna luč izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"vestibule.completed",{productName=m.productName,lightRadius=m.lightRadius,prestige=m.prestige,happiness=m.happiness}) end end
function VestibuleLightMaker.update(dt) if not _G.state then return end; VestibuleLightMaker.dayTimer=VestibuleLightMaker.dayTimer+dt; if VestibuleLightMaker.dayTimer>=30 then VestibuleLightMaker.dayTimer=0; for i=#VestibuleLightMaker.activeMaking,1,-1 do local m=VestibuleLightMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then VestibuleLightMaker.completeMaking(m); table.remove(VestibuleLightMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(VestibuleLightMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if VestibuleLightMaker.maker then tu=tu+14 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function VestibuleLightMaker.getStats() return {brassStock=VestibuleLightMaker.brassStock,glassStock=VestibuleLightMaker.glassStock,waxStock=VestibuleLightMaker.waxStock,ironStock=VestibuleLightMaker.ironStock,silverStock=VestibuleLightMaker.silverStock,goldStock=VestibuleLightMaker.goldStock,jewelStock=VestibuleLightMaker.jewelStock,pearlStock=VestibuleLightMaker.pearlStock,productStock=VestibuleLightMaker.productStock,numBuildings=#VestibuleLightMaker.buildings,hasMaker=VestibuleLightMaker.maker~=nil,makerName=VestibuleLightMaker.maker and VestibuleLightMaker.maker.name or "—",makerSkill=VestibuleLightMaker.maker and VestibuleLightMaker.maker.skill or 0,activeMaking=#VestibuleLightMaker.activeMaking,totalProducts=VestibuleLightMaker.totalProducts} end
return VestibuleLightMaker
