local PaletteMaker = {}
local PRODUCTS = {
    iron_palette = { name = "Železna paleta", ironCost = 1, woodCost = 3, leatherCost = 1, time = 4, cost = 120, prestige = 3, happiness = 2, description = "Železna paleta za mešanje barv." },
    bronze_palette = { name = "Bronasta paleta", bronzeCost = 1, ironCost = 1, woodCost = 3, leatherCost = 1, time = 6, cost = 300, prestige = 5, happiness = 3, description = "Bronasta paleta za atelje." },
    silver_palette = { name = "Srebrna paleta", silverCost = 1, bronzeCost = 1, ironCost = 1, woodCost = 3, leatherCost = 1, time = 10, cost = 740, prestige = 10, happiness = 4, description = "Srebrna paleta za plemiške slikarje." },
    gilded_palette = { name = "Pozlačena paleta", goldCost = 1, silverCost = 1, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 14, cost = 1620, prestige = 19, happiness = 5, description = "Pozlačena paleta za dvorne slikarje." },
    jewel_set_palette = { name = "Draguljasta paleta", goldCost = 2, silverCost = 1, jewelCost = 1, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 18, cost = 3550, prestige = 35, happiness = 7, description = "Draguljasta paleta za kraljeve slikarje." },
    royal_sovereign_palette = { name = "Kraljevski suverena paleta", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 4, leatherCost = 1, time = 25, cost = 7900, prestige = 67, happiness = 13, description = "Suverena paleta z biseri za krono." },
}
local BUILDINGS = {
    palette_workshop = { name = "Paletna delavnica", cost = { gold = 290, wood = 175, stone = 120, iron = 6 }, upkeep = 5, qualityBonus = 5 },
    palette_house = { name = "Paletna hiša", cost = { gold = 1080, wood = 350, stone = 250, silver = 6, iron = 6 }, upkeep = 23, qualityBonus = 18 },
    master_palette_atelier = { name = "Mojstrski paletni atelje", cost = { gold = 2870, wood = 410, stone = 490, silver = 32, gold = 6 }, upkeep = 67, qualityBonus = 30 },
    sovereign_palette_palace = { name = "Suverena paletna palača", cost = { gold = 12480, wood = 625, stone = 805, gold = 80, jewel = 18 }, upkeep = 246, qualityBonus = 55, prestigeBonus = 50 },
}
PaletteMaker.ironStock = 10; PaletteMaker.bronzeStock = 8; PaletteMaker.woodStock = 18; PaletteMaker.leatherStock = 10; PaletteMaker.silverStock = 8; PaletteMaker.goldStock = 6; PaletteMaker.jewelStock = 4; PaletteMaker.pearlStock = 4
PaletteMaker.productStock = {}; PaletteMaker.buildings = {}; PaletteMaker.maker = nil; PaletteMaker.activeMaking = {}; PaletteMaker.totalProducts = 0; PaletteMaker.dayTimer = 0
function PaletteMaker.init() PaletteMaker.ironStock=10; PaletteMaker.bronzeStock=8; PaletteMaker.woodStock=18; PaletteMaker.leatherStock=10; PaletteMaker.silverStock=8; PaletteMaker.goldStock=6; PaletteMaker.jewelStock=4; PaletteMaker.pearlStock=4; PaletteMaker.productStock={}; PaletteMaker.buildings={}; PaletteMaker.maker=nil; PaletteMaker.activeMaking={}; PaletteMaker.totalProducts=0; PaletteMaker.dayTimer=0; print("[PaletteMaker] Royal Palette Maker System initialized (6 products, 4 buildings)") end
function PaletteMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; PaletteMaker.maker={name=n or ("Paletar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Paletar najet: %s (spretnost: %d)",PaletteMaker.maker.name,s),"success") end; return true end
function PaletteMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function PaletteMaker.build(id) local ok,e=PaletteMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(PaletteMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function PaletteMaker.getQualityBonus() local b=0; for _,bd in ipairs(PaletteMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function PaletteMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and PaletteMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and PaletteMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and PaletteMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and PaletteMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and PaletteMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and PaletteMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and PaletteMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and PaletteMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #PaletteMaker.buildings==0 then return false,"Potrebna paletna delavnica" end; if not PaletteMaker.maker then return false,"Potreben paletar" end; return true end
function PaletteMaker.make(pt,qty) qty=qty or 1; local ok,e=PaletteMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then PaletteMaker.ironStock=PaletteMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then PaletteMaker.bronzeStock=PaletteMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then PaletteMaker.woodStock=PaletteMaker.woodStock-d.woodCost*qty end; if d.leatherCost then PaletteMaker.leatherStock=PaletteMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then PaletteMaker.silverStock=PaletteMaker.silverStock-d.silverCost*qty end; if d.goldCost then PaletteMaker.goldStock=PaletteMaker.goldStock-d.goldCost*qty end; if d.jewelCost then PaletteMaker.jewelStock=PaletteMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then PaletteMaker.pearlStock=PaletteMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if PaletteMaker.maker then t=math.max(1,t-math.floor(PaletteMaker.maker.skill/13)) end; table.insert(PaletteMaker.activeMaking,{id="palette_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function PaletteMaker.completeMaking(m) local q=1.0+(PaletteMaker.getQualityBonus()/100); if PaletteMaker.maker then q=q+(PaletteMaker.maker.skill/140) end; q=math.min(2.5,q); PaletteMaker.productStock[m.productType]=(PaletteMaker.productStock[m.productType] or 0)+m.quantity; PaletteMaker.totalProducts=PaletteMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if PaletteMaker.maker then PaletteMaker.maker.itemsMade=PaletteMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then PaletteMaker.maker.skill=math.min(100,PaletteMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Paleta izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"palette.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function PaletteMaker.update(dt) if not _G.state then return end; PaletteMaker.dayTimer=PaletteMaker.dayTimer+dt; if PaletteMaker.dayTimer>=30 then PaletteMaker.dayTimer=0; for i=#PaletteMaker.activeMaking,1,-1 do local m=PaletteMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then PaletteMaker.completeMaking(m); table.remove(PaletteMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(PaletteMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if PaletteMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function PaletteMaker.getStats() return {ironStock=PaletteMaker.ironStock,bronzeStock=PaletteMaker.bronzeStock,woodStock=PaletteMaker.woodStock,leatherStock=PaletteMaker.leatherStock,silverStock=PaletteMaker.silverStock,goldStock=PaletteMaker.goldStock,jewelStock=PaletteMaker.jewelStock,pearlStock=PaletteMaker.pearlStock,productStock=PaletteMaker.productStock,numBuildings=#PaletteMaker.buildings,hasMaker=PaletteMaker.maker~=nil,makerName=PaletteMaker.maker and PaletteMaker.maker.name or "—",makerSkill=PaletteMaker.maker and PaletteMaker.maker.skill or 0,activeMaking=#PaletteMaker.activeMaking,totalProducts=PaletteMaker.totalProducts} end
return PaletteMaker
