local GardenWateringTrayMaker = {}
local PRODUCTS = {
    iron_gardenwateringtray = { name = "Železni pladenj za zalivanje", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni pladenj za zalivanje za vrtnarje." },
    bronze_gardenwateringtray = { name = "Bronast pladenj za zalivanje", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast pladenj za zalivanje za vrtnarje." },
    silver_gardenwateringtray = { name = "Srebrn pladenj za zalivanje", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn pladenj za zalivanje za vrtnarje." },
    gilded_gardenwateringtray = { name = "Pozlačen pladenj za zalivanje", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen pladenj za zalivanje za vrtnarje." },
    jewel_set_gardenwateringtray = { name = "Draguljast pladenj za zalivanje", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast pladenj za zalivanje za vrtnarje." },
    royal_sovereign_gardenwateringtray = { name = "Kraljevski suveren pladenj za zalivanje", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren pladenj za zalivanje z biseri za krono." },
}
local BUILDINGS = {
    gardenwateringtray_workshop = { name = "Gardenwateringtray delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    gardenwateringtray_house = { name = "Gardenwateringtray hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_gardenwateringtray_atelier = { name = "Mojstrski gardenwateringtray atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_gardenwateringtray_palace = { name = "Suverena gardenwateringtray palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
GardenWateringTrayMaker.ironStock=12; GardenWateringTrayMaker.bronzeStock=10; GardenWateringTrayMaker.woodStock=14; GardenWateringTrayMaker.leatherStock=10; GardenWateringTrayMaker.silverStock=8; GardenWateringTrayMaker.goldStock=6; GardenWateringTrayMaker.jewelStock=4; GardenWateringTrayMaker.pearlStock=4
GardenWateringTrayMaker.productStock = {}; GardenWateringTrayMaker.buildings = {}; GardenWateringTrayMaker.maker = nil; GardenWateringTrayMaker.activeMaking = {}; GardenWateringTrayMaker.totalProducts = 0; GardenWateringTrayMaker.dayTimer = 0
function GardenWateringTrayMaker.init() GardenWateringTrayMaker.ironStock=12; GardenWateringTrayMaker.bronzeStock=10; GardenWateringTrayMaker.woodStock=14; GardenWateringTrayMaker.leatherStock=10; GardenWateringTrayMaker.silverStock=8; GardenWateringTrayMaker.goldStock=6; GardenWateringTrayMaker.jewelStock=4; GardenWateringTrayMaker.pearlStock=4; GardenWateringTrayMaker.productStock={}; GardenWateringTrayMaker.buildings={}; GardenWateringTrayMaker.maker=nil; GardenWateringTrayMaker.activeMaking={}; GardenWateringTrayMaker.totalProducts=0; GardenWateringTrayMaker.dayTimer=0; print("[GardenWateringTrayMaker] Royal Garden Watering Tray Maker System initialized (6 products, 4 buildings)") end
function GardenWateringTrayMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GardenWateringTrayMaker.maker={name=n or ("Pladnjar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pladnjar najet: %s (spretnost: %d)",GardenWateringTrayMaker.maker.name,s),"success") end; return true end
function GardenWateringTrayMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GardenWateringTrayMaker.build(id) local ok,e=GardenWateringTrayMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GardenWateringTrayMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GardenWateringTrayMaker.getQualityBonus() local b=0; for _,bd in ipairs(GardenWateringTrayMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GardenWateringTrayMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GardenWateringTrayMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GardenWateringTrayMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GardenWateringTrayMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GardenWateringTrayMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GardenWateringTrayMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GardenWateringTrayMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GardenWateringTrayMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GardenWateringTrayMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GardenWateringTrayMaker.buildings==0 then return false,"Potrebna pladnjska delavnica" end; if not GardenWateringTrayMaker.maker then return false,"Potreben pladnjar" end; return true end
function GardenWateringTrayMaker.make(pt,qty) qty=qty or 1; local ok,e=GardenWateringTrayMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GardenWateringTrayMaker.ironStock=GardenWateringTrayMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GardenWateringTrayMaker.bronzeStock=GardenWateringTrayMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GardenWateringTrayMaker.woodStock=GardenWateringTrayMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GardenWateringTrayMaker.leatherStock=GardenWateringTrayMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GardenWateringTrayMaker.silverStock=GardenWateringTrayMaker.silverStock-d.silverCost*qty end; if d.goldCost then GardenWateringTrayMaker.goldStock=GardenWateringTrayMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GardenWateringTrayMaker.jewelStock=GardenWateringTrayMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GardenWateringTrayMaker.pearlStock=GardenWateringTrayMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GardenWateringTrayMaker.maker then t=math.max(1,t-math.floor(GardenWateringTrayMaker.maker.skill/13)) end; table.insert(GardenWateringTrayMaker.activeMaking,{id="gardenwateringtray_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GardenWateringTrayMaker.completeMaking(m) local q=1.0+(GardenWateringTrayMaker.getQualityBonus()/100); if GardenWateringTrayMaker.maker then q=q+(GardenWateringTrayMaker.maker.skill/140) end; q=math.min(2.5,q); GardenWateringTrayMaker.productStock[m.productType]=(GardenWateringTrayMaker.productStock[m.productType] or 0)+m.quantity; GardenWateringTrayMaker.totalProducts=GardenWateringTrayMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GardenWateringTrayMaker.maker then GardenWateringTrayMaker.maker.itemsMade=GardenWateringTrayMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GardenWateringTrayMaker.maker.skill=math.min(100,GardenWateringTrayMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pladenj izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"gardenwateringtray.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GardenWateringTrayMaker.update(dt) if not _G.state then return end; GardenWateringTrayMaker.dayTimer=GardenWateringTrayMaker.dayTimer+dt; if GardenWateringTrayMaker.dayTimer>=30 then GardenWateringTrayMaker.dayTimer=0; for i=#GardenWateringTrayMaker.activeMaking,1,-1 do local m=GardenWateringTrayMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GardenWateringTrayMaker.completeMaking(m); table.remove(GardenWateringTrayMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GardenWateringTrayMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GardenWateringTrayMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GardenWateringTrayMaker.getStats() return {ironStock=GardenWateringTrayMaker.ironStock,bronzeStock=GardenWateringTrayMaker.bronzeStock,woodStock=GardenWateringTrayMaker.woodStock,leatherStock=GardenWateringTrayMaker.leatherStock,silverStock=GardenWateringTrayMaker.silverStock,goldStock=GardenWateringTrayMaker.goldStock,jewelStock=GardenWateringTrayMaker.jewelStock,pearlStock=GardenWateringTrayMaker.pearlStock,productStock=GardenWateringTrayMaker.productStock,numBuildings=#GardenWateringTrayMaker.buildings,hasMaker=GardenWateringTrayMaker.maker~=nil,makerName=GardenWateringTrayMaker.maker and GardenWateringTrayMaker.maker.name or "—",makerSkill=GardenWateringTrayMaker.maker and GardenWateringTrayMaker.maker.skill or 0,activeMaking=#GardenWateringTrayMaker.activeMaking,totalProducts=GardenWateringTrayMaker.totalProducts} end
return GardenWateringTrayMaker
