local SpiceMillMaker = {}
local PRODUCTS = {
    simple_stone_spice_mill = { name = "Preprost kamnit mlin za začimbe", stoneCost = 3, woodCost = 2, time = 4, cost = 150, food = 8, happiness = 1, description = "Preprost kamnit mlin za mletje začimb." },
    iron_reinforced_spice_mill = { name = "Železnookrepljen mlin za začimbe", stoneCost = 2, ironCost = 2, woodCost = 2, time = 7, cost = 380, food = 14, happiness = 2, prestige = 2, description = "Železnookrepljen mlin za začimbe za trgovce." },
    silver_geared_spice_mill = { name = "Srebrnozobčani mlin za začimbe", stoneCost = 2, ironCost = 2, silverCost = 1, woodCost = 2, time = 10, cost = 880, food = 22, happiness = 2, prestige = 6, description = "Srebrnozobčani mlin za začimbe za plemiče." },
    gold_trimmed_spice_mill = { name = "Zlatookrasni mlin za začimbe", stoneCost = 2, ironCost = 2, goldCost = 1, silverCost = 1, woodCost = 2, time = 14, cost = 2000, food = 32, happiness = 3, prestige = 14, description = "Zlatookrasni mlin za začimbe za visoke plemiče." },
    jewel_set_spice_mill = { name = "Draguljasta mlin za začimbe", stoneCost = 2, ironCost = 2, goldCost = 1, silverCost = 1, woodCost = 2, jewelCost = 1, time = 18, cost = 4400, food = 45, happiness = 5, prestige = 27, description = "Mlin za začimbe z draguljem za visoko plemstvo." },
    royal_grand_spice_mill = { name = "Kraljevski veliki mlin za začimbe", stoneCost = 3, ironCost = 3, goldCost = 2, silverCost = 2, woodCost = 2, jewelCost = 2, pearlCost = 2, time = 25, cost = 9500, food = 65, happiness = 12, prestige = 58, description = "Veliki kraljevski mlin za začimbe z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    spice_mill_workshop = { name = "Začimbna mlinska delavnica", cost = { gold = 280, wood = 160, stone = 160, iron = 6 }, upkeep = 6, qualityBonus = 5 },
    milling_loft = { name = "Mlinska podstrešje", cost = { gold = 1000, wood = 320, stone = 280, silver = 6, iron = 8 }, upkeep = 23, qualityBonus = 18 },
    master_spice_miller_atelier = { name = "Mojstrski začimbni mlinski atelje", cost = { gold = 2700, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 62, qualityBonus = 30 },
    royal_spice_mill_palace = { name = "Kraljevska začimbna mlinska palača", cost = { gold = 11500, wood = 600, stone = 800, gold = 75, jewel = 18 }, upkeep = 230, qualityBonus = 55, prestigeBonus = 50 },
}
SpiceMillMaker.stoneStock = 18; SpiceMillMaker.ironStock = 14; SpiceMillMaker.woodStock = 14; SpiceMillMaker.silverStock = 6; SpiceMillMaker.goldStock = 6; SpiceMillMaker.jewelStock = 4; SpiceMillMaker.pearlStock = 4
SpiceMillMaker.productStock = {}; SpiceMillMaker.buildings = {}; SpiceMillMaker.maker = nil; SpiceMillMaker.activeMaking = {}; SpiceMillMaker.totalProducts = 0; SpiceMillMaker.dayTimer = 0
function SpiceMillMaker.init() SpiceMillMaker.stoneStock=18; SpiceMillMaker.ironStock=14; SpiceMillMaker.woodStock=14; SpiceMillMaker.silverStock=6; SpiceMillMaker.goldStock=6; SpiceMillMaker.jewelStock=4; SpiceMillMaker.pearlStock=4; SpiceMillMaker.productStock={}; SpiceMillMaker.buildings={}; SpiceMillMaker.maker=nil; SpiceMillMaker.activeMaking={}; SpiceMillMaker.totalProducts=0; SpiceMillMaker.dayTimer=0; print("[SpiceMillMaker] Royal Spice Mill Maker System initialized (6 products, 4 buildings)") end
function SpiceMillMaker.hireMaker(n,s) s=s or math.random(55,90); local c=560+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SpiceMillMaker.maker={name=n or ("Začimbni mlinar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Začimbni mlinar najet: %s (spretnost: %d)",SpiceMillMaker.maker.name,s),"success") end; return true end
function SpiceMillMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SpiceMillMaker.build(id) local ok,e=SpiceMillMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SpiceMillMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SpiceMillMaker.getQualityBonus() local b=0; for _,bd in ipairs(SpiceMillMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SpiceMillMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.stoneCost and SpiceMillMaker.stoneStock<(d.stoneCost or 0) then return false,"Premalo kamna" end; if d.ironCost and SpiceMillMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.woodCost and SpiceMillMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.silverCost and SpiceMillMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SpiceMillMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SpiceMillMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SpiceMillMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SpiceMillMaker.buildings==0 then return false,"Potrebna začimbna mlinska delavnica" end; if not SpiceMillMaker.maker then return false,"Potreben začimbni mlinar" end; return true end
function SpiceMillMaker.make(pt,qty) qty=qty or 1; local ok,e=SpiceMillMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.stoneCost then SpiceMillMaker.stoneStock=SpiceMillMaker.stoneStock-d.stoneCost*qty end; if d.ironCost then SpiceMillMaker.ironStock=SpiceMillMaker.ironStock-d.ironCost*qty end; if d.woodCost then SpiceMillMaker.woodStock=SpiceMillMaker.woodStock-d.woodCost*qty end; if d.silverCost then SpiceMillMaker.silverStock=SpiceMillMaker.silverStock-d.silverCost*qty end; if d.goldCost then SpiceMillMaker.goldStock=SpiceMillMaker.goldStock-d.goldCost*qty end; if d.jewelCost then SpiceMillMaker.jewelStock=SpiceMillMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then SpiceMillMaker.pearlStock=SpiceMillMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if SpiceMillMaker.maker then t=math.max(1,t-math.floor(SpiceMillMaker.maker.skill/13)) end; table.insert(SpiceMillMaker.activeMaking,{id="spicemill_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=d.food or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SpiceMillMaker.completeMaking(m) local q=1.0+(SpiceMillMaker.getQualityBonus()/100); if SpiceMillMaker.maker then q=q+(SpiceMillMaker.maker.skill/140) end; q=math.min(2.5,q); SpiceMillMaker.productStock[m.productType]=(SpiceMillMaker.productStock[m.productType] or 0)+m.quantity; SpiceMillMaker.totalProducts=SpiceMillMaker.totalProducts+m.quantity; if m.food>0 and _G.state then _G.state.food=(_G.state.food or 0)+m.food end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SpiceMillMaker.maker then SpiceMillMaker.maker.itemsMade=SpiceMillMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then SpiceMillMaker.maker.skill=math.min(100,SpiceMillMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mlin za začimbe izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"spicemill.completed",{productName=m.productName,food=m.food,prestige=m.prestige,happiness=m.happiness}) end end
function SpiceMillMaker.update(dt) if not _G.state then return end; SpiceMillMaker.dayTimer=SpiceMillMaker.dayTimer+dt; if SpiceMillMaker.dayTimer>=30 then SpiceMillMaker.dayTimer=0; for i=#SpiceMillMaker.activeMaking,1,-1 do local m=SpiceMillMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SpiceMillMaker.completeMaking(m); table.remove(SpiceMillMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SpiceMillMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SpiceMillMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SpiceMillMaker.getStats() return {stoneStock=SpiceMillMaker.stoneStock,ironStock=SpiceMillMaker.ironStock,woodStock=SpiceMillMaker.woodStock,silverStock=SpiceMillMaker.silverStock,goldStock=SpiceMillMaker.goldStock,jewelStock=SpiceMillMaker.jewelStock,pearlStock=SpiceMillMaker.pearlStock,productStock=SpiceMillMaker.productStock,numBuildings=#SpiceMillMaker.buildings,hasMaker=SpiceMillMaker.maker~=nil,makerName=SpiceMillMaker.maker and SpiceMillMaker.maker.name or "—",makerSkill=SpiceMillMaker.maker and SpiceMillMaker.maker.skill or 0,activeMaking=#SpiceMillMaker.activeMaking,totalProducts=SpiceMillMaker.totalProducts} end
return SpiceMillMaker
