local ForcepsMaker = {}
local PRODUCTS = {
    iron_forceps = { name = "Zelezne klesce", ironCost = 2, woodCost = 1, leatherCost = 1, time = 5, cost = 160, prestige = 3, happiness = 1, description = "Zelezne klesce za ekstrakcijo." },
    bronze_forceps = { name = "Bronaste klesce", bronzeCost = 2, ironCost = 1, woodCost = 1, leatherCost = 1, time = 7, cost = 380, prestige = 5, happiness = 2, description = "Bronaste klesce za kirurge." },
    silver_forceps = { name = "Srebrne klesce", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 11, cost = 900, prestige = 10, happiness = 3, description = "Srebrne klesce za plemiske zdravnike." },
    gilded_forceps = { name = "Pozlacene klesce", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 15, cost = 1920, prestige = 19, happiness = 4, description = "Pozlacene klesce za dvornega kirurga." },
    jewel_set_forceps = { name = "Draguljaste klesce", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 6, description = "Draguljaste klesce za kraljevega zdravnika." },
    royal_sovereign_forceps = { name = "Kraljevski suverena klesce", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 26, cost = 8800, prestige = 70, happiness = 12, description = "Suverena klesce z biseri za krono." },
}
local BUILDINGS = {
    forceps_workshop = { name = "Klescarska delavnica", cost = { gold = 350, wood = 170, stone = 130, iron = 7 }, upkeep = 7, qualityBonus = 5 },
    forceps_house = { name = "Klescarska hisa", cost = { gold = 1250, wood = 360, stone = 270, silver = 7, iron = 7 }, upkeep = 27, qualityBonus = 18 },
    master_forceps_atelier = { name = "Mojstrski klescarski atelje", cost = { gold = 3120, wood = 420, stone = 520, silver = 36, gold = 7 }, upkeep = 72, qualityBonus = 30 },
    sovereign_surgical_palace = { name = "Suverena kirurska palaca", cost = { gold = 13200, wood = 620, stone = 820, gold = 85, jewel = 19 }, upkeep = 255, qualityBonus = 55, prestigeBonus = 55 },
}
ForcepsMaker.ironStock = 12; ForcepsMaker.bronzeStock = 10; ForcepsMaker.woodStock = 14; ForcepsMaker.leatherStock = 10; ForcepsMaker.silverStock = 8; ForcepsMaker.goldStock = 6; ForcepsMaker.jewelStock = 4; ForcepsMaker.pearlStock = 4
ForcepsMaker.productStock = {}; ForcepsMaker.buildings = {}; ForcepsMaker.maker = nil; ForcepsMaker.activeMaking = {}; ForcepsMaker.totalProducts = 0; ForcepsMaker.dayTimer = 0
function ForcepsMaker.init() ForcepsMaker.ironStock=12; ForcepsMaker.bronzeStock=10; ForcepsMaker.woodStock=14; ForcepsMaker.leatherStock=10; ForcepsMaker.silverStock=8; ForcepsMaker.goldStock=6; ForcepsMaker.jewelStock=4; ForcepsMaker.pearlStock=4; ForcepsMaker.productStock={}; ForcepsMaker.buildings={}; ForcepsMaker.maker=nil; ForcepsMaker.activeMaking={}; ForcepsMaker.totalProducts=0; ForcepsMaker.dayTimer=0; print("[ForcepsMaker] Royal Forceps Maker System initialized (6 products, 4 buildings)") end
function ForcepsMaker.hireMaker(n,s) s=s or math.random(55,90); local c=600+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; ForcepsMaker.maker={name=n or ("Klescar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Klescar najet: %s (spretnost: %d)",ForcepsMaker.maker.name,s),"success") end; return true end
function ForcepsMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function ForcepsMaker.build(id) local ok,e=ForcepsMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(ForcepsMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function ForcepsMaker.getQualityBonus() local b=0; for _,bd in ipairs(ForcepsMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function ForcepsMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and ForcepsMaker.ironStock<(d.ironCost or 0) then return false,"Premalo zeleza" end; if d.bronzeCost and ForcepsMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and ForcepsMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and ForcepsMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and ForcepsMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and ForcepsMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and ForcepsMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and ForcepsMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #ForcepsMaker.buildings==0 then return false,"Potrebna delavnica" end; if not ForcepsMaker.maker then return false,"Potreben mojster" end; return true end
function ForcepsMaker.make(pt,qty) qty=qty or 1; local ok,e=ForcepsMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then ForcepsMaker.ironStock=ForcepsMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then ForcepsMaker.bronzeStock=ForcepsMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then ForcepsMaker.woodStock=ForcepsMaker.woodStock-d.woodCost*qty end; if d.leatherCost then ForcepsMaker.leatherStock=ForcepsMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then ForcepsMaker.silverStock=ForcepsMaker.silverStock-d.silverCost*qty end; if d.goldCost then ForcepsMaker.goldStock=ForcepsMaker.goldStock-d.goldCost*qty end; if d.jewelCost then ForcepsMaker.jewelStock=ForcepsMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then ForcepsMaker.pearlStock=ForcepsMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if ForcepsMaker.maker then t=math.max(1,t-math.floor(ForcepsMaker.maker.skill/13)) end; table.insert(ForcepsMaker.activeMaking,{id="forceps_"..tostring(os.time()).."_a"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function ForcepsMaker.completeMaking(m) local q=1.0+(ForcepsMaker.getQualityBonus()/100); if ForcepsMaker.maker then q=q+(ForcepsMaker.maker.skill/140) end; q=math.min(2.5,q); ForcepsMaker.productStock[m.productType]=(ForcepsMaker.productStock[m.productType] or 0)+m.quantity; ForcepsMaker.totalProducts=ForcepsMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if ForcepsMaker.maker then ForcepsMaker.maker.itemsMade=ForcepsMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then ForcepsMaker.maker.skill=math.min(100,ForcepsMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"forceps.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function ForcepsMaker.update(dt) if not _G.state then return end; ForcepsMaker.dayTimer=ForcepsMaker.dayTimer+dt; if ForcepsMaker.dayTimer>=30 then ForcepsMaker.dayTimer=0; for i=#ForcepsMaker.activeMaking,1,-1 do local m=ForcepsMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then ForcepsMaker.completeMaking(m); table.remove(ForcepsMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(ForcepsMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if ForcepsMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function ForcepsMaker.getStats() return {ironStock=ForcepsMaker.ironStock,bronzeStock=ForcepsMaker.bronzeStock,woodStock=ForcepsMaker.woodStock,leatherStock=ForcepsMaker.leatherStock,silverStock=ForcepsMaker.silverStock,goldStock=ForcepsMaker.goldStock,jewelStock=ForcepsMaker.jewelStock,pearlStock=ForcepsMaker.pearlStock,productStock=ForcepsMaker.productStock,numBuildings=#ForcepsMaker.buildings,hasMaker=ForcepsMaker.maker~=nil,makerName=ForcepsMaker.maker and ForcepsMaker.maker.name or "Â",makerSkill=ForcepsMaker.maker and ForcepsMaker.maker.skill or 0,activeMaking=#ForcepsMaker.activeMaking,totalProducts=ForcepsMaker.totalProducts} end
return ForcepsMaker
