local BookStitchingFrameMaker = {}
local PRODUCTS = {
    iron_bookstitchingframe = { name = "Železni okvir za šivanje knjig", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni okvir za šivanje knjig za knjigoveze." },
    bronze_bookstitchingframe = { name = "Bronast okvir za šivanje knjig", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast okvir za šivanje knjig za knjigoveze." },
    silver_bookstitchingframe = { name = "Srebrn okvir za šivanje knjig", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn okvir za šivanje knjig za knjigoveze." },
    gilded_bookstitchingframe = { name = "Pozlačen okvir za šivanje knjig", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen okvir za šivanje knjig za knjigoveze." },
    jewel_set_bookstitchingframe = { name = "Draguljast okvir za šivanje knjig", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast okvir za šivanje knjig za knjigoveze." },
    royal_sovereign_bookstitchingframe = { name = "Kraljevski suveren okvir za šivanje knjig", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren okvir za šivanje knjig z biseri za krono." },
}
local BUILDINGS = {
    bookstitchingframe_workshop = { name = "Bookstitchingframe delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    bookstitchingframe_house = { name = "Bookstitchingframe hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_bookstitchingframe_atelier = { name = "Mojstrski bookstitchingframe atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_bookstitchingframe_palace = { name = "Suverena bookstitchingframe palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
BookStitchingFrameMaker.ironStock=12; BookStitchingFrameMaker.bronzeStock=10; BookStitchingFrameMaker.woodStock=18; BookStitchingFrameMaker.leatherStock=8; BookStitchingFrameMaker.silverStock=8; BookStitchingFrameMaker.goldStock=6; BookStitchingFrameMaker.jewelStock=4; BookStitchingFrameMaker.pearlStock=4
BookStitchingFrameMaker.productStock = {}; BookStitchingFrameMaker.buildings = {}; BookStitchingFrameMaker.maker = nil; BookStitchingFrameMaker.activeMaking = {}; BookStitchingFrameMaker.totalProducts = 0; BookStitchingFrameMaker.dayTimer = 0
function BookStitchingFrameMaker.init() BookStitchingFrameMaker.ironStock=12; BookStitchingFrameMaker.bronzeStock=10; BookStitchingFrameMaker.woodStock=18; BookStitchingFrameMaker.leatherStock=8; BookStitchingFrameMaker.silverStock=8; BookStitchingFrameMaker.goldStock=6; BookStitchingFrameMaker.jewelStock=4; BookStitchingFrameMaker.pearlStock=4; BookStitchingFrameMaker.productStock={}; BookStitchingFrameMaker.buildings={}; BookStitchingFrameMaker.maker=nil; BookStitchingFrameMaker.activeMaking={}; BookStitchingFrameMaker.totalProducts=0; BookStitchingFrameMaker.dayTimer=0; print("[BookStitchingFrameMaker] Royal Book Stitching Frame Maker System initialized (6 products, 4 buildings)") end
function BookStitchingFrameMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; BookStitchingFrameMaker.maker={name=n or ("Okvirjar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Okvirjar najet: %s (spretnost: %d)",BookStitchingFrameMaker.maker.name,s),"success") end; return true end
function BookStitchingFrameMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function BookStitchingFrameMaker.build(id) local ok,e=BookStitchingFrameMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(BookStitchingFrameMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function BookStitchingFrameMaker.getQualityBonus() local b=0; for _,bd in ipairs(BookStitchingFrameMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function BookStitchingFrameMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and BookStitchingFrameMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and BookStitchingFrameMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and BookStitchingFrameMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and BookStitchingFrameMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and BookStitchingFrameMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and BookStitchingFrameMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and BookStitchingFrameMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and BookStitchingFrameMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #BookStitchingFrameMaker.buildings==0 then return false,"Potrebna okvirna delavnica" end; if not BookStitchingFrameMaker.maker then return false,"Potreben okvirjar" end; return true end
function BookStitchingFrameMaker.make(pt,qty) qty=qty or 1; local ok,e=BookStitchingFrameMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then BookStitchingFrameMaker.ironStock=BookStitchingFrameMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then BookStitchingFrameMaker.bronzeStock=BookStitchingFrameMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then BookStitchingFrameMaker.woodStock=BookStitchingFrameMaker.woodStock-d.woodCost*qty end; if d.leatherCost then BookStitchingFrameMaker.leatherStock=BookStitchingFrameMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then BookStitchingFrameMaker.silverStock=BookStitchingFrameMaker.silverStock-d.silverCost*qty end; if d.goldCost then BookStitchingFrameMaker.goldStock=BookStitchingFrameMaker.goldStock-d.goldCost*qty end; if d.jewelCost then BookStitchingFrameMaker.jewelStock=BookStitchingFrameMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then BookStitchingFrameMaker.pearlStock=BookStitchingFrameMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if BookStitchingFrameMaker.maker then t=math.max(1,t-math.floor(BookStitchingFrameMaker.maker.skill/13)) end; table.insert(BookStitchingFrameMaker.activeMaking,{id="bookstitchingframe_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function BookStitchingFrameMaker.completeMaking(m) local q=1.0+(BookStitchingFrameMaker.getQualityBonus()/100); if BookStitchingFrameMaker.maker then q=q+(BookStitchingFrameMaker.maker.skill/140) end; q=math.min(2.5,q); BookStitchingFrameMaker.productStock[m.productType]=(BookStitchingFrameMaker.productStock[m.productType] or 0)+m.quantity; BookStitchingFrameMaker.totalProducts=BookStitchingFrameMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if BookStitchingFrameMaker.maker then BookStitchingFrameMaker.maker.itemsMade=BookStitchingFrameMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then BookStitchingFrameMaker.maker.skill=math.min(100,BookStitchingFrameMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Okvir izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"bookstitchingframe.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function BookStitchingFrameMaker.update(dt) if not _G.state then return end; BookStitchingFrameMaker.dayTimer=BookStitchingFrameMaker.dayTimer+dt; if BookStitchingFrameMaker.dayTimer>=30 then BookStitchingFrameMaker.dayTimer=0; for i=#BookStitchingFrameMaker.activeMaking,1,-1 do local m=BookStitchingFrameMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then BookStitchingFrameMaker.completeMaking(m); table.remove(BookStitchingFrameMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(BookStitchingFrameMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if BookStitchingFrameMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function BookStitchingFrameMaker.getStats() return {ironStock=BookStitchingFrameMaker.ironStock,bronzeStock=BookStitchingFrameMaker.bronzeStock,woodStock=BookStitchingFrameMaker.woodStock,leatherStock=BookStitchingFrameMaker.leatherStock,silverStock=BookStitchingFrameMaker.silverStock,goldStock=BookStitchingFrameMaker.goldStock,jewelStock=BookStitchingFrameMaker.jewelStock,pearlStock=BookStitchingFrameMaker.pearlStock,productStock=BookStitchingFrameMaker.productStock,numBuildings=#BookStitchingFrameMaker.buildings,hasMaker=BookStitchingFrameMaker.maker~=nil,makerName=BookStitchingFrameMaker.maker and BookStitchingFrameMaker.maker.name or "—",makerSkill=BookStitchingFrameMaker.maker and BookStitchingFrameMaker.maker.skill or 0,activeMaking=#BookStitchingFrameMaker.activeMaking,totalProducts=BookStitchingFrameMaker.totalProducts} end
return BookStitchingFrameMaker
