local HoneyCollector = {}
local PRODUCTS = {
    wild_honey = { name = "Divji med", waxCost = 1, time = 2, cost = 18, sweetness = 50, happiness = 1, description = "Divji med iz gozdnih panjev." },
    clover_honey = { name = "Deteljin med", flowerCost = 2, waxCost = 1, time = 3, cost = 40, sweetness = 60, happiness = 2, prestige = 1, description = "Deteljin med z nežnim okusom." },
    wildflower_honey = { name = "Gozdni cvetlični med", flowerCost = 3, waxCost = 1, time = 5, cost = 90, sweetness = 70, happiness = 3, prestige = 2, description = "Cvetlični med iz gozdnih rož." },
    lavender_honey = { name = "Sivkin med", flowerCost = 4, waxCost = 1, time = 7, cost = 200, sweetness = 80, happiness = 4, prestige = 5, description = "Sivkin med z zdravilnimi lastnostmi." },
    silver_comb_honey = { name = "Srebrno satje med", flowerCost = 5, waxCost = 2, silverCost = 1, time = 10, cost = 480, sweetness = 90, happiness = 6, prestige = 12, description = "Med iz srebrnega satja za plemiče." },
    royal_ambrosia_honey = { name = "Kraljevski ambrozij med", flowerCost = 8, goldCost = 1, silverCost = 1, jewelCost = 1, waxCost = 3, time = 15, cost = 1500, sweetness = 100, happiness = 14, prestige = 36, description = "Veliki kraljevski ambrozij med z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Medenjarska delavnica", cost = { gold = 260, wood = 140 }, upkeep = 6, qualityBonus = 5 },
    apiary = { name = "Panjarna", cost = { gold = 850, wood = 280, flower = 10 }, upkeep = 20, qualityBonus = 18 },
    extraction_room = { name = "Izvlekalnica", cost = { gold = 2000, wood = 350, stone = 500, silver = 30, wax = 10 }, upkeep = 50, qualityBonus = 30 },
    royal_honey_atelier = { name = "Kraljevski atelje medu", cost = { gold = 8500, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 170, qualityBonus = 55, prestigeBonus = 40 },
}
HoneyCollector.flowerStock = 22; HoneyCollector.waxStock = 14; HoneyCollector.silverStock = 8; HoneyCollector.goldStock = 6; HoneyCollector.jewelStock = 6
HoneyCollector.productStock = {}; HoneyCollector.buildings = {}; HoneyCollector.maker = nil; HoneyCollector.activeMaking = {}; HoneyCollector.totalProducts = 0; HoneyCollector.dayTimer = 0
function HoneyCollector.init() HoneyCollector.flowerStock=22; HoneyCollector.waxStock=14; HoneyCollector.silverStock=8; HoneyCollector.goldStock=6; HoneyCollector.jewelStock=6; HoneyCollector.productStock={}; HoneyCollector.buildings={}; HoneyCollector.maker=nil; HoneyCollector.activeMaking={}; HoneyCollector.totalProducts=0; HoneyCollector.dayTimer=0; print("[HoneyCollector] Royal Honey Collector System initialized (6 products, 4 buildings)") end
function HoneyCollector.hireMaker(n,s) s=s or math.random(50,90); local c=480+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; HoneyCollector.maker={name=n or ("Medenjar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Medenjar najet: %s (spretnost: %d)",HoneyCollector.maker.name,s),"success") end; return true end
function HoneyCollector.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function HoneyCollector.build(id) local ok,e=HoneyCollector.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(HoneyCollector.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function HoneyCollector.getQualityBonus() local b=0; for _,bd in ipairs(HoneyCollector.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function HoneyCollector.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.flowerCost and HoneyCollector.flowerStock<(d.flowerCost or 0) then return false,"Premalo cvetja" end; if d.waxCost and HoneyCollector.waxStock<(d.waxCost or 0) then return false,"Premalo voska" end; if d.silverCost and HoneyCollector.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and HoneyCollector.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and HoneyCollector.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if #HoneyCollector.buildings==0 then return false,"Potrebna delavnica" end; if not HoneyCollector.maker then return false,"Potreben medenjar" end; return true end
function HoneyCollector.make(pt,qty) qty=qty or 5; local ok,e=HoneyCollector.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.flowerCost then HoneyCollector.flowerStock=HoneyCollector.flowerStock-d.flowerCost*qty end; if d.waxCost then HoneyCollector.waxStock=HoneyCollector.waxStock-d.waxCost*qty end; if d.silverCost then HoneyCollector.silverStock=HoneyCollector.silverStock-d.silverCost*qty end; if d.goldCost then HoneyCollector.goldStock=HoneyCollector.goldStock-d.goldCost*qty end; if d.jewelCost then HoneyCollector.jewelStock=HoneyCollector.jewelStock-d.jewelCost*qty end; local t=d.time; if HoneyCollector.maker then t=math.max(1,t-math.floor(HoneyCollector.maker.skill/12)) end; table.insert(HoneyCollector.activeMaking,{id="honey_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,sweetness=d.sweetness or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function HoneyCollector.completeMaking(m) local q=1.0+(HoneyCollector.getQualityBonus()/100); if HoneyCollector.maker then q=q+(HoneyCollector.maker.skill/180) end; q=math.min(2.0,q); HoneyCollector.productStock[m.productType]=(HoneyCollector.productStock[m.productType] or 0)+m.quantity; HoneyCollector.totalProducts=HoneyCollector.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if HoneyCollector.maker then HoneyCollector.maker.itemsMade=HoneyCollector.maker.itemsMade+m.quantity; if math.random()<0.20 then HoneyCollector.maker.skill=math.min(100,HoneyCollector.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Med izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"honey.completed",{productName=m.productName,sweetness=m.sweetness,happiness=m.happiness}) end end
function HoneyCollector.update(dt) if not _G.state then return end; HoneyCollector.dayTimer=HoneyCollector.dayTimer+dt; if HoneyCollector.dayTimer>=30 then HoneyCollector.dayTimer=0; for i=#HoneyCollector.activeMaking,1,-1 do local m=HoneyCollector.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then HoneyCollector.completeMaking(m); table.remove(HoneyCollector.activeMaking,i) end end; local tu=0; for _,bd in ipairs(HoneyCollector.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if HoneyCollector.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function HoneyCollector.getStats() return {flowerStock=HoneyCollector.flowerStock,waxStock=HoneyCollector.waxStock,silverStock=HoneyCollector.silverStock,goldStock=HoneyCollector.goldStock,jewelStock=HoneyCollector.jewelStock,productStock=HoneyCollector.productStock,numBuildings=#HoneyCollector.buildings,hasMaker=HoneyCollector.maker~=nil,makerName=HoneyCollector.maker and HoneyCollector.maker.name or "—",makerSkill=HoneyCollector.maker and HoneyCollector.maker.skill or 0,activeMaking=#HoneyCollector.activeMaking,totalProducts=HoneyCollector.totalProducts} end
return HoneyCollector
