local FlourSifterMaker = {}
local PRODUCTS = {
    iron_flour_sifter = { name = "Železno sito za moko", ironCost = 2, woodCost = 3, leatherCost = 1, time = 5, cost = 145, prestige = 3, happiness = 2, description = "Železno sito za sejanje moke." },
    bronze_flour_sifter = { name = "Bronasto sito za moko", bronzeCost = 2, ironCost = 1, woodCost = 3, leatherCost = 1, time = 7, cost = 350, prestige = 5, happiness = 3, description = "Bronasto sito za finijo moko." },
    silver_flour_sifter = { name = "Srebrno sito za moko", silverCost = 2, bronzeCost = 1, ironCost = 1, woodCost = 3, leatherCost = 1, time = 11, cost = 850, prestige = 10, happiness = 4, description = "Srebrno sito za plemiške mline." },
    gilded_flour_sifter = { name = "Pozlačeno sito za moko", goldCost = 1, silverCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 15, cost = 1820, prestige = 19, happiness = 5, description = "Pozlačeno sito za dvorne mline." },
    jewel_set_flour_sifter = { name = "Draguljasto sito za moko", goldCost = 2, silverCost = 2, jewelCost = 1, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 19, cost = 3920, prestige = 35, happiness = 7, description = "Draguljasto sito za kraljeve mline." },
    royal_sovereign_flour_sifter = { name = "Kraljevski suvereno sito za moko", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 4, leatherCost = 1, time = 26, cost = 8400, prestige = 67, happiness = 13, description = "Suvereno sito z biseri za krono." },
}
local BUILDINGS = {
    floursifter_workshop = { name = "Sitna delavnica", cost = { gold = 305, wood = 180, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    floursifter_house = { name = "Sitna hiša", cost = { gold = 1135, wood = 360, stone = 260, silver = 7, iron = 7 }, upkeep = 24, qualityBonus = 18 },
    master_floursifter_atelier = { name = "Mojstrski sitni atelje", cost = { gold = 2880, wood = 425, stone = 500, silver = 33, gold = 7 }, upkeep = 68, qualityBonus = 30 },
    sovereign_floursifter_palace = { name = "Suverena sitna palača", cost = { gold = 12480, wood = 650, stone = 810, gold = 80, jewel = 18 }, upkeep = 246, qualityBonus = 55, prestigeBonus = 50 },
}
FlourSifterMaker.ironStock = 12; FlourSifterMaker.bronzeStock = 10; FlourSifterMaker.woodStock = 16; FlourSifterMaker.leatherStock = 10; FlourSifterMaker.silverStock = 8; FlourSifterMaker.goldStock = 6; FlourSifterMaker.jewelStock = 4; FlourSifterMaker.pearlStock = 4
FlourSifterMaker.productStock = {}; FlourSifterMaker.buildings = {}; FlourSifterMaker.maker = nil; FlourSifterMaker.activeMaking = {}; FlourSifterMaker.totalProducts = 0; FlourSifterMaker.dayTimer = 0
function FlourSifterMaker.init() FlourSifterMaker.ironStock=12; FlourSifterMaker.bronzeStock=10; FlourSifterMaker.woodStock=16; FlourSifterMaker.leatherStock=10; FlourSifterMaker.silverStock=8; FlourSifterMaker.goldStock=6; FlourSifterMaker.jewelStock=4; FlourSifterMaker.pearlStock=4; FlourSifterMaker.productStock={}; FlourSifterMaker.buildings={}; FlourSifterMaker.maker=nil; FlourSifterMaker.activeMaking={}; FlourSifterMaker.totalProducts=0; FlourSifterMaker.dayTimer=0; print("[FlourSifterMaker] Royal Flour Sifter Maker System initialized (6 products, 4 buildings)") end
function FlourSifterMaker.hireMaker(n,s) s=s or math.random(55,90); local c=570+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; FlourSifterMaker.maker={name=n or ("Sitar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sitar najet: %s (spretnost: %d)",FlourSifterMaker.maker.name,s),"success") end; return true end
function FlourSifterMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function FlourSifterMaker.build(id) local ok,e=FlourSifterMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(FlourSifterMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function FlourSifterMaker.getQualityBonus() local b=0; for _,bd in ipairs(FlourSifterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function FlourSifterMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and FlourSifterMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and FlourSifterMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and FlourSifterMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and FlourSifterMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and FlourSifterMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and FlourSifterMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and FlourSifterMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and FlourSifterMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #FlourSifterMaker.buildings==0 then return false,"Potrebna sitna delavnica" end; if not FlourSifterMaker.maker then return false,"Potreben sitar" end; return true end
function FlourSifterMaker.make(pt,qty) qty=qty or 1; local ok,e=FlourSifterMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then FlourSifterMaker.ironStock=FlourSifterMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then FlourSifterMaker.bronzeStock=FlourSifterMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then FlourSifterMaker.woodStock=FlourSifterMaker.woodStock-d.woodCost*qty end; if d.leatherCost then FlourSifterMaker.leatherStock=FlourSifterMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then FlourSifterMaker.silverStock=FlourSifterMaker.silverStock-d.silverCost*qty end; if d.goldCost then FlourSifterMaker.goldStock=FlourSifterMaker.goldStock-d.goldCost*qty end; if d.jewelCost then FlourSifterMaker.jewelStock=FlourSifterMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then FlourSifterMaker.pearlStock=FlourSifterMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if FlourSifterMaker.maker then t=math.max(1,t-math.floor(FlourSifterMaker.maker.skill/13)) end; table.insert(FlourSifterMaker.activeMaking,{id="floursifter_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function FlourSifterMaker.completeMaking(m) local q=1.0+(FlourSifterMaker.getQualityBonus()/100); if FlourSifterMaker.maker then q=q+(FlourSifterMaker.maker.skill/140) end; q=math.min(2.5,q); FlourSifterMaker.productStock[m.productType]=(FlourSifterMaker.productStock[m.productType] or 0)+m.quantity; FlourSifterMaker.totalProducts=FlourSifterMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if FlourSifterMaker.maker then FlourSifterMaker.maker.itemsMade=FlourSifterMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then FlourSifterMaker.maker.skill=math.min(100,FlourSifterMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Sito izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"floursifter.completed",{productName=m.productName,prestige=m.prestige,happiness:m.happiness}) end end
function FlourSifterMaker.update(dt) if not _G.state then return end; FlourSifterMaker.dayTimer=FlourSifterMaker.dayTimer+dt; if FlourSifterMaker.dayTimer>=30 then FlourSifterMaker.dayTimer=0; for i=#FlourSifterMaker.activeMaking,1,-1 do local m=FlourSifterMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then FlourSifterMaker.completeMaking(m); table.remove(FlourSifterMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(FlourSifterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if FlourSifterMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function FlourSifterMaker.getStats() return {ironStock=FlourSifterMaker.ironStock,bronzeStock=FlourSifterMaker.bronzeStock,woodStock=FlourSifterMaker.woodStock,leatherStock=FlourSifterMaker.leatherStock,silverStock=FlourSifterMaker.silverStock,goldStock=FlourSifterMaker.goldStock,jewelStock=FlourSifterMaker.jewelStock,pearlStock=FlourSifterMaker.pearlStock,productStock=FlourSifterMaker.productStock,numBuildings=#FlourSifterMaker.buildings,hasMaker=FlourSifterMaker.maker~=nil,makerName=FlourSifterMaker.maker and FlourSifterMaker.maker.name or "—",makerSkill=FlourSifterMaker.maker and FlourSifterMaker.maker.skill or 0,activeMaking=#FlourSifterMaker.activeMaking,totalProducts=FlourSifterMaker.totalProducts} end
return FlourSifterMaker
