local MillstoneMaker = {}
local PRODUCTS = {
    iron_millstone = { name = "Železni mlinček za žito", ironCost = 3, woodCost = 2, leatherCost = 1, time = 6, cost = 200, prestige = 4, happiness = 2, description = "Železni mlinček za mletje žita." },
    bronze_millstone = { name = "Bronast mlinček za žito", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 8, cost = 480, prestige = 6, happiness = 3, description = "Bronast mlinček za fino moko." },
    silver_millstone = { name = "Srebrni mlinček za žito", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 12, cost = 1150, prestige = 11, happiness = 4, description = "Srebrni mlinček za plemiške mline." },
    gilded_millstone = { name = "Pozlačeni mlinček za žito", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 16, cost = 2480, prestige = 20, happiness = 5, description = "Pozlačeni mlinček za dvorne mline." },
    jewel_set_millstone = { name = "Draguljasti mlinček za žito", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 20, cost = 5300, prestige = 36, happiness = 7, description = "Draguljasti mlinček za kraljeve mline." },
    royal_sovereign_millstone = { name = "Kraljevski suvereni mlinček za žito", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 27, cost = 11300, prestige = 70, happiness = 13, description = "Suvereni mlinček z biseri za krono." },
}
local BUILDINGS = {
    millstone_workshop = { name = "Mlinarska delavnica", cost = { gold = 380, wood = 195, stone = 150, iron = 10 }, upkeep = 7, qualityBonus = 5 },
    millstone_house = { name = "Mlinarska hiša", cost = { gold = 1320, wood = 380, stone = 295, silver = 8, iron = 8 }, upkeep = 28, qualityBonus = 18 },
    master_millstone_atelier = { name = "Mojstrski mlinarski atelje", cost = { gold = 3280, wood = 440, stone = 555, silver = 39, gold = 8 }, upkeep = 76, qualityBonus = 30 },
    sovereign_millstone_palace = { name = "Suverena mlinarska palača", cost = { gold = 13900, wood = 670, stone = 875, gold = 89, jewel = 20 }, upkeep = 264, qualityBonus = 55, prestigeBonus = 50 },
}
MillstoneMaker.ironStock = 14; MillstoneMaker.bronzeStock = 12; MillstoneMaker.woodStock = 14; MillstoneMaker.leatherStock = 10; MillstoneMaker.silverStock = 8; MillstoneMaker.goldStock = 6; MillstoneMaker.jewelStock = 4; MillstoneMaker.pearlStock = 4
MillstoneMaker.productStock = {}; MillstoneMaker.buildings = {}; MillstoneMaker.maker = nil; MillstoneMaker.activeMaking = {}; MillstoneMaker.totalProducts = 0; MillstoneMaker.dayTimer = 0
function MillstoneMaker.init() MillstoneMaker.ironStock=14; MillstoneMaker.bronzeStock=12; MillstoneMaker.woodStock=14; MillstoneMaker.leatherStock=10; MillstoneMaker.silverStock=8; MillstoneMaker.goldStock=6; MillstoneMaker.jewelStock=4; MillstoneMaker.pearlStock=4; MillstoneMaker.productStock={}; MillstoneMaker.buildings={}; MillstoneMaker.maker=nil; MillstoneMaker.activeMaking={}; MillstoneMaker.totalProducts=0; MillstoneMaker.dayTimer=0; print("[MillstoneMaker] Royal Millstone Maker System initialized (6 products, 4 buildings)") end
function MillstoneMaker.hireMaker(n,s) s=s or math.random(55,90); local c=595+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MillstoneMaker.maker={name=n or ("Mlinar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mlinar najet: %s (spretnost: %d)",MillstoneMaker.maker.name,s),"success") end; return true end
function MillstoneMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MillstoneMaker.build(id) local ok,e=MillstoneMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MillstoneMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MillstoneMaker.getQualityBonus() local b=0; for _,bd in ipairs(MillstoneMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MillstoneMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MillstoneMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MillstoneMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MillstoneMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MillstoneMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MillstoneMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MillstoneMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MillstoneMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MillstoneMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MillstoneMaker.buildings==0 then return false,"Potrebna mlinarska delavnica" end; if not MillstoneMaker.maker then return false,"Potreben mlinar" end; return true end
function MillstoneMaker.make(pt,qty) qty=qty or 1; local ok,e=MillstoneMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MillstoneMaker.ironStock=MillstoneMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MillstoneMaker.bronzeStock=MillstoneMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MillstoneMaker.woodStock=MillstoneMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MillstoneMaker.leatherStock=MillstoneMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MillstoneMaker.silverStock=MillstoneMaker.silverStock-d.silverCost*qty end; if d.goldCost then MillstoneMaker.goldStock=MillstoneMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MillstoneMaker.jewelStock=MillstoneMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MillstoneMaker.pearlStock=MillstoneMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MillstoneMaker.maker then t=math.max(1,t-math.floor(MillstoneMaker.maker.skill/13)) end; table.insert(MillstoneMaker.activeMaking,{id="millstone_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MillstoneMaker.completeMaking(m) local q=1.0+(MillstoneMaker.getQualityBonus()/100); if MillstoneMaker.maker then q=q+(MillstoneMaker.maker.skill/140) end; q=math.min(2.5,q); MillstoneMaker.productStock[m.productType]=(MillstoneMaker.productStock[m.productType] or 0)+m.quantity; MillstoneMaker.totalProducts=MillstoneMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MillstoneMaker.maker then MillstoneMaker.maker.itemsMade=MillstoneMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MillstoneMaker.maker.skill=math.min(100,MillstoneMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Mlinček izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"millstone.completed",{productName=m.productName,prestige=m.prestige,happiness:m.happiness}) end end
function MillstoneMaker.update(dt) if not _G.state then return end; MillstoneMaker.dayTimer=MillstoneMaker.dayTimer+dt; if MillstoneMaker.dayTimer>=30 then MillstoneMaker.dayTimer=0; for i=#MillstoneMaker.activeMaking,1,-1 do local m=MillstoneMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MillstoneMaker.completeMaking(m); table.remove(MillstoneMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MillstoneMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MillstoneMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MillstoneMaker.getStats() return {ironStock=MillstoneMaker.ironStock,bronzeStock=MillstoneMaker.bronzeStock,woodStock=MillstoneMaker.woodStock,leatherStock=MillstoneMaker.leatherStock,silverStock=MillstoneMaker.silverStock,goldStock=MillstoneMaker.goldStock,jewelStock=MillstoneMaker.jewelStock,pearlStock=MillstoneMaker.pearlStock,productStock=MillstoneMaker.productStock,numBuildings=#MillstoneMaker.buildings,hasMaker=MillstoneMaker.maker~=nil,makerName=MillstoneMaker.maker and MillstoneMaker.maker.name or "—",makerSkill=MillstoneMaker.maker and MillstoneMaker.maker.skill or 0,activeMaking=#MillstoneMaker.activeMaking,totalProducts=MillstoneMaker.totalProducts} end
return MillstoneMaker
