local MoldFlowTesterMaker = {}
local PRODUCTS = {
    iron_moldflowtester = { name = "Železni preizkuševalec pretoka kalupa", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni preizkuševalec pretoka kalupa za livarje." },
    bronze_moldflowtester = { name = "Bronast preizkuševalec pretoka kalupa", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast preizkuševalec pretoka kalupa za livarje." },
    silver_moldflowtester = { name = "Srebrn preizkuševalec pretoka kalupa", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn preizkuševalec pretoka kalupa za livarje." },
    gilded_moldflowtester = { name = "Pozlačen preizkuševalec pretoka kalupa", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen preizkuševalec pretoka kalupa za livarje." },
    jewel_set_moldflowtester = { name = "Draguljast preizkuševalec pretoka kalupa", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast preizkuševalec pretoka kalupa za livarje." },
    royal_sovereign_moldflowtester = { name = "Kraljevski suveren preizkuševalec pretoka kalupa", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren preizkuševalec pretoka kalupa z biseri za krono." },
}
local BUILDINGS = {
    moldflowtester_workshop = { name = "Moldflowtester delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    moldflowtester_house = { name = "Moldflowtester hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_moldflowtester_atelier = { name = "Mojstrski moldflowtester atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_moldflowtester_palace = { name = "Suverena moldflowtester palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
MoldFlowTesterMaker.ironStock=18; MoldFlowTesterMaker.bronzeStock=14; MoldFlowTesterMaker.woodStock=10; MoldFlowTesterMaker.leatherStock=8; MoldFlowTesterMaker.silverStock=8; MoldFlowTesterMaker.goldStock=6; MoldFlowTesterMaker.jewelStock=4; MoldFlowTesterMaker.pearlStock=4
MoldFlowTesterMaker.productStock = {}; MoldFlowTesterMaker.buildings = {}; MoldFlowTesterMaker.maker = nil; MoldFlowTesterMaker.activeMaking = {}; MoldFlowTesterMaker.totalProducts = 0; MoldFlowTesterMaker.dayTimer = 0
function MoldFlowTesterMaker.init() MoldFlowTesterMaker.ironStock=18; MoldFlowTesterMaker.bronzeStock=14; MoldFlowTesterMaker.woodStock=10; MoldFlowTesterMaker.leatherStock=8; MoldFlowTesterMaker.silverStock=8; MoldFlowTesterMaker.goldStock=6; MoldFlowTesterMaker.jewelStock=4; MoldFlowTesterMaker.pearlStock=4; MoldFlowTesterMaker.productStock={}; MoldFlowTesterMaker.buildings={}; MoldFlowTesterMaker.maker=nil; MoldFlowTesterMaker.activeMaking={}; MoldFlowTesterMaker.totalProducts=0; MoldFlowTesterMaker.dayTimer=0; print("[MoldFlowTesterMaker] Royal Mold Flow Tester Maker System initialized (6 products, 4 buildings)") end
function MoldFlowTesterMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; MoldFlowTesterMaker.maker={name=n or ("Preizkušalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Preizkušalec najet: %s (spretnost: %d)",MoldFlowTesterMaker.maker.name,s),"success") end; return true end
function MoldFlowTesterMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function MoldFlowTesterMaker.build(id) local ok,e=MoldFlowTesterMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(MoldFlowTesterMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function MoldFlowTesterMaker.getQualityBonus() local b=0; for _,bd in ipairs(MoldFlowTesterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function MoldFlowTesterMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and MoldFlowTesterMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and MoldFlowTesterMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and MoldFlowTesterMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and MoldFlowTesterMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and MoldFlowTesterMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and MoldFlowTesterMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and MoldFlowTesterMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and MoldFlowTesterMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #MoldFlowTesterMaker.buildings==0 then return false,"Potrebna preizkuševalna delavnica" end; if not MoldFlowTesterMaker.maker then return false,"Potreben preizkusalec" end; return true end
function MoldFlowTesterMaker.make(pt,qty) qty=qty or 1; local ok,e=MoldFlowTesterMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then MoldFlowTesterMaker.ironStock=MoldFlowTesterMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then MoldFlowTesterMaker.bronzeStock=MoldFlowTesterMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then MoldFlowTesterMaker.woodStock=MoldFlowTesterMaker.woodStock-d.woodCost*qty end; if d.leatherCost then MoldFlowTesterMaker.leatherStock=MoldFlowTesterMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then MoldFlowTesterMaker.silverStock=MoldFlowTesterMaker.silverStock-d.silverCost*qty end; if d.goldCost then MoldFlowTesterMaker.goldStock=MoldFlowTesterMaker.goldStock-d.goldCost*qty end; if d.jewelCost then MoldFlowTesterMaker.jewelStock=MoldFlowTesterMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then MoldFlowTesterMaker.pearlStock=MoldFlowTesterMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if MoldFlowTesterMaker.maker then t=math.max(1,t-math.floor(MoldFlowTesterMaker.maker.skill/13)) end; table.insert(MoldFlowTesterMaker.activeMaking,{id="moldflowtester_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function MoldFlowTesterMaker.completeMaking(m) local q=1.0+(MoldFlowTesterMaker.getQualityBonus()/100); if MoldFlowTesterMaker.maker then q=q+(MoldFlowTesterMaker.maker.skill/140) end; q=math.min(2.5,q); MoldFlowTesterMaker.productStock[m.productType]=(MoldFlowTesterMaker.productStock[m.productType] or 0)+m.quantity; MoldFlowTesterMaker.totalProducts=MoldFlowTesterMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if MoldFlowTesterMaker.maker then MoldFlowTesterMaker.maker.itemsMade=MoldFlowTesterMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then MoldFlowTesterMaker.maker.skill=math.min(100,MoldFlowTesterMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Preizkuševalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"moldflowtester.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function MoldFlowTesterMaker.update(dt) if not _G.state then return end; MoldFlowTesterMaker.dayTimer=MoldFlowTesterMaker.dayTimer+dt; if MoldFlowTesterMaker.dayTimer>=30 then MoldFlowTesterMaker.dayTimer=0; for i=#MoldFlowTesterMaker.activeMaking,1,-1 do local m=MoldFlowTesterMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then MoldFlowTesterMaker.completeMaking(m); table.remove(MoldFlowTesterMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(MoldFlowTesterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if MoldFlowTesterMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function MoldFlowTesterMaker.getStats() return {ironStock=MoldFlowTesterMaker.ironStock,bronzeStock=MoldFlowTesterMaker.bronzeStock,woodStock=MoldFlowTesterMaker.woodStock,leatherStock=MoldFlowTesterMaker.leatherStock,silverStock=MoldFlowTesterMaker.silverStock,goldStock=MoldFlowTesterMaker.goldStock,jewelStock=MoldFlowTesterMaker.jewelStock,pearlStock=MoldFlowTesterMaker.pearlStock,productStock=MoldFlowTesterMaker.productStock,numBuildings=#MoldFlowTesterMaker.buildings,hasMaker=MoldFlowTesterMaker.maker~=nil,makerName=MoldFlowTesterMaker.maker and MoldFlowTesterMaker.maker.name or "—",makerSkill=MoldFlowTesterMaker.maker and MoldFlowTesterMaker.maker.skill or 0,activeMaking=#MoldFlowTesterMaker.activeMaking,totalProducts=MoldFlowTesterMaker.totalProducts} end
return MoldFlowTesterMaker
