local SamplerStitcher = {}
local PRODUCTS = {
    plain_alphabet_sampler = { name = "Preprosta črkovna vezenina", linenCost = 2, threadCost = 2, time = 4, cost = 50, beauty = 20, happiness = 1, description = "Preprosta črkovna vezenina za šolo." },
    bordered_motif_sampler = { name = "Obrobljena motivna vezenina", linenCost = 2, threadCost = 3, silkCost = 1, time = 6, cost = 130, beauty = 35, happiness = 1, prestige = 2, description = "Obrobljena motivna vezenina za trgovce." },
    silk_thread_biblical_sampler = { name = "Svilena biblijska vezenina", linenCost = 3, threadCost = 2, silkCost = 2, time = 9, cost = 320, beauty = 50, happiness = 2, prestige = 6, description = "Svilena biblijska vezenina za plemiče." },
    silver_stitched_crest = { name = "Srebrnovezena grbada", linenCost = 3, silkCost = 2, silverCost = 1, threadCost = 2, time = 13, cost = 760, beauty = 65, happiness = 3, prestige = 15, description = "Srebrnovezena grbada za visoke plemiče." },
    gold_embroidered_scene = { name = "Zlato vezana scena", linenCost = 4, silkCost = 3, goldCost = 1, silverCost = 1, threadCost = 2, time = 17, cost = 1700, beauty = 78, happiness = 5, prestige = 27, description = "Zlato vezana scena za visoko plemstvo." },
    royal_embroidered_panels = { name = "Kraljevski vezani paneli", linenCost = 5, silkCost = 4, goldCost = 2, silverCost = 2, jewelCost = 1, pearlCost = 1, threadCost = 3, time = 24, cost = 3900, beauty = 92, happiness = 12, prestige = 58, description = "Veliki kraljevski vezani paneli z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    stitcher_cottage = { name = "Vezenjska koča", cost = { gold = 200, wood = 100, stone = 80, linen = 6, thread = 6 }, upkeep = 4, qualityBonus = 5 },
    embroidery_loft = { name = "Vezenjska podstrešje", cost = { gold = 780, wood = 240, stone = 220, silk = 6, thread = 8 }, upkeep = 18, qualityBonus = 18 },
    fine_stitch_atelier = { name = "Finovezalni atelje", cost = { gold = 2300, wood = 360, stone = 480, silver = 30, gold = 6 }, upkeep = 52, qualityBonus = 30 },
    royal_embroidery_palace = { name = "Kraljevska vezenjska palača", cost = { gold = 9500, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 50 },
}
SamplerStitcher.linenStock = 14; SamplerStitcher.threadStock = 16; SamplerStitcher.silkStock = 10; SamplerStitcher.silverStock = 6; SamplerStitcher.goldStock = 6; SamplerStitcher.jewelStock = 4; SamplerStitcher.pearlStock = 4
SamplerStitcher.productStock = {}; SamplerStitcher.buildings = {}; SamplerStitcher.maker = nil; SamplerStitcher.activeMaking = {}; SamplerStitcher.totalProducts = 0; SamplerStitcher.dayTimer = 0
function SamplerStitcher.init() SamplerStitcher.linenStock=14; SamplerStitcher.threadStock=16; SamplerStitcher.silkStock=10; SamplerStitcher.silverStock=6; SamplerStitcher.goldStock=6; SamplerStitcher.jewelStock=4; SamplerStitcher.pearlStock=4; SamplerStitcher.productStock={}; SamplerStitcher.buildings={}; SamplerStitcher.maker=nil; SamplerStitcher.activeMaking={}; SamplerStitcher.totalProducts=0; SamplerStitcher.dayTimer=0; print("[SamplerStitcher] Royal Sampler Stitcher System initialized (6 products, 4 buildings)") end
function SamplerStitcher.hireMaker(n,s) s=s or math.random(55,90); local c=480+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; SamplerStitcher.maker={name=n or ("Vezenjak "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vezenjak najet: %s (spretnost: %d)",SamplerStitcher.maker.name,s),"success") end; return true end
function SamplerStitcher.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function SamplerStitcher.build(id) local ok,e=SamplerStitcher.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(SamplerStitcher.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function SamplerStitcher.getQualityBonus() local b=0; for _,bd in ipairs(SamplerStitcher.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function SamplerStitcher.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.linenCost and SamplerStitcher.linenStock<(d.linenCost or 0) then return false,"Premalo lanu" end; if d.threadCost and SamplerStitcher.threadStock<(d.threadCost or 0) then return false,"Premalo niti" end; if d.silkCost and SamplerStitcher.silkStock<(d.silkCost or 0) then return false,"Premalo svile" end; if d.silverCost and SamplerStitcher.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and SamplerStitcher.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and SamplerStitcher.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and SamplerStitcher.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #SamplerStitcher.buildings==0 then return false,"Potrebna vezenjska koča" end; if not SamplerStitcher.maker then return false,"Potreben vezenjak" end; return true end
function SamplerStitcher.make(pt,qty) qty=qty or 1; local ok,e=SamplerStitcher.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.linenCost then SamplerStitcher.linenStock=SamplerStitcher.linenStock-d.linenCost*qty end; if d.threadCost then SamplerStitcher.threadStock=SamplerStitcher.threadStock-d.threadCost*qty end; if d.silkCost then SamplerStitcher.silkStock=SamplerStitcher.silkStock-d.silkCost*qty end; if d.silverCost then SamplerStitcher.silverStock=SamplerStitcher.silverStock-d.silverCost*qty end; if d.goldCost then SamplerStitcher.goldStock=SamplerStitcher.goldStock-d.goldCost*qty end; if d.jewelCost then SamplerStitcher.jewelStock=SamplerStitcher.jewelStock-d.jewelCost*qty end; if d.pearlCost then SamplerStitcher.pearlStock=SamplerStitcher.pearlStock-d.pearlCost*qty end; local t=d.time; if SamplerStitcher.maker then t=math.max(1,t-math.floor(SamplerStitcher.maker.skill/13)) end; table.insert(SamplerStitcher.activeMaking,{id="sampler_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,beauty=d.beauty or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vezenje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function SamplerStitcher.completeMaking(m) local q=1.0+(SamplerStitcher.getQualityBonus()/100); if SamplerStitcher.maker then q=q+(SamplerStitcher.maker.skill/150) end; q=math.min(2.4,q); SamplerStitcher.productStock[m.productType]=(SamplerStitcher.productStock[m.productType] or 0)+m.quantity; SamplerStitcher.totalProducts=SamplerStitcher.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if SamplerStitcher.maker then SamplerStitcher.maker.itemsMade=SamplerStitcher.maker.itemsMade+m.quantity; if math.random()<0.25 then SamplerStitcher.maker.skill=math.min(100,SamplerStitcher.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Vezenina gotova: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"sampler.completed",{productName=m.productName,beauty=m.beauty,prestige=m.prestige,happiness=m.happiness}) end end
function SamplerStitcher.update(dt) if not _G.state then return end; SamplerStitcher.dayTimer=SamplerStitcher.dayTimer+dt; if SamplerStitcher.dayTimer>=30 then SamplerStitcher.dayTimer=0; for i=#SamplerStitcher.activeMaking,1,-1 do local m=SamplerStitcher.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then SamplerStitcher.completeMaking(m); table.remove(SamplerStitcher.activeMaking,i) end end; local tu=0; for _,bd in ipairs(SamplerStitcher.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if SamplerStitcher.maker then tu=tu+12 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function SamplerStitcher.getStats() return {linenStock=SamplerStitcher.linenStock,threadStock=SamplerStitcher.threadStock,silkStock=SamplerStitcher.silkStock,silverStock=SamplerStitcher.silverStock,goldStock=SamplerStitcher.goldStock,jewelStock=SamplerStitcher.jewelStock,pearlStock=SamplerStitcher.pearlStock,productStock=SamplerStitcher.productStock,numBuildings=#SamplerStitcher.buildings,hasMaker=SamplerStitcher.maker~=nil,makerName=SamplerStitcher.maker and SamplerStitcher.maker.name or "—",makerSkill=SamplerStitcher.maker and SamplerStitcher.maker.skill or 0,activeMaking=#SamplerStitcher.activeMaking,totalProducts=SamplerStitcher.totalProducts} end
return SamplerStitcher
