local AnvilStumpWedgeMaker = {}
local PRODUCTS = {
    iron_anvilstumpwedge = { name = "Železni klin za panj nakovala", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 150, prestige = 4, happiness = 2, description = "Železni klin za panj nakovala za kovace." },
    bronze_anvilstumpwedge = { name = "Bronast klin za panj nakovala", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 365, prestige = 6, happiness = 3, description = "Bronast klin za panj nakovala za kovace." },
    silver_anvilstumpwedge = { name = "Srebrn klin za panj nakovala", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 880, prestige = 11, happiness = 4, description = "Srebrn klin za panj nakovala za kovace." },
    gilded_anvilstumpwedge = { name = "Pozlačen klin za panj nakovala", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 1900, prestige = 20, happiness = 5, description = "Pozlačen klin za panj nakovala za kovace." },
    jewel_set_anvilstumpwedge = { name = "Draguljast klin za panj nakovala", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4100, prestige = 36, happiness = 7, description = "Draguljast klin za panj nakovala za kovace." },
    royal_sovereign_anvilstumpwedge = { name = "Kraljevski suveren klin za panj nakovala", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 8800, prestige = 68, happiness = 13, description = "Suveren klin za panj nakovala z biseri za krono." },
}
local BUILDINGS = {
    anvilstumpwedge_workshop = { name = "Anvilstumpwedge delavnica", cost = { gold = 325, wood = 185, stone = 130, iron = 7 }, upkeep = 6, qualityBonus = 5 },
    anvilstumpwedge_house = { name = "Anvilstumpwedge hiša", cost = { gold = 1185, wood = 370, stone = 265, silver = 7, iron = 7 }, upkeep = 25, qualityBonus = 18 },
    master_anvilstumpwedge_atelier = { name = "Mojstrski anvilstumpwedge atelje", cost = { gold = 2975, wood = 425, stone = 515, silver = 35, gold = 7 }, upkeep = 70, qualityBonus = 30 },
    sovereign_anvilstumpwedge_palace = { name = "Suverena anvilstumpwedge palača", cost = { gold = 12920, wood = 650, stone = 825, gold = 83, jewel = 19 }, upkeep = 253, qualityBonus = 55, prestigeBonus = 50 },
}
AnvilStumpWedgeMaker.ironStock=14; AnvilStumpWedgeMaker.bronzeStock=12; AnvilStumpWedgeMaker.woodStock=14; AnvilStumpWedgeMaker.leatherStock=8; AnvilStumpWedgeMaker.silverStock=8; AnvilStumpWedgeMaker.goldStock=6; AnvilStumpWedgeMaker.jewelStock=4; AnvilStumpWedgeMaker.pearlStock=4
AnvilStumpWedgeMaker.productStock = {}; AnvilStumpWedgeMaker.buildings = {}; AnvilStumpWedgeMaker.maker = nil; AnvilStumpWedgeMaker.activeMaking = {}; AnvilStumpWedgeMaker.totalProducts = 0; AnvilStumpWedgeMaker.dayTimer = 0
function AnvilStumpWedgeMaker.init() AnvilStumpWedgeMaker.ironStock=14; AnvilStumpWedgeMaker.bronzeStock=12; AnvilStumpWedgeMaker.woodStock=14; AnvilStumpWedgeMaker.leatherStock=8; AnvilStumpWedgeMaker.silverStock=8; AnvilStumpWedgeMaker.goldStock=6; AnvilStumpWedgeMaker.jewelStock=4; AnvilStumpWedgeMaker.pearlStock=4; AnvilStumpWedgeMaker.productStock={}; AnvilStumpWedgeMaker.buildings={}; AnvilStumpWedgeMaker.maker=nil; AnvilStumpWedgeMaker.activeMaking={}; AnvilStumpWedgeMaker.totalProducts=0; AnvilStumpWedgeMaker.dayTimer=0; print("[AnvilStumpWedgeMaker] Royal Anvil Stump Wedge Maker System initialized (6 products, 4 buildings)") end
function AnvilStumpWedgeMaker.hireMaker(n,s) s=s or math.random(55,90); local c=575+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; AnvilStumpWedgeMaker.maker={name=n or ("Klinar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Klinar najet: %s (spretnost: %d)",AnvilStumpWedgeMaker.maker.name,s),"success") end; return true end
function AnvilStumpWedgeMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function AnvilStumpWedgeMaker.build(id) local ok,e=AnvilStumpWedgeMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(AnvilStumpWedgeMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function AnvilStumpWedgeMaker.getQualityBonus() local b=0; for _,bd in ipairs(AnvilStumpWedgeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function AnvilStumpWedgeMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and AnvilStumpWedgeMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and AnvilStumpWedgeMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and AnvilStumpWedgeMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and AnvilStumpWedgeMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and AnvilStumpWedgeMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and AnvilStumpWedgeMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and AnvilStumpWedgeMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and AnvilStumpWedgeMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #AnvilStumpWedgeMaker.buildings==0 then return false,"Potrebna klinska delavnica" end; if not AnvilStumpWedgeMaker.maker then return false,"Potreben klinar" end; return true end
function AnvilStumpWedgeMaker.make(pt,qty) qty=qty or 1; local ok,e=AnvilStumpWedgeMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then AnvilStumpWedgeMaker.ironStock=AnvilStumpWedgeMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then AnvilStumpWedgeMaker.bronzeStock=AnvilStumpWedgeMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then AnvilStumpWedgeMaker.woodStock=AnvilStumpWedgeMaker.woodStock-d.woodCost*qty end; if d.leatherCost then AnvilStumpWedgeMaker.leatherStock=AnvilStumpWedgeMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then AnvilStumpWedgeMaker.silverStock=AnvilStumpWedgeMaker.silverStock-d.silverCost*qty end; if d.goldCost then AnvilStumpWedgeMaker.goldStock=AnvilStumpWedgeMaker.goldStock-d.goldCost*qty end; if d.jewelCost then AnvilStumpWedgeMaker.jewelStock=AnvilStumpWedgeMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then AnvilStumpWedgeMaker.pearlStock=AnvilStumpWedgeMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if AnvilStumpWedgeMaker.maker then t=math.max(1,t-math.floor(AnvilStumpWedgeMaker.maker.skill/13)) end; table.insert(AnvilStumpWedgeMaker.activeMaking,{id="anvilstumpwedge_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function AnvilStumpWedgeMaker.completeMaking(m) local q=1.0+(AnvilStumpWedgeMaker.getQualityBonus()/100); if AnvilStumpWedgeMaker.maker then q=q+(AnvilStumpWedgeMaker.maker.skill/140) end; q=math.min(2.5,q); AnvilStumpWedgeMaker.productStock[m.productType]=(AnvilStumpWedgeMaker.productStock[m.productType] or 0)+m.quantity; AnvilStumpWedgeMaker.totalProducts=AnvilStumpWedgeMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if AnvilStumpWedgeMaker.maker then AnvilStumpWedgeMaker.maker.itemsMade=AnvilStumpWedgeMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then AnvilStumpWedgeMaker.maker.skill=math.min(100,AnvilStumpWedgeMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Klin izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"anvilstumpwedge.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function AnvilStumpWedgeMaker.update(dt) if not _G.state then return end; AnvilStumpWedgeMaker.dayTimer=AnvilStumpWedgeMaker.dayTimer+dt; if AnvilStumpWedgeMaker.dayTimer>=30 then AnvilStumpWedgeMaker.dayTimer=0; for i=#AnvilStumpWedgeMaker.activeMaking,1,-1 do local m=AnvilStumpWedgeMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then AnvilStumpWedgeMaker.completeMaking(m); table.remove(AnvilStumpWedgeMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(AnvilStumpWedgeMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if AnvilStumpWedgeMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function AnvilStumpWedgeMaker.getStats() return {ironStock=AnvilStumpWedgeMaker.ironStock,bronzeStock=AnvilStumpWedgeMaker.bronzeStock,woodStock=AnvilStumpWedgeMaker.woodStock,leatherStock=AnvilStumpWedgeMaker.leatherStock,silverStock=AnvilStumpWedgeMaker.silverStock,goldStock=AnvilStumpWedgeMaker.goldStock,jewelStock=AnvilStumpWedgeMaker.jewelStock,pearlStock=AnvilStumpWedgeMaker.pearlStock,productStock=AnvilStumpWedgeMaker.productStock,numBuildings=#AnvilStumpWedgeMaker.buildings,hasMaker=AnvilStumpWedgeMaker.maker~=nil,makerName=AnvilStumpWedgeMaker.maker and AnvilStumpWedgeMaker.maker.name or "—",makerSkill=AnvilStumpWedgeMaker.maker and AnvilStumpWedgeMaker.maker.skill or 0,activeMaking=#AnvilStumpWedgeMaker.activeMaking,totalProducts=AnvilStumpWedgeMaker.totalProducts} end
return AnvilStumpWedgeMaker
