local CandlestickBaseMaker = {}
local PRODUCTS = {
    iron_candlestick_base = { name = "Železni podstavka za svečnik", ironCost = 3, woodCost = 2, leatherCost = 1, time = 5, cost = 170, prestige = 4, happiness = 2, description = "Železni podstavka za stabilne svečnike." },
    bronze_candlestick_base = { name = "Bronast podstavka za svečnik", bronzeCost = 3, ironCost = 1, woodCost = 2, leatherCost = 1, time = 7, cost = 410, prestige = 6, happiness = 3, description = "Bronast podstavka za okrasne svečnike." },
    silver_candlestick_base = { name = "Srebrni podstavka za svečnik", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 2, leatherCost = 1, time = 11, cost = 990, prestige = 11, happiness = 4, description = "Srebrni podstavka za plemiške svečnike." },
    gilded_candlestick_base = { name = "Pozlačeni podstavka za svečnik", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 15, cost = 2130, prestige = 20, happiness = 5, description = "Pozlačeni podstavka za dvorne svečnike." },
    jewel_set_candlestick_base = { name = "Draguljasti podstavka za svečnik", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 19, cost = 4600, prestige = 36, happiness = 7, description = "Draguljasti podstavka za kraljevske svečnike." },
    royal_sovereign_candlestick_base = { name = "Kraljevski suvereni podstavka za svečnik", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 3, leatherCost = 1, time = 26, cost = 9800, prestige = 69, happiness = 13, description = "Suvereni podstavka z biseri za krono." },
}
local BUILDINGS = {
    candlestickbase_workshop = { name = "Podstavkarska delavnica", cost = { gold = 340, wood = 180, stone = 135, iron = 8 }, upkeep = 6, qualityBonus = 5 },
    candlestickbase_house = { name = "Podstavkarska hiša", cost = { gold = 1220, wood = 365, stone = 275, silver = 7, iron = 7 }, upkeep = 26, qualityBonus = 18 },
    master_candlestickbase_atelier = { name = "Mojstrski podstavkarski atelje", cost = { gold = 3050, wood = 425, stone = 525, silver = 36, gold = 7 }, upkeep = 72, qualityBonus = 30 },
    sovereign_candlestickbase_palace = { name = "Suverena podstavkarska palača", cost = { gold = 13100, wood = 650, stone = 835, gold = 84, jewel = 19 }, upkeep = 257, qualityBonus = 55, prestigeBonus = 50 },
}
CandlestickBaseMaker.ironStock = 14; CandlestickBaseMaker.bronzeStock = 12; CandlestickBaseMaker.woodStock = 16; CandlestickBaseMaker.leatherStock = 8; CandlestickBaseMaker.silverStock = 8; CandlestickBaseMaker.goldStock = 6; CandlestickBaseMaker.jewelStock = 4; CandlestickBaseMaker.pearlStock = 4
CandlestickBaseMaker.productStock = {}; CandlestickBaseMaker.buildings = {}; CandlestickBaseMaker.maker = nil; CandlestickBaseMaker.activeMaking = {}; CandlestickBaseMaker.totalProducts = 0; CandlestickBaseMaker.dayTimer = 0
function CandlestickBaseMaker.init() CandlestickBaseMaker.ironStock=14; CandlestickBaseMaker.bronzeStock=12; CandlestickBaseMaker.woodStock=16; CandlestickBaseMaker.leatherStock=8; CandlestickBaseMaker.silverStock=8; CandlestickBaseMaker.goldStock=6; CandlestickBaseMaker.jewelStock=4; CandlestickBaseMaker.pearlStock=4; CandlestickBaseMaker.productStock={}; CandlestickBaseMaker.buildings={}; CandlestickBaseMaker.maker=nil; CandlestickBaseMaker.activeMaking={}; CandlestickBaseMaker.totalProducts=0; CandlestickBaseMaker.dayTimer=0; print("[CandlestickBaseMaker] Royal Candlestick Base Maker System initialized (6 products, 4 buildings)") end
function CandlestickBaseMaker.hireMaker(n,s) s=s or math.random(55,90); local c=585+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; CandlestickBaseMaker.maker={name=n or ("Podstavkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Podstavkar najet: %s (spretnost: %d)",CandlestickBaseMaker.maker.name,s),"success") end; return true end
function CandlestickBaseMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function CandlestickBaseMaker.build(id) local ok,e=CandlestickBaseMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(CandlestickBaseMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function CandlestickBaseMaker.getQualityBonus() local b=0; for _,bd in ipairs(CandlestickBaseMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function CandlestickBaseMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and CandlestickBaseMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and CandlestickBaseMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and CandlestickBaseMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and CandlestickBaseMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and CandlestickBaseMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and CandlestickBaseMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and CandlestickBaseMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and CandlestickBaseMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #CandlestickBaseMaker.buildings==0 then return false,"Potrebna podstavkarska delavnica" end; if not CandlestickBaseMaker.maker then return false,"Potreben podstavkar" end; return true end
function CandlestickBaseMaker.make(pt,qty) qty=qty or 1; local ok,e=CandlestickBaseMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then CandlestickBaseMaker.ironStock=CandlestickBaseMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then CandlestickBaseMaker.bronzeStock=CandlestickBaseMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then CandlestickBaseMaker.woodStock=CandlestickBaseMaker.woodStock-d.woodCost*qty end; if d.leatherCost then CandlestickBaseMaker.leatherStock=CandlestickBaseMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then CandlestickBaseMaker.silverStock=CandlestickBaseMaker.silverStock-d.silverCost*qty end; if d.goldCost then CandlestickBaseMaker.goldStock=CandlestickBaseMaker.goldStock-d.goldCost*qty end; if d.jewelCost then CandlestickBaseMaker.jewelStock=CandlestickBaseMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then CandlestickBaseMaker.pearlStock=CandlestickBaseMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if CandlestickBaseMaker.maker then t=math.max(1,t-math.floor(CandlestickBaseMaker.maker.skill/13)) end; table.insert(CandlestickBaseMaker.activeMaking,{id="candlestickbase_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function CandlestickBaseMaker.completeMaking(m) local q=1.0+(CandlestickBaseMaker.getQualityBonus()/100); if CandlestickBaseMaker.maker then q=q+(CandlestickBaseMaker.maker.skill/140) end; q=math.min(2.5,q); CandlestickBaseMaker.productStock[m.productType]=(CandlestickBaseMaker.productStock[m.productType] or 0)+m.quantity; CandlestickBaseMaker.totalProducts=CandlestickBaseMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if CandlestickBaseMaker.maker then CandlestickBaseMaker.maker.itemsMade=CandlestickBaseMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then CandlestickBaseMaker.maker.skill=math.min(100,CandlestickBaseMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Podstavka izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"candlestickbase.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function CandlestickBaseMaker.update(dt) if not _G.state then return end; CandlestickBaseMaker.dayTimer=CandlestickBaseMaker.dayTimer+dt; if CandlestickBaseMaker.dayTimer>=30 then CandlestickBaseMaker.dayTimer=0; for i=#CandlestickBaseMaker.activeMaking,1,-1 do local m=CandlestickBaseMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then CandlestickBaseMaker.completeMaking(m); table.remove(CandlestickBaseMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(CandlestickBaseMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if CandlestickBaseMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function CandlestickBaseMaker.getStats() return {ironStock=CandlestickBaseMaker.ironStock,bronzeStock=CandlestickBaseMaker.bronzeStock,woodStock=CandlestickBaseMaker.woodStock,leatherStock=CandlestickBaseMaker.leatherStock,silverStock=CandlestickBaseMaker.silverStock,goldStock=CandlestickBaseMaker.goldStock,jewelStock=CandlestickBaseMaker.jewelStock,pearlStock=CandlestickBaseMaker.pearlStock,productStock=CandlestickBaseMaker.productStock,numBuildings=#CandlestickBaseMaker.buildings,hasMaker=CandlestickBaseMaker.maker~=nil,makerName=CandlestickBaseMaker.maker and CandlestickBaseMaker.maker.name or "—",makerSkill=CandlestickBaseMaker.maker and CandlestickBaseMaker.maker.skill or 0,activeMaking=#CandlestickBaseMaker.activeMaking,totalProducts=CandlestickBaseMaker.totalProducts} end
return CandlestickBaseMaker
