local GlassCutterMaker = {}
local PRODUCTS = {
    iron_glass_cutter = { name = "Železni rezalec za steklo", ironCost = 3, woodCost = 1, leatherCost = 1, time = 5, cost = 170, prestige = 3, happiness = 2, description = "Železni rezalec za rezanje stekla." },
    bronze_glass_cutter = { name = "Bronast rezalec za steklo", bronzeCost = 3, ironCost = 1, woodCost = 1, leatherCost = 1, time = 7, cost = 415, prestige = 5, happiness = 3, description = "Bronast rezalec za fino steklo." },
    silver_glass_cutter = { name = "Srebrni rezalec za steklo", silverCost = 3, bronzeCost = 1, ironCost = 1, woodCost = 1, leatherCost = 1, time = 11, cost = 1000, prestige = 10, happiness = 4, description = "Srebrni rezalec za plemiške steklarje." },
    gilded_glass_cutter = { name = "Pozlačeni rezalec za steklo", goldCost = 1, silverCost = 3, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 15, cost = 2150, prestige = 19, happiness = 5, description = "Pozlačeni rezalec za dvorne steklarje." },
    jewel_set_glass_cutter = { name = "Draguljasti rezalec za steklo", goldCost = 2, silverCost = 3, jewelCost = 1, bronzeCost = 1, woodCost = 1, leatherCost = 1, time = 19, cost = 4650, prestige = 35, happiness = 7, description = "Draguljasti rezalec za kraljeve steklarje." },
    royal_sovereign_glass_cutter = { name = "Kraljevski suvereni rezalec za steklo", goldCost = 3, silverCost = 3, jewelCost = 2, pearlCost = 2, bronzeCost = 1, woodCost = 2, leatherCost = 1, time = 26, cost = 10000, prestige = 67, happiness = 13, description = "Suvereni rezalec z biseri za krono." },
}
local BUILDINGS = {
    glasscutter_workshop = { name = "Rezalna delavnica", cost = { gold = 345, wood = 170, stone = 135, iron = 9 }, upkeep = 6, qualityBonus = 5 },
    glasscutter_house = { name = "Rezalna hiša", cost = { gold = 1230, wood = 350, stone = 270, silver = 7, iron = 8 }, upkeep = 26, qualityBonus = 18 },
    master_glasscutter_atelier = { name = "Mojstrski rezalni atelje", cost = { gold = 3080, wood = 410, stone = 525, silver = 36, gold = 7 }, upkeep = 72, qualityBonus = 30 },
    sovereign_glasscutter_palace = { name = "Suverena rezalna palača", cost = { gold = 13150, wood = 630, stone = 835, gold = 84, jewel = 19 }, upkeep = 258, qualityBonus = 55, prestigeBonus = 50 },
}
GlassCutterMaker.ironStock = 14; GlassCutterMaker.bronzeStock = 12; GlassCutterMaker.woodStock = 10; GlassCutterMaker.leatherStock = 10; GlassCutterMaker.silverStock = 8; GlassCutterMaker.goldStock = 6; GlassCutterMaker.jewelStock = 4; GlassCutterMaker.pearlStock = 4
GlassCutterMaker.productStock = {}; GlassCutterMaker.buildings = {}; GlassCutterMaker.maker = nil; GlassCutterMaker.activeMaking = {}; GlassCutterMaker.totalProducts = 0; GlassCutterMaker.dayTimer = 0
function GlassCutterMaker.init() GlassCutterMaker.ironStock=14; GlassCutterMaker.bronzeStock=12; GlassCutterMaker.woodStock=10; GlassCutterMaker.leatherStock=10; GlassCutterMaker.silverStock=8; GlassCutterMaker.goldStock=6; GlassCutterMaker.jewelStock=4; GlassCutterMaker.pearlStock=4; GlassCutterMaker.productStock={}; GlassCutterMaker.buildings={}; GlassCutterMaker.maker=nil; GlassCutterMaker.activeMaking={}; GlassCutterMaker.totalProducts=0; GlassCutterMaker.dayTimer=0; print("[GlassCutterMaker] Royal Glass Cutter Maker System initialized (6 products, 4 buildings)") end
function GlassCutterMaker.hireMaker(n,s) s=s or math.random(55,90); local c=580+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; GlassCutterMaker.maker={name=n or ("Rezalec "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rezalec najet: %s (spretnost: %d)",GlassCutterMaker.maker.name,s),"success") end; return true end
function GlassCutterMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function GlassCutterMaker.build(id) local ok,e=GlassCutterMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(GlassCutterMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function GlassCutterMaker.getQualityBonus() local b=0; for _,bd in ipairs(GlassCutterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function GlassCutterMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.ironCost and GlassCutterMaker.ironStock<(d.ironCost or 0) then return false,"Premalo železa" end; if d.bronzeCost and GlassCutterMaker.bronzeStock<(d.bronzeCost or 0) then return false,"Premalo brona" end; if d.woodCost and GlassCutterMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.leatherCost and GlassCutterMaker.leatherStock<(d.leatherCost or 0) then return false,"Premalo usnja" end; if d.silverCost and GlassCutterMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and GlassCutterMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and GlassCutterMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and GlassCutterMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #GlassCutterMaker.buildings==0 then return false,"Potrebna rezalna delavnica" end; if not GlassCutterMaker.maker then return false,"Potreben rezalec" end; return true end
function GlassCutterMaker.make(pt,qty) qty=qty or 1; local ok,e=GlassCutterMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.ironCost then GlassCutterMaker.ironStock=GlassCutterMaker.ironStock-d.ironCost*qty end; if d.bronzeCost then GlassCutterMaker.bronzeStock=GlassCutterMaker.bronzeStock-d.bronzeCost*qty end; if d.woodCost then GlassCutterMaker.woodStock=GlassCutterMaker.woodStock-d.woodCost*qty end; if d.leatherCost then GlassCutterMaker.leatherStock=GlassCutterMaker.leatherStock-d.leatherCost*qty end; if d.silverCost then GlassCutterMaker.silverStock=GlassCutterMaker.silverStock-d.silverCost*qty end; if d.goldCost then GlassCutterMaker.goldStock=GlassCutterMaker.goldStock-d.goldCost*qty end; if d.jewelCost then GlassCutterMaker.jewelStock=GlassCutterMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then GlassCutterMaker.pearlStock=GlassCutterMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if GlassCutterMaker.maker then t=math.max(1,t-math.floor(GlassCutterMaker.maker.skill/13)) end; table.insert(GlassCutterMaker.activeMaking,{id="glasscutter_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,food=0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function GlassCutterMaker.completeMaking(m) local q=1.0+(GlassCutterMaker.getQualityBonus()/100); if GlassCutterMaker.maker then q=q+(GlassCutterMaker.maker.skill/140) end; q=math.min(2.5,q); GlassCutterMaker.productStock[m.productType]=(GlassCutterMaker.productStock[m.productType] or 0)+m.quantity; GlassCutterMaker.totalProducts=GlassCutterMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if GlassCutterMaker.maker then GlassCutterMaker.maker.itemsMade=GlassCutterMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then GlassCutterMaker.maker.skill=math.min(100,GlassCutterMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rezalec izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"glasscutter.completed",{productName=m.productName,prestige=m.prestige,happiness=m.happiness}) end end
function GlassCutterMaker.update(dt) if not _G.state then return end; GlassCutterMaker.dayTimer=GlassCutterMaker.dayTimer+dt; if GlassCutterMaker.dayTimer>=30 then GlassCutterMaker.dayTimer=0; for i=#GlassCutterMaker.activeMaking,1,-1 do local m=GlassCutterMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then GlassCutterMaker.completeMaking(m); table.remove(GlassCutterMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(GlassCutterMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if GlassCutterMaker.maker then tu=tu+15 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function GlassCutterMaker.getStats() return {ironStock=GlassCutterMaker.ironStock,bronzeStock=GlassCutterMaker.bronzeStock,woodStock=GlassCutterMaker.woodStock,leatherStock=GlassCutterMaker.leatherStock,silverStock=GlassCutterMaker.silverStock,goldStock=GlassCutterMaker.goldStock,jewelStock=GlassCutterMaker.jewelStock,pearlStock=GlassCutterMaker.pearlStock,productStock=GlassCutterMaker.productStock,numBuildings=#GlassCutterMaker.buildings,hasMaker=GlassCutterMaker.maker~=nil,makerName=GlassCutterMaker.maker and GlassCutterMaker.maker.name or "—",makerSkill=GlassCutterMaker.maker and GlassCutterMaker.maker.skill or 0,activeMaking=#GlassCutterMaker.activeMaking,totalProducts=GlassCutterMaker.totalProducts} end
return GlassCutterMaker
