local WoodenSpoonCarver = {}
local PRODUCTS = {
    simple_wooden_spoon = { name = "Preprosta lesena žlica", woodCost = 1, time = 2, cost = 20, culinary = 15, happiness = 1, description = "Preprosta lesena žlica za kuhinjo." },
    carved_oak_ladle = { name = "Izrezljan hrastov zajemalka", woodCost = 2, time = 4, cost = 70, culinary = 28, happiness = 1, prestige = 2, description = "Izrezljan hrastov zajemalka za trgovce." },
    silver_banded_spoon = { name = "Srebrnopasna žlica", woodCost = 2, silverCost = 1, time = 7, cost = 200, culinary = 42, happiness = 2, prestige = 5, description = "Srebrnopasna žlica za plemiče." },
    gold_trimmed_spatula = { name = "Zlatookrasni lopatica", woodCost = 2, goldCost = 1, silverCost = 1, time = 11, cost = 480, culinary = 58, happiness = 3, prestige = 13, description = "Zlatookrasni lopatica za visoke plemiče." },
    jewel_handle_carving_set = { name = "Draguljnorokavni rezilni set", woodCost = 3, goldCost = 1, silverCost = 1, jewelCost = 1, time = 15, cost = 1100, culinary = 75, happiness = 5, prestige = 26, description = "Rezilni set z draguljnim ročajem za visoko plemstvo." },
    royal_grand_wooden_set = { name = "Kraljevski veliki leseni set", woodCost = 5, goldCost = 2, silverCost = 2, jewelCost = 2, pearlCost = 2, time = 22, cost = 2800, culinary = 92, happiness = 11, prestige = 55, description = "Veliki kraljevski leseni set z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    spoon_workshop = { name = "Žličkasta delavnica", cost = { gold = 200, wood = 140, stone = 80 }, upkeep = 4, qualityBonus = 5 },
    carving_loft = { name = "Rezbarska podstrešje", cost = { gold = 780, wood = 280, stone = 220, silver = 6 }, upkeep = 18, qualityBonus = 18 },
    master_carver_atelier = { name = "Mojstrski rezbarski atelje", cost = { gold = 2300, wood = 380, stone = 480, silver = 30, gold = 6 }, upkeep = 52, qualityBonus = 30 },
    royal_carving_palace = { name = "Kraljevska rezbarska palača", cost = { gold = 9500, wood = 580, stone = 740, gold = 60, jewel = 16 }, upkeep = 190, qualityBonus = 55, prestigeBonus = 50 },
}
WoodenSpoonCarver.woodStock = 18; WoodenSpoonCarver.silverStock = 6; WoodenSpoonCarver.goldStock = 6; WoodenSpoonCarver.jewelStock = 4; WoodenSpoonCarver.pearlStock = 4
WoodenSpoonCarver.productStock = {}; WoodenSpoonCarver.buildings = {}; WoodenSpoonCarver.maker = nil; WoodenSpoonCarver.activeMaking = {}; WoodenSpoonCarver.totalProducts = 0; WoodenSpoonCarver.dayTimer = 0
function WoodenSpoonCarver.init() WoodenSpoonCarver.woodStock=18; WoodenSpoonCarver.silverStock=6; WoodenSpoonCarver.goldStock=6; WoodenSpoonCarver.jewelStock=4; WoodenSpoonCarver.pearlStock=4; WoodenSpoonCarver.productStock={}; WoodenSpoonCarver.buildings={}; WoodenSpoonCarver.maker=nil; WoodenSpoonCarver.activeMaking={}; WoodenSpoonCarver.totalProducts=0; WoodenSpoonCarver.dayTimer=0; print("[WoodenSpoonCarver] Royal Wooden Spoon Carver System initialized (6 products, 4 buildings)") end
function WoodenSpoonCarver.hireMaker(n,s) s=s or math.random(55,90); local c=440+s*11; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; WoodenSpoonCarver.maker={name=n or ("Žličkar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Žličkar najet: %s (spretnost: %d)",WoodenSpoonCarver.maker.name,s),"success") end; return true end
function WoodenSpoonCarver.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function WoodenSpoonCarver.build(id) local ok,e=WoodenSpoonCarver.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(WoodenSpoonCarver.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function WoodenSpoonCarver.getQualityBonus() local b=0; for _,bd in ipairs(WoodenSpoonCarver.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function WoodenSpoonCarver.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.woodCost and WoodenSpoonCarver.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.silverCost and WoodenSpoonCarver.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and WoodenSpoonCarver.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and WoodenSpoonCarver.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and WoodenSpoonCarver.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #WoodenSpoonCarver.buildings==0 then return false,"Potrebna žličkasta delavnica" end; if not WoodenSpoonCarver.maker then return false,"Potreben žličkar" end; return true end
function WoodenSpoonCarver.make(pt,qty) qty=qty or 1; local ok,e=WoodenSpoonCarver.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.woodCost then WoodenSpoonCarver.woodStock=WoodenSpoonCarver.woodStock-d.woodCost*qty end; if d.silverCost then WoodenSpoonCarver.silverStock=WoodenSpoonCarver.silverStock-d.silverCost*qty end; if d.goldCost then WoodenSpoonCarver.goldStock=WoodenSpoonCarver.goldStock-d.goldCost*qty end; if d.jewelCost then WoodenSpoonCarver.jewelStock=WoodenSpoonCarver.jewelStock-d.jewelCost*qty end; if d.pearlCost then WoodenSpoonCarver.pearlStock=WoodenSpoonCarver.pearlStock-d.pearlCost*qty end; local t=d.time; if WoodenSpoonCarver.maker then t=math.max(1,t-math.floor(WoodenSpoonCarver.maker.skill/14)) end; table.insert(WoodenSpoonCarver.activeMaking,{id="woodenspoon_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,culinary=d.culinary or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Rezbarjenje: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function WoodenSpoonCarver.completeMaking(m) local q=1.0+(WoodenSpoonCarver.getQualityBonus()/100); if WoodenSpoonCarver.maker then q=q+(WoodenSpoonCarver.maker.skill/150) end; q=math.min(2.4,q); WoodenSpoonCarver.productStock[m.productType]=(WoodenSpoonCarver.productStock[m.productType] or 0)+m.quantity; WoodenSpoonCarver.totalProducts=WoodenSpoonCarver.totalProducts+m.quantity; if m.culinary>0 and _G.state then _G.state.culinary=(_G.state.culinary or 0)+m.culinary end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if WoodenSpoonCarver.maker then WoodenSpoonCarver.maker.itemsMade=WoodenSpoonCarver.maker.itemsMade+m.quantity; if math.random()<0.25 then WoodenSpoonCarver.maker.skill=math.min(100,WoodenSpoonCarver.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Žlica izdelana: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"woodenspoon.completed",{productName=m.productName,culinary=m.culinary,prestige=m.prestige,happiness=m.happiness}) end end
function WoodenSpoonCarver.update(dt) if not _G.state then return end; WoodenSpoonCarver.dayTimer=WoodenSpoonCarver.dayTimer+dt; if WoodenSpoonCarver.dayTimer>=30 then WoodenSpoonCarver.dayTimer=0; for i=#WoodenSpoonCarver.activeMaking,1,-1 do local m=WoodenSpoonCarver.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then WoodenSpoonCarver.completeMaking(m); table.remove(WoodenSpoonCarver.activeMaking,i) end end; local tu=0; for _,bd in ipairs(WoodenSpoonCarver.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if WoodenSpoonCarver.maker then tu=tu+11 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function WoodenSpoonCarver.getStats() return {woodStock=WoodenSpoonCarver.woodStock,silverStock=WoodenSpoonCarver.silverStock,goldStock=WoodenSpoonCarver.goldStock,jewelStock=WoodenSpoonCarver.jewelStock,pearlStock=WoodenSpoonCarver.pearlStock,productStock=WoodenSpoonCarver.productStock,numBuildings=#WoodenSpoonCarver.buildings,hasMaker=WoodenSpoonCarver.maker~=nil,makerName=WoodenSpoonCarver.maker and WoodenSpoonCarver.maker.name or "—",makerSkill=WoodenSpoonCarver.maker and WoodenSpoonCarver.maker.skill or 0,activeMaking=#WoodenSpoonCarver.activeMaking,totalProducts=WoodenSpoonCarver.totalProducts} end
return WoodenSpoonCarver
