local QuillPenMaker = {}
local PRODUCTS = {
    goose_quill = { name = "Gosje pero", featherCost = 1, time = 1, cost = 8, quality = 40, description = "Gosje pero za pisanje." },
    swan_quill = { name = "Labodje pero", swanFeatherCost = 1, time = 2, cost = 22, quality = 55, prestige = 1, description = "Labodje pero za fine dokumente." },
    steel_nib_pen = { name = "Jekleno koničasto pero", steelCost = 1, woodCost = 1, time = 3, cost = 55, quality = 70, prestige = 3, happiness = 1, description = "Jekleno koničasto pero za trdo pisanje." },
    silver_nib_pen = { name = "Srebrno koničasto pero", silverCost = 1, woodCost = 1, time = 5, cost = 130, quality = 82, prestige = 7, happiness = 2, description = "Srebrno koničasto pero za plemiče." },
    silver_handle_pen = { name = "Srebrno ročajno pero", silverCost = 1, goldCost = 1, woodCost = 1, time = 8, cost = 320, quality = 92, prestige = 14, happiness = 3, description = "Pero s srebrnim ročajem za visoke plemiče." },
    royal_grand_pen = { name = "Kraljevski veliki pero", goldCost = 1, silverCost = 1, jewelCost = 1, pearlCost = 1, woodCost = 1, time = 13, cost = 1200, quality = 100, prestige = 33, happiness = 7, description = "Veliko kraljevsko pero z zlatom in dragulji za kronanje." },
}
local BUILDINGS = {
    workshop = { name = "Pernarska postaja", cost = { gold = 240, wood = 120, stone = 150 }, upkeep = 5, qualityBonus = 5 },
    pen_workshop = { name = "Pernarna", cost = { gold = 800, wood = 220, stone = 300, feather = 8 }, upkeep = 20, qualityBonus = 18 },
    tempering_room = { name = "Žarilnica", cost = { gold = 2000, wood = 300, stone = 600, silver = 25, steel = 8 }, upkeep = 50, qualityBonus = 30 },
    royal_quill_atelier = { name = "Kraljevski atelje peres", cost = { gold = 8200, wood = 600, stone = 900, gold = 60, jewel = 20 }, upkeep = 165, qualityBonus = 55, prestigeBonus = 40 },
}
QuillPenMaker.featherStock = 24; QuillPenMaker.swanFeatherStock = 14; QuillPenMaker.steelStock = 10; QuillPenMaker.woodStock = 14; QuillPenMaker.silverStock = 8; QuillPenMaker.goldStock = 6; QuillPenMaker.jewelStock = 6; QuillPenMaker.pearlStock = 4
QuillPenMaker.productStock = {}; QuillPenMaker.buildings = {}; QuillPenMaker.maker = nil; QuillPenMaker.activeMaking = {}; QuillPenMaker.totalProducts = 0; QuillPenMaker.dayTimer = 0
function QuillPenMaker.init() QuillPenMaker.featherStock=24; QuillPenMaker.swanFeatherStock=14; QuillPenMaker.steelStock=10; QuillPenMaker.woodStock=14; QuillPenMaker.silverStock=8; QuillPenMaker.goldStock=6; QuillPenMaker.jewelStock=6; QuillPenMaker.pearlStock=4; QuillPenMaker.productStock={}; QuillPenMaker.buildings={}; QuillPenMaker.maker=nil; QuillPenMaker.activeMaking={}; QuillPenMaker.totalProducts=0; QuillPenMaker.dayTimer=0; print("[QuillPenMaker] Royal Quill Pen Maker System initialized (6 products, 4 buildings)") end
function QuillPenMaker.hireMaker(n,s) s=s or math.random(50,90); local c=480+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; QuillPenMaker.maker={name=n or ("Pernar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pernar najet: %s (spretnost: %d)",QuillPenMaker.maker.name,s),"success") end; return true end
function QuillPenMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function QuillPenMaker.build(id) local ok,e=QuillPenMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(QuillPenMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function QuillPenMaker.getQualityBonus() local b=0; for _,bd in ipairs(QuillPenMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function QuillPenMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.featherCost and QuillPenMaker.featherStock<(d.featherCost or 0) then return false,"Premalo peres" end; if d.swanFeatherCost and QuillPenMaker.swanFeatherStock<(d.swanFeatherCost or 0) then return false,"Premalo labodjih peres" end; if d.steelCost and QuillPenMaker.steelStock<(d.steelCost or 0) then return false,"Premalo jekla" end; if d.woodCost and QuillPenMaker.woodStock<(d.woodCost or 0) then return false,"Premalo lesa" end; if d.silverCost and QuillPenMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and QuillPenMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and QuillPenMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and QuillPenMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #QuillPenMaker.buildings==0 then return false,"Potrebna delavnica" end; if not QuillPenMaker.maker then return false,"Potreben pernar" end; return true end
function QuillPenMaker.make(pt,qty) qty=qty or 5; local ok,e=QuillPenMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.featherCost then QuillPenMaker.featherStock=QuillPenMaker.featherStock-d.featherCost*qty end; if d.swanFeatherCost then QuillPenMaker.swanFeatherStock=QuillPenMaker.swanFeatherStock-d.swanFeatherCost*qty end; if d.steelCost then QuillPenMaker.steelStock=QuillPenMaker.steelStock-d.steelCost*qty end; if d.woodCost then QuillPenMaker.woodStock=QuillPenMaker.woodStock-d.woodCost*qty end; if d.silverCost then QuillPenMaker.silverStock=QuillPenMaker.silverStock-d.silverCost*qty end; if d.goldCost then QuillPenMaker.goldStock=QuillPenMaker.goldStock-d.goldCost*qty end; if d.jewelCost then QuillPenMaker.jewelStock=QuillPenMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then QuillPenMaker.pearlStock=QuillPenMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if QuillPenMaker.maker then t=math.max(1,t-math.floor(QuillPenMaker.maker.skill/12)) end; table.insert(QuillPenMaker.activeMaking,{id="quill_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,quality=d.quality or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Izdelava: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function QuillPenMaker.completeMaking(m) local q=1.0+(QuillPenMaker.getQualityBonus()/100); if QuillPenMaker.maker then q=q+(QuillPenMaker.maker.skill/180) end; q=math.min(2.0,q); QuillPenMaker.productStock[m.productType]=(QuillPenMaker.productStock[m.productType] or 0)+m.quantity; QuillPenMaker.totalProducts=QuillPenMaker.totalProducts+m.quantity; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if QuillPenMaker.maker then QuillPenMaker.maker.itemsMade=QuillPenMaker.maker.itemsMade+m.quantity; if math.random()<0.20 then QuillPenMaker.maker.skill=math.min(100,QuillPenMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Pero izdelano: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"quill.completed",{productName=m.productName,quality=m.quality}) end end
function QuillPenMaker.update(dt) if not _G.state then return end; QuillPenMaker.dayTimer=QuillPenMaker.dayTimer+dt; if QuillPenMaker.dayTimer>=30 then QuillPenMaker.dayTimer=0; for i=#QuillPenMaker.activeMaking,1,-1 do local m=QuillPenMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then QuillPenMaker.completeMaking(m); table.remove(QuillPenMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(QuillPenMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if QuillPenMaker.maker then tu=tu+13 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function QuillPenMaker.getStats() return {featherStock=QuillPenMaker.featherStock,swanFeatherStock=QuillPenMaker.swanFeatherStock,steelStock=QuillPenMaker.steelStock,woodStock=QuillPenMaker.woodStock,silverStock=QuillPenMaker.silverStock,goldStock=QuillPenMaker.goldStock,jewelStock=QuillPenMaker.jewelStock,pearlStock=QuillPenMaker.pearlStock,productStock=QuillPenMaker.productStock,numBuildings=#QuillPenMaker.buildings,hasMaker=QuillPenMaker.maker~=nil,makerName=QuillPenMaker.maker and QuillPenMaker.maker.name or "—",makerSkill=QuillPenMaker.maker and QuillPenMaker.maker.skill or 0,activeMaking=#QuillPenMaker.activeMaking,totalProducts=QuillPenMaker.totalProducts} end
return QuillPenMaker
