local AqueductMaker = {}
local PRODUCTS = {
    simple_stone_aqueduct = { name = "Preprost kamnit akvadukt", stoneCost = 5, clayCost = 2, time = 8, cost = 300, waterSupply = 40, happiness = 2, description = "Preprost kamnit akvadukt za prenos vode." },
    brick_arched_aqueduct = { name = "Opečnolokastni akvadukt", brickCost = 4, stoneCost = 3, clayCost = 2, time = 11, cost = 680, waterSupply = 60, happiness = 2, prestige = 3, description = "Opečnolokastni akvadukt za trgovce." },
    marble_faced_aqueduct = { name = "Marmornatoobložen akvadukt", marbleCost = 3, brickCost = 3, stoneCost = 2, clayCost = 2, time = 15, cost = 1500, waterSupply = 80, happiness = 3, prestige = 8, description = "Marmornatoobložen akvadukt za plemiče." },
    silver_inlaid_aqueduct = { name = "Srebrnovloženi akvadukt", marbleCost = 3, silverCost = 1, brickCost = 3, stoneCost = 2, clayCost = 2, time = 19, cost = 3400, waterSupply = 100, happiness = 4, prestige = 16, description = "Srebrnovloženi akvadukt za visoke plemiče." },
    jewel_set_aqueduct = { name = "Draguljasta akvadukt", marbleCost = 3, goldCost = 1, silverCost = 1, brickCost = 3, stoneCost = 2, clayCost = 2, jewelCost = 1, time = 23, cost = 7200, waterSupply = 125, happiness = 6, prestige = 30, description = "Akvadukt z draguljem za visoko plemstvo." },
    royal_grand_aqueduct = { name = "Kraljevski veliki akvadukt", marbleCost = 4, goldCost = 2, silverCost = 2, brickCost = 3, stoneCost = 2, clayCost = 2, jewelCost = 2, pearlCost = 2, time = 30, cost = 15000, waterSupply = 160, happiness = 13, prestige = 62, description = "Veliki kraljevski akvadukt z biseri in zlatom za kronanje." },
}
local BUILDINGS = {
    aqueduct_workshop = { name = "Akvaduktna delavnica", cost = { gold = 340, wood = 140, stone = 200, clay = 8 }, upkeep = 8, qualityBonus = 5 },
    waterworks_loft = { name = "Vodovodna podstrešje", cost = { gold = 1200, wood = 280, stone = 360, silver = 6, marble = 4 }, upkeep = 28, qualityBonus = 18 },
    master_aqueduct_atelier = { name = "Mojstrski akvaduktni atelje", cost = { gold = 3000, wood = 380, stone = 520, silver = 32, gold = 6 }, upkeep = 70, qualityBonus = 30 },
    royal_waterworks_palace = { name = "Kraljevska vodovodna palača", cost = { gold = 13000, wood = 600, stone = 800, gold = 80, jewel = 18 }, upkeep = 260, qualityBonus = 55, prestigeBonus = 50 },
}
AqueductMaker.stoneStock = 22; AqueductMaker.brickStock = 16; AqueductMaker.marbleStock = 10; AqueductMaker.clayStock = 12; AqueductMaker.silverStock = 6; AqueductMaker.goldStock = 6; AqueductMaker.jewelStock = 4; AqueductMaker.pearlStock = 4
AqueductMaker.productStock = {}; AqueductMaker.buildings = {}; AqueductMaker.maker = nil; AqueductMaker.activeMaking = {}; AqueductMaker.totalProducts = 0; AqueductMaker.dayTimer = 0
function AqueductMaker.init() AqueductMaker.stoneStock=22; AqueductMaker.brickStock=16; AqueductMaker.marbleStock=10; AqueductMaker.clayStock=12; AqueductMaker.silverStock=6; AqueductMaker.goldStock=6; AqueductMaker.jewelStock=4; AqueductMaker.pearlStock=4; AqueductMaker.productStock={}; AqueductMaker.buildings={}; AqueductMaker.maker=nil; AqueductMaker.activeMaking={}; AqueductMaker.totalProducts=0; AqueductMaker.dayTimer=0; print("[AqueductMaker] Royal Aqueduct Maker System initialized (6 products, 4 buildings)") end
function AqueductMaker.hireMaker(n,s) s=s or math.random(55,90); local c=640+s*12; if not _G.state or (_G.state.gold or 0)<c then return false,"Premalo zlata" end; _G.state.gold=_G.state.gold-c; AqueductMaker.maker={name=n or ("Akvaduktar "..math.random(1,99)),skill=s,hiredDay=os.time(),itemsMade=0}; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Akvaduktar najet: %s (spretnost: %d)",AqueductMaker.maker.name,s),"success") end; return true end
function AqueductMaker.canBuild(id) local d=BUILDINGS[id]; if not d then return false,"Neznana zgradba" end; if not _G.state then return false,"Brez stanja" end; if _G.state.gold<(d.cost.gold or 0) then return false,"Premalo zlata" end; if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" and (_G.state.resources[r] or 0)<a then return false,"Premalo "..r end end end; return true end
function AqueductMaker.build(id) local ok,e=AqueductMaker.canBuild(id); if not ok then return false,e end; local d=BUILDINGS[id]; _G.state.gold=_G.state.gold-(d.cost.gold or 0); if _G.state.resources then for r,a in pairs(d.cost) do if r~="gold" then _G.state.resources[r]=(_G.state.resources[r] or 0)-a end end end; table.insert(AqueductMaker.buildings,{type=id,builtDay=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,"Zgrajeno: "..d.name,"success") end; return true end
function AqueductMaker.getQualityBonus() local b=0; for _,bd in ipairs(AqueductMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.qualityBonus then b=b+d.qualityBonus end end; return b end
function AqueductMaker.canMake(pt) local d=PRODUCTS[pt]; if not d then return false,"Neznan produkt" end; if d.stoneCost and AqueductMaker.stoneStock<(d.stoneCost or 0) then return false,"Premalo kamna" end; if d.brickCost and AqueductMaker.brickStock<(d.brickCost or 0) then return false,"Premalo opek" end; if d.marbleCost and AqueductMaker.marbleStock<(d.marbleCost or 0) then return false,"Premalo marmorja" end; if d.clayCost and AqueductMaker.clayStock<(d.clayCost or 0) then return false,"Premalo gline" end; if d.silverCost and AqueductMaker.silverStock<(d.silverCost or 0) then return false,"Premalo srebra" end; if d.goldCost and AqueductMaker.goldStock<(d.goldCost or 0) then return false,"Premalo zlata" end; if d.jewelCost and AqueductMaker.jewelStock<(d.jewelCost or 0) then return false,"Premalo draguljev" end; if d.pearlCost and AqueductMaker.pearlStock<(d.pearlCost or 0) then return false,"Premalo biserov" end; if #AqueductMaker.buildings==0 then return false,"Potrebna akvaduktna delavnica" end; if not AqueductMaker.maker then return false,"Potreben akvaduktar" end; return true end
function AqueductMaker.make(pt,qty) qty=qty or 1; local ok,e=AqueductMaker.canMake(pt); if not ok then return false,e end; local d=PRODUCTS[pt]; if d.stoneCost then AqueductMaker.stoneStock=AqueductMaker.stoneStock-d.stoneCost*qty end; if d.brickCost then AqueductMaker.brickStock=AqueductMaker.brickStock-d.brickCost*qty end; if d.marbleCost then AqueductMaker.marbleStock=AqueductMaker.marbleStock-d.marbleCost*qty end; if d.clayCost then AqueductMaker.clayStock=AqueductMaker.clayStock-d.clayCost*qty end; if d.silverCost then AqueductMaker.silverStock=AqueductMaker.silverStock-d.silverCost*qty end; if d.goldCost then AqueductMaker.goldStock=AqueductMaker.goldStock-d.goldCost*qty end; if d.jewelCost then AqueductMaker.jewelStock=AqueductMaker.jewelStock-d.jewelCost*qty end; if d.pearlCost then AqueductMaker.pearlStock=AqueductMaker.pearlStock-d.pearlCost*qty end; local t=d.time; if AqueductMaker.maker then t=math.max(1,t-math.floor(AqueductMaker.maker.skill/12)) end; table.insert(AqueductMaker.activeMaking,{id="aqueduct_"..tostring(os.time()).."_"..tostring(math.random(1000,9999)),productType=pt,productName=d.name,cost=d.cost*qty,quantity=qty,waterSupply=d.waterSupply or 0,prestige=d.prestige or 0,happiness=d.happiness or 0,daysRemaining=t,started=os.time()}); if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Gradnja: %d %s (%d dni)",qty,d.name,t),"info") end; return true end
function AqueductMaker.completeMaking(m) local q=1.0+(AqueductMaker.getQualityBonus()/100); if AqueductMaker.maker then q=q+(AqueductMaker.maker.skill/140) end; q=math.min(2.5,q); AqueductMaker.productStock[m.productType]=(AqueductMaker.productStock[m.productType] or 0)+m.quantity; AqueductMaker.totalProducts=AqueductMaker.totalProducts+m.quantity; if m.waterSupply>0 and _G.state then _G.state.water=(_G.state.water or 0)+m.waterSupply end; if m.prestige>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.prestige) end; if m.happiness>0 and _G.state and _G.state.happiness then _G.state.happiness=math.min(100,_G.state.happiness+m.happiness) end; if AqueductMaker.maker then AqueductMaker.maker.itemsMade=AqueductMaker.maker.itemsMade+m.quantity; if math.random()<0.25 then AqueductMaker.maker.skill=math.min(100,AqueductMaker.maker.skill+1) end end; if _G.NotificationCenter then pcall(_G.NotificationCenter.notify,string.format("Akvadukt izdelan: %d %s (kakovost: %.1f)",m.quantity,m.productName,q),"success") end; if _G.GameEventBus then pcall(_G.GameEventBus.publish,"aqueduct.completed",{productName=m.productName,waterSupply=m.waterSupply,prestige=m.prestige,happiness=m.happiness}) end end
function AqueductMaker.update(dt) if not _G.state then return end; AqueductMaker.dayTimer=AqueductMaker.dayTimer+dt; if AqueductMaker.dayTimer>=30 then AqueductMaker.dayTimer=0; for i=#AqueductMaker.activeMaking,1,-1 do local m=AqueductMaker.activeMaking[i]; m.daysRemaining=m.daysRemaining-1; if m.daysRemaining<=0 then AqueductMaker.completeMaking(m); table.remove(AqueductMaker.activeMaking,i) end end; local tu=0; for _,bd in ipairs(AqueductMaker.buildings) do local d=BUILDINGS[bd.type]; if d and d.upkeep then tu=tu+d.upkeep end end; if AqueductMaker.maker then tu=tu+18 end; if tu>0 and _G.state then _G.state.gold=math.max(0,(_G.state.gold or 0)-tu) end end end
function AqueductMaker.getStats() return {stoneStock=AqueductMaker.stoneStock,brickStock=AqueductMaker.brickStock,marbleStock=AqueductMaker.marbleStock,clayStock=AqueductMaker.clayStock,silverStock=AqueductMaker.silverStock,goldStock=AqueductMaker.goldStock,jewelStock=AqueductMaker.jewelStock,pearlStock=AqueductMaker.pearlStock,productStock=AqueductMaker.productStock,numBuildings=#AqueductMaker.buildings,hasMaker=AqueductMaker.maker~=nil,makerName=AqueductMaker.maker and AqueductMaker.maker.name or "—",makerSkill=AqueductMaker.maker and AqueductMaker.maker.skill or 0,activeMaking=#AqueductMaker.activeMaking,totalProducts=AqueductMaker.totalProducts} end
return AqueductMaker
